### ISSUE TITLE
Manual post processing does not work, path error?

### ISSUE THREAD

**Issue by perara** [SickChill/SickChill#1845]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: ffcea549ea699fb27937324c8f33bd91da264ce4
OS: Ubuntu 14.04
What you did: Manual Post Processing -> Run
What happened: For some reason, "SickRage" is appended in the directory path. My path is set to "/mnt/Torrent/Sickbeard/" however SickRage appends itself to the path.
What you expected: To be able to post process correctly
Logs:

```
Error

[Errno 2] No such file or directory: '/mnt/Torrent/Sickbeard/SickRage'

Traceback

Traceback (most recent call last): 
File "/sickrage/lib/tornado/web.py", line 1415, in _execute result = yield result 
File "/sickrage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/sickrage/lib/tornado/concurrent.py", line 215, in result raise_exc_info(self._exc_info) 
File "/sickrage/lib/tornado/gen.py", line 876, in run yielded = self.gen.throw(*exc_info) 
File "/sickrage/sickbeard/webserve.py", line 254, in get results = yield self.async_call(method) 
File "/sickrage/lib/tornado/gen.py", line 870, in run value = future.result() 
File "/sickrage/lib/concurrent/futures/_base.py", line 400, in result return self.__get_result() 
File "/sickrage/lib/concurrent/futures/_base.py", line 359, in __get_result reraise(self._exception, self._traceback) 
File "/sickrage/lib/concurrent/futures/_compat.py", line 107, in reraise exec('raise exc_type, exc_value, traceback', {}, locals_) 
File "/sickrage/lib/concurrent/futures/thread.py", line 61, in run result = self.fn(*self.args, **self.kwargs) 
File "/sickrage/sickbeard/webserve.py", line 270, in async_call result = function(**kwargs) 
File "/sickrage/sickbeard/webserve.py", line 2291, in processEpisode is_priority=argToBool(is_priority), delete_on=argToBool(delete_on), failed=argToBool(failed), proc_type=proc_type 
File "/sickrage/sickbeard/processTV.py", line 290, in processDir process_media(processPath, videoFiles, nzbName, process_method, force, is_priority, result) 
File "/sickrage/sickbeard/processTV.py", line 560, in process_media result.result = processor.process() 
File "/sickrage/sickbeard/postProcessor.py", line 1027, in process if not verify_freespace(self.file_path, ep_obj.show._location, [ep_obj] + ep_obj.relatedEps, method=self.process_method): # pylint: disable=protected-access 
File "/sickrage/sickbeard/helpers.py", line 1578, in verify_freespace if method == "move" and ek(os.stat, src).st_dev == ek(os.stat, dest if ek(os.path.exists, dest) else ek(os.path.dirname, dest)).st_dev: # pylint: disable=no-member 
File "/sickrage/sickrage/helper/encoding.py", line 40, in ek result = function(*[ss(x) if isinstance(x, (str, unicode)) else x for x in args], **kwargs) 
OSError: [Errno 2] No such file or directory: '/mnt/Torrent/Sickbeard/SickRage' 

Request Info

body: proc_dir=%2Fmnt%2FTorrent%2FSickbeard&process_method=move&is_priority=on
files: {}
protocol: http
connection: 
body_arguments: {'is_priority': ['on'], 'proc_dir': ['/mnt/Torrent/Sickbeard'], 'process_method': ['move']}
uri: /home/postprocess/processEpisode
query_arguments: {}
_start_time: 1464073203.26
headers: {'Origin': 'http://sickrage.persoft.no', 'Content-Length': '72', 'Accept-Language': 'nb-NO,nb;q=0.8,no;q=0.6,nn;q=0.4,en-US;q=0.2,en;q=0.2', 'Accept-Encoding': 'gzip, deflate', 'Connection': 'close', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Upgrade-Insecure-Requests': '1', 'Host': 'torrent.hgsd.persoft.lan:8081', 'Referer': 'http://sickrage.persoft.no/home/postprocess/', 'Cache-Control': 'max-age=0', 'Cookie': '_ga=GA1.2.2070465739.1461604730; sickrage_user="2|1:0|10:1463540059|13:sickrage_user|44:YTc5YmY5MzkwM2JjMDUxNjAwYjA4ZDc0YTBhODNkN2M=|f5d6391c265cbc6fafddbc9837597a1596067801b1c36a83295c8c49f8c7f925"', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded'}
host: torrent.hgsd.persoft.lan:8081
version: HTTP/1.0
arguments: {'is_priority': 'on', 'proc_dir': '/mnt/Torrent/Sickbeard', 'process_method': 'move'}
_finish_time: None
query: 
path: /home/postprocess/processEpisode
_cookies: Set-Cookie: _ga=GA1.2.2070465739.1461604730 Set-Cookie: sickrage_user="2|1:0|10:1463540059|13:sickrage_user|44:YTc5YmY5MzkwM2JjMDUxNjAwYjA4ZDc0YTBhODNkN2M=|f5d6391c265cbc6fafddbc9837597a1596067801b1c36a83295c8c49f8c7f925"
method: POST
remote_ip: 192.168.10.26

View Log(Errors)
```

**Comment by SickRage2** [comment]
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment]
Is that mount working correctly.? If its a network drive, than maybe the connection was dropped.?
And make sure to not use special characters in the names when possible.

`OSError: [Errno 2] No such file or directory: '/mnt/Torrent/Sickbeard/SickRage' `

**Comment by perara** [comment]
Yeh mount is OK.

The thing is that i have not specified that path 
` '/mnt/Torrent/Sickbeard/SickRage'`
But in my configuration i have defined:
` '/mnt/Torrent/Sickbeard'`

**Comment by neoatomic** [comment]
Maybe you setup a custom path in/for the download client.?

**Comment by perara** [comment]
No custom path is set
This worked fine until i updated sickrage. hmmm

**Comment by neoatomic** [comment]
Do you recall from what version you did update.? Might be able to look back at the changes.

**Comment by perara** [comment]
Sadly no :( But it is between  Now and the last 30 commits

**Comment by perara** [comment]
Unless i can see which version it auto updated from?

**Comment by neoatomic** [comment]
@perara Are you using a reverse proxy.? Otherwise it might be related to this issue. : https://github.com/SickRage/SickRage/issues/1622

**Comment by perara** [comment]
I am indeed using a reverse proxy using nginx 

`
server {
        listen   80;
        server_name sickrage.xxxxx.no;
        location / {
        proxy_pass http://torrent.hgsd.persoft.lan:8081;
        }
}



`

**Comment by Naushi** [comment]
I have the same issue on my NAS, did anyone have a fix? (no reverse proxy, just Sickrage on a Synology)

**Comment by hctancredi** [comment]
I'm having the same issue and just tested with copy instead of move and worked... any news?

**Comment by hctancredi** [comment]
found out that the dir where I place my tv shows were not correct. I've migrated by base from a ubuntu standalone server to a unraid built nas. Had to manually add the correct dir and move action were back in business.
