### ISSUE TITLE
[APP SUBMITTED]: set_site_message() takes exactly 4 arguments (1 given)

### ISSUE THREAD

**Issue by Hujiin** [SickChill/SickChill#3798]
### INFO
Python Version: **2.7.13 (default, Dec 18 2016, 21:23:50) [GCC 4.6.4]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@10a0c3012e600ed61cdff6a6108b2bb55062907b
No Log available with ERRORS:
### ERROR
```
Thread-15 :: [10a0c30] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: set_site_message() takes exactly 4 arguments (1 given)

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by masonr** [comment]
I've been getting this error as well for the past couple months. After clearing it out, comes back within 10 or so minutes.

Python Version: 2.7.12
OS: Linux-4.4.0-79-generic-x86_64-with-Ubuntu-16.04-xenial 
Locale: en_US.UTF-8 
Branch: master
Commit:  96b53de

**Comment by sharkykh** [comment]
@masonr I don't know what triggers it.
The function is only called in one place, but I couldn't reproduce this issue.
Maybe this is browser-javascript related, what browser are you using?

**Comment by sharkykh** [comment]
Also, have you tried clearing the cache (reload the SickRage page with <kbd>Cmd / Ctrl + F5</kbd>? Restarting SickRage?

**Comment by sharkykh** [comment]
Well...
```
Error

set_site_message() takes exactly 4 arguments (1 given)

Traceback

Traceback (most recent call last): 
File "C:\SickRage\SickRage\lib\tornado\web.py", line 1511, in _execute result = yield result 
File "C:\SickRage\SickRage\lib\tornado\gen.py", line 1055, in run value = future.result() 
File "C:\SickRage\SickRage\lib\tornado\concurrent.py", line 238, in result raise_exc_info(self._exc_info) 
File "C:\SickRage\SickRage\lib\tornado\gen.py", line 1063, in run yielded = self.gen.throw(*exc_info) 
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 257, in get results = yield self.async_call(method) 
File "C:\SickRage\SickRage\lib\tornado\gen.py", line 1055, in run value = future.result() 
File "C:\SickRage\SickRage\lib\concurrent\futures\_base.py", line 422, in result return self.__get_result() 
File "C:\SickRage\SickRage\lib\concurrent\futures\thread.py", line 62, in run result = self.fn(*self.args, **self.kwargs) 
File "C:\SickRage\SickRage\sickbeard\webserve.py", line 273, in async_call result = function(**kwargs) 
TypeError: set_site_message() takes exactly 4 arguments (1 given) 

Request Info

body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /ui/set_site_message
query_arguments: {}
_start_time: 1497538826.84
headers: Origin: http://localhost:8081 Content-Length: 0 Accept-Language: en-US,en;q=0.8,he;q=0.6 Accept-Encoding: gzip, deflate Connection: keep-alive Accept: */* User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Host: khpc:8081 X-Requested-With: XMLHttpRequest Referer: http://localhost:8081/history/ 
host: localhost:8081
version: HTTP/1.1
server_connection: 
host_name: localhost
_finish_time: None
query: 
arguments: {}
path: /ui/set_site_message
method: POST
remote_ip: <redacted>
```

But I had to change the javascript code. Weird.

**Comment by masonr** [comment]
@sharkykh Using Firefox. Tried a hard refresh of the page (Ctrl+F5) and the error still occurs.

Let me know if you still want me to submit the error via SickRage and I'll do so.

**Comment by sharkykh** [comment]
@masonr 
I can't, for the life of me, figure out why javascript sends out an empty object.
This isn't a Python issue so logs from SickRage probably won't help me...
Tried with FF 53.0.3 and still couldn't reproduce it.

**Comment by sharkykh** [comment]
@masonr 
If this is consistent... I mean, if every time you dismiss it, then navigate to another page it pops up again then this might help me. But if not, I don't know...

Open the Firefox Developer Tools (<kbd>F12</kbd>),
go to Network tab, click <kbd>Esc</kbd>, then type `addSiteMessage()` and hit <kbd>Enter</kbd>
You should now have a new row in the list `POST set_site_message`.
If it failed it should have a purple icon to the left.
Right click the row and select `Copy as cURL` and paste it here,
then go back and click `Copy Response` and paste it here.

**Comment by masonr** [comment]
@sharkykh 

It's definitely not occurring every time it is dismissed and I navigate to a new page. Using the method above got a valid (200) response.

**Comment by dhensen** [comment]
@sharkykh 
I am running in to the same, but it is 100% reproducible for me:

```
curl 'http://emilia.local:8081/ui/set_site_message' -H 'Origin: http://emilia.local:8081' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,nl;q=0.6' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Accept: */*' -H 'Referer: http://emilia.local:8081/schedule/' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --data 'level=danger&message=' --compressed
```

```
<html>
                                 <title>set_site_message() takes exactly 4 arguments (3 given)</title>
                                 <body>
                                    <h2>Error</h2>
                                    <p>set_site_message() takes exactly 4 arguments (3 given)</p>
                                    <h2>Traceback</h2>
                                    <p>Traceback (most recent call last):
<br>  File "/sickrage/lib/tornado/web.py", line 1511, in _execute
    result = yield result
<br>  File "/sickrage/lib/tornado/gen.py", line 1055, in run
    value = future.result()
<br>  File "/sickrage/lib/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
<br>  File "/sickrage/lib/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
<br>  File "/sickrage/sickbeard/webserve.py", line 257, in get
    results = yield self.async_call(method)
<br>  File "/sickrage/lib/tornado/gen.py", line 1055, in run
    value = future.result()
<br>  File "/sickrage/lib/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
<br>  File "/sickrage/lib/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
<br>  File "/sickrage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
<br>TypeError: set_site_message() takes exactly 4 arguments (3 given)
<br></p>
                                    <h2>Request Info</h2>
                                    <p><strong>body</strong>: level=danger&message=<br><strong>files</strong>: {}<br><strong>protocol</strong>: http<br><strong>connection</strong>: <tornado.http1connection.HTTP1Connection object at 0x7f2863ccc950><br><strong>body_arguments</strong>: {'message': [''], 'level': ['danger']}<br><strong>uri</strong>: /ui/set_site_message<br><strong>query_arguments</strong>: {}<br><strong>_start_time</strong>: 1498672990.38<br><strong>headers</strong>: Origin: http://emilia.local:8081
Content-Length: 21
Accept-Language: en-US,en;q=0.8,nl;q=0.6
Accept-Encoding: gzip, deflate
Connection: keep-alive
Accept: */*
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36
Host: emilia.local:8081
X-Requested-With: XMLHttpRequest
Referer: http://emilia.local:8081/schedule/
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
<br><strong>host</strong>: emilia.local:8081<br><strong>version</strong>: HTTP/1.1<br><strong>server_connection</strong>: <tornado.http1connection.HTTP1ServerConnection object at 0x7f2863cccb50><br><strong>host_name</strong>: emilia.local<br><strong>_finish_time</strong>: None<br><strong>query</strong>: <br><strong>arguments</strong>: {'message': '', 'level': 'danger'}<br><strong>path</strong>: /ui/set_site_message<br><strong>method</strong>: POST<br><strong>remote_ip</strong>: 192.168.1.2<br></p>
                                    <button onclick="window.location='/errorlogs/';">View Log(Errors)</button>
                                 </body>
                               </html>
```

**Comment by sharkykh** [comment]
@dhensen Yours is slightly different (4 arguments, **3** given)
Restart SickRage and reset the cache in your browser (or do a hard refresh Ctrl+F5).

**Comment by dhensen** [comment]
@sharkykh thanks for the quick reply, after a day of work I look passed that! hard refresh did the trick!

**Comment by Tyrell66** [comment]
### INFO
Python Version: **2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]**
Operating System: **Linux-3.10.102-x86_64-with**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@abc6aab554715e57cf1668627a1f57f5b1ed4588
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [abc6aab] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: set_site_message() takes exactly 4 arguments (1 given)

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mikemor22** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@b3da866cadff70973fabdbb3ffbe8ad0dd208c49
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [b3da866] Failed doing webui callback: Traceback (most recent call last):
  File "C:\Applications\SickChill\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: set_site_message() takes exactly 4 arguments (1 given)

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mikemor22** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@b3da866cadff70973fabdbb3ffbe8ad0dd208c49
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [b3da866] Failed doing webui callback: Traceback (most recent call last):
  File "C:\Applications\SickChill\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: set_site_message() takes exactly 4 arguments (1 given)

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
