### ISSUE TITLE
Error starting sickrage

### ISSUE THREAD

**Issue by Patxinho** [SickChill/SickChill#3816]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Last 18/05/17
OS: Centos 7
What you did: python SickBeard.py 
What happened: Dont start Sickrage
What you expected: 
Logs:
```
Traceback (most recent call last):
  File "/.sickrage/sickbeard/__init__.py", line 36, in <module>
    import pytz  # pylint: disable=unused-import
ImportError: No module named 'pytz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SickBeard.py", line 66, in <module>
    import sickbeard
  File "/.sickrage/sickbeard/__init__.py", line 39, in <module>
    from pkg_resources import require
  File "/.sickrage/lib/pkg_resources.py", line 29
    def _bypass_ensure_directory(name, mode=0777):
                                               ^
SyntaxError: invalid token
```

**Comment by sharkykh** [comment]
What's your Python version? You should be using 2.7.10 - 2.7.13
