### ISSUE TITLE
Can't find certain UK show torrents.

### ISSUE THREAD

**Issue by GGMalone** [SickChill/SickChill#4054]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: v2017.06.05-1
OS: Synology DSM 6.1.3-15152 Update 4
What you did: Added A League of Their Own series a long time ago.
What happened: It has never found a torrent for the episodes even though I have checked and they exist. Other American based programs are being found and downloaded.
What you expected: Automatic download of current season 12.
Logs: Not sure what logs are required.
```
PASTE LOGS HERE
```

**Comment by bobbysteel** [comment]
No logs to understand, but you may want to create a scene exception for both "A League of their Own" and "A league of their own UK"

**Comment by GGMalone** [comment]
Yeah that was already in there but it didn't help. Tried all variations but it simple isn't seeing it.

**Comment by bobbysteel** [comment]
then search through the logs to see why it's not finding. either your
search providers aren't outputting or the match is failing which the logs
could help with.

**Comment by GGMalone** [comment]
Restarted Sickrage and did a manual search... This is the log from that:

2017-09-25 14:36:22 INFO SEARCHQUEUE-MANUAL-149101 :: Unable to find a download for: [A League of Their Own (2010) - S12E02 - Anthony Joshua, Mo Farah, Emma Bunton]
AA IndexError: list index out of range
AA info_hash = download_url.rsplit('/', 2)[1]
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/skytorrents.py", line 117, in search
AA items_list += self.search(search_string, ep_obj=episode)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickrage/providers/GenericProvider.py", line 154, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 480, in searchProviders
AA Traceback (most recent call last):
2017-09-25 14:36:22 ERROR SEARCHQUEUE-MANUAL-149101 :: [SkyTorrents] :: [d8c2613] Exception while searching SkyTorrents. Error: IndexError('list index out of range',)
2017-09-25 14:36:21 INFO SEARCHQUEUE-MANUAL-149101 :: [SkyTorrents] :: Performing episode search for A League of Their Own (2010)
2017-09-25 14:36:21 INFO SEARCHQUEUE-MANUAL-149101 :: [LimeTorrents] :: Performing season pack search for A League of Their Own (2010)
2017-09-25 14:36:19 INFO SEARCHQUEUE-MANUAL-149101 :: [LimeTorrents] :: Performing episode search for A League of Their Own (2010)
2017-09-25 14:36:19 INFO SEARCHQUEUE-MANUAL-149101 :: [ThePirateBay] :: Performing season pack search for A League of Their Own (2010)
2017-09-25 14:36:18 INFO SEARCHQUEUE-MANUAL-149101 :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Read timed out. (read timeout=30)
2017-09-25 14:35:48 INFO SEARCHQUEUE-MANUAL-149101 :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Read timed out. (read timeout=30)
2017-09-25 14:35:17 INFO SEARCHQUEUE-MANUAL-149101 :: [ThePirateBay] :: Request failed: HTTPSConnectionPool(host='thepiratebay.org', port=443): Read timed out. (read timeout=30)
2017-09-25 14:34:45 INFO SEARCHQUEUE-MANUAL-149101 :: [ThePirateBay] :: Performing episode search for A League of Their Own (2010)
2017-09-25 14:34:40 INFO SEARCHQUEUE-MANUAL-149101 :: Beginning manual search for: [A League of Their Own (2010) - S12E02 - Anthony Joshua, Mo Farah, Emma Bunton]
2017-09-25 14:33:58 INFO TORNADO :: Starting SickRage on http://0.0.0.0:8083/
2017-09-25 14:33:58 INFO MAIN :: Starting SickRage [master] using '/usr/local/sickbeard-custom/var/config.ini'
2017-09-25 14:33:58 INFO MAIN :: Writing PID: 14964 to /usr/local/sickbeard-custom/var/sickbeard-custom.pid

**Comment by bobbysteel** [comment]
it doesn't seem that there's a valid result anywhere. your search on piratebay is failing (due to blocking by your ISP if you're in the UK). your search on skytorrents is erroring due to a bug in that particular provider (see other bug I recall opened for that) and limetorrents doesn't seem to be returning a result of the quality you're asking for (or at all)

**Comment by GGMalone** [comment]
I use a VPN but admittedly it is connecting to a UK location so I'll try and change that to a non UK location and see if that fixes piratebay. With regard to skytorrents, is there plans to fix that provider? The reason I ask is that site is my number 1 go to site and is what I'm basing my statements of finding valid torrents on.

**Comment by bobbysteel** [comment]
skytorrents was fixed Aug 6 but it hasn't been merged into the master branch yet. https://github.com/SickRage/SickRage/commit/073a7e1e5c4f785ee51089649bfbb2d3f8f9db5e

you can manually copy those files into your config as a hack, or switch to the devel branch (although I've had weirdness with it and switched back myself). dunno why the master updates have stopped tbh.

**Comment by GGMalone** [comment]
Who does the merges?

**Comment by GGMalone** [comment]
Hi bobbysteel,

Has there been any news on the skytorrents fix being merged in the master branch?

**Comment by bobbysteel** [comment]
No looking like no merges since August I'm afraid.

**Comment by OmgImAlexis** [comment]
@bobbysteel this should already be fixed in https://github.com/SickRage/SickRage/pull/3946/files

If you need something merge quickly please just ping me and I'll look into it. We do keep an eye on issues and such we're all just very busy right now.

**Comment by bobbysteel** [comment]
I think he was just asking about merges into master. I'm fine w/ cherry
picks of my own ;)

**Comment by GGMalone** [comment]
@OmgImAlexis Unfortunately this has not been fixed from my version running on a Synology NAS.

These are the errors I receive:

2017-10-27 15:46:25 SEARCHQUEUE-MANUAL-78901 :: [SkyTorrents] :: [d8c2613] Exception while searching SkyTorrents. Error: IndexError('list index out of range',)
