### ISSUE TITLE
BTFailure: not a valid bencoded string

### ISSUE THREAD

**Issue by jangrewe** [SickChill/SickChill#4126]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / d8c2613583ce8b321a5adc9ff70c52e830f224a8
OS: Debian 9 (stretch)
What you did: Searched for a torrent
What happened: A torrent was found via Cardigann, but couldn't be added to deluge
What you expected: The torrent to be added to deluge
Logs:
```
AA . Error not a valid bencoded string
AA Release Group: None
AA Size: 155520000
AA Name: SomeExampleTorrent.WEB-DL.x264.AAC
AA Quality: SDTV
AA status: 3
AA hastbn: False
AA hasnfo: False
AA airdate: 736634 (datetime.date(2017, 11, 1))
AA subtitles_lastsearch: '0001-01-01 00:00:00'
AA subtitles_searchcount: 0
AA subtitles: u''
AA description: u'Some text here.'
AA location: u''
AA u'Some Example' - S1E1 - u'Torrent'
AA Episodes:
AA Extra Info:
2017-11-07 21:54:06 DEBUG    SEARCHQUEUE-MANUAL-95011 :: DelugeD: Exception raised when sending torrent: Cardigann @ http://localhost:9088/download/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsIjoiaHR0cHM6Ly9teWxpbmsuc3Qvci5waHA_dXJsPW1hZ25ldCUzQSUzRnh0JTNEdXJuJTNBYnRpaCUzQWJlM2UyNzJlZmFjYmRmYTMwMDFhYzkzOTY5NTk0ODY2NDA5MGExMzglMjZkbiUzRE1vZGVybi5GYW1pbHkuUzA5RTA2LlRlbi5ZZWFycy5MYXRlci5BTVpOLldFQi1ETC54MjY0LkFBQyUyNnRyJTNEdWRwJTI1M0ElMjUyRiUyNTJGdHJhY2tlci5sZWVjaGVycy1wYXJhZGlzZS5vcmclMjUzQTY5NjklMjZ0ciUzRHVkcCUyNTNBJTI1MkYlMjUyRnplcjBkYXkuY2glMjUzQTEzMzclMjZ0ciUzRHVkcCUyNTNBJTI1MkYlMjUyRm9wZW4uZGVtb25paS5jb20lMjUzQTEzMzclMjZ0ciUzRHVkcCUyNTNBJTI1MkYlMjUyRnRyYWNrZXIuY29wcGVyc3VyZmVyLnRrJTI1M0E2OTY5JTI2dHIlM0R1ZHAlMjUzQSUyNTJGJTI1MkZleG9kdXMuZGVzeW5jLmNvbSUyNTNBNjk2OSIsIm5iZiI6MTUxMDA4ODA0MywicyI6ImtpY2thc3N0b3JyZW50In0.cclNsj-UAjJi6ViucF7VI0nYzjI4hNJQgJFSFR_CuKE/SomeExampleTorrent.WEB-DL.x264.AAC.torrent
AA BTFailure: not a valid bencoded string
AA raise BTFailure("not a valid bencoded string")
AA File "/opt/sickrage/lib/bencode/__init__.py", line 68, in bdecode
AA torrent_bdecode = bencode.bdecode(result.content)
AA File "/opt/sickrage/sickbeard/clients/generic.py", line 215, in _get_torrent_hash
AA result = self._get_torrent_hash(result)
AA File "/opt/sickrage/sickbeard/clients/generic.py", line 257, in sendTORRENT
AA Traceback (most recent call last):
2017-11-07 21:54:06 ERROR    SEARCHQUEUE-MANUAL-95011 :: [d8c2613] DelugeD: Failed Sending Torrent
2017-11-07 21:54:06 DEBUG    SEARCHQUEUE-MANUAL-95011 :: Error is: not a valid bencoded string
AA BTFailure: not a valid bencoded string
AA raise BTFailure("not a valid bencoded string")
AA File "/opt/sickrage/lib/bencode/__init__.py", line 68, in bdecode
AA torrent_bdecode = bencode.bdecode(result.content)
AA File "/opt/sickrage/sickbeard/clients/generic.py", line 215, in _get_torrent_hash
AA Traceback (most recent call last):
2017-11-07 21:54:06 ERROR    SEARCHQUEUE-MANUAL-95011 :: [d8c2613] Unable to bdecode torrent
2017-11-07 21:54:06 DEBUG    SEARCHQUEUE-MANUAL-95011 :: Calling DelugeD Client
2017-11-07 21:54:06 DEBUG    SEARCHQUEUE-MANUAL-95011 :: GET URL: http://localhost:9088/download/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsIjoiaHR0cHM6Ly9teWxpbmsuc3Qvci5waHA_dXJsPW1hZ25ldCUzQSUzRnh0JTNEdXJuJTNBYnRpaCUzQWJlM2UyNzJlZmFjYmRmYTMwMDFhYzkzOTY5NTk0ODY2NDA5MGExMzglMjZkbiUzRE1vZGVybi5GYW1pbHkuUzA5RTA2LlRlbi5ZZWFycy5MYXRlci5BTVpOLldFQi1ETC54MjY0LkFBQyUyNnRyJTNEdWRwJTI1M0ElMjUyRiUyNTJGdHJhY2tlci5sZWVjaGVycy1wYXJhZGlzZS5vcmclMjUzQTY5NjklMjZ0ciUzRHVkcCUyNTNBJTI1MkYlMjUyRnplcjBkYXkuY2glMjUzQTEzMzclMjZ0ciUzRHVkcCUyNTNBJTI1MkYlMjUyRm9wZW4uZGVtb25paS5jb20lMjUzQTEzMzclMjZ0ciUzRHVkcCUyNTNBJTI1MkYlMjUyRnRyYWNrZXIuY29wcGVyc3VyZmVyLnRrJTI1M0E2OTY5JTI2dHIlM0R1ZHAlMjUzQSUyNTJGJTI1MkZleG9kdXMuZGVzeW5jLmNvbSUyNTNBNjk2OSIsIm5iZiI6MTUxMDA4ODA0MywicyI6ImtpY2thc3N0b3JyZW50In0.cclNsj-UAjJi6ViucF7VI0nYzjI4hNJQgJFSFR_CuKE/SomeExampleTorrent.WEB-DL.x264.AAC.torrent [Status: 200]
2017-11-07 21:54:05 INFO     SEARCHQUEUE-MANUAL-95011 :: Downloading SomeExampleTorrent.WEB-DL.x264.AAC from Cardigann
2017-11-07 21:54:05 DEBUG    SEARCHQUEUE-MANUAL-95011 :: [Cardigann] :: Checking if we should keep searching after we've found SomeExampleTorrent.WEB-DL.x264.AAC
2017-11-07 21:54:05 DEBUG    SEARCHQUEUE-MANUAL-95011 :: [Cardigann] :: Picked SomeExampleTorrent.WEB-DL.x264.AAC as the best
```

**Comment by cico971** [comment]
I Have the same issue

**Comment by Floyonal** [comment]
Same issue for me, after checking the log, it's been 2 days SR doesn't download anything.
Transmission on Qnap TS-251

**Comment by bderenzo** [comment]
I have the same issue since the last update... :(

**Comment by antipiot** [comment]
same issue here too: 
opened an issue aswell here: 
https://github.com/SickRage/SickRage/issues/4705

**Comment by rousseldenis** [comment]
Same issue here.

**Comment by kestrator** [comment]
same issue too

**Comment by neo62248** [comment]
Hello, 

same issue here. It exists from months. Not enough to do some thing, really? 

Regards,
