### ISSUE TITLE
exception in issue submitter

### ISSUE THREAD

**Issue by core-code** [SickChill/SickChill#4179]
2017-12-06 14:09:27 WARNING Thread-14 :: Exception generated in issue submitter, please check the log AA IndexError: tuple index out of range AA regex = r'^({0})\s+([A-Z]+)\s+[A-Za-z0-9\-\[\] :]+::\s(?:\[[\w]{7}\]).*$'.format(re.escape(cur_error.time)) AA File "/Users/xxx/Downloads/SickRage/sickbeard/logger.py", line 325, in submit_errors AA Traceback (most recent call last): AA IndexError: tuple index out of range AA regex = r'^({0})\s+([A-Z]+)\s+[A-Za-z0-9\-\[\] :]+::\s(?:\[[\w]{7}\]).*$'.format(re.escape(cur_error.time)) AA File "/Users/xxx/Downloads/SickRage/sickbeard/logger.py", line 325, in submit_errors 2017-12-06 14:09:27 ERROR Thread-14 :: [d8c2613] Traceback (most recent call last):

**Comment by nmbchaves** [comment]
2017-12-07 15:35:14 Thread-14 :: [d8c2613] Traceback (most recent call last):
File "/opt/sickrage/sickbeard/logger.py", line 325, in submit_errors
regex = r'^({0})\s+([A-Z]+)\s+[A-Za-z0-9\-\[\] :]+::\s(?:\[[\w]{7}\]).*$'.format(re.escape(cur_error.time))
IndexError: tuple index out of range
