### ISSUE TITLE
MTV - backlog searching for season packs not working

### ISSUE THREAD

**Issue by soapy01** [SickChill/SickChill#4233]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 4b69468cc1ea330f598364718068352a54b0eb92
Version: v2017.12.19-1
Database Version: 44.0
OS: Linux-3.10.102-x86_64-with-glibc2.2.5 Synology DS916
What you did: Searched via backlog for a season pack on MTV
What happened: Threw an error and didn't find anything, this is only with backlog searching. If I add a new series from scratch, it searches and snatches the season pack without a problem. I have checked the following boxes at Provider options.
Enable daily searches
Enable backlog searches
Season search mode: Season packs only
Enable fallback

I tried various combinations with above settings but no difference there: it only throws error if i backlog search for season packs.

What you expected: To snatch a season pack with a backlog search.

Logs:

ERROR LOG:
2018-01-04 22:11:56 SEARCHQUEUE-BACKLOG-298901 :: [MoreThanTV] :: [4b69468] Exception while searching MoreThanTV. Error: AttributeError("'NoneType' object has no attribute 'group'",)

LOG FILE
2018-01-04 22:11:56 INFO     SEARCHQUEUE-BACKLOG-298901 :: No needed episodes found during backlog search for: [NAMEOFSERIES]
2018-01-04 22:11:56 INFO     SEARCHQUEUE-BACKLOG-298901 :: [MoreThanTV] :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
AA AttributeError: 'NoneType' object has no attribute 'group'
AA searchedSeason = re.match('.*\s(Season\s\d+|S\d+)', search_string).group(1)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/morethantv.py", line 133, in search
AA items_list += self.search(search_string, ep_obj=episode)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickrage/providers/GenericProvider.py", line 155, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 475, in searchProviders
AA AttributeError: 'NoneType' object has no attribute 'group'
AA searchedSeason = re.match('.*\s(Season\s\d+|S\d+)', search_string).group(1)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/morethantv.py", line 133, in search
AA items_list += self.search(search_string, ep_obj=episode)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickrage/providers/GenericProvider.py", line 155, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 475, in searchProviders
AA Traceback (most recent call last):
2018-01-04 22:11:56 ERROR    SEARCHQUEUE-BACKLOG-298901 :: [MoreThanTV] :: [4b69468] Exception while searching MoreThanTV. Error: AttributeError("'NoneType' object has no attribute 'group'",)
2018-01-04 22:11:56 INFO     SEARCHQUEUE-BACKLOG-298901 :: [MoreThanTV] :: Performing season pack search for NAMEOFSERIES
2018-01-04 22:11:56 INFO     SEARCHQUEUE-BACKLOG-298901 :: Beginning backlog search for: [NAMEOFSERIES]
2018-01-04 22:11:55 INFO     Thread-14 :: Sending backlog for NAMEOFSERIES season 2 because some eps were set to wanted

**Comment by DrAlphabet** [comment]
Having a similar issue

**Comment by soapy01** [comment]
I changed to docker and I no longer have issues with MTV. Don't know why. But for me, this is no longer a issue.

soap

**Comment by soapy01** [comment]
actually, this is still an issue at my other synology diskstation 416play. I ran in to the same problem so i decided to make the switch as well to a docker container. But there i have the same problem. Running docker or not :(
