### ISSUE TITLE
when I execute sickrage I get this error

### ISSUE THREAD

**Issue by Valyester** [SickChill/SickChill#4292]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Debian 9 GNU/Linux
What you did:when I execute sickrage I get this error, i don't know why the console get this error, i try install with this [manual](https://www.htpcguides.com/install-sickrage-ubuntu-14-04/) and it don't start,
thanks
What happened: sickrage don't start
What you expected:
Logs:
```
root@HTPC:/opt/sickrage# python /opt/sickrage/SickBeard.py -d
Traceback (most recent call last):
  File "/opt/sickrage/SickBeard.py", line 69, in <module>
    import sickbeard
  File "/opt/sickrage/sickbeard/__init__.py", line 34, in <module>
    import requests
  File "/opt/sickrage/lib/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/opt/sickrage/lib/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

```

**Comment by maru3l** [comment]
I'm getting exactly the same issue.

**Comment by benyjr** [comment]
I am also getting this same error.

**Comment by WebSpider** [comment]
This is caused by a bug in your installed version of pyopenssl. Please upgrade/reinstall pyopenssl, for instance by executing ```apt-get purge pyopenssl && apt-get install pyopenssl```
