### ISSUE TITLE
[APP SUBMITTED]: unexpected unindent (viewlogs.mako.py, line 99)

### ISSUE THREAD

**Issue by grandboricua** [SickChill/SickChill#4450]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [9783c5f] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 5391, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 115, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickRage\SickRage\lib\mako\lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "C:\SickRage\SickRage\lib\mako\lookup.py", line 323, in _load
    **self.template_args)
  File "C:\SickRage\SickRage\lib\mako\template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\SickRage\lib\mako\template.py", line 396, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\SickRage\lib\mako\compat.py", line 90, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickRage\Data\cache\mako\viewlogs.mako.py", line 99
    
    ^
IndentationError: unexpected unindent

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by gotoman00** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [a760263] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 5391, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 115, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickRage\SickRage\lib\mako\lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "C:\SickRage\SickRage\lib\mako\lookup.py", line 323, in _load
    **self.template_args)
  File "C:\SickRage\SickRage\lib\mako\template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\SickRage\lib\mako\template.py", line 396, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\SickRage\lib\mako\compat.py", line 90, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickRage\Data\cache\mako\viewlogs.mako.py", line 99
    
    ^
IndentationError: unexpected unindent

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by titomontes** [comment]
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.16299**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [a760263] Failed doing webui callback: Traceback (most recent call last):
  File "C:\Program Files\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\Program Files\SickRage\sickbeard\webserve.py", line 5391, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "C:\Program Files\SickRage\sickbeard\webserve.py", line 115, in __init__
    self.template = lookup.get_template(filename)
  File "C:\Program Files\SickRage\lib\mako\lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "C:\Program Files\SickRage\lib\mako\lookup.py", line 323, in _load
    **self.template_args)
  File "C:\Program Files\SickRage\lib\mako\template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\Program Files\SickRage\lib\mako\template.py", line 396, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\Program Files\SickRage\lib\mako\compat.py", line 90, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\Program Files\SickRage\cache\mako\viewlogs.mako.py", line 99
    
    ^
IndentationError: unexpected unindent

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by hzqtaegp** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [5a9a634] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 5283, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 115, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickRage\SickRage\lib\mako\lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "C:\SickRage\SickRage\lib\mako\lookup.py", line 323, in _load
    **self.template_args)
  File "C:\SickRage\SickRage\lib\mako\template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\SickRage\lib\mako\template.py", line 396, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\SickRage\lib\mako\compat.py", line 90, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickRage\SickRage\cache\mako\viewlogs.mako.py", line 99
    
    ^
IndentationError: unexpected unindent

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by glenviewjeff** [comment]
Me too, after a migration from Sickrage to Sickchill.

2019-05-05 08:40:44 ThreadPoolExecutor-0_0 :: [b3da866] Failed doing webui callback: Traceback (most recent call last):
File "C:\SickChill\SickChill\sickbeard\webserve.py", line 287, in async_call
result = function(**kwargs)
File "C:\SickChill\SickChill\sickbeard\webserve.py", line 5268, in viewlog
t = PageTemplate(rh=self, filename="viewlogs.mako")
File "C:\SickChill\SickChill\sickbeard\webserve.py", line 114, in __init__
self.template = lookup.get_template(filename)
File "C:\SickChill\SickChill\lib\mako\lookup.py", line 258, in get_template
return self._load(srcfile, uri)
File "C:\SickChill\SickChill\lib\mako\lookup.py", line 323, in _load
**self.template_args)
File "C:\SickChill\SickChill\lib\mako\template.py", line 338, in __init__
module = self._compile_from_file(path, filename)
File "C:\SickChill\SickChill\lib\mako\template.py", line 396, in _compile_from_file
module = compat.load_module(self.module_id, path)
File "C:\SickChill\SickChill\lib\mako\compat.py", line 90, in load_module
return imp.load_source(module_id, path, fp)
File "C:\SickChill\Data\cache\mako\viewlogs.mako.py", line 99

^
IndentationError: unexpected unindent

2019-05-05 08:40:44 ThreadPoolExecutor-0_1 :: [b3da866] Failed doing webui callback: Traceback (most recent call last):
File "C:\SickChill\SickChill\sickbeard\webserve.py", line 287, in async_call
result = function(**kwargs)
File "C:\SickChill\SickChill\sickbeard\webserve.py", line 5268, in viewlog
t = PageTemplate(rh=self, filename="viewlogs.mako")
File "C:\SickChill\SickChill\sickbeard\webserve.py", line 114, in __init__
self.template = lookup.get_template(filename)
File "C:\SickChill\SickChill\lib\mako\lookup.py", line 258, in get_template
return self._load(srcfile, uri)
File "C:\SickChill\SickChill\lib\mako\lookup.py", line 323, in _load
**self.template_args)
File "C:\SickChill\SickChill\lib\mako\template.py", line 338, in __init__
module = self._compile_from_file(path, filename)
File "C:\SickChill\SickChill\lib\mako\template.py", line 396, in _compile_from_file
module = compat.load_module(self.module_id, path)
File "C:\SickChill\SickChill\lib\mako\compat.py", line 90, in load_module
return imp.load_source(module_id, path, fp)
File "C:\SickChill\Data\cache\mako\viewlogs.mako.py", line 99

^
IndentationError: unexpected unindent

**Comment by ming1981** [comment]
### INFO
Python Version: **2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [f7a113a] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 5268, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 114, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickRage\lib\mako\lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "C:\SickRage\lib\mako\lookup.py", line 323, in _load
    **self.template_args)
  File "C:\SickRage\lib\mako\template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 396, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 90, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickRage\cache\mako\viewlogs.mako.py", line 99
    
    ^
IndentationError: unexpected unindent

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by jpenberthy** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@9ae2c845db7315015ae07f3f486661a62947a288
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [9ae2c84] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickChill\SickChill\sickbeard\webserve.py", line 5287, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "C:\SickChill\SickChill\sickbeard\webserve.py", line 114, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 323, in _load
    **self.template_args)
  File "C:\SickChill\SickChill\lib\mako\template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickChill\SickChill\lib\mako\template.py", line 396, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickChill\SickChill\lib\mako\compat.py", line 90, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickChill\Data\cache\mako\viewlogs.mako.py", line 99
    
    ^
IndentationError: unexpected unindent

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cepelkey** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17134**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@09207fe0680c8a8fd7b9b93127f28b62b6de3732
Link to Log: https://gist.github.com/51d2ff887d87addd75d894ea22f780e7
### ERROR
```
WEBSERVER-ERRORLOGS :: [09207fe] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickchill\views\index.py", line 178, in async_call
    result = function(**kwargs)
  File "C:\SickChill\SickChill\sickchill\views\logs.py", line 94, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "C:\SickChill\SickChill\sickchill\views\common.py", line 64, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 260, in get_template
    return self._load(srcfile, uri)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 327, in _load
    **self.template_args
  File "C:\SickChill\SickChill\lib\mako\template.py", line 347, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickChill\SickChill\lib\mako\template.py", line 415, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickChill\SickChill\lib\mako\compat.py", line 103, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickChill\Data\gui\slick\cache\mako\viewlogs.mako.py", line 99
    
    ^
IndentationError: unexpected unindent

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by dd30fragbait** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@5daf9c65e418611df376a9604565494bf748384a
Link to Log: https://gist.github.com/955af8ecf49a068769baa41fa07d4385
### ERROR
```
WEBSERVER-ERRORLOGS :: [5daf9c6] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickchill\views\index.py", line 216, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickchill\views\logs.py", line 94, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "C:\SickRage\sickchill\views\common.py", line 64, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickRage\lib\mako\lookup.py", line 260, in get_template
    return self._load(srcfile, uri)
  File "C:\SickRage\lib\mako\lookup.py", line 327, in _load
    **self.template_args
  File "C:\SickRage\lib\mako\template.py", line 348, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 416, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 114, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickRage\gui\slick\cache\mako\viewlogs.mako.py", line 99
    
    ^
IndentationError: unexpected unindent

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by dd30fragbait** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@a2dc606824280455182dd7806fe070be7cfe0930
Link to Log: https://gist.github.com/99fbd5bc4a790be72bb8e3209d1dffec
### ERROR
```
WEBSERVER-ERRORLOGS :: [a2dc606] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickchill\views\index.py", line 216, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickchill\views\logs.py", line 94, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "C:\SickRage\sickchill\views\common.py", line 64, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickRage\lib\mako\lookup.py", line 260, in get_template
    return self._load(srcfile, uri)
  File "C:\SickRage\lib\mako\lookup.py", line 327, in _load
    **self.template_args
  File "C:\SickRage\lib\mako\template.py", line 348, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 416, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 114, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickRage\gui\slick\cache\mako\viewlogs.mako.py", line 99
    
    ^
IndentationError: unexpected unindent

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by dd30fragbait** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@3e12397aa1e0e125752e46a629fba4f56dcdc1ab
Link to Log: https://gist.github.com/42ab8c9580f50331986bc9aeb393ecfe
### ERROR
```
WEBSERVER-ERRORLOGS :: [3e12397] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickchill\views\index.py", line 216, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickchill\views\logs.py", line 94, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "C:\SickRage\sickchill\views\common.py", line 64, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickRage\lib\mako\lookup.py", line 260, in get_template
    return self._load(srcfile, uri)
  File "C:\SickRage\lib\mako\lookup.py", line 327, in _load
    **self.template_args
  File "C:\SickRage\lib\mako\template.py", line 348, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 416, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 114, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickRage\gui\slick\cache\mako\viewlogs.mako.py", line 99
    
    ^
IndentationError: unexpected unindent

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by dd30fragbait** [comment]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@c5ed827b40693bd481417845e37ff2622cd6ab8a
Link to Log: https://gist.github.com/6c7b03a3139f4ccde475bef6f41af726
### ERROR
```
WEBSERVER-ERRORLOGS :: [c5ed827] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickchill\views\index.py", line 216, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickchill\views\logs.py", line 94, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "C:\SickRage\sickchill\views\common.py", line 64, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickRage\lib\mako\lookup.py", line 260, in get_template
    return self._load(srcfile, uri)
  File "C:\SickRage\lib\mako\lookup.py", line 327, in _load
    **self.template_args
  File "C:\SickRage\lib\mako\template.py", line 348, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 416, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 114, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickRage\gui\slick\cache\mako\viewlogs.mako.py", line 99
    
    ^
IndentationError: unexpected unindent

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
