### ISSUE TITLE
[APP SUBMITTED]: 404 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Not Found'}

### ISSUE THREAD

**Issue by aidopotato** [SickChill/SickChill#4547]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@9783c5f4de5d600d249705ce230cca53a9169f65
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [9783c5f] Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/logger.py", line 335, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickrage.log': InputFileContent(paste_data)})
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Not Found'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by scarygary** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@a7602639bd525f27475f1eeb2fc504111a14b51c
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [a760263] Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/logger.py", line 335, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickrage.log': InputFileContent(paste_data)})
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Not Found'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ravensorb** [comment]
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-11.0-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@807c5ae37ecd5af7483f06459c94788ee9db483d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_4 :: [807c5ae] Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/logger.py", line 335, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickrage.log': InputFileContent(paste_data)})
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Not Found'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by ryanjnacht** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012Server-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@b3da866cadff70973fabdbb3ffbe8ad0dd208c49
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [b3da866] Traceback (most recent call last):
  File "C:\SickRage\sickbeard\logger.py", line 335, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickchill.log': InputFileContent(paste_data)})
  File "C:\SickRage\lib\github\AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "C:\SickRage\lib\github\Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickRage\lib\github\Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Not Found'}

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mshuflin** [comment]
### INFO
Python Version: **2.7.16 (default, Apr  6 2019, 01:42:57) [GCC 8.2.0]**
Operating System: **Linux-4.19.66-v7+-armv7l-with-debian-10.1**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@2404f197697602a2bbfa8e6b39207229a94d37bb
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_2 :: [2404f19] Traceback (most recent call last):
  File "/opt/sickchill/sickbeard/logger.py", line 335, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickchill.log': InputFileContent(paste_data)})
  File "/opt/sickchill/lib/github/AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "/opt/sickchill/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/opt/sickchill/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Not Found'}

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
