### ISSUE TITLE
[APP SUBMITTED]: execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by Thilas** [SickChill/SickChill#4671]
### INFO
Python Version: **2.7.12 (default, Mar 22 2018, 06:58:41) [GCC 4.9.3 20150311 (prerelease)]**
Operating System: **Linux-3.2.40-armv7l-with-glibc2.4**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5a9a634bc8af642c13a41b01affabbe96d9564dd
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [5a9a634] Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@sickrage/sickrage/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/volume1/@sickrage/sickrage/sickbeard/webserve.py", line 2997, in addNewShow
    dir_exists = helpers.makeDir(show_dir)
  File "/volume1/@sickrage/sickrage/sickbeard/helpers.py", line 286, in makeDir
    sickbeard.notifiers.synoindex_notifier.addFolder(path)
  File "/volume1/@sickrage/sickrage/sickbeard/notifiers/synoindex.py", line 72, in addFolder
    self.makeObject('-A', cur_path)
  File "/volume1/@sickrage/sickrage/sickbeard/notifiers/synoindex.py", line 87, in makeObject
    cwd=sickbeard.PROG_DIR)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Thilas** [comment]
In order to reproduce this issue, I just tried to add a show from theTVDB with french metadata and using its french name: "Un village français".
