### ISSUE TITLE
AA BTFailure: not a valid bencoded string

### ISSUE THREAD

**Issue by antipiot** [SickChill/SickChill#4705]
Hello :-)

Since some days, maybe after latest updates, my sickrage doesn't download anymore:
I tried another torrent provider: same error.
Tried to send to blackhole: Getting error: Could not download "URL" -  could not download eny result
Deluge works perfectly.
Sickrage is up to date and no config change has benn made frm a while.

Tried downloading from Torrent 9 and yggtorrent aswell without success

Seems a lot to be sickrage related:

`AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/opt/sickbeard/sickbeard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/opt/sickbeard/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA result = self._get_torrent_hash(result)
AA File "/opt/sickbeard/sickbeard/clients/generic.py", line 259, in sendTORRENT
AA Traceback (most recent call last):
2018-05-16 21:18:23 ERROR    SEARCHQUEUE-MANUAL-322399 :: [5a9a634] Deluge: Failed Sending Torrent
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/opt/sickbeard/sickbeard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/opt/sickbeard/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA Traceback (most recent call last):
2018-05-16 21:18:23 ERROR    SEARCHQUEUE-MANUAL-322399 :: [5a9a634] Unable to bdecode torrent
2018-05-16 21:18:23 INFO     SEARCHQUEUE-MANUAL-322399 :: Downloading Genius.S02E04.FRENCH.HDTV.x264-Torrent9 from Torrent9
2018-05-16 21:18:23 INFO     SEARCHQUEUE-MANUAL-322399 :: [Torrent9] :: Quality of Genius.S02E04.FRENCH.HDTV.x264-Torrent9 is SDTV
2018-05-16 21:18:23 INFO     SEARCHQUEUE-MANUAL-322399 :: [Torrent9] :: Found result Genius.S02E04.FRENCH.HDTV.x264-Torrent9 at http://www.torrent9.red/get_torrent/genius-s02e04-french-hdtv.torrent
2018-05-16 21:18:22 INFO     SEARCHQUEUE-MANUAL-322399 :: [Torrent9] :: Performing episode search for Genius`

Another with debug enabled:
`AA . Error not a valid bencoded string
AA Release Group: Torrent9
AA Size: -1
AA Name: Genius.S02E04.FRENCH.HDTV.x264-Torrent9
AA Quality: SDTV
AA status: 104
AA hastbn: False
AA hasnfo: False
AA airdate: 736822 (datetime.date(2018, 5, 8))
AA subtitles_lastsearch: '0001-01-01 00:00:00'
AA subtitles_searchcount: 0
AA subtitles: u''
AA description: u"Alors que Picasso jongle entre deux relations amoureuses, le jeunePablo s'efforce de cr\xe9er un chef-d'\u0153uvre qui marquera son arriv\xe9e en tant que grand artiste."
AA location: u'/srv/dev-disk-by-label-Volume1/share/videos/series/Genius/Season 02/Genius - S02E04 - Chapitre quatre.avi'
AA u'Genius' - S2E4 - u'Chapitre quatre'
AA Episodes:
AA Extra Info:
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/opt/sickbeard/sickbeard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/opt/sickbeard/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA result = self._get_torrent_hash(result)
AA File "/opt/sickbeard/sickbeard/clients/generic.py", line 259, in sendTORRENT
AA Traceback (most recent call last):
2018-05-18 17:05:52 ERROR    SEARCHQUEUE-MANUAL-322399 :: [5a9a634] Deluge: Failed Sending Torrent
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/opt/sickbeard/sickbeard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/opt/sickbeard/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA Traceback (most recent call last)`

**Comment by cico971** [comment]
Same issue with transmission on synology ds415play

**Comment by antipiot** [comment]
Nobody else? issue persist.

Not even a work-around?

**Comment by rdehouss** [comment]
Same issue here as well

**Comment by kestrator** [comment]
Same issue here as well, please help me

**Comment by antipiot** [comment]
Issue Persist:
Always present with Yggtorrent but depends for yggtorrent: A reboot of sickrage and the torrent download is correctly send:
`2018-05-31 07:24:39 INFO     SEARCHQUEUE-MANUAL-296762 :: Downloading Westworld.S02E01.VOSTFR.PROPER.720p.AMZN.WEB-DL.DDP5.1.H.264-exPM5 from YggTorrent
2018-05-31 07:24:39 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Release: Westworld.S02E01.REPACK.FRENCH.720p.WEB.H264-GODSPACE doesn't contain any of multi, vostfr, ignoring it
2018-05-31 07:24:39 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Quality of Westworld.S02E01.REPACK.FRENCH.720p.WEB.H264-GODSPACE is 720p WEB-DL
2018-05-31 07:24:39 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Quality of Westworld.S02E01.(VOSTFR.720p.WEBRip.x265.NSP) is 720p WEB-DL
2018-05-31 07:24:39 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Release: Westworld.S02E01.FRENCH.720p.AMZN.WEB-DL.DD5.1.H264-FRATERNiTY doesn't contain any of multi, vostfr, ignoring it
2018-05-31 07:24:39 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Quality of Westworld.S02E01.FRENCH.720p.AMZN.WEB-DL.DD5.1.H264-FRATERNiTY is 720p WEB-DL
2018-05-31 07:24:39 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Quality of Westworld.S02E01.VOSTFR.PROPER.720p.AMZN.WEB-DL.DDP5.1.H.264-exPM5 is 720p WEB-DL
2018-05-31 07:24:37 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Performing episode search for Westworld
2018-05-31 07:24:37 INFO     SEARCHQUEUE-MANUAL-296762 :: Beginning manual search for: [Westworld - S02E01 - Journey Into Night]
2018-05-31 07:24:27 INFO     CHECKVERSION :: Checking for updates using GIT
2018-05-31 07:24:27 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2018-05-31 07:24:27 INFO     MAIN :: Starting SickRage [master] using '/config/config.ini'
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Shutting down Tornado
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Saving config file to disk
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Saving all shows to the database
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2018-05-31 07:24:19 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2018-05-31 07:24:18 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2018-05-31 07:24:18 INFO     EVENT-QUEUE :: Aborting all threads
2018-05-31 07:24:18 INFO     MAIN :: Signal 15 caught, saving and exiting...
2018-05-31 07:24:15 INFO     CHECKVERSION :: Checking for updates using GIT
2018-05-31 07:24:15 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2018-05-31 07:24:15 INFO     MAIN :: Starting SickRage [master] using '/config/config.ini'
2018-05-31 07:24:00 INFO     EVENT-QUEUE :: Saving all shows to the database
2018-05-31 07:24:00 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2018-05-31 07:24:00 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2018-05-31 07:24:00 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2018-05-31 07:24:00 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2018-05-31 07:24:00 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR-AUTO thread to exit
2018-05-31 07:24:00 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2018-05-31 07:24:00 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE-MANUAL-296762 thread to exit
2018-05-31 07:24:00 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE-REFRESH thread to exit
2018-05-31 07:24:00 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2018-05-31 07:24:00 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2018-05-31 07:24:00 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2018-05-31 07:23:59 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2018-05-31 07:23:59 INFO     EVENT-QUEUE :: Aborting all threads
2018-05-31 07:23:59 INFO     MAIN :: Signal 15 caught, saving and exiting...
AA . Error not a valid bencoded string
AA Release Group: exPM5
AA Size: -1
AA Name: Westworld.S02E01.VOSTFR.PROPER.720p.AMZN.WEB-DL.DDP5.1.H.264-exPM5
AA Quality: 720p WEB-DL
AA status: 3209
AA hastbn: False
AA hasnfo: False
AA airdate: 736806 (datetime.date(2018, 4, 22))
AA subtitles_lastsearch: '0001-01-01 00:00:00'
AA subtitles_searchcount: 0
AA subtitles: u''
AA description: u'Wyatt, Maeve, and the other hosts pursue their respective new goals. The Delos corporation sends its security forces in to combat the rebellion.'
AA location: u'/tv/Westworld/Season 02/Westworld - S02E01 - Journey Into Night.mkv'
AA u'Westworld' - S2E1 - u'Journey Into Night'
AA Episodes:
AA Extra Info:
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/app/sickrage/sickbeard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/app/sickrage/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA result = self._get_torrent_hash(result)
AA File "/app/sickrage/sickbeard/clients/generic.py", line 259, in sendTORRENT
AA Traceback (most recent call last):
2018-05-31 07:23:22 ERROR    SEARCHQUEUE-MANUAL-296762 :: [5a9a634] Deluge: Failed Sending Torrent
AA BTFailure: not a valid bencoded string
AA raise bencode.BTL.BTFailure("not a valid bencoded string")
AA File "/app/sickrage/sickbeard/helpers.py", line 1935, in bdecode
AA torrent_bdecode = helpers.bdecode(result.content, True)
AA File "/app/sickrage/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
AA Traceback (most recent call last):
2018-05-31 07:23:21 ERROR    SEARCHQUEUE-MANUAL-296762 :: [5a9a634] Unable to bdecode torrent
2018-05-31 07:23:21 INFO     SEARCHQUEUE-MANUAL-296762 :: Downloading Westworld.S02E01.VOSTFR.PROPER.720p.AMZN.WEB-DL.DDP5.1.H.264-exPM5 from YggTorrent
2018-05-31 07:23:21 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Release: Westworld.S02E01.REPACK.FRENCH.720p.WEB.H264-GODSPACE doesn't contain any of multi, vostfr, ignoring it
2018-05-31 07:23:21 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Quality of Westworld.S02E01.REPACK.FRENCH.720p.WEB.H264-GODSPACE is 720p WEB-DL
2018-05-31 07:23:21 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Quality of Westworld.S02E01.(VOSTFR.720p.WEBRip.x265.NSP) is 720p WEB-DL
2018-05-31 07:23:21 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Release: Westworld.S02E01.FRENCH.720p.AMZN.WEB-DL.DD5.1.H264-FRATERNiTY doesn't contain any of multi, vostfr, ignoring it
2018-05-31 07:23:21 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Quality of Westworld.S02E01.FRENCH.720p.AMZN.WEB-DL.DD5.1.H264-FRATERNiTY is 720p WEB-DL
2018-05-31 07:23:21 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Quality of Westworld.S02E01.VOSTFR.PROPER.720p.AMZN.WEB-DL.DDP5.1.H.264-exPM5 is 720p WEB-DL
2018-05-31 07:23:03 INFO     SEARCHQUEUE-MANUAL-296762 :: [YggTorrent] :: Performing episode search for Westworld
2018-05-31 07:23:03 INFO     SEARCHQUEUE-MANUAL-296762 :: Beginning manual search for: [Westworld - S02E01 - Journey Into Night]
2018-05-31 07:22:51 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2018-05-31 07:22:48 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes`

**Comment by neo62248** [comment]
Same issue here. UP

The last log is pretty the same than I could give. It is about Yggtorrent and the daily search. 
Maybe you could do something about a problem that exists from months now? 

Thanks
