### ISSUE TITLE
Unable to bdecode torrent.... 

### ISSUE THREAD

**Issue by neo62248** [SickChill/SickChill#4768]
Hello, 

Again and again, this error prevents Download Station from taking new torrents. What is going on? Why is this bug not a priority? It's blocking. No download possible.
Please take into account the requests for this problem as soon as possible please.

Regards,

**Comment by neo62248** [comment]
Her's a fresh stacktrace : 

2018-06-13 23:20:10 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Fear.The.Walking.Dead.S04E08.FRENCH.BluRay.720p.HDTV.x264-Torrent9 from Torrent9
2018-06-13 23:20:10 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: GET URL: http://www.torrent9.red/get_torrent/fear-the-walking-dead-s04e08-french-bluray-720p-hdtv.torrent [Status: 301]
2018-06-13 23:20:10 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: GET URL: http://www.torrent9.ec/get_torrent/fear-the-walking-dead-s04e08-french-bluray-720p-hdtv.torrent [Status: 301]
2018-06-13 23:20:10 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: GET URL: http://www.torrent9.ec/top_torrent.php [Status: 200]
2018-06-13 23:20:10 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Calling DownloadStation Client
2018-06-13 23:20:10 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [9392379] Unable to bdecode torrent
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
    torrent_bdecode = helpers.bdecode(result.content, True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1935, in bdecode
    raise bencode.BTL.BTFailure("not a valid bencoded string")
BTFailure: not a valid bencoded string
2018-06-13 23:20:10 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Error is: not a valid bencoded string
2018-06-13 23:20:10 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [9392379] DownloadStation: Failed Sending Torrent
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 259, in sendTORRENT
    result = self._get_torrent_hash(result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
    torrent_bdecode = helpers.bdecode(result.content, True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1935, in bdecode
    raise bencode.BTL.BTFailure("not a valid bencoded string")
BTFailure: not a valid bencoded string
2018-06-13 23:20:10 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: DownloadStation: Exception raised when sending torrent: Torrent9 @ http://www.torrent9.red/get_torrent/fear-the-walking-dead-s04e08-french-bluray-720p-hdtv.torrent
Extra Info:
Episodes:
 u'Fear the Walking Dead' - S4E8 - u'Personne n\u2019est parti'
location: u''
description: u'Madison fights to preserve the life she worked so hard to build. Morgan tries to do the right thing.'
subtitles: u''
subtitles_searchcount: 0
subtitles_lastsearch: '0001-01-01 00:00:00'
airdate: 736855 (datetime.date(2018, 6, 10))
hasnfo: False
hastbn: False
status: 3

Quality: 720p BluRay
Name: Fear.The.Walking.Dead.S04E08.FRENCH.BluRay.720p.HDTV.x264-Torrent9
Size: -1
Release Group: Torrent9
. Error not a valid bencoded string
2018-06-13 23:20:12 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading Westworld.S02E06.FRENCH.HDTV.x264-Torrent9 from Torrent9
2018-06-13 23:20:12 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: GET URL: http://www.torrent9.red/get_torrent/westworld-s02e06-french-hdtv.torrent [Status: 301]
2018-06-13 23:20:12 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: GET URL: http://www.torrent9.ec/get_torrent/westworld-s02e06-french-hdtv.torrent [Status: 301]
2018-06-13 23:20:12 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: GET URL: http://www.torrent9.ec/top_torrent.php [Status: 200]
2018-06-13 23:20:12 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Calling DownloadStation Client
2018-06-13 23:20:13 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [9392379] Unable to bdecode torrent
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
    torrent_bdecode = helpers.bdecode(result.content, True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1935, in bdecode
    raise bencode.BTL.BTFailure("not a valid bencoded string")
BTFailure: not a valid bencoded string
2018-06-13 23:20:13 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Error is: not a valid bencoded string
2018-06-13 23:20:13 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [9392379] DownloadStation: Failed Sending Torrent
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 259, in sendTORRENT
    result = self._get_torrent_hash(result)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/clients/generic.py", line 216, in _get_torrent_hash
    torrent_bdecode = helpers.bdecode(result.content, True)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1935, in bdecode
    raise bencode.BTL.BTFailure("not a valid bencoded string")
BTFailure: not a valid bencoded string
2018-06-13 23:20:13 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: DownloadStation: Exception raised when sending torrent: Torrent9 @ http://www.torrent9.red/get_torrent/westworld-s02e06-french-hdtv.torrent
Extra Info:
Episodes:
 u'Westworld' - S2E6 - u'Espace des phases'
location: u''
description: u'Nous m\xe9ritons chacun de choisir notre propre destin.\nTeddy prend conscience que son code a \xe9t\xe9 modifi\xe9 par Dolores, il est maintenant plus agressif et moins empathique. Bernard et Elsie se retrouvent confront\xe9s \xe0 de nouvelles difficult\xe9s au c\u0153ur du laboratoire secret.'
subtitles: u''
subtitles_searchcount: 0
subtitles_lastsearch: '0001-01-01 00:00:00'
airdate: 736841 (datetime.date(2018, 5, 27))
hasnfo: False
hastbn: False
status: 3

Quality: SDTV
Name: Westworld.S02E06.FRENCH.HDTV.x264-Torrent9
Size: -1
Release Group: Torrent9
. Error not a valid bencoded string

**Comment by neo62248** [comment]
Please note that removing cache.db does not resolve anything.

**Comment by neodavid13fr** [comment]
same here with torrent9

**Comment by neo62248** [comment]
Hello, 
this is not a problem for me anymore. I found a solution on my own. 
Bye

**Comment by LaurentDes** [comment]
yes share please

**Comment by neo62248** [comment]
Maybe Sickrage devs could do their job first and work to reduce number of issues ? .... 


I discovered that the login in YGGTORRENT wasn't effective in Sickrage bot, but my login/pass were good. 

I first disabled the function which validate the torrent file (where the bdecode error is).
Then I tried to snatch episodes and let Sickrage put my torrent files in a "black hole" directory (I changed my setting in Search Strings / Torrent Search -> Send .torrent files to: Black hole). I choosed a directory which is not empty by my torrent client to get the torrent files downloaded by SR.  
My directory full of torrent files, I just opened one with a code editor, I saw an invalid torrent file because the login for Yggtorrent didn't work (my file contained only "Please login to download torrents"). 

The solution is : verify your credentials for provider in SR (login/pass OK)
After, stop your SickRage.
Go to yggtorrent.py in sources and change url to ww1.yggtorrent.is (and not yggtorrent.is). Devs are too slow to change that -- I recommand to put a field in SR provider config to let users change urls when they want.... 
The best is to verify in all sources it doesn't exit another url yggtorrent.is to change in ww1.yggtorrent.is.
Then restart SickRage (after compiling your yggtorrent.py source with python) 
Retry to snatch and go to your black hole directory, and open on torrent file to see if it is good one.
Then change in SR config the black hole to go to a directory which is empty by your torrent client, to download videos files. 

That's all

**Comment by LaurentDes** [comment]
how do you make change in .py files on synology ?

thanks for you help

**Comment by neo62248** [comment]
You can use putty in a PC to access your Syno in ssh. I do that. 
Go to your synology config (in DSM), activate ssh via Terminal and SNMP. You can put an ssh port, default is 22.
Download putty, launch it and in the putty window u enter you syno IP (local) and ssh port, then it opens a console window, just enter login / pass and you're connected. 
After it is a search about unix commands and vi and so on... I let you search the Internet to do that.

**Comment by danpilch** [comment]
@neo62248 stop whining and fix the issue yourself if you're going to bitch about it. Let me guess though, you don't possess the skills to do so.

Open source developers work in their free time they're not here to serve you.

**Comment by neo62248** [comment]
@danpilch  you don't know my capacities, ofc I can fix issues, and I do. My SR is correctly downloading since days and I won't wait about a team which is not so reactive. 
Since I posted my issue, 18 more issues went on top of the stack. And no response, like mine.... I can't tell it is efficient support. Maybe dev team is not as big to take in charge so many problems. 
I'm mad about this project because I know that if you have problem, you will wait for a very long time to see its resolution....

**Comment by neo62248** [comment]
We have 6-7 issues opened for months and about the same problem I opened for.... think about it

**Comment by neodavid13fr** [comment]
@neo62248 I don't understand your solution .. you talk to us about a problem with Torrent9 bdecode torrent and you post a solution with Yggtorrent login issue ...  
Have you fix your torrent9 bdecode issue ?
thanks

**Comment by neo62248** [comment]
I use YggTorrent only now. I can see if my solution works for Torrent9. I would do the same debug processing to test it.

**Comment by neodavid13fr** [comment]
I have try the same solution for torrent9 too (change url) but it doesn't work

**Comment by neo62248** [comment]
I will take a look later. 
You know, I don't have to answer the problems here, not like the developers working on this project. If they did their job on time, everything would be better. And I did not force anyone to create Sickrage, but it needs to be maintained.

**Comment by djoole** [comment]
@neo62248 stop complaining, and make a PR instead... like that #4800 (took me a few sec)
