### ISSUE TITLE
[APP SUBMITTED]: 401 {u'documentation_url': u'https://developer.github.com/v3/issues/comments/#create-a-comment', u'message': u'Requires authentication'}

### ISSUE THREAD

**Issue by stewartpriest** [SickChill/SickChill#4769]
### INFO
Python Version: **2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]**
Operating System: **Linux-4.2.0-27-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@93923792e8908427344d6e01de968656cf096626
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [9392379] Traceback (most recent call last):
  File "/home/stewart/.sickrage/sickbeard/logger.py", line 392, in submit_errors
    if report.create_comment(message):
  File "/home/stewart/.sickrage/lib/github/Issue.py", line 276, in create_comment
    input=post_parameters
  File "/home/stewart/.sickrage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/home/stewart/.sickrage/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 401 {u'documentation_url': u'https://developer.github.com/v3/issues/comments/#create-a-comment', u'message': u'Requires authentication'}

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mitch71h** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [e094759] Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\logger.py", line 392, in submit_errors
    if report.create_comment(message):
  File "C:\SickChill\SickChill\lib\github\Issue.py", line 276, in create_comment
    input=post_parameters
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 401 {u'documentation_url': u'https://developer.github.com/v3/issues/comments/#create-a-comment', u'message': u'Requires authentication'}

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by mitch71h** [comment]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [e094759] Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\logger.py", line 392, in submit_errors
    if report.create_comment(message):
  File "C:\SickChill\SickChill\lib\github\Issue.py", line 276, in create_comment
    input=post_parameters
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
GithubException: 401 {u'documentation_url': u'https://developer.github.com/v3/issues/comments/#create-a-comment', u'message': u'Requires authentication'}

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
