### ISSUE TITLE
2018-06-16 14:16:20 ThreadPoolExecutor-0_2 :: [807c5ae] Failed doing webui callback: Traceback (most recent call last):

### ISSUE THREAD

**Issue by ebaydan777** [SickChill/SickChill#4783]
2018-06-16 14:16:20 ThreadPoolExecutor-0_2 :: [807c5ae] Failed doing webui callback: Traceback (most recent call last):
File "/app/sickrage/sickbeard/webserve.py", line 288, in async_call
result = function(**kwargs)
File "/app/sickrage/sickbeard/webserve.py", line 2483, in processEpisode
process_path = ss(kwargs.get('dir', xhtml_unescape(proc_dir)) or '')
File "/app/sickrage/lib/tornado/escape.py", line 68, in xhtml_unescape
return re.sub(r"&(#?)(\w+?);", _convert_entity, _unicode(value))
File "/usr/lib/python2.7/re.py", line 155, in sub
return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

```
SABNZBD Logs:

[14:16:19] [INFO]::MAIN: Loading config from [/config/nzbToMedia/autoProcessMedia.cfg]
[14:16:19] [INFO]::MAIN: Checking database structure...
[14:16:19] [INFO]::MAIN: Checking if git needs an update
[14:16:19] [ERROR]::MAIN: Unable to determine installed version via git, please check your logs!
[14:16:19] [INFO]::MAIN: No update needed
[14:16:19] [INFO]::MAIN: nzbToMedia Version:10.12 Branch:master (Linux 4.4.59+)
[14:16:19] [WARNING]::MAIN: Failed to locate ffmpeg. Transcoding disabled!
[14:16:19] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[14:16:19] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
[14:16:19] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature  ...
[14:16:19] [INFO]::MAIN: #########################################################
[14:16:19] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
[14:16:19] [INFO]::MAIN: #########################################################
[14:16:19] [INFO]::MAIN: Script triggered from SABnzbd 0.7.17+
[14:16:19] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[14:16:19] [INFO]::MAIN: Calling SickBeard:tv to post-process:Americas.Got.Talent.S13E03.1080p.Netflix.WEB-DL.DD5.1.x264.1-TrollHD-Obfuscated.nzb
[14:16:20] [INFO]::MAIN: SickBeard:tv fork set to sickrage
[14:16:20] [INFO]::MAIN: FLATTEN: Flattening directory: /downloads/Temp/Americas.Got.Talent.S13E03.1080p.Netflix.WEB-DL.DD5.1.x264.1-TrollHD-Obfuscated
[14:16:20] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
[14:16:20] [ERROR]::SICKBEARD: Server returned status 500
[14:16:20] [ERROR]::MAIN: A problem was reported in the /config/nzbToMedia/nzbToSickBeard.py script.
SickBeard: Failed to post-process - Server returned status 500!
```

**Comment by brentavery** [comment]
I'm getting the same error, using nzbget with nzbToMedia

**Comment by MichelRabozee** [comment]
Sorry, I have no experience with a docker container. I found some tutorial how to edit a file inside it:
https://ligerlearn.com/how-to-edit-files-within-docker-containers/

If you are uncomfortable with those manipulations, I suppose the best is to wait for the new update which should come quite quickly.

**Comment by gauth-fr** [comment]
> as a quick fix (until this is better fixed by capable people), you may edit webserve.py:
set line 2483 to:
process_path = ss(kwargs.get('dir', proc_dir) or '')

Thanks

 it works as a temp fix waiting for an update ;)

**Comment by charlie460** [comment]
I am getting the same error as well. Thank you for the temporary fix.
