### ISSUE TITLE
Error deleting TV Show with 's in name

### ISSUE THREAD

**Issue by IamC8** [SickChill/SickChill#4838]
### Before submitting your issue:

The 's was seen as a separate command?

Branch/Commit: Master/0e727649748ec38c5bba69f3f97c9e7b794d56df
OS: Ubuntu 16.04
Browser: Chrome
What you did: Delete TV show
What happened: Error in logs
What you expected: Show to be deleted
Logs:
```
2018-07-22 13:06:22 INFO SHOWQUEUE-REMOVE-SHOW :: Here is the arguments that were passed to this function (This is what the developers need to know): {'fetchall': True, 'attempt': 0, 'severity': 40, 'self': , 'args': [295760], 'sql_results': [], 'query': u"SELECT location from tv_shows WHERE location LIKE '/data/Sickrage/DC's Legends of Tomorrow%' AND indexer_id != ?", 'e': OperationalError('near "s": syntax error',), 'fetchone': False}
2018-07-22 13:06:22 INFO SHOWQUEUE-REMOVE-SHOW :: If this happened in cache.db, you can safely stop SickRage, and delete the cache.db file without losing any data
AA OperationalError: near "s": syntax error
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/opt/sickrage/sickbeard/db.py", line 141, in _execute
AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA File "/opt/sickrage/sickbeard/db.py", line 283, in action
AA Traceback (most recent call last):
2018-07-22 13:06:22 ERROR SHOWQUEUE-REMOVE-SHOW :: [0e72764] Fatal error executing query with db.action in database /opt/sickrage/sickbeard.db: near "s": syntax error
2018-07-22 13:06:22 INFO SHOWQUEUE-REMOVE-SHOW :: Attempt to delete show folder /data/Sickrage/DC's Legends of Tomorrow
```

**Comment by miigotu** [comment]
Fixed in b8070c99c23bfdfedd05e1b9b34d4643e50313af
