### ISSUE TITLE
[APP SUBMITTED]: [Errno 2] No such file or directory: '/config/cache/mako/tmpD1DZ1p'

### ISSUE THREAD

**Issue by Zabanya** [SickChill/SickChill#4842]
### INFO
Python Version: **2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]**
Operating System: **Linux-4.9.87-linuxkit-aufs-x86_64-with**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@0e727649748ec38c5bba69f3f97c9e7b794d56df
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [0e72764] Failed doing webui callback: Traceback (most recent call last):
  File "/app/sickrage/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/app/sickrage/sickbeard/webserve.py", line 490, in schedule
    t = PageTemplate(rh=self, filename='schedule.mako')
  File "/app/sickrage/sickbeard/webserve.py", line 115, in __init__
    self.template = lookup.get_template(filename)
  File "/app/sickrage/lib/mako/lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "/app/sickrage/lib/mako/lookup.py", line 323, in _load
    **self.template_args)
  File "/app/sickrage/lib/mako/template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "/app/sickrage/lib/mako/template.py", line 395, in _compile_from_file
    self.module_writer)
  File "/app/sickrage/lib/mako/template.py", line 731, in _compile_module_file
    (dest, name) = tempfile.mkstemp(dir=os.path.dirname(outputpath))
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/config/cache/mako/tmpD1DZ1p'

```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by WebSpider** [comment]
It appears the container doesn't have the needed directory layout for the cache files.
