### ISSUE TITLE
ValueError: field 6 out of range (need a 48-bit value)

### ISSUE THREAD

**Issue by Vidanez** [SickChill/SickChill#4846]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: MacOS
Browser: None
What you did: reboot the host
What happened: I cant boot sickrage anymore
What you expected: 
Logs:
```
Mediaserver:SickRage root# python --version
Python 2.7.15
Mediaserver:SickRage root# ./SickBeard.py &
[1] 49055
Mediaserver:SickRage root# Traceback (most recent call last):
  File "./SickBeard.py", line 69, in <module>
    import sickbeard
  File "/usr/local/Cellar/SickRage/sickbeard/__init__.py", line 46, in <module>
    from sickbeard import (auto_postprocessor, dailysearcher, db, helpers, logger, metadata, naming, post_processing_queue, properFinder, providers, scheduler,
  File "/usr/local/Cellar/SickRage/sickbeard/dailysearcher.py", line 27, in <module>
    from sickbeard import common, db, logger, network_timezones
  File "/usr/local/Cellar/SickRage/sickbeard/common.py", line 51, in <module>
    INSTANCE_ID = str(uuid.uuid1())
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)

[1]+  Done(1)                 ./SickBeard.py
Mediaserver:SickRage root# 
Mediaserver:~ root# pip list
Package      Version  
------------ ---------
asn1crypto   0.24.0   
certifi      2018.4.16
cffi         1.11.5   
cfscrape     1.9.5    
chardet      3.0.4    
cryptography 2.3      
enum34       1.1.6    
idna         2.7      
ipaddress    1.0.22   
pip          18.0     
pycparser    2.18     
PyExecJS     1.5.1    
pyOpenSSL    18.0.0   
requests     2.19.1   
setuptools   40.0.0   
six          1.11.0   
urllib3      1.23     
wheel        0.31.1  



```

**Comment by Vidanez** [comment]
Mediaserver:~ root# pip list
Package      Version  
------------ ---------
asn1crypto   0.24.0   
certifi      2018.4.16
cffi         1.11.5   
cfscrape     1.9.5    
chardet      3.0.4    
cryptography 2.3      
enum34       1.1.6    
idna         2.7      
ipaddress    1.0.22   
pip          18.0     
pycparser    2.18     
PyExecJS     1.5.1    
pyOpenSSL    18.0.0   
requests     2.19.1   
setuptools   40.0.0   
six          1.11.0   
urllib3      1.23     
wheel        0.31.1

**Comment by WebSpider** [comment]
Please update your python version.
