### ISSUE TITLE
HTTP error 405: Method not allowed on API post

### ISSUE THREAD

**Issue by markheloking** [SickChill/SickChill#4985]
### Before submitting your issue:

Branch/Commit: **51328d1fb61ebc9704934e3cf14425453196790d**
OS: **Windows-10-10.0.17763**
Browser: **Google Chrome 69.0.3497.100 64-bit**
What you did: **Webcall to the API using Postman (because the NzbToMedia script kept failing and I wanted to know why, the script made the same request and it failed similarly as well)**
What happened: **I got a traceback to `HTTPError: HTTP 405: Method Not Allowed`**
What you expected: **Sickrage to processes the actual postprocess request**
Logs: **There was actually no mention of any of the requests or errors in the logs (with debug logging on), I was only able to get the error as a response to the API post call itself:**

```
Traceback (most recent call last):
  File "C:\Program Files\SickRage\lib\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:\Program Files\SickRage\lib\tornado\web.py", line 227, in post
    raise HTTPError(405)
HTTPError: HTTP 405: Method Not Allowed
```

The API call I made was this (POST request):
```
http://localhost:8082/api/*APIKEY*/?cmd=postprocess
```

With POST header:
```
Key: Content-Type, Value: application/json
```

With POST body:
```
{'nzbName': 'The.Expanse.S02E13.1080p.BluRay.x264-ROVERS.nzb', 'quiet': 1, 'failed': '0', 'force_next': 1, 'proc_dir': 'D:\\Downloads\\Sabnzbd\\ToParse'}
```

This POST request I grabbed from the debug logging of NzbToMedia as an example of what it tried to call to find out why it didn't work.

**Comment by markheloking** [comment]
Not sure what the issue was. It's working on latest version of SickRage (although autodetection from nzbToMedia is still broken, just set it to `sickrage-api`).
