### ISSUE TITLE
libpthread.so error on freebsd 11.2

### ISSUE THREAD

**Issue by lokipo** [SickChill/SickChill#5069]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/latest
OS: freebsd 11.2
Browser: safari 12
What you did: start sickchill
What happened: got an error in log
What you expected: not to get an error :-)
Logs:
```
2018-10-15 11:47:13 ERROR    MAIN :: [d019c54] There was an error creating the show in /some/folder/some tvshow: Error Shared object "libpthread.so.0" not found, required by "etree.so"
Traceback (most recent call last):
  File "/usr/local/SickRage/SickBeard.py", line 418, in load_shows_from_db
    cur_show = TVShow(sql_show[b'indexer'], sql_show[b'indexer_id'])
  File "/usr/local/SickRage/sickbeard/tv.py", line 111, in __init__
    self.loadFromDB()
  File "/usr/local/SickRage/sickbeard/tv.py", line 813, in loadFromDB
    self.loadIMDbInfo()
  File "/usr/local/SickRage/sickbeard/tv.py", line 899, in loadIMDbInfo
    i = imdb.IMDb()
  File "/usr/local/SickRage/lib/imdb/__init__.py", line 195, in IMDb
    from .parser.http import IMDbHTTPAccessSystem
  File "/usr/local/SickRage/lib/imdb/parser/http/__init__.py", line 39, in <module>
    from . import (
  File "/usr/local/SickRage/lib/imdb/parser/http/companyParser.py", line 34, in <module>
    from .piculet import Path, Rule, Rules
  File "/usr/local/SickRage/lib/imdb/parser/http/piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: Shared object "libpthread.so.0" not found, required by "etree.so"
2018-10-15 11:47:13 DEBUG    MAIN :: Traceback (most recent call last):
  File "/usr/local/SickRage/SickBeard.py", line 418, in load_shows_from_db
    cur_show = TVShow(sql_show[b'indexer'], sql_show[b'indexer_id'])
  File "/usr/local/SickRage/sickbeard/tv.py", line 111, in __init__
    self.loadFromDB()
  File "/usr/local/SickRage/sickbeard/tv.py", line 813, in loadFromDB
    self.loadIMDbInfo()
  File "/usr/local/SickRage/sickbeard/tv.py", line 899, in loadIMDbInfo
    i = imdb.IMDb()
  File "/usr/local/SickRage/lib/imdb/__init__.py", line 195, in IMDb
    from .parser.http import IMDbHTTPAccessSystem
  File "/usr/local/SickRage/lib/imdb/parser/http/__init__.py", line 39, in <module>
    from . import (
  File "/usr/local/SickRage/lib/imdb/parser/http/companyParser.py", line 34, in <module>
    from .piculet import Path, Rule, Rules
  File "/usr/local/SickRage/lib/imdb/parser/http/piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: Shared object "libpthread.so.0" not found, required by "etree.so"


libpthread.so is available on my system:

user@system:/usr/local/SickRage/Logs % locate libpthread.so
/compat/linux/lib/libpthread.so.0
/usr/lib/libpthread.so
/usr/lib32/libpthread.so
/usr/local/lib/compat/libpthread.so.2
/usr/local/lib32/compat/libpthread.so.2
```

**Comment by miigotu** [comment]
Try the develop branch please

**Comment by lokipo** [comment]
Works fine on develop. Thanks.
