### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by xDowwdeen** [SickChill/SickChill#5076]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: DeitPi 6.16
Browser: Chrome 
What you did: Request check for updated
What happened:
What you expected:
Logs:
```
2018-10-15 18:32:07 ThreadPoolExecutor-0_0 :: [13bbd46] Failed doing webui callback: Traceback (most recent call last):
File "/mnt/dietpi_userdata/sickrage/sickbeard/webserve.py", line 288, in async_call
result = function(**kwargs)
File "/mnt/dietpi_userdata/sickrage/sickbeard/webserve.py", line 1315, in fetchRemoteBranches
gh_branches = sickbeard.versionCheckScheduler.action.list_remote_branches()
File "/mnt/dietpi_userdata/sickrage/sickbeard/versionChecker.py", line 332, in list_remote_branches
return self.updater.list_remote_branches()
File "/mnt/dietpi_userdata/sickrage/sickbeard/versionChecker.py", line 863, in list_remote_branches
repo = sickbeard.gh.get_organization(sickbeard.GIT_ORG).get_repo(sickbeard.GIT_REPO)
File "/mnt/dietpi_userdata/sickrage/lib/github/MainClass.py", line 198, in get_organization
"/orgs/" + login
File "/mnt/dietpi_userdata/sickrage/lib/github/Requester.py", line 169, in requestJsonAndCheck
return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
File "/mnt/dietpi_userdata/sickrage/lib/github/Requester.py", line 215, in requestJson
return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
File "/mnt/dietpi_userdata/sickrage/lib/github/Requester.py", line 268, in __requestEncode
status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
File "/mnt/dietpi_userdata/sickrage/lib/github/Requester.py", line 293, in __requestRaw
requestHeaders
File "/usr/lib/python2.7/httplib.py", line 1042, in request
self._send_request(method, url, body, headers)
File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
self.endheaders(body)
File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
self._send_output(message_body)
File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
self.send(msg)
File "/usr/lib/python2.7/httplib.py", line 844, in send
self.connect()
File "/usr/lib/python2.7/httplib.py", line 1263, in connect
server_hostname=server_hostname)
File "/usr/lib/python2.7/ssl.py", line 363, in wrap_socket
_context=self)
File "/usr/lib/python2.7/ssl.py", line 611, in __init__
self.do_handshake()
File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
self._sslobj.do_handshake()
SSLError: getrandom() initialization failed. (_ssl.c:661)

```

**Comment by miigotu** [comment]
Install rng-tools - This is a distro issue not a SR issue.
