### ISSUE TITLE
[APP SUBMITTED]: unexpected unindent (home.mako.py, line 96)

### ISSUE THREAD

**Issue by Tiwas** [SickChill/SickChill#5092]
### INFO
Python Version: **2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@fa36303a1f48e9862729b0f1a74f83de81bc2522
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [fa36303] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 716, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "C:\SickRage\sickbeard\webserve.py", line 115, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickRage\lib\mako\lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "C:\SickRage\lib\mako\lookup.py", line 323, in _load
    **self.template_args)
  File "C:\SickRage\lib\mako\template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickRage\lib\mako\template.py", line 396, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickRage\lib\mako\compat.py", line 90, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickRage\cache\mako\home.mako.py", line 96
    
    ^
IndentationError: unexpected unindent

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Stop SickChill and delete the folder `C:\SickRage\cache\mako` and then start the service back up.
