### ISSUE TITLE
deleteing show with apostrophe in name causes error

### ISSUE THREAD

**Issue by si458** [SickChill/SickChill#5127]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Ubuntu 16.04
Browser: Firefox
What you did: remove a show from my list
What happened: deleted show but caused a DB error
What you expected: delete show and delete from DB
Logs:
```
2018-10-27 21:00:10 INFO     SHOWQUEUE-REMOVE-SHOW :: Here is the arguments that were passed to this function (This is what the developers need to know): {'fetchall': True, 'attempt': 0, 'severity': 40, 'self': , 'args': [294757], 'sql_results': [], 'query': u"SELECT location from tv_shows WHERE location LIKE '/home/plexnas/tvshows/Peter Kay's Car Share%' AND indexer_id != ?", 'e': OperationalError('near "s": syntax error',), 'fetchone': False}
2018-10-27 21:00:10 INFO     SHOWQUEUE-REMOVE-SHOW :: If this happened in cache.db, you can safely stop SickChill, and delete the cache.db file without losing any data
AA OperationalError: near "s": syntax error
AA sql_results = self.connection.cursor().execute(query, args)
AA File "/opt/sickchill/sickbeard/db.py", line 141, in _execute
AA sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
AA File "/opt/sickchill/sickbeard/db.py", line 283, in action
AA Traceback (most recent call last):
2018-10-27 21:00:10 ERROR    SHOWQUEUE-REMOVE-SHOW :: [4f7a2a5] Fatal error executing query with db.action in database /opt/sickchill/sickbeard.db: near "s": syntax error
```

**Comment by austinstevenson** [comment]
I believe the offending line in tv.py (1029): 
```
shows_in_folder = main_db_con.select("SELECT location from tv_shows WHERE location LIKE '{showloc}%' AND indexer_id != ?".format(
                    showloc=self.location), [self.indexerid])
```
Could be rewritten:
```
shows_in_folder = main_db_con.select("SELECT location from tv_shows WHERE location LIKE ? AND indexer_id != ?", 
[self.location + %, self.indexerid])
```
[http://docs.xojo.com/index.php/SQLitePreparedStatement](http://docs.xojo.com/index.php/SQLitePreparedStatement)
