### ISSUE TITLE
Failure to start after last update

### ISSUE THREAD

**Issue by dirkr07** [SickChill/SickChill#5140]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 
OS: Synology DSM
Browser: Chrome
What you did: did the last update of today (30/10)
What happened: SC restarted but never came back up (failed to run the package service)
What you expected: that it would start up again
I can just see this in the logs of SickBeard Custom
Logs:
```
Tue Oct 30 15:25:44 CET 2018
Starting sickbeard-custom command /volume1/@appstore/sickbeard-custom/env/bin/python /volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py --daemon --pidfile /volume1/@appstore/sickbeard-custom/var/sickbeard-custom.pid --config /volume1/@appstore/sickbeard-custom/var/config.ini --datadir /volume1/@appstore/sickbeard-custom/var/
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py", line 69, in <module>
    import sickbeard
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 46, in <module>
    from sickbeard import (auto_postprocessor, dailysearcher, db, helpers, logger, metadata, naming, post_processing_queue, properFinder, providers, scheduler,
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/dailysearcher.py", line 27, in <module>
    from sickbeard import common, db, logger, network_timezones
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/db.py", line 34, in <module>
    from sickbeard import logger
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 43
    from requests.compat quote
                             ^
SyntaxError: invalid syntax

```
Hopefull this can be resolved manually without a reinstall?

**Comment by dirkr07** [comment]
Seems to be the same as #5141

**Comment by jangrewe** [comment]
Ah, i checked the issues before opening mine, but it looks we were both opening one at the same time ;-)

**Comment by dirkr07** [comment]
> Ah, i checked the issues before opening mine, but it looks we were both opening one at the same time ;-)

Pretty much yeah!
