### ISSUE TITLE
SickChill won't start after latest update

### ISSUE THREAD

**Issue by tapessur** [SickChill/SickChill#5146]
SickChill just auto-updated and won't start anymore on Synology. 
Following error is spewed out...

```
Traceback (most recent call last):
  File "/volume1/@appstore/sickchill/var/SickBeard/SickBeard.py", line 72, in <module>
    from sickbeard.webserveInit import SRWebServer
  File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/webserveInit.py", line 17, in <module>
    from sickbeard.webserve import CalendarHandler, KeyHandler, LoginHandler, LogoutHandler
  File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/webserve.py", line 49
    from requests.compat unquote_plus
                                    ^
SyntaxError: invalid syntax

```

**Comment by miigotu** [comment]
```
cd /volume1/@appstore/sickchill/var/SickBeard
git pull
```
