### ISSUE TITLE
SickChill wont star - Synology

### ISSUE THREAD

**Issue by fadern** [SickChill/SickChill#5149]
Suddenly SickChill went offline and wont start again...

Branch/Commit: master/ec4903128d7674a334873835ba35d72b9991a924
OS: Synology DSM 6.2.1-23824 Update 1
Browser: FF
What you did: nothing
What happened: dont know, Sickchill died and wont start
What you expected: Sickchill to run
Installed using -> https://github.com/SickChill/SickChill/wiki/Switching-your-Synology%27s-Sickrage-to-the-new-repository

Logs:
```
tail sickbeard-custom.log 
Starting sickbeard-custom command /volume1/@appstore/sickbeard-custom/env/bin/python /volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py --daemon --pidfile /volume1/@appstore/sickbeard-custom/var/sickbeard-custom.pid --config /volume1/@appstore/sickbeard-custom/var/config.ini --datadir /volume1/@appstore/sickbeard-custom/var/ 
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py", line 72, in <module>
    from sickbeard.webserveInit import SRWebServer
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserveInit.py", line 17, in <module>
    from sickbeard.webserve import CalendarHandler, KeyHandler, LoginHandler, LogoutHandler
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/webserve.py", line 49
    from requests.compat unquote_plus
                                    ^
SyntaxError: invalid syntax


tail /var/log/messages

2018-10-31T10:15:21+01:00 NAS1 [ 1505.375769] init: pkgctl-sickbeard-custom pre-start process (23669) terminated with status 1
2018-10-31T10:15:21+01:00 NAS1 synoscgi_SYNO.Core.Package.Control_1_start[23582]: servicecfg_internal_lib.c:187 Failed to start job [pkgctl-sickbeard-custom][0xD900 manager.cpp:204]
2018-10-31T10:15:22+01:00 NAS1 synoscgi_SYNO.Core.Package.Control_1_start[23582]: service_initjob_action.c:27 InitJobStart failed, [0xD900 manager.cpp:204]
2018-10-31T10:15:22+01:00 NAS1 synoscgi_SYNO.Core.Package.Control_1_start[23582]: pkgstartstop.cpp:367 Failed to start pkgctl-sickbeard-custom (err=-1) [0xD900 manager.cpp:204]

```

**Comment by fadern** [comment]
maybe related to this old issue https://github.com/SynoCommunity/spksrc/issues/3338

**Comment by nicktones** [comment]
I also have this... New yesterday, so not sure the post above is relevant.

**Comment by mbmaley** [comment]
I had the same but I did a git pull and it seems to be fixed. There were a few changes yesterday so maybe one of them broke it?

**Comment by nicktones** [comment]
Can confirm that a git pull fixed this issue.

**Comment by fadern** [comment]
ill try the pull.
is this correct?
cd /volume1/@appstore/sickbeard-custom/var/SickBeard/
/volume1/@appstore/git/bin/git pull

?

**Comment by fadern** [comment]
i did this

git remote add upstream https://github.com/SickChill/SickChill.git
git fetch upstream
git checkout master
git branch -u upstream/master
git reset --hard upstream/master
git pull

and now its working again. thank you!

https://github.com/SickChill/SickChill/wiki/FAQ%27s-and-Fixes#i-have-problems-updating-or-my-installation-got-corrupt-what-now
