### ISSUE TITLE
SickChill failing to start on veteran install

### ISSUE THREAD

**Issue by ATor69** [SickChill/SickChill#5152]
### Before submitting your issue:

Starting today I am getting the following error when attempting to start SickChill:

Branch: Master
OS: Debian Squeeze

What you did: Nothing
What happened: Failed to start
What you expected: SickChill to start up
System Logs:
```
Oct 31 18:43:32 [hostname] [10195]: Traceback (most recent call last):
Oct 31 18:43:32 [hostname] [10195]:   File "SickBeard.py", line 72, in <module>
Oct 31 18:43:32 [hostname] [10195]:     from sickbeard.webserveInit import SRWebServer
Oct 31 18:43:32 [hostname] [10195]:   File "/home/XXXXXX/SickRage/sickbeard/webserveInit.py", line 17, in <module>
Oct 31 18:43:32 [hostname] [10195]:     from sickbeard.webserve import CalendarHandler, KeyHandler, LoginHandler, LogoutHandler
Oct 31 18:43:32 [hostname] [10195]:   File "/home/XXXXXX/SickRage/sickbeard/webserve.py", line 49
Oct 31 18:43:32 [hostname] [10195]:     from requests.compat unquote_plus
```

SickChill Logs:

```
2018-10-30 10:48:06 INFO     CHECKVERSION :: New update found for SickChill, starting auto-updater ...
2018-10-30 10:48:07 INFO     CHECKVERSION :: Config backup in progress...
2018-10-30 10:49:02 INFO     CHECKVERSION :: Config backup successful, updating...
2018-10-30 10:49:05 INFO     CHECKVERSION :: Update was successful!
2018-10-30 10:49:05 INFO     EVENT-QUEUE :: Aborting all threads
2018-10-30 10:49:05 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2018-10-30 10:49:06 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2018-10-30 10:49:06 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2018-10-30 10:49:06 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2018-10-30 10:49:06 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2018-10-30 10:49:06 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2018-10-30 10:49:06 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2018-10-30 10:49:06 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR-AUTO thread to exit
2018-10-30 10:49:06 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2018-10-30 10:49:06 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2018-10-30 10:49:06 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2018-10-30 10:49:06 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2018-10-30 10:49:06 INFO     EVENT-QUEUE :: Saving all shows to the database
2018-10-30 10:49:09 INFO     EVENT-QUEUE :: Saving config file to disk
2018-10-30 10:49:09 INFO     EVENT-QUEUE :: Shutting down Tornado
2018-10-30 10:49:09 INFO     EVENT-QUEUE :: Restarting SickChill with ['/usr/bin/python2.7', u'/home/**********/SickRage/SickBeard.py', '-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickrage/sickrage_**********.pid', '--datadir=/h$
```

**Comment by ATor69** [comment]
Appears the service needed a full stop and start to get restarted.  Resolved
