### ISSUE TITLE
It doesnt boot after abrupt shutdown

### ISSUE THREAD

**Issue by Vidanez** [SickChill/SickChill#5251]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: OSX
Browser:
What you did: Abrupt shutdown
What happened: it doesn't boot
What you expected:
Logs:
```
Mac-mini:sickrage root# ./SiCKRAGE.py 
Traceback (most recent call last):
  File "/Applications/SickRage.app/sickrage/sickrage/__init__.py", line 223, in main
    app = Core()
  File "/Applications/SickRage.app/sickrage/sickrage/core/__init__.py", line 121, in __init__
    self.user_agent = 'SiCKRAGE.CE.1/({};{};{})'.format(platform.system(), platform.release(), str(uuid.uuid1()))
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/uuid.py", line 588, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/uuid.py", line 164, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)
Mac-mini:sickrage root# 
```

**Comment by WebSpider** [comment]
You are running a different fork, not SickChill, it would be best to migrate to SickChill ;)
