### ISSUE TITLE
Error adding show with Fate⁄Apocrypha

### ISSUE THREAD

**Issue by jakewarren81** [SickChill/SickChill#5268]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:  master/ abc6aab554715e57cf1668627a1f57f5b1ed4588 
OS:  Windows-10-10.0.17134 
Browser:  Firefox
What you did:  Add a show Fate⁄Apocrypha
What happened:  Error page pasted below.
What you expected:   Add a show.
Logs:
```
2019-01-04 18:42:14 ThreadPoolExecutor-0_3 :: [abc6aab] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickChill\sickbeard\webserve.py", line 2511, in sanitizeFileName
    return sanitize_filename(name)
  File "C:\SickChill\sickchill\helper\common.py", line 298, in sanitize_filename
    filename = filename.strip(' .')
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5: character maps to 

                        2019-01-04 18:34:08 ThreadPoolExecutor-0_1 :: [abc6aab] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickChill\sickbeard\webserve.py", line 2511, in sanitizeFileName
    return sanitize_filename(name)
  File "C:\SickChill\sickchill\helper\common.py", line 298, in sanitize_filename
    filename = filename.strip(' .')
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5: character maps to 

                        2019-01-04 18:34:08 ThreadPoolExecutor-0_2 :: [abc6aab] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickChill\sickbeard\webserve.py", line 2393, in fetch_releasegroups
    logger.log('ReleaseGroups: {0}'.format(show_name), logger.INFO)
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5: character maps to 

                        2019-01-04 18:34:05 ThreadPoolExecutor-0_0 :: [abc6aab] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickChill\sickbeard\webserve.py", line 2511, in sanitizeFileName
    return sanitize_filename(name)
  File "C:\SickChill\sickchill\helper\common.py", line 298, in sanitize_filename
    filename = filename.strip(' .')
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5: character maps to 

Error

'charmap' codec can't decode byte 0x81 in position 61: character maps to
Traceback

Traceback (most recent call last):
File "C:\SickChill\lib\tornado\web.py", line 1511, in _execute result = yield result
File "C:\SickChill\lib\tornado\gen.py", line 1055, in run value = future.result()
File "C:\SickChill\lib\tornado\concurrent.py", line 238, in result raise_exc_info(self._exc_info)
File "C:\SickChill\lib\tornado\gen.py", line 1063, in run yielded = self.gen.throw(*exc_info)
File "C:\SickChill\sickbeard\webserve.py", line 265, in get results = yield self.async_call(method)
File "C:\SickChill\lib\tornado\gen.py", line 1055, in run value = future.result()
File "C:\SickChill\lib\concurrent\futures\_base.py", line 455, in result return self.__get_result()
File "C:\SickChill\lib\concurrent\futures\thread.py", line 63, in run result = self.fn(*self.args, **self.kwargs)
File "C:\SickChill\sickbeard\webserve.py", line 287, in async_call result = function(**kwargs)
File "C:\SickChill\sickbeard\webserve.py", line 2953, in addNewShow series_pieces = whichSeries.split('|')
File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 61: character maps to
Request Info

body: indexerLang=en&providedIndexer=0&whichSeries=theTVDB%7C1%7Chttp%3A%2F%2Fthetvdb.com%2F%3Ftab%3Dseries%26id%3D%7C326332%7CFate%E2%81%84Apocrypha%7C2017-07-02%7Cfalse&rootDir=D%3A%5CShare%5CMedia%5CTV_Shows&quality_preset=500&anyQualities=4&anyQualities=16&anyQualities=32&anyQualities=64&anyQualities=128&anyQualities=256&defaultStatus=3&defaultStatusAfter=3&season_folders=on&anime=on&scene=on&whitelist=&blacklist=&skipShow=
files: {}
protocol: http
connection:
body_arguments: {'defaultStatus': ['3'], 'providedIndexer': ['0'], 'whichSeries': ['theTVDB|1|http://thetvdb.com/?tab=series&id=|326332|Fate\xe2\x81\x84Apocrypha|2017-07-02|false'], 'skipShow': [''], 'anyQualities': ['4', '16', '32', '64', '128', '256'], 'indexerLang': ['en'], 'season_folders': ['on'], 'scene': ['on'], 'blacklist': [''], 'rootDir': ['D:\\Share\\Media\\TV_Shows'], 'quality_preset': ['500'], 'defaultStatusAfter': ['3'], 'whitelist': [''], 'anime': ['on']}
uri: /addShows/addNewShow
query_arguments: {}
_start_time: 1546656374.69
headers: Content-Length: 425 Accept-Language: en-US,en;q=0.5 Accept-Encoding: gzip, deflate Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0 Host: Content-Type: application/x-www-form-urlencoded
version: HTTP/1.1
server_connection:
_finish_time: None
query:
arguments: {'defaultStatus': '3', 'providedIndexer': '0', 'skipShow': '', 'anyQualities': ['4', '16', '32', '64', '128', '256'], 'indexerLang': 'en', 'season_folders': 'on', 'scene': 'on', 'blacklist': '', 'rootDir': 'D:\\Share\\Media\\TV_Shows', 'defaultStatusAfter': '3', 'quality_preset': '500', 'whichSeries': 'theTVDB|1|http://thetvdb.com/?tab=series&id=|326332|Fate\xe2\x81\x84Apocrypha|2017-07-02|false', 'whitelist': '', 'anime': 'on'}
path: /addShows/addNewShow
method: POST
remote_ip: 192.168.1.104

```

**Comment by jakewarren81** [comment]
thetvdb.com had funky characters in the title.  Fix it there.
