### ISSUE TITLE
SSL version errors

### ISSUE THREAD

**Issue by tjenvy** [SickChill/SickChill#5270]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/ abc6aab554715e57cf1668627a1f57f5b1ed4588
OS: macOS 10.11.6 (max version for this system)
Browser: Safari
What you did: errors with SSL
What happened: na
What you expected: na
Logs:
```
10:17:14 INFO::MAIN :: SSL Error requesting url: 'https://sickchill.github.io/sb_network_timezones/network_timezones.txt' You have OpenSSL 0.9.8zh 14 Jan 2016, try upgrading OpenSSL to 1.0.1e+

```

**_See issue  2160_**

This issue has shown up out of nowhere again.  Its not related to TPB  but in fact just SickChill as a whole.  Most of the instructions I tried from that previous iteration to no avail.  I am assuming that something changed when I trashed the old Sickrage for sick chill, starting fresh.  

While this is a time zone error and irrelevant really, the concern is the OpenSSL version.  I had issues "updating" the commits earlier because of this error.  I scrapped everything and pulled a new copy and its up to date now without issue.  

From SC
```
  Python Version: 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
  SSL Version: OpenSSL 0.9.8zh 14 Jan 2016
  OS: Darwin-15.6.0-x86_64-i386-64bit
```

From Terminal
```TJ-Johnsens-Mac-Pro:~ tjenvy$ python --version
Python 2.7.12
TJ-Johnsens-Mac-Pro:~ tjenvy$ openssl version -a
OpenSSL 1.0.2p  14 Aug 2018
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/etc/openssl"
```

**Comment by tjenvy** [comment]
```2019-01-06 10:23:03 INFO     SEARCHQUEUE-MANUAL-270408 :: [Rarbg] :: Performing episode search for Outlander

2019-01-06 10:23:03 INFO     SEARCHQUEUE-MANUAL-270408 :: [Nyaa] :: SSL Error requesting url: 'https://nyaa.si/?s=id&c=1_0&page=rss&o=desc&f=2' Try disabling Cert Verification on the advanced tab of /config/general

2019-01-06 10:23:03 INFO     SEARCHQUEUE-MANUAL-270408 :: [Nyaa] :: SSL Error requesting url: 'https://nyaa.si/?s=id&c=1_0&page=rss&o=desc&f=2' You have OpenSSL 0.9.8zh 14 Jan 2016, try upgrading OpenSSL to 1.0.1e+

2019-01-06 10:23:02 INFO     SEARCHQUEUE-MANUAL-270408 :: [SkyTorrents] :: SSL Error requesting url: 'https://www.skytorrents.lol/rss?sort=created&query=&tag=hd&type=video' Try disabling Cert Verification on the advanced tab of /config/general

2019-01-06 10:23:02 INFO     SEARCHQUEUE-MANUAL-270408 :: [SkyTorrents] :: SSL Error requesting url: 'https://www.skytorrents.lol/rss?sort=created&query=&tag=hd&type=video' You have OpenSSL 0.9.8zh 14 Jan 2016, try upgrading OpenSSL to 1.0.1e+

2019-01-06 10:23:00 INFO     SEARCHQUEUE-MANUAL-270408 :: [Torrentz] :: SSL Error requesting url: 'https://torrentz2.eu/feed?f=' Try disabling Cert Verification on the advanced tab of /config/general

2019-01-06 10:23:00 INFO     SEARCHQUEUE-MANUAL-270408 :: [Torrentz] :: SSL Error requesting url: 'https://torrentz2.eu/feed?f=' You have OpenSSL 0.9.8zh 14 Jan 2016, try upgrading OpenSSL to 1.0.1e+

2019-01-06 10:23:00 INFO     SEARCHQUEUE-MANUAL-270408 :: [LimeTorrents] :: SSL Error requesting url: 'https://www.limetorrents.cc/rss/tv/' Try disabling Cert Verification on the advanced tab of /config/general

2019-01-06 10:23:00 INFO     SEARCHQUEUE-MANUAL-270408 :: [LimeTorrents] :: SSL Error requesting url: 'https://www.limetorrents.cc/rss/tv/' You have OpenSSL 0.9.8zh 14 Jan 2016, try upgrading OpenSSL to 1.0.1e+

2019-01-06 10:22:40 INFO     SEARCHQUEUE-MANUAL-270408 :: SSL Error requesting url: 'https://sickchill.github.io/scene_exceptions/scene_exceptions.json' Try disabling Cert Verification on the advanced tab of /config/general

2019-01-06 10:22:40 INFO     SEARCHQUEUE-MANUAL-270408 :: SSL Error requesting url: 'https://sickchill.github.io/scene_exceptions/scene_exceptions.json' You have OpenSSL 0.9.8zh 14 Jan 2016, try upgrading OpenSSL to 1.0.1e+

2019-01-06 10:22:40 INFO     SEARCHQUEUE-MANUAL-270408 :: Checking for scene exception updates from http://sickchill.github.io/scene_exceptions/scene_exceptions.json

2019-01-06 10:22:40 INFO     SEARCHQUEUE-MANUAL-270408 :: Beginning manual search for: [Outlander - S04E10 - The Deep Heart's Core]

2019-01-06 10:22:35 WARNING  MAIN :: Updating network timezones failed, this can happen from time to time. URL: http://sickchill.github.io/sb_network_timezones/network_timezones.txt

2019-01-06 10:22:35 INFO     MAIN :: SSL Error requesting url: 'https://sickchill.github.io/sb_network_timezones/network_timezones.txt' Try disabling Cert Verification on the advanced tab of /config/general```

**Comment by tjenvy** [comment]
Followed all these steps form another site......

```
Got this working after several days. MAC OS X El Captian or greater

 sudo rm -rf /Library/Frameworks/Python.framework/Versions/2.7
 sudo rm -rf "/Applications/Python 2.7"
 cd /usr/local/bin/
 ls -l /usr/local/bin | grep '../Library/Frameworks/Python.framework/Versions/2.7' | awk '{print $9}' | tr -d @ | xargs rm
 brew uninstall python
 brew uninstall openssl
 brew link --force openssl
Now install python and openssl again using brew.

 brew install openssl
 brew install python --with-brewed-openssl
Add the following to the PATH in ~/.bash_profile on your MAC

 vi ~/.bash_profile
 export PATH=/usr/local/opt/openssl/bin:/usr/local/opt/python/libexec/bin:$PATH
restart the terminal

 python --version (verify if it is picking up the right version)
 openssl version -a (verify if it is picking up the right version)
 python -c "import ssl; print ssl.OPENSSL_VERSION"
(note: if you installed Python3, you'll have to update the print syntax in the inline compiler step)

python -c "import ssl; print(ssl.OPENSSL_VERSION)"
should give you the latest version OPEN SSL version
```

now terminal states:

```
python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.0.2q  20 Nov 2018


python --version
Python 3.7.2


 openssl version -a
OpenSSL 1.0.2q  20 Nov 2018


```

But when I open SickChill  I get that its running on 2.7 with the older ssl


```
  Python Version: 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
  SSL Version: OpenSSL 0.9.8zh 14 Jan 2016

```


What gives???

**Comment by WebSpider** [comment]
I'm sorry man, I'm really no Mac guy, else I'd love to help you out

**Comment by tjenvy** [comment]
Really the main question now it seems comes down to why sickchill is using python 2.7.  I thought i had eradicated all traces of 2.7 but apparently not

**Comment by tjenvy** [comment]
so trying to force into p3 I am getting the following

```
TJ-Johnsens-Mac-Pro:bin tjenvy$ /usr/local/cellar/python/3.7.2/bin/python3 /Users/tjenvy/Desktop/SickChill/sickbeard.py
Traceback (most recent call last):
  File "/Users/tjenvy/Desktop/SickChill/sickbeard.py", line 69, in <module>
    import sickbeard
  File "/Users/tjenvy/Desktop/SickChill/sickbeard/__init__.py", line 34, in <module>
    import requests
  File "/Users/tjenvy/Desktop/SickChill/lib/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/tjenvy/Desktop/SickChill/lib/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Users/tjenvy/Desktop/SickChill/lib/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/Users/tjenvy/Desktop/SickChill/lib/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "/Users/tjenvy/Desktop/SickChill/lib/urllib3/packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/Users/tjenvy/Desktop/SickChill/lib/urllib3/packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/Users/tjenvy/Desktop/SickChill/lib/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/Users/tjenvy/Desktop/SickChill/lib/http/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

**Comment by tjenvy** [comment]
This is so infuriating as all I did was switch to the new SickChill form the SickRage.  Literally just replaced my directory (since it would not update) and now this is whats happening.  nothing else on the system has changed.

**Comment by brendan-pike** [comment]
Effects me on a QNAP nas install also and renders it unusable :(
