### ISSUE TITLE
Sickchill no longer can search for episodes / requires node.js???

### ISSUE THREAD

**Issue by tvann2182** [SickChill/SickChill#5277]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:master/f7a113a737654a91076bb42221e119db6258a276
OS:QNAP Nas Linux-4.2.8-x86_64-with-glibc2.2.5
Browser:
What you did: I updated the last two latest commits that updated the date from 2018 to 2018
What happened: after updating IPTorrent no longer is working
What you expected: no issues and it works as normal
Logs:
```
PASTE LOGS HERE
2019-01-09 17:03:26 INFO     ThreadPoolExecutor-0_0 :: Config backup in progress...
2019-01-09 17:03:47 INFO     POSTPROCESSOR-AUTO :: Processing /share/CACHEDEV1_DATA/Download/rtorrent/complete/sickbeard/Outlander.S04E10.720p.WEB.H264-AMCON/Outlander.S04E10.720p.WEB.H264-AMCON.mkv (None)
2019-01-09 17:03:47 INFO     POSTPROCESSOR-AUTO :: This download is marked a priority download so I'm going to replace an existing file if I find one
2019-01-09 17:03:47 INFO     POSTPROCESSOR-AUTO :: Trying to clean any empty folders under /share/Video/TV/Active TV Shows/Outlander/Season 04
2019-01-09 17:03:47 INFO     POSTPROCESSOR-AUTO :: Release name (tvmaze) found from file (tvmaze.nfo)
2019-01-09 17:03:56 INFO     POSTPROCESSOR-AUTO :: Processing succeeded for /share/CACHEDEV1_DATA/Download/rtorrent/complete/sickbeard/Outlander.S04E10.720p.WEB.H264-AMCON/Outlander.S04E10.720p.WEB.H264-AMCON.mkv
2019-01-09 17:03:57 INFO     POSTPROCESSOR-AUTO :: Successfully processed
2019-01-09 17:03:57 INFO     POSTPROCESSOR-AUTO :: Auto post processing task for /share/Download/rtorrent/complete/sickbeard completed
2019-01-09 17:04:09 INFO     ThreadPoolExecutor-0_0 :: Config backup successful, updating...
2019-01-09 17:04:11 INFO     EVENT-QUEUE :: Aborting all threads
2019-01-09 17:04:11 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE-REFRESH thread to exit
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE-BACKLOG-278125 thread to exit
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR-AUTO thread to exit
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Saving all shows to the database
2019-01-09 17:04:12 INFO     EVENT-QUEUE :: Saving config file to disk
2019-01-09 17:04:13 INFO     EVENT-QUEUE :: Shutting down Tornado
2019-01-09 17:04:13 INFO     EVENT-QUEUE :: Restarting SickChill with ['/opt/SickChill/bin/python', u'/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/SickBeard.py', '-p', '29998', '--datadir', '/share/CACHEDEV1_DATA/.qpkg/QSickChill/DATAS', '--config', '/share/CACHEDEV1_DATA/.qpkg/QSickChill/CONFIG/sickbeard.conf', u'--nolaunch']
2019-01-09 17:04:14 INFO     MAIN :: Starting SickChill [master] using '/share/CACHEDEV1_DATA/.qpkg/QSickChill/CONFIG/sickbeard.conf'
2019-01-09 17:04:14 INFO     MAIN :: Forcing web server to port 29998
2019-01-09 17:04:14 INFO     TORNADO :: Starting SickChill on http://0.0.0.0:29998/
2019-01-09 17:04:14 INFO     CHECKVERSION :: Checking for updates using GIT
2019-01-09 17:04:18 ERROR    ThreadPoolExecutor-0_2 :: [f7a113a] Missing time zone for network: Fullscreen. Check valid network is set in indexer (theTVDB) before filing issue.
None
2019-01-09 17:04:57 INFO     ThreadPoolExecutor-0_0 :: Removing release_name for episode as you want to set a downloaded episode back to wanted, so obviously you want it replaced
2019-01-09 17:04:57 INFO     ThreadPoolExecutor-0_0 :: Sending backlog for NCIS: New Orleans season 5 because some eps were set to wanted
2019-01-09 17:04:59 INFO     SEARCHQUEUE-BACKLOG-278125 :: Beginning backlog search for: [NCIS: New Orleans]
**2019-01-09 17:04:59 INFO     SEARCHQUEUE-BACKLOG-278125 :: [IPTorrents] :: Performing episode search for NCIS: New Orleans
2019-01-09 17:05:08 ERROR    SEARCHQUEUE-BACKLOG-278125 :: [IPTorrents] :: [f7a113a] Request failed: Missing Node.js runtime. Node is required and must be in the PATH (check with `node -v`). Your Node binary may be called `nodejs` rather than `node`, in which case you may need to run `apt-get install nodejs-legacy` on some Debian-based systems. (Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies. (<type 'str'>)**
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/helpers.py", line 1526, in handle_requests_exception
    raise requests_exception
EnvironmentError: Missing Node.js runtime. Node is required and must be in the PATH (check with `node -v`). Your Node binary may be called `nodejs` rather than `node`, in which case you may need to run `apt-get install nodejs-legacy` on some Debian-based systems. (Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.
2019-01-09 17:05:16 ERROR    SEARCHQUEUE-BACKLOG-278125 :: [IPTorrents] :: [f7a113a] Request failed: Missing Node.js runtime. Node is required and must be in the PATH (check with `node -v`). Your Node binary may be called `nodejs` rather than `node`, in which case you may need to run `apt-get install nodejs-legacy` on some Debian-based systems. (Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies. (<type 'str'>)
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/helpers.py", line 1526, in handle_requests_exception
    raise requests_exception
EnvironmentError: Missing Node.js runtime. Node is required and must be in the PATH (check with `node -v`). Your Node binary may be called `nodejs` rather than `node`, in which case you may need to run `apt-get install nodejs-legacy` on some Debian-based systems. (Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.

**Comment by papampi** [comment]
I had same issue on qnap Nas and solved it by installing node.js

**Comment by tvann2182** [comment]
I took your advice and this resolved my issue, my problem is that it was working for months without issue and then it stopped after updating on the latest branch. It is working now and thank you for the advice.
