### ISSUE TITLE
unable to connect to web gui after fresh install

### ISSUE THREAD

**Issue by greydawg00** [SickChill/SickChill#5293]
I have been a SickRage user for many years.  I switched to SickChill in Oct after Sickrage no longer updated.  All was working until last week when I started getting errors from SABNZBD coming from NZBtomedia.  "importerror: unable to import Client.  Research seemed to indicate it might not be able to connect to sickchill. In my attempts to repair this is when I started having issues. 

Here is what I attempted:
1) Add API key from Sickchill to nzbtomedia config
2) change sickchill web password
3) restart sickchill
 - after this, sickchill has never worked again (cannot access gui)
4) copy sickchill directory for backup, then new git pull
5) git pull showed already up to date, so force pull with a reset (--hard)
6) multiple service and computer restarts, still nothing worked
7) disabled existing service
8) installed sickchill from scratch using installer
9) new install still not able to access gui
10) tried installing with different port, still not working

At this point I have run out of ideas, google searchs, etc.  PLEASE HELP

This site can’t be reached localhost refused to connect.
Search Google for localhost 8081 home
ERR_CONNECTION_REFUSED

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: latest
OS: Windows 10
Browser: Chrome
What you did:  New install of SickChill using SickChillInstaller
What happened: When it attempt to launch in browser, I get a connection refused error
What you expected:  The sickchill gui to launch
Logs:
```
2019-01-17 14:55:23 ERROR    MAIN :: Fatal error executing query with db.action in database C:\SickChill\Data\sickbeard.db: table tv_shows has 17 columns but 18 values were supplied
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\db.py", line 283, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\SickChill\SickChill\sickbeard\db.py", line 139, in _execute
    sql_results = self.connection.cursor().execute(query)
OperationalError: table tv_shows has 17 columns but 18 values were supplied
2019-01-17 14:55:23 INFO     MAIN :: If this happened in cache.db, you can safely stop SickChill, and delete the cache.db file without losing any data
2019-01-17 14:55:23 INFO     MAIN :: Here is the arguments that were passed to this function (This is what the developers need to know): {'fetchall': False, 'attempt': 0, 'severity': 40, 'self': <sickbeard.db.DBConnection object at 0x0000000007698B00>, 'args': None, 'sql_results': [], 'query': u'INSERT INTO tv_shows SELECT * FROM tmp_tv_shows', 'e': OperationalError('table tv_shows has 17 columns but 18 values were supplied',), 'fetchone': False}
2019-01-17 14:55:23 ERROR    MAIN :: Error in RenameSeasonFolders: table tv_shows has 17 columns but 18 values were supplied
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\db.py", line 488, in _process_upgrade
    instance.execute()
  File "C:\SickChill\SickChill\sickbeard\databases\mainDB.py", line 484, in execute
    self.connection.action("INSERT INTO tv_shows SELECT * FROM tmp_tv_shows")
  File "C:\SickChill\SickChill\sickbeard\db.py", line 283, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\SickChill\SickChill\sickbeard\db.py", line 139, in _execute
    sql_results = self.connection.cursor().execute(query)
OperationalError: table tv_shows has 17 columns but 18 values were supplied
2019-01-17 14:55:31 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-01-17 14:55:31 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2019-01-17 14:55:31 DEBUG    MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
2019-01-17 14:55:31 DEBUG    MAIN :: formatting pattern: %SN - S%0SE%0E - %EN -> Show Name - S02E03 - Ep Name
2019-01-17 14:55:31 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-01-17 14:55:31 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2019-01-17 14:55:31 DEBUG    MAIN :: formatting pattern: Season %0S -> Season 02
2019-01-17 14:55:31 DEBUG    MAIN :: Trying to parse Show Name - S02E03 - Ep Name.ext
2019-01-17 14:55:31 DEBUG    MAIN :: Parsed Show Name - S02E03 - Ep Name.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-01-17 14:55:31 DEBUG    MAIN :: The name Show Name - S02E03 - Ep Name.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-01-17 14:55:32 DEBUG    MAIN :: Checking database structure...sickbeard.db
2019-01-17 14:55:32 DEBUG    MAIN :: Database upgrade required: Add Size And Scene Name Fields
2019-01-17 14:55:32 INFO     MAIN :: Backing up database before upgrade
2019-01-17 14:55:32 INFO     MAIN :: Proceeding with upgrade
2019-01-17 14:55:32 INFO     MAIN :: Adding file size to all episodes in DB, please be patient
2019-01-17 14:55:32 INFO     MAIN :: Adding release name to all episodes still in history
2019-01-17 14:55:32 INFO     MAIN :: Adding release name to all episodes with obvious scene filenames
2019-01-17 14:55:32 DEBUG    MAIN :: AddSizeAndSceneNameFields upgrade completed
2019-01-17 14:55:32 DEBUG    MAIN :: Database upgrade required: Rename Season Folders
2019-01-17 14:55:32 INFO     MAIN :: Backing up database before upgrade
2019-01-17 14:55:32 INFO     MAIN :: Proceeding with upgrade
2019-01-17 14:55:34 DEBUG    MAIN :: RenameSeasonFolders upgrade completed
2019-01-17 14:55:34 DEBUG    MAIN :: Database upgrade required: Add1080p And Raw Qualities
2019-01-17 14:55:34 INFO     MAIN :: Backing up database before upgrade
2019-01-17 14:55:34 INFO     MAIN :: Proceeding with upgrade
2019-01-17 14:55:34 INFO     MAIN :: [1/4] Updating pre-defined templates and the quality for each show...
2019-01-17 14:55:34 INFO     MAIN :: [2/4] Updating the status for the episodes within each show...
2019-01-17 14:55:34 INFO     MAIN :: [3/4] Updating history to reflect the correct action...
2019-01-17 14:55:34 INFO     MAIN :: [4/4] Updating history to reflect the correct quality...
2019-01-17 14:55:34 DEBUG    MAIN :: Performing a vacuum on the database.
2019-01-17 14:55:35 DEBUG    MAIN :: Add1080pAndRawHDQualities upgrade completed
2019-01-17 14:55:35 DEBUG    MAIN :: Database upgrade required: Add Showid Tvdbid Index
2019-01-17 14:55:35 INFO     MAIN :: Backing up database before upgrade
2019-01-17 14:55:35 INFO     MAIN :: Proceeding with upgrade
2019-01-17 14:55:35 INFO     MAIN :: Check for duplicate shows before adding unique index.
2019-01-17 14:55:35 INFO     MAIN :: Adding index on tvdb_id (tv_shows) and showid (tv_episodes) to speed up searches/queries.
2019-01-17 14:55:35 DEBUG    MAIN :: AddShowidTvdbidIndex upgrade completed
2019-01-17 14:55:35 DEBUG    MAIN :: Database upgrade required: Add Last Update
2019-01-17 14:55:35 INFO     MAIN :: Backing up database before upgrade
2019-01-17 14:55:35 INFO     MAIN :: Proceeding with upgrade
2019-01-17 14:55:35 INFO     MAIN :: Adding column last_update_tvdb to tvshows
2019-01-17 14:55:36 DEBUG    MAIN :: AddLastUpdateTVDB upgrade completed
2019-01-17 14:55:36 DEBUG    MAIN :: Database upgrade required: Add Increase To15
2019-01-17 14:55:36 INFO     MAIN :: Backing up database before upgrade
2019-01-17 14:55:36 INFO     MAIN :: Proceeding with upgrade
2019-01-17 14:55:36 DEBUG    MAIN :: AddDBIncreaseTo15 upgrade completed
2019-01-17 14:55:36 DEBUG    MAIN :: Database upgrade required: Add Db Info
2019-01-17 14:55:36 INFO     MAIN :: Backing up database before upgrade
2019-01-17 14:55:36 INFO     MAIN :: Proceeding with upgrade
2019-01-17 14:55:36 ERROR    MAIN :: Fatal error executing query with db.action in database C:\SickChill\Data\sickbeard.db: table imdb_info already exists
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\db.py", line 283, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\SickChill\SickChill\sickbeard\db.py", line 139, in _execute
    sql_results = self.connection.cursor().execute(query)
OperationalError: table imdb_info already exists
2019-01-17 14:55:36 INFO     MAIN :: If this happened in cache.db, you can safely stop SickChill, and delete the cache.db file without losing any data
2019-01-17 14:55:36 INFO     MAIN :: Here is the arguments that were passed to this function (This is what the developers need to know): {'fetchall': False, 'attempt': 0, 'severity': 40, 'self': <sickbeard.db.DBConnection object at 0x0000000007720B00>, 'args': None, 'sql_results': [], 'query': u'CREATE TABLE imdb_info (tvdb_id INTEGER PRIMARY KEY, imdb_id TEXT, title TEXT, year NUMERIC, akas TEXT, runtimes NUMERIC, genres TEXT, countries TEXT, country_codes TEXT, certificates TEXT, rating TEXT, votes INTEGER, last_update NUMERIC)', 'e': OperationalError('table imdb_info already exists',), 'fetchone': False}
2019-01-17 14:55:36 ERROR    MAIN :: Error in AddIMDbInfo: table imdb_info already exists
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\db.py", line 488, in _process_upgrade
    instance.execute()
  File "C:\SickChill\SickChill\sickbeard\databases\mainDB.py", line 683, in execute
    "CREATE TABLE imdb_info (tvdb_id INTEGER PRIMARY KEY, imdb_id TEXT, title TEXT, year NUMERIC, akas TEXT, runtimes NUMERIC, genres TEXT, countries TEXT, country_codes TEXT, certificates TEXT, rating TEXT, votes INTEGER, last_update NUMERIC)")
  File "C:\SickChill\SickChill\sickbeard\db.py", line 283, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\SickChill\SickChill\sickbeard\db.py", line 139, in _execute
    sql_results = self.connection.cursor().execute(query)
OperationalError: table imdb_info already exists
2019-01-17 14:55:44 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-01-17 14:55:44 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2019-01-17 14:55:44 DEBUG    MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
2019-01-17 14:55:44 DEBUG    MAIN :: formatting pattern: %SN - S%0SE%0E - %EN -> Show Name - S02E03 - Ep Name
2019-01-17 14:55:44 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-01-17 14:55:44 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2019-01-17 14:55:44 DEBUG    MAIN :: formatting pattern: Season %0S -> Season 02
2019-01-17 14:55:44 DEBUG    MAIN :: Trying to parse Show Name - S02E03 - Ep Name.ext
2019-01-17 14:55:44 DEBUG    MAIN :: Parsed Show Name - S02E03 - Ep Name.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-01-17 14:55:44 DEBUG    MAIN :: The name Show Name - S02E03 - Ep Name.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-01-17 14:55:45 DEBUG    MAIN :: Checking database structure...sickbeard.db
2019-01-17 14:55:45 DEBUG    MAIN :: Database upgrade required: Add Size And Scene Name Fields
2019-01-17 14:55:45 INFO     MAIN :: Backing up database before upgrade
2019-01-17 14:55:45 INFO     MAIN :: Proceeding with upgrade
2019-01-17 14:55:45 INFO     MAIN :: Adding file size to all episodes in DB, please be patient
2019-01-17 14:55:45 INFO     MAIN :: Adding release name to all episodes still in history
2019-01-17 14:55:45 INFO     MAIN :: Adding release name to all episodes with obvious scene filenames
2019-01-17 14:55:45 DEBUG    MAIN :: AddSizeAndSceneNameFields upgrade completed
2019-01-17 14:55:45 DEBUG    MAIN :: Database upgrade required: Rename Season Folders
2019-01-17 14:55:45 INFO     MAIN :: Backing up database before upgrade
2019-01-17 14:55:45 INFO     MAIN :: Proceeding with upgrade
2019-01-17 14:55:45 ERROR    MAIN :: Fatal error executing query with db.action in database C:\SickChill\Data\sickbeard.db: table tv_shows has 17 columns but 18 values were supplied
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\db.py", line 283, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\SickChill\SickChill\sickbeard\db.py", line 139, in _execute
    sql_results = self.connection.cursor().execute(query)
OperationalError: table tv_shows has 17 columns but 18 values were supplied
2019-01-17 14:55:45 INFO     MAIN :: If this happened in cache.db, you can safely stop SickChill, and delete the cache.db file without losing any data
2019-01-17 14:55:45 INFO     MAIN :: Here is the arguments that were passed to this function (This is what the developers need to know): {'fetchall': False, 'attempt': 0, 'severity': 40, 'self': <sickbeard.db.DBConnection object at 0x0000000007113B00>, 'args': None, 'sql_results': [], 'query': u'INSERT INTO tv_shows SELECT * FROM tmp_tv_shows', 'e': OperationalError('table tv_shows has 17 columns but 18 values were supplied',), 'fetchone': False}
2019-01-17 14:55:46 ERROR    MAIN :: Error in RenameSeasonFolders: table tv_shows has 17 columns but 18 values were supplied
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\db.py", line 488, in _process_upgrade
    instance.execute()
  File "C:\SickChill\SickChill\sickbeard\databases\mainDB.py", line 484, in execute
    self.connection.action("INSERT INTO tv_shows SELECT * FROM tmp_tv_shows")
  File "C:\SickChill\SickChill\sickbeard\db.py", line 283, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\SickChill\SickChill\sickbeard\db.py", line 139, in _execute
    sql_results = self.connection.cursor().execute(query)
OperationalError: table tv_shows has 17 columns but 18 values were supplied

```

**Comment by greydawg00** [comment]
edited config.ini  .... debug = 1  
hopefully that turned on debug logs.

Here is sickchill.log

[sickchill.log](https://github.com/SickChill/SickChill/files/2770537/sickchill.log)
