### ISSUE TITLE
[APP SUBMITTED]: displayShow() got an unexpected keyword argument 'status'

### ISSUE THREAD

**Issue by cbinder4** [SickChill/SickChill#5299]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_4 :: [f7a113a] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: displayShow() got an unexpected keyword argument 'status'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by cbinder4** [comment]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_7 :: [f7a113a] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
TypeError: displayShow() got an unexpected keyword argument 'status'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
