### ISSUE TITLE
Updating to SickChill - No such file or directory: u'/sickbeard/cache/mako/layouts/main.mako.py

### ISSUE THREAD

**Issue by mapleleafs89** [SickChill/SickChill#5308]
I was on the old SickRage branch, for months I had the "Local Branch is ahead of master. Automatic update not possible". I found out today about the name dispute and finally came across the new SickChill branch, I followed the steps here to update by remote git url and pull the updates. Now the sickchill service won't startup properly, complaining about the mako layout cache files. Restarting does not fix the issue.

https://github.com/SickChill/SickChill/issues/5022

Branch/Commit:
OS: CentOS7
Browser: Chrome

Logs:
```
Error
[Errno 2] No such file or directory: u'/home/apps/sickbeard/cache/mako/layouts/main.mako.py'

Traceback
Traceback (most recent call last): 
File "/home/apps/sickbeard/lib/tornado/web.py", line 1511, in _execute result = yield result 
File "/home/apps/sickbeard/lib/tornado/gen.py", line 1055, in run value = future.result() 
File "/home/apps/sickbeard/lib/tornado/concurrent.py", line 238, in result raise_exc_info(self._exc_info) 
File "/home/apps/sickbeard/lib/tornado/gen.py", line 1063, in run yielded = self.gen.throw(*exc_info) 
File "/home/apps/sickbeard/sickbeard/webserve.py", line 266, in get 
File "/home/apps/sickbeard/lib/tornado/gen.py", line 1055, in run value = future.result() 
File "/home/apps/sickbeard/lib/concurrent/futures/_base.py", line 455, in result return self.__get_result() 
File "/home/apps/sickbeard/lib/concurrent/futures/thread.py", line 63, in run result = self.fn(*self.args, **self.kwargs) 
File "/home/apps/sickbeard/sickbeard/webserve.py", line 288, in async_call return result 
File "/home/apps/sickbeard/sickbeard/webserve.py", line 493, in schedule title=_('Schedule'), header=_('Schedule'), topmenu='schedule', 
File "/home/apps/sickbeard/sickbeard/webserve.py", line 165, in render return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs) 
File "/home/apps/sickbeard/lib/mako/exceptions.py", line 93, in __init__ self.records = self._init(traceback) 
File "/home/apps/sickbeard/lib/mako/exceptions.py", line 165, in _init module_source = info.code 
File "/home/apps/sickbeard/lib/mako/template.py", line 660, in code return util.read_python_file(self.module_filename) 
File "/home/apps/sickbeard/lib/mako/util.py", line 374, in read_python_file fp = open(path, "rb") 
IOError: [Errno 2] No such file or directory: u'/home/apps/sickbeard/cache/mako/layouts/main.mako.py' 
```

**Comment by mapleleafs89** [comment]
I deleted the cache folder and tried to start again, cache directory was created automatically again but is empty.

**Comment by mapleleafs89** [comment]
I found in the sickchill logs it was actually failing to come up because there was some old sickrage process holding onto the port. Perhaps I forgot to stop it somewhere along the way during the update process. Killed the old process and then it all began working.

2019-01-27 15:09:10 INFO     TORNADO :: Starting SickChill on https://0.0.0.0:8081/
2019-01-27 15:09:10 INFO     TORNADO :: Could not start webserver on port 8081: already in use!
