### ISSUE TITLE
[APP SUBMITTED]: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by janusn** [SickChill/SickChill#5397]
### INFO
Python Version: **2.7.14 (default, May 28 2018, 14:47:18) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-4.4.59+-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickChill/SickChill@f7a113a737654a91076bb42221e119db6258a276
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_3 :: [f7a113a] Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/logger.py", line 391, in submit_errors
    if not report.raw_data['locked']:
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/GithubObject.py", line 97, in raw_data
    self._completeIfNeeded()
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/GithubObject.py", line 255, in _completeIfNeeded
    self.__complete()
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/GithubObject.py", line 260, in __complete
    self._url.value
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 215, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 268, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/github/Requester.py", line 293, in __requestRaw
    requestHeaders
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "/var/packages/python/target/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/var/packages/python/target/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 86, in getaddrinfo_wrapper
    return orig_getaddrinfo(host, port, family, socktype, proto, flags)
gaierror: [Errno -3] Temporary failure in name resolution

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by WebSpider** [comment]
You probably has a problem with your DNS/internet connection

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]**
Operating System: **Linux-4.15.0-51-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [6bfdb22] Traceback (most recent call last):
  File "/home/kevin/.sickrage/sickbeard/logger.py", line 385, in submit_errors
    for report in reports:
  File "/home/kevin/.sickrage/lib/github/PaginatedList.py", line 49, in __iter__
    newElements = self._grow()
  File "/home/kevin/.sickrage/lib/github/PaginatedList.py", line 61, in _grow
    newElements = self._fetchNextPage()
  File "/home/kevin/.sickrage/lib/github/PaginatedList.py", line 163, in _fetchNextPage
    headers=self.__headers
  File "/home/kevin/.sickrage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/home/kevin/.sickrage/lib/github/Requester.py", line 215, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/kevin/.sickrage/lib/github/Requester.py", line 268, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/home/kevin/.sickrage/lib/github/Requester.py", line 293, in __requestRaw
    requestHeaders
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/kevin/.sickrage/sickbeard/helpers.py", line 87, in getaddrinfo_wrapper
    return orig_getaddrinfo(host, port, family, socktype, proto, flags)
gaierror: [Errno -3] Temporary failure in name resolution

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by ahyear** [comment]
### INFO
Python Version: **2.7.15+ (default, Nov 27 2018, 23:36:35) [GCC 7.3.0]**
Operating System: **Linux-4.15.0-51-generic-x86_64-with-Ubuntu-18.04-bionic**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@6bfdb2236003331e639a1845f765ee0462ae8a5d
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [6bfdb22] Traceback (most recent call last):
  File "/home/kevin/.sickrage/sickbeard/logger.py", line 385, in submit_errors
    for report in reports:
  File "/home/kevin/.sickrage/lib/github/PaginatedList.py", line 49, in __iter__
    newElements = self._grow()
  File "/home/kevin/.sickrage/lib/github/PaginatedList.py", line 61, in _grow
    newElements = self._fetchNextPage()
  File "/home/kevin/.sickrage/lib/github/PaginatedList.py", line 163, in _fetchNextPage
    headers=self.__headers
  File "/home/kevin/.sickrage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/home/kevin/.sickrage/lib/github/Requester.py", line 215, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/kevin/.sickrage/lib/github/Requester.py", line 268, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/home/kevin/.sickrage/lib/github/Requester.py", line 293, in __requestRaw
    requestHeaders
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/home/kevin/.sickrage/sickbeard/helpers.py", line 87, in getaddrinfo_wrapper
    return orig_getaddrinfo(host, port, family, socktype, proto, flags)
gaierror: [Errno -3] Temporary failure in name resolution

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
