### ISSUE TITLE
Yggtorrent manual search error

### ISSUE THREAD

**Issue by Hydro8** [SickChill/SickChill#5427]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / b3da866  
OS: windows 10
Browser: brave
What you did: fresh install, add one provider, add one show and manual search for an episode
What happened: errors in log
What you expected: finding torrent or some results on log
Logs:
```

2019-04-16 18:58:30 INFO     ThreadPoolExecutor-0_1 :: Updating scene exceptions
2019-04-16 18:59:11 INFO     SEARCHQUEUE-MANUAL-253573 :: Beginning manual search for: [American Gods - S02E04 - The Greatest Story Ever Told]
2019-04-16 18:59:12 INFO     SEARCHQUEUE-MANUAL-253573 :: [YggTorrent] :: Request failed: 401 Client Error: Unauthorized for url: https://www2.yggtorrent.gg/user/login (<type 'str'>)
2019-04-16 18:59:12 ERROR    SEARCHQUEUE-MANUAL-253573 :: [YggTorrent] :: [b3da866] Failed parsing provider YggTorrent.
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\providers\yggtorrent.py", line 156, in search
    self.login()
  File "C:\SickChill\SickChill\sickbeard\providers\yggtorrent.py", line 92, in login
    if self.url not in response.url:
AttributeError: 'NoneType' object has no attribute 'url'
2019-04-16 18:59:12 INFO     SEARCHQUEUE-MANUAL-253573 :: [YggTorrent] :: Performing episode search for American Gods
2019-04-16 18:59:12 INFO     SEARCHQUEUE-MANUAL-253573 :: [YggTorrent] :: Request failed: 401 Client Error: Unauthorized for url: https://www2.yggtorrent.gg/user/login (<type 'str'>)
2019-04-16 18:59:12 ERROR    SEARCHQUEUE-MANUAL-253573 :: [YggTorrent] :: [b3da866] Failed parsing provider YggTorrent.
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\providers\yggtorrent.py", line 156, in search
    self.login()
  File "C:\SickChill\SickChill\sickbeard\providers\yggtorrent.py", line 92, in login
    if self.url not in response.url:
AttributeError: 'NoneType' object has no attribute 'url'
```
Thank for your help.

**Comment by ninovanhooff** [comment]
I suggest that you create a pull request for this, since the fix should be simply changing that number in the url

**Comment by WebSpider** [comment]
Did you add credentials for yggtorrent?

**Comment by Hydro8** [comment]
Yes
