### ISSUE TITLE
SickChill Not Downloading from HD-Torrents

### ISSUE THREAD

**Issue by seesalt** [SickChill/SickChill#5453]
What you did: Trying to fetch from HD-Torrents
What happened: `tuple indices must be integers, not str`
What you expected: Download in my client
Tried Rarbg as source, that worked just fine.
Logs:
```
2019-05-04 00:01:09 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Search Mode: RSS
2019-05-04 00:01:09 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Error while searching HDTorrents, skipping: TypeError('tuple indices must be integers, not str',)
2019-05-04 00:01:09 INFO     SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Performing episode search for Brooklyn Nine-Nine
2019-05-04 00:01:09 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Using cached parse result for: Brooklyn.Nine-Nine.S06E15.Return.of.the.King.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
2019-05-04 00:01:09 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Any,Best = [ 720p HDTV, 1080p HDTV, 1080p WEB-DL, 1080p BluRay ] [ 1080p WEB-DL, 1080p BluRay ] Found = [ 1080p WEB-DL ]
2019-05-04 00:01:09 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Existing episode status is 'Wanted', getting found result for Brooklyn Nine-Nine S06E15 with quality 1080p WEB-DL
2019-05-04 00:01:09 INFO     SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Found result Brooklyn.Nine-Nine.S06E15.Return.of.the.King.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb at https://hd-torrents.org/download.php?id=c8eac36517c9032bc8efab687a7324b1da3f9412&f=Brooklyn+Nine-Nine+S06E15+Return+of+the+King+1080p+AMZN+WEB-DL+DDP5+1+H+264-NTb.torrent
2019-05-04 00:01:09 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Using cached parse result for: Brooklyn.Nine-Nine.S06E15.Return.of.the.King.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb
2019-05-04 00:01:09 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Any,Best = [ 720p HDTV, 1080p HDTV, 1080p WEB-DL, 1080p BluRay ] [ 1080p WEB-DL, 1080p BluRay ] Found = [ 720p WEB-DL ]
2019-05-04 00:01:09 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Don't want this quality, ignoring found result for Brooklyn Nine-Nine S06E15 with quality 720p WEB-DL
2019-05-04 00:01:09 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Ignoring Brooklyn.Nine-Nine.S06E15.Return.of.the.King.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb
2019-05-04 00:01:10 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: The highest quality of any match is 1080p WEB-DL
2019-05-04 00:01:10 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Picking the best result out of [u'Brooklyn.Nine-Nine.S06E15.Return.of.the.King.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb']
2019-05-04 00:01:10 INFO     SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Quality of Brooklyn.Nine-Nine.S06E15.Return.of.the.King.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb is 1080p WEB-DL
2019-05-04 00:01:10 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Picked Brooklyn.Nine-Nine.S06E15.Return.of.the.King.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb as the best
2019-05-04 00:01:10 DEBUG    SEARCHQUEUE-MANUAL-269586 :: [HDTorrents] :: Checking if we should keep searching after we've found Brooklyn.Nine-Nine.S06E15.Return.of.the.King.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb
2019-05-04 00:01:10 INFO     SEARCHQUEUE-MANUAL-269586 :: Downloading Brooklyn.Nine-Nine.S06E15.Return.of.the.King.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb from HDTorrents
2019-05-04 00:01:10 DEBUG    SEARCHQUEUE-MANUAL-269586 :: Traceback (most recent call last):
  File "/home/hd23/*******/apps/sickrage/sickbeard/search_queue.py", line 182, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "/home/hd23/*******/apps/sickrage/sickbeard/search.py", line 127, in snatchEpisode
    result.content = result.provider.get_url(result.url, returns='content')
  File "/home/hd23/*******/apps/sickrage/sickchill/providers/GenericProvider.py", line 372, in get_url
    return getURL(url, post_data, params, self.headers, timeout, self.session, **kwargs)
  File "/home/hd23/*******/apps/sickrage/sickbeard/helpers.py", line 1465, in getURL
    handle_requests_exception(error)
  File "/home/hd23/*******/apps/sickrage/sickbeard/helpers.py", line 1578, in handle_requests_exception
    logger.log(default.format(error, type(error.__class__.__name__)), get_level(error))
  File "/home/hd23/*******/apps/sickrage/sickbeard/helpers.py", line 1522, in get_level
    return (logger.ERROR, logger.WARNING)[exception.message and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception.message]
TypeError: tuple indices must be integers, not str
```

**Comment by marcb1387** [comment]
`2019-05-08` 10:03:48 SEARCHQUEUE-BACKLOG-269586 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:58:55 SEARCHQUEUE-BACKLOG-226391 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:58:00 SEARCHQUEUE-BACKLOG-287036 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:57:20 SEARCHQUEUE-BACKLOG-77038 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:52:29 SEARCHQUEUE-BACKLOG-81472 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:44:37 SEARCHQUEUE-BACKLOG-78645 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:43:47 SEARCHQUEUE-BACKLOG-77960 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:40:57 SEARCHQUEUE-BACKLOG-79275 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:39:21 SEARCHQUEUE-BACKLOG-250734 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:38:55 SEARCHQUEUE-BACKLOG-76115 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:36:26 SEARCHQUEUE-BACKLOG-335717 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:36:11 SEARCHQUEUE-BACKLOG-272472 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:35:15 SEARCHQUEUE-BACKLOG-300921 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:34:55 SEARCHQUEUE-BACKLOG-77995 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:32:31 SEARCHQUEUE-BACKLOG-76666 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:28:16 SEARCHQUEUE-BACKLOG-78419 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:26:40 SEARCHQUEUE-BACKLOG-251085 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:26:00 SEARCHQUEUE-BACKLOG-79349 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:24:26 SEARCHQUEUE-BACKLOG-77398 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:24:10 SEARCHQUEUE-BACKLOG-71492 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:22:18 SEARCHQUEUE-BACKLOG-75729 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:21:24 SEARCHQUEUE-BACKLOG-76386 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:21:14 SEARCHQUEUE-BACKLOG-168571 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:20:28 SEARCHQUEUE-BACKLOG-75886 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:10:53 SEARCHQUEUE-BACKLOG-337149 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:10:44 SEARCHQUEUE-BACKLOG-270550 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:10:38 SEARCHQUEUE-BACKLOG-318453 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:10:21 SEARCHQUEUE-BACKLOG-75805 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:08:32 SEARCHQUEUE-BACKLOG-247808 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:05:55 SEARCHQUEUE-BACKLOG-334147 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:05:40 SEARCHQUEUE-BACKLOG-121361 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:05:25 SEARCHQUEUE-BACKLOG-289574 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-08 09:05:19 SEARCHQUEUE-BACKLOG-76177 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-07 21:06:09 SEARCHQUEUE-BACKLOG-317479 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-07 21:05:56 SEARCHQUEUE-BACKLOG-279121 :: [HDTorrents] :: [b3da866] Exception while searching HDTorrents. Error: TypeError('tuple indices must be integers, not str',)
2019-05-07 21:04:40 FINDPROPERS :: [HDTorrents] :: [HDTorrents] :: [b3da866] Exception while searching propers in HDTorrents, skipping: tuple indices must be integers, not str``

Here are the errors i am getting with this as well

**Comment by WebSpider** [comment]
Please update, this was related to an outdated component
