### ISSUE TITLE
2019-05-06 11:57:28 SEARCHQUEUE-MANUAL-121361 :: [TorrentLeech] :: [b3da866] Exception while searching TorrentLeech. Error: TypeError('tuple indices must be integers, not str',)

### ISSUE THREAD

**Issue by Mozziimo** [SickChill/SickChill#5458]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master / Version: v2019.04.07-1
OS: Windows 10
Browser: Google Chrome
What you did: Manual Search for an Epesoide
What happened: Error popped up with the following; (See Below)
What you expected: Epesoide to be found (confirmed manually it is available in the torrent providor)
Logs:
```
2019-05-06 11:59:38 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /volume1/Transmission/Sickchill completed
2019-05-06 11:59:38 INFO POSTPROCESSOR-AUTO :: Successfully processed
2019-05-06 11:59:34 INFO POSTPROCESSOR-AUTO :: Processing /volume1/Transmission/Sickchill
2019-05-06 11:59:34 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /volume1/Transmission/Sickchill
2019-05-06 11:59:30 INFO POSTPROCESSOR :: Auto post processing task for /volume1/Transmission/Sickchill was added to the queue
2019-05-06 11:57:28 INFO SEARCHQUEUE-MANUAL-121361 :: Unable to find a download for: [Game of Thrones - S08E04 - ]
2019-05-06 11:57:28 INFO SEARCHQUEUE-MANUAL-121361 :: [TorrentLeech] :: No NZB/Torrent providers found or enabled in the sickchill config for backlog searches. Please check your settings.
AA TypeError: tuple indices must be integers, not str
AA return (logger.ERROR, logger.WARNING)[exception.message and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception.message]
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1522, in get_level
AA logger.log(default.format(error, type(error.__class__.__name__)), get_level(error))
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1578, in handle_requests_exception
AA handle_requests_exception(error)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1465, in getURL
AA return getURL(url, post_data, params, self.headers, timeout, self.session, **kwargs)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickchill/providers/GenericProvider.py", line 372, in get_url
AA data = self.get_url(search_url, returns='json')
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/torrentleech.py", line 115, in search
AA items_list += self.search(search_string, ep_obj=episode)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickchill/providers/GenericProvider.py", line 170, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 474, in searchProviders
AA Traceback (most recent call last):
2019-05-06 11:57:28 ERROR SEARCHQUEUE-MANUAL-121361 :: [TorrentLeech] :: [b3da866] Exception while searching TorrentLeech. Error: TypeError('tuple indices must be integers, not str',)
2019-05-06 11:57:27 INFO SEARCHQUEUE-MANUAL-121361 :: [TorrentLeech] :: Performing episode search for Game of Thrones
2019-05-06 11:57:27 INFO SEARCHQUEUE-MANUAL-121361 :: Beginning manual search for: [Game of Thrones - S08E04 - ]
2019-05-06 11:54:38 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
```

**Comment by waltermaldonado** [comment]
Just for the record, my SickChill also is not searching TorrentLeech torrents. I think now an API key is needed...
