### ISSUE TITLE
SickChill will not start

### ISSUE THREAD

**Issue by zunder1990** [SickChill/SickChill#5463]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: [master] Upgrade cfscrape to version 1.9.7 (#5405)
OS: Ubuntu 18.04.2 LTS
Browser: Chrome
What you did:
The server was been online for about 100 days, I did OS update and reboot. It was working before the reboot. 
What happened:
Failed to start SickChill Daemon
What you expected:
Should have started
Logs:
```
May 08 09:41:52 homeserver python2.7[26711]: Traceback (most recent call last):
May 08 09:41:52 homeserver python2.7[26711]:   File "/opt/sickchill/SickBeard.py", line 72, in <module>
May 08 09:41:52 homeserver python2.7[26711]:     from sickbeard.webserveInit import SRWebServer
May 08 09:41:52 homeserver python2.7[26711]:   File "/opt/sickchill/sickbeard/webserveInit.py", line 10, in <module>
May 08 09:41:52 homeserver python2.7[26711]:     from tornado.web import Application, RedirectHandler, StaticFileHandler
May 08 09:41:52 homeserver python2.7[26711]:   File "/opt/sickchill/lib/tornado/web.py", line 85, in <module>
May 08 09:41:52 homeserver python2.7[26711]:     from tornado import gen
May 08 09:41:52 homeserver python2.7[26711]:   File "/opt/sickchill/lib/tornado/gen.py", line 1298, in <module>
May 08 09:41:52 homeserver python2.7[26711]:     import tornado.platform.asyncio
May 08 09:41:52 homeserver python2.7[26711]:   File "/opt/sickchill/lib/tornado/platform/asyncio.py", line 33, in <module
May 08 09:41:52 homeserver python2.7[26711]:     import asyncio  # type: ignore
May 08 09:41:52 homeserver python2.7[26711]:   File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9,
May 08 09:41:52 homeserver python2.7[26711]:     from . import selectors
May 08 09:41:52 homeserver python2.7[26711]:   File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 3
May 08 09:41:52 homeserver python2.7[26711]:     "{!r}".format(fileobj)) from None
May 08 09:41:52 homeserver python2.7[26711]:                                ^
May 08 09:41:52 homeserver python2.7[26711]: SyntaxError: invalid syntax
May 08 09:41:52 homeserver systemd[1]: sickchill.service: Control process exited, code=exited status=1
May 08 09:41:52 homeserver systemd[1]: sickchill.service: Failed with result 'exit-code'.
May 08 09:41:52 homeserver systemd[1]: Failed to start SickChill Daemon.

```

**Comment by zunder1990** [comment]
$ sudo pip2 uninstall asyncio
$ sudo pip2 install trollius

That was the fix
found ti here https://github.com/jupyter/notebook/issues/824
