### ISSUE TITLE
SC not downloading => exception.message and 's,t,o,p,b,r,e,a,k,i,n,g,f

### ISSUE THREAD

**Issue by jura4** [SickChill/SickChill#5489]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
Branch: master
Commit: 175df89cabf295358b8caa2d96dafadb2347622d
Version: v2019.05.15-3

Database Version: 44.0
OS: Linux-2.6.32.12-armv5tel-with-glibc2.4
Browser: Vivaldi

What you did:  Nothing, 
What happened: SC stoppend downloading end of March. Hasn't gotten it back working again. Updates were not coming in since then. But I didn't notice any commits either untill recent commit that reactivaed an update. I was hoping it would resolve my issue. Been Checking the debug logs, and the only thing that slightly resembles and error message is here posted underneath. This was when I manually activaed the search for Greys Anatomy S15E25. 
What you expected: That downloading would work. 

Any help is highly appriciated guys. I'm stuck. Thanks in advance.

Logs:
```
PASTE LOGS HERE
```
2019-05-19 18:33:12 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2019-05-19 18:33:09 INFO DAILYSEARCHER :: No new released episodes found ...
2019-05-19 18:33:09 INFO DAILYSEARCHER :: Searching for new released episodes ...
2019-05-19 18:31:30 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /volume1/Videos/downloads completed
2019-05-19 18:31:30 INFO POSTPROCESSOR-AUTO :: /volume1/Videos/downloads/torrent/@eaDir : Hidden folder
2019-05-19 18:31:30 INFO POSTPROCESSOR-AUTO :: Some items were not processed.
2019-05-19 18:31:30 INFO POSTPROCESSOR-AUTO :: Successfully processed
2019-05-19 18:31:23 INFO POSTPROCESSOR-AUTO :: Processing /volume1/Videos/downloads
2019-05-19 18:31:23 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /volume1/Videos/downloads
2019-05-19 18:31:18 INFO POSTPROCESSOR :: Auto post processing task for /volume1/Videos/downloads was added to the queue
AA TypeError: tuple indices must be integers, not str
AA return (logger.ERROR, logger.WARNING)[exception.message and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception.message]
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1522, in get_level
AA logger.log(default.format(error, type(error.__class__.__name__)), get_level(error))
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1578, in handle_requests_exception
AA handle_requests_exception(error)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1514, in download_file
AA hooks={'response': self.get_url_hook}, return_filename=True)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickchill/providers/GenericProvider.py", line 119, in download_result
AA newResult = resProvider.download_result(result)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 52, in _downloadResult
AA dlResult = _downloadResult(result)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 123, in snatchEpisode
AA self.success = search.snatchEpisode(searchResult[0])
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search_queue.py", line 182, in run
2019-05-19 18:26:13 INFO SEARCHQUEUE-MANUAL-73762 :: Downloading a result from Rarbg at http://itorrents.org/torrent/CB4DFBA10A16F378EBE80BA2A241C298009E44A9.torrent
2019-05-19 18:26:13 INFO SEARCHQUEUE-MANUAL-73762 :: Downloading Greys.Anatomy.S15E25.HDTV.x264-KILLERS[rartv] from Rarbg
2019-05-19 18:26:13 INFO SEARCHQUEUE-MANUAL-73762 :: [Rarbg] :: Quality of Greys.Anatomy.S15E25.WEBRip.x264-ION10 is SDTV
2019-05-19 18:26:13 INFO SEARCHQUEUE-MANUAL-73762 :: [Rarbg] :: Quality of Greys.Anatomy.S15E25.WEBRip.x264-ION10 is SDTV
2019-05-19 18:26:13 INFO SEARCHQUEUE-MANUAL-73762 :: [Rarbg] :: Quality of Greys.Anatomy.S15E25.HDTV.x264-KILLERS[rartv] is SDTV
2019-05-19 18:26:13 INFO SEARCHQUEUE-MANUAL-73762 :: [Rarbg] :: Quality of Greys.Anatomy.S15E25.HDTV.x264-KILLERS[rartv] is SDTV
2019-05-19 18:25:43 INFO SEARCHQUEUE-MANUAL-73762 :: [Rarbg] :: Performing episode search for Grey's Anatomy
2019-05-19 18:21:26 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /volume1/Videos/downloads completed
2019-05-19 18:21:26 INFO POSTPROCESSOR-AUTO :: /volume1/Videos/downloads/torrent/@eaDir : Hidden folder

**Comment by miigotu** [comment]
You need to update, thats all

**Comment by jura4** [comment]
Thank you for the reply miigotu,

Unfortunatly still not working. Not sure if it's a bug, but I'm realy stuck here. Fully up to date and no avail.

2019-05-28 21:07:41 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /volume1/Videos/downloads completed
2019-05-28 21:07:41 INFO POSTPROCESSOR-AUTO :: /volume1/Videos/downloads/torrent/@eaDir : Hidden folder
2019-05-28 21:07:41 INFO POSTPROCESSOR-AUTO :: Some items were not processed.
2019-05-28 21:07:41 INFO POSTPROCESSOR-AUTO :: Successfully processed
2019-05-28 21:07:41 DEBUG POSTPROCESSOR-AUTO :: Ignoring hidden folder: /volume1/Videos/downloads/torrent/@eaDir
2019-05-28 21:07:41 DEBUG POSTPROCESSOR-AUTO :: Processing folder /volume1/Videos/downloads/torrent/@eaDir
2019-05-28 21:07:40 DEBUG POSTPROCESSOR-AUTO :: /volume1/Videos/downloads/torrent : No processable items found in folder
2019-05-28 21:07:37 DEBUG POSTPROCESSOR-AUTO :: Processing folder /volume1/Videos/downloads/torrent
2019-05-28 21:07:37 DEBUG POSTPROCESSOR-AUTO :: /volume1/Videos/downloads/cache : No processable items found in folder
2019-05-28 21:07:37 DEBUG POSTPROCESSOR-AUTO :: Processing folder /volume1/Videos/downloads/cache
2019-05-28 21:07:37 DEBUG POSTPROCESSOR-AUTO :: /volume1/Videos/downloads : No processable items found in folder
2019-05-28 21:07:35 DEBUG POSTPROCESSOR-AUTO :: Processing folder /volume1/Videos/downloads
2019-05-28 21:07:35 INFO POSTPROCESSOR-AUTO :: Processing /volume1/Videos/downloads
2019-05-28 21:07:35 DEBUG POSTPROCESSOR-AUTO :: Processing in folder /volume1/Videos/downloads
2019-05-28 21:07:35 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /volume1/Videos/downloads
2019-05-28 21:07:33 INFO POSTPROCESSOR :: Auto post processing task for /volume1/Videos/downloads was added to the queue
2019-05-28 21:07:33 DEBUG POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
AA TypeError: tuple indices must be integers, not str
AA return (logger.ERROR, logger.WARNING)[exception.message and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception.message]
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1519, in get_level
AA logger.log(default.format(error, type(error.__class__.__name__)), get_level(error))
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1575, in handle_requests_exception
AA handle_requests_exception(error)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 1511, in download_file
AA hooks={'response': self.get_url_hook}, return_filename=True)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickchill/providers/GenericProvider.py", line 119, in download_result
AA newResult = resProvider.download_result(result)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 52, in _downloadResult
AA dlResult = _downloadResult(result)
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search.py", line 123, in snatchEpisode
AA self.success = search.snatchEpisode(searchResult[0])
AA File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/search_queue.py", line 182, in run
2019-05-28 21:03:40 DEBUG SEARCHQUEUE-MANUAL-295647 :: Traceback (most recent call last):
2019-05-28 21:03:38 INFO SEARCHQUEUE-MANUAL-295647 :: Downloading a result from Rarbg at http://itorrents.org/torrent/7877CF712D1BB900D1058FEFD8F4F24223C9EBF3.torrent
2019-05-28 21:03:38 INFO SEARCHQUEUE-MANUAL-295647 :: Request failed: 404 Client Error: Not Found for url: http://btdig.com/torrent/7877CF712D1BB900D1058FEFD8F4F24223C9EBF3.torrent ()
2019-05-28 21:03:37 INFO SEARCHQUEUE-MANUAL-295647 :: Downloading a result from Rarbg at http://btdig.com/torrent/7877CF712D1BB900D1058FEFD8F4F24223C9EBF3.torrent
2019-05-28 21:03:37 INFO SEARCHQUEUE-MANUAL-295647 :: Request failed: 522 Server Error: Origin Connection Time-out for url: http://torrentproject.se/torrent/7877CF712D1BB900D1058FEFD8F4F24223C9EBF3.torrent ()
2019-05-28 21:03:22 INFO SEARCHQUEUE-MANUAL-295647 :: Downloading a result from Rarbg at http://torrentproject.se/torrent/7877CF712D1BB900D1058FEFD8F4F24223C9EBF3.torrent
2019-05-28 21:03:22 INFO SEARCHQUEUE-MANUAL-295647 :: Request failed: 404 Client Error: Not Found for url: http://thetorrent.org/torrent/7877CF712D1BB900D1058FEFD8F4F24223C9EBF3.torrent ()
2019-05-28 21:03:22 INFO SEARCHQUEUE-MANUAL-295647 :: Downloading a result from Rarbg at http://thetorrent.org/torrent/7877CF712D1BB900D1058FEFD8F4F24223C9EBF3.torrent
2019-05-28 21:03:21 INFO SEARCHQUEUE-MANUAL-295647 :: Downloading Blindspot.S04E20.HDTV.x264-SVA[rartv] from Rarbg
2019-05-28 21:03:21 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Checking if we should keep searching after we've found Blindspot.S04E20.HDTV.x264-SVA[rartv]
2019-05-28 21:03:21 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Picked Blindspot.S04E20.HDTV.x264-SVA[rartv] as the best
2019-05-28 21:03:21 INFO SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Quality of Blindspot.S04E20.WEBRip.x264-ION10 is SDTV
2019-05-28 21:03:21 INFO SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Quality of Blindspot.S04E20.HDTV.x264-SVA[rartv] is SDTV
2019-05-28 21:03:21 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Picking the best result out of [u'Blindspot.S04E20.HDTV.x264-SVA[rartv]', u'Blindspot.S04E20.WEBRip.x264-ION10']
2019-05-28 21:03:21 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: The highest quality of any match is SDTV
2019-05-28 21:03:21 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Single episode result.
2019-05-28 21:03:21 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Found result Blindspot.S04E20.WEBRip.x264-ION10 at magnet:?xt=urn:btih:3c34f15ac081dcb128159f791bcd8508a3645f19&dn=Blindspot.S04E20.WEBRip.x264-ION10&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce
2019-05-28 21:03:21 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Existing episode status is 'Wanted', getting found result for Blindspot S04E20 with quality SDTV
2019-05-28 21:03:21 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ SDTV ]
2019-05-28 21:03:21 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Using cached parse result for: Blindspot.S04E20.WEBRip.x264-ION10
2019-05-28 21:03:21 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Single episode result.
2019-05-28 21:03:21 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Found result Blindspot.S04E20.HDTV.x264-SVA[rartv] at magnet:?xt=urn:btih:7877cf712d1bb900d1058fefd8f4f24223c9ebf3&dn=Blindspot.S04E20.HDTV.x264-SVA%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce
2019-05-28 21:03:21 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Existing episode status is 'Wanted', getting found result for Blindspot S04E20 with quality SDTV
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ SDTV ]
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Using cached parse result for: Blindspot.S04E20.HDTV.x264-SVA[rartv]
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Ignoring result Blindspot.S04E20.720p.HDTV.x264-AVS[rartv].
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Don't want this quality, ignoring found result for Blindspot S04E20 with quality 720p HDTV
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ 720p HDTV ]
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Using cached parse result for: Blindspot.S04E20.720p.HDTV.x264-AVS[rartv]
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Ignoring result Blindspot.S04E20.iNTERNAL.720p.WEB.H264-AMRAP[rartv].
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Don't want this quality, ignoring found result for Blindspot S04E20 with quality 720p WEB-DL
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ 720p WEB-DL ]
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Using cached parse result for: Blindspot.S04E20.iNTERNAL.720p.WEB.H264-AMRAP[rartv]
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Ignoring result Blindspot.S04E20.iNTERNAL.720p.WEB.h264-BAMBOOZLE[rartv].
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Don't want this quality, ignoring found result for Blindspot S04E20 with quality 720p WEB-DL
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ 720p WEB-DL ]
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Using cached parse result for: Blindspot.S04E20.iNTERNAL.720p.WEB.h264-BAMBOOZLE[rartv]
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Ignoring result Blindspot.S04E20.Coder.to.Killer.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv].
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Don't want this quality, ignoring found result for Blindspot S04E20 with quality 720p WEB-DL
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ 720p WEB-DL ]
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Using cached parse result for: Blindspot.S04E20.Coder.to.Killer.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv]
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Ignoring result Blindspot.S04E20.Coder.to.Killer.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv].
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Don't want this quality, ignoring found result for Blindspot S04E20 with quality 1080p WEB-DL
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ 1080p WEB-DL ]
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Using cached parse result for: Blindspot.S04E20.Coder.to.Killer.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv]
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Ignoring result Blindspot.S04E20.1080p.WEB.H264-AMCON[rartv].
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Don't want this quality, ignoring found result for Blindspot S04E20 with quality 1080p WEB-DL
2019-05-28 21:03:20 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ 1080p WEB-DL ]
2019-05-28 21:03:19 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Using cached parse result for: Blindspot.S04E20.1080p.WEB.H264-AMCON[rartv]
2019-05-28 21:03:19 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Found result: Blindspot.S04E20.iNTERNAL.720p.WEB.H264-AMRAP[rartv] with 23 seeders and 4 leechers
2019-05-28 21:03:19 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Found result: Blindspot.S04E20.iNTERNAL.720p.WEB.h264-BAMBOOZLE[rartv] with 40 seeders and 2 leechers
2019-05-28 21:03:19 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Found result: Blindspot.S04E20.Coder.to.Killer.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv] with 76 seeders and 10 leechers
2019-05-28 21:03:19 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Found result: Blindspot.S04E20.Coder.to.Killer.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv] with 115 seeders and 10 leechers
2019-05-28 21:03:19 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Found result: Blindspot.S04E20.1080p.WEB.H264-AMCON[rartv] with 161 seeders and 10 leechers
2019-05-28 21:03:19 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Found result: Blindspot.S04E20.WEBRip.x264-ION10 with 236 seeders and 22 leechers
2019-05-28 21:03:19 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Found result: Blindspot.S04E20.HDTV.x264-SVA[rartv] with 364 seeders and 20 leechers
2019-05-28 21:03:19 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Found result: Blindspot.S04E20.720p.HDTV.x264-AVS[rartv] with 507 seeders and 35 leechers
2019-05-28 21:03:19 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: GET URL: http://torrentapi.org/pubapi_v2.php?sort=seeders&min_leechers=0&min_seeders=1&search_tvdb=295647&app_id=sickchill&search_string=Blindspot+S04E20&ranked=1&category=tv&format=json_extended&token=dr83b6i5av&limit=100&mode=search [Status: 200]
2019-05-28 21:03:17 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Search string: Blindspot S04E20
2019-05-28 21:03:17 DEBUG SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Search Mode: Episode
2019-05-28 21:03:17 INFO SEARCHQUEUE-MANUAL-295647 :: [Rarbg] :: Performing episode search for Blindspot
2019-05-28 21:03:16 DEBUG SEARCHQUEUE-MANUAL-295647 :: [ThePirateBay] :: Last update was too soon, using old cache: 2019-05-28 20:45:10. Updated less then 30 minutes ago
2019-05-28 21:03:16 DEBUG SEARCHQUEUE-MANUAL-295647 :: [LimeTorrents] :: Unable to match Taj.Mahal.-.Taj.Mahal.(1968;.2017.Japan).[Z3K] to a show in your database. Parser result: Taj Mahal - Taj Mahal ( - [ABS: [196]] [ANIME VER: -1] [ABD: False] [ANIME: True] [whichReg: [u'anime_codec_crc']]

**Comment by miigotu** [comment]
@pro-src this is also due to cloudflare, probably because of no custom ciphers.
http://itorrents.org/torrent/7877CF712D1BB900D1058FEFD8F4F24223C9EBF3.torrent

**Comment by pro-src** [comment]
Indeed, https://github.com/Anorov/cloudflare-scrape/issues/259#issuecomment-497279016

**Comment by jura4** [comment]
Could you elaborate, can't seem to get SC working. Is there something I can add/change or do I need to wait for an update ? 

Thanks a lot in advance ! 

J
