### ISSUE TITLE
[APP SUBMITTED]: unindent does not match any outer indentation level (viewlogs.mako.py, line 98)

### ISSUE THREAD

**Issue by jaggeddragon** [SickChill/SickChill#5496]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.17763**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@9ae2c845db7315015ae07f3f486661a62947a288
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [9ae2c84] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickChill\SickChill\sickbeard\webserve.py", line 5287, in viewlog
    t = PageTemplate(rh=self, filename="viewlogs.mako")
  File "C:\SickChill\SickChill\sickbeard\webserve.py", line 114, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 258, in get_template
    return self._load(srcfile, uri)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 323, in _load
    **self.template_args)
  File "C:\SickChill\SickChill\lib\mako\template.py", line 338, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickChill\SickChill\lib\mako\template.py", line 396, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "C:\SickChill\SickChill\lib\mako\compat.py", line 90, in load_module
    return imp.load_source(module_id, path, fp)
  File "C:\SickChill\Data\cache\mako\viewlogs.mako.py", line 98
    __M_writer(u'                    </select>\r\n                    &nbsp;\r\n                </label>\r\n                <label>\r\n                    <span>')
                                                                                                                                                                  ^
IndentationError: unindent does not match any outer indentation level

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by jaggeddragon** [comment]
Error appears upon attempting to clear errors...




Error
unindent does not match any outer indentation level (viewlogs.mako.py, line 98)

Traceback
Traceback (most recent call last): 
File "C:\SickChill\SickChill\lib\tornado\web.py", line 1511, in _execute result = yield result 
File "C:\SickChill\SickChill\lib\tornado\gen.py", line 1055, in run value = future.result() 
File "C:\SickChill\SickChill\lib\tornado\concurrent.py", line 238, in result raise_exc_info(self._exc_info) 
File "C:\SickChill\SickChill\lib\tornado\gen.py", line 1063, in run yielded = self.gen.throw(*exc_info) 
File "C:\SickChill\SickChill\sickbeard\webserve.py", line 265, in get results = yield self.async_call(method) 
File "C:\SickChill\SickChill\lib\tornado\gen.py", line 1055, in run value = future.result() 
File "C:\SickChill\SickChill\lib\concurrent\futures\_base.py", line 455, in result return self.__get_result() 
File "C:\SickChill\SickChill\lib\concurrent\futures\thread.py", line 63, in run result = self.fn(*self.args, **self.kwargs) 
File "C:\SickChill\SickChill\sickbeard\webserve.py", line 287, in async_call result = function(**kwargs) 
File "C:\SickChill\SickChill\sickbeard\webserve.py", line 5287, in viewlog t = PageTemplate(rh=self, filename="viewlogs.mako") 
File "C:\SickChill\SickChill\sickbeard\webserve.py", line 114, in __init__ self.template = lookup.get_template(filename) 
File "C:\SickChill\SickChill\lib\mako\lookup.py", line 258, in get_template return self._load(srcfile, uri) 
File "C:\SickChill\SickChill\lib\mako\lookup.py", line 323, in _load **self.template_args) 
File "C:\SickChill\SickChill\lib\mako\template.py", line 338, in __init__ module = self._compile_from_file(path, filename) 
File "C:\SickChill\SickChill\lib\mako\template.py", line 396, in _compile_from_file module = compat.load_module(self.module_id, path) 
File "C:\SickChill\SickChill\lib\mako\compat.py", line 90, in load_module return imp.load_source(module_id, path, fp) 
File "C:\SickChill\Data\cache\mako\viewlogs.mako.py", line 98 
__M_writer(u' \r\n  \r\n \r\n \r\n ') 
^ 
IndentationError: unindent does not match any outer indentation level 

Request Info
body: 
files: {}
protocol: http
connection: 
body_arguments: {}
uri: /errorlogs/viewlog/
query_arguments: {}
_start_time: 1558581926.78
headers: Accept-Language: en-US,en;q=0.9 Accept-Encoding: gzip, deflate, br Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36 Dnt: 1 Host: 127.0.0.1:8081 Referer: http://127.0.0.1:8081/errorlogs/ Cookie: sr_access_token="2|1:0|10:1558198333|15:sr_access_token|1988:...==|..."; sr_refresh_token="2|1:0|10:1558198333|16:sr_refresh_token|1204:...=|..." Upgrade-Insecure-Requests: 1 
host: 127.0.0.1:8081
version: HTTP/1.1
server_connection: 
host_name: 127.0.0.1
_finish_time: None
query: 
arguments: {}
path: /errorlogs/viewlog/
method: GET
remote_ip: 127.0.0.1
