### ISSUE TITLE
Cloudflare captcha challenge

### ISSUE THREAD

**Issue by flobafff** [SickChill/SickChill#5497]
Branch: master
Commit: 9ae2c845db7315015ae07f3f486661a62947a288
OS: Linux-4.19.42+-armv6l-with-debian-9.9
Browser: Chrome
What you did: During SEARCHQUEUE-MANUAL
What happened:  When I do a torrent search, I get the following message:
(For information, I use raspbian)

Request failed: Cloudflare captcha challenge presented for www.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)

Logs:

2019-05-23 13:24:25 DEBUG    SEARCHQUEUE-MANUAL-268592 :: formatting pattern: %SN - S%0SE%0E - %EN -> Les 100 - S06E04 - The Face Behind the Glass
2019-05-23 13:24:25 INFO     SEARCHQUEUE-MANUAL-268592 :: Beginning manual search for: [Les 100 - S06E04 - The Face Behind the Glass]
2019-05-23 13:24:25 DEBUG    SEARCHQUEUE-MANUAL-268592 :: [Torrent9] :: Search Mode: RSS
2019-05-23 13:24:40 ERROR    SEARCHQUEUE-MANUAL-268592 :: [Torrent9] :: [9ae2c84] Request failed: Cloudflare captcha challenge presented for www.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
Traceback (most recent call last):
  File "/opt/sickchill/sickbeard/helpers.py", line 1523, in handle_requests_exception
    raise requests_exception
CloudflareCaptchaError: Cloudflare captcha challenge presented for www.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python.
2019-05-23 13:24:40 DEBUG    SEARCHQUEUE-MANUAL-268592 :: [Torrent9] :: Traceback (most recent call last):
  File "/opt/sickchill/sickbeard/helpers.py", line 1523, in handle_requests_exception
    raise requests_exception
CloudflareCaptchaError: Cloudflare captcha challenge presented for www.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python.

2019-05-23 13:24:40 INFO     SEARCHQUEUE-MANUAL-268592 :: [Torrent9] :: Performing episode search for Les 100
2019-05-23 13:24:40 DEBUG    SEARCHQUEUE-MANUAL-268592 :: [Torrent9] :: Search Mode: Episode
2019-05-23 13:24:40 DEBUG    SEARCHQUEUE-MANUAL-268592 :: [Torrent9] :: Search string: Les 100 S06E04
2019-05-23 13:24:55 ERROR    SEARCHQUEUE-MANUAL-268592 :: [Torrent9] :: [9ae2c84] Request failed: Cloudflare captcha challenge presented for www.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python. (<type 'str'>)
Traceback (most recent call last):
  File "/opt/sickchill/sickbeard/helpers.py", line 1523, in handle_requests_exception
    raise requests_exception
CloudflareCaptchaError: Cloudflare captcha challenge presented for www.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python.
2019-05-23 13:24:55 DEBUG    SEARCHQUEUE-MANUAL-268592 :: [Torrent9] :: Traceback (most recent call last):
  File "/opt/sickchill/sickbeard/helpers.py", line 1523, in handle_requests_exception
    raise requests_exception
CloudflareCaptchaError: Cloudflare captcha challenge presented for www.torrent9.nz (cfscrape cannot solve captchas). Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library and recompile Python.

2019-05-23 13:24:55 DEBUG    SEARCHQUEUE-MANUAL-268592 :: formatting pattern: %SN - S%0SE%0E - %EN -> Les 100 - S06E04 - The Face Behind the Glass
2019-05-23 13:24:55 DEBUG    SEARCHQUEUE-MANUAL-268592 :: formatting pattern: %SN - S%0SE%0E - %EN -> Les 100 - S06E04 - The Face Behind the Glass
2019-05-23 13:24:55 INFO     SEARCHQUEUE-MANUAL-268592 :: Unable to find a download for: [Les 100 - S06E04 - The Face Behind the Glass]

I suppose this comes from the openssl version I use but how do I upgrade openssl to version 1.1.1 with Python 2.7 and recompile in raspbian?

thank you in advance for your help

**Comment by miigotu** [comment]
`Your OpenSSL version is lower than 1.1.1. Please upgrade your OpenSSL library`

**Comment by pro-src** [comment]
@flobafff I thought to inform you that a related problem has been fixed on the master branch. You absolutely should still upgrade your OpenSSL library for security purposes. Using at least v1.1.1 is known to avoid the CAPTCHA challenge in some cases.
