### ISSUE TITLE
Error trying to add SABnzbd

### ISSUE THREAD

**Issue by generalsnipe** [SickChill/SickChill#5501]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: origin/latest
OS: docker - binhex/arch-sabnzbd
Browser: Chrome
What you did: Saved Setting for NZB. 
What happened: Settings did not save. Error message appeared. 
What you expected: Settings to save with configuration
Logs:
```
AA TypeError: saveSearch() got an unexpected keyword argument 'torrent_download_dir_deluge'
AA result = function(**kwargs)
AA File "/opt/sickchill/sickbeard/webserve.py", line 287, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "/opt/sickchill/lib/concurrent/futures/thread.py", line 63, in run
AA return self.__get_result()
AA File "/opt/sickchill/lib/concurrent/futures/_base.py", line 455, in result
AA value = future.result()
AA File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
AA results = yield self.async_call(method)
AA File "/opt/sickchill/sickbeard/webserve.py", line 265, in get
AA yielded = self.gen.throw(*exc_info)
AA File "/opt/sickchill/lib/tornado/gen.py", line 1063, in run
AA raise_exc_info(self._exc_info)
AA File "/opt/sickchill/lib/tornado/concurrent.py", line 238, in result
AA value = future.result()
AA File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
AA result = yield result
AA File "/opt/sickchill/lib/tornado/web.py", line 1511, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol=u'http', host='192.168.X.X:8081', method='POST', uri='/config/search/saveSearch', version='HTTP/1.1', remote_ip='192.168.X.X', headers={'Origin': 'http://192.168.X.X:8081', 'Content-Length': '1487', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.X.X:8081', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.X.X:8081/config/search/', 'Cookie': 'snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; advanced_toggle_checked=1; blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; unassigned-complete-view=true; docker_listview_mode=advanced; zmHeaderFlip=up; zmEventRate=100; zmMontageLayout=1; zmWatchScale1=100; startupButton=new; dashapps_view_mode=allapps; enter_view=2; diskio=diskio; dockerSearchFlag=false; installMulti=false; sortButton=nameUp; Auth-Type=http; Auth-Token=H0zMPI5eV1qzzGBD3n6DCLCF0ZRPKRn8rtaifLU3lX5Z816o; categoryText=Search%20for%20sabnzbd; data=%7B%22docker%22%3A%22%22%2C%22section%22%3A%22AppStore%22%2C%22selected_category%22%3A%22%22%2C%22subcategory%22%3A%22%22%2C%22selected_subcategory%22%3A%22%22%2C%22selected%22%3A%22%22%2C%22lastUpdated%22%3A0%2C%22nextpage%22%3A0%2C%22prevpage%22%3A0%2C%22currentpage%22%3A1%2C%22searchFlag%22%3Atrue%7D; sortIcon=true; selectedMenu=', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
AA 2019-05-24 23:21:26 ERROR Uncaught exception POST /config/search/saveSearch (192.168.X.X)
AA TypeError: saveSearch() got an unexpected keyword argument 'torrent_download_dir_deluge'
AA result = function(**kwargs)
AA File "/opt/sickchill/sickbeard/webserve.py", line 287, in async_call
AA Traceback (most recent call last):
AA TypeError: saveSearch() got an unexpected keyword argument 'torrent_download_dir_deluge'
AA result = function(**kwargs)
AA File "/opt/sickchill/sickbeard/webserve.py", line 287, in async_call
```

**Comment by miigotu** [comment]
Update SC, fixed in newest update
