### ISSUE TITLE
Unable to contact theTVDB

### ISSUE THREAD

**Issue by johnramsden** [SickChill/SickChill#5610]
#### System Information

Branch/Commit: `master/1ed315660d99f6673a3bb53363fdff6902b89429`
OS: FreeBSD 11.2
Browser: Google Chrome
What you did: Attempted to update show from TVDB
What happened: Unable to contact theTVDB
What you expected: Show update
Logs:

```
2019-08-24 13:21:51 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: not well-formed (invalid token): line 19409, column 12
```

#### Details

This occurs both with regular updates and manual Force Refresh. 

I attempted deleting `cache*` in the sickchill root, but it didn't help. 

There are new updates on TVDB, but i'm not receiving them.

This started occurring in the last week.

**Comment by johnramsden** [comment]
Update, I also tried removing the show and re-adding it, I received:

```
AA tvdb_error: not well-formed (invalid token): line 19409, column 12
AA raise tvdb_error(e)
AA File "/var/db/sickchill/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
AA epsEt = self._getetsrc(url, language=language)
AA File "/var/db/sickchill/lib/tvdb_api/tvdb_api.py", line 874, in _getShowData
AA self._getShowData(key, self.config['language'], True)
AA File "/var/db/sickchill/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
AA s = t[self.indexer_id]
AA File "/var/db/sickchill/sickbeard/show_queue.py", line 324, in run
AA Traceback (most recent call last):
2019-09-02 17:57:30 ERROR SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /media/Series/Documentary/Vice News Tonight on theTVDB using ID 317479, not using the NFO. Delete .nfo and try adding manually again.: not well-formed (invalid token): line 19409, column 12
```

There are no `.nfo` files in the directory.
