### ISSUE TITLE
Sickchill and MacOS Catalina - Nolonger can add new shows from tvdb

### ISSUE THREAD

**Issue by troypressley** [SickChill/SickChill#5696]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: MacOS Catalina 10.15.1
Browser: Firefox 70.0.1
What you did: Tried to add new show even after using the fix from #5687 
What happened: Errors out
```
**Before Fix #5687 this was Debug error:**

AA tvdb_error: "There is no item named 'en.xml' in the archive"
AA raise tvdb_error(e)
AA File "/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 629, in _getetsrc
AA epsEt = self._getetsrc(url, language=language)
AA File "/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 874, in _getShowData
AA self._getShowData(key, self.config['language'], True)
AA File "/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 946, in __getitem__
AA s = t[self.indexer_id]
AA File "/Applications/SickRage/sickbeard/show_queue.py", line 324, in run
AA Traceback (most recent call last):
2019-11-17 19:54:18 ERROR    SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /Users/troypressley/Downloads/complete/Stumptown on theTVDB using ID 359581, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'en.xml' in the archive"
2019-11-17 19:54:18 INFO     SHOWQUEUE-ADD :: theTVDB: {u'useZip': True, u'apikey': u'F9C450E78D99172E', u'cache': u'/Applications/SickRage/cache/indexers/theTVDB', u'language': 'en'}
2019-11-17 19:54:18 INFO     SHOWQUEUE-ADD :: Starting to add show by ShowDir: /Users/troypressley/Downloads/complete/Stumptown
2019-11-17 19:54:10 DEBUG    ThreadPoolExecutor-0_4 :: Searching for Show with searchterm(s): ['Stumptown'] on Indexer: theTVDB
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: cur_commit = e094759640ca61c5c033bf1ff9d33bc7fc1ba857, newest_commit = e094759640ca61c5c033bf1ff9d33bc7fc1ba857, num_commits_behind = 0, num_commits_ahead = 0
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /Applications/SickRage
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /Applications/SickRage
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: git branch --set-upstream-to origin/master : returned successful
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: Executing git branch --set-upstream-to origin/master with your shell in /Applications/SickRage
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: git fetch origin --prune : returned successful
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: Executing git fetch origin --prune with your shell in /Applications/SickRage
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: git config remote.origin.url https://github.com/SickChill/SickChill.git : returned successful
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: Executing git config remote.origin.url https://github.com/SickChill/SickChill.git with your shell in /Applications/SickRage
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: git rev-parse HEAD : returned successful
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: Executing git rev-parse HEAD with your shell in /Applications/SickRage
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: git symbolic-ref -q HEAD : returned successful
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: Executing git symbolic-ref -q HEAD with your shell in /Applications/SickRage
2019-11-17 19:53:58 INFO     CHECKVERSION :: Checking for updates using GIT
2019-11-17 19:53:58 DEBUG    CHECKVERSION :: Starting new thread: CHECKVERSION
2019-11-17 19:53:58 INFO     TORNADO :: Starting SickChill on http://0.0.0.0:8081/
2019-11-17 19:53:58 INFO     MAIN :: Starting SickChill [master] using '/Applications/SickRage/config.ini'
2019-11-17 19:53:58 DEBUG    MAIN :: Loading initial show list
2019-11-17 19:53:58 DEBUG    MAIN :: Retrieving the last check time from the DB
2019-11-17 19:53:58 DEBUG    MAIN :: git symbolic-ref -q HEAD : returned successful
2019-11-17 19:53:58 DEBUG    MAIN :: Executing git symbolic-ref -q HEAD with your shell in /Applications/SickRage
2019-11-17 19:53:58 DEBUG    MAIN :: Using: git
2019-11-17 19:53:58 DEBUG    MAIN :: git version : returned successful
2019-11-17 19:53:58 DEBUG    MAIN :: Executing git version with your shell in /Applications/SickRage
2019-11-17 19:53:58 DEBUG    MAIN :: Checking if we can use git commands: git version
2019-11-17 19:53:58 DEBUG    MAIN :: Checking for archived episodes not qualified
2019-11-17 19:53:58 DEBUG    MAIN :: Checking for shows with tvrage id's, since tvrage is gone
2019-11-17 19:53:58 DEBUG    MAIN :: Checking database structure...failed.db
2019-11-17 19:53:58 DEBUG    MAIN :: Checking database structure...cache.db
2019-11-17 19:53:58 DEBUG    MAIN :: ResetDBVersion upgrade completed
2019-11-17 19:53:58 DEBUG    MAIN :: Database upgrade required: Reset Version
2019-11-17 19:53:58 DEBUG    MAIN :: Checking database structure...sickbeard.db
2019-11-17 19:53:58 DEBUG    MAIN :: The name Show Name - S02E03 - Ep Name.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-11-17 19:53:58 DEBUG    MAIN :: Parsed Show Name - S02E03 - Ep Name.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-11-17 19:53:58 DEBUG    MAIN :: Trying to parse Show Name - S02E03 - Ep Name.ext
2019-11-17 19:53:58 DEBUG    MAIN :: formatting pattern: Season %0S -> Season 02
2019-11-17 19:53:58 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2019-11-17 19:53:58 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-11-17 19:53:58 DEBUG    MAIN :: formatting pattern: %SN - S%0SE%0E - %EN -> Show Name - S02E03 - Ep Name
2019-11-17 19:53:58 DEBUG    MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
2019-11-17 19:53:58 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2019-11-17 19:53:58 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Restarting SickChill with ['/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', u'/Applications/SickRage/SickBeard.py', '--nolaunch']
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Shutting down Tornado
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Saving config file to disk
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Saving all shows to the database
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE-ADD thread to exit
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2019-11-17 19:53:57 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2019-11-17 19:53:56 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2019-11-17 19:53:56 INFO     EVENT-QUEUE :: Aborting all threads
AA tvdb_error: Bad zip file received from thetvdb.com, could not read it
AA raise tvdb_error(e)
AA File "/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 630, in _getetsrc
AA epsEt = self._getetsrc(url, language=language)
AA File "/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 875, in _getShowData
AA self._getShowData(key, self.config['language'], True)
AA File "/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 947, in __getitem__
AA s = t[self.indexer_id]
AA File "/Applications/SickRage/sickbeard/show_queue.py", line 324, in run
AA Traceback (most recent call last):
2019-11-17 19:48:58 ERROR    SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /Users/troypressley/Downloads/complete/Stumptown on theTVDB using ID 359581, not using the NFO. Delete .nfo and try adding manually again.: Bad zip file received from thetvdb.com, could not read it
2019-11-17 19:48:57 INFO     SHOWQUEUE-ADD :: theTVDB: {u'useZip': True, u'apikey': u'F9C450E78D99172E', u'cache': u'/Applications/SickRage/cache/indexers/theTVDB', u'language': 'en'}
2019-11-17 19:48:57 INFO     SHOWQUEUE-ADD :: Starting to add show by ShowDir: /Users/troypressley/Downloads/complete/Stumptown
2019-11-17 19:48:50 DEBUG    ThreadPoolExecutor-0_0 :: Searching for Show with searchterm(s): ['Stumptown'] on Indexer: theTVDB
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: cur_commit = e094759640ca61c5c033bf1ff9d33bc7fc1ba857, newest_commit = e094759640ca61c5c033bf1ff9d33bc7fc1ba857, num_commits_behind = 0, num_commits_ahead = 0
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /Applications/SickRage
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /Applications/SickRage
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: git branch --set-upstream-to origin/master : returned successful
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: Executing git branch --set-upstream-to origin/master with your shell in /Applications/SickRage
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: git fetch origin --prune : returned successful
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: Executing git fetch origin --prune with your shell in /Applications/SickRage
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: git config remote.origin.url https://github.com/SickChill/SickChill.git : returned successful
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: Executing git config remote.origin.url https://github.com/SickChill/SickChill.git with your shell in /Applications/SickRage
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: git rev-parse HEAD : returned successful
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: Executing git rev-parse HEAD with your shell in /Applications/SickRage
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: git symbolic-ref -q HEAD : returned successful
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: Executing git symbolic-ref -q HEAD with your shell in /Applications/SickRage
2019-11-17 19:48:37 INFO     CHECKVERSION :: Checking for updates using GIT
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: Starting new thread: CHECKVERSION
2019-11-17 19:48:37 INFO     TORNADO :: Starting SickChill on http://0.0.0.0:8081/
2019-11-17 19:48:37 INFO     MAIN :: Starting SickChill [master] using '/Applications/SickRage/config.ini'
2019-11-17 19:48:37 DEBUG    MAIN :: Loading initial show list
2019-11-17 19:48:37 DEBUG    MAIN :: Retrieving the last check time from the DB
2019-11-17 19:48:37 DEBUG    MAIN :: git symbolic-ref -q HEAD : returned successful
2019-11-17 19:48:37 DEBUG    MAIN :: Executing git symbolic-ref -q HEAD with your shell in /Applications/SickRage
2019-11-17 19:48:37 DEBUG    MAIN :: Using: git
2019-11-17 19:48:37 DEBUG    MAIN :: git version : returned successful
2019-11-17 19:48:37 DEBUG    MAIN :: Executing git version with your shell in /Applications/SickRage
2019-11-17 19:48:37 DEBUG    MAIN :: Checking if we can use git commands: git version
2019-11-17 19:48:37 DEBUG    MAIN :: Checking for archived episodes not qualified
2019-11-17 19:48:37 DEBUG    MAIN :: Checking for shows with tvrage id's, since tvrage is gone
2019-11-17 19:48:37 DEBUG    MAIN :: Checking database structure...failed.db
2019-11-17 19:48:37 DEBUG    MAIN :: Checking database structure...cache.db
2019-11-17 19:48:37 DEBUG    MAIN :: ResetDBVersion upgrade completed
2019-11-17 19:48:37 DEBUG    MAIN :: Database upgrade required: Reset Version
2019-11-17 19:48:37 DEBUG    MAIN :: Checking database structure...sickbeard.db
2019-11-17 19:48:37 DEBUG    MAIN :: The name Show Name - S02E03 - Ep Name.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-11-17 19:48:37 DEBUG    MAIN :: Parsed Show Name - S02E03 - Ep Name.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-11-17 19:48:37 DEBUG    MAIN :: Trying to parse Show Name - S02E03 - Ep Name.ext
2019-11-17 19:48:37 DEBUG    MAIN :: formatting pattern: Season %0S -> Season 02
2019-11-17 19:48:37 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2019-11-17 19:48:37 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-11-17 19:48:37 DEBUG    MAIN :: formatting pattern: %SN - S%0SE%0E - %EN -> Show Name - S02E03 - Ep Name
2019-11-17 19:48:37 DEBUG    MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
2019-11-17 19:48:37 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2019-11-17 19:48:37 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Restarting SickChill with ['/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', u'/Applications/SickRage/SickBeard.py', '--nolaunch']
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Shutting down Tornado
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Saving config file to disk
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Saving all shows to the database
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE-ADD thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Aborting all threads

**After Fix #5687 this was Debug error:**

AA tvdb_error: Bad zip file received from thetvdb.com, could not read it
AA raise tvdb_error(e)
AA File "/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 630, in _getetsrc
AA epsEt = self._getetsrc(url, language=language)
AA File "/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 875, in _getShowData
AA self._getShowData(key, self.config['language'], True)
AA File "/Applications/SickRage/lib/tvdb_api/tvdb_api.py", line 947, in __getitem__
AA s = t[self.indexer_id]
AA File "/Applications/SickRage/sickbeard/show_queue.py", line 324, in run
AA Traceback (most recent call last):
2019-11-17 19:48:58 ERROR    SHOWQUEUE-ADD :: [e094759] Unable to look up the show in /Users/troypressley/Downloads/complete/Stumptown on theTVDB using ID 359581, not using the NFO. Delete .nfo and try adding manually again.: Bad zip file received from thetvdb.com, could not read it
2019-11-17 19:48:57 INFO     SHOWQUEUE-ADD :: theTVDB: {u'useZip': True, u'apikey': u'F9C450E78D99172E', u'cache': u'/Applications/SickRage/cache/indexers/theTVDB', u'language': 'en'}
2019-11-17 19:48:57 INFO     SHOWQUEUE-ADD :: Starting to add show by ShowDir: /Users/troypressley/Downloads/complete/Stumptown
2019-11-17 19:48:50 DEBUG    ThreadPoolExecutor-0_0 :: Searching for Show with searchterm(s): ['Stumptown'] on Indexer: theTVDB
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: cur_commit = e094759640ca61c5c033bf1ff9d33bc7fc1ba857, newest_commit = e094759640ca61c5c033bf1ff9d33bc7fc1ba857, num_commits_behind = 0, num_commits_ahead = 0
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /Applications/SickRage
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /Applications/SickRage
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: git branch --set-upstream-to origin/master : returned successful
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: Executing git branch --set-upstream-to origin/master with your shell in /Applications/SickRage
2019-11-17 19:48:38 DEBUG    CHECKVERSION :: git fetch origin --prune : returned successful
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: Executing git fetch origin --prune with your shell in /Applications/SickRage
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: git config remote.origin.url https://github.com/SickChill/SickChill.git : returned successful
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: Executing git config remote.origin.url https://github.com/SickChill/SickChill.git with your shell in /Applications/SickRage
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: git rev-parse HEAD : returned successful
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: Executing git rev-parse HEAD with your shell in /Applications/SickRage
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: git symbolic-ref -q HEAD : returned successful
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: Executing git symbolic-ref -q HEAD with your shell in /Applications/SickRage
2019-11-17 19:48:37 INFO     CHECKVERSION :: Checking for updates using GIT
2019-11-17 19:48:37 DEBUG    CHECKVERSION :: Starting new thread: CHECKVERSION
2019-11-17 19:48:37 INFO     TORNADO :: Starting SickChill on http://0.0.0.0:8081/
2019-11-17 19:48:37 INFO     MAIN :: Starting SickChill [master] using '/Applications/SickRage/config.ini'
2019-11-17 19:48:37 DEBUG    MAIN :: Loading initial show list
2019-11-17 19:48:37 DEBUG    MAIN :: Retrieving the last check time from the DB
2019-11-17 19:48:37 DEBUG    MAIN :: git symbolic-ref -q HEAD : returned successful
2019-11-17 19:48:37 DEBUG    MAIN :: Executing git symbolic-ref -q HEAD with your shell in /Applications/SickRage
2019-11-17 19:48:37 DEBUG    MAIN :: Using: git
2019-11-17 19:48:37 DEBUG    MAIN :: git version : returned successful
2019-11-17 19:48:37 DEBUG    MAIN :: Executing git version with your shell in /Applications/SickRage
2019-11-17 19:48:37 DEBUG    MAIN :: Checking if we can use git commands: git version
2019-11-17 19:48:37 DEBUG    MAIN :: Checking for archived episodes not qualified
2019-11-17 19:48:37 DEBUG    MAIN :: Checking for shows with tvrage id's, since tvrage is gone
2019-11-17 19:48:37 DEBUG    MAIN :: Checking database structure...failed.db
2019-11-17 19:48:37 DEBUG    MAIN :: Checking database structure...cache.db
2019-11-17 19:48:37 DEBUG    MAIN :: ResetDBVersion upgrade completed
2019-11-17 19:48:37 DEBUG    MAIN :: Database upgrade required: Reset Version
2019-11-17 19:48:37 DEBUG    MAIN :: Checking database structure...sickbeard.db
2019-11-17 19:48:37 DEBUG    MAIN :: The name Show Name - S02E03 - Ep Name.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-11-17 19:48:37 DEBUG    MAIN :: Parsed Show Name - S02E03 - Ep Name.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-11-17 19:48:37 DEBUG    MAIN :: Trying to parse Show Name - S02E03 - Ep Name.ext
2019-11-17 19:48:37 DEBUG    MAIN :: formatting pattern: Season %0S -> Season 02
2019-11-17 19:48:37 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2019-11-17 19:48:37 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-11-17 19:48:37 DEBUG    MAIN :: formatting pattern: %SN - S%0SE%0E - %EN -> Show Name - S02E03 - Ep Name
2019-11-17 19:48:37 DEBUG    MAIN :: Episode has no release group, replacing it with 'RLSGROUP'
2019-11-17 19:48:37 DEBUG    MAIN :: Found codec for 'Show Name: Ep Name'.
2019-11-17 19:48:37 DEBUG    MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-RLSGROUP into Show Name - S02E03 [GROUP: RLSGROUP] [ABD: False] [ANIME: False] [whichReg: [u'standard']]
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Restarting SickChill with ['/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', u'/Applications/SickRage/SickBeard.py', '--nolaunch']
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Shutting down Tornado
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Saving config file to disk
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Saving all shows to the database
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2019-11-17 19:48:36 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE-ADD thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2019-11-17 19:48:35 INFO     EVENT-QUEUE :: Aborting all threads

```

**Comment by mmhere** [comment]
See late breaking updates in issue-5696 discussion thread where we've found that the current change on the develop branch does not quite get us there.  You can instead [temporarily] turn off requests for compressed (zip) data and instead ask for plain uncompressed XML, which works for the moment.

**Comment by didyouexpectthat** [comment]
@mmhere  5696 is this issue :P

**Comment by WebSpider** [comment]
Closing this issue, please track #5686
