### ISSUE TITLE
[APP SUBMITTED]: Found 332525, but attribute 'seriesname' was empty.

### ISSUE THREAD

**Issue by LeeThompson** [SickChill/SickChill#5712]
### INFO
Python Version: **2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]**
Operating System: **Linux-3.10.105-x86_64-with** (linuxserver.io/sickchill running in Docker on Synology)
Locale: None
Branch: **master**
Commit: SickChill/SickChill@e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Link to Log: https://gist.github.com/b5dafd2a93311b483bd429e20598294c

**NOTE:** `/lib/tvdb_api/tvdb_api.py` has been **modified**.  `%s.xml` has been changed to `%s.zip.xml` as a workaround for thetvdb changes per #5686 

### ERROR
```
SHOWQUEUE-FORCE-UPDATE :: [e094759] Data retrieved from theTVDB was incomplete, aborting: Found 332525, but attribute 'seriesname' was empty.
```

```
AA tvdb_attributenotfound: Found 332525, but attribute 'seriesname' was empty.
AA "Found {0}, but attribute 'seriesname' was empty.".format(self.indexerid))
AA File "/app/sickchill/sickbeard/tv.py", line 853, in loadFromIndexer
AA self.show.loadFromIndexer(cache=not self.force)
AA File "/app/sickchill/sickbeard/show_queue.py", line 651, in run
AA Traceback (most recent call last):
```

More information, API Results:

**API v3**

```
https://api.thetvdb.com/series/332525

{
  "data": {
    "id": 332525,
    "seriesId": "203712",
    "seriesName": "Black Lightning",
    "aliases": [],
    "season": "3",
    "poster": "posters/5d6bb9048b2c3.jpg",
    "banner": "graphical/332525-g4.jpg",
    "fanart": "fanart/original/5db98c417433d.jpg",
    "status": "Continuing",
    "firstAired": "2018-01-16",
    "network": "The CW",
    "networkId": "267",
    "runtime": "45",
    "language": "en",
    "genre": [
      "Action",
      "Drama",
      "Science Fiction"
    ],
    "overview": "Jefferson Pierce, who retired from his superhero persona Black Lightning nine years ago after seeing the effects it had on his family, is forced to become a vigilante again when the rise of the local gang called the 100 leads to increased crime and corruption in his community of Freeland.",
    "lastUpdated": 1573496491,
    "airsDayOfWeek": "Monday",
    "airsTime": "9:00 PM",
    "rating": "TV-14",
    "imdbId": "tt6045840",
    "zap2itId": "EP02698280",
    "added": "2017-07-28 12:56:03",
    "addedBy": 171,
    "siteRating": 0,
    "siteRatingCount": 0,
    "slug": "black-lightning"
  }
}
```

**API v2**

If I use SickChill's API v2 method, SeriesName is there but for some reason SickChill doesn't see it.

```
https://thetvdb.com/api/0629B785CE550C8D/series/332525/en.zip.xml
https://thetvdb.com/api/0629B785CE550C8D/series/332525/en.xml

<Data>
<Series>
<id>332525</id>
<Actors>
|Damon Gupton|Cress Williams|James Remar|China Anne McClain|Jill Scott|Christine Adams|Nafessa Williams|Marvin 'Krondon' Jones III|
</Actors>
<Airs_DayOfWeek>Monday</Airs_DayOfWeek>
<Airs_Time>9:00 PM</Airs_Time>
<ContentRating>TV-14</ContentRating>
<FirstAired>2018-01-16</FirstAired>
<Genre>|Action|Drama|Science Fiction|</Genre>
<IMDB_ID>tt6045840</IMDB_ID>
<Language>en</Language>
<Network>The CW</Network>
<NetworkID>267</NetworkID>
<Overview>
Jefferson Pierce, who retired from his superhero persona Black Lightning nine years ago after seeing the effects it had on his family, is forced to become a vigilante again when the rise of the local gang called the 100 leads to increased crime and corruption in his community of Freeland.
</Overview>
<Rating>0</Rating>
<RatingCount>0</RatingCount>
<Runtime>45</Runtime>
<SeriesID>203712</SeriesID>
<SeriesName>Black Lightning</SeriesName>
<Status>Continuing</Status>
<added>2017-07-28 12:56:03</added>
<addedBy/>
<banner>graphical/332525-g4.jpg</banner>
<fanart>fanart/original/5db98c417433d.jpg</fanart>
<lastupdated>1573496491</lastupdated>
<poster>posters/5d6bb9048b2c3.jpg</poster>
<zap2it_id>EP02698280</zap2it_id>
</Series>
</Data>
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by LeeThompson** [comment]
Oddly it's working today, here is the API v2 pull for analysis:

```
<Data>
<Series>
<id>332525</id>
<Actors>
|Damon Gupton|Cress Williams|James Remar|China Anne McClain|Jill Scott|Christine Adams|Nafessa Williams|Marvin 'Krondon' Jones III|
</Actors>
<Airs_DayOfWeek>Monday</Airs_DayOfWeek>
<Airs_Time>9:00 PM</Airs_Time>
<ContentRating>TV-14</ContentRating>
<FirstAired>2018-01-16</FirstAired>
<Genre>|Action|Drama|Science Fiction|</Genre>
<IMDB_ID>tt6045840</IMDB_ID>
<Language>en</Language>
<Network>The CW</Network>
<NetworkID>267</NetworkID>
<Overview>
Jefferson Pierce, who retired from his superhero persona Black Lightning nine years ago after seeing the effects it had on his family, is forced to become a vigilante again when the rise of the local gang called the 100 leads to increased crime and corruption in his community of Freeland.
</Overview>
<Rating>0</Rating>
<RatingCount>0</RatingCount>
<Runtime>45</Runtime>
<SeriesID>203712</SeriesID>
<SeriesName>Black Lightning</SeriesName>
<Status>Continuing</Status>
<added>2017-07-28 12:56:03</added>
<addedBy/>
<banner>graphical/332525-g4.jpg</banner>
<fanart>fanart/original/5db98c417433d.jpg</fanart>
<lastupdated>1573496491</lastupdated>
<poster>posters/5d6bb9048b2c3.jpg</poster>
<zap2it_id>EP02698280</zap2it_id>
</Series>
</Data>
```

**Comment by miigotu** [comment]
#5789 fixes, is in develop branch. Will be on master after more testing.
