### ISSUE TITLE
cannot add new/existing shows

### ISSUE THREAD

**Issue by roscopwnz** [SickChill/SickChill#5715]
2019-11-17 23:13:00 SHOWQUEUE-ADD :: [e094759] Unable to look up the show in B:\Plex Media\TV Shows\The World According to Jeff Goldblum on theTVDB using ID 362437, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'en.xml' in the archive"

**Branch**: master
**Commit**: e094759640ca61c5c033bf1ff9d33bc7fc1ba857
**Version**: v2019.06.28-1
**Database** **Version**: 44.0
**OS**: Windows 10
**Browser**: Brave
**What you did**: tried to add a new (or existing show) to list
**What happened**: appeared to work, but does not show in the list after some time, error appears in log as seen above
**What you expected**: show to add to list and begin download missing episodes (or according to config)
**Additional comment**: I am not sure it cannot resolve github.com to do updates? perhaps that the real issue and its just outdated?

**Log File**
2019-11-21 01:32:55 WARNING CHECKVERSION :: Unable to contact github, can't check for update
2019-11-21 01:32:55 WARNING CHECKVERSION :: git fetch origin --prune returned : (128) fatal: unable to access 'https://github.com/SickChill/SickChill.git/': Could not resolve host: github.com
AA tvdb_error: "There is no item named 'en.xml' in the archive"
AA raise tvdb_error(e)
AA File "C:\Users\rojoj\SickChill\lib\tvdb_api\tvdb_api.py", line 629, in _getetsrc
AA epsEt = self._getetsrc(url, language=language)
AA File "C:\Users\rojoj\SickChill\lib\tvdb_api\tvdb_api.py", line 874, in _getShowData
AA self._getShowData(key, self.config['language'], True)
AA File "C:\Users\rojoj\SickChill\lib\tvdb_api\tvdb_api.py", line 946, in __getitem__
AA s = t[self.indexer_id]
AA File "C:\Users\rojoj\SickChill\sickbeard\show_queue.py", line 324, in run
AA Traceback (most recent call last):
2019-11-20 23:25:15 ERROR SHOWQUEUE-ADD :: [e094759] Unable to look up the show in B:\Plex Media\TV Shows\The Real Housewives of New York City on theTVDB using ID 84669, not using the NFO. Delete .nfo and try adding manually again.: "There is no item named 'en.xml' in the archive"

**Comment by mmhere** [comment]
https://github.com/SickChill/SickChill/issues/5686
duplicate

**Comment by QuentinJ54** [comment]
Hello,
I can not load the branch "develop" it tells me what does not exist

**Comment by miigotu** [comment]
#5789 fixes, is in develop branch. Will be on master after more testing.
