### ISSUE TITLE
Problem when I try to add tv show El embarcadero

### ISSUE THREAD

**Issue by 03397** [SickChill/SickChill#5732]
When I try to add the tv show above I am getting the error messages below

2019-11-28 18:41:03 INFO     SHOWQUEUE-ADD :: Starting to add show by ShowDir: /share/Multimed                                                                   ia/Video/Series/The Pier
2019-11-28 18:41:03 INFO     SHOWQUEUE-ADD :: theTVDB: {u'useZip': True, u'apikey': u'F9C450E7                                                                   8D99172E', u'cache': u'/share/MD0_DATA/.qpkg/SickRage/config/cache/indexers/theTVDB', u'langua                                                                   ge': 'en'}
2019-11-28 18:41:05 ERROR    SHOWQUEUE-ADD :: [e9a82d9] Unable to look up the show in /share/M                                                                   ultimedia/Video/Series/The Pier on theTVDB using ID 348005, not using the NFO. Delete .nfo and                                                                    try adding manually again.: "There is no item named 'en.zip.xml' in the archive"
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickRage/SickRage/sickbeard/show_queue.py", line 324, in run
    s = t[self.indexer_id]
  File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdb_api/tvdb_api.py", line 946, in __geti                                                                   tem__
    self._getShowData(key, self.config['language'], True)
  File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdb_api/tvdb_api.py", line 874, in _getSh                                                                   owData
    epsEt = self._getetsrc(url, language=language)
  File "/share/MD0_DATA/.qpkg/SickRage/SickRage/lib/tvdb_api/tvdb_api.py", line 629, in _getet                                                                   src
    raise tvdb_error(e)
tvdb_error: "There is no item named 'en.zip.xml' in the archive"

This is my setup

Branch: master
Commit: e094759640ca61c5c033bf1ff9d33bc7fc1ba857
Version: v2019.06.28-1
Database Version: 44.0
  Python Version:2.7.14 (default, Jan 11 2018, 08:24:40) [GCC 6.3.0]
  SSL Version:OpenSSL 1.0.2k 26 Jan 2017
  OS:Linux-3.4.6-x86_64-with-glibc2.2.5
  Locale:en_US.UTF-8

**Comment by mesa57** [comment]
Master branch works fine for me for this show.

**Comment by miigotu** [comment]
Fixed in #5789, live on develop.
