### ISSUE TITLE
2019-11-30 13:50:01 SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' ()

### ISSUE THREAD

**Issue by beironjohn** [SickChill/SickChill#5739]
Branch/Commit: Master/404f197697602a2bbfa8e6b39207229a94d37bb
OS: Windows-10-10.0.18362
Browser: Chrome
What you did: Updated to latest release
What happened: Errors occurred immediately "SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' ()"
What you expected: backlog search to complete as before the update
Logs:
```
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: Checking if we can use git commands: git version
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: Executing git version with your shell in C:\SickChill\SickChill
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: git version : returned successful
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: Using: git
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: Executing git symbolic-ref -q HEAD with your shell in C:\SickChill\SickChill
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: git symbolic-ref -q HEAD : returned successful
2019-11-30 13:50:00 INFO     ThreadPoolExecutor-0_1 :: Checking for updates using GIT
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: Executing git symbolic-ref -q HEAD with your shell in C:\SickChill\SickChill
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: git symbolic-ref -q HEAD : returned successful
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: Executing git rev-parse HEAD with your shell in C:\SickChill\SickChill
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: git rev-parse HEAD : returned successful
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: Executing git config remote.origin.url https://github.com/SickChill/SickChill.git with your shell in C:\SickChill\SickChill
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: git config remote.origin.url https://github.com/SickChill/SickChill.git : returned successful
2019-11-30 13:50:00 DEBUG    ThreadPoolExecutor-0_1 :: Executing git fetch origin --prune with your shell in C:\SickChill\SickChill
2019-11-30 13:50:01 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:01 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:01 WARNING  SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Unable to connect to provider
2019-11-30 13:50:01 DEBUG    ThreadPoolExecutor-0_1 :: git fetch origin --prune : returned successful
2019-11-30 13:50:01 DEBUG    ThreadPoolExecutor-0_1 :: Executing git branch --set-upstream-to origin/master with your shell in C:\SickChill\SickChill
2019-11-30 13:50:01 DEBUG    ThreadPoolExecutor-0_1 :: git branch --set-upstream-to origin/master : returned successful
2019-11-30 13:50:01 DEBUG    ThreadPoolExecutor-0_1 :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in C:\SickChill\SickChill
2019-11-30 13:50:01 DEBUG    ThreadPoolExecutor-0_1 :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2019-11-30 13:50:01 DEBUG    ThreadPoolExecutor-0_1 :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in C:\SickChill\SickChill
2019-11-30 13:50:01 DEBUG    ThreadPoolExecutor-0_1 :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2019-11-30 13:50:01 DEBUG    ThreadPoolExecutor-0_1 :: cur_commit = 2404f197697602a2bbfa8e6b39207229a94d37bb, newest_commit = 2404f197697602a2bbfa8e6b39207229a94d37bb, num_commits_behind = 0, num_commits_ahead = 0
2019-11-30 13:50:01 WARNING  ThreadPoolExecutor-0_1 :: Issue submitter is running, please wait for it to complete
2019-11-30 13:50:05 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:05 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:09 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:09 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:09 WARNING  SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Unable to connect to provider
2019-11-30 13:50:13 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:13 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:17 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:17 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:17 WARNING  SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Unable to connect to provider
2019-11-30 13:50:17 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Fallback season pack search initiate
2019-11-30 13:50:17 INFO     SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Performing season pack search for The Simpsons
2019-11-30 13:50:21 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:21 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:26 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:26 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:26 WARNING  SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Unable to connect to provider
2019-11-30 13:50:26 INFO     SEARCHQUEUE-BACKLOG-71663 :: No needed episodes found during backlog search for: [The Simpsons]
2019-11-30 13:50:30 INFO     SEARCHQUEUE-BACKLOG-71663 :: Beginning backlog search for: [The Simpsons]
2019-11-30 13:50:30 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Last update was too soon, using old cache: 2019-11-30 13:45:07. Updated less then 10 minutes ago
2019-11-30 13:50:30 INFO     SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Performing episode search for The Simpsons
2019-11-30 13:50:34 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:34 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:38 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:38 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:38 WARNING  SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Unable to connect to provider
2019-11-30 13:50:42 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:42 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: Checking if we can use git commands: git version
2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: Executing git version with your shell in C:\SickChill\SickChill
2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: git version : returned successful
2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: Using: git
2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: Executing git symbolic-ref -q HEAD with your shell in C:\SickChill\SickChill
2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: git symbolic-ref -q HEAD : returned successful
2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: Executing git symbolic-ref -q HEAD with your shell in C:\SickChill\SickChill
2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: git symbolic-ref -q HEAD : returned successful
2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: Executing git rev-parse HEAD with your shell in C:\SickChill\SickChill
2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: git rev-parse HEAD : returned successful
2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: Executing git config remote.origin.url https://github.com/SickChill/SickChill.git with your shell in C:\SickChill\SickChill
2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: git config remote.origin.url https://github.com/SickChill/SickChill.git : returned successful
2019-11-30 13:50:43 DEBUG    ThreadPoolExecutor-0_2 :: Executing git fetch origin --prune with your shell in C:\SickChill\SickChill
2019-11-30 13:50:44 DEBUG    ThreadPoolExecutor-0_2 :: git fetch origin --prune : returned successful
2019-11-30 13:50:44 DEBUG    ThreadPoolExecutor-0_2 :: Executing git branch --set-upstream-to origin/master with your shell in C:\SickChill\SickChill
2019-11-30 13:50:44 DEBUG    ThreadPoolExecutor-0_2 :: git branch --set-upstream-to origin/master : returned successful
2019-11-30 13:50:44 DEBUG    ThreadPoolExecutor-0_2 :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in C:\SickChill\SickChill
2019-11-30 13:50:44 DEBUG    ThreadPoolExecutor-0_2 :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2019-11-30 13:50:44 DEBUG    ThreadPoolExecutor-0_2 :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in C:\SickChill\SickChill
2019-11-30 13:50:44 DEBUG    ThreadPoolExecutor-0_2 :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2019-11-30 13:50:44 DEBUG    ThreadPoolExecutor-0_2 :: cur_commit = 2404f197697602a2bbfa8e6b39207229a94d37bb, newest_commit = 2404f197697602a2bbfa8e6b39207229a94d37bb, num_commits_behind = 0, num_commits_ahead = 0
2019-11-30 13:50:44 DEBUG    ThreadPoolExecutor-0_2 :: Executing git describe --abbrev=0 2404f197697602a2bbfa8e6b39207229a94d37bb with your shell in C:\SickChill\SickChill
2019-11-30 13:50:44 DEBUG    ThreadPoolExecutor-0_2 :: git describe --abbrev=0 2404f197697602a2bbfa8e6b39207229a94d37bb : returned successful
2019-11-30 13:50:47 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:47 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:47 WARNING  SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Unable to connect to provider
2019-11-30 13:50:51 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:51 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:55 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:55 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:50:55 WARNING  SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Unable to connect to provider
2019-11-30 13:50:59 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-11-30 13:50:59 DEBUG    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-11-30 13:51:03 ERROR    SEARCHQUEUE-BACKLOG-71663 :: [IPTorrents] :: [2404f19] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
```
[sickchill.log](https://github.com/SickChill/SickChill/files/3907159/sickchill.log)

**Comment by beironjohn** [comment]
I created this manually as the automated process did not appear to work.

Due to the vast number of emails I've received today I think the issue was originally automatically posted here - https://github.com/SickChill/SickChill/issues/2206

**Comment by Viss** [comment]
I am also experiencing this issue.
and to boot, I have 2fa enabled for github, and sickchill doesn't appear to support allowing me to authenticate to github when 2fa is enabled.

**Comment by davidfm** [comment]
Same issue if HDTorrents

**Comment by defhead** [comment]
Same issue for me. Ocurring sometimes, not every time.

**Comment by lussierj** [comment]
Getting same issue for:
HDTorrents
IPTorrents
Speedcd

**Comment by skaynl** [comment]
Same IPTorrents line in my Error log but shows are snatched just fine from iptorrents.
In the Warning logs you get an "SEARCHQUEUE-DAILY-SEARCH :: [IPTorrents] :: Unable to connect to provider" at the same time the error is posted in the error log.

**Comment by labbean** [comment]
Same here:

Branch: master
Commit: 1ed315660d99f6673a3bb53363fdff6902b89429
Version: v2019.06.28-1
Database Version: 44.0

2019-12-12 11:41:55 SEARCHQUEUE-DAILY-SEARCH :: [1ed3156] Request failed: 'location' ()
                        2019-12-12 11:41:12 SEARCHQUEUE-BACKLOG-348851 :: [1ed3156] Request failed: 'location' ()
                        2019-12-12 08:23:35 SEARCHQUEUE-BACKLOG-359581 :: [1ed3156] Request failed: 'location' ()
                        2019-12-12 05:40:28 SEARCHQUEUE-BACKLOG-360733 :: [1ed3156] Request failed: 'location' ()

**Comment by mullvaden83** [comment]
I get this too on HDTorrents. 
Driving me mad. Is this a programing error from the dev? Or something I can fix by myself?

**Comment by tobias-urdin** [comment]
See https://github.com/SickChill/SickChill/issues/5737#issuecomment-567677430
