### ISSUE TITLE
SickBeard.py can't start ValueError: cr{ptkgrqphy.backends

### ISSUE THREAD

**Issue by fernbach** [SickChill/SickChill#5768]
After an update (Also tried to clone the repo) when I start SichChill I receive the following error:
ValueError: ('Invalid group name', 'cr{ptkgrqphy.backends').

Running on Raspbian

full error:
`Traceback (most recent call last):
  File "SickBeard.py", line 69, in <module>
    import sickbeard
  File "/opt/sickrage/sickbeard/__init__.py", line 38, in <module>
    from sickbeard import (auto_postprocessor, dailysearcher, db, helpers, logger, metadata, naming, post_processing_queue, properFinder, providers,
  File "/opt/sickrage/sickbeard/naming.py", line 27, in <module>
    from sickbeard import common, logger, tv
  File "/opt/sickrage/sickbeard/tv.py", line 36, in <module>
    from sickbeard import db, helpers, image_cache, logger, network_timezones, notifiers, postProcessor, subtitles
  File "/opt/sickrage/sickbeard/subtitles.py", line 32, in <module>
    import subliminal
  File "/opt/sickrage/lib/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/opt/sickrage/lib/subliminal/core.py", line 13, in <module>
    from guessit import guessit
  File "/opt/sickrage/lib/guessit/__init__.py", line 8, in <module>
    from .api import guessit, GuessItApi
  File "/opt/sickrage/lib/guessit/api.py", line 20, in <module>
    from .rules import rebulk_builder
  File "/opt/sickrage/lib/guessit/rules/__init__.py", line 11, in <module>
    from .properties.episodes import episodes
  File "/opt/sickrage/lib/guessit/rules/properties/episodes.py", line 14, in <module>
    from .title import TitleFromPosition
  File "/opt/sickrage/lib/guessit/rules/properties/title.py", line 11, in <module>
    from .language import (
  File "/opt/sickrage/lib/guessit/rules/properties/language.py", line 76, in <module>
    NON_SPECIFIC_LANGUAGES = frozenset([UNDETERMINED, MULTIPLE])
  File "/opt/sickrage/lib/babelfish/language.py", line 155, in __hash__
    return hash(str(self))
  File "/opt/sickrage/lib/babelfish/language.py", line 178, in __str__
    s = self.alpha2
  File "/opt/sickrage/lib/babelfish/language.py", line 150, in __getattr__
    return language_converters[name].convert(alpha3, country, script)
  File "/opt/sickrage/lib/babelfish/converters/__init__.py", line 238, in __getitem__
    for ep in iter_entry_points(self.entry_point):
  File "/opt/sickrage/lib/pkg_resources.py", line 480, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "/opt/sickrage/lib/pkg_resources.py", line 2233, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/opt/sickrage/lib/pkg_resources.py", line 2046, in parse_map
    maps[group] = cls.parse_group(group, lines, dist)
  File "/opt/sickrage/lib/pkg_resources.py", line 2019, in parse_group
    raise ValueError("Invalid group name", group)
ValueError: ('Invalid group name', 'cr{ptkgrqphy.backends')
`
Anyone was received that error and was able to fix it?

**Comment by miigotu** [comment]
@fernbach this looks like disk corruption. `'cr{ptkgrqphy.backends'` is supposed to be `'cryptography.backends'`. Backup and delete the git repo and re-clone
