### ISSUE TITLE
 UserWarning: unable to use "lxml": cannot import name etree

### ISSUE THREAD

**Issue by kailia** [SickChill/SickChill#5794]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 2c72459ddfd209106d1eb76677b2016f4bcecd74
Version: v2019.12.22-1
Database Version: 44.1

OS: Windows 10
Browser:

Logs:
```
C:\DATA\SickRage\SickChill\lib\imdb\parser\http\utils.py:481: UserWarning: unable to use "lxml": cannot import name etree
  warnings.warn('unable to use "%s": %s' % (mod, str(e)))
C:\DATA\SickRage\SickChill\lib\imdb\parser\http\utils.py:472: UserWarning: falling back to "beautifulsoup"
  warnings.warn('falling back to "%s"' % mod)
```

**Comment by miigotu** [comment]
Nothing wrong with this

**Comment by Tiwas** [comment]
I'm getting a lot of these, too

```
AA ImportError: cannot import name etree
AA from lxml import etree as ElementTree
AA File "C:\SickChill\SickChill\lib\imdb\parser\http\piculet.py", line 263, in
AA from .piculet import Path, Rule, Rules
AA File "C:\SickChill\SickChill\lib\imdb\parser\http\companyParser.py", line 32, in
AA from . import (
AA File "C:\SickChill\SickChill\lib\imdb\parser\http\__init__.py", line 40, in
AA from .parser.http import IMDbHTTPAccessSystem
AA File "C:\SickChill\SickChill\lib\imdb\__init__.py", line 195, in IMDb
AA i = imdb.IMDb()
AA File "C:\SickChill\SickChill\sickbeard\tv.py", line 851, in loadIMDbInfo
AA self.show.loadIMDbInfo()
AA File "C:\SickChill\SickChill\sickbeard\show_queue.py", line 661, in run
AA Traceback (most recent call last):
2020-04-19 04:02:30 ERROR SHOWQUEUE-FORCE-UPDATE :: [290b22c] Error loading IMDb info: cannot import name etree
AA ImportError: cannot import name etree
AA from lxml import etree as ElementTree
AA File "C:\SickChill\SickChill\lib\imdb\parser\http\piculet.py", line 263, in
AA from .piculet import Path, Rule, Rules
AA File "C:\SickChill\SickChill\lib\imdb\parser\http\companyParser.py", line 32, in
AA from . import (
AA File "C:\SickChill\SickChill\lib\imdb\parser\http\__init__.py", line 40, in
AA from .parser.http import IMDbHTTPAccessSystem
AA File "C:\SickChill\SickChill\lib\imdb\__init__.py", line 195, in IMDb
AA i = imdb.IMDb()
AA File "C:\SickChill\SickChill\sickbeard\tv.py", line 851, in loadIMDbInfo
AA self.show.loadIMDbInfo()
AA File "C:\SickChill\SickChill\sickbeard\show_queue.py", line 661, in run
AA Traceback (most recent call last):
2020-04-19 04:01:00 ERROR SHOWQUEUE-FORCE-UPDATE :: [290b22c] Error loading IMDb info: cannot import name etree
```
