### ISSUE TITLE
IPT errors

### ISSUE THREAD

**Issue by chopnblok** [SickChill/SickChill#5796]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / v2019.12.22-1
OS: Windows 10 64bit
Browser: Chrome
What you did: Manual search
What happened: Could not download file
What you expected: Go to search provider website download file
Logs:
```
2019-12-26 11:12:16 INFO     SEARCHQUEUE-MANUAL-260449 :: Beginning manual search for: [Vikings - S06E01 - New Beginnings]
2019-12-26 11:12:20 ERROR    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: [2c72459] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-12-26 11:12:24 ERROR    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: [2c72459] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-12-26 11:12:24 WARNING  SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Unable to connect to provider
2019-12-26 11:12:24 INFO     SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Performing episode search for Vikings
2019-12-26 11:12:28 ERROR    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: [2c72459] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-12-26 11:12:32 ERROR    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: [2c72459] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-12-26 11:12:32 WARNING  SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Unable to connect to provider
2019-12-26 11:12:32 INFO     SEARCHQUEUE-MANUAL-260449 :: Unable to find a download for: [Vikings - S06E01 - New Beginnings]
2019-12-26 11:12:36 INFO     SEARCHQUEUE-MANUAL-260449 :: Beginning manual search for: [Vikings - S06E02 - The Prophet]
2019-12-26 11:12:36 INFO     SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Performing episode search for Vikings
2019-12-26 11:12:40 ERROR    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: [2c72459] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-12-26 11:12:44 ERROR    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: [2c72459] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-12-26 11:12:44 WARNING  SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Unable to connect to provider
2019-12-26 11:12:44 INFO     SEARCHQUEUE-MANUAL-260449 :: Unable to find a download for: [Vikings - S06E02 - The Prophet]
2019-12-26 11:12:46 INFO     SEARCHQUEUE-MANUAL-260449 :: Beginning manual search for: [Vikings - S06E03 - Ghosts, Gods and Running Dogs]
2019-12-26 11:12:46 INFO     SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Performing episode search for Vikings
2019-12-26 11:12:50 ERROR    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: [2c72459] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-12-26 11:12:54 ERROR    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: [2c72459] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-12-26 11:12:54 WARNING  SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Unable to connect to provider
2019-12-26 11:12:54 INFO     SEARCHQUEUE-MANUAL-260449 :: Unable to find a download for: [Vikings - S06E03 - Ghosts, Gods and Running Dogs]
2019-12-26 11:12:56 INFO     SEARCHQUEUE-MANUAL-260449 :: Beginning manual search for: [Vikings - S06E04 - All the Prisoners]
2019-12-26 11:12:56 INFO     SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Performing episode search for Vikings
2019-12-26 11:13:00 ERROR    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: [2c72459] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-12-26 11:13:04 ERROR    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: [2c72459] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-12-26 11:13:04 WARNING  SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Unable to connect to provider
2019-12-26 11:13:04 INFO     SEARCHQUEUE-MANUAL-260449 :: Unable to find a download for: [Vikings - S06E04 - All the Prisoners]
2019-12-26 11:14:43 INFO     ThreadPoolExecutor-0_31 :: No update needed
2019-12-26 11:15:36 DEBUG    SEARCHQUEUE-MANUAL-260449 :: formatting pattern: %SN - S%0SE%0E - %EN -> Vikings - S06E01 - New Beginnings
2019-12-26 11:15:36 INFO     SEARCHQUEUE-MANUAL-260449 :: Beginning manual search for: [Vikings - S06E01 - New Beginnings]
2019-12-26 11:15:36 DEBUG    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Last update was too soon, using old cache: 2019-12-26 11:12:24. Updated less then 10 minutes ago
2019-12-26 11:15:36 INFO     SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Performing episode search for Vikings
2019-12-26 11:15:40 ERROR    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: [2c72459] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-12-26 11:15:40 DEBUG    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-12-26 11:15:44 ERROR    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: [2c72459] Request failed: 'location' (<type 'str'>)
Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'
2019-12-26 11:15:44 DEBUG    SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 1527, in handle_requests_exception
    raise requests_exception
KeyError: 'location'

2019-12-26 11:15:44 WARNING  SEARCHQUEUE-MANUAL-260449 :: [IPTorrents] :: Unable to connect to provider
2019-12-26 11:15:44 DEBUG    SEARCHQUEUE-MANUAL-260449 :: formatting pattern: %SN - S%0SE%0E - %EN -> Vikings - S06E01 - New Beginnings
2019-12-26 11:15:44 DEBUG    SEARCHQUEUE-MANUAL-260449 :: formatting pattern: %SN - S%0SE%0E - %EN -> Vikings - S06E01 - New Beginnings
2019-12-26 11:15:44 INFO     SEARCHQUEUE-MANUAL-260449 :: Unable to find a download for: [Vikings - S06E01 - New Beginnings]
2019-12-26 11:16:11 DEBUG    POSTPROCESSOR :: Starting new thread: POSTPROCESSOR

```

**Comment by tiamatloc** [comment]
This sounds like you have not set your cookie values. Run a search in the IPT forums for a guide if you don't know what cookie settings you need in SickChill.

**Comment by chopnblok** [comment]
> This sounds like you have not set your cookie values. Run a search in the IPT forums for a guide if you don't know what cookie settings you need in SickChill.

This fixed the issue. Interesting I've never done this in the past and it has always worked, maybe something has changed recently which now requires this to be set.
