### ISSUE TITLE
Cannot search legendas.tv

### ISSUE THREAD

**Issue by NunoHiggs** [SickChill/SickChill#5814]
Branch/Commit:  Master
OS: Linux 
Browser: Any
What you did: Tried to download subtitles form legendas.tv
What happened:  Could not search in legendastv provider. Discarding for now
What you expected: The subtitle to be downloaded.

Logs:
```
2019-12-31 09:48:20 DEBUG    SHOWQUEUE-SUBTITLE :: Could not search in legendastv provider. Discarding for now
2019-12-31 09:48:20 DEBUG    SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1954870007 is: 348 (min=213)
2019-12-31 09:48:20 DEBUG    SHOWQUEUE-SUBTITLE :: [opensubtitles] Subtitle score for 1953904541 is: 331 (min=213)
```
The account has the correct username and password defined in the subtitles section of sickchill

I suspect that they made some change to the site, dus invalidating the download api.
How can i activate the debug on the legendas.tv login/download process to check what is the speciffic error instead of getting the general error?

Thanks

**Comment by miigotu** [comment]
Try with the regular subliminal lib, we just package their app up and use it. We don't edit that module

**Comment by NunoHiggs** [comment]
Tks for the feedback. How can i use the subliminal  lib?

**Comment by miigotu** [comment]
If I make you a branch to try with an updated subliminal lib, can you try it?

**Comment by NunoHiggs** [comment]
Yes. Can you make it?

**Comment by miigotu** [comment]
One sec

**Comment by miigotu** [comment]
Branch name is subliminal

**Comment by miigotu** [comment]
Any results to report?

**Comment by NunoHiggs** [comment]
Updating now. Ill get back to you soon

**Comment by NunoHiggs** [comment]
I am unable to test. 
When trying to do an mass add of a directory that has NO subtiles, this started appearing in the logs:

020-01-09 09:20:57 ERROR    Uncaught exception POST /sickrage/addShows/massAddTable/ (172.16.0.10)
HTTPServerRequest(protocol=u'http', host='lxcvpar50.net.xpto:8081', method='POST', uri='/sickrage/addShows/massAddTable/', version='HTTP/1.1', remote_ip='172.16.0.10', headers={'Origin': 'http://lxcvpar50.net.xpto:8081', 'Content-Length': '118', 'Accept-Language': 'pt,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': 'lxcvpar50.net.xpto:8081', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://lxcvpar50.net.xpto:8081/sickrage/addShows/existingShows/', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
Traceback (most recent call last):
  File "/opt/sickchill/lib/tornado/web.py", line 1511, in _execute
    result = yield result
  File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/sickchill/lib/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/sickchill/lib/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/sickchill.subliminal/sickchill/views/index.py", line 160, in get
    results = yield self.async_call(method)
  File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/sickchill/lib/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/opt/sickchill/lib/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/sickchill.subliminal/sickchill/views/index.py", line 182, in async_call
    result = function(**kwargs)
  File "/opt/sickchill.subliminal/sickchill/views/manage/add_shows.py", line 200, in massAddTable
    result = find_on_indexers(indexer_id, show_name, indexer)
  File "/opt/sickchill.subliminal/sickchill/views/manage/add_shows.py", line 183, in find_on_indexers
    search_results = sickchill.indexer.search_indexers_for_series_name(n)
  File "/opt/sickchill.subliminal/sickchill/show/indexers/handler.py", line 102, in search_indexers_for_series_name
    search = indexer.search(name, language)
  File "/opt/sickchill.subliminal/sickchill/show/indexers/tvdb.py", line 122, in search
    return result
UnboundLocalError: local variable 'result' referenced before assignment

**Comment by NunoHiggs** [comment]
This is how i procceded about:

(on the sickchill dir)

 git checkout subliminal
 git fetch
 git update
 git merge master


Then started sickchill, and tried to add a new series via directory that does not have any subtititles.
All my other dirs have all the subtitles via opensubtitles - altough they are not as refined as the ones form legendas.

That error is generated when i try to add the new dir.

**Comment by miigotu** [comment]
@NunoHiggs I fixed that error, but searching legendas.tv works fine
