### ISSUE TITLE
[APP SUBMITTED]: datetime.date(1896, 1, 1) is not JSON serializable

### ISSUE THREAD

**Issue by overloadsix** [SickChill/SickChill#5833]
### INFO
Python Version: **2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-171-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@17e379df7dadc7711db1c76695411267f245a961
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_4 :: [17e379d] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickchill/sickchill/views/index.py", line 180, in async_call
    result = function(**kwargs)
  File "/opt/sickchill/sickchill/views/manage/add_shows.py", line 122, in searchIndexersForShowName
    return json.dumps({'results': final_results, 'langid': lang_id, 'success': len(final_results) > 0})
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.date(1896, 1, 1) is not JSON serializable

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by overloadsix** [comment]
### INFO
Python Version: **2.7.12 (default, Oct  8 2019, 14:14:10) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.4.0-171-generic-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@17e379df7dadc7711db1c76695411267f245a961
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_5 :: [17e379d] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickchill/sickchill/views/index.py", line 180, in async_call
    result = function(**kwargs)
  File "/opt/sickchill/sickchill/views/manage/add_shows.py", line 122, in searchIndexersForShowName
    return json.dumps({'results': final_results, 'langid': lang_id, 'success': len(final_results) > 0})
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.date(1896, 1, 1) is not JSON serializable

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
