### ISSUE TITLE
Can not add show with & in title. Series not found by title or tvdb id 

### ISSUE THREAD

**Issue by klainn** [SickChill/SickChill#5836]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
Branch: master
Commit: 17e379df7dadc7711db1c76695411267f245a961
Database Version: 44.1
OS: Unraid nas 
Browser: chrome
What you did:
Attempting to add Locke & key from thetvdb https://thetvdb.com/series/locke-and-key but no results returned using title or thetvdb show id 
What happened:
No results found
What you expected:
Find the show 
Logs:
```

AA TypeError: addExistingShows() takes exactly 3 arguments (1 given) AA result = function(**kwargs) AA File "/app/sickchill/sickchill/views/index.py", line 180, in async_call AA result = self.fn(*self.args, **self.kwargs) AA File "/app/sickchill/lib/concurrent/futures/thread.py", line 63, in run AA return self.__get_result() AA File "/app/sickchill/lib/concurrent/futures/_base.py", line 455, in result AA value = future.result() AA File "/app/sickchill/lib/tornado/gen.py", line 1055, in run AA results = yield self.async_call(method) AA File "/app/sickchill/sickchill/views/index.py", line 158, in get AA yielded = self.gen.throw(*exc_info) AA File "/app/sickchill/lib/tornado/gen.py", line 1063, in run AA raise_exc_info(self._exc_info) AA File "/app/sickchill/lib/tornado/concurrent.py", line 238, in result AA value = future.result() AA File "/app/sickchill/lib/tornado/gen.py", line 1055, in run AA result = yield result AA File "/app/sickchill/lib/tornado/web.py", line 1511, in _execute AA Traceback (most recent call last): AA HTTPServerRequest(protocol=u'http', host='192.168.0.103:8083', method='GET', uri='/addShows/addExistingShows', version='HTTP/1.1', remote_ip='192.168.0.115', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.0.103:8083', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (iPad; CPU OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/79.0.3945.73 Mobile/15E148 Safari/604.1', 'Connection': 'keep-alive', 'Cookie': 'blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_top_250_movies_view=thumb; late_view=list; soon_view=thumb; suggest_view=thumb; snatched_view=list; user="2|1:0|10:1578645446|4:user|44:MWZmMDE0OGJjZDg3NDMxNWE2ZGI2MTMxMmE0YmRhYjA=|ff3a92ca9904a16013bd43162067cd3002f59cab8cd177e0a73427bfdfd0bae6"; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; login_cookie=e4bc3171c255ee5055114ca367a370695d00e8f4; login_salt=432; sickchill_user="2|1:0|10:1576836203|14:sickchill_user|44:NDFlYTg2OWI2MDUyZDc0ZTVjM2I5Mzk1ZWFkMzBhMTQ=|445cbd17745a0540b054d6931704c7bcea40a4e944caf1e82fa177a559fdad0b"; plushQueuePerPage=9999999; plushHistPerPage=50', 'Upgrade-Insecure-Requests': '1'}) AA 2020-01-10 04:01:18 ERROR Uncaught exception GET /addShows/addExistingShows (192.168.0.115) AA TypeError: addExistingShows() takes exactly 3 arguments (1 given) AA result = function(**kwargs) AA File "/app/sickchill/sickchill/views/index.py", line 180, in async_call AA Traceback (most recent call last): AA TypeError: addExistingShows() takes exactly 3 arguments (1 given) AA result = function(**kwargs) AA File "/app/sickchill/sickchill/views/index.py", line 180, in async_call 2020-01-10 04:01:18 ERROR ThreadPoolExecutor-0_0 :: [17e379d] Failed doing webui callback: Traceback (most recent call last): AA TypeError: addExistingShows() takes exactly 3 arguments (1 given) AA result = function(**kwargs) AA File "/app/sickchill/sickchill/views/index.py", line 180, in async_call AA result = self.fn(*self.args, **self.kwargs) AA File "/app/sickchill/lib/concurrent/futures/thread.py", line 63, in run AA return self.__get_result() AA File "/app/sickchill/lib/concurrent/futures/_base.py", line 455, in result AA value = future.result() AA File "/app/sickchill/lib/tornado/gen.py", line 1055, in run AA results = yield self.async_call(method) AA File "/app/sickchill/sickchill/views/index.py", line 158, in get AA yielded = self.gen.throw(*exc_info) AA File "/app/sickchill/lib/tornado/gen.py", line 1063, in run AA raise_exc_info(self._exc_info) AA File "/app/sickchill/lib/tornado/concurrent.py", line 238, in result AA value = future.result() AA File "/app/sickchill/lib/tornado/gen.py", line 1055, in run AA result = yield result AA File "/app/sickchill/lib/tornado/web.py", line 1511, in _execute AA Traceback (most recent call last): AA HTTPServerRequest(protocol=u'http', host='192.168.0.103:8083', method='GET', uri='/addShows/addExistingShows', version='HTTP/1.1', remote_ip='192.168.0.115', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.0.103:8083', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (iPad; CPU OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/79.0.3945.73 Mobile/15E148 Safari/604.1', 'Connection': 'keep-alive', 'Cookie': 'blu_ray_com_new_releases_view=thumb; imdb_box_office_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_top_250_movies_view=thumb; late_view=list; soon_view=thumb; suggest_view=thumb; snatched_view=list; user="2|1:0|10:1578645446|4:user|44:MWZmMDE0OGJjZDg3NDMxNWE2ZGI2MTMxMmE0YmRhYjA=|ff3a92ca9904a16013bd43162067cd3002f59cab8cd177e0a73427bfdfd0bae6"; plushContainerWidth=100%25; plushMultiOps=1; plushNoTopMenu=0; login_cookie=e4bc3171c255ee5055114ca367a370695d00e8f4; login_salt=432; sickchill_user="2|1:0|10:1576836203|14:sickchill_user|44:NDFlYTg2OWI2MDUyZDc0ZTVjM2I5Mzk1ZWFkMzBhMTQ=|445cbd17745a0540b054d6931704c7bcea40a4e944caf1e82fa177a559fdad0b"; plushQueuePerPage=9999999; plushHistPerPage=50', 'Upgrade-Insecure-Requests': '1'}) AA 2020-01-10 04:01:18 ERROR Uncaught exception GET /addShows/addExistingShows (192.168.0.115) AA TypeError: addExistingShows() takes exactly 3 arguments (1 given) AA result = function(**kwargs) AA File "/app/sickchill/sickchill/views/index.py", line 180, in async_call AA Traceback (most recent call last): AA TypeError: addExistingShows() takes exactly 3 arguments (1 given) AA result = function(**kwargs) AA File "/app/sickchill/sickchill/views/index.py", line 180, in async_call 2020-01-10 04:01:18 ERROR ThreadPoolExecutor-0_1 :: [17e379d] Failed doing webui callback: Traceback (most recent call last):

```

**Comment by klainn** [comment]
I managed to manually add this but copying a tvshow.nfo from another series and changing a few of the show specific bits. The & seemed to be throwing it off. Not surprising. When I had the title in the nfo set to Locke & Key I received

```

2020-01-10 04:16:33 WARNING ThreadPoolExecutor-0_1 :: There was an error parsing your existing metadata file: '/tv/locke.and.key/tvshow.nfo' error: not well-formed (invalid token): line 3, column 16

```

Which was the &

**Comment by miigotu** [comment]
This is fixed in develop, because we switched to the tvdb API v3

**Comment by klainn** [comment]
I had switched to the develop branch and was unable to add it with the same error as well, but I will trust you are correct.

**Comment by miigotu** [comment]
@klainn I found the problem, ill be adding a fix for it in my next commit
