### ISSUE TITLE
[APP SUBMITTED]: '__TVShow' object has no attribute 'lang'

### ISSUE THREAD

**Issue by krangas** [SickChill/SickChill#5863]
### INFO
Python Version: **2.7.16 (default, May 23 2019, 05:34:26) [GCC 7.4.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7f1edd5394aff690feccf43f1e0e1ea31b0500e7
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [7f1edd5] Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/views/index.py", line 182, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/views/manage/add_shows.py", line 345, in getTrendingShowImage
    image_url = sickchill.indexer.series_poster_url_by_id(indexerId)
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/handler.py", line 189, in series_poster_url_by_id
    return self.series_poster_url(__TVShow(indexerid, language, indexer), thumb)
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/handler.py", line 192, in series_poster_url
    return self.indexers[show.indexer].series_poster_url(show, thumb)
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/tvdb.py", line 182, in series_poster_url
    return self.__call_images_api(show, thumb, 'poster')
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/wrappers.py", line 38, in wrapper
    result = target(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/tvdb.py", line 171, in __call_images_api
    images = self.series_images(show.indexerid, show.lang, keyType=keyType, subKey=subKey)
AttributeError: '__TVShow' object has no attribute 'lang'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by krangas** [comment]
### INFO
Python Version: **2.7.16 (default, May 23 2019, 05:34:26) [GCC 7.4.0]**
Operating System: **Linux-4.2.8-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@7f1edd5394aff690feccf43f1e0e1ea31b0500e7
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [7f1edd5] Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/views/index.py", line 182, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/views/manage/add_shows.py", line 345, in getTrendingShowImage
    image_url = sickchill.indexer.series_poster_url_by_id(indexerId)
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/handler.py", line 189, in series_poster_url_by_id
    return self.series_poster_url(__TVShow(indexerid, language, indexer), thumb)
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/handler.py", line 192, in series_poster_url
    return self.indexers[show.indexer].series_poster_url(show, thumb)
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/tvdb.py", line 182, in series_poster_url
    return self.__call_images_api(show, thumb, 'poster')
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/wrappers.py", line 38, in wrapper
    result = target(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/tvdb.py", line 171, in __call_images_api
    images = self.series_images(show.indexerid, show.lang, keyType=keyType, subKey=subKey)
AttributeError: '__TVShow' object has no attribute 'lang'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators
