### ISSUE TITLE
logger error on launch

### ISSUE THREAD

**Issue by mgaulton** [SickChill/SickChill#5869]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: git master and devlop
OS: Opensuse Tumbleweed
Browser: Chrome
What you did: Tried to launch SickChill
What happened:
Failure to launch
What you expected:
Logs:
```

server6:/opt/SickBeard-tvrage # python /opt/SickBeard-tvrage/SickBeard.py -q --daemon --nolaunch --pidfile /var/run/sickrage/sickrage.pid --datadir /opt/SBconfig
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python2.7/logging/handlers.py", line 156, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/opt/SickBeard-tvrage/sickbeard/logger.py", line 107, in format
    msg = re.sub(r'\b({item})\b'.format(item=item), '*' * 8, msg)
  File "/usr/lib64/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib64/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: multiple repeat
Logged from file logger.py, line 255

```

**Comment by miigotu** [comment]
If you open sickbeard/logger.py and replace:
```python
msg = re.sub(r'\b({item})\b'.format(item=item), '*' * 8, msg)
```
With
```python
msg = re.sub(r'\b({item})\b'.format(item=re.escape(item)), '*' * 8, msg)
```
Does that work and still censor the username/password from your logs?

**Comment by mgaulton** [comment]
Awesome, thanks.
