### ISSUE TITLE
folders not showing when trying to add existing shows 

### ISSUE THREAD

**Issue by mixquilz** [SickChill/SickChill#5883]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Windows
Browser: Chrome
What you did: tried to "add existing shows"
What happened: spinning while showing loading but no folders showed
What you expected: folders of shows i have not added to sickhill
Logs:
```
PASTE LOGS HERE
2020-01-17 15:25:43 ThreadPoolExecutor-0_2 :: [a39f879] Failed doing webui callback: Traceback (most recent call last):
File "C:\SickChill\SickChill\sickchill\views\index.py", line 182, in async_call
result = function(**kwargs)
File "C:\SickChill\SickChill\sickchill\views\manage\add_shows.py", line 211, in massAddTable
result = find_on_indexers(indexer_id, show_name, indexer)
File "C:\SickChill\SickChill\sickchill\views\manage\add_shows.py", line 191, in find_on_indexers
search_results = sickchill.indexer.search_indexers_for_series_name(n, exact=True)
File "C:\SickChill\SickChill\sickchill\show\indexers\handler.py", line 104, in search_indexers_for_series_name
search = indexer.search(name, language=language, exact=exact)
File "C:\SickChill\SickChill\sickchill\show\indexers\wrappers.py", line 38, in wrapper
result = target(*args, **kwargs)
File "C:\SickChill\SickChill\sickchill\show\indexers\tvdb.py", line 138, in search
result = self._search(attempt, language=language)
File "C:\SickChill\SickChill\lib\tvdbsimple\search.py", line 55, in series
response = self._GET(path, params=filters)
File "C:\SickChill\SickChill\lib\tvdbsimple\base.py", line 149, in _GET
return self._request('GET', path, params=params, cleanJson=cleanJson)
File "C:\SickChill\SickChill\lib\tvdbsimple\base.py", line 142, in _request
return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
File "C:\SickChill\SickChill\lib\tvdbsimple\base.py", line 126, in _request
self._set_token_header(forceNewToken)
File "C:\SickChill\SickChill\lib\tvdbsimple\base.py", line 91, in _set_token_header
self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
File "C:\SickChill\SickChill\lib\tvdbsimple\base.py", line 122, in get_token
raise AuthenticationError(error)
AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
```

**Comment by miigotu** [comment]
Their api was down it looks like.
