### ISSUE TITLE
The Daily Show is not displaying any episodes

### ISSUE THREAD

**Issue by damagu** [SickChill/SickChill#5915]
Branch/Commit: v2020.01.21-1
OS: OSMC
Browser: Chrome Version 79.0.3945.117 (Official Build) (64-bit)
When I look at the episode list in http://192.168.178.10:8899/home/displayShow?show=71256 the list is empty. I.e. no seasons or episodes are listed at all. I'm not getting any errors or warnings related to this so I'm not sure that the debug logs will help. Is it possible that the problem relates to the size of the list (25 seasons with 150+ episodes each).

**Comment by Wally73** [comment]
just do a force full update

**Comment by miigotu** [comment]
Tvdb issue, their api is only working sometimes right now. It will resolve when they are done messing with it

**Comment by damagu** [comment]
I did a force update and got this error:
SHOWQUEUE-FORCE-UPDATE :: [855f137] Unable to get info from theTVDB, the show info will not be refreshed: 'NoneType' object has no attribute 'get'

**Comment by miigotu** [comment]
Show the rest of the debug log

**Comment by defhead** [comment]
Here some logs for the same error ('NoneType' object has no attribute 'get'):

```
2020-01-23 22:53:22 ERROR    SHOWQUEUE-ADD :: [1ed3156] Error with theTVDB, not creating episode list: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/sickchill/sickbeard/show_queue.py", line 477, in run
    self.show.loadEpisodesFromIndexer()
  File "/app/sickchill/sickbeard/tv.py", line 535, in loadEpisodesFromIndexer
    show_episode.loadFromIndexer(*season_episode)
  File "/app/sickchill/sickbeard/tv.py", line 1575, in loadFromIndexer
    if not myEp.get('episodeName'):
AttributeError: 'NoneType' object has no attribute 'get'
2020-01-23 22:53:22 DEBUG    SHOWQUEUE-ADD :: Traceback (most recent call last):
  File "/app/sickchill/sickbeard/show_queue.py", line 477, in run
    self.show.loadEpisodesFromIndexer()
  File "/app/sickchill/sickbeard/tv.py", line 535, in loadEpisodesFromIndexer
    show_episode.loadFromIndexer(*season_episode)
  File "/app/sickchill/sickbeard/tv.py", line 1575, in loadFromIndexer
    if not myEp.get('episodeName'):
AttributeError: 'NoneType' object has no attribute 'get'
```

The show was "Star Trek: Picard"

**Comment by mgaulton** [comment]
I started getting the below today, latest version, linux opensuse tumbleweed. Just curious if this is an api thing again?

2020-02-28 15:14:32 WARNING  SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: 'NoneType' object has no attribute 'info'
