### ISSUE TITLE
Show Episodes not loading 

### ISSUE THREAD

**Issue by marcb1387** [SickChill/SickChill#5921]
This looks like the Issues we have been having with TVDB API but wanted to post to confirm and for visibility of others if they came looking. 

Branch/Commit: Master/855f1372e4a868fb27e8202a51dbfcebb9c0701f Latest 
OS: WIn 10
Browser: Chrome
What you did: Added a new show 
What happened: Show loaded but not episodes 
What you expected: Episodes 
Logs:
```
AA AttributeError: 'NoneType' object has no attribute 'get'
AA if not myEp.get('episodeName'):
AA File "/opt/sickchill/sickbeard/tv.py", line 1575, in loadFromIndexer
AA show_episode.loadFromIndexer(*season_episode)
AA File "/opt/sickchill/sickbeard/tv.py", line 535, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "/opt/sickchill/sickbeard/show_queue.py", line 665, in run
AA Traceback (most recent call last):
2020-01-23 20:55:40 ERROR SHOWQUEUE-FORCE-UPDATE :: [855f137] Unable to get info from theTVDB, the show info will not be refreshed: 'NoneType' object has no attribute 'get'
```

**Comment by miigotu** [comment]
Should be fixed now, not failing when tvdb returns junk or None

**Comment by miigotu** [comment]
#5915
