### ISSUE TITLE
API Builder Broken

### ISSUE THREAD

**Issue by theone678-beep** [SickChill/SickChill#5922]
The API builder is broken in the current release, please see details below. Thanks in advance for any help :)

Branch/Commit: master
OS: MacOS
Browser: Firefox
What you did: Go to the general settings -> interface -> API -> click the link to the API builder (/apibuilder/)
What happened: Showing a blank page and giving errors in the log
What you expected: See the API builder
Logs:
```
2020-01-25 12:12:49 WEBSERVER-WEBROOT :: [be5e346] Failed doing webui callback: Traceback (most recent call last):
  File "/Users/test/sickchill/sickchill/views/index.py", line 182, in async_call
    result = function(**kwargs)
  File "/Users/test/sickchill/sickchill/views/index.py", line 232, in apibuilder
    t = PageTemplate(rh=self, filename='apiBuilder.mako')
  File "/Users/test/sickchill/sickchill/views/common.py", line 64, in __init__
    self.template = lookup.get_template(filename)
  File "/Users/test/sickchill/lib/mako/lookup.py", line 260, in get_template
    return self._load(srcfile, uri)
  File "/Users/test/sickchill/lib/mako/lookup.py", line 327, in _load
    **self.template_args
  File "/Users/test/sickchill/lib/mako/template.py", line 347, in __init__
    module = self._compile_from_file(path, filename)
  File "/Users/test/sickchill/lib/mako/template.py", line 413, in _compile_from_file
    self, data, filename, path, self.module_writer
  File "/Users/test/sickchill/lib/mako/template.py", line 749, in _compile_module_file
    template, text, filename, generate_magic_comment=True
  File "/Users/test/sickchill/lib/mako/template.py", line 708, in _compile
    node = lexer.parse()
  File "/Users/test/sickchill/lib/mako/lexer.py", line 272, in parse
    if self.match_python_block():
  File "/Users/test/sickchill/lib/mako/lexer.py", line 417, in match_python_block
    pos=pos,
  File "/Users/test/sickchill/lib/mako/lexer.py", line 152, in append_node
    node = nodecls(*args, **kwargs)
  File "/Users/test/sickchill/lib/mako/parsetree.py", line 159, in __init__
    self.code = ast.PythonCode(text, **self.exception_kwargs)
  File "/Users/test/sickchill/lib/mako/ast.py", line 43, in __init__
    expr = pyparser.parse(code.lstrip(), "exec", **exception_kwargs)
  File "/Users/test/sickchill/lib/mako/pyparser.py", line 54, in parse
    **exception_kwargs
SyntaxException: (IndentationError) unexpected indent (, line 7) (u'if required:\n    # noinspection PyUnusedLocal\n    ') in file '/Users/test/sickchill/gui/slick/views/apiBuilder.mako' at line: 272 char: 9
```

**Comment by miigotu** [comment]
Fixed
