### ISSUE TITLE
Update Failed 

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#5947]
SickChill Info:
Branch: master
Commit: 54aaf19ff076d5591c60e757135cdaf58d6cc31d
Database Version: 44.1
  Python Version:
2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]
  SSL Version:
OpenSSL 1.0.2t 10 Sep 2019
  OS:
Windows-7-6.1.7601-SP1
  Locale:
en_US.cp1252

What you did:   Clicked the update from the notice
What happened:   Update Error see logs
What you expected:   Update
Logs:
```
2020-01-30 06:59:18 INFO     EVENT-QUEUE :: Aborting all threads
AA WindowsError: [Error 2] The system cannot find the file specified: u'C:\\SickChil\\sr-update\\SickChill-SickChill-54aaf19\\lib\\pytz\\zoneinfo\\America\\Barbados'
AA os.remove(fullname)
AA File "C:\Python27\lib\shutil.py", line 273, in rmtree
AA onerror(os.remove, fullname, sys.exc_info())
AA File "C:\Python27\lib\shutil.py", line 275, in rmtree
AA rmtree(fullname, ignore_errors, onerror)
AA File "C:\Python27\lib\shutil.py", line 270, in rmtree
AA rmtree(fullname, ignore_errors, onerror)
AA File "C:\Python27\lib\shutil.py", line 270, in rmtree
AA rmtree(fullname, ignore_errors, onerror)
AA File "C:\Python27\lib\shutil.py", line 270, in rmtree
AA rmtree(fullname, ignore_errors, onerror)
AA File "C:\Python27\lib\shutil.py", line 270, in rmtree
AA rmtree(fullname, ignore_errors, onerror)
AA File "C:\Python27\lib\shutil.py", line 270, in rmtree
AA shutil.rmtree(sr_update_dir)
AA File "C:\SickChil\sickbeard\versionChecker.py", line 797, in update
AA Traceback (most recent call last):
2020-01-30 06:59:09 ERROR    WEBSERVER-HOME :: [248db26] Error while trying to update: error 2 : The system cannot find the file specified
2020-01-30 06:59:09 INFO     WEBSERVER-HOME :: Clearing out update folder C:\SickChil\sr-update before extracting
2020-01-30 06:59:08 INFO     WEBSERVER-HOME :: Config backup successful, updating...
2020-01-30 06:58:48 INFO     WEBSERVER-HOME :: Moving files from C:\SickChil\sr-update\SickChill-SickChill-54aaf19 to C:\SickChil
2020-01-30 06:58:48 INFO     WEBSERVER-HOME :: Deleting file C:\SickChil\sr-update\sr-update.tar
2020-01-30 06:57:49 INFO     WEBSERVER-HOME :: Extracting file C:\SickChil\sr-update\sr-update.tar
2020-01-30 06:57:40 INFO     WEBSERVER-HOME :: Downloading update from http://github.com/SickChill/SickChill/tarball/master
2020-01-30 06:57:40 INFO     WEBSERVER-HOME :: Creating update folder C:\SickChil\sr-update before extracting
2020-01-30 06:57:39 INFO     WEBSERVER-HOME :: Config backup successful, updating...
2020-01-30 06:57:22 INFO     WEBSERVER-HOME :: Config backup in progress...

```

**Comment by nydave69** [comment]
I did a restart of SC..   from the log
2020-01-30 07:21:01 INFO     SEARCHQUEUE-MANUAL- :: Beginning manual search for: [Schitt's Creek - S06E04 - Maid of Honour]
2020-01-30 07:16:33 INFO     CHECKVERSION :: Checking for updates using SOURCE
2020-01-30 07:16:33 INFO     WEBSERVER :: Starting SickChill on http://0.0.0.0:8085/


It just paused check version,  I kicked off the search to see if it's running..  looks like it

**Comment by miigotu** [comment]
im sure its fine

**Comment by miigotu** [comment]
Also, you are using czotti fork?
