### ISSUE TITLE
Cant Add Shows From Tract The Error Below Occurs

### ISSUE THREAD

**Issue by cadmuslabslex** [SickChill/SickChill#5950]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: Windows 7 X64
Browser: FireFox
What you did: Add Shows From Tract
What happened:
2020-02-02 04:17:37 INFO     SHOWQUEUE-FORCE-UPDATE :: No XEM data for show "311711 on theTVDB"
2020-02-02 04:17:37 INFO     SHOWQUEUE-FORCE-UPDATE :: Request failed: HTTPConnectionPool(host='thexem.de', port=80): Max retries exceeded with url: /map/all?id=311711&origin=tvdb&destination=scene (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)) ()
AA TypeError: get() takes at least 2 arguments (1 given)
AA result = func(*args, **kwargs)
AA File "C:\SickChill\SickChill\lib\tornado\gen.py", line 292, in wrapper
AA raise_exc_info(self._exc_info)
AA File "C:\SickChill\SickChill\lib\tornado\concurrent.py", line 238, in result
AA value = future.result()
AA File "C:\SickChill\SickChill\lib\tornado\gen.py", line 1055, in run
AA result = yield result
AA File "C:\SickChill\SickChill\lib\tornado\web.py", line 1511, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol=u'http', host='192.168.1.111:8081', method='GET', uri='/favicon.ico', version='HTTP/1.1', remote_ip='192.168.1.111', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.111:8081', 'Accept': 'image/webp,*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0', 'Connection': 'keep-alive', 'Cookie': 'smplrefresh=5; login_cookie=c44499346f5a1bdcdc20f1542781bf95661fe357; login_salt=631'})
AA 2020-02-02 04:16:52 ERROR    Uncaught exception GET /favicon.ico (192.168.1.111)
What you expected: The Show to add.

**Comment by miigotu** [comment]
Looks like either thexem was down or you had a connection problem
