### ISSUE TITLE
Python error on loading

### ISSUE THREAD

**Issue by youdroid** [SickChill/SickChill#5974]
Branch/Commit: On master, last commit
OS: Debian 4.9.210-1
Browser: Chrome
What you did: Try to start service on boot or manualy
What happened: Failed to start SickChill Daemon, when i search the line on file to try to debug, i don't find the corresponding line. It's impossible for me to start the service any idea ?

Logs:
```
févr. 12 23:10:06 Download python2.7[9095]: Traceback (most recent call last):
févr. 12 23:10:06 Download python2.7[9095]:   File "/opt/sickchill/SickBeard.py", line 546, in <module>
févr. 12 23:10:06 Download python2.7[9095]:     SickChill().start()
févr. 12 23:10:06 Download python2.7[9095]:   File "/opt/sickchill/SickBeard.py", line 245, in start
févr. 12 23:10:06 Download python2.7[9095]:     sickbeard.CFG = ConfigObj(sickbeard.CONFIG_FILE, encoding='UTF-8')
févr. 12 23:10:06 Download python2.7[9095]:   File "/opt/sickchill/lib/configobj.py", line 1219, in __init__
févr. 12 23:10:06 Download python2.7[9095]:     self._load(infile, configspec)
févr. 12 23:10:06 Download python2.7[9095]:   File "/opt/sickchill/lib/configobj.py", line 1302, in _load
févr. 12 23:10:06 Download python2.7[9095]:     raise error
févr. 12 23:10:06 Download python2.7[9095]: configobj.ParseError: Invalid line at line "678".
févr. 12 23:10:06 Download systemd[1]: sickchill.service: Control process exited, code=exited status=1
févr. 12 23:10:06 Download systemd[1]: Failed to start SickChill Daemon.
```

**Comment by youdroid** [comment]
Problem solved, just remove corrupted data on my file config.ini (one line had just key, and no value)
