### ISSUE TITLE
Exception while searching YggTorrent. Error: AttributeError("'NoneType' object has no attribute 'url'",)

### ISSUE THREAD

**Issue by PixLzzz** [SickChill/SickChill#5998]
OS: Ubuntu
Browser: Chrome
What you did: Nothing
What happened: Have like 100 errors per days in errorlogs of sickchill
Logs:
```
2020-02-19 11:35:35 SEARCHQUEUE-BACKLOG-79635 :: [YggTorrent] :: [c0061b1] Exception while searching YggTorrent. Error: AttributeError("'NoneType' object has no attribute 'url'",)
2020-02-19 11:35:05 SEARCHQUEUE-BACKLOG-360898 :: [YggTorrent] :: [c0061b1] Exception while searching YggTorrent. Error: AttributeError("'NoneType' object has no attribute 'url'",)
2020-02-19 11:35:00 SEARCHQUEUE-BACKLOG-318408 :: [YggTorrent] :: [c0061b1] Exception while searching YggTorrent. Error: AttributeError("'NoneType' object has no attribute 'url'",)
2020-02-19 11:34:55 SEARCHQUEUE-BACKLOG-270408 :: [YggTorrent] :: [c0061b1] Exception while searching YggTorrent. Error: AttributeError("'NoneType' object has no attribute 'url'",)
2020-02-19 11:34:42 SEARCHQUEUE-BACKLOG-361594 :: [YggTorrent] :: [c0061b1] Exception while searching YggTorrent. Error: AttributeError("'NoneType' object has no attribute 'url'",)
```
If you have any idea on how to make it disappear..
Thank you for your help,

**Comment by thenamelessthing** [comment]
Me too! I revised my settings and everything seems to be correct.

**Comment by dsm1212** [comment]
Same problem with kickasstorrents. I think it just started after I updated on 12/17. I'm usually only a few days behind so it was around that time the change occurred.

2020-02-17 13:17:39 ERROR    FINDPROPERS :: [KickAssTorrents] :: [1f124b3] Exception while searching propers in KickAssTorrents, skipping: 'NoneType
' object is not callable
Traceback (most recent call last):
  File "/apps/sickbeard/sickbeard/properFinder.py", line 93, in _getProperList
    curPropers = curProvider.find_propers(search_date)
  File "/apps/sickbeard/sickchill/providers/torrent/TorrentProvider.py", line 68, in find_propers
    for item in self.search(search_string):
  File "/apps/sickbeard/sickbeard/providers/kat.py", line 120, in search
    labels = [cell.get_text() for cell in html.find(class_="firstr")("th")]
TypeError: 'NoneType' object is not callable

**Comment by fildar** [comment]
Same issue here with Yggtorrent.
Sickchill is running in linuxserver-sickchill docker container on a Synology NAS.
Only 2 lines have been added to the sickchill/sickbeard/providers/yggtorrent.py file (lines 122 & 123).
I removed them and it seems to do the trick.
Hope this helps

**Comment by miigotu** [comment]
Fixed
