### ISSUE TITLE
Process Hang/CPU Usage

### ISSUE THREAD

**Issue by kcwebby** [SickChill/SickChill#6004]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 1f124b31b16303a511c86717f11dd28b9cbf7b46
Database Version: 44.1
OS: Ubuntu / Docker
Browser: Chrome
What you did: Clicked the Schedule / Also occurs when trying to filter the log
What happened:  CPU pegged out, hung, and I think sickchill crashed
What you expected:  Schedule to load as normal.
Logs:
```
PROCESS INFO: 140.2% CPU 61.2% Mem  17:32.01 python /app/sickchill/SickBeard.py --datadir /config
```
LOG:
```
2020-02-20 21:07:08 INFO     SEARCHQUEUE-MANUAL-73762 :: [Local Hydra2] :: Performing season pack search for Grey's Anatomy
2020-02-20 21:07:08 INFO     SEARCHQUEUE-MANUAL- :: Unable to find a download for: [Grey's Anatomy - S16E14 - A Diagnosis]
2020-02-20 21:07:11 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-02-20 21:08:12 INFO     EVENT-QUEUE :: Aborting all threads
2020-02-20 21:08:12 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE-REFRESH thread to exit
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE-MANUAL-73762 thread to exit
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Saving all shows to the database
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Saving config file to disk
2020-02-20 21:08:13 INFO     EVENT-QUEUE :: Shutting down Tornado
2020-02-20 21:08:22 INFO     MAIN :: Starting SickChill [master] using '/config/config.ini'
2020-02-20 21:08:22 INFO     WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
2020-02-20 21:08:27 INFO     SHOWUPDATER :: ShowUpdater for tvdb Api V3 starting
2020-02-20 21:08:27 INFO     SHOWUPDATER :: Last update: 2020-02-20 20:53:38
2020-02-20 21:08:32 INFO     SHOWQUEUE-REFRESH :: Performing refresh on Chicago Fire

```
(SECOND EVENT LOG)
```
2020-02-20 20:53:29 WARNING SHOWUPDATER :: Updating network timezones failed, this can happen from time to time. URL: http://sickchill.github.io/sb_network_timezones/network_timezones.txt
AA TypeError: get() takes at least 2 arguments (1 given)
AA result = func(*args, **kwargs)
AA File "/app/sickchill/lib/tornado/gen.py", line 292, in wrapper
AA raise_exc_info(self._exc_info)
AA File "/app/sickchill/lib/tornado/concurrent.py", line 238, in result
AA value = future.result()
AA File "/app/sickchill/lib/tornado/gen.py", line 1055, in run
AA result = yield result
AA File "/app/sickchill/lib/tornado/web.py", line 1511, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='https', host='rage.local:443', method='GET', uri='/favicon.ico', version='HTTP/1.1', remote_ip='172.0.0.12', headers={'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'X-Forwarded-Host': 'rage.local', 'X-Forwarded-Ssl': 'on', 'X-Forwarded-For': '172.0.0.12', 'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36', 'Host': 'rage.local:443', 'X-Forwarded-Proto': 'https', 'Referer': 'https://rage.local/schedule/', 'Sec-Fetch-Mode': 'no-cors', 'X-Real-Ip': '172.0.0.12', 'Cookie': '_ga=GA1.2.1911477551.1556070295; sickchill_user="2|1:0|10:1580177682|14:sickchill_user|44:NjA2MjVkZGM0MzQ3MWMzZDJkYTIyY2RlMWM4ZDM0M2U=|dc4220e699dfb92b6b5e775a21b8cf90e14d6fcff5e2d38b153a639b31e9d039"; _policy=%7B%22restricted_market%22:true,%22tracking_market%22:%22explicit%22%7D; visitor=vid=5c053c17-9329-5f68-b166-27a9543fe9f5; _gid=GA1.2.1337364564.1582251572', 'Sec-Fetch-Site': 'same-origin'})
AA 2020-02-20 20:53:29 ERROR Uncaught exception GET /favicon.ico (172.0.0.12)
2020-02-20 20:50:44 WARNING MAIN :: Updating network timezones failed, this can happen from time to time. URL: http://sickchill.github.io/sb_network_timezones/network_timezones.txt
AA timeout: timed out
AA raise err
AA File "/usr/lib/python2.7/socket.py", line 575, in create_connection
AA self.timeout, self.source_address)
AA File "/usr/lib/python2.7/httplib.py", line 821, in connect
AA HTTPConnection.connect(self)
AA File "/usr/lib/python2.7/httplib.py", line 1255, in connect
AA self.connect()
AA File "/usr/lib/python2.7/httplib.py", line 844, in send
AA self.send(msg)
AA File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
AA self._send_output(message_body)
AA File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
AA self.endheaders(body)
AA File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
AA self._send_request(method, url, body, headers)
AA File "/usr/lib/python2.7/httplib.py", line 1042, in request
AA requestHeaders
AA File "/app/sickchill/lib/github/Requester.py", line 293, in __requestRaw
AA status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
AA File "/app/sickchill/lib/github/Requester.py", line 268, in __requestEncode
AA return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
AA File "/app/sickchill/lib/github/Requester.py", line 215, in requestJson
AA return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
AA File "/app/sickchill/lib/github/Requester.py", line 169, in requestJsonAndCheck
AA "/orgs/" + login
AA File "/app/sickchill/lib/github/MainClass.py", line 198, in get_organization
AA sickbeard.gh.get_organization(sickbeard.GIT_ORG)
AA File "/app/sickchill/sickchill/helper/common.py", line 379, in setup_github
AA Traceback (most recent call last):
2020-02-20 20:48:36 ERROR MAIN :: Unable to setup GitHub properly. GitHub will not be available. Error: timed out
AA TypeError: get() takes at least 2 arguments (1 given)
AA result = func(*args, **kwargs)
AA File "/app/sickchill/lib/tornado/gen.py", line 292, in wrapper
AA raise_exc_info(self._exc_info)
AA File "/app/sickchill/lib/tornado/concurrent.py", line 238, in result
AA value = future.result()
AA File "/app/sickchill/lib/tornado/gen.py", line 1055, in run
AA result = yield result
AA File "/app/sickchill/lib/tornado/web.py", line 1511, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='https', host='rage.local:443', method='GET', uri='/favicon.ico', version='HTTP/1.1', remote_ip='172.0.0.12', headers={'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'X-Forwarded-Host': 'rage.local', 'X-Forwarded-Ssl': 'on', 'X-Forwarded-For': '172.0.0.12', 'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36', 'Host': 'rage.local:443', 'X-Forwarded-Proto': 'https', 'Referer': 'https://rage.local/schedule/', 'Sec-Fetch-Mode': 'no-cors', 'X-Real-Ip': '172.0.0.12', 'Cookie': '_ga=GA1.2.1911477551.1556070295; sickchill_user="2|1:0|10:1580177682|14:sickchill_user|44:NjA2MjVkZGM0MzQ3MWMzZDJkYTIyY2RlMWM4ZDM0M2U=|dc4220e699dfb92b6b5e775a21b8cf90e14d6fcff5e2d38b153a639b31e9d039"; _policy=%7B%22restricted_market%22:true,%22tracking_market%22:%22explicit%22%7D; visitor=vid=5c053c17-9329-5f68-b166-27a9543fe9f5; _gid=GA1.2.1337364564.1582251572', 'Sec-Fetch-Site': 'same-origin'})
AA 2020-02-20 20:37:20 ERROR Uncaught exception GET /favicon.ico (172.0.0.12)
AA TypeError: get() takes at least 2 arguments (1 given)
AA result = func(*args, **kwargs)
AA File "/app/sickchill/lib/tornado/gen.py", line 292, in wrapper
AA raise_exc_info(self._exc_info)
AA File "/app/sickchill/lib/tornado/concurrent.py", line 238, in result
AA value = future.result()
AA File "/app/sickchill/lib/tornado/gen.py", line 1055, in run
AA result = yield result
AA File "/app/sickchill/lib/tornado/web.py", line 1511, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='https', host='rage.local:443', method='GET', uri='/favicon.ico', version='HTTP/1.1', remote_ip='172.0.0.12', headers={'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'X-Forwarded-Host': 'rage.local', 'X-Forwarded-Ssl': 'on', 'X-Forwarded-For': '172.0.0.12', 'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36', 'Host': 'rage.local:443', 'X-Forwarded-Proto': 'https', 'Referer': 'https://rage.local/schedule/', 'Sec-Fetch-Mode': 'no-cors', 'X-Real-Ip': '172.0.0.12', 'Cookie': '_ga=GA1.2.1911477551.1556070295; sickchill_user="2|1:0|10:1580177682|14:sickchill_user|44:NjA2MjVkZGM0MzQ3MWMzZDJkYTIyY2RlMWM4ZDM0M2U=|dc4220e699dfb92b6b5e775a21b8cf90e14d6fcff5e2d38b153a639b31e9d039"; _policy=%7B%22restricted_market%22:true,%22tracking_market%22:%22explicit%22%7D; visitor=vid=5c053c17-9329-5f68-b166-27a9543fe9f5; _gid=GA1.2.1337364564.1582251572', 'Sec-Fetch-Site': 'same-origin'})
AA 2020-02-20 20:30:04 ERROR Uncaught exception GET /favicon.ico (172.0.0.12)
2020-02-20 20:29:40 WARNING SHOWUPDATER :: Updating network timezones failed, this can happen from time to time. URL: http://sickchill.github.io/sb_network_timezones/network_timezones.txt
2020-02-20 20:25:41 WARNING MAIN :: Updating network timezones failed, this can happen from time to time. URL: http://sickchill.github.io/sb_network_timezones/network_timezones.txt
AA timeout: timed out
AA raise err
AA File "/usr/lib/python2.7/socket.py", line 575, in create_connection
AA self.timeout, self.source_address)
AA File "/usr/lib/python2.7/httplib.py", line 821, in connect
AA HTTPConnection.connect(self)
AA File "/usr/lib/python2.7/httplib.py", line 1255, in connect
AA self.connect()
AA File "/usr/lib/python2.7/httplib.py", line 844, in send
AA self.send(msg)
AA File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
AA self._send_output(message_body)
AA File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
AA self.endheaders(body)
AA File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
AA self._send_request(method, url, body, headers)
AA File "/usr/lib/python2.7/httplib.py", line 1042, in request
AA requestHeaders
AA File "/app/sickchill/lib/github/Requester.py", line 293, in __requestRaw
AA status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
AA File "/app/sickchill/lib/github/Requester.py", line 268, in __requestEncode
AA return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
AA File "/app/sickchill/lib/github/Requester.py", line 215, in requestJson
AA return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
AA File "/app/sickchill/lib/github/Requester.py", line 169, in requestJsonAndCheck
AA "/orgs/" + login
AA File "/app/sickchill/lib/github/MainClass.py", line 198, in get_organization
AA sickbeard.gh.get_organization(sickbeard.GIT_ORG)
AA File "/app/sickchill/sickchill/helper/common.py", line 379, in setup_github
AA Traceback (most recent call last):
2020-02-20 20:23:33 ERROR MAIN :: Unable to setup GitHub properly. GitHub will not be available. Error: timed out
2020-02-20 20:17:32 WARNING SEARCHQUEUE-DAILY-SEARCH :: [Local Hydra2] :: Error getting caps xml for [Local Hydra2]
2020-02-20 19:37:37 WARNING SEARCHQUEUE-DAILY-SEARCH :: [Local Hydra2] :: Error getting caps xml for [Local Hydra2]
2020-02-20 18:57:31 WARNING SEARCHQUEUE-DAILY-SEARCH :: [Local Hydra2] :: Error getting caps xml for [Local Hydra2]
2020-02-20 18:17:29 WARNING SEARCHQUEUE-DAILY-SEARCH :: [Local Hydra2] :: Error getting caps xml for [Local Hydra2]
2020-02-20 17:37:31 WARNING SEARCHQUEUE-DAILY-SEARCH :: [Local Hydra2] :: Error getting caps xml for [Local Hydra2]
2020-02-20 16:57:29 WARNING SEARCHQUEUE-DAILY-SEARCH :: [Local Hydra2] :: Error getting caps xml for [Local Hydra2]
2020-02-20 16:17:31 WARNING SEARCHQUEUE-DAILY-SEARCH :: [Local Hydra2] :: Error getting caps xml for [Local Hydra2]
```

**Comment by kcwebby** [comment]
Thinking I had a network/routing issue, I verified that all network communication from the docker was working properly.  I think the network timeout was caused by the python process being overworked.

**Comment by BenjV** [comment]
No network timeout is not caused by an overworked python process, that is just not possible.
There was clearly a network issue either local, your internet connection or the sites you tried to reach.
Every call waits for a response with a timeout time ( I am not sure but I think 20 sec) and SickChill does a lot of internet calls, so everytime it wait for that timeout.
During that timeout periode it look likes the process is halted but in fact it is just sleeping.

**Comment by miigotu** [comment]
@kcwebby yes, could not connect to github.
