### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by bradywang** [SickChill/SickChill#6026]
XXX-MacBook-Pro:~ XXX$ python /Applications/SickChill/SickBeard.py
Traceback (most recent call last):
  File "/Applications/SickChill/SickBeard.py", line 70, in <module>
    from sickchill.views.server_settings import SRWebServer
  File "/Applications/SickChill/sickchill/views/__init__.py", line 23, in <module>
    from .authentication import LoginHandler, LogoutHandler
  File "/Applications/SickChill/sickchill/views/authentication.py", line 35, in <module>
    from .index import BaseHandler
  File "/Applications/SickChill/sickchill/views/index.py", line 34, in <module>
    from jwt.algorithms import RSAAlgorithm as jwt_algorithms_RSAAlgorithm
ImportError: cannot import name RSAAlgorithm
XXX-MacBook-Pro:~ XXX$

**Comment by miigotu** [comment]
@bradywang you dont have cryptography installed
pip install cryptography

**Comment by miigotu** [comment]
Im going to add a check in to make it still start if you dont have it.

**Comment by bradywang** [comment]
I rebooted my computer today and sickchill will not start i tried to reinstall it from the instructions at https://www.htpcguides.com/install-sickrage-mac-osx-usenet-torrent-tv/  and "pip install cryptography" is not listed in thoes instructions

**Comment by grendelrt** [comment]
I am getting the same error after updating on FreeNAS, has this cryptography always been a requirement, why is it just erroring now?

  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/SickBeard.py", line 70, in <module>
    from sickchill.views.server_settings import SRWebServer
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickchill/views/__init__.py", line 23, in <module>
    from .authentication import LoginHandler, LogoutHandler
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickchill/views/authentication.py", line 35, in <module>
    from .index import BaseHandler
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickchill/views/index.py", line 34, in <module>
    from jwt.algorithms import RSAAlgorithm as jwt_algorithms_RSAAlgorithm
ImportError: cannot import name RSAAlgorithm
/usr/local/etc/rc.d/sickrage: WARNING: failed to start sickrage

**Comment by bradywang** [comment]
pip install cryptography

**Comment by bradywang** [comment]
pip install cryptography works fine now to wait for the auto refresh :( and then disable debug

**Comment by miigotu** [comment]
git pull and start it again. 3c4a005b20b7a7ef7be0e1ea3bb17e39f5461edb
