### ISSUE TITLE
latest update fails

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6083]
2020-03-10 20:21:16 WEBSERVER-HOME :: [c31c4f8] Error while trying to update: error 32 : The process cannot access the file because it is being used by another process

 SickChill Info:
Branch: master
Commit: c31c4f89d3cd0ca841c604d034cb371251684572
Database Version: 44.1
  Python Version:
2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]
  SSL Version:
OpenSSL 1.0.2t 10 Sep 2019
  OS:
Windows-7-6.1.7601-SP1
  Locale:
en_US.cp1252

clicked update from the banner....
There is a newer version available (you're 4 commit behind) — Update Now

```
AA WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:\\SickChil\\lib\\certifi\\cacert.pem'
AA result = function(*args, **kwargs)
AA File "C:\SickChil\sickchill\helper\encoding.py", line 44, in ek
AA ek(os.remove, new_path)
AA File "C:\SickChil\sickbeard\versionChecker.py", line 843, in update
AA Traceback (most recent call last):
2020-03-10 20:21:16 ERROR    WEBSERVER-HOME :: [c31c4f8] Error while trying to update: error 32 : The process cannot access the file because it is being used by another process
2020-03-10 20:21:11 INFO     WEBSERVER-HOME :: Moving files from C:\SickChil\sr-update\SickChill-SickChill-cec77d3 to C:\SickChil
2020-03-10 20:21:11 INFO     WEBSERVER-HOME :: Deleting file C:\SickChil\sr-update\sr-update.tar
2020-03-10 20:20:51 INFO     WEBSERVER-HOME :: Extracting file C:\SickChil\sr-update\sr-update.tar
2020-03-10 20:20:45 INFO     WEBSERVER-HOME :: Downloading update from http://github.com/SickChill/SickChill/tarball/master
2020-03-10 20:20:45 INFO     WEBSERVER-HOME :: Creating update folder C:\SickChil\sr-update before extracting
2020-03-10 20:20:42 INFO     WEBSERVER-HOME :: Clearing out update folder C:\SickChil\sr-update before extracting
2020-03-10 20:20:41 INFO     WEBSERVER-HOME :: Config backup successful, updating...
```

**Comment by miigotu** [comment]
`The process cannot access the file because it is being used by another process`
Restart your machine and try agin.
