### ISSUE TITLE
API Key Authentication Error

### ISSUE THREAD

**Issue by Oxeus** [SickChill/SickChill#6084]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Windows 10
Browser: Chrome
What you did: Tried to add show/refresh another show.
What happened: Error saying that authentication of the API key has a problem
What you expected: When adding show or updating. the show will be grabbed from tvdb.
Logs:
```
2020-03-10 18:36:56 SHOWQUEUE-FORCE-UPDATE :: [cec77d3] Unable to get info from theTVDB, the show info will not be refreshed: Unknown error while authenticating. Check your api key or your user/userkey

2020-03-10 18:38:04 INFO SHOWQUEUE-REFRESH :: Done cache check
2020-03-10 18:37:01 INFO SHOWQUEUE-REFRESH :: 176941: Updating NFOs for show with new indexer info
2020-03-10 18:36:59 INFO SHOWQUEUE-REFRESH :: Performing refresh on Sherlock
AA AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
AA raise AuthenticationError(error)
AA File "C:\Program Files\SickChill\SickChill\lib\tvdbsimple\base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "C:\Program Files\SickChill\SickChill\lib\tvdbsimple\base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "C:\Program Files\SickChill\SickChill\lib\tvdbsimple\base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "C:\Program Files\SickChill\SickChill\lib\tvdbsimple\base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "C:\Program Files\SickChill\SickChill\lib\tvdbsimple\base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "C:\Program Files\SickChill\SickChill\lib\tvdbsimple\series.py", line 244, in page
AA self.page(1)
AA File "C:\Program Files\SickChill\SickChill\lib\tvdbsimple\series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "C:\Program Files\SickChill\SickChill\lib\tvdbsimple\series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "C:\Program Files\SickChill\SickChill\sickchill\show\indexers\tvdb.py", line 110, in episode
AA result = target(*args, **kwargs)
AA File "C:\Program Files\SickChill\SickChill\sickchill\show\indexers\wrappers.py", line 44, in wrapper
AA myEp = self.idxr.episode(self.show, season or self.season, episode or self.episode)
AA File "C:\Program Files\SickChill\SickChill\sickbeard\tv.py", line 1565, in loadFromIndexer
AA show_episode.loadFromIndexer(*season_episode)
AA File "C:\Program Files\SickChill\SickChill\sickbeard\tv.py", line 542, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "C:\Program Files\SickChill\SickChill\sickbeard\show_queue.py", line 681, in run
AA Traceback (most recent call last):
2020-03-10 18:36:56 ERROR SHOWQUEUE-FORCE-UPDATE :: [cec77d3] Unable to get info from theTVDB, the show info will not be refreshed: Unknown error while authenticating. Check your api key or your user/userkey
```

**Comment by augur42** [comment]
[https://forums.thetvdb.com/viewtopic.php?p=172414#p172414](https://forums.thetvdb.com/viewtopic.php?p=172414#p172414)

The TVDB API may have fallen over.

**Comment by Oxeus** [comment]
Yeah, I got it to stop giving me the API Error after a full restart of the program. I now have the list index error.
'''
2020-03-10 19:11:48 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-10 19:11:48 INFO SEARCHQUEUE-DAILY-SEARCH :: No NZB/Torrent providers found or enabled in the sickchill config for daily searches. Please check your settings.
2020-03-10 19:11:21 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-10 19:11:16 INFO FINDSUBTITLES :: No subtitles to download
2020-03-10 19:11:16 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-10 19:11:16 INFO FINDSUBTITLES :: Checking for missed subtitles
2020-03-10 19:11:16 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-10 19:07:52 INFO SHOWQUEUE-REFRESH :: 176941: Updating NFOs for show with new indexer info
2020-03-10 19:07:51 INFO SHOWQUEUE-REFRESH :: Performing refresh on Sherlock
AA TypeError: list indices must be integers, not str
AA self._PAGES_LIST[page] = response['data']
AA File "C:\Program Files\SickChill\SickChill\lib\tvdbsimple\series.py", line 248, in page
AA self.page(1)
AA File "C:\Program Files\SickChill\SickChill\lib\tvdbsimple\series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "C:\Program Files\SickChill\SickChill\lib\tvdbsimple\series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "C:\Program Files\SickChill\SickChill\sickchill\show\indexers\tvdb.py", line 110, in episode
AA result = target(*args, **kwargs)
AA File "C:\Program Files\SickChill\SickChill\sickchill\show\indexers\wrappers.py", line 44, in wrapper
AA myEp = self.idxr.episode(self.show, season or self.season, episode or self.episode)
AA File "C:\Program Files\SickChill\SickChill\sickbeard\tv.py", line 1565, in loadFromIndexer
AA show_episode.loadFromIndexer(*season_episode)
AA File "C:\Program Files\SickChill\SickChill\sickbeard\tv.py", line 542, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "C:\Program Files\SickChill\SickChill\sickbeard\show_queue.py", line 681, in run
AA Traceback (most recent call last):
2020-03-10 19:07:50 ERROR SHOWQUEUE-FORCE-UPDATE :: [cec77d3] Unable to get info from theTVDB, the show info will not be refreshed: list indices must be integers, not str
'''

**Comment by miigotu** [comment]
Update and try again, new api key for thetvdb
