### ISSUE TITLE
error list indices must be integers, not str

### ISSUE THREAD

**Issue by Ventje23** [SickChill/SickChill#6085]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / cec77d3551a9593a1da98b887104458c13189e92
OS: Linux-4.4.59+-x86_64-with-glibc2.2.5
Browser: Chome
What you did: nothing
What happened: daily show updater generated errors
What you expected: no errors, just the daily update
Logs:
```
2020-03-11 09:39:58 INFO CHECKVERSION :: Checking for updates using GIT
2020-03-11 09:10:10 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-11 09:10:10 INFO SEARCHQUEUE-DAILY-SEARCH :: No episodes needed.
2020-03-11 09:10:09 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-11 09:10:06 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-11 09:10:06 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-11 08:30:07 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-11 08:30:07 INFO SEARCHQUEUE-DAILY-SEARCH :: No episodes needed.
2020-03-11 08:30:07 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-11 08:30:05 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-11 08:30:05 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-11 07:50:05 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-11 07:50:05 INFO SEARCHQUEUE-DAILY-SEARCH :: No episodes needed.
2020-03-11 07:50:05 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-11 07:50:05 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-11 07:50:05 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-11 07:10:08 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-11 07:10:08 INFO SEARCHQUEUE-DAILY-SEARCH :: No episodes needed.
2020-03-11 07:10:08 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-11 07:10:04 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-11 07:10:04 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-11 06:30:06 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-11 06:30:06 INFO SEARCHQUEUE-DAILY-SEARCH :: No episodes needed.
2020-03-11 06:30:06 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-11 06:30:04 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-11 06:30:04 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-11 05:50:19 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-11 05:50:09 INFO SEARCHQUEUE-DAILY-SEARCH :: No episodes needed.
2020-03-11 05:50:09 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-11 05:50:04 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-11 05:50:04 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-11 05:10:07 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-11 05:10:07 INFO SEARCHQUEUE-DAILY-SEARCH :: No episodes needed.
2020-03-11 05:10:07 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-11 05:10:03 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-11 05:10:03 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-11 04:52:39 INFO SHOWQUEUE-REFRESH :: Done cache check
2020-03-11 04:52:36 INFO SHOWQUEUE-REFRESH :: 365302: Updating NFOs for show with new indexer info
2020-03-11 04:52:36 INFO SHOWQUEUE-REFRESH :: Performing refresh on Hoogvliegers
2020-03-11 04:52:33 INFO SHOWQUEUE-REFRESH :: Done cache check
2020-03-11 04:52:31 INFO SHOWQUEUE-REFRESH :: 374548: Updating NFOs for show with new indexer info
2020-03-11 04:52:31 INFO SHOWQUEUE-REFRESH :: Performing refresh on Almost Paradise
2020-03-11 04:52:27 INFO SHOWQUEUE-REFRESH :: Done cache check
2020-03-11 04:50:56 INFO SHOWQUEUE-REFRESH :: 378014: Updating NFOs for show with new indexer info
2020-03-11 04:50:56 INFO SHOWQUEUE-REFRESH :: Performing refresh on The English Game
2020-03-11 04:49:51 INFO SHOWQUEUE-REFRESH :: 377294: Updating NFOs for show with new indexer info
2020-03-11 04:49:51 INFO SHOWQUEUE-REFRESH :: Performing refresh on Feel Good
2020-03-11 04:49:16 INFO SHOWQUEUE-REFRESH :: 373452: Updating NFOs for show with new indexer info
2020-03-11 04:49:16 INFO SHOWQUEUE-REFRESH :: Performing refresh on The Letter for the King
2020-03-11 04:49:11 INFO SHOWQUEUE-REFRESH :: 364047: Updating NFOs for show with new indexer info
2020-03-11 04:49:11 INFO SHOWQUEUE-REFRESH :: Performing refresh on Motherland: Fort Salem
2020-03-11 04:49:07 INFO SHOWQUEUE-REFRESH :: Done cache check
2020-03-11 04:49:06 INFO SHOWQUEUE-REFRESH :: 363194: Updating NFOs for show with new indexer info
2020-03-11 04:49:06 INFO SHOWQUEUE-REFRESH :: Performing refresh on Little Fires Everywhere
2020-03-11 04:49:01 INFO SHOWQUEUE-REFRESH :: 367559: Updating NFOs for show with new indexer info
2020-03-11 04:49:01 INFO SHOWQUEUE-REFRESH :: Performing refresh on The Plot Against America
2020-03-11 04:48:56 INFO SHOWQUEUE-REFRESH :: 368120: Updating NFOs for show with new indexer info
2020-03-11 04:48:56 INFO SHOWQUEUE-REFRESH :: Performing refresh on Amazing Stories (2020)
2020-03-11 04:48:51 INFO SHOWQUEUE-REFRESH :: 364149: Updating NFOs for show with new indexer info
2020-03-11 04:48:51 INFO SHOWQUEUE-REFRESH :: Performing refresh on Devs
2020-03-11 04:48:46 INFO SHOWQUEUE-REFRESH :: 371820: Updating NFOs for show with new indexer info
2020-03-11 04:48:46 INFO SHOWQUEUE-REFRESH :: Performing refresh on Dispatches from Elsewhere
2020-03-11 04:48:41 INFO SHOWQUEUE-REFRESH :: 316316: Updating NFOs for show with new indexer info
2020-03-11 04:48:41 INFO SHOWQUEUE-REFRESH :: Performing refresh on Noughts + Crosses
2020-03-11 04:48:36 INFO SHOWQUEUE-REFRESH :: 354905: Updating NFOs for show with new indexer info
2020-03-11 04:48:36 INFO SHOWQUEUE-REFRESH :: Performing refresh on DAVE
2020-03-11 04:48:31 INFO SHOWQUEUE-REFRESH :: 363777: Updating NFOs for show with new indexer info
2020-03-11 04:48:31 INFO SHOWQUEUE-REFRESH :: Performing refresh on Breeders
2020-03-11 04:48:11 INFO SHOWQUEUE-REFRESH :: Performing refresh on Council of Dads
2020-03-11 04:48:06 INFO SHOWQUEUE-REFRESH :: Performing refresh on Vagrant Queen
AA TypeError: list indices must be integers, not str
AA self._PAGES_LIST[page] = response['data']
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 248, in page
AA self.page(1)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, language=show.lang).all()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 94, in episodes
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA for series_episode in self.idxr.episodes(self):
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 526, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 681, in run
AA Traceback (most recent call last):
2020-03-11 04:46:43 ERROR SHOWQUEUE-FORCE-UPDATE :: [cec77d3] Unable to get info from theTVDB, the show info will not be refreshed: list indices must be integers, not str
AA TypeError: list indices must be integers, not str
AA self._PAGES_LIST[page] = response['data']
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 248, in page
AA self.page(1)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 110, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA myEp = self.idxr.episode(self.show, season or self.season, episode or self.episode)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 1565, in loadFromIndexer
AA show_episode.loadFromIndexer(*season_episode)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 542, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 681, in run
AA Traceback (most recent call last):
2020-03-11 04:43:19 ERROR SHOWQUEUE-FORCE-UPDATE :: [cec77d3] Unable to get info from theTVDB, the show info will not be refreshed: list indices must be integers, not str
AA TypeError: list indices must be integers, not str
AA self._PAGES_LIST[page] = response['data']
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 248, in page
AA self.page(1)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 110, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA myEp = self.idxr.episode(self.show, season or self.season, episode or self.episode)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 1565, in loadFromIndexer
AA show_episode.loadFromIndexer(*season_episode)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 542, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 681, in run
AA Traceback (most recent call last):
2020-03-11 04:40:57 ERROR SHOWQUEUE-FORCE-UPDATE :: [cec77d3] Unable to get info from theTVDB, the show info will not be refreshed: list indices must be integers, not str
2020-03-11 04:40:05 INFO SHOWQUEUE-REFRESH :: Performing refresh on High Fidelity
2020-03-11 04:40:00 INFO SHOWUPDATER :: Last update: 2020-03-10 04:57:42
2020-03-11 04:40:00 INFO SHOWUPDATER :: ShowUpdater for tvdb Api V3 starting
2020-03-11 04:30:05 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-11 04:30:05 INFO SEARCHQUEUE-DAILY-SEARCH :: No episodes needed.
2020-03-11 04:30:04 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-11 04:30:03 INFO DAILYSEARCHER :: No new released episodes found ...

```

**Comment by Ventje23** [comment]
sory, looks like issue was already submitted.

**Comment by Ventje23** [comment]
sorry, looks like issue was already submitted.
