### ISSUE TITLE
Unable to add show from any source

### ISSUE THREAD

**Issue by hallinan** [SickChill/SickChill#6087]
### Before submitting your issue:

SickChill Info:

Branch: master
Commit: 55c97c3890aab9b1bd1408b5541296e9528d22e6
Database Version: 44.1
Python Version: 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
SSL Version:OpenSSL 1.1.0l 10 Sep 2019
OS:Linux-4.19.66-v7+-armv7l-with-debian-9.11
Locale:en_GB.UTF-8

  User:sickchill
  Program Folder:/opt/sickchill
  Config File:/opt/sickchill/config.ini
  Database File:/opt/sickchill/sickbeard.db
  Cache Folder:/opt/sickchill/gui/slick/cache
  Log Folder:/opt/sickchill/Logs
  Arguments:['-q', '--daemon', '--nolaunch', '--datadir=/opt/sickchill']

Branch/Commit: Master
OS: Raspbian
Browser: Chrome
What you did: Tried to add show from Existing source/Track and IMDB
What happened: Could not connect to any of these providers 
What you expected: Show to be imported or a list of shows from shown 
Logs:
```

AA TypeError: addExistingShows() takes exactly 3 arguments (1 given)
--
  | AA result = function(**kwargs)
  | AA File "/opt/sickchill/sickchill/views/index.py", line 215, in async_call
  | AA result = self.fn(*self.args, **self.kwargs)
  | AA File "/opt/sickchill/lib/concurrent/futures/thread.py", line 63, in run
  | AA return self.__get_result()
  | AA File "/opt/sickchill/lib/concurrent/futures/_base.py", line 455, in result
  | AA value = future.result()
  | AA File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
  | AA results = yield self.async_call(method)
  | AA File "/opt/sickchill/sickchill/views/index.py", line 193, in get
  | AA yielded = self.gen.throw(*exc_info)
  | AA File "/opt/sickchill/lib/tornado/gen.py", line 1063, in run
  | AA raise_exc_info(self._exc_info)
  | AA File "/opt/sickchill/lib/tornado/concurrent.py", line 238, in result
  | AA value = future.result()
  | AA File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
  | AA result = yield result
  | AA File "/opt/sickchill/lib/tornado/web.py", line 1511, in _execute
  | AA Traceback (most recent call last):
  | AA HTTPServerRequest(protocol=u'http', host='192.168.0.206:8081', method='GET', uri='/addShows/addExistingShows', version='HTTP/1.1', remote_ip='192.168.0.192', headers={'Accept-Language': 'en,en-GB;q=0.9,und;q=0.8,de;q=0.7', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.0.206:8081', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive'})
  | AA 2020-03-11 21:04:02 ERROR    Uncaught exception GET /addShows/addExistingShows (192.168.0.192)
  | AA TypeError: addExistingShows() takes exactly 3 arguments (1 given)
  | AA result = function(**kwargs)
  | AA File "/opt/sickchill/sickchill/views/index.py", line 215, in async_call
  | AA Traceback (most recent call last):
  | AA TypeError: addExistingShows() takes exactly 3 arguments (1 given)
  | AA result = function(**kwargs)
  | AA File "/opt/sickchill/sickchill/views/index.py", line 215, in async_call
  | 2020-03-11 21:04:02 ERROR    WEBSERVER-ADDSHOWS :: [55c97c3] Failed doing webui callback: Traceback (most recent call last):
  | 2020-03-11 21:03:32 WARNING  MAIN :: Updating network timezones failed, this can happen from time to time. URL: http://sickchill.github.io/sb_network_timezones/network_timezones.txt


```

**Comment by miigotu** [comment]
Doesnt look like it has network connectivity.

**Comment by miigotu** [comment]
Try updating and trying again, Just changed the api key for thetvdb

**Comment by shanehallinan** [comment]
I had tried updating but that didn't work maybe miigotu hadn't changed the api key yet.
I did delete in and reinstall and that worked
