### ISSUE TITLE
API key error & JSON object could not be decoded

### ISSUE THREAD

**Issue by Ventje23** [SickChill/SickChill#6094]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / b2d7ac109604ed7585ba0b56c53fcf93e4f2fadd
OS: Linux-4.4.59+-x86_64-with-glibc2.2.5
Browser: Chrome
What you did: Nothing
What happened: Showupdates
What you expected:No errors and just showupdates
Logs:
```
20-03-14 12:08:55 INFO WEBSERVER-ERRORLOGS :: Commented on existing issue #5870 successfully!
2020-03-14 12:06:13 INFO WEBSERVER-ERRORLOGS :: Checking for updates using GIT
2020-03-14 11:36:14 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-14 11:36:06 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-14 11:36:05 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-14 11:36:05 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-14 10:56:30 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-14 10:56:09 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-14 10:56:05 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-14 10:56:05 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-14 10:16:28 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-14 10:16:07 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-14 10:16:05 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-14 10:16:05 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-14 09:36:26 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-14 09:36:05 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-14 09:36:05 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-14 09:36:05 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-14 09:26:27 INFO SEARCHQUEUE-BACKLOG- :: No needed episodes found during backlog search for: [Twenties]
2020-03-14 09:26:25 INFO SEARCHQUEUE-BACKLOG-374877 :: [Rarbg] :: Performing episode search for Twenties
2020-03-14 09:26:25 INFO SEARCHQUEUE-BACKLOG- :: Beginning backlog search for: [Twenties]
2020-03-14 09:26:22 INFO SEARCHQUEUE-BACKLOG- :: No needed episodes found during backlog search for: [Stateless]
2020-03-14 09:26:20 INFO SEARCHQUEUE-BACKLOG-368855 :: [Rarbg] :: Performing episode search for Stateless
2020-03-14 09:26:20 INFO SEARCHQUEUE-BACKLOG- :: Beginning backlog search for: [Stateless]
2020-03-14 09:26:16 INFO SEARCHQUEUE-BACKLOG- :: No needed episodes found during backlog search for: [Amazing Stories (2020)]
2020-03-14 09:26:14 INFO SEARCHQUEUE-BACKLOG-368120 :: [Rarbg] :: Performing episode search for Amazing Stories (2020)
2020-03-14 09:25:59 INFO SEARCHQUEUE-BACKLOG- :: Beginning backlog search for: [Amazing Stories (2020)]
2020-03-14 09:25:58 INFO CHECKVERSION :: Checking for updates using GIT
2020-03-14 08:56:28 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-14 08:56:08 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-14 08:56:04 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-14 08:56:04 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-14 08:16:37 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-14 08:16:05 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-14 08:16:04 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-14 08:16:04 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-14 07:36:39 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-14 07:36:08 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-14 07:36:03 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-14 07:36:03 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-14 06:56:37 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-14 06:56:05 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-14 06:56:03 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-14 06:56:03 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-14 06:16:34 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-14 06:16:03 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-14 06:16:03 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-14 06:16:03 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-14 05:36:41 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-14 05:36:06 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-14 05:36:03 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-14 05:36:03 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-14 05:15:00 INFO SHOWQUEUE-REFRESH :: 374877: Updating NFOs for show with new indexer info
2020-03-14 05:15:00 INFO SHOWQUEUE-REFRESH :: Performing refresh on Twenties
2020-03-14 05:14:55 INFO SHOWQUEUE-REFRESH :: 355228: Updating NFOs for show with new indexer info
2020-03-14 05:14:55 INFO SHOWQUEUE-REFRESH :: Performing refresh on Kingdom (2019)
2020-03-14 05:13:50 INFO SHOWQUEUE-REFRESH :: 374548: Updating NFOs for show with new indexer info
2020-03-14 05:13:50 INFO SHOWQUEUE-REFRESH :: Performing refresh on Almost Paradise
2020-03-14 05:13:45 INFO SHOWQUEUE-REFRESH :: 363853: Updating NFOs for show with new indexer info
2020-03-14 05:13:45 INFO SHOWQUEUE-REFRESH :: Performing refresh on Council of Dads
2020-03-14 05:13:40 INFO SHOWQUEUE-REFRESH :: 364047: Updating NFOs for show with new indexer info
2020-03-14 05:13:40 INFO SHOWQUEUE-REFRESH :: Performing refresh on Motherland: Fort Salem
2020-03-14 05:13:35 INFO SHOWQUEUE-REFRESH :: 368120: Updating NFOs for show with new indexer info
2020-03-14 05:13:35 INFO SHOWQUEUE-REFRESH :: Performing refresh on Amazing Stories (2020)
2020-03-14 05:13:30 INFO SHOWQUEUE-REFRESH :: 316316: Updating NFOs for show with new indexer info
2020-03-14 05:13:30 INFO SHOWQUEUE-REFRESH :: Performing refresh on Noughts + Crosses
2020-03-14 05:13:25 INFO SHOWQUEUE-REFRESH :: 354905: Updating NFOs for show with new indexer info
2020-03-14 05:13:25 INFO SHOWQUEUE-REFRESH :: Performing refresh on DAVE
2020-03-14 05:13:20 INFO SHOWQUEUE-REFRESH :: 363777: Updating NFOs for show with new indexer info
2020-03-14 05:13:20 INFO SHOWQUEUE-REFRESH :: Performing refresh on Breeders
2020-03-14 05:13:15 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: No JSON object could be decoded
AA ValueError: No JSON object could be decoded
AA raise ValueError("No JSON object could be decoded")
AA File "/var/packages/python/target/lib/python2.7/json/decoder.py", line 382, in raw_decode
AA obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AA File "/var/packages/python/target/lib/python2.7/json/decoder.py", line 364, in decode
AA return _default_decoder.decode(s)
AA File "/var/packages/python/target/lib/python2.7/json/__init__.py", line 339, in loads
AA return complexjson.loads(self.text, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/requests/models.py", line 898, in json
AA KEYS.API_TOKEN = response.json()['token']
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 115, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 244, in page
AA self.page(1)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 110, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA myEp = self.idxr.episode(self.show, season or self.season, episode or self.episode)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 1565, in loadFromIndexer
AA show_episode.loadFromIndexer(*season_episode)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 542, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 681, in run
AA Traceback (most recent call last):
2020-03-14 05:12:15 ERROR SHOWQUEUE-FORCE-UPDATE :: [b2d7ac1] Unable to get info from theTVDB, the show info will not be refreshed: No JSON object could be decoded
2020-03-14 05:07:00 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: No JSON object could be decoded
AA ValueError: No JSON object could be decoded
AA raise ValueError("No JSON object could be decoded")
AA File "/var/packages/python/target/lib/python2.7/json/decoder.py", line 382, in raw_decode
AA obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AA File "/var/packages/python/target/lib/python2.7/json/decoder.py", line 364, in decode
AA return _default_decoder.decode(s)
AA File "/var/packages/python/target/lib/python2.7/json/__init__.py", line 339, in loads
AA return complexjson.loads(self.text, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/requests/models.py", line 898, in json
AA jsn = response.json()
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 137, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 244, in page
AA self.page(1)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 110, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA myEp = self.idxr.episode(self.show, season or self.season, episode or self.episode)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 1565, in loadFromIndexer
AA show_episode.loadFromIndexer(*season_episode)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 542, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 681, in run
AA Traceback (most recent call last):
2020-03-14 05:04:58 ERROR SHOWQUEUE-FORCE-UPDATE :: [b2d7ac1] Unable to get info from theTVDB, the show info will not be refreshed: No JSON object could be decoded
2020-03-14 05:02:49 INFO SHOWQUEUE-REFRESH :: Performing refresh on Hoogvliegers
AA AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
AA raise AuthenticationError(error)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 244, in page
AA self.page(1)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, language=show.lang).all()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 94, in episodes
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA for series_episode in self.idxr.episodes(self):
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 526, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 681, in run
AA Traceback (most recent call last):
2020-03-14 05:02:49 ERROR SHOWQUEUE-FORCE-UPDATE :: [b2d7ac1] Unable to get info from theTVDB, the show info will not be refreshed: Unknown error while authenticating. Check your api key or your user/userkey
AA ValueError: No JSON object could be decoded
AA raise ValueError("No JSON object could be decoded")
AA File "/var/packages/python/target/lib/python2.7/json/decoder.py", line 382, in raw_decode
AA obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AA File "/var/packages/python/target/lib/python2.7/json/decoder.py", line 364, in decode
AA return _default_decoder.decode(s)
AA File "/var/packages/python/target/lib/python2.7/json/__init__.py", line 339, in loads
AA return complexjson.loads(self.text, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/requests/models.py", line 898, in json
AA jsn = response.json()
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 137, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 244, in page
AA self.page(1)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, language=show.lang).all()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 94, in episodes
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA for series_episode in self.idxr.episodes(self):
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 526, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 681, in run
AA Traceback (most recent call last):
2020-03-14 04:58:42 ERROR SHOWQUEUE-FORCE-UPDATE :: [b2d7ac1] Unable to get info from theTVDB, the show info will not be refreshed: No JSON object could be decoded
2020-03-14 04:58:35 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: No JSON object could be decoded
2020-03-14 04:58:30 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: No JSON object could be decoded
2020-03-14 04:57:25 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: No JSON object could be decoded
2020-03-14 04:56:23 INFO SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2020-03-14 04:56:19 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: Unknown error while authenticating. Check your api key or your user/userkey
2020-03-14 04:56:03 INFO SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2020-03-14 04:56:02 INFO DAILYSEARCHER :: No new released episodes found ...
2020-03-14 04:56:02 INFO DAILYSEARCHER :: Searching for new released episodes ...
2020-03-14 04:51:09 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: No JSON object could be decoded
2020-03-14 04:50:04 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: Unknown error while authenticating. Check your api key or your user/userkey
AA AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
AA raise AuthenticationError(error)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 244, in page
AA self.page(1)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 110, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA myEp = self.idxr.episode(self.show, season or self.season, episode or self.episode)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 1565, in loadFromIndexer
AA show_episode.loadFromIndexer(*season_episode)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 542, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 681, in run
AA Traceback (most recent call last):
2020-03-14 04:46:02 ERROR SHOWQUEUE-FORCE-UPDATE :: [b2d7ac1] Unable to get info from theTVDB, the show info will not be refreshed: Unknown error while authenticating. Check your api key or your user/userkey
2020-03-14 04:41:54 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: Unknown error while authenticating. Check your api key or your user/userkey
2020-03-14 04:37:49 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: Unknown error while authenticating. Check your api key or your user/userkey
AA AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
AA raise AuthenticationError(error)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 244, in page
AA self.page(1)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 110, in episode
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA myEp = self.idxr.episode(self.show, season or self.season, episode or self.episode)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 1565, in loadFromIndexer
AA show_episode.loadFromIndexer(*season_episode)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 542, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 681, in run
AA Traceback (most recent call last):
2020-03-14 04:33:43 ERROR SHOWQUEUE-FORCE-UPDATE :: [b2d7ac1] Unable to get info from theTVDB, the show info will not be refreshed: Unknown error while authenticating. Check your api key or your user/userkey
AA AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
AA raise AuthenticationError(error)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 244, in page
AA self.page(1)
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, language=show.lang).all()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/tvdb.py", line 94, in episodes
AA result = target(*args, **kwargs)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA for series_episode in self.idxr.episodes(self):
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 526, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 681, in run
AA Traceback (most recent call last):
2020-03-14 04:27:16 ERROR SHOWQUEUE-FORCE-UPDATE :: [b2d7ac1] Unable to get info from theTVDB, the show info will not be refreshed: Unknown error while authenticating. Check your api key or your user/userkey
2020-03-14 04:26:07 INFO SHOWQUEUE-REFRESH :: Performing refresh on High Fidelity
2020-03-14 04:26:02 INFO SHOWUPDATER :: Last update: 2020-03-13 04:13:57
2020-03-14 04:26:02 INFO SHOWUPDATER :: ShowUpdater for tvdb Api V3 starting
```

**Comment by wallacebrf** [comment]
I am getting this as well
2020-03-14 19:41:05 SHOWQUEUE-FORCE-UPDATE :: [b2d7ac1] Unable to get info from theTVDB, the show info will not be refreshed: No JSON object could be decoded

**Comment by dracupg** [comment]
Same issue here

**Comment by miigotu** [comment]
You can open up 500 issues for the same issue but it won't solve the problem.

**Comment by Ventje23** [comment]
as far as i know i haven't added 500 issues for the same issue.

**Comment by miigotu** [comment]
But there ARE open issues for it, caused by the same problem, and the same people commenting on all of them. Forcing me to spend more time on the issue tracker is not going to get it fixed any faster. If anything it slows me down because I only have so much time to go around.

**Comment by Ventje23** [comment]
I understand. Sorry about that. Would like to take this opportunity to thank you for all the work you do on SC.
