### ISSUE TITLE
Unknown error while authenticating when adding show

### ISSUE THREAD

**Issue by cgatesman** [SickChill/SickChill#6095]
Running on latest master (v2020.03.13-6 - 715aa19), I am unable to add a show.  I also tried develop branch (b2d7ac1), and had the same problem.

```
AA AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
AA raise AuthenticationError(error)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/series.py", line 244, in page
AA self.page(1)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, language=show.lang).all()
AA File "/Users/********/Applications/SickChill/sickchill/show/indexers/tvdb.py", line 94, in episodes
AA result = target(*args, **kwargs)
AA File "/Users/********/Applications/SickChill/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA for series_episode in self.idxr.episodes(self):
AA File "/Users/********/Applications/SickChill/sickbeard/tv.py", line 526, in loadEpisodesFromIndexer
AA self.show.loadEpisodesFromIndexer()
AA File "/Users/********/Applications/SickChill/sickbeard/show_queue.py", line 491, in run
AA AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey
AA raise AuthenticationError(error)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/series.py", line 244, in page
AA self.page(1)
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/Users/********/Applications/SickChill/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, language=show.lang).all()
AA File "/Users/********/Applications/SickChill/sickchill/show/indexers/tvdb.py", line 94, in episodes
AA result = target(*args, **kwargs)
AA File "/Users/********/Applications/SickChill/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA for series_episode in self.idxr.episodes(self):
AA File "/Users/********/Applications/SickChill/sickbeard/tv.py", line 526, in loadEpisodesFromIndexer
AA self.show.loadEpisodesFromIndexer()
AA File "/Users/********/Applications/SickChill/sickbeard/show_queue.py", line 491, in run
AA Traceback (most recent call last):
2020-03-14 09:41:17 ERROR    SHOWQUEUE-ADD :: [b2d7ac1] Error with theTVDB, not creating episode list: Unknown error while authenticating. Check your api key or your user/userkey
2020-03-14 09:37:13 INFO     SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2020-03-14 09:37:13 INFO     SHOWQUEUE-ADD :: 363194: Unable to find the show in the database
2020-03-14 09:37:13 INFO     SHOWQUEUE-ADD :: Starting to add show by ShowDir: /Users/********/Usenet/TV/Little Fires Everywhere
```

**Comment by l3rady** [comment]
I am getting this issue too but I did see the latest news feed article that says the following:

> TVDB api should be working on our end as long as their side is working. It does go down from time to time while they are working on it. If you see an APIkey error, its on theTVDB side and we cannot fix it so just be patient.

**Comment by wallacebrf** [comment]
thanks for the update as i too am getting this

**Comment by Yoshi900** [comment]
I think I am getting the same 

2020-03-15 09:58:17 WEBSERVER-ADDSHOWS :: [b2d7ac1] Failed doing webui callback: Traceback (most recent call last):
File "C:\SickChill\SickChill\sickchill\views\index.py", line 215, in async_call
result = function(**kwargs)
File "C:\SickChill\SickChill\sickchill\views\manage\add_shows.py", line 526, in addNewShow
s = sickchill.indexer.series_by_id(indexerid=indexer_id, indexer=indexer, language=indexerLang)
File "C:\SickChill\SickChill\sickchill\show\indexers\handler.py", line 156, in series_by_id
series = self.indexers[indexer].series(id=indexerid, language=language)
File "C:\SickChill\SickChill\sickchill\show\indexers\wrappers.py", line 44, in wrapper
result = target(*args, **kwargs)
File "C:\SickChill\SickChill\sickchill\show\indexers\tvdb.py", line 59, in series
result.info(language=kwargs.get('language'))
File "C:\SickChill\SickChill\lib\tvdbsimple\series.py", line 64, in info
response = self._GET(path)
File "C:\SickChill\SickChill\lib\tvdbsimple\base.py", line 149, in _GET
return self._request('GET', path, params=params, cleanJson=cleanJson)
File "C:\SickChill\SickChill\lib\tvdbsimple\base.py", line 142, in _request
return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
File "C:\SickChill\SickChill\lib\tvdbsimple\base.py", line 126, in _request
self._set_token_header(forceNewToken)
File "C:\SickChill\SickChill\lib\tvdbsimple\base.py", line 91, in _set_token_header
self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
File "C:\SickChill\SickChill\lib\tvdbsimple\base.py", line 122, in get_token
raise AuthenticationError(error)
AuthenticationError: Unknown error while authenticating. Check your api key or your user/userkey

**Comment by marcb1387** [comment]
yeah tvdb is having all kinda issues, im also having trouble with plex for something and other with kodi too. https://forums.thetvdb.com/viewtopic.php?f=122&t=63148
