### ISSUE TITLE
Searching for a specific episode Cosmos causes: AttributeError: 'NoneType' object has no attribute 'next'

### ISSUE THREAD

**Issue by joshbaptiste** [SickChill/SickChill#6135]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:  b2d7ac109604ed7585ba0b56c53fcf93e4f2fadd

OS: Debian Linux
Browser: Chrome
What you did: Manual Search
What happened: Raised an exception 
What you expected:  I mean it's not a big issue as other episodes worked fine.. but just wanted to raise an issue as it seems this traceback is raised depends on a certain Jackett response
Logs:
```
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ SDTV ]
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Existing episode status is 'Wanted', getting found result for Cosmos: Possible Worlds S01E03 with quality SDTV
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Found result Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[ettv] at http://127.0.0.1:9117/dl/ettv/?jackett_apikey=**
********&path=Q2ZESjhHTkN4LUNmYW5OQmlHVVNJbEs5b3BVYmk1S1gzajM4ZjM0SHlFaVlfeS1PMGs4WVZMLTZyc2Mtd3BkYXFZX2VfX09OVWF6QTVGNUtWV3ctSVA3aWRNNXRhRVZpckY2VlYzUmpCbzZ2eWZRMFdQSS00Y2JoTU5VLTh0RHBGS1BI
QklQZVFKVVZxZ2g3dDhkYTNKVWxIbnhBX3VDdEYzcFk0c05wVkw2NXY1c2QxZzJYVDZxZjZpMVFaRjdXbHNfd2IzZmQ3cFRoUUNXZkFjUXpud0loUTkweFluYjBuMjBhR0NHeE52b0xKcnB6&file=Cosmos.Possible.Worlds.S01E03.HDTV.x264-
aAF%5Bettv%5D
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Single episode result.
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Using cached parse result for: Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[TGx]
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Any,Best = [ SDTV, SD DVD ] [ None ] Found = [ SDTV ]
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Existing episode status is 'Wanted', getting found result for Cosmos: Possible Worlds S01E03 with quality SDTV
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Found result Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[TGx] at http://127.0.0.1:9117/dl/ettv/?jackett_apikey=***
*******&path=Q2ZESjhHTkN4LUNmYW5OQmlHVVNJbEs5b3BXcHdIVThkcTBRWWNtTXlGWE9ELWxyOE1ScW5rb1ZyLVpyR0Jma0xtS2s5Z0JWdmxVcE5qdHMyenNfaFh2MDhydk1pSEI3bGlNeVRVUnVVa19NVnhBM3R0bG9wZzFHVE1uTXdoblBGdVRMN
WVHQl9vQXkzMk40dEU1YnBFdjdacXRzR21Cc3d3Zmd3RkNKVnRHZnNjTXhaelpIYjJhX2g4cjAwRWhONHN4RW1QbzBtVHB3Q3p0LTl1VURYM1pNZ1BGMW5YY0hjejBCbTBkOTd1M1NNc3NT&file=Cosmos.Possible.Worlds.S01E03.HDTV.x264-a
AF%5BTGx%5D
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Single episode result.
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: The highest quality of any match is SDTV
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Picking the best result out of [u'Cosmos.Possible.Worlds.S01E03.480p.x264-ZMNT', u'Cosmos.Possible.Worlds.S01E03.L
ost.City.of.Life.iNTERNAL.480p.x264-mSD[eztv].mkv', u'Cosmos.Possible.Worlds.S01E03.Lost.City.of.Life.iNTERNAL.WEBRip.x264-CAFFEiNE[eztv].mkv', u'Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[
eztv].mkv', u'Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[ettv]', u'Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[TGx]']
2020-03-20 23:58:55 INFO     SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Quality of Cosmos.Possible.Worlds.S01E03.480p.x264-ZMNT is SDTV
2020-03-20 23:58:55 INFO     SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Release: Cosmos.Possible.Worlds.S01E03.480p.x264-ZMNT contains 480p, ignoring it
2020-03-20 23:58:55 INFO     SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Quality of Cosmos.Possible.Worlds.S01E03.Lost.City.of.Life.iNTERNAL.480p.x264-mSD[eztv].mkv is SDTV
2020-03-20 23:58:55 INFO     SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Release: Cosmos.Possible.Worlds.S01E03.Lost.City.of.Life.iNTERNAL.480p.x264-mSD[eztv].mkv contains 480p, ignoring 
it
2020-03-20 23:58:55 INFO     SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Quality of Cosmos.Possible.Worlds.S01E03.Lost.City.of.Life.iNTERNAL.WEBRip.x264-CAFFEiNE[eztv].mkv is SDTV
2020-03-20 23:58:55 INFO     SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Quality of Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[eztv].mkv is SDTV
2020-03-20 23:58:55 INFO     SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Preferring Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[eztv].mkv (normal instead of internal)
2020-03-20 23:58:55 INFO     SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Quality of Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[ettv] is SDTV
2020-03-20 23:58:55 INFO     SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Quality of Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[TGx] is SDTV
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Picked Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[eztv].mkv as the best
2020-03-20 23:58:55 DEBUG    SEARCHQUEUE-MANUAL-378214 :: [jackett_ettv] :: Checking if we should keep searching after we've found Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[eztv].mkv
2020-03-20 23:58:55 INFO     SEARCHQUEUE-MANUAL- :: Downloading Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF[eztv].mkv from jackett_ettv
2020-03-20 23:58:56 INFO     SEARCHQUEUE-MANUAL- :: Request failed: 404 Client Error: Not Found for url: http://127.0.0.1:9117/dl/ettv/?jackett_apikey=**********&path=Q2ZESjhHTkN4LUNmYW5OQml
HVVNJbEs5b3BVenQ0N19nVm9XMmc2VEZZbGdNcW9GV0IxLWpuX1lucW9ILURxVzF4VERzZGtHRDkwYVNfUDRVRkVDbXkxTURqelNkYnQ0VUEzYTJmdXlGekdjRTY3Z3UyeUtvZGNOeW80VUhfdG5hLVVRcmpQVV9rb05pdHRxZTgzWWs4RFNuR2FLYmZpe
lRZTmdrTi1yM2dBNDFuclNzUXNvY1lFanU2a0FQY1p4NFZGUWt2Z2s3Qi14aTdHdG5lazlWSmJIZlpfakYxcE9oT2ZPZlZ2WDFGbVpwdHdl&file=Cosmos.Possible.Worlds.S01E03.HDTV.x264-aAF%5Beztv%5D.mkv (<type 'str'>)
2020-03-20 23:58:56 DEBUG    SEARCHQUEUE-MANUAL- :: Traceback (most recent call last):
  File "/home/pvr/pvr/SickRage/sickbeard/search_queue.py", line 186, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "/home/pvr/pvr/SickRage/sickbeard/search.py", line 111, in snatchEpisode
    if response.next and response.next.url and response.next.url.startswith('magnet'):
AttributeError: 'NoneType' object has no attribute 'next'

```

**Comment by miigotu** [comment]
`Request failed: 404 Client Error: Not Found for url: http://127.0.0.1:9117/dl/ettv/?ja`
this is an error with jackett's ettv provider, it cannot download the file. You will have to contact them.
