### ISSUE TITLE
Reporting errors to github issue does not work any more

### ISSUE THREAD

**Issue by mesa57** [SickChill/SickChill#6167]
Logs:
```
2020-04-02 20:37:39 ERROR    WEBSERVER-ERRORLOGS :: [50a2b16] Traceback (most recent call last):
  File "/app/sickrage/sickbeard/logger.py", line 342, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickchill.log': InputFileContent(paste_data)})
  File "/app/sickrage/lib/github/AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "/app/sickrage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/app/sickrage/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Not Found'}
Traceback (most recent call last):
  File "/app/sickrage/sickbeard/logger.py", line 342, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickchill.log': InputFileContent(paste_data)})
  File "/app/sickrage/lib/github/AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "/app/sickrage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/app/sickrage/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Not Found'}
```

**Comment by hooligeek** [comment]
I'm also experiencing this.


2020-04-03 07:52:10 WEBSERVER-ERRORLOGS :: [50a2b16] Failed doing webui callback: Traceback (most recent call last):
File "C:\SickChill\SickChill\sickchill\views\index.py", line 215, in async_call
result = function(**kwargs)
File "C:\SickChill\SickChill\sickchill\views\logs.py", line 94, in viewlog
t = PageTemplate(rh=self, filename="viewlogs.mako")
File "C:\SickChill\SickChill\sickchill\views\common.py", line 64, in __init__
self.template = lookup.get_template(filename)
File "C:\SickChill\SickChill\lib\mako\lookup.py", line 260, in get_template
return self._load(srcfile, uri)
File "C:\SickChill\SickChill\lib\mako\lookup.py", line 327, in _load
**self.template_args
File "C:\SickChill\SickChill\lib\mako\template.py", line 347, in __init__
module = self._compile_from_file(path, filename)
File "C:\SickChill\SickChill\lib\mako\template.py", line 417, in _compile_from_file
if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'

Also when I try to view the logs I met with a 404 error page.

Oops: 404 Not Found
You have reached this page by accident, please check the url.

So far all other functionality seems to be fine.

**Comment by miigotu** [comment]
Fix the roles allowed on the GitHub token you made for SC, it doesn't have permission to create gists.

**Comment by mesa57** [comment]
Thank you!

**Comment by mesa57** [comment]
Still not working
```
2020-04-04 17:45:52 WEBSERVER-ERRORLOGS :: [50a2b16] Traceback (most recent call last):
  File "/app/sickrage/sickbeard/logger.py", line 342, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickchill.log': InputFileContent(paste_data)})
  File "/app/sickrage/lib/github/AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "/app/sickrage/lib/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/app/sickrage/lib/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
UnknownObjectException: 404 {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Not Found'}
```
