### ISSUE TITLE
[APP SUBMITTED]: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by hooligeek** [SickChill/SickChill#6171]
### INFO
Python Version: **2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-2012ServerR2-6.3.9600**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@50a2b16835064938d2a99129fca8744edcfb18a2
Link to Log: https://gist.github.com/24d0958c7248b8db4a7534ab0cf0d328
### ERROR
```
WEBSERVER-ERRORLOGS :: [50a2b16] Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickbeard\logger.py", line 342, in submit_errors
    gist = sickbeard.gh.get_user().create_gist(False, {'sickchill.log': InputFileContent(paste_data)})
  File "C:\SickChill\SickChill\lib\github\AuthenticatedUser.py", line 479, in create_gist
    input=post_parameters
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 215, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 268, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "C:\SickChill\SickChill\lib\github\Requester.py", line 293, in __requestRaw
    requestHeaders
  File "C:\SickChill\Python\lib\httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "C:\SickChill\Python\lib\httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "C:\SickChill\Python\lib\httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "C:\SickChill\Python\lib\httplib.py", line 882, in _send_output
    self.send(msg)
  File "C:\SickChill\Python\lib\httplib.py", line 844, in send
    self.connect()
  File "C:\SickChill\Python\lib\httplib.py", line 1255, in connect
    HTTPConnection.connect(self)
  File "C:\SickChill\Python\lib\httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "C:\SickChill\Python\lib\socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\SickChill\SickChill\sickbeard\helpers.py", line 93, in getaddrinfo_wrapper
    return orig_getaddrinfo(host, port, family, socktype, proto, flags)
gaierror: [Errno 11001] getaddrinfo failed

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by hooligeek** [comment]
I restarted SC and it seems to be ok, now
