### ISSUE TITLE
SEARCHQUEUE-MANUAL Request failed: 404 Client Error AttributeError: 'NoneType' object has no attribute 'next'

### ISSUE THREAD

**Issue by flobafff** [SickChill/SickChill#6180]
Branch: master
Commit: 50a2b16835064938d2a99129fca8744edcfb18a2
Version: v2020.04.01-2
Database Version: 44.1
OS: Linux-4.19.66+-armv6l-with-debian-9.11

I use Jackett for the oxtorrent provider and since last week, I can no longer download torrents.

Logs:
2020-04-07 10:47:08 INFO     SEARCHQUEUE-MANUAL-247897 :: [Oxtorrent] :: Found result Homeland.S08E09.HDTV.VOSTFR at http://192.168.1.60:9117/dl/oxtorrent/?jackett_apikey=**********&path=Q2ZESjhGZHdKcWI2czM1THNvVm80SDd6U0RuR1NhOUh2QnRGbFJqNGNfdGhyU09HSnk1cFE4M0R6bVFEYVhYeE5tLTVid0pOU2o0UnoySndoQUhVdUR3UlJKTzIxN1FVTXkwZlZ4RWJJa2lxUE1JdzdwaDZHSHBnLTJJM0VpUFZfSTJoM3kxWGNCUy1XZzJZcHp5c1JzMGk1OHdpYnZCU2tMQW9ubmRRVlVJUE9kV1pNLUx6dXVJUlQ0bnRDTnVaT3JoN3M4bjI4LVFjandQNHhKd25QY2tBZl9v&file=Homeland+S08E09+HDTV+VOSTFR+
2020-04-07 10:47:08 DEBUG    SEARCHQUEUE-MANUAL-247897 :: [Oxtorrent] :: The highest quality of any match is 720p HDTV
2020-04-07 10:47:08 DEBUG    SEARCHQUEUE-MANUAL-247897 :: [Oxtorrent] :: Picking the best result out of [u'Homeland.S08E09.HDTV.VOSTFR']
2020-04-07 10:47:08 INFO     SEARCHQUEUE-MANUAL-247897 :: [Oxtorrent] :: Quality of Homeland.S08E09.HDTV.VOSTFR is 720p HDTV
2020-04-07 10:47:08 DEBUG    SEARCHQUEUE-MANUAL-247897 :: [Oxtorrent] :: Picked Homeland.S08E09.HDTV.VOSTFR as the best
2020-04-07 10:47:08 DEBUG    SEARCHQUEUE-MANUAL-247897 :: [Oxtorrent] :: Checking if we should keep searching after we've found Homeland.S08E09.HDTV.VOSTFR
2020-04-07 10:47:08 INFO     SEARCHQUEUE-MANUAL- :: Downloading Homeland.S08E09.HDTV.VOSTFR from Oxtorrent
2020-04-07 10:47:09 INFO     SEARCHQUEUE-MANUAL- :: Request failed: 404 Client Error: Not Found for url: http://192.168.1.60:9117/dl/oxtorrent/?jackett_apikey=**********&path=Q2ZESjhGZHdKcWI2czM1THNvVm80SDd6U0RuR1NhOUh2QnRGbFJqNGNfdGhyU09HSnk1cFE4M0R6bVFEYVhYeE5tLTVid0pOU2o0UnoySndoQUhVdUR3UlJKTzIxN1FVTXkwZlZ4RWJJa2lxUE1JdzdwaDZHSHBnLTJJM0VpUFZfSTJoM3kxWGNCUy1XZzJZcHp5c1JzMGk1OHdpYnZCU2tMQW9ubmRRVlVJUE9kV1pNLUx6dXVJUlQ0bnRDTnVaT3JoN3M4bjI4LVFjandQNHhKd25QY2tBZl9v&file=Homeland+S08E09+HDTV+VOSTFR+ (<type 'str'>)
2020-04-07 10:47:09 DEBUG    SEARCHQUEUE-MANUAL- :: Traceback (most recent call last):
  File "/opt/sickchill/sickbeard/search_queue.py", line 186, in run
    self.success = search.snatchEpisode(searchResult[0])
  File "/opt/sickchill/sickbeard/search.py", line 111, in snatchEpisode
    if response.next and response.next.url and response.next.url.startswith('magnet'):
AttributeError: 'NoneType' object has no attribute 'next'

Here is the log when everything works:

2020-03-30 11:26:38 INFO     SEARCHQUEUE-BACKLOG- :: Downloading The.Walking.Dead.S10E14.HDTV.VOSTFR.BluRay.720p from Oxtorrent
2020-03-30 11:26:48 DEBUG    SEARCHQUEUE-BACKLOG- :: GET URL: http://192.168.1.60:9117/dl/oxtorrent/?jackett_apikey=**********&path=Q2ZESjhGZHdKcWI2czM1THNvVm80SDd6U0RuNmpaUDZSa1pWOHl3d3NhcllmUkNGdURQYWc5bk56UkdmSUtvRDNMcTlqR3MwZE5ZcFJNYzNBaTdWZ0x0NXBZNy04bEdxZW1jRzNzbXpQeEJoVl94cUhxNEQ0aTVRZXhKY2k0el96QU16OXFUUFdjbzJKUjNvYXdkLW55SFlpd012Um1JRk50RWhQTGhMdGpUTlJXOFBPZjlTTHNia2lVSzczSGJQY1o5OVFYREEwdEtTUUJyWlFZdktWbFk3MHpiQ1Q2RTZuQ0gyM2x1azlRVlFtY3VT&file=The+Walking+Dead+S10E14+HDTV+VOSTFR+BluRay+720p+ [Status: 200]
2020-03-30 11:26:48 INFO     SEARCHQUEUE-BACKLOG- :: Downloading a result from Oxtorrent at http://192.168.1.60:9117/dl/oxtorrent/?jackett_apikey=**********&path=Q2ZESjhGZHdKcWI2czM1THNvVm80SDd6U0RuNmpaUDZSa1pWOHl3d3NhcllmUkNGdURQYWc5bk56UkdmSUtvRDNMcTlqR3MwZE5ZcFJNYzNBaTdWZ0x0NXBZNy04bEdxZW1jRzNzbXpQeEJoVl94cUhxNEQ0aTVRZXhKY2k0el96QU16OXFUUFdjbzJKUjNvYXdkLW55SFlpd012Um1JRk50RWhQTGhMdGpUTlJXOFBPZjlTTHNia2lVSzczSGJQY1o5OVFYREEwdEtTUUJyWlFZdktWbFk3MHpiQ1Q2RTZuQ0gyM2x1azlRVlFtY3VT&file=The+Walking+Dead+S10E14+HDTV+VOSTFR+BluRay+720p+
2020-03-30 11:26:49 DEBUG    SEARCHQUEUE-BACKLOG- :: GET URL: http://192.168.1.60:9117/dl/oxtorrent/?jackett_apikey=**********&path=Q2ZESjhGZHdKcWI2czM1THNvVm80SDd6U0RuNmpaUDZSa1pWOHl3d3NhcllmUkNGdURQYWc5bk56UkdmSUtvRDNMcTlqR3MwZE5ZcFJNYzNBaTdWZ0x0NXBZNy04bEdxZW1jRzNzbXpQeEJoVl94cUhxNEQ0aTVRZXhKY2k0el96QU16OXFUUFdjbzJKUjNvYXdkLW55SFlpd012Um1JRk50RWhQTGhMdGpUTlJXOFBPZjlTTHNia2lVSzczSGJQY1o5OVFYREEwdEtTUUJyWlFZdktWbFk3MHpiQ1Q2RTZuQ0gyM2x1azlRVlFtY3VT&file=The+Walking+Dead+S10E14+HDTV+VOSTFR+BluRay+720p+ [Status: 200]
2020-03-30 11:26:49 INFO     SEARCHQUEUE-BACKLOG- :: Saved result to /media/freebox/Téléchargements/A Télécharger/The.Walking.Dead.S10E14.HDTV.VOSTFR.BluRay.720p.torrent
2020-03-30 11:26:49 DEBUG    SEARCHQUEUE-BACKLOG- :: Checking if we should stop searching for a better quality for for episode The.Walking.Dead.S10E14.HDTV.VOSTFR.BluRay.720p
2020-03-30 11:26:50 DEBUG    SEARCHQUEUE-BACKLOG- :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> The Walking Dead - 10x14 - Look at the Flowers - 720p BluRay

Can you investigate? if you want more informations do not hesitate
Thanks

**Comment by miigotu** [comment]
This is a jackett problem, not a SC one.
