### ISSUE TITLE
Page testRename fails with HTTP 504 on synology

### ISSUE THREAD

**Issue by marcofranssen** [SickChill/SickChill#6183]
Branch/Commit: master 50a2b16835064938d2a99129fca8744edcfb18a2
OS: Synology
Browser: Google Chrome
What you did: navigate to `/home/testRename?show=` for the walking dead which has many episodes
What happened: Page doesn't load and fails with 504
What you expected: The page opens quicker
Logs:
```
AA TypeError: get() takes at least 2 arguments (1 given)
AA result = func(*args, **kwargs)
AA File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 292, in wrapper
AA raise_exc_info(self._exc_info)
AA File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/concurrent.py", line 238, in result
AA value = future.result()
AA File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 1055, in run
AA result = yield result
AA File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1511, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='https', host='sickrage.********.nl', method='GET', uri='/favicon.ico', version='HTTP/1.1', remote_ip='84.28.154.71', headers={'Accept-Language': 'en-US,en;q=0.9,nl;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'X-Forwarded-For': '***.***.***.***', 'Host': 'sickrage.********.com', 'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36', 'Connection': 'close', 'X-Forwarded-Proto': 'https', 'Referer': 'https://sickrage.********.com/home/testRename?show=153021', 'Sec-Fetch-Mode': 'no-cors', 'X-Real-Ip': '84.28.154.71', 'Cookie': '_ga=GA1.2.882667637.1576957888; sickchill_user="xxxxxxxxx"', 'Sec-Fetch-Site': 'same-origin', 'Sec-Fetch-Dest': 'image'})
```

In general the page to rename episodes is very slow and in the case of series with a huge amount of episodes it completely fails to load.

**Comment by miigotu** [comment]
Very likely your nas is running out of memory there, but there isnt much I can do about it. Have you tried to do it using the local IP of the nas? Preview rename isnt something you should be needing to do almost *ever*, use the post processor and it it handle the renaming.

**Comment by miigotu** [comment]
#5984
