### ISSUE TITLE
Won't start after update

### ISSUE THREAD

**Issue by theskillwithin** [SickChill/SickChill#6213]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Most recent release
OS:  ReadyNAS
Browser: Chrome
What you did: Update Sickchill
What happened: It did not start up again, can't seem to start the app up again

**Comment by theskillwithin** [comment]
I think my only option here is to somehow reinstall and then use the previous backup once i reinstalled

**Comment by developenguin** [comment]
The workaround in https://github.com/SickChill/SickChill/issues/6208 worked for me. Then start sickchill manually. For me (FreeNAS) it is 'service sickchill start'

**Comment by theskillwithin** [comment]
i figured out how to look at logs:

```
➜  sickchill journalctl -u fvapp-sickchill.service | tail -50
Apr 18 13:56:58 AustinReadyNAS python[5002]:   File "/apps/sickchill/SickBeard.py", line 67, in <module>
Apr 18 13:56:58 AustinReadyNAS python[5002]:     import sickbeard
Apr 18 13:56:58 AustinReadyNAS python[5002]:   File "/apps/sickchill/sickbeard/__init__.py", line 41, in <module>
Apr 18 13:56:58 AustinReadyNAS python[5002]:     import sickchill
Apr 18 13:56:58 AustinReadyNAS python[5002]:   File "/apps/sickchill/sickchill/__init__.py", line 5, in <module>
Apr 18 13:56:58 AustinReadyNAS python[5002]:     from .show.indexers import indexer, ShowIndexer
Apr 18 13:56:58 AustinReadyNAS python[5002]:   File "/apps/sickchill/sickchill/show/indexers/__init__.py", line 22, in <module>
Apr 18 13:56:58 AustinReadyNAS python[5002]:     from .handler import ShowIndexer
Apr 18 13:56:58 AustinReadyNAS python[5002]:   File "/apps/sickchill/sickchill/show/indexers/handler.py", line 31, in <module>
Apr 18 13:56:58 AustinReadyNAS python[5002]:     from sickbeard.tv import Show
Apr 18 13:56:58 AustinReadyNAS python[5002]:   File "/apps/sickchill/sickbeard/tv.py", line 48, in <module>
Apr 18 13:56:58 AustinReadyNAS python[5002]:     from . import db, helpers, logger, network_timezones, notifiers, postProcessor, subtitles
Apr 18 13:56:58 AustinReadyNAS python[5002]:   File "/apps/sickchill/sickbeard/helpers.py", line 55, in <module>
Apr 18 13:56:58 AustinReadyNAS python[5002]:     import cloudscraper
Apr 18 13:56:58 AustinReadyNAS python[5002]:   File "/apps/sickchill/lib/cloudscraper/__init__.py", line 27, in <module>
Apr 18 13:56:58 AustinReadyNAS python[5002]:     from .exceptions import (
Apr 18 13:56:58 AustinReadyNAS python[5002]: ImportError: cannot import name CloudflareLoopProtection
Apr 18 13:56:58 AustinReadyNAS systemd[1]: fvapp-sickchill.service: Main process exited, code=exited, status=1/FAILURE
Apr 18 13:56:58 AustinReadyNAS systemd[1]: fvapp-sickchill.service: Unit entered failed state.
Apr 18 13:56:58 AustinReadyNAS systemd[1]: fvapp-sickchill.service: Failed with result 'exit-code'.
Apr 18 13:56:58 AustinReadyNAS systemd[1]: fvapp-sickchill.service: Service hold-off time over, scheduling restart.
Apr 18 13:56:58 AustinReadyNAS systemd[1]: Stopped Service for sickchill app.
Apr 18 13:56:59 AustinReadyNAS systemd[1]: Started Service for sickchill app.
Apr 18 13:57:00 AustinReadyNAS python[5011]: Traceback (most recent call last):
Apr 18 13:57:00 AustinReadyNAS python[5011]:   File "/apps/sickchill/SickBeard.py", line 67, in <module>
Apr 18 13:57:00 AustinReadyNAS python[5011]:     import sickbeard
Apr 18 13:57:00 AustinReadyNAS python[5011]:   File "/apps/sickchill/sickbeard/__init__.py", line 41, in <module>
Apr 18 13:57:00 AustinReadyNAS python[5011]:     import sickchill
Apr 18 13:57:00 AustinReadyNAS python[5011]:   File "/apps/sickchill/sickchill/__init__.py", line 5, in <module>
Apr 18 13:57:00 AustinReadyNAS python[5011]:     from .show.indexers import indexer, ShowIndexer
Apr 18 13:57:00 AustinReadyNAS python[5011]:   File "/apps/sickchill/sickchill/show/indexers/__init__.py", line 22, in <module>
Apr 18 13:57:00 AustinReadyNAS python[5011]:     from .handler import ShowIndexer
Apr 18 13:57:00 AustinReadyNAS python[5011]:   File "/apps/sickchill/sickchill/show/indexers/handler.py", line 31, in <module>
Apr 18 13:57:00 AustinReadyNAS python[5011]:     from sickbeard.tv import Show
Apr 18 13:57:00 AustinReadyNAS python[5011]:   File "/apps/sickchill/sickbeard/tv.py", line 48, in <module>
Apr 18 13:57:00 AustinReadyNAS python[5011]:     from . import db, helpers, logger, network_timezones, notifiers, postProcessor, subtitles
Apr 18 13:57:00 AustinReadyNAS python[5011]:   File "/apps/sickchill/sickbeard/helpers.py", line 55, in <module>
Apr 18 13:57:00 AustinReadyNAS python[5011]:     import cloudscraper
Apr 18 13:57:00 AustinReadyNAS python[5011]:   File "/apps/sickchill/lib/cloudscraper/__init__.py", line 27, in <module>
Apr 18 13:57:00 AustinReadyNAS python[5011]:     from .exceptions import (
Apr 18 13:57:00 AustinReadyNAS python[5011]: ImportError: cannot import name CloudflareLoopProtection
Apr 18 13:57:00 AustinReadyNAS systemd[1]: fvapp-sickchill.service: Main process exited, code=exited, status=1/FAILURE
Apr 18 13:57:00 AustinReadyNAS systemd[1]: fvapp-sickchill.service: Unit entered failed state.
Apr 18 13:57:00 AustinReadyNAS systemd[1]: fvapp-sickchill.service: Failed with result 'exit-code'.
Apr 18 13:57:00 AustinReadyNAS systemd[1]: fvapp-sickchill.service: Service hold-off time over, scheduling restart.
Apr 18 13:57:00 AustinReadyNAS systemd[1]: Stopped Service for sickchill app.
Apr 18 13:57:00 AustinReadyNAS systemd[1]: fvapp-sickchill.service: Start request repeated too quickly.
Apr 18 13:57:00 AustinReadyNAS systemd[1]: Failed to start Service for sickchill app.
Apr 18 13:57:00 AustinReadyNAS systemd[1]: fvapp-sickchill.service: Unit entered failed state.
Apr 18 13:57:00 AustinReadyNAS systemd[1]: fvapp-sickchill.service: Failed with result 'start-limit-hit'.
```

**Comment by theskillwithin** [comment]
closing this because this appears to be the same problem occurring in #6208

**Comment by miigotu** [comment]
@VeNoMouS
https://github.com/VeNoMouS/cloudscraper/commit/b31521ca9604223c2a124ed144453de5eea27b35
This commit is breaking things and I don't understand why

**Comment by VeNoMouS** [comment]
Have them check the `lib/cloudscraper` and that they dont have an old `exceptions` directory which was in earlier versions.
