### ISSUE TITLE
v2020.04.19-4 still has that lxml etree error.

### ISSUE THREAD

**Issue by Viss** [SickChill/SickChill#6218]
Branch/Commit: v2020.04.19-4
OS: synology os
Browser: newest chrome
What you did: tried to add a show
What happened: I got this etree error
What you expected: for the show to be added without an error
Logs:
```
AA ImportError: cannot import name etree
AA from lxml import etree as ElementTree
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/piculet.py", line 263, in
AA from .piculet import Path, Rule, Rules
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/companyParser.py", line 32, in
AA from . import (
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/__init__.py", line 40, in
AA from .parser.http import IMDbHTTPAccessSystem
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/imdb/__init__.py", line 195, in IMDb
AA i = imdb.IMDb()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 851, in loadIMDbInfo
AA self.loadIMDbInfo()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 785, in loadFromDB
AA self.loadFromDB()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 120, in __init__
AA newShow = TVShow(self.indexer, self.indexer_id, self.lang)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 405, in run
AA ImportError: cannot import name etree
AA from lxml import etree as ElementTree
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/piculet.py", line 263, in
AA from .piculet import Path, Rule, Rules
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/companyParser.py", line 32, in
AA from . import (
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/__init__.py", line 40, in
AA from .parser.http import IMDbHTTPAccessSystem
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/imdb/__init__.py", line 195, in IMDb
AA i = imdb.IMDb()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 851, in loadIMDbInfo
AA self.loadIMDbInfo()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 785, in loadFromDB
AA self.loadFromDB()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 120, in __init__
AA newShow = TVShow(self.indexer, self.indexer_id, self.lang)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 405, in run
AA Traceback (most recent call last):
2020-04-19 00:14:08 ERROR SHOWQUEUE-ADD :: [9c4c5c5] Error trying to add show: cannot import name etree
AA ImportError: cannot import name etree
AA from lxml import etree as ElementTree
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/piculet.py", line 263, in
AA from .piculet import Path, Rule, Rules
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/companyParser.py", line 32, in
AA from . import (
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/__init__.py", line 40, in
AA from .parser.http import IMDbHTTPAccessSystem
AA File "/volume1/@appstore/sickchill/var/SickBeard/lib/imdb/__init__.py", line 195, in IMDb
AA i = imdb.IMDb()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 851, in loadIMDbInfo
AA self.loadIMDbInfo()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 785, in loadFromDB
AA self.loadFromDB()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 120, in __init__
AA newShow = TVShow(self.indexer, self.indexer_id, self.lang)
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickbeard/show_queue.py", line 405, in run
AA Traceback (most recent call last):
2020-04-19 00:14:08 ERROR SHOWQUEUE-ADD :: [9c4c5c5] Unable to add show due to an error with theTVDB: cannot import name etree
2020-04-19 00:14:08 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /volume1/Movies/fresh/Atlanta
```

**Comment by Viss** [comment]
additionally,I have to edit three files and manually change feedparser import lines and pyjsparser import lines, because they call submodules that dont exist on synology. making just 'import feedparser' and 'import pyjsparser' fix those problems. It wont even start with those errors, so manual edits are required. Once those are all done, we're back to square 1 with this libxml/etree error.

**Comment by miigotu** [comment]
The feedparser error is that you need to delete the folder `lib/feedparser`, the pyjsparser one is a similar fix but I dont know the error to say what it is.
You need to install lxml outside of SC, it is a dependancy

**Comment by miigotu** [comment]
Also, lets not open 10 issues for the same problem. Theres like 30 of them already, you arent the only person having trouble,

**Comment by Viss** [comment]
lxml is installed already, and deleting lib/feedparser doesnt fix the error.
Additionally, following these steps gets undone when the update runs and it tries to catch up, and the dirs need to get nuked and the files need to be edited to get it to come back to life.

**Comment by miigotu** [comment]
Reinstall the package
