### ISSUE TITLE
Any new show that's added has an error: Error cannot import name etree 

### ISSUE THREAD

**Issue by omerh** [SickChill/SickChill#6239]
Branch/Commit: master/dcb20eaa5e83923d0fdd292804fbfcafc8af7097
OS: Synology
Browser:FF
What you did:Added a show 
What happened:`2020-04-20 13:23:00 MAIN :: [dcb20ea] There was an error creating the show in /volume2/TV/Carnival Row: Error cannot import name etree 
`
Logs:
```
2020-04-20 13:23:00 ERROR    MAIN :: [dcb20ea] There was an error creating the show in /volume2/TV/IPO Family: Error cannot import name etree
Traceback (most recent call last):
  File "/volume2/@appstore/sickchill/var/SickBeard/SickBeard.py", line 416, in load_shows_from_db
    cur_show = TVShow(sql_show[b'indexer'], sql_show[b'indexer_id'])
  File "/volume2/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 120, in __init__
    self.loadFromDB()
  File "/volume2/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 785, in loadFromDB
    self.loadIMDbInfo()
  File "/volume2/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 851, in loadIMDbInfo
    i = imdb.IMDb()
  File "/volume2/@appstore/sickchill/var/SickBeard/lib/imdb/__init__.py", line 195, in IMDb
    from .parser.http import IMDbHTTPAccessSystem
  File "/volume2/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/__init__.py", line 40, in <module>
    from . import (
  File "/volume2/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/companyParser.py", line 32, in <module>
    from .piculet import Path, Rule, Rules
  File "/volume2/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: cannot import name etree
2020-04-20 13:23:00 DEBUG    MAIN :: Traceback (most recent call last):
  File "/volume2/@appstore/sickchill/var/SickBeard/SickBeard.py", line 416, in load_shows_from_db
    cur_show = TVShow(sql_show[b'indexer'], sql_show[b'indexer_id'])
  File "/volume2/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 120, in __init__
    self.loadFromDB()
  File "/volume2/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 785, in loadFromDB
    self.loadIMDbInfo()
  File "/volume2/@appstore/sickchill/var/SickBeard/sickbeard/tv.py", line 851, in loadIMDbInfo
    i = imdb.IMDb()
  File "/volume2/@appstore/sickchill/var/SickBeard/lib/imdb/__init__.py", line 195, in IMDb
    from .parser.http import IMDbHTTPAccessSystem
  File "/volume2/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/__init__.py", line 40, in <module>
    from . import (
  File "/volume2/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/companyParser.py", line 32, in <module>
    from .piculet import Path, Rule, Rules
  File "/volume2/@appstore/sickchill/var/SickBeard/lib/imdb/parser/http/piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: cannot import name etree
```

**Comment by omerh** [comment]
There is an [APP SUMBMITTED] issue that is closed, don't understand why

https://github.com/SickChill/SickChill/issues/5063

**Comment by miigotu** [comment]
How about looking at the open issues, or maybe the pinned ones.
