### ISSUE TITLE
[APP SUBMITTED]: 'unicode' object is not callable

### ISSUE THREAD

**Issue by vroemraw** [SickChill/SickChill#6240]
### INFO
Python Version: **2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]**
Operating System: **Linux-4.15.18-seedhost-x86_64-with-Ubuntu-16.04-xenial**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@e94d4a6e8d6f65318dee8fa07e8a1b77d171cf9a
Link to Log: https://gist.github.com/c16d2db3ade658fe426c986c2c6604ca
### ERROR
```
WEBSERVER-HOME :: [e94d4a6] Failed doing webui callback: Traceback (most recent call last):
  File "/home14/vroemraw/software/SickRage/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
  File "/home14/vroemraw/software/SickRage/sickchill/views/home.py", line 678, in update
    if checkversion.updater.need_update() and checkversion.updater.update():
  File "/home14/vroemraw/software/SickRage/sickbeard/versionChecker.py", line 876, in update
    self.clean_libs()
  File "/home14/vroemraw/software/SickRage/sickbeard/versionChecker.py", line 883, in clean_libs
    lib_path = ek(os.path.join, sickbeard.PROG_DIR, 'lib')
  File "/home14/vroemraw/software/SickRage/sickchill/helper/encoding.py", line 46, in ek
    result = function(*[ss(x) if isinstance(x, six.string_types) else x for x in args], **kwargs)
TypeError: 'unicode' object is not callable

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Just restart it, it is ok.
