### ISSUE TITLE
SC wont start after updating to latest commit

### ISSUE THREAD

**Issue by zarboz** [SickChill/SickChill#6243]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 518e33e62
OS: MacOS
Browser: Chrome
What you did: Tried to init SC from terminal
What happened: Failed launch
What you expected: Website to be opened

Appears to be some issue with python loading up proper libs 

last stable commit is:
77822cbf3

Logs:
```
python SickBeard.py   
Traceback (most recent call last):
  File "SickBeard.py", line 67, in <module>
    import sickbeard
  File "/Volumes/Extended Hack/Users/zarboz/SickChill/sickbeard/__init__.py", line 49, in <module>
    from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_processing_queue, properFinder, providers,
  File "/Volumes/Extended Hack/Users/zarboz/SickChill/sickbeard/providers/__init__.py", line 29, in <module>
    from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
  File "/Volumes/Extended Hack/Users/zarboz/SickChill/sickbeard/providers/abnormal.py", line 34, in <module>
    from sickchill.providers.torrent.TorrentProvider import TorrentProvider
  File "/Volumes/Extended Hack/Users/zarboz/SickChill/sickchill/providers/torrent/TorrentProvider.py", line 25, in <module>
    from feedparser import FeedParserDict
ImportError: cannot import name FeedParserDict
zarboz@Bryans-iMac SickChill % git reset --hard HEAD^
HEAD is now at 4d23d38d2 Add synchronousdeluge dirty
```

**Comment by zarboz** [comment]
find . -name "*.pyc" -delete
find lib -empty -type d -delete
git pull
git clean -dfq lib

Works on MacOS as well

**Comment by brianjmurrell** [comment]
Yeah, that worked here too.  A bit ugly that it was needed.
