### ISSUE TITLE
Log errors

### ISSUE THREAD

**Issue by nydave69** [SickChill/SickChill#6254]
SickChill Info:
Branch: master
Commit: 518e33e628df975eb178c2a6b8541066818a2359
Database Version: 44.1

  Python Version:
2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]

  SSL Version:
OpenSSL 1.0.2t 10 Sep 2019

  OS:
Windows-7-6.1.7601-SP1

  Locale:
en_US.cp1252

Browser: NA
What you did: Nothing
What happened: Keep finding this error in the logs..
What you expected: no errors :)
Logs:
```
AA ImportError: DLL load failed: %1 is not a valid Win32 application.
AA from lxml import etree as ElementTree
AA File "C:\SickChill\lib\imdb\parser\http\piculet.py", line 263, in 
AA from .piculet import Path, Rule, Rules
AA File "C:\SickChill\lib\imdb\parser\http\companyParser.py", line 32, in 
AA from . import (
AA File "C:\SickChill\lib\imdb\parser\http\__init__.py", line 40, in 
AA from .parser.http import IMDbHTTPAccessSystem
AA File "C:\SickChill\lib\imdb\__init__.py", line 195, in IMDb
AA i = imdb.IMDb()
AA File "C:\SickChill\sickbeard\tv.py", line 851, in loadIMDbInfo
AA self.show.loadIMDbInfo()
AA File "C:\SickChill\sickbeard\show_queue.py", line 661, in run
AA Traceback (most recent call last):
2020-04-21 20:18:04 ERROR    SHOWQUEUE-FORCE-UPDATE :: [518e33e] Error loading IMDb info: DLL load failed: %1 is not a valid Win32 application.PASTE LOGS HERE
```

**Comment by miigotu** [comment]
#6230

**Comment by nydave69** [comment]
This is after a new install from the current zip at the time...

**Comment by miigotu** [comment]
If you have c:\SickChill\SickChill\lib\lxml folder, delete it.
