### ISSUE TITLE
History not working

### ISSUE THREAD

**Issue by meneses-pt** [SickChill/SickChill#6260]
Branch/Commit: master/3a1f59212c9d43fc37f39c886f6fe70e417236b7
OS: Windows
Browser: Chrome
What you did: Clicked on History link
What happened: I got an 404 not found error
What you expected: To see the History page
Logs:
```
2020-04-22 12:26:02 WEBSERVER-HISTORY :: [3a1f592] Failed doing webui callback: Traceback (most recent call last):
File "C:\SickChill\SickChill\sickchill\views\index.py", line 216, in async_call
result = function(**kwargs)
File "C:\SickChill\SickChill\sickchill\views\history.py", line 83, in index
t = PageTemplate(rh=self, filename="history.mako")
File "C:\SickChill\SickChill\sickchill\views\common.py", line 64, in __init__
self.template = lookup.get_template(filename)
File "C:\SickChill\SickChill\lib\mako\lookup.py", line 260, in get_template
return self._load(srcfile, uri)
File "C:\SickChill\SickChill\lib\mako\lookup.py", line 327, in _load
**self.template_args
File "C:\SickChill\SickChill\lib\mako\template.py", line 348, in __init__
module = self._compile_from_file(path, filename)
File "C:\SickChill\SickChill\lib\mako\template.py", line 418, in _compile_from_file
if module._magic_number != codegen.MAGIC_NUMBER:
AttributeError: 'module' object has no attribute '_magic_number'
```

**Comment by miigotu** [comment]
Stop SC and delete `c:\SickChill\SickChill\gui\slick\cache\mako`
