### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'episode' -- cannot download new episodes

### ISSUE THREAD

**Issue by didyouexpectthat** [SickChill/SickChill#6297]
Branch/Commit: 757fa1f130e39bef50b35941364d64ac10bfe3f3
OS: Debian 9 
Browser: Chrome
What you did: Added a new show on SickChill
What happened: It added successfully. SickChill found episodes to download but failed to download them. Haven't had any success download episodes for past 14 hours from any show, both nzb and torrent.
What you expected: SickChill should have been able to pull the the episode without failing.  
Logs:
```
AA AttributeError: 'NoneType' object has no attribute 'episode'
AA episode_number = episode_object[0].episode
AA File "/apps/sickchill/sickchill/providers/GenericProvider.py", line 332, in find_search_results
AA searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
AA File "/apps/sickchill/sickbeard/search.py", line 487, in searchProviders
AA Traceback (most recent call last):
2020-04-22 22:56:42 ERROR SEARCHQUEUE-BACKLOG-360814 :: [ANY PROVIDER] :: [757fa1f] Exception while searching ANY PROVIDER. Error: AttributeError("'NoneType' object has no attribute 'episode'",)
```

**Comment by didyouexpectthat** [comment]
@miigotu  thank you.
