### ISSUE TITLE
Sickchill won't start on MAC OS

### ISSUE THREAD

**Issue by troypressley** [SickChill/SickChill#6310]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Latest
OS: Mac OS Catalina
Browser: Firefox
What you did: Updated Sickchill from the update button in Sickchill. It usually restarts automatically. However this time it did not work. I ran my Applescript for starting Sickchill and got the error listed.
What happened: Errored out
What you expected: Sickchill to start
Logs:
```
The action “Run AppleScript” encountered an error: “Traceback (most recent call last):
  File "/Applications/SickRage/SickBeard.py", line 67, in <module>
    import sickbeard
  File "/Applications/SickRage/sickbeard/__init__.py", line 49, in <module>
    from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_processing_queue, properFinder, providers,
  File "/Applications/SickRage/sickbeard/providers/__init__.py", line 29, in <module>
    from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
  File "/Applications/SickRage/sickbeard/providers/abnormal.py", line 34, in <module>
    from sickchill.providers.torrent.TorrentProvider import TorrentProvider
  File "/Applications/SickRage/sickchill/providers/torrent/TorrentProvider.py", line 25, in <module>
    from feedparser import FeedParserDict
ImportError: cannot import name FeedParserDict
```

**Comment by miigotu** [comment]
#6230
