### ISSUE TITLE
[APP SUBMITTED]: u'home_mako'

### ISSUE THREAD

**Issue by arathas** [SickChill/SickChill#6312]
### INFO
Python Version: **2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 21:01:17) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.18362**
Locale: cp1252
Branch: **master**
Commit: SickChill/SickChill@9092ab322aae9c9d7d2ce183b3f600fbe5c39631
Link to Log: https://gist.github.com/5d65977817e59855f80d7e643bac6e95
### ERROR
```
WEBSERVER-HOME :: [9092ab3] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickchill\views\index.py", line 216, in async_call
    result = function(**kwargs)
  File "C:\SickChill\SickChill\sickchill\views\home.py", line 98, in index
    t = PageTemplate(rh=self, filename="home.mako")
  File "C:\SickChill\SickChill\sickchill\views\common.py", line 64, in __init__
    self.template = lookup.get_template(filename)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 260, in get_template
    return self._load(srcfile, uri)
  File "C:\SickChill\SickChill\lib\mako\lookup.py", line 327, in _load
    **self.template_args
  File "C:\SickChill\SickChill\lib\mako\template.py", line 348, in __init__
    module = self._compile_from_file(path, filename)
  File "C:\SickChill\SickChill\lib\mako\template.py", line 417, in _compile_from_file
    del sys.modules[self.module_id]
KeyError: u'home_mako'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Restart
