### ISSUE TITLE
SC Won't start after last update

### ISSUE THREAD

**Issue by neomvll** [SickChill/SickChill#6314]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
Browser: Chrome
What you did: Update from web link, SC front page
What happened: Page down and can't back, even after Rpi reboot
What you expected: Update, like always
Logs from `sickchill status` :
```
Logs:
   Active: failed (Result: exit-code) since Thu 2020-04-23 19:21:18 -03; 1min 40s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 486 ExecStart=/etc/init.d/sickchill start (code=exited, status=1/FAILURE)

abr 23 19:21:18 raspberrypi sickchill[486]:     write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
abr 23 19:21:18 raspberrypi sickchill[486]:   File "/opt/sickchill/lib/fake_useragent/utils.py", line 189, in load
abr 23 19:21:18 raspberrypi sickchill[486]:     verify_ssl=verify_ssl,
abr 23 19:21:18 raspberrypi sickchill[486]:   File "/opt/sickchill/lib/fake_useragent/utils.py", line 84, in get
abr 23 19:21:18 raspberrypi sickchill[486]:     raise FakeUserAgentError('Maximum amount of retries reached')
abr 23 19:21:18 raspberrypi sickchill[486]: fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
abr 23 19:21:18 raspberrypi systemd[1]: sickchill.service: Control process exited, code=exited status=1
abr 23 19:21:18 raspberrypi systemd[1]: Failed to start LSB: starts instance of SickChill.
abr 23 19:21:18 raspberrypi systemd[1]: sickchill.service: Unit entered failed state.
abr 23 19:21:18 raspberrypi systemd[1]: sickchill.service: Failed with result 'exit-code'.
```
Do you have anyway to do a reinstall from git?? I'm using `https://www.htpcguides.com/install-sickrage-raspberry-pi-usenet-torrent-tv/` and getting:
```
sudo git clone https://github.com/SickChill/SickChill.git /opt/sickchill
fatal: destination path '/opt/sickchill' already exists and is not an empty directory.
```

**Comment by neomvll** [comment]
I did this:
https://github.com/SickChill/SickChill/issues/6224#issuecomment-616137422

And now its working, but not at reboot. Everytime I get this:
```
Apr 23 20:14:30 raspberrypi sickchill[508]: Starting SickChill
Apr 23 20:14:38 raspberrypi sickchill[508]: No handlers could be found for logger "root"
Apr 23 20:14:38 raspberrypi sickchill[508]: Traceback (most recent call last):
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "SickBeard.py", line 67, in <module>
Apr 23 20:14:38 raspberrypi sickchill[508]:     import sickbeard
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/sickbeard/__init__.py", line 41, in <module>
Apr 23 20:14:38 raspberrypi sickchill[508]:     import sickchill
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/sickchill/__init__.py", line 5, in <module>
Apr 23 20:14:38 raspberrypi sickchill[508]:     from .show.indexers import indexer, ShowIndexer
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 22, in <module>
Apr 23 20:14:38 raspberrypi sickchill[508]:     from .handler import ShowIndexer
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/sickchill/show/indexers/handler.py", line 30, in <module>
Apr 23 20:14:38 raspberrypi sickchill[508]:     from sickbeard import logger
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/sickbeard/logger.py", line 53, in <module>
Apr 23 20:14:38 raspberrypi sickchill[508]:     from . import classes
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/sickbeard/classes.py", line 37, in <module>
Apr 23 20:14:38 raspberrypi sickchill[508]:     from .common import Quality, USER_AGENT
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/sickbeard/common.py", line 59, in <module>
Apr 23 20:14:38 raspberrypi sickchill[508]:     UA_POOL = UserAgent()
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/lib/fake_useragent/fake.py", line 69, in __init__
Apr 23 20:14:38 raspberrypi sickchill[508]:     self.load()
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/lib/fake_useragent/fake.py", line 78, in load
Apr 23 20:14:38 raspberrypi sickchill[508]:     verify_ssl=self.verify_ssl,
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/lib/fake_useragent/utils.py", line 250, in load_cached
Apr 23 20:14:38 raspberrypi sickchill[508]:     update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/lib/fake_useragent/utils.py", line 245, in update
Apr 23 20:14:38 raspberrypi sickchill[508]:     write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/lib/fake_useragent/utils.py", line 189, in load
Apr 23 20:14:38 raspberrypi sickchill[508]:     verify_ssl=verify_ssl,
Apr 23 20:14:38 raspberrypi sickchill[508]:   File "/opt/sickchill/lib/fake_useragent/utils.py", line 84, in get
Apr 23 20:14:38 raspberrypi sickchill[508]:     raise FakeUserAgentError('Maximum amount of retries reached')
Apr 23 20:14:38 raspberrypi sickchill[508]: fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
Apr 23 20:14:38 raspberrypi systemd[1]: sickchill.service: Control process exited, code=exited status=1
Apr 23 20:14:38 raspberrypi systemd[1]: sickchill.service: Unit entered failed state.
Apr 23 20:14:38 raspberrypi systemd[1]: sickchill.service: Failed with result 'exit-code'.

```

But after reboot I can do `service sickchill start` and SC goes up
```
Apr 23 20:18:47 raspberrypi sickchill[1857]: Starting SickChill
Apr 23 20:19:29 raspberrypi sickchill[1857]: DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.1.0l  10 Sep 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.

```

So what is missing?? Why SC can't working from auto systemctl anymore after update?

**Comment by miigotu** [comment]
Update python, 2.7.9+, and make sure the steps from #6230 are done.

**Comment by neomvll** [comment]
> Update python to 2.7.9+ (not python 3), and make sure the steps from #6230 are done.

```
pi@raspberrypi:~ $ python --version
Python 2.7.13
```
I did "Linux with Git" steps:
https://github.com/SickChill/SickChill/issues/6230#issue-602814841

SC still won't starts at reboot Rpi, I need to do `service sickchill start` manualy

Worked very well before last update, around 50~55 commits, I think

**Comment by miigotu** [comment]
did you `systemctl enable sickchill` ?

**Comment by neomvll** [comment]
> did you `systemctl enable sickchill` ?

yes

**Comment by miigotu** [comment]
It is because it is trying to access internet before your network is up. I am adding a file that will help with that, but you should make the service depend on network-online.target:
```
After=network-online.target
Wants=network-online.target
```

**Comment by miigotu** [comment]
Edit: why are you using the init script instead of the systemctl unit?

**Comment by neomvll** [comment]
> Edit: why are you using the init script instead of the systemctl unit?
> 
> `runscripts/init.systemd`

just following this guide `https://www.htpcguides.com/install-sickrage-raspberry-pi-usenet-torrent-tv/` Am I wrong?

**Comment by miigotu** [comment]
sytsemd loads sysVinit/init.d scripts just fine, but they lack the extra features like waiting for the network to be up.

**Comment by neomvll** [comment]
> sytsemd loads sysVinit/init.d scripts just fine, but they lack the extra features like waiting for the network to be up.

I understand, so do you have a guide to help me to do this better? Including waiting network etc?

**Comment by miigotu** [comment]
The latest version should work fine for you

**Comment by neomvll** [comment]
> The latest version should work fine for you

Amazing! Its working !
Thanks :)
