### ISSUE TITLE
After running the update of the following Sickchill is not starting anymore

### ISSUE THREAD

**Issue by marcofranssen** [SickChill/SickChill#6318]
Today I pulled in the following changeset when updating.

https://github.com/SickChill/SickChill/compare/50a2b16835064938d2a99129fca8744edcfb18a2...0306ded8f236585531276bc4cc1db9303f26bfce

See below for the logs. SInce then no new logs and sickchil isn't starting anymore.

```
HTTPServerRequest(protocol='https', host='sickrage.********.nl', method='GET', uri='/favicon.ico', version='HTTP/1.1', remote_ip='192.168.178.14', headers={'Accept-Language': 'en-US,en;q=0.9,nl;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'X-Forwarded-For': '192.168.178.14', 'Host': 'sickrage.********.nl', 'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36', 'Connection': 'close', 'X-Forwarded-Proto': 'https', 'Referer': 'https://sickrage.********.nl/home/update/?pid=24922', 'Sec-Fetch-Mode': 'no-cors', 'X-Real-Ip': '192.168.178.14', 'Cookie': '_ga=GA1.2.882667637.1576957888; sickchill_user="2|1:0|10:1586282319|14:sickchill_user|44:YTk4NzE3YjJiM2MxYTUwNDNiNTliNDFkZjNkZTAxZjM=|9ca06b6b8582d8ae17b8c51a913642bbf03d613f5209dcd1e14381ed389140dd"', 'Sec-Fetch-Site': 'same-origin', 'Sec-Fetch-Dest': 'empty'})
Traceback (most recent call last):
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1511, in _execute
    if result is not None:
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
TypeError: get() takes at least 2 arguments (1 given)
2020-04-24 13:05:21 INFO     EVENT-QUEUE :: Aborting all threads
2020-04-24 13:05:21 INFO     EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2020-04-24 13:05:21 INFO     EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2020-04-24 13:05:21 INFO     EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2020-04-24 13:05:21 INFO     EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2020-04-24 13:05:21 INFO     EVENT-QUEUE :: Waiting for the SHOWQUEUE-REFRESH thread to exit
2020-04-24 13:05:21 INFO     EVENT-QUEUE :: Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2020-04-24 13:05:21 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2020-04-24 13:05:21 INFO     EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2020-04-24 13:05:21 INFO     EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2020-04-24 13:05:21 INFO     EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2020-04-24 13:05:22 INFO     EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2020-04-24 13:05:22 INFO     WEBSERVER-HOME :: Config backup in progress...
2020-04-24 13:05:22 INFO     EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2020-04-24 13:05:22 INFO     EVENT-QUEUE :: Saving all shows to the database
2020-04-24 13:05:22 INFO     EVENT-QUEUE :: Saving config file to disk
2020-04-24 13:05:24 INFO     EVENT-QUEUE :: Shutting down Tornado
2020-04-24 13:05:24 INFO     EVENT-QUEUE :: Restarting SickChill with ['/volume2/@appstore/sickbeard-custom/env/bin/python', u'/volume2/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py', '--daemon', '--pidfile', '/volume2/@appstore/sickbeard-custom/var/sickbeard-custom.pid', '--config', '/volume2/@appstore/sickbeard-custom/var/config.ini', '--datadir', '/volume2/@appstore/sickbeard-custom/var/', '--nolaunch']
```

**Comment by marcofranssen** [comment]
I now tried launching myself from commandline. Then following error shows up. I'm running on a Synology NAS.

```bash
$ ../env/bin/python SickBeard/SickBeard.py --config config.ini --datadir /volume2/@appstore/sickbeard-custom/var/ --nolaunch
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2n  7 Dec 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "SickBeard/SickBeard.py", line 67, in <module>
    import sickbeard
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 49, in <module>
    from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_processing_queue, properFinder, providers,
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/__init__.py", line 29, in <module>
    from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/abnormal.py", line 34, in <module>
    from sickchill.providers.torrent.TorrentProvider import TorrentProvider
  File "/volume2/@appstore/sickbeard-custom/var/SickBeard/sickchill/providers/torrent/TorrentProvider.py", line 25, in <module>
    from feedparser import FeedParserDict
ImportError: cannot import name FeedParserDict
```

**Comment by miigotu** [comment]
#6230

**Comment by marcofranssen** [comment]
Thanks

Running 

```
sudo -i find /volume1/@appstore/sickbeard-custom/var/SickBeard -name *.pyc -delete
```

resolved the issue on Synology
