### ISSUE TITLE
SC broke after last update

### ISSUE THREAD

**Issue by waltermaldonado** [SickChill/SickChill#6353]
My SC won't start after updating to the latest commit today.
```
❯ ./SickBeard.py
Traceback (most recent call last):
  File "./SickBeard.py", line 67, in <module>
    import sickbeard
  File "/opt/sickchill/sickbeard/__init__.py", line 49, in <module>
    from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_processing_queue, properFinder, providers,
  File "/opt/sickchill/sickbeard/providers/__init__.py", line 29, in <module>
    from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
  File "/opt/sickchill/sickbeard/providers/abnormal.py", line 34, in <module>
    from sickchill.providers.torrent.TorrentProvider import TorrentProvider
  File "/opt/sickchill/sickchill/providers/torrent/TorrentProvider.py", line 25, in <module>
    from feedparser import FeedParserDict
ImportError: cannot import name FeedParserDict
```

**Comment by flashbacknl** [comment]
https://github.com/SickChill/SickChill/issues/6230 @waltermaldonado
