### ISSUE TITLE
Could not add show due to system time being off: No error message

### ISSUE THREAD

**Issue by jayhowell** [SickChill/SickChill#6354]
Hello All,

Branch/Commit: master/develop
OS: Fedora 22
Browser: firefox
What you did:

* Pulled clean from master
* Using the service profile provided
* I started the service, it started fine
* tried to add already existing shows.
* Finding the show, specifying defaults, etc everything works fine, 
* I click add show

What happened:
* sytem displays the sickchill banner with my show and says, Loading.,
* waited a half hour to see if it was just lagging from tvdb or imdb.(no show was added).
* Show doesn't show up in list and never loads
* enabled debug and tried to add show again, output below in log section
* I looked at different bugs(with the TVDB issue last Nov) and code on an off for 2 days(also went back and forth between master and devel branches)
* I stopped using the service and the {--daemon} switch and just ran it as root on the bare command line.
* I saw the error(2nd log block below){Request timestamp: Thu, 30 Apr 2020 06:15:11 GMT expired.  It must be within 300 secs/ of server time.}
* I realized that for some reason, my ntp quit working and my clock was 20 minutes off
* Fixed the time and shows add correctly.
* We just need to catch the and display the error in {show_queue.py}

What you expected:
* Show to eventuall load from TVDB or IMDB and show up in my list.
* It never does and never throws an error saying the time is out of sync
Logs:
**Debug log that shows no error**
```2020-04-30 11:20:05 DEBUG    WEBSERVER-ADDSHOWS :: Searching for Show with searchterm(s): ['The Plot Against America', 'Plot Against America'] on Indexer: theTVDB
2020-04-30 11:20:14 INFO     SHOWQUEUE-ADD :: Starting to add show by ShowDir: /mnt/Shows/The Plot Against America
2020-04-30 11:20:15 INFO     SHOWQUEUE-ADD :: 367559: Unable to find the show in the database
2020-04-30 11:20:15 DEBUG    SHOWQUEUE-ADD :: 367559: Loading show info from theTVDB
2020-04-30 11:20:15 DEBUG    SHOWQUEUE-ADD :: Setter sets location to /mnt/Shows/The Plot Against America
2020-04-30 11:20:15 INFO     SHOWQUEUE-ADD :: Setting all episodes to the specified default status: 5
2020-04-30 11:20:15 DEBUG    SHOWQUEUE-ADD :: 367559: Loading show info from IMDb
```

**output from running bare command line {python2.7 sickbeard.py}**
```Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/opt/sickchill/sickbeard/show_queue.py", line 469, in run
    self.show.loadIMDbInfo()
  File "/opt/sickchill/sickbeard/tv.py", line 874, in loadIMDbInfo
    imdb_title = i.get_title(self.imdbid)
  File "/opt/sickchill/lib/imdbpie/facade.py", line 23, in get_title
    title_data, title_aux_data = self._get_title_data(imdb_id=imdb_id)
  File "/opt/sickchill/lib/imdbpie/facade.py", line 157, in _get_title_data
    base_title_data = self._client.get_title(imdb_id=imdb_id)
  File "/opt/sickchill/lib/imdbpie/imdbpie.py", line 81, in get_title
    '/title/{0}/auxiliary'.format(imdb_id)
  File "/opt/sickchill/lib/imdbpie/imdbpie.py", line 299, in _get_resource
    return self._get(url=url)['resource']
  File "/opt/sickchill/lib/imdbpie/imdbpie.py", line 315, in _get
    raise ImdbAPIError(msg)
ImdbAPIError: 400 {"message":"Request timestamp: Thu, 30 Apr 2020 06:15:11 GMT expired.  It must be within 300 secs/ of server time."}
```

**Comment by miigotu** [comment]
#6350

**Comment by jayhowell** [comment]
This was not a duplicate of #6350. This WAS NOT due to tmp directory. If you look at the log, it was actually due to my local system time being off when making the REST call to TVDB or IMDB. It's fairly easy to reproduce.  Just set your time off by a half hour and try to add a show. 

I did come across #6350 and was commenting on that one because I initially thought that was my problem, but it wasn't. This is an edge case because "who is going to have the incorrect time on thier server, right?"

I know what it was and how to fix it, but wanted to either put it out there so others could see it or so we could make sick chill better. 

Cheers, Jay

**Comment by miigotu** [comment]
The log is clear, it tells you to set your system time.

This error is in a 3rd party library, so if it's something you think isn't good enough open the issue on the imdbpie repo.
