### ISSUE TITLE
Error adding Foreign Language show

### ISSUE THREAD

**Issue by opie4624** [SickChill/SickChill#6370]
Branch/Commit: c5ed827b40693bd481417845e37ff2622cd6ab8a
OS: FreeBSD
Browser: Chrome
What you did: Added a Korean Show
What happened: Error creating show
What you expected: It would get added fine (either with english or korean titleing)
TVDB ID: [349768](https://thetvdb.com/series/tvn-escape)
Logs:
```
2020-05-03 16:10:21 MAIN :: [c5ed827] There was an error creating the show in /media/TV/대탈출: Error invalid query, does not contain any alphanumeric characters
```

**Comment by opie4624** [comment]
More logs:
```
AA ValueError: invalid query, does not contain any alphanumeric characters
AA 'invalid query, does not contain any alphanumeric characters'
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/imdbpie/imdbpie.py", line 348, in _query_first_alpha_num
AA first_alphanum_char = self._query_first_alpha_num(cleaned_query)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/imdbpie/imdbpie.py", line 155, in _suggest_search
AA search_results = self._suggest_search(title)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/imdbpie/imdbpie.py", line 182, in search_for_title
AA for result in self._client.search_for_title(query):
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/imdbpie/facade.py", line 87, in search_for_title
AA results = filter(lambda x: x.type == 'TV series' and x.title == attempt, i.search_for_title(attempt))
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 856, in loadIMDbInfo
AA self.loadIMDbInfo()
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 797, in loadFromDB
AA self.loadFromDB()
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 121, in __init__
AA newShow = TVShow(self.indexer, self.indexer_id, self.lang)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/show_queue.py", line 404, in run
AA ValueError: invalid query, does not contain any alphanumeric characters
AA 'invalid query, does not contain any alphanumeric characters'
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/imdbpie/imdbpie.py", line 348, in _query_first_alpha_num
AA first_alphanum_char = self._query_first_alpha_num(cleaned_query)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/imdbpie/imdbpie.py", line 155, in _suggest_search
AA search_results = self._suggest_search(title)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/imdbpie/imdbpie.py", line 182, in search_for_title
AA for result in self._client.search_for_title(query):
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/imdbpie/facade.py", line 87, in search_for_title
AA results = filter(lambda x: x.type == 'TV series' and x.title == attempt, i.search_for_title(attempt))
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 856, in loadIMDbInfo
AA self.loadIMDbInfo()
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 797, in loadFromDB
AA self.loadFromDB()
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 121, in __init__
AA newShow = TVShow(self.indexer, self.indexer_id, self.lang)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/show_queue.py", line 404, in run
AA Traceback (most recent call last):
2020-05-03 17:21:39 ERROR SHOWQUEUE-ADD :: [c5ed827] Error trying to add show: invalid query, does not contain any alphanumeric characters
AA ValueError: invalid query, does not contain any alphanumeric characters
AA 'invalid query, does not contain any alphanumeric characters'
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/imdbpie/imdbpie.py", line 348, in _query_first_alpha_num
AA first_alphanum_char = self._query_first_alpha_num(cleaned_query)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/imdbpie/imdbpie.py", line 155, in _suggest_search
AA search_results = self._suggest_search(title)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/imdbpie/imdbpie.py", line 182, in search_for_title
AA for result in self._client.search_for_title(query):
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/lib/imdbpie/facade.py", line 87, in search_for_title
AA results = filter(lambda x: x.type == 'TV series' and x.title == attempt, i.search_for_title(attempt))
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 856, in loadIMDbInfo
AA self.loadIMDbInfo()
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 797, in loadFromDB
AA self.loadFromDB()
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/tv.py", line 121, in __init__
AA newShow = TVShow(self.indexer, self.indexer_id, self.lang)
AA File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/show_queue.py", line 404, in run
AA Traceback (most recent call last):
2020-05-03 17:21:39 ERROR SHOWQUEUE-ADD :: [c5ed827] Unable to add show due to an error with theTVDB: invalid query, does not contain any alphanumeric characters
2020-05-03 17:21:38 INFO SHOWQUEUE-ADD :: Starting to add show by ShowDir: /media/TV/The Great Escape (2018)
```
