### ISSUE TITLE
Docker : Fail to Establish a new connection

### ISSUE THREAD

**Issue by Ex4l** [SickChill/SickChill#6379]
Since the last update on the docker image, every time i'm trying to search for an episode show or add a new show i got a network connection error.

## Branch/Commit: 
latest docker image (i don't update via git)

## OS: 
Sickchill official docker container running under XPenology

## Browser: 
chrome

## What you did: 
Add a new show, search manually for a show episode

## What happened: 
Network error

## What you expected: 
being able to add a new show,
download the show episode

## Logs:
```
2020-05-05 09:15:58 INFO SEARCHQUEUE-DAILY-SEARCH :: Checking for scene exception updates from http://sickchill.github.io/scene_exceptions/scene_exceptions.json
2020-05-05 09:15:58 INFO SEARCHQUEUE-DAILY-SEARCH :: Request failed: HTTPConnectionPool(host='sickchill.github.io', port=80): Max retries exceeded with url: /scene_exceptions/scene_exceptions.json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Try again',)) ()
2020-05-05 09:15:53 INFO SEARCHQUEUE-DAILY-SEARCH :: Checking for scene exception updates from http://sickchill.github.io/scene_exceptions/scene_exceptions.json
2020-05-05 09:15:53 INFO SEARCHQUEUE-DAILY-SEARCH :: Request failed: HTTPConnectionPool(host='sickchill.github.io', port=80): Max retries exceeded with url: /scene_exceptions/scene_exceptions.json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Try again',)) ()
2020-05-05 09:15:48 INFO SEARCHQUEUE-DAILY-SEARCH :: Checking for scene exception updates from http://sickchill.github.io/scene_exceptions/scene_exceptions.json
2020-05-05 09:15:47 INFO SEARCHQUEUE-DAILY-SEARCH :: Request failed: HTTPConnectionPool(host='sickchill.github.io', port=80): Max retries exceeded with url: /scene_exceptions/scene_exceptions.json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Try again',)) ()
2020-05-05 09:15:42 INFO SEARCHQUEUE-DAILY-SEARCH :: Checking for scene exception updates from http://sickchill.github.io/scene_exceptions/scene_exceptions.json
2020-05-05 09:15:42 INFO SEARCHQUEUE-DAILY-SEARCH :: Request failed: HTTPConnectionPool(host='sickchill.github.io', port=80): Max retries exceeded with url: /scene_exceptions/scene_exceptions.json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Try again',)) ()
2020-05-05 09:15:37 INFO SEARCHQUEUE-DAILY-SEARCH :: Checking for scene exception updates from http://sickchill.github.io/scene_exceptions/scene_exceptions.json
2020-05-05 09:15:37 INFO SEARCHQUEUE-DAILY-SEARCH :: Request failed: HTTPConnectionPool(host='sickchill.github.io', port=80): Max retries exceeded with url: /scene_exceptions/scene_exceptions.json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Try again',)) ()
2020-05-05 09:15:32 INFO SEARCHQUEUE-DAILY-SEARCH :: Checking for scene exception updates from http://sickchill.github.io/scene_exceptions/scene_exceptions.json
2020-05-05 09:15:31 INFO SEARCHQUEUE-DAILY-SEARCH :: Request failed: HTTPConnectionPool(host='sickchill.github.io', port=80): Max retries exceeded with url: /scene_exceptions/scene_exceptions.json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Try again',)) ()
2020-05-05 09:15:26 INFO SEARCHQUEUE-DAILY-SEARCH :: Checking for scene exception updates from http://sickchill.github.io/scene_exceptions/scene_exceptions.json
2020-05-05 09:15:25 INFO SEARCHQUEUE-DAILY-SEARCH :: Request failed: HTTPConnectionPool(host='sickchill.github.io', port=80): Max retries exceeded with url: /scene_exceptions/scene_exceptions.json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Try again',)) ()
2020-05-05 09:15:20 INFO SEARCHQUEUE-DAILY-SEARCH :: Checking for scene exception updates from http://sickchill.github.io/scene_exceptions/scene_exceptions.json
AA ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/SickChill (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Try again',))
AA raise ConnectionError(e, request=request)
AA File "/app/sickchill/lib/requests/adapters.py", line 516, in send
AA r = adapter.send(request, **kwargs)
AA File "/app/sickchill/lib/requests/sessions.py", line 643, in send
AA resp = self.send(prep, **send_kwargs)
AA File "/app/sickchill/lib/requests/sessions.py", line 530, in request
AA return self.request('GET', url, **kwargs)
AA File "/app/sickchill/lib/requests/sessions.py", line 543, in get
AA allow_redirects=False,
AA File "/app/sickchill/lib/github/Requester.py", line 119, in getresponse
AA response = cnx.getresponse()
AA File "/app/sickchill/lib/github/Requester.py", line 501, in __requestRaw
AA cnx, verb, url, requestHeaders, encoded_input
AA File "/app/sickchill/lib/github/Requester.py", line 475, in __requestEncode
AA return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
AA File "/app/sickchill/lib/github/Requester.py", line 413, in requestJson
AA verb, url, parameters, headers, input, self.__customConnection(url)
AA File "/app/sickchill/lib/github/Requester.py", line 322, in requestJsonAndCheck
AA headers, data = self.__requester.requestJsonAndCheck("GET", "/orgs/" + login)
AA File "/app/sickchill/lib/github/MainClass.py", line 293, in get_organization
AA sickbeard.gh.get_organization(sickbeard.GIT_ORG)
AA File "/app/sickchill/sickchill/helper/common.py", line 382, in setup_github
AA Traceback (most recent call last):
2020-05-05 09:15:20 ERROR WEBSERVER-CONFIGGENERAL :: [42a2ae4] Unable to setup GitHub properly. GitHub will not be available. Error: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/SickChill (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Try again',))
```

**Comment by miigotu** [comment]
Reverted a change to the docker image, I will merge it to master soon as I get to a PC.

**Comment by Ex4l** [comment]
> Reverted a change to the docker image, I will merge it to master soon as I get to a PC.

Thank you ! 😊
