### ISSUE TITLE
sickchill service will not start

### ISSUE THREAD

**Issue by AP-Engineering** [SickChill/SickChill#6414]
### Before submitting your issue:

Branch/Commit: not sure as webserver not working
OS: raspberry pi
Browser: chrome
What you did: updated sickchill manually
What happened: webserver will not start (sickchill service failed to start)
What you expected:
Logs:
```
2020-05-06 22:03:49 ERROR    WEBSERVER-CONFIGGENERAL :: [6515b3a] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickchill/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
  File "/opt/sickchill/sickchill/views/config/general.py", line 219, in saveGeneral
    sickbeard.save_config()
  File "/opt/sickchill/sickbeard/__init__.py", line 1781, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
  File "/opt/sickchill/lib/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/sickchill/lib/configobj.py", line 1318, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1078.
Traceback (most recent call last):
  File "/opt/sickchill/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
  File "/opt/sickchill/sickchill/views/config/general.py", line 219, in saveGeneral
    sickbeard.save_config()
  File "/opt/sickchill/sickbeard/__init__.py", line 1781, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
  File "/opt/sickchill/lib/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/sickchill/lib/configobj.py", line 1318, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1078.
2020-05-06 22:03:49 ERROR    WEBSERVER-CONFIGGENERAL :: [6515b3a] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickchill/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
  File "/opt/sickchill/sickchill/views/config/general.py", line 219, in saveGeneral
    sickbeard.save_config()
  File "/opt/sickchill/sickbeard/__init__.py", line 1781, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
  File "/opt/sickchill/lib/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/sickchill/lib/configobj.py", line 1318, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1078.
Traceback (most recent call last):
  File "/opt/sickchill/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
  File "/opt/sickchill/sickchill/views/config/general.py", line 219, in saveGeneral
    sickbeard.save_config()
  File "/opt/sickchill/sickbeard/__init__.py", line 1781, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
  File "/opt/sickchill/lib/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/sickchill/lib/configobj.py", line 1318, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1078.
2020-05-06 22:03:49 ERROR    Uncaught exception POST /config/general/saveGeneral (192.168.1.219)
HTTPServerRequest(protocol=u'http', host='192.168.1.169:8081', method='POST', uri='/config/general/saveGeneral', version='HTTP/1.1', remote_ip='192.168.1.219', headers={'Origin': 'http://192.168.1.169:8081', 'Content-Length': '957', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.169:8081', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.1.169:8081/config/general/', 'Cookie': 'snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; wanted_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; advanced_toggle_checked=1; sickchill_user="2|1:0|10:1586625493|14:sickchill_user|44:NjliOTk5NDIxZTc5MGUzYTE5MDRiMjAzNGI5ZDA4YTM=|ac2acdddff4837aa33b62e83f87068936a20c8e71fb04d9f7960936f553496ca"; Auth-Type=http; Auth-Token=MPOfuHK3SPMmsjRXQ4L4dBj6hPjkBvnnkaAMPkOH9A2zRTwH', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
Traceback (most recent call last):
  File "/opt/sickchill/lib/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/sickchill/lib/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/sickchill/lib/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/sickchill/sickchill/views/index.py", line 194, in get
    results = yield self.async_call(method)
  File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/sickchill/lib/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/opt/sickchill/lib/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/sickchill/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
File "/opt/sickchill/sickchill/views/config/general.py", line 219, in saveGeneral
    sickbeard.save_config()
  File "/opt/sickchill/sickbeard/__init__.py", line 1781, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
  File "/opt/sickchill/lib/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/sickchill/lib/configobj.py", line 1318, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1078.
2020-05-06 22:03:49 ERROR    Uncaught exception POST /config/general/saveGeneral (192.168.1.219)
HTTPServerRequest(protocol=u'http', host='192.168.1.169:8081', method='POST', uri='/config/general/saveGeneral', version='HTTP/1.1', remote_ip='192.168.1.219', headers={'Origin': 'http://192.168.1.169:8081', 'Content-Length': '957', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.169:8081', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.1.169:8081/config/general/', 'Cookie': 'snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; wanted_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; advanced_toggle_checked=1; sickchill_user="2|1:0|10:1586625493|14:sickchill_user|44:NjliOTk5NDIxZTc5MGUzYTE5MDRiMjAzNGI5ZDA4YTM=|ac2acdddff4837aa33b62e83f87068936a20c8e71fb04d9f7960936f553496ca"; Auth-Type=http; Auth-Token=MPOfuHK3SPMmsjRXQ4L4dBj6hPjkBvnnkaAMPkOH9A2zRTwH', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
Traceback (most recent call last):
  File "/opt/sickchill/lib/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
value = future.result()
  File "/opt/sickchill/lib/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/sickchill/lib/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/sickchill/sickchill/views/index.py", line 194, in get
    results = yield self.async_call(method)
  File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/sickchill/lib/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/opt/sickchill/lib/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/sickchill/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
  File "/opt/sickchill/sickchill/views/config/general.py", line 219, in saveGeneral
    sickbeard.save_config()
  File "/opt/sickchill/sickbeard/__init__.py", line 1781, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
  File "/opt/sickchill/lib/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/sickchill/lib/configobj.py", line 1318, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1078.
2020-05-06 22:03:49 ERROR    WEBSERVER-CONFIGGENERAL :: [6515b3a] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickchill/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
File "/opt/sickchill/sickchill/views/config/general.py", line 219, in saveGeneral
    sickbeard.save_config()
  File "/opt/sickchill/sickbeard/__init__.py", line 1781, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
  File "/opt/sickchill/lib/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/sickchill/lib/configobj.py", line 1318, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1078.
2020-05-06 22:03:49 ERROR    Uncaught exception POST /config/general/saveGeneral (192.168.1.219)
HTTPServerRequest(protocol=u'http', host='192.168.1.169:8081', method='POST', uri='/config/general/saveGeneral', version='HTTP/1.1', remote_ip='192.168.1.219', headers={'Origin': 'http://192.168.1.169:8081', 'Content-Length': '957', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.169:8081', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.1.169:8081/config/general/', 'Cookie': 'snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; wanted_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; advanced_toggle_checked=1; sickchill_user="2|1:0|10:1586625493|14:sickchill_user|44:NjliOTk5NDIxZTc5MGUzYTE5MDRiMjAzNGI5ZDA4YTM=|ac2acdddff4837aa33b62e83f87068936a20c8e71fb04d9f7960936f553496ca"; Auth-Type=http; Auth-Token=MPOfuHK3SPMmsjRXQ4L4dBj6hPjkBvnnkaAMPkOH9A2zRTwH', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
Traceback (most recent call last):
  File "/opt/sickchill/lib/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
    value = future.result()
File "/opt/sickchill/sickchill/views/config/general.py", line 219, in saveGeneral
    sickbeard.save_config()
  File "/opt/sickchill/sickbeard/__init__.py", line 1781, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
  File "/opt/sickchill/lib/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/sickchill/lib/configobj.py", line 1318, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1078.
2020-05-06 22:03:49 ERROR    Uncaught exception POST /config/general/saveGeneral (192.168.1.219)
HTTPServerRequest(protocol=u'http', host='192.168.1.169:8081', method='POST', uri='/config/general/saveGeneral', version='HTTP/1.1', remote_ip='192.168.1.219', headers={'Origin': 'http://192.168.1.169:8081', 'Content-Length': '957', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.169:8081', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.1.169:8081/config/general/', 'Cookie': 'snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; wanted_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; advanced_toggle_checked=1; sickchill_user="2|1:0|10:1586625493|14:sickchill_user|44:NjliOTk5NDIxZTc5MGUzYTE5MDRiMjAzNGI5ZDA4YTM=|ac2acdddff4837aa33b62e83f87068936a20c8e71fb04d9f7960936f553496ca"; Auth-Type=http; Auth-Token=MPOfuHK3SPMmsjRXQ4L4dBj6hPjkBvnnkaAMPkOH9A2zRTwH', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
Traceback (most recent call last):
  File "/opt/sickchill/lib/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
    value = future.result()
 File "/opt/sickchill/lib/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/sickchill/lib/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/sickchill/sickchill/views/index.py", line 194, in get
    results = yield self.async_call(method)
  File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/sickchill/lib/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/opt/sickchill/lib/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/sickchill/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
  File "/opt/sickchill/sickchill/views/config/general.py", line 219, in saveGeneral
    sickbeard.save_config()
  File "/opt/sickchill/sickbeard/__init__.py", line 1781, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
  File "/opt/sickchill/lib/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/sickchill/lib/configobj.py", line 1318, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1078.
2020-05-06 22:03:49 ERROR    WEBSERVER-CONFIGGENERAL :: [6515b3a] Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickchill/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
  File "/opt/sickchill/sickchill/views/config/general.py", line 219, in saveGeneral
    sickbeard.save_config()
  File "/opt/sickchill/sickbeard/__init__.py", line 1781, in save_config
   new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
  File "/opt/sickchill/lib/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/sickchill/lib/configobj.py", line 1318, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1078.
2020-05-06 22:03:49 ERROR    Uncaught exception POST /config/general/saveGeneral (192.168.1.219)
HTTPServerRequest(protocol=u'http', host='192.168.1.169:8081', method='POST', uri='/config/general/saveGeneral', version='HTTP/1.1', remote_ip='192.168.1.219', headers={'Origin': 'http://192.168.1.169:8081', 'Content-Length': '957', 'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.169:8081', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.1.169:8081/config/general/', 'Cookie': 'snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; wanted_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; advanced_toggle_checked=1; sickchill_user="2|1:0|10:1586625493|14:sickchill_user|44:NjliOTk5NDIxZTc5MGUzYTE5MDRiMjAzNGI5ZDA4YTM=|ac2acdddff4837aa33b62e83f87068936a20c8e71fb04d9f7960936f553496ca"; Auth-Type=http; Auth-Token=MPOfuHK3SPMmsjRXQ4L4dBj6hPjkBvnnkaAMPkOH9A2zRTwH', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
Traceback (most recent call last):
  File "/opt/sickchill/lib/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/sickchill/lib/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/sickchill/lib/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/sickchill/lib/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/sickchill/sickchill/views/index.py", line 194, in get
    results = yield self.async_call(method)
  File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/sickchill/lib/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/opt/sickchill/lib/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/sickchill/sickchill/views/index.py", line 216, in async_call
    result = function(**kwargs)
  File "/opt/sickchill/sickchill/views/config/general.py", line 219, in saveGeneral
    sickbeard.save_config()
  File "/opt/sickchill/sickbeard/__init__.py", line 1781, in save_config
    new_config = ConfigObj(CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
  File "/opt/sickchill/lib/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/sickchill/lib/configobj.py", line 1318, in _load
    raise error
ConfigObjError: Parsing failed with several errors.
First error at line 1078.
2020-05-06 22:05:15 ERROR    Uncaught exception GET /favicon.ico (192.168.1.219)
HTTPServerRequest(protocol=u'http', host='192.168.1.169:8081', method='GET', uri='/favicon.ico', version='HTTP/1.1', remote_ip='192.168.1.219', headers={'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.169:8081', 'Accept': 'image/webp,image/apng,image/*,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://192.168.1.169:8081/home/searchEpisode?show=289574&season=5&episode=128', 'Cookie': 'snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; wanted_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; advanced_toggle_checked=1; sickchill_user="2|1:0|10:1586625493|14:sickchill_user|44:NjliOTk5NDIxZTc5MGUzYTE5MDRiMjAzNGI5ZDA4YTM=|ac2acdddff4837aa33b62e83f87068936a20c8e71fb04d9f7960936f553496ca"; Auth-Type=http; Auth-Token=MPOfuHK3SPMmsjRXQ4L4dBj6hPjkBvnnkaAMPkOH9A2zRTwH'})
Traceback (most recent call last):
  File "/opt/sickchill/lib/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/opt/sickchill/lib/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/sickchill/lib/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/opt/sickchill/lib/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
TypeError: get() takes at least 2 arguments (1 given)


```

**Comment by miigotu** [comment]
Looks like you broke your config.ini.

**Comment by AP-Engineering** [comment]
In what way is the config.ini broke? After updating via the web interface, sickchill service would no longer start and the web interface no longer works. Any suggestions on how to help with this issue would be appreciated

**Comment by AP-Engineering** [comment]
when checking the service the following message is displayed:

● sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-05-08 10:17:18 PDT; 22h ago

May 08 10:17:18 raspberrypi python2.7[445]:     sickbeard.CFG = ConfigObj(sickbeard.CONFIG_FILE, encoding='UTF-8', options={'indent_type': '  '})
May 08 10:17:18 raspberrypi python2.7[445]:   File "/opt/sickchill/lib/configobj.py", line 1229, in __init__
May 08 10:17:18 raspberrypi python2.7[445]:     self._load(infile, configspec)
May 08 10:17:18 raspberrypi python2.7[445]:   File "/opt/sickchill/lib/configobj.py", line 1318, in _load
May 08 10:17:18 raspberrypi python2.7[445]:     raise error
May 08 10:17:18 raspberrypi python2.7[445]: configobj.ConfigObjError: Parsing failed with several errors.
May 08 10:17:18 raspberrypi python2.7[445]: First error at line 1078.
May 08 10:17:18 raspberrypi systemd[1]: sickchill.service: Control process exited, code=exited, status=1/FAILURE
May 08 10:17:18 raspberrypi systemd[1]: sickchill.service: Failed with result 'exit-code'.
May 08 10:17:18 raspberrypi systemd[1]: Failed to start SickChill Daemon.

**Comment by AP-Engineering** [comment]
Solved --
Restored config.ini from old config.ini.bak to get web interface to work again
Then restored from backup file to bring it all back.
