### ISSUE TITLE
https notification for emby

### ISSUE THREAD

**Issue by mabelisle** [SickChill/SickChill#6418]
Branch/Commit: v2020.05.08-4
OS: OSX
Browser: Firefox
What you did: Tried https notifications for emby
What happened: Not working
What you expected: N/A
Logs:
```
2020-05-09 19:31:14 WARNING  WEBSERVER-HOME :: EMBY: Warning: Couldn't contact Emby at http://emby.xxxxxx.com/emby/Notifications/Admin
```

[https://github.com/SickChill/SickChill/blob/e9ccfe43f7515ddcacb872f3dc679694ad707481/sickbeard/notifiers/emby.py#L55-L60](https://github.com/SickChill/SickChill/blob/e9ccfe43f7515ddcacb872f3dc679694ad707481/sickbeard/notifiers/emby.py#L55-L60)

I think you just forgot the 's' in 'https'. I would also hard code it like the http line. I tried the "!" too and it returns all sorts of errors. I don't think it likes the "//" in the url.
```
elif host.startswith('https'):
    url = 'https://{0}/emby/Notifications/Admin'.format(host)
else:
    url = 'http://{0}/emby/Notifications/Admin'.format(host)
```

**Comment by mabelisle** [comment]
That's what I get with the `!https://emby.xxxxx.com/emby/Notifications/Admin`

```AA ValueError: unknown url type: https
AA raise ValueError, "unknown url type: %s" % self.__original
AA File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
AA protocol = req.get_type()
AA File "/usr/lib/python2.7/urllib2.py", line 421, in open
AA return opener.open(url, data, timeout)
AA File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
AA response = urllib.request.urlopen(req)
AA File "/app/sickchill/sickbeard/notifiers/emby.py", line 68, in _notify_emby
AA return self._notify_emby('This is a test notification from SickChill', host, emby_apikey)
AA File "/app/sickchill/sickbeard/notifiers/emby.py", line 85, in test_notify
AA result = notifiers.emby_notifier.test_notify(unquote_plus(host), emby_apikey)
AA File "/app/sickchill/sickchill/views/home.py", line 453, in testEMBY
AA result = function(**kwargs)
AA File "/app/sickchill/sickchill/views/index.py", line 216, in async_call
AA result = self.fn(*self.args, **self.kwargs)
AA File "/app/sickchill/lib/concurrent/futures/thread.py", line 63, in run
AA return self.__get_result()
AA File "/app/sickchill/lib/concurrent/futures/_base.py", line 455, in result
AA value = future.result()
AA File "/app/sickchill/lib/tornado/gen.py", line 1055, in run
AA results = yield self.async_call(method)
AA File "/app/sickchill/sickchill/views/index.py", line 194, in get
AA yielded = self.gen.throw(*exc_info)
AA File "/app/sickchill/lib/tornado/gen.py", line 1063, in run
AA raise_exc_info(self._exc_info)
AA File "/app/sickchill/lib/tornado/concurrent.py", line 238, in result
AA value = future.result()
AA File "/app/sickchill/lib/tornado/gen.py", line 1055, in run
AA result = yield result
AA File "/app/sickchill/lib/tornado/web.py", line 1512, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol=u'http', host='sickchill.xxxxxx.com', method='GET', uri='/home/testEMBY?host=!https%3A%2F%2Femby.xxxxxxx.com%2Femby%2FNotifications%2FAdmin&emby_apikey=16e197a8d889420dae126200d03a2bfc', version='HTTP/1.1', remote_ip='10.0.X.X', headers={'Te': 'trailers', 'Accept-Language': 'en-CA,en-US;q=0.7,en;q=0.3', 'Accept-Encoding': 'gzip, deflate, br', 'X-Forwarded-Host': 'sickchill.xxxxxx.com', 'X-Forwarded-Port': '443', 'X-Forwarded-For': '192.168.X.XXX', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0', 'Host': 'sickchill.xxxxxxx.com', 'X-Forwarded-Proto': 'https', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'https://sickchill.xxxxxxx.com/config/notifications/', 'X-Real-Ip': '192.168.X.XXX', 'Cookie': 'experimentation_subject_id=IjAzOGI0MDUxLTIwM2ItNGZhZi05YjdjLWRhZmRmOTZkMjAxOSI%3D--3d889082b82a063ef89be7657130aad5c6d8aaa8; sickchill_user="2|1:0|10:1588794598|14:sickchill_user|44:Y2NmYWRlM2FjNjcyNDczMTdjNGQwN2ZiZTg5MDY3NTQ=|82302391070db8cf4cca56ea1e120ea8cc5e7613d507e38f42a8878a79056132"', 'X-Forwarded-Server': '6e3ecd9e511b'})
AA 2020-05-10 10:03:21 ERROR    Uncaught exception GET /home/testEMBY?host=!https%3A%2F%2Femby.xxxxxxx.com%2Femby%2FNotifications%2FAdmin&emby_apikey=16e197a8d889420dae126200d03a2bfc (10.0.X.X)
AA ValueError: unknown url type: https
AA raise ValueError, "unknown url type: %s" % self.__original
AA File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
AA protocol = req.get_type()
AA File "/usr/lib/python2.7/urllib2.py", line 421, in open
AA return opener.open(url, data, timeout)
AA File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
AA response = urllib.request.urlopen(req)
AA File "/app/sickchill/sickbeard/notifiers/emby.py", line 68, in _notify_emby
AA return self._notify_emby('This is a test notification from SickChill', host, emby_apikey)
AA File "/app/sickchill/sickbeard/notifiers/emby.py", line 85, in test_notify
AA result = notifiers.emby_notifier.test_notify(unquote_plus(host), emby_apikey)
AA File "/app/sickchill/sickchill/views/home.py", line 453, in testEMBY
AA result = function(**kwargs)
AA File "/app/sickchill/sickchill/views/index.py", line 216, in async_call
AA Traceback (most recent call last):
AA ValueError: unknown url type: https
AA raise ValueError, "unknown url type: %s" % self.__original
AA File "/usr/lib/python2.7/urllib2.py", line 283, in get_type
AA protocol = req.get_type()
AA File "/usr/lib/python2.7/urllib2.py", line 421, in open
AA return opener.open(url, data, timeout)
AA File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
AA response = urllib.request.urlopen(req)
AA File "/app/sickchill/sickbeard/notifiers/emby.py", line 68, in _notify_emby
AA return self._notify_emby('This is a test notification from SickChill', host, emby_apikey)
AA File "/app/sickchill/sickbeard/notifiers/emby.py", line 85, in test_notify
AA result = notifiers.emby_notifier.test_notify(unquote_plus(host), emby_apikey)
AA File "/app/sickchill/sickchill/views/home.py", line 453, in testEMBY
AA result = function(**kwargs)
AA File "/app/sickchill/sickchill/views/index.py", line 216, in async_call
2020-05-10 10:03:21 ERROR    WEBSERVER-HOME :: [e9ccfe4] Failed doing webui callback: Traceback (most recent call last):```

**Comment by miigotu** [comment]
I'll take a look later.
