### ISSUE TITLE
Login screen not working anymore http 500 error after last commit

### ISSUE THREAD

**Issue by spoelly** [SickChill/SickChill#6441]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / latest
OS: Synology DSM
Browser: all
What you did: go to the site and want to login
What happened: http 500 error "Page does not work currently"
What you expected: login screen. 
Logs:
```
2020-05-15 15:26:12 ERROR    Uncaught exception GET /login/?next=%2F (192.168.2.90)
HTTPServerRequest(protocol=u'http', host='192.168.2.3:8899', method='GET', uri='/login/?next=%2F', version='HTTP/1.1', remote_ip='192.168.2.90')
Traceback (most recent call last):
  File "/volume1/@appstore/sickchill/var/SickBeard/lib/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)

```

**Comment by Guesch** [comment]
Just to say that I have the exact same issue with the same system.

**Comment by spoelly** [comment]
See an error in the log on my Iphone.. which still has a session.. but can't get it copied and pasted here.

**Comment by ronrosenfeld** [comment]
@spoelly  To copy the log, if you can log into your Synology, navigate to a folder `../sickchill/config/Logs/` and you should find the current `sickchill.log` file.  You can then download and copy the relevant portion of the log folder as text.

**Comment by Guesch** [comment]
Here is mine in case it helps:
2020-05-15 14:05:17 ERROR    Uncaught exception GET /login/?next=%2F (PUBLIC IP REDACTED)
HTTPServerRequest(protocol=u'http', host='*********.fr:8083', method='GET', uri='/login/?next=%2F', version='HTTP/1.1', remote_ip='PUBLIC IP REDACTED')
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
2020-05-15 14:05:23 ERROR    Uncaught exception GET /login/?next=%2F (PUBLIC IP REDACTED)
HTTPServerRequest(protocol=u'http', host='*********.fr:8083', method='GET', uri='/login/?next=%2F', version='HTTP/1.1', remote_ip='PUBLIC IP REDACTED')
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
2020-05-15 14:05:23 ERROR    Uncaught exception GET /login/?next=%2F (PUBLIC IP REDACTED)
HTTPServerRequest(protocol=u'http', host='*********.fr:8083', method='GET', uri='/login/?next=%2F', version='HTTP/1.1', remote_ip='PUBLIC IP REDACTED')
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
2020-05-15 14:05:24 ERROR    Uncaught exception GET /login/?next=%2F (PUBLIC IP REDACTED)
HTTPServerRequest(protocol=u'http', host='*********.fr:8083', method='GET', uri='/login/?next=%2F', version='HTTP/1.1', remote_ip='PUBLIC IP REDACTED')
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
2020-05-15 14:05:24 ERROR    Uncaught exception GET /login/?next=%2F (PUBLIC IP REDACTED)
HTTPServerRequest(protocol=u'http', host='*********.fr:8083', method='GET', uri='/login/?next=%2F', version='HTTP/1.1', remote_ip='PUBLIC IP REDACTED')
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
2020-05-15 14:06:22 ERROR    Uncaught exception GET /login/?next=%2F (PUBLIC IP REDACTED)
HTTPServerRequest(protocol=u'http', host='*********.fr:8083', method='GET', uri='/login/?next=%2F', version='HTTP/1.1', remote_ip='PUBLIC IP REDACTED')
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
2020-05-15 14:06:27 ERROR    Uncaught exception GET /login/ (PUBLIC IP REDACTED)
HTTPServerRequest(protocol=u'http', host='*********.fr:8083', method='GET', uri='/login/', version='HTTP/1.1', remote_ip='PUBLIC IP REDACTED')
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
2020-05-15 14:06:28 ERROR    Uncaught exception GET /login/ (PUBLIC IP REDACTED)
HTTPServerRequest(protocol=u'http', host='*********.fr:8083', method='GET', uri='/login/', version='HTTP/1.1', remote_ip='PUBLIC IP REDACTED')
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
2020-05-15 14:06:40 ERROR    Uncaught exception GET /login/ (192.168.0.22)
HTTPServerRequest(protocol=u'http', host='192.168.0.1:8083', method='GET', uri='/login/', version='HTTP/1.1', remote_ip='192.168.0.22')
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
2020-05-15 14:06:44 ERROR    Uncaught exception GET /login/ (192.168.0.22)
HTTPServerRequest(protocol=u'http', host='192.168.0.1:8083', method='GET', uri='/login/', version='HTTP/1.1', remote_ip='192.168.0.22')
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)
2020-05-15 14:06:47 ERROR    Uncaught exception GET /login/?next=%2F (192.168.0.22)
HTTPServerRequest(protocol=u'http', host='192.168.0.1:8083', method='GET', uri='/login/?next=%2F', version='HTTP/1.1', remote_ip='192.168.0.22')
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() takes exactly 1 argument (2 given)

**Comment by primer55** [comment]
Getting the same issue here on Windows after the update.

**Comment by miigotu** [comment]
Will push a fix soon

**Comment by Guesch** [comment]
How does one update his version when he doesn't have access to the GUI? :(

**Comment by ronrosenfeld** [comment]
@Guesch  Depends on the OS.  I've seen, and used, instructions for Windows and for Docker running on a Synology NAS (Linux OS).

**Comment by Guesch** [comment]
@ronrosenfeld I'm using Synology but unfortunately which doesn't support Docker.. so installed it as a package.
By any chance would you happen to have a link that would provide the commands I could use while SSHing into my NAS?

Appreciated!

**Comment by ronrosenfeld** [comment]
I have a Synology also but I run docker on it. It is an app published by Synology I think. I don't know how you would update your sick chill app from the command line. But can't you open the app store and select update next to the package, as you can with other apps? I would try that first.On May 17, 2020 8:34 AM, Guesch <notifications@github.com> wrote:
@ronrosenfeld I'm using Synology but unfortunately which doesn't support Docker.. so installed it as a package.
By any chance would you happen to have a link that would provide the commands I could use while SSHing into my NAS?
Appreciated!

**Comment by Guesch** [comment]
Unfortunately the package installed is actually "Sickbeard-custom" which
allows us to install different forks of the sickbeard projects.. Sickchill
being one of them.. So update through package center is only if
"Sickbeard-custom" is getting updated..
I will try to check if I can find the config file and verify that I
activated the auto update.. Otherwise I think I will be forced to
re-install, which would be a pity :(

**Comment by ronrosenfeld** [comment]
I think if you save and then restore your config folder, it may not be too painful.On May 17, 2020 8:54 AM, Guesch <notifications@github.com> wrote:

Unfortunately the package installed is actually "Sickbeard-custom" which

allows us to install different forks of the sickbeard projects.. Sickchill

being one of them.. So update through package center is only if

"Sickbeard-custom" is getting updated..

I will try to check if I can find the config file and verify that I

activated the auto update.. Otherwise I think I will be forced to

re-install, which would be a pity :(



On Sun, May 17, 2020 at 2:20 PM ronrosenfeld <notifications@github.com>

wrote:

**Comment by miigotu** [comment]
Stop SC, edit your config.ini and change web_username and web_password to empty and start it up, update, then set your username and password again.
