### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by vicks619** [SickChill/SickChill#6445]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: readynas
Browser:brave
What you did:tried updating sickchill
What happened: error and not updating
What you expected: sickchill to update sucessfully
Logs:
```Log File

2020-05-16 14:09:06 INFO WEBSERVER-HOME :: Downloading update from http://github.com/SickChill/SickChill/tarball/master 
2020-05-16 14:09:06 INFO WEBSERVER-HOME :: Creating update folder /apps/sickchill/sr-update before extracting 
2020-05-16 14:09:06 INFO WEBSERVER-HOME :: Clearing out update folder /apps/sickchill/sr-update before extracting 
2020-05-16 14:08:59 INFO WEBSERVER-HOME :: Config backup successful, updating... AA IOError: CRC check failed 0xd34fc540L != 0xa6146223L AA hex(self.crc))) AA File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof AA self._read_eof() AA File "/usr/lib/python2.7/gzip.py", line 315, in _read AA self._read(readsize) AA File "/usr/lib/python2.7/gzip.py", line 268, in read AA return self.fileobj.read(size) AA File "/usr/lib/python2.7/tarfile.py", line 751, in readnormal AA return self.readnormal(size) AA File "/usr/lib/python2.7/tarfile.py", line 742, in read AA buf += self.fileobj.read(size - len(buf)) AA File "/usr/lib/python2.7/tarfile.py", line 824, in read AA buf = fsrc.read(length) AA File "/usr/lib/python2.7/shutil.py", line 49, in copyfileobj AA return copyfileobj_orig(fsrc, fdst, length) AA File "/apps/sickchill/sickbeard/helpers.py", line 111, in _copyfileobj AA shutil.copyfileobj(src, dst) AA File "/usr/lib/python2.7/tarfile.py", line 265, in copyfileobj AA copyfileobj(source, target) AA File "/usr/lib/python2.7/tarfile.py", line 2224, in makefile AA self.makefile(tarinfo, targetpath) AA File "/usr/lib/python2.7/tarfile.py", line 2183, in _extract_member AA self._extract_member(tarinfo, os.path.join(path, tarinfo.name)) AA File "/usr/lib/python2.7/tarfile.py", line 2107, in extract AA self.extract(tarinfo, path) AA File "/usr/lib/python2.7/tarfile.py", line 2070, in extractall AA tar.extractall(sr_update_dir) AA File "/apps/sickchill/sickbeard/versionChecker.py", line 840, in update AA Traceback (most recent call last): 
2020-05-16 14:08:13 ERROR WEBSERVER-HOME :: [1f1254c] Error while trying to update: CRC check failed 0xd34fc540L != 0xa6146223L 
2020-05-16 14:08:11 INFO WEBSERVER-HOME :: Extracting file /apps/sickchill/sr-update/sr-update.tar 
2020-05-16 14:08:11 WARNING WEBSERVER-HOME :: Problem downloading file, setting permissions or writing file to /apps/sickchill/sr-update/sr-update.tar - ERROR: ('Connection broken: IncompleteRead(766 bytes read, 258 more expected)', IncompleteRead(766 bytes read, 258 more expected)) 
2020-05-16 14:07:30 INFO WEBSERVER-HOME :: Config backup in progress... 
2020-05-16 14:05:59 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /data/Transmission/Downloads/Shows completed 
2020-05-16 14:05:59 INFO POSTPROCESSOR-AUTO :: Successfully processed 
2020-05-16 14:05:59 INFO POSTPROCESSOR-AUTO :: Processing /data/Transmission/Downloads/Shows 
2020-05-16 14:05:59 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /data/Transmission/Downloads/Shows 2020-05-16 14:05:57 INFO POSTPROCESSOR :: Auto post processing task for /data/Transmission/Downloads/Shows was added to the queue 
2020-05-16 14:02:44 INFO WEBSERVER-HOME :: Downloading update from http://github.com/SickChill/SickChill/tarball/master 
2020-05-16 14:02:44 INFO WEBSERVER-HOME :: Creating update folder /apps/sickchill/sr-update before extracting 
2020-05-16 14:02:44 INFO WEBSERVER-HOME :: Clearing out update folder /apps/sickchill/sr-update before extracting 
2020-05-16 14:02:37 INFO WEBSERVER-HOME :: Config backup successful, updating... AA IOError: CRC check failed 0x6a5c640d != 0xf4998ca4L AA hex(self.crc))) AA File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof AA self._read_eof() AA File "/usr/lib/python2.7/gzip.py", line 315, in _read AA self._read(readsize) AA File "/usr/lib/python2.7/gzip.py", line 268, in read AA return self.fileobj.read(size) AA File "/usr/lib/python2.7/tarfile.py", line 751, in readnormal AA return self.readnormal(size) AA File "/usr/lib/python2.7/tarfile.py", line 742, in read AA buf += self.fileobj.read(size - len(buf)) AA File "/usr/lib/python2.7/tarfile.py", line 824, in read AA buf = fsrc.read(length) AA File "/usr/lib/python2.7/shutil.py", line 49, in copyfileobj AA return copyfileobj_orig(fsrc, fdst, length) AA File "/apps/sickchill/sickbeard/helpers.py", line 111, in _copyfileobj AA shutil.copyfileobj(src, dst) AA File "/usr/lib/python2.7/tarfile.py", line 265, in copyfileobj AA copyfileobj(source, target) AA File "/usr/lib/python2.7/tarfile.py", line 2224, in makefile AA self.makefile(tarinfo, targetpath) AA File "/usr/lib/python2.7/tarfile.py", line 2183, in _extract_member AA self._extract_member(tarinfo, os.path.join(path, tarinfo.name)) AA File "/usr/lib/python2.7/tarfile.py", line 2107, in extract AA self.extract(tarinfo, path) AA File "/usr/lib/python2.7/tarfile.py", line 2070, in extractall AA tar.extractall(sr_update_dir) AA File "/apps/sickchill/sickbeard/versionChecker.py", line 840, in update AA Traceback (most recent call last): 
2020-05-16 14:02:33 ERROR WEBSERVER-HOME :: [1f1254c] Error while trying to update: CRC check failed 0x6a5c640d != 0xf4998ca4L 
2020-05-16 14:02:31 INFO WEBSERVER-HOME :: Extracting file /apps/sickchill/sr-update/sr-update.tar 
2020-05-16 14:02:31 WARNING WEBSERVER-HOME :: Problem downloading file, setting permissions or writing file to /apps/sickchill/sr-update/sr-update.tar - ERROR: ('Connection broken: IncompleteRead(95 bytes read, 929 more expected)', IncompleteRead(95 bytes read, 929 more expected)) 
2020-05-16 14:01:03 INFO WEBSERVER-HOME :: Config backup in progress... 
2020-05-16 14:00:02 INFO FINDSUBTITLES :: Finished checking for missed subtitles 
2020-05-16 14:00:02 INFO FINDSUBTITLES :: Checking for missed subtitles 
2020-05-16 13:55:59 INFO POSTPROCESSOR-AUTO :: Auto post processing task for /data/Transmission/Downloads/Shows completed 
2020-05-16 13:55:59 INFO POSTPROCESSOR-AUTO :: Successfully processed 
2020-05-16 13:55:59 INFO POSTPROCESSOR-AUTO :: Processing /data/Transmission/Downloads/Shows 
2020-05-16 13:55:59 INFO POSTPROCESSOR-AUTO :: Beginning auto post processing task: /data/Transmission/Downloads/Shows 
2020-05-16 13:55:56 INFO POSTPROCESSOR :: Auto post processing task for /data/Transmission/Downloads/Shows was added to the queue 
2020-05-16 13:55:06 INFO WEBSERVER-HOME :: Downloading update from http://github.com/SickChill/SickChill/tarball/master 
2020-05-16 13:55:06 INFO WEBSERVER-HOME :: Creating update folder /apps/sickchill/sr-update before extracting 
2020-05-16 13:55:00 INFO WEBSERVER-HOME :: Config backup successful, updating... 
2020-05-16 13:53:13 INFO WEBSERVER-HOME :: Config backup in progress... 
2020-05-16 13:50:01 INFO CHECKVERSION :: Checking for updates using SOURCE 
PASTE LOGS HERE
```2020-05-16 14:16:15 WEBSERVER-HOME :: [1f1254c] Error while trying to update: CRC check failed 0x6aa47254 != 0x54070a9L
2020-05-16 14:08:13 WEBSERVER-HOME :: [1f1254c] Error while trying to update: CRC check failed 0xd34fc540L != 0xa6146223L

**Comment by miigotu** [comment]
Make sure there is no file in `/apps/sickchill/sr-update/sr-update.tar`
If there is, open it with a text editor and see what it looks like. The update is not downloading for you correctly (not because of SC)

**Comment by vicks619** [comment]
Deleting sr-update folder and updating again solved the problem. Thanks for your reply
