### ISSUE TITLE
Not supporting Python 2.7.8?

### ISSUE THREAD

**Issue by alex-plunge** [SickChill/SickChill#6458]
Branch/Commit: Latest (May 20th 2020, but same issue 3 days ago)
OS: DLink ShareCenter
What you did: The daemon cannot be started
Logs:
```
/mnt/HD/HD_a2/Nas_Prog/python # DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.1j 15 Oct 2014) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "/mnt/HD/HD_a2/Sickrage/SickBeard.py", line 70, in <module>
    from sickchill.views.server_settings import SRWebServer
  File "/mnt/HD/HD_a2/Sickrage/sickchill/views/__init__.py", line 22, in <module>
    from .api import ApiCall, ApiHandler, function_mapper, KeyHandler
  File "/mnt/HD/HD_a2/Sickrage/sickchill/views/api/__init__.py", line 22, in <module>
    from .authentication import KeyHandler
  File "/mnt/HD/HD_a2/Sickrage/sickchill/views/api/authentication.py", line 25, in <module>
    from tornado.web import RequestHandler
  File "/mnt/HD/HD_a2/Sickrage/lib/tornado/web.py", line 89, in <module>
    from tornado import iostream
  File "/mnt/HD/HD_a2/Sickrage/lib/tornado/iostream.py", line 41, in <module>
    from tornado.netutil import ssl_wrap_socket, _client_ssl_defaults, _server_ssl_defaults
  File "/mnt/HD/HD_a2/Sickrage/lib/tornado/netutil.py", line 44, in <module>
    _client_ssl_defaults = ssl.create_default_context(
AttributeError: 'module' object has no attribute 'create_default_context'
```
Since I am running Python 2.7.8, and cannot be updated easily (it is an embedded Linux without make or pip for instance), I am wondering if there is anything related to it

TIA

**Comment by joshbaptiste** [comment]
Minimum version to run SickCHill is 2.7.10 and that's probably one of the reasons why.. create_default_context() was added in 2.7.9

**Comment by miigotu** [comment]
You could always use pyenv or virtualenv.

**Comment by miigotu** [comment]
It will run on 2.7.9, readme specifies 2.7.10+, but 2.7.17+ is recommended.
