### ISSUE TITLE
"API Key Required" when updating show from TVDB

### ISSUE THREAD

**Issue by gniting** [SickChill/SickChill#6482]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / 9d460f97f2c3ac8f6d075ea33267f1de6bb959db
OS: Linux-5.3.0-55-generic-x86_64-with-Ubuntu-19.10-eoan
Browser: Brave (latest)
What you did: Force updated a show
What happened: Got an error that show info could not be updated
What you expected: The show to update
Logs:
```
AA AuthenticationError: API Key Required
AA raise AuthenticationError(error)
AA File "/opt/sickchill/lib/tvdbsimple/base.py", line 122, in get_token
AA self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
AA File "/opt/sickchill/lib/tvdbsimple/base.py", line 91, in _set_token_header
AA self._set_token_header(forceNewToken)
AA File "/opt/sickchill/lib/tvdbsimple/base.py", line 126, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "/opt/sickchill/lib/tvdbsimple/base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "/opt/sickchill/lib/tvdbsimple/base.py", line 149, in _GET
AA response = self._GET(path, params=filters, cleanJson=False)
AA File "/opt/sickchill/lib/tvdbsimple/series.py", line 244, in page
AA self.page(1)
AA File "/opt/sickchill/lib/tvdbsimple/series.py", line 201, in pages
AA for i in range (1, self.pages()+1):
AA File "/opt/sickchill/lib/tvdbsimple/series.py", line 222, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, airedEpisode=episode, language=show.lang, **kwargs).all()[0]
AA File "/opt/sickchill/sickchill/show/indexers/tvdb.py", line 113, in episode
AA result = target(*args, **kwargs)
AA File "/opt/sickchill/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA myEp = self.idxr.episode(self.show, season or self.season, episode or self.episode)
AA File "/opt/sickchill/sickbeard/tv.py", line 1549, in loadFromIndexer
AA show_episode.loadFromIndexer(*season_episode)
AA File "/opt/sickchill/sickbeard/tv.py", line 556, in loadEpisodesFromIndexer
AA IndexerEpList = self.show.loadEpisodesFromIndexer()
AA File "/opt/sickchill/sickbeard/show_queue.py", line 667, in run
AA Traceback (most recent call last):
2020-05-29 09:43:39 ERROR SHOWQUEUE-FORCE-UPDATE :: [9d460f9] Unable to get info from theTVDB, the show info will not be refreshed: API Key Required
```

This happens for any show I try and update. Nothing has changed from my end over the past several days. Sickchill updated itself yesterday to the latest commit, maybe that triggered this?

**Comment by gniting** [comment]
Updated Sickchill to the latest commit (d2c60105671645c41cb27e1909254370d1ebd839) and now seeing this error:
```2020-05-29 10:04:05 WARNING SHOWQUEUE-FORCE-UPDATE :: Unable to contact theTVDB, aborting: API Key Required```

**Comment by gniting** [comment]
Dig some more digging around. The issue was related to DNS resolution of api.thetvdb.com and not API key. Once I addressed the DNS issue, all went back to normal. Hopefully helps someone else.
