### ISSUE TITLE
Can't start in https since yesterday with lets encrypt certs

### ISSUE THREAD

**Issue by aurelien-joly** [SickChill/SickChill#6521]
Hi, having this issue on a synology install, the install hasn't been touched except for sickchill updates yesterday.

The certificates are in the app folder since early may and everything was working correctly. it looks like the app is trying and failing to create self signed certs ...

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/885488a9fbaeb592225320cad73c3dddecb3c5ad,
OS: synology
Browser: N/A
What you did: tried chmod 777 on certs, tried install pyopenssl from pip
What happened: ssl error at certificate creation ? fallback to http
What you expected: app started with https
Logs:
```
2020-06-08 22:22:57 INFO     MAIN :: Starting SickChill [master] using '/volume1/@appstore/sickbeard-custom/var/config.ini'
2020-06-08 22:22:57 INFO     MAIN :: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/helpers.py", line 806, in create_https_certificates
    from OpenSSL import crypto
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/lib/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
ImportError: cannot import name certificate_transparency

2020-06-08 22:22:57 WARNING  MAIN :: pyopenssl module missing, please install for https access
2020-06-08 22:22:57 INFO     MAIN :: Unable to create CERT/KEY files, disabling HTTPS
2020-06-08 22:22:57 WARNING  MAIN :: Disabled HTTPS because of missing CERT and KEY files
2020-06-08 22:22:57 INFO     WEBSERVER :: Starting SickChill on http://0.0.0.0:8899/
```
Tried installing pyopenssl, used the same python cmd that starts sickchill : 
```
/usr/local/sickbeard-custom/var/SickBeard# /volume1/@appstore/sickbeard-custom/env/bin/pip install pyopenssl
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: pyopenssl in /volume1/@appstore/python/lib/python2.7/site-packages (17.5.0)
Requirement already satisfied: six>=1.5.2 in /volume1/@appstore/python/lib/python2.7/site-packages (from pyopenssl) (1.11.0)
Requirement already satisfied: cryptography>=2.1.4 in /volume1/@appstore/python/lib/python2.7/site-packages (from pyopenssl) (2.1.4)
Requirement already satisfied: enum34; python_version < "3" in /volume1/@appstore/python/lib/python2.7/site-packages (from cryptography>=2.1.4->pyopenssl) (1.1.6)
Requirement already satisfied: asn1crypto>=0.21.0 in /volume1/@appstore/python/lib/python2.7/site-packages (from cryptography>=2.1.4->pyopenssl) (0.24.0)
Requirement already satisfied: idna>=2.1 in /volume1/@appstore/python/lib/python2.7/site-packages (from cryptography>=2.1.4->pyopenssl) (2.6)
Requirement already satisfied: ipaddress; python_version < "3" in /volume1/@appstore/python/lib/python2.7/site-packages (from cryptography>=2.1.4->pyopenssl) (1.0.19)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /volume1/@appstore/python/lib/python2.7/site-packages (from cryptography>=2.1.4->pyopenssl) (1.11.2)
Requirement already satisfied: pycparser in /volume1/@appstore/python/lib/python2.7/site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.1.4->pyopenssl) (2.18)
```

**Comment by miigotu** [comment]
Set your key/cert path to the path to the live letsencrypt cert/key. They no longer are required to be in the SC root.

**Comment by aurelien-joly** [comment]
Hi, 

did what you asked and after changing the permissions of the key/cert so that sickchill can read them, it works.

any reason that it doesn't work in SC root anymore ?

thanks

**Comment by miigotu** [comment]
Honestly, they should work in root now also, but maybe there is a mistake in my code.
