### ISSUE TITLE
[Bug] Anime Princess Connect! Re:Dive not being processed.

### ISSUE THREAD

**Issue by gbschenkel** [SickChill/SickChill#6563]
This show is not working, I have added it on SickChill from TheTVDB.com. The SickChill didn't download the files, than I have downloaded by myself, and have put in the auto processing folder, files are being "ignorated". Manual postprocessing not work too. Log too long, if the log is not satisfatory I will use just one file to get the all the log about it.

Version: v2020.07.06-1
Commit: b2cf429b
OS: Slackware 14.2-current 64Bits
Browser: Firefox 78.0.1esr 
What you did: Added the Show and downloaded all files externally of the anime. (The SickChill didn't downloaded the files)
What happened: Files are not been processed, appears the show can't be found (http://dereferer.org/?https://thetvdb.com/?tab=series&id=377034).
What you expected: SickChill was suppose to do his stuffs.
Logs:
```
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: Auto post processing task for /shared/Downloads completed
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 10 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 02 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 12 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 04 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 09 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 06 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 05 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 07 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 08 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 01 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 11 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 13 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 03 [1080p].mkv : Processing failed:
2020-07-07 16:53:15 INFO     POSTPROCESSOR-AUTO :: Some items were not processed.
2020-07-07 16:53:15 WARNING  POSTPROCESSOR-AUTO :: Processing Failed
2020-07-07 16:53:14 WARNING  POSTPROCESSOR-AUTO :: Processing failed for /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 10 [1080p].mkv:
2020-07-07 16:53:14 INFO     POSTPROCESSOR-AUTO :: This show isn't in your list, you need to add it to SR before post-processing an episode
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Unable to match Downloads [HorribleSubs] Princess Connect! Re Dive - 10 [1080p] to a show in your database. Parser result: Downloads [HorribleSubs] Princess Connect! Re Dive -  [ABS: [10]] [ANIME VER: 1] [ABD: False] [ANIME: True] [whichReg: [u'anime_standard']]
AA TypeError: expected string or buffer
AA return _compile(pattern, flags).match(string)
AA File "/usr/lib/python2.7/re.py", line 141, in match
AA test = re.match(r'^(.+?)[. -]+\(\d{4}\)?$', name)
AA File "/opt/sickchill/sickchill/show/indexers/tvdb.py", line 143, in search
AA result = target(*args, **kwargs)
AA File "/opt/sickchill/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA result = self._series(self.search(name, language)[0]['id'])
AA File "/opt/sickchill/sickchill/show/indexers/tvdb.py", line 87, in get_series_by_name
AA result = self.indexers[i].get_series_by_name(n, indexerid, language)
AA File "/opt/sickchill/sickchill/show/indexers/handler.py", line 137, in search_indexers_for_series_id
AA sickbeard.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "/opt/sickchill/sickbeard/helpers.py", line 1046, in get_show
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Traceback (most recent call last):
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Error when attempting to find show: Downloads [HorribleSubs] Princess Connect! Re Dive in SickChill. Error: expected string or buffer
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Trying to find [u'downloads [horriblesubs] princess connect re dive'] on theTVDB
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Analyzing name Downloads [HorribleSubs] Princess Connect! Re Dive - 10 [1080p].mkv
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Unable to match /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 10 [1080p] to a show in your database. Parser result: Princess Connect! Re Dive -  [ABS: [10]] [ANIME VER: 1] [GROUP: HorribleSubs] [ABD: False] [ANIME: True] [whichReg: [u'anime_horriblesubs']]
AA TypeError: expected string or buffer
AA return _compile(pattern, flags).match(string)
AA File "/usr/lib/python2.7/re.py", line 141, in match
AA test = re.match(r'^(.+?)[. -]+\(\d{4}\)?$', name)
AA File "/opt/sickchill/sickchill/show/indexers/tvdb.py", line 143, in search
AA result = target(*args, **kwargs)
AA File "/opt/sickchill/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA result = self._series(self.search(name, language)[0]['id'])
AA File "/opt/sickchill/sickchill/show/indexers/tvdb.py", line 87, in get_series_by_name
AA result = self.indexers[i].get_series_by_name(n, indexerid, language)
AA File "/opt/sickchill/sickchill/show/indexers/handler.py", line 137, in search_indexers_for_series_id
AA sickbeard.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "/opt/sickchill/sickbeard/helpers.py", line 1046, in get_show
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Traceback (most recent call last):
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Error when attempting to find show: Princess Connect! Re Dive in SickChill. Error: expected string or buffer
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Trying to find [u'princess connect re dive'] on theTVDB
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Analyzing name /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 10 [1080p].mkv
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Unable to match Downloads to a show in your database. Parser result:  [ABD: False] [ANIME: False] [whichReg: []]
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Analyzing name Downloads
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Unable to match [HorribleSubs] Princess Connect! Re Dive - 10 [1080p] to a show in your database. Parser result: Princess Connect! Re Dive -  [ABS: [10]] [ANIME VER: 1] [GROUP: HorribleSubs] [ABD: False] [ANIME: True] [whichReg: [u'anime_horriblesubs']]
AA TypeError: expected string or buffer
AA return _compile(pattern, flags).match(string)
AA File "/usr/lib/python2.7/re.py", line 141, in match
AA test = re.match(r'^(.+?)[. -]+\(\d{4}\)?$', name)
AA File "/opt/sickchill/sickchill/show/indexers/tvdb.py", line 143, in search
AA result = target(*args, **kwargs)
AA File "/opt/sickchill/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA result = self._series(self.search(name, language)[0]['id'])
AA File "/opt/sickchill/sickchill/show/indexers/tvdb.py", line 87, in get_series_by_name
AA result = self.indexers[i].get_series_by_name(n, indexerid, language)
AA File "/opt/sickchill/sickchill/show/indexers/handler.py", line 137, in search_indexers_for_series_id
AA sickbeard.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "/opt/sickchill/sickbeard/helpers.py", line 1046, in get_show
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Traceback (most recent call last):
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Error when attempting to find show: Princess Connect! Re Dive in SickChill. Error: expected string or buffer
2020-07-07 16:53:14 DEBUG    POSTPROCESSOR-AUTO :: Trying to find [u'princess connect re dive'] on theTVDB
2020-07-07 16:53:13 DEBUG    POSTPROCESSOR-AUTO :: Analyzing name [HorribleSubs] Princess Connect! Re Dive - 10 [1080p].mkv
2020-07-07 16:53:13 INFO     POSTPROCESSOR-AUTO :: Processing /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 10 [1080p].mkv (None)
2020-07-07 16:53:13 WARNING  POSTPROCESSOR-AUTO :: Processing failed for /shared/Downloads/[HorribleSubs] Princess Connect! Re Dive - 02 [1080p].mkv:
2020-07-07 16:53:13 INFO     POSTPROCESSOR-AUTO :: This show isn't in your list, you need to add it to SR before post-processing an episode
2020-07-07 16:53:13 DEBUG    POSTPROCESSOR-AUTO :: Unable to match Downloads [HorribleSubs] Princess Connect! Re Dive - 02 [1080p] to a show in your database. Parser result: Downloads [HorribleSubs] Princess Connect! Re Dive -  [ABS: [2]] [ANIME VER: 1] [ABD: False] [ANIME: True] [whichReg: [u'anime_standard']]
AA TypeError: expected string or buffer
AA return _compile(pattern, flags).match(string)
AA File "/usr/lib/python2.7/re.py", line 141, in match
AA test = re.match(r'^(.+?)[. -]+\(\d{4}\)?$', name)
AA File "/opt/sickchill/sickchill/show/indexers/tvdb.py", line 143, in search
AA result = target(*args, **kwargs)
AA File "/opt/sickchill/sickchill/show/indexers/wrappers.py", line 44, in wrapper
AA result = self._series(self.search(name, language)[0]['id'])
```

**Comment by consenti** [comment]
I've run into this problem before.  Especially shows that have invalid/special characters in the show name on TVDB. In your case, the show name from TVDB is "Princess Connect! Re:Dive".  From what I can see on the log, the files you are importing don't match that show name because your files are missing the colon and start instead with "Princess Connect! Re Dive". 

I would suggest adding a scene exception for the show.  You can do this by going to EDIT the show, then click the ADVANCED tab. Add "Princess Connect! Re Dive" without the quotes as a Show exception (not season exception).  

![image](https://user-images.githubusercontent.com/10899191/87175588-b5883000-c28d-11ea-9589-c867ffdeedb0.png)


Post processing and downloading should work correctly after you save these changes.

**Comment by gbschenkel** [comment]
> I've run into this problem before. Especially shows that have invalid/special characters in the show name on TVDB. In your case, the show name from TVDB is "Princess Connect! Re:Dive". From what I can see on the log, the files you are importing don't match that show name because your files are missing the colon and start instead with "Princess Connect! Re Dive".
> 
> I would suggest adding a scene exception for the show. You can do this by going to EDIT the show, then click the ADVANCED tab. Add "Princess Connect! Re Dive" without the quotes as a Show exception (not season exception).
> 
> ![image](https://user-images.githubusercontent.com/10899191/87175588-b5883000-c28d-11ea-9589-c867ffdeedb0.png)
> 
> Post processing and downloading should work correctly after you save these changes.

Thanks, didn't know that option, I was gonna say to put this info on Wiki, but I just checked before write this, the info already exist in there :P. Next time I will read all in there before submitting a issue.
