### ISSUE TITLE
CFFI version mismatch

### ISSUE THREAD

**Issue by mgaulton** [SickChill/SickChill#6599]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Opensuse Tumbleweed
Browser: Chrome
What you did: attempte4d to start SC after realizing it wasn't running
What happened: Error occurs for cffi version mismatch
What you expected: SC to start.
Logs:
```
Traceback (most recent call last):
  File "/opt/SickBeard-tvrage/SickBeard.py", line 67, in <module>
    import sickbeard
  File "/opt/SickBeard-tvrage/sickbeard/__init__.py", line 35, in <module>
    import rarfile
  File "/opt/SickBeard-tvrage/lib/rarfile.py", line 126, in <module>
    from Crypto.Cipher import AES
  File "/usr/local/lib64/python2.7/site-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/usr/local/lib64/python2.7/site-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/usr/local/lib64/python2.7/site-packages/Crypto/Util/_raw_api.py", line 86, in <module>
    ffi = FFI()
  File "/opt/SickBeard-tvrage/lib/cffi/api.py", line 56, in __init__
    backend.__version__, backend.__file__))
Exception: Version mismatch: this is the 'cffi' package version 1.14.0, located in '/opt/SickBeard-tvrage/lib/cffi/api.pyc'.  When we import the top-level '_cffi_backend' extension module, we get version 1.14.1, located in '/usr/local/lib64/python2.7/site-packages/_cffi_backend.so'.  The two versions should be equal; check your installation.
```

**Comment by mgaulton** [comment]
So I did manage to work around this by downgrading the package through pip "pip2 install cffi==1.14.0" and in the process discovered that Tumbleweed no longer offers a python-cffi package, only python3-cffi.

I'll have to go through an update cycle but this seems to have been an issue on my end, but not sure why it happened to start.

**Comment by miigotu** [comment]
Plus side, SickChill/SickChill@py3-again is all python3 =P
