### ISSUE TITLE
Sickchill not starting after installing Synology DSM 6.2.3-25426 Update 2

### ISSUE THREAD

**Issue by EvilHannie** [SickChill/SickChill#6605]
Branch/Commit:
OS:
Browser: doesnt matter - package service won't start
What you did:  update DSM to 6.2.3-25426 Update 2
What happened: sickbeard-custom not longer starting ; error unable to start package service ( translated from dutch )
What you expected:
Logs:
Sat Aug  1 19:38:41 CEST 2020
Starting sickbeard-custom command /volume1/@appstore/sickbeard-custom/env/bin/python /volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py --daemon --pidfile /volume1/@appstore/sickbeard-custom/var/sickbeard-custom.pid --config$
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2n  7 Dec 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected r$
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/SickBeard.py", line 67, in <module>
    import sickbeard
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/__init__.py", line 49, in <module>
    from . import (auto_postprocessor, clients, dailysearcher, db, helpers, image_cache, logger, metadata, naming, post_processing_queue, properFinder, providers,
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/__init__.py", line 29, in <module>
    from sickbeard.providers import (abnormal, alpharatio, archetorrent, binsearch, bitcannon, bjshare, btn, cpasbien, danishbits, demonoid, elitetorrent, filelist,
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickbeard/providers/abnormal.py", line 34, in <module>
    from sickchill.providers.torrent.TorrentProvider import TorrentProvider
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/sickchill/providers/torrent/TorrentProvider.py", line 25, in <module>
    from feedparser import FeedParserDict
ImportError: cannot import name FeedParserDict

**Comment by miigotu** [comment]
#6230
