### ISSUE TITLE
Still regarding issue: 6619 - Cannot import backup from version running on python 2.7

### ISSUE THREAD

**Issue by NunoHiggs** [SickChill/SickChill#6621]
Branch/Commit: master - installed via pip3 install sickchill -U sickchill
OS: linux
Browser: any
What you did: tried to restore zip form running version on py 2.7
What happened: The restore worked in the process.  Search providers loaded, but  not series or episodes.
What you expected: restore to work.
Logs:

[sickchill@lxcVpar18 bin]$ ./SickChill.py
Restore: restoring DB and config.ini SUCCESSFUL!
2020-08-09 18:04:07 INFO :: MAIN :: Restore: Unable to remove the cache/mako directory: [Errno 2] No such file or directory: '/home/sickchill/.local/lib/python3.7/site-packages/sickchill/gui/slick/cache/mako'
2020-08-09 18:04:07 DEBUG :: MAIN :: Found codec for 'Show Name: Ep Name'.
2020-08-09 18:04:07 DEBUG :: MAIN :: formatting pattern: Season %0S -> Season 02
2020-08-09 18:04:07 DEBUG :: MAIN :: Trying to parse Show Name - S02E03 - Ep Name.ext
2020-08-09 18:04:07 DEBUG :: MAIN :: Parsed Show Name - S02E03 - Ep Name.ext into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2020-08-09 18:04:07 DEBUG :: MAIN :: The name Show Name - S02E03 - Ep Name.ext parsed into Show Name - S02E03 [ABD: False] [ANIME: False] [whichReg: ['standard']]
2020-08-09 18:04:08 DEBUG :: MAIN :: Checking database structure...sickchill.db
2020-08-09 18:04:08 DEBUG :: MAIN :: Checking database structure...cache.db
2020-08-09 18:04:08 DEBUG :: MAIN :: Checking database structure...failed.db
2020-08-09 18:04:08 DEBUG :: MAIN :: Checking for shows with tvrage id's, since tvrage is gone
2020-08-09 18:04:08 DEBUG :: MAIN :: Checking for archived episodes not qualified
2020-08-09 18:04:08 DEBUG :: MAIN :: Retrieving the last check time from the DB
2020-08-09 18:04:08 DEBUG :: MAIN :: Loading initial show list

After the restore from backup, it is even worst now. The series are not found.

Also, in the logs, the warning appears to be related to my proxy, but it is working.

2020-08-09 18:04:08 DEBUG :: MAIN :: Using global proxy: 172.16.3.252:33128
Traceback (most recent call last):
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1285, in handle_requests_exception
    raise requests_exception
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1219, in getURL
    headers=headers, cookies=cookies, proxies=proxies, verify=verify
  File "/home/sickchill/.local/lib/python3.7/site-packages/cloudscraper/__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/cloudscraper/__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/cachecontrol/adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/adapters.py", line 199, in proxy_manager_for
    **proxy_kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 492, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "/home/sickchill/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 429, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sickchill/.local/bin/SickChill.py", line 464, in <module>
    SickChill().start()
  File "/home/sickchill/.local/bin/SickChill.py", line 216, in start
    name_cache.buildNameCache()
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/name_cache.py", line 68, in buildNameCache
    scene_exceptions.retrieve_exceptions()
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/scene_exceptions.py", line 216, in retrieve_exceptions
    _xem_exceptions_fetcher()
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/scene_exceptions.py", line 300, in _xem_exceptions_fetcher
    parsed_json = helpers.getURL(url, session=xem_session, timeout=90, returns='json')
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1224, in getURL
    handle_requests_exception(error)
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1329, in handle_requests_exception
    level = get_level(error)
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1281, in get_level
    return (logger.ERROR, logger.WARNING)[exception and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception]
TypeError: argument of type 'ProxySchemeUnknown' is not iterable
2020-08-09 18:04:09 DEBUG :: CHECKVERSION :: cur_commit = 99336df163c7e776c7931d864e84d1f0f83afe4d, newest_commit = 99336df163c7e776c7931d864e84d1f0f83afe4d, num_commits_behind = 0
2020-08-09 18:04:09 DEBUG :: CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2020-08-09 18:04:09 DEBUG :: CHECKVERSION :: Using global proxy: 172.16.3.252:33128
2020-08-09 18:04:09 WARNING :: CHECKVERSION :: check_for_new_news: Could not load news from repo.
2020-08-09 18:04:32 ERROR :: WEBSERVER :: Uncaught exception GET /favicon.ico (172.16.0.10)
HTTPServerRequest(protocol='http', host='lxcvpar18.net.xpto:8081', method='GET', uri='/favicon.ico', version='HTTP/1.1', remote_ip='172.16.0.10')
Traceback (most recent call last):
  File "/home/sickchill/.local/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
TypeError: get() missing 1 required positional argument: 'path'
2020-08-09 18:05:45 DEBUG :: WEBSERVER-CONFIGPROVIDERS_0 :: Using global proxy: 172.16.3.252:33128
2020-08-09 18:05:45 ERROR :: WEBSERVER :: Uncaught exception GET /sickrage/config/providers/getNewznabCategories?url=http%3A%2F%2Fjackett.net.xpto%3A9117%2Fapi%2Fv2.0%2Findexers%2Fall%2Fresults%2Ftorznab%2F&name=Jackett-ALL&key= (172.16.0.10)
HTTPServerRequest(protocol='http', host='lxcvpar18.net.xpto:8081', method='GET', uri='/sickrage/config/providers/getNewznabCategories?url=http%3A%2F%2Fjackett.net.xpto%3A9117%2Fapi%2Fv2.0%2Findexers%2Fall%2Fresults%2Ftorznab%2F&name=Jackett-ALL&key=', version='HTTP/1.1', remote_ip='172.16.0.10')
Traceback (most recent call last):
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1285, in handle_requests_exception
    raise requests_exception
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1219, in getURL
    headers=headers, cookies=cookies, proxies=proxies, verify=verify
  File "/home/sickchill/.local/lib/python3.7/site-packages/cloudscraper/__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/cloudscraper/__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/cachecontrol/adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/adapters.py", line 199, in proxy_manager_for
    **proxy_kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 492, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "/home/sickchill/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 429, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/views/index.py", line 182, in async_call
    return function(**kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/views/config/providers.py", line 68, in getNewznabCategories
    success, tv_categories, error = tempProvider.get_newznab_categories()
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/providers/newznab.py", line 147, in get_newznab_categories
    data = self.get_url(urljoin(self.url, 'api'), params=url_params, returns='text')
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/providers/GenericProvider.py", line 348, in get_url
    return getURL(url, post_data, params, self.headers, timeout, self.session, **kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1224, in getURL
    handle_requests_exception(error)
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1329, in handle_requests_exception
    level = get_level(error)
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1281, in get_level
    return (logger.ERROR, logger.WARNING)[exception and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception]
TypeError: argument of type 'ProxySchemeUnknown' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sickchill/.local/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/home/sickchill/.local/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/views/index.py", line 159, in get
    results = yield self.async_call(method)
  File "/home/sickchill/.local/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/views/index.py", line 184, in async_call
    return function()
TypeError: getNewznabCategories() missing 3 required positional arguments: 'name', 'url', and 'key'
2020-08-09 18:05:45 DEBUG :: WEBSERVER-CONFIGPROVIDERS_0 :: Using global proxy: 172.16.3.252:33128
2020-08-09 18:05:45 ERROR :: WEBSERVER :: Uncaught exception GET /sickrage/config/providers/getNewznabCategories?url=http%3A%2F%2Fjackett.net.xpto%3A9117%2Fapi%2Fv2.0%2Findexers%2Frarbg%2Fresults%2Ftorznab%2F&name=Jacket-RARBG&key=(172.16.0.10)
HTTPServerRequest(protocol='http', host='lxcvpar18.net.xpto:8081', method='GET', uri='/sickrage/config/providers/getNewznabCategories?url=http%3A%2F%2Fjackett.net.xpto%3A9117%2Fapi%2Fv2.0%2Findexers%2Frarbg%2Fresults%2Ftorznab%2F&name=Jacket-RARBG&key=', version='HTTP/1.1', remote_ip='172.16.0.10')
Traceback (most recent call last):
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1285, in handle_requests_exception
    raise requests_exception
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1219, in getURL
    headers=headers, cookies=cookies, proxies=proxies, verify=verify
  File "/home/sickchill/.local/lib/python3.7/site-packages/cloudscraper/__init__.py", line 263, in request
    self.perform_request(method, url, *args, **kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/cloudscraper/__init__.py", line 182, in perform_request
    return super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/cachecontrol/adapter.py", line 53, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/home/sickchill/.local/lib/python3.7/site-packages/requests/adapters.py", line 199, in proxy_manager_for
    **proxy_kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 492, in proxy_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "/home/sickchill/.local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 429, in __init__
    raise ProxySchemeUnknown(proxy.scheme)
urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/views/index.py", line 182, in async_call
    return function(**kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/views/config/providers.py", line 68, in getNewznabCategories
    success, tv_categories, error = tempProvider.get_newznab_categories()
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/providers/newznab.py", line 147, in get_newznab_categories
    data = self.get_url(urljoin(self.url, 'api'), params=url_params, returns='text')
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/providers/GenericProvider.py", line 348, in get_url
    return getURL(url, post_data, params, self.headers, timeout, self.session, **kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1224, in getURL
    handle_requests_exception(error)
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1329, in handle_requests_exception
    level = get_level(error)
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/oldbeard/helpers.py", line 1281, in get_level
    return (logger.ERROR, logger.WARNING)[exception and 's,t,o,p,b,r,e,a,k,i,n,g,f' in exception]
TypeError: argument of type 'ProxySchemeUnknown' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sickchill/.local/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/home/sickchill/.local/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/views/index.py", line 159, in get
    results = yield self.async_call(method)
  File "/home/sickchill/.local/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/lib64/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/sickchill/.local/lib/python3.7/site-packages/sickchill/views/index.py", line 184, in async_call
    return function()
TypeError: getNewznabCategories() missing 3 required positional arguments: 'name', 'url', and 'key'

**Comment by miigotu** [comment]
Restart after restore, the db name changed.

**Comment by miigotu** [comment]
Also remove your jacket API key from this post, and next time please reuse your existing issue even if it is closed (I can still see it)

**Comment by NunoHiggs** [comment]
I did restart. Multiple times. All the configs are there. There series are missing.

**Comment by miigotu** [comment]
3 of of those are now fixed in my PR, will be releasing it soon
