### ISSUE TITLE
RuntimeError during start on Synology DSM

### ISSUE THREAD

**Issue by BalintBanyasz** [SickChill/SickChill#6676]
Branch/Commit: Branch: master, Commit: 99336df163c7e776c7931d864e84d1f0f83afe4d, Version: v2020.08.07-1.
Package: BenjV's .SPK SickChill package
Python version: 2.7.12 (default, May 7 2020, 04:26:57) [GCC 4.9.3 20150311 (prerelease)]
OS: Synology DSM 6.2.3-25426 Update 2 (Linux-3.10.105-armv7l-with-glibc2.4)
Device: Synology DS216play

What you did: upgraded to the latest version of SickChill
What happened: SickChill crashes on start
What you expected: SickChill to start normally

Logs:
```
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python /volume1/@appstore/sickchill/SickChill/SickBeard.py --daemon --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/config.ini --datadir /volume1/@appstore/sickchill/var
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2u-fips  20 Dec 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "/volume1/@appstore/sickchill/SickChill/SickBeard.py", line 67, in <module>
    import sickbeard
  File "/volume1/@appstore/sickchill/SickChill/sickbeard/__init__.py", line 41, in <module>
    import sickchill
  File "/volume1/@appstore/sickchill/SickChill/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/volume1/@appstore/sickchill/SickChill/sickchill/show/indexers/__init__.py", line 22, in <module>
    from .handler import ShowIndexer
  File "/volume1/@appstore/sickchill/SickChill/sickchill/show/indexers/handler.py", line 31, in <module>
    from sickbeard.tv import Show
  File "/volume1/@appstore/sickchill/SickChill/sickbeard/tv.py", line 53, in <module>
    from . import db, helpers, logger, network_timezones, notifiers, postProcessor, subtitles
  File "/volume1/@appstore/sickchill/SickChill/sickbeard/helpers.py", line 56, in <module>
    import ifaddr
  File "/volume1/@appstore/sickchill/SickChill/lib/ifaddr/__init__.py", line 29, in <module>
    from ifaddr._posix import get_adapters
  File "/volume1/@appstore/sickchill/SickChill/lib/ifaddr/_posix.py", line 40, in <module>
    libc = ctypes.CDLL(ctypes.util.find_library("socket" if os.uname()[0] == "SunOS" else "c"), use_errno=True)
  File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
    raise RuntimeError("can not find library %s" % name)
RuntimeError: can not find library c
```

The issue seems to be introduced by de0c3c30987ff39a5788ccb686e8e7a45ed508b9 and is specific to Synology. Based on a patch found [here](https://github.com/chrisjbillington/inotify_simple/issues/21#issuecomment-668567322), I edited my `_posix.py` file to load `libc.so.6` directly. After that, SickChill started correctly.

**Comment by miigotu** [comment]
Master branch is no longer supported. Ask BenjV if he has a python3 version in the works.

**Comment by miigotu** [comment]
Also, python3 is required in master now, please get ahold of someone who creates packages for your device.
