### ISSUE TITLE
Error: no such table: tv_episodes

### ISSUE THREAD

**Issue by NiteAngyl** [SickChill/SickChill#6680]
Python version: 2.7.13

Because I was unable to update my install of SickChill I decided to reinstall it on my Qnap. I've downloaded the latest version from the QnapClub website (QSickChill_1.20181015_x86_64). Now SickChill refuses to start due to the following error:

```
Error
no such table: tv_episodes

Traceback
Traceback (most recent call last):
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/tornado/web.py", line 1511, in _execute
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/tornado/gen.py", line 1055, in run
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/tornado/concurrent.py", line 238, in result def done(self):
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/tornado/gen.py", line 1063, in run self.result_future = result_future
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/webserve.py", line 266, in get
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/tornado/gen.py", line 1055, in run
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/concurrent/futures/_base.py", line 455, in result return self.__get_result()
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/concurrent/futures/thread.py", line 63, in run result = self.fn(*self.args, **self.kwargs)
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/webserve.py", line 288, in async_call
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/webserve.py", line 758, in index
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/webserve.py", line 793, in show_statistics
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/db.py", line 318, in select
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/db.py", line 283, in action try:
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/db.py", line 139, in _execute :param fetchone: Boolean to indicate one result must be fetched (to walk results for instance)
OperationalError: no such table: tv_episodes

Request Info
body:
files: {}
protocol: http
connection:
body_arguments: {}
uri: /home/
query_arguments: {}
_start_time: 1599297415.88
headers: Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,nl;q=0.7 Accept-Encoding: gzip, deflate Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Host: 172.16.0.7:29998 Referer: http://172.16.0.7:8080/cgi-bin/ Cookie: NAS_USER=admin; NAS_SID=ab34g8yo; home=1; remeber=1; nas_1_u=YWRtaW4=; nas_1_a=MC40NDQ2NTY5NzczMDY2MDIyNS14LXgteC0wLjMxOTA2NjU5MzEyMTcwNDU=; qtoken_account=YWRtaW4=; qtoken=05a3053068b602bcdcce672b7bf2e1b4; QT=1599297414977 Upgrade-Insecure-Requests: 1
host: 172.16.0.7:29998
version: HTTP/1.1
server_connection:
host_name: 172.16.0.7
_finish_time: None
query:
arguments: {}
path: /home/
method: GET
remote_ip: 172.16.0.119

View Log(Errors)
```

**Comment by NiteAngyl** [comment]
Update:

After my attempt to install Python3 (# python3 -V results in Python 3.5.2) and the Python3 qpkg 3.8.0.0 I receive the following error:

`Error
database disk image is malformed

Traceback
Traceback (most recent call last):
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/tornado/web.py", line 1511, in _execute
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/tornado/gen.py", line 1055, in run
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/tornado/concurrent.py", line 238, in result def done(self):
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/tornado/gen.py", line 1063, in run self.result_future = result_future
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/webserve.py", line 266, in get
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/tornado/gen.py", line 1055, in run
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/concurrent/futures/_base.py", line 455, in result return self.__get_result()
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/lib/concurrent/futures/thread.py", line 63, in run result = self.fn(*self.args, **self.kwargs)
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/webserve.py", line 288, in async_call
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/webserve.py", line 758, in index
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/webserve.py", line 793, in show_statistics
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/db.py", line 318, in select
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/db.py", line 283, in action try:
File "/share/MD0_DATA/.qpkg/QSickChill/SickChill/sickbeard/db.py", line 139, in _execute :param fetchone: Boolean to indicate one result must be fetched (to walk results for instance)
DatabaseError: database disk image is malformed

Request Info
body:
files: {}
protocol: http
connection:
body_arguments: {}
uri: /home/
query_arguments: {}
_start_time: 1599302225.39
headers: Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,nl;q=0.7 Accept-Encoding: gzip, deflate Connection: keep-alive Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9 User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Host: 172.16.0.7:29998 Referer: http://172.16.0.7:8080/cgi-bin/ Cookie: NAS_USER=admin; NAS_SID=ab34g8yo; home=1; remeber=1; nas_1_u=YWRtaW4=; nas_1_a=MC40NDQ2NTY5NzczMDY2MDIyNS14LXgteC0wLjMxOTA2NjU5MzEyMTcwNDU=; qtoken_account=YWRtaW4=; qtoken=05a3053068b602bcdcce672b7bf2e1b4; QT=1599302166400; nas_lang=ENG Upgrade-Insecure-Requests: 1
host: 172.16.0.7:29998
version: HTTP/1.1
server_connection:
host_name: 172.16.0.7
_finish_time: None
query:
arguments: {}
path: /home/
method: GET
remote_ip: 172.16.0.119

View Log(Errors)`

Are there steps missing to upgrade my Qnap Python3 version to 3.6+ for SickChill to run?

**Comment by NiteAngyl** [comment]
Update:

After installing Python 3.6.2 and un- and installing SickChill multiple times I rebooted my Qnap twice. Seems like SickChill has installed in its default fresh state. After restoring my settings and database I seem to be 691 commits behind. After updating via SickChill or a git pull SickChill doesn't seem to boot anymore. I've un- and installed SickChill again and decided not to update anymore.
It's still unclear to me what generated the initial error I've started this thread with. I think an install and update to Python 3.6.2 and reboot of the Qnap was sufficient to run SickChill again in its most base form.

**Comment by miigotu** [comment]
The master branch runs on python 2.7
The develop branch requires Python3.6+

SC is working in both branches, but it seems a bad database was either created or restored. Delete the DB and make sure it is somewhere writable.
AFAIK Qnap Stephanie (or someone else) needs to make a new package for QNap
