### ISSUE TITLE
Manually added episodes not detected + mako error on testRename

### ISSUE THREAD

**Issue by kyuuk** [SickChill/SickChill#6711]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master/3484b32552b388617d53101b6ebdce3b0a1c76f5
OS: Docker container on a debian 10
Browser: chrome/firefox
What you did: manually added an episode
What happened: actually there are two problems :

1.  when i try to scan folder for the manually added episode it does not detect it (the episode is named with the same pattern than the others on the same show)
![image](https://user-images.githubusercontent.com/16566073/92581847-7cba0680-f290-11ea-8f37-78f3ec1f7dc0.png)
2. when i try to do a testRename on the shows that have an undetected manually added episode i get a mako error (i don't have the error for other show)

What you expected: episode to be detected & the testRename to work
Logs:
for the first issue (don't think this is relevant for the issue, the episode "142" is not in the logs)

```
2020-09-09 11:21:44 DEBUG :: SHOWQUEUE-REFRESH :: 331753: Creating episode object from /tv/Animes/enCours/Black Clover/Season_01/Black Clover_S01E138.mkv
2020-09-09 11:21:44 DEBUG :: SHOWQUEUE-REFRESH :: 331753: Creating episode from Black Clover_S01E138.mkv
2020-09-09 11:21:44 INFO :: SHOWQUEUE-REFRESH :: 331753: No episode number found in /tv/Animes/enCours/Black Clover/Season_01/Black Clover_S01E04_-_PAGE 4 Le test pour devenir Chevalier-Mage.mkv, ignoring it
2020-09-09 11:21:44 INFO :: SHOWQUEUE-REFRESH :: 331753: parse_result: Season - [ABS: [0]] [ANIME VER: 1] [ABD: False] [ANIME: True] [whichReg: ['anime_and_normal', 'anime_bare']] Score: -17
2020-09-09 11:21:44 DEBUG :: SHOWQUEUE-REFRESH :: Parsed /tv/Animes/enCours/Black Clover/Season_01/Black Clover_S01E04_-_PAGE 4 Le test pour devenir Chevalier-Mage.mkv into Season - [ABS: [0]] [ANIME VER: 1] [ABD: False] [ANIME: True] [whichReg: ['anime_and_normal', 'anime_bare']] Score: -17
AA IndexError: list index out of range
AA result = self._series(self.search(name, language)[0]['id'])
AA File "/app/sickchill/sickchill/show/indexers/tvdb.py", line 63, in get_series_by_name
AA result = self.indexers[i].get_series_by_name(n, indexerid, language)
AA File "/app/sickchill/sickchill/show/indexers/handler.py", line 114, in search_indexers_for_series_id
AA settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "/app/sickchill/sickchill/oldbeard/helpers.py", line 947, in get_show
2020-09-09 11:21:43 DEBUG :: SHOWQUEUE-REFRESH :: Traceback (most recent call last):
2020-09-09 11:21:43 DEBUG :: SHOWQUEUE-REFRESH :: Error when attempting to find show: Season in SickChill. Error: list index out of range
2020-09-09 11:21:43 DEBUG :: SHOWQUEUE-REFRESH :: Could not find item on the indexer: (Indexer probably doesn't have this item) [expected string or bytes-like object]
2020-09-09 11:21:43 DEBUG :: SHOWQUEUE-REFRESH :: Trying to find ['season'] on theTVDB
2020-09-09 11:21:43 DEBUG :: SHOWQUEUE-REFRESH :: 331753: Creating episode object from /tv/Animes/enCours/Black Clover/Season_01/Black Clover_S01E04_-_PAGE 4 Le test pour devenir Chevalier-Mage.mkv
2020-09-09 11:21:43 DEBUG :: SHOWQUEUE-REFRESH :: 331753: Creating episode from Black Clover_S01E04_-_PAGE 4 Le test pour devenir Chevalier-Mage.mkv
```
for the second issue there is no logs, i just have the error shown on the page 
```
File /app/sickchill/sickchill/gui/slick/views/testRename.mako:59, in render_content:
% for current_season in sorted(show.episodes, reverse=True):
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```
![image](https://user-images.githubusercontent.com/16566073/92581670-4086a600-f290-11ea-9fd9-aac7e8d811d8.png)

**Comment by miigotu** [comment]
You should never manually add files to a show folder. remove the show and use `add existing show` to fix it, next time use manual post processing to add episodes.

**Comment by kyuuk** [comment]
Okay, but just for information, before Python3 update, it was working fine.

thank you @miigotu
