### ISSUE TITLE
Rarbg fails to search - AttributeError: 'NoneType' object has no attribute 'query'

### ISSUE THREAD

**Issue by Smokey23** [SickChill/SickChill#6715]
Branch/Commit: 2020-09-09 20:24:48 DEBUG :: CHECKVERSION :: cur_commit = 7435bdf348cf507cc0d026769ea2dc49869667ce, newest_commit = 7435bdf348cf507cc0d026769ea2dc49869667ce, num_commits_behind = 0, num_commits_ahead = 0
OS: 10.0.19041.508
Browser: Chrome
What you did:  Normal Daily Search background process
What happened:  Failed to process Rarbg for daily episodes.  Cannot use Rarbg at all due to this bug

What you expected:  A normal search for episodes.  It looks like the issue may relate to some changes made about 8 or 9 days ago around additions to movies via rarbg.

Logs:
```
2020-09-09 20:34:50 DEBUG :: SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Search Mode: RSS
2020-09-09 20:34:50 DEBUG :: SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Error while searching Rarbg, skipping: AttributeError("'NoneType' object has no attribute 'query'")
2020-09-09 20:34:50 DEBUG :: SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickchill\oldbeard\tvcache.py", line 66, in update_cache
    data = self._get_rss_data()
  File "C:\SickChill\SickChill\sickchill\oldbeard\tvcache.py", line 55, in _get_rss_data
    return {'entries': self.provider.search(self.search_params)} if self.search_params else None
  File "C:\SickChill\SickChill\sickchill\oldbeard\providers\rarbg.py", line 84, in search
    if settings.movie_list.query.count():
AttributeError: 'NoneType' object has no attribute 'query'
```

**Comment by miigotu** [comment]
Easy fix. Will fix tomorrow

**Comment by Ventje23** [comment]
@miigotu 

I got same sort of error, although little bit different messages in log (see below)
Also it says are you sure show exists. If i look it up in thetvdb it's thre and I added the show using add shows in Sickchill.

2020-09-10 12:14:53 INFO :: SEARCHQUEUE-BACKLOG-381654 :: No needed episodes found during backlog search for: [Halifax: Retribution]
2020-09-10 12:14:53 INFO :: SEARCHQUEUE-BACKLOG-381654 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2020-09-10 12:14:51 INFO :: SEARCHQUEUE-BACKLOG-381654 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2020-09-10 12:14:49 INFO :: SEARCHQUEUE-BACKLOG-381654 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2020-09-10 12:14:47 INFO :: SEARCHQUEUE-BACKLOG-381654 :: [Rarbg] :: Performing episode search for Halifax: Retribution
AA AttributeError: 'NoneType' object has no attribute 'query'
AA if settings.movie_list.query.count():
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/oldbeard/providers/rarbg.py", line 84, in search
AA return {'entries': self.provider.search(self.search_params)} if self.search_params else None
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/oldbeard/tvcache.py", line 55, in _get_rss_data
AA data = self._get_rss_data()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/oldbeard/tvcache.py", line 66, in update_cache
2020-09-10 12:14:47 INFO :: SEARCHQUEUE-BACKLOG-381654 :: Beginning backlog search for: [Halifax: Retribution]
2020-09-10 12:13:46 INFO :: SEARCHQUEUE-BACKLOG-368643 :: No needed episodes found during backlog search for: [Raised by Wolves (2020)]
2020-09-10 12:13:42 INFO :: SEARCHQUEUE-BACKLOG-368643 :: [Rarbg] :: Performing episode search for Raised by Wolves (2020)
AA AttributeError: 'NoneType' object has no attribute 'query'
AA if settings.movie_list.query.count():
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/oldbeard/providers/rarbg.py", line 84, in search
AA return {'entries': self.provider.search(self.search_params)} if self.search_params else None
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/oldbeard/tvcache.py", line 55, in _get_rss_data
AA data = self._get_rss_data()
AA File "/volume1/@appstore/sickchill/var/SickBeard/sickchill/oldbeard/tvcache.py", line 66, in update_cache
2020-09-10 12:13:42 INFO :: SEARCHQUEUE-BACKLOG-368643 :: Beginning backlog search for: [Raised by Wolves (2020)]
