### ISSUE TITLE
AA sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: movie.pk

### ISSUE THREAD

**Issue by Parlane** [SickChill/SickChill#6722]
Hi @miigotu, On all tv searches currently I am getting this sql error when it searches for movies. Do I need to delete a cache file to resolve?

I know I probably wouldnt get these if I didnt have developer set to true, but I do to hide the warning about being on the develop branch. Would it be possible to add another config option like ack_develop = True ? Thanks.

```

2020-09-11 14:40:16 INFO :: SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
AA (Background on this error at: http://sqlalche.me/e/13/e3q8)
AA FROM movie) AS anon_1]
AA FROM (SELECT movie.pk AS movie_pk, movie.name AS movie_name, movie.date AS movie_date, movie.year AS movie_year, movie.status AS movie_status, movie.paused AS movie_paused, movie.location AS movie_location, movie.start AS movie_start, movie.interval AS movie_interval, movie.added AS movie_added, movie.updated AS movie_updated, movie.completed AS movie_completed, movie.searched AS movie_searched, movie.slug AS movie_slug, movie.language AS movie_language
AA [SQL: SELECT count(*) AS count_1
AA sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: movie.pk
AA cursor.execute(statement, parameters)
AA File "/app/sickchill/lib3/sqlalchemy/engine/default.py", line 593, in do_execute
AA cursor, statement, parameters, context
AA File "/app/sickchill/lib3/sqlalchemy/engine/base.py", line 1277, in _execute_context
AA raise exception
AA File "/app/sickchill/lib3/sqlalchemy/util/compat.py", line 182, in raise_
AA sqlalchemy_exception, with_traceback=exc_info[2], from_=e
AA File "/app/sickchill/lib3/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
AA e, statement, parameters, cursor, context
AA File "/app/sickchill/lib3/sqlalchemy/engine/base.py", line 1317, in _execute_context
AA distilled_params,
AA File "/app/sickchill/lib3/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
AA return connection._execute_clauseelement(self, multiparams, params)
AA File "/app/sickchill/lib3/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
AA return meth(self, multiparams, params)
AA File "/app/sickchill/lib3/sqlalchemy/engine/base.py", line 1011, in execute
AA result = conn.execute(querycontext.statement, self._params)
AA File "/app/sickchill/lib3/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
AA return self._execute_and_instances(context)
AA File "/app/sickchill/lib3/sqlalchemy/orm/query.py", line 3508, in __iter__
AA ret = list(self)
AA File "/app/sickchill/lib3/sqlalchemy/orm/query.py", line 3432, in one_or_none
AA ret = self.one_or_none()
AA File "/app/sickchill/lib3/sqlalchemy/orm/query.py", line 3463, in one
AA ret = self.one()
AA File "/app/sickchill/lib3/sqlalchemy/orm/query.py", line 3496, in scalar
AA return self.from_self(col).scalar()
AA File "/app/sickchill/lib3/sqlalchemy/orm/query.py", line 3776, in count
AA if settings.movie_list and settings.movie_list.query.count():
AA File "/app/sickchill/sickchill/oldbeard/providers/rarbg.py", line 84, in search
AA return {'entries': self.provider.search(self.search_params)} if self.search_params else None
AA File "/app/sickchill/sickchill/oldbeard/tvcache.py", line 55, in _get_rss_data
AA data = self._get_rss_data()
AA File "/app/sickchill/sickchill/oldbeard/tvcache.py", line 66, in update_cache
AA Traceback (most recent call last):
AA The above exception was the direct cause of the following exception:
AA sqlite3.OperationalError: no such column: movie.pk
AA cursor.execute(statement, parameters)
AA File "/app/sickchill/lib3/sqlalchemy/engine/default.py", line 593, in do_execute
AA cursor, statement, parameters, context
AA File "/app/sickchill/lib3/sqlalchemy/engine/base.py", line 1277, in _execute_context
2020-09-11 14:40:16 INFO :: SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
```

**Comment by miigotu** [comment]
Stop SC and delete movies.db (I made changes to it and there are no migrations for it yet)

**Comment by Parlane** [comment]
Thanks, fixed 👍
