### ISSUE TITLE
Updating Anime file list not working

### ISSUE THREAD

**Issue by Navino16** [SickChill/SickChill#6742]
Hi,

Branch/Commit: master
OS: Linux / Docker (linuxserver version)
Browser: Chrome
What you did:
 - 1. Adding new files for season 4 of anime "Sword Art Online"
 - 2. Press button "re-scan files" for updating sickchill

What happened: New files are not listed in sickchill
What you expected: Files must be listed
What you have tested:
 - Checking that Sickchill have right path to the files
 - Checking files permissions
 - Force full update
 - Restart sickchill
 - Disable Anidb

It seem that it's only related with anime since I can update classic shows. And before migrating to py3 version, there was no problems.

Logs:
```
2020-09-14 14:15:47 DEBUG :: SHOWQUEUE-REFRESH :: 259640: Creating episode object from /tv/shows1/Animes/Sword_Art_Online/Saison_02/Sword_Art_Online_S02E03.mkv
2020-09-14 14:15:47 DEBUG :: SHOWQUEUE-REFRESH :: 259640: Creating episode from Sword_Art_Online_S02E03.mkv
2020-09-14 14:15:47 DEBUG :: SHOWQUEUE-REFRESH :: 259640: Loading all episodes from the show directory /tv/shows1/Animes/Sword_Art_Online
```

Thanks for your help.

**Comment by miigotu** [comment]
Use the post processor. Adding files to an existing show folder is not supported and was never supposed to work.

**Comment by Navino16** [comment]
Hi,

Thanks for your response.
When using post processor I have this error :
```
2020-09-15 09:48:10 INFO :: POSTPROCESSOR-MANUAL :: Manual post processing task for /downloads/Direct completed
AA ValueError: max() arg is an empty sequence
AA best_result_anime = max(sorted([x for x in matches if x.is_anime], reverse=True, key=attrgetter('which_regex')), key=attrgetter('score'))
AA File "/usr/lib/python3.8/site-packages/sickchill/oldbeard/name_parser/parser.py", line 210, in _parse_string
AA file_name_result = self._parse_string(base_file_name, skip_scene_detection)
AA File "/usr/lib/python3.8/site-packages/sickchill/oldbeard/name_parser/parser.py", line 418, in parse
AA NameParser().parse(found_file, cache_result=False)
AA File "/usr/lib/python3.8/site-packages/sickchill/oldbeard/processTV.py", line 293, in validate_dir
AA if not validate_dir(current_directory, release_name, failed, result):
AA File "/usr/lib/python3.8/site-packages/sickchill/oldbeard/processTV.py", line 170, in process_dir
2020-09-15 09:48:10 DEBUG :: POSTPROCESSOR-MANUAL :: Traceback (most recent call last):
2020-09-15 09:48:10 DEBUG :: POSTPROCESSOR-MANUAL :: Processing folder /downloads/Direct
2020-09-15 09:48:10 INFO :: POSTPROCESSOR-MANUAL :: Processing /downloads/Direct
2020-09-15 09:48:10 DEBUG :: POSTPROCESSOR-MANUAL :: Processing in folder /downloads/Direct
2020-09-15 09:48:10 INFO :: POSTPROCESSOR-MANUAL :: Beginning manual post processing task: /downloads/Direct
2020-09-15 09:48:07 INFO :: WEBSERVER-POSTPROCESS_0 :: Manual post processing task for /downloads/Direct was added to the queue
```

Any idea why ?

Thanks for your help
