### ISSUE TITLE
Error when adding existing shows

### ISSUE THREAD

**Issue by dracosveen** [SickChill/SickChill#6744]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/20d84f5288ec3e532b6dd46cdbe4b833fbef00fd
OS: macOS 10.15.6
Browser: Safari
[sickchill.log](https://github.com/SickChill/SickChill/files/5221224/sickchill.log)
[sickchill.log](https://github.com/SickChill/SickChill/files/5221231/sickchill.log)

What you did: Trying to add existing shows from hard drive.  There are about 20.  I submit them sequentially.
What happened: This error appears for every submitted show.  Some shows are added but after a few minutes SickChill hangs and I have to restart. Even with debug log enabled, this error only appears in the console window and not in the log.
What you expected: Shows to be added without errors.
Logs:
2020-09-15 07:36:46,139 ERROR [imdbpy.parser.http.domparser] /Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/utils.py:468: DOMHTMLMovieParser: caught exception extracting XPath "//b[text()='Series Crew']"
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 272, in iterfind
    selector = _cache[cache_key]
KeyError: (".//b[text()='Series Crew']", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/utils.py", line 465, in xpath
    return piculet_xpath(element, path)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/piculet.py", line 327, in <lambda>
    xpath = lambda e, p: XPath(p)(e)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/piculet.py", line 325, in __call__
    return self._apply(element)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 313, in findall
    return list(iterfind(elem, path, namespaces))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 286, in iterfind
    selector.append(ops[token[0]](next, token))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 242, in prepare_predicate
    raise SyntaxError("invalid predicate")
  File "<string>", line None
SyntaxError: invalid predicate
2020-09-15 07:36:46,140 ERROR [imdbpy.parser.http.domparser] /Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/utils.py:427: DOMHTMLMovieParser: caught exception preprocessing DOM
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 272, in iterfind
    selector = _cache[cache_key]
KeyError: ('.//a[@class="tn15more"][starts-with(@href, "/title/")]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/utils.py", line 424, in parse
    dom = self.preprocess_dom(dom)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/movieParser.py", line 696, in preprocess_dom
    preprocessors.remove(dom, '//a[@class="tn15more"][starts-with(@href, "/title/")]')
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/piculet.py", line 609, in remove_elements
    elements = XPath(path)(root)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/piculet.py", line 325, in __call__
    return self._apply(element)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 313, in findall
    return list(iterfind(elem, path, namespaces))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 286, in iterfind
    selector.append(ops[token[0]](next, token))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 242, in prepare_predicate
    raise SyntaxError("invalid predicate")
  File "<string>", line None
SyntaxError: invalid predicate
2020-09-15 07:36:46,141 CRITICAL [imdbpy] /Users/richardcumming/_Apps/SickChill/lib3/imdb/__init__.py:792: caught an exception retrieving or parsing "main" info set for mopID "5853176" (accessSystem: http)
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 272, in iterfind
    selector = _cache[cache_key]
KeyError: ('.//h4[contains(@class, "ipl-header__content")]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/__init__.py", line 787, in update
    ret = method(mopID)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/__init__.py", line 455, in get_movie_main
    return self.mProxy.movie_parser.parse(cont, mdparse=self._mdparse)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/utils.py", line 434, in parse
    data = self.parse_dom(dom)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/utils.py", line 526, in parse_dom
    return Rules(self.rules).extract(dom)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/piculet.py", line 373, in extract
    value = self.apply(element)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/piculet.py", line 517, in apply
    extracted = rule.extract(subroot)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/piculet.py", line 583, in extract
    for r in self.extractor.foreach(subroot)]
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/piculet.py", line 325, in __call__
    return self._apply(element)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 313, in findall
    return list(iterfind(elem, path, namespaces))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 286, in iterfind
    selector.append(ops[token[0]](next, token))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 242, in prepare_predicate
    raise SyntaxError("invalid predicate")
  File "<string>", line None
SyntaxError: invalid predicate
2020-09-15 07:36:49,490 WARNING [imdbpy.parser.http.domparser] /Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/utils.py:433: DOMHTMLPlotParser: unable to gather refs
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 272, in iterfind
    selector = _cache[cache_key]
KeyError: ('.//a[starts-with(@href, "/name/nm")]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/utils.py", line 430, in parse
    self.gather_refs(dom)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/utils.py", line 515, in gather_refs
    refs = grParser.parse_dom(dom)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/utils.py", line 526, in parse_dom
    return Rules(self.rules).extract(dom)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/piculet.py", line 373, in extract
    value = self.apply(element)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/piculet.py", line 517, in apply
    extracted = rule.extract(subroot)
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/piculet.py", line 583, in extract
    for r in self.extractor.foreach(subroot)]
  File "/Users/richardcumming/_Apps/SickChill/lib3/imdb/parser/http/piculet.py", line 325, in __call__
    return self._apply(element)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 313, in findall
    return list(iterfind(elem, path, namespaces))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 286, in iterfind
    selector.append(ops[token[0]](next, token))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/xml/etree/ElementPath.py", line 242, in prepare_predicate
    raise SyntaxError("invalid predicate")
  File "<string>", line None
SyntaxError: invalid predicate

**Comment by miigotu** [comment]
`pip3 install lxml`

**Comment by dracosveen** [comment]
thank you thank you.  That seems to have fixed the issue.
