### ISSUE TITLE
imdb parser issue with pip install

### ISSUE THREAD

**Issue by aptalca** [SickChill/SickChill#6765]
Branch/Commit: pip version 2020.9.16-post3
OS: alpine (linuxserver docker)
Browser: N/A
What you did: pip install sickchill and start
What happened: crashes with error
What you expected: start successfully
Logs:
```
/usr/lib/python3.8/site-packages/sickchill/locale
/usr/lib/python3.8/site-packages/sickchill/locale
/usr/lib/python3.8/site-packages/sickchill/locale
Traceback (most recent call last):
  File "/usr/bin/SickChill.py", line 40, in <module>
    from sickchill.views.server_settings import SRWebServer
  File "/usr/lib/python3.8/site-packages/sickchill/views/__init__.py", line 15, in <module>
    from .manage import AddShows, Manage, ManageSearches, PostProcess
  File "/usr/lib/python3.8/site-packages/sickchill/views/manage/__init__.py", line 1, in <module>
    from .add_shows import AddShows
  File "/usr/lib/python3.8/site-packages/sickchill/views/manage/add_shows.py", line 21, in <module>
    from sickchill.show.recommendations.imdb import imdb_popular
  File "/usr/lib/python3.8/site-packages/sickchill/show/recommendations/imdb.py", line 66, in <module>
    imdb_popular = imdbPopular()
  File "/usr/lib/python3.8/site-packages/sickchill/show/recommendations/imdb.py", line 17, in __init__
    self.imdb.topBottomProxy.tvmeter100_parser.rules[0].extractor.rules.append(
  File "/usr/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 90, in __getattr__
    return getattr(_sm, name)
AttributeError: module 'imdb.parser.http.topBottomParser' has no attribute 'tvmeter100_parser'
```

**Comment by fl1ck3r** [comment]
Same issue on my side,
OS : Raspbian 10.
Original issue as per  #6755 ,

Temporarily rolling back to 2020.9.13.post1 fixes the issue
pip3 install -Iv sickchill==2020.9.13.post1

**Comment by fl1ck3r** [comment]
So after some further debuging, it was clear from @aptalca 's log,  that the attribute tvmeter100_parser does not exists in 'imdb.parser.http.topBottomParse.py",

I fixed this issue, by doing the following:
Uninstalled incorrect imdbpy : 
pip3 uninstall imdbpy

Then installed this repo (which has tvmeter100): https://github.com/alberanid/imdbpy

pip3 install git+https://github.com/alberanid/imdbpy

after which sickchill 2020.9.16.post3 , started successfully. 💯

**Comment by slusken** [comment]
```

/usr/lib/python3.8/site-packages/sickchill/locale
/usr/lib/python3.8/site-packages/sickchill/locale
Traceback (most recent call last):
  File "/usr/bin/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/usr/lib/python3.8/site-packages/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/usr/lib/python3.8/site-packages/sickchill/tv.py", line 15, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'
```

Having problem with Docker-image also regarding IMDB.

**Comment by miigotu** [comment]
@fl1ck3r for some reason imdbpy has not released the update yet smh, I but a try/except around it for now so it will start with the older version too.
