### ISSUE TITLE
ModuleNotFoundError: No module named 'imdb'

### ISSUE THREAD

**Issue by robbaman** [SickChill/SickChill#6768]
I'm running SickRage as a docker container using the linuxserver/sickchill image. When I upgrade to the latest version linuxserver/sickchill:2020.9.16.post2-ls43 this gives me the error below. I've also tried starting a new instance in a completely new configuration directory, but the error remains.

```
ModuleNotFoundError: No module named 'imdb'
/usr/lib/python3.8/site-packages/sickchill/locale
/usr/lib/python3.8/site-packages/sickchill/locale
Traceback (most recent call last):
  File "/usr/bin/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/usr/lib/python3.8/site-packages/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/usr/lib/python3.8/site-packages/sickchill/tv.py", line 15, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'
```

Sorry I don't have more sophisticated logs, but this is all docker spits out and it seems it happens too early in the startup for the SickChill logs to be created.

Any chance you know what's going on here? Thanks in advance.

**Comment by robbaman** [comment]
Apologies, I just found other issues with this exact problem... I'm an idiot :)
