### ISSUE TITLE
Docker-image dont show gui.

### ISSUE THREAD

**Issue by slusken** [SickChill/SickChill#6769]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Linuxserver.io version:- 2020.9.16.post2-ls43 Build
OS: Debian Docker
Browser: FF
What you did: Updated the Docker.
What happened:  Don't show GUI.
What you expected: It to work.
Logs:
```

ModuleNotFoundError: No module named 'imdb'
/usr/lib/python3.8/site-packages/sickchill/locale
/usr/lib/python3.8/site-packages/sickchill/locale
Traceback (most recent call last):
  File "/usr/bin/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/usr/lib/python3.8/site-packages/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/usr/lib/python3.8/site-packages/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/usr/lib/python3.8/site-packages/sickchill/tv.py", line 15, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'
```

**Comment by miigotu** [comment]
Ever try pulling the newest image?

**Comment by miigotu** [comment]
Also, linuxserver image is not our responsibility. We have our own image at sickchill/sickchill
