### ISSUE TITLE
cannot Manual post-processing - UnicodeEncodeError ascii 

### ISSUE THREAD

**Issue by VietTPham** [SickChill/SickChill#6770]
Branch/Commit: master fc91063a06dbf81d239f974d531a17f515f7853a
OS: Ubuntu docker
Browser: curl / api / FF
What you did: curl using curl -sk -o /dev/null 'https://localhost:8081/api/<api key>/?cmd=postprocess&force_next=1&is_priority=0&path=/tmpfs/sort&return_data=0&process_method=move&type=manual'
Also did it manual process on the webui on firefox.
This was working when using python 2.7. I had to upgrade to python 3.6 and that's when it stopped working.
What happened: It error about unicode/ascii
What you expected: Folder to be process
Logs:
```
2020-09-17 09:38:22 DEBUG :: POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2020-09-17 09:38:24 INFO :: POSTPROCESSOR :: Auto post processing task for /tmpfs/sort was added to the queue
2020-09-17 09:38:26 INFO :: POSTPROCESSOR-AUTO :: Beginning auto post processing task: /tmpfs/sort
2020-09-17 09:38:26 DEBUG :: POSTPROCESSOR-AUTO :: Processing in folder /tmpfs/sort
2020-09-17 09:38:26 INFO :: POSTPROCESSOR-AUTO :: Processing /tmpfs/sort
2020-09-17 09:38:26 DEBUG :: POSTPROCESSOR-AUTO :: Processing folder /tmpfs/sort
2020-09-17 09:38:26 DEBUG :: POSTPROCESSOR-AUTO :: Traceback (most recent call last):
  File "/opt/SickChill/sickchill/oldbeard/processTV.py", line 170, in process_dir
    if not validate_dir(current_directory, release_name, failed, result):
  File "/opt/SickChill/sickchill/oldbeard/processTV.py", line 268, in validate_dir
    if process_path.lower().startswith(os.path.realpath(sqlShow["location"]).lower() + os.sep) or \
  File "/usr/lib/python3.6/posixpath.py", line 395, in realpath
    path, ok = _joinrealpath(filename[:0], filename, {})
  File "/usr/lib/python3.6/posixpath.py", line 429, in _joinrealpath
    if not islink(newpath):
  File "/usr/lib/python3.6/posixpath.py", line 171, in islink
    st = os.lstat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2606' in position 28: ordinal not in range(128)

2020-09-17 09:38:26 INFO :: POSTPROCESSOR-AUTO :: Auto post processing task for /tmpfs/sort completed
```

**Comment by miigotu** [comment]
Whose docker image is this? because our ioencoding is set to utf-8.

**Comment by VietTPham** [comment]
I am using ubuntu:18.04, looks like I just need to set the LANG environment variable to en_US.UTF-8
