### ISSUE TITLE
TD not working

### ISSUE THREAD

**Issue by hansbogert** [SickChill/SickChill#6775]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Debian 10
Browser: Firefox
What you did: manually trigger search for episode
What happened: nothing 
What you expected: fetch an episode.
Logs:
```
AA AttributeError: module 'bencodepy' has no attribute 'DecodingError'
AA except bencodepy.DecodingError as e:
AA File "/opt/SickRage/sickchill/providers/torrent/TorrentProvider.py", line 109, in _verify_download
AA if self._verify_download(downloaded_filename):
AA File "/opt/SickRage/sickchill/providers/GenericProvider.py", line 105, in download_result
AA newResult = resProvider.download_result(result)
AA File "/opt/SickRage/sickchill/oldbeard/search.py", line 34, in _downloadResult
AA dlResult = _downloadResult(result)
AA File "/opt/SickRage/sickchill/oldbeard/search.py", line 111, in snatchEpisode
AA self.success = search.snatchEpisode(search_result[0])
AA File "/opt/SickRage/sickchill/oldbeard/search_queue.py", line 174, in run
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA AttributeError: module 'bencodepy' has no attribute 'decode_from_file'
AA bencodepy.decode_from_file(file_name)
AA File "/opt/SickRage/sickchill/providers/torrent/TorrentProvider.py", line 108, in _verify_download
```

**Comment by miigotu** [comment]
You aren't updated...
