### ISSUE TITLE
Can't start, IMDbPy error after upgrade via PIP

### ISSUE THREAD

**Issue by lightningjim** [SickChill/SickChill#6778]
Branch/Commit: sickchill-2020.9.16.post3
OS: Ubuntu 20.04
Browser: Google Chrome
What you did:  Start SickChill after PIP update
What happened: Crashed with an Attribute error
What you expected: It to start
Logs:
$ SickChill.py 
/usr/local/lib/python3.8/dist-packages/sickchill/locale
/usr/local/lib/python3.8/dist-packages/sickchill/locale
/usr/local/lib/python3.8/dist-packages/sickchill/locale
Traceback (most recent call last):
  File "/usr/local/bin/SickChill.py", line 40, in <module>
    from sickchill.views.server_settings import SRWebServer
  File "/usr/local/lib/python3.8/dist-packages/sickchill/views/__init__.py", line 15, in <module>
    from .manage import AddShows, Manage, ManageSearches, PostProcess
  File "/usr/local/lib/python3.8/dist-packages/sickchill/views/manage/__init__.py", line 1, in <module>
    from .add_shows import AddShows
  File "/usr/local/lib/python3.8/dist-packages/sickchill/views/manage/add_shows.py", line 21, in <module>
    from sickchill.show.recommendations.imdb import imdb_popular
  File "/usr/local/lib/python3.8/dist-packages/sickchill/show/recommendations/imdb.py", line 66, in <module>
    imdb_popular = imdbPopular()
  File "/usr/local/lib/python3.8/dist-packages/sickchill/show/recommendations/imdb.py", line 17, in __init__
    self.imdb.topBottomProxy.tvmeter100_parser.rules[0].extractor.rules.append(
  File "/usr/local/lib/python3.8/dist-packages/imdb/parser/http/__init__.py", line 90, in __getattr__
    return getattr(_sm, name)
AttributeError: module 'imdb.parser.http.topBottomParser' has no attribute 'tvmeter100_parser'

When I did my pip update for SickChill, it updated IMDbPY to version 6.8, which is likely the cause here.

**Comment by lightningjim** [comment]
Forgot that GitHub only shows Open tickets in default view, and thought I had seen all tickets

Please close out as duplicate of https://github.com/SickChill/SickChill/issues/6765 while I do the workaround posted there
