### ISSUE TITLE
Emby notifications don't work

### ISSUE THREAD

**Issue by romainsi** [SickChill/SickChill#6816]
Branch/Commit:master/20d84f5288ec3e532b6dd46cdbe4b833fbef00fd
OS:Linux-4.19-std-centos-7
Browser:chrome
Version: v2020.09.14-2
Database Version: 44.5
Python Version:3.6.8 (default, Apr 2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

Emby Version 4.5.0.50 and 4.5.1.0

What you did:
After correctly configuring and testing the connection to Emby for notifications, when I run "Update Emby" or "Update Series in Emby" it doesn't work.
![image](https://user-images.githubusercontent.com/30522413/94545862-637ff680-024d-11eb-95e4-2c9efb9c01ac.png)

What happened:
Sickchill generates an error for Emby notifications :

When "Update Series in Emby" :
Log sickchill :
```
2020-09-29 11:18:39 DEBUG :: AUTO :: Failed doing webui request "sickchill/cache/images/268592_fanart_jpg": Traceback (most recent call last):
2020-09-29 11:18:37 WARNING :: WEBSERVER-HOME_0 :: EMBY: Warning: Could not contact Emby at https://emby.mydomain.fr/emby/Library/Series/Updated 404 Client Error: Not Found for url: https://emby.mydomain.fr/emby/Library/Series/Updated?tvdbid=268592
AA AttributeError: 'WebRoot' object has no attribute 'sickchill/cache/images/268592_fanart_jpg'
AA method = getattr(self, route)
AA File "/opt/usenet/SickChill/sickchill/views/index.py", line 159, in get

```
Log Emby :
```
2020-09-29 11:12:59.366 Info HttpServer: HTTP GET http://emby.mydomain.fr/emby/Library/Series/Updated?tvdbid=268592. UserAgent: python-requests/2.24.0
2020-09-29 11:12:59.367 Info HttpServer: HTTP Response 404 to *.*.*.*. Time: 1ms. http://emby.mydomain.fr/emby/Library/Series/Updated?tvdbid=268592. ConnectionId: 0HM349B8ML439
```

When I test the connection to Emby by SickChill
Log Emby :
```
2020-09-29 11:12:42.684 Info HttpServer: HTTP GET http://emby.mydomain.fr/emby/Notifications/Admin?Name=SickChill&Description=This+is+a+test+notification+from+SickChill&ImageUrl=https%3A%2F%2Fsickchill.github.io%2Fimages%2Fico%2Ffavicon-64.png. UserAgent: python-requests/2.24.0
2020-09-29 11:12:42.684 Info HttpServer: HTTP Response 200 to *.*.*.*. Time: 1ms. http://emby.mydomain.fr/emby/Notifications/Admin?Name=SickChill&Description=This+is+a+test+notification+from+SickChill&ImageUrl=https%3A%2F%2Fsickchill.github.io%2Fimages%2Fico%2Ffavicon-64.png. ConnectionId: 0HM349B8ML438
```

What you expected:
That it works ^^ ;)
I can provide a real domain name with test api for Emby in private if needed.

Edit : Same error with localhost (emby is on same server with reverse nginx).
```
2020-09-29 09:57:47 WARNING :: WEBSERVER-HOME_0 :: EMBY: Warning: Could not contact Emby at http://localhost:8096/emby/Library/Series/Updated 404 Client Error: Not Found for url: http://localhost:8096/emby/Library/Series/Updated?tvdbid=268592
AA AttributeError: 'WebRoot' object has no attribute 'sickchill/cache/images/268592_fanart_jpg'
AA method = getattr(self, route)
AA File "/opt/usenet/SickChill/sickchill/views/index.py", line 159, in get
```

**Comment by DragonEmbers** [comment]
Can confirm, this is because Emby have depricated the API http://swagger.emby.media/?staticview=true#/LibraryService/postLibrarySeriesAdded

The new API is http://swagger.emby.media/?staticview=true#/LibraryService/postLibraryMediaUpdated

**Comment by einarsi** [comment]
@DragonEmbers: Thank you for discovering and sharing that the API has been deprecated. I took the liberty to create an improved solution that makes use of show information to avoid updating the entire library.

**Comment by miigotu** [comment]
I've merged the updated PR. My only concern is what about people running older version of emby?

**Comment by einarsi** [comment]
Thanks for the merge. The API endpoint is almost three years old, so I wouldn't worry about people running older versions at all: https://github.com/MediaBrowser/Emby/commit/6d5ec16c4756b8f204166e82010ae027954bd148#diff-f09c930df9817e1a39f56c13a4d128ca5ffc82fa190120933f4609e650a5a1c7R264

**Comment by romainsi** [comment]
Ok with update v2020.10.22-1.
Thank you ! 👍
