### ISSUE TITLE
Could not find item on the indexer (Season pack PP)

### ISSUE THREAD

**Issue by jackkiej** [SickChill/SickChill#6830]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
Commit: 7b98df0
Version: v2020.09.28-2
Database Version: 44.2
Python Version : 3.7.5 (default, Oct 17 2019, 12:21:00) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
SSL Version : OpenSSL 1.1.1d FIPS 10 Sep 2019
OS: Linux-5.3.11-100.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine

Although postprocessing works fine with this error it still is strange that it looks up "fear the walking dead s" in theTVDB which never happened before.

Logs:
```
2020-10-07 01:14:08 INFO :: WEBSERVER-POSTPROCESS_0 :: Processing /mnt/virtual_hdd/downloads/deluge/complete/series/Fear.the.Walking.Dead.S02.1080p.AMZN.WEBRip.DDP5.1.x265-SiGMA[rartv]/Fear.the.Walking.Dead.S02E14.Wrath.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA.mkv (Fear.the.Walking.Dead.S02.1080p.AMZN.WEBRip.DDP5.1.x265-SiGMA[rartv])
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Analyzing name Fear.the.Walking.Dead.S02.1080p.AMZN.WEBRip.DDP5.1.x265-SiGMA[rartv]
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Using cached parse result for: Fear.the.Walking.Dead.S02.1080p.AMZN.WEBRip.DDP5.1.x265-SiGMA
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Parse result not sufficient (all following have to be set). will not save release name
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Parse result(series_name): Fear the Walking Dead
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Parse result(season_number): 2
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Parse result(episode_numbers): []
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 ::  or Parse result(air_date): None
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Parse result(release_group): SiGMA
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Analyzing name Fear.the.Walking.Dead.S02E14.Wrath.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA.mkv
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Parsed Fear.the.Walking.Dead.S02E14.Wrath.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA into Fear the Walking Dead - S02E14 [GROUP: SiGMA] [ABD: False] [ANIME: False] [whichReg: ['standard']] Score: 5
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Retrieving episode object for 2x14
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Snatch history had a quality in it, using that: 1080p WEB-DL
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Quality of the episode we're processing: 1080p WEB-DL
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: SR snatched this episode and it is not processed before
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Is ep a priority download: True
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: There is no existing file so there's no worries about replacing it
2020-10-07 01:14:08 INFO :: WEBSERVER-POSTPROCESS_0 :: This download is marked a priority download so I'm going to replace an existing file if I find one
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Trying to determine free space on the destination drive
2020-10-07 01:14:08 INFO :: WEBSERVER-POSTPROCESS_0 :: Process method is 'move' and src and destination are on the same device, skipping free space check
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Found release name Fear.the.Walking.Dead.S02E14.Wrath.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA
2020-10-07 01:14:08 INFO :: WEBSERVER-POSTPROCESS_0 :: Using nzb_name for release name.
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Using cached parse result for: Fear.the.Walking.Dead.S02E14.Wrath.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Found codec for 'Fear the Walking Dead: Wrath'.
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Episode has no release group, replacing it with 'SiGMA'
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: formatting pattern: %SN - S%0SE%0E - %EN - %SQN - %RG -> Fear the Walking Dead - S02E14 - Wrath - 1080p WEB-DL h265 - SiGMA
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Using cached parse result for: Fear.the.Walking.Dead.S02E14.Wrath.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Found codec for 'Fear the Walking Dead: Wrath'.
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: formatting pattern: Season %0S -> Season 02
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Destination folder for this episode: /mnt/virtual_hdd/plex/series/Fear the Walking Dead/Season 02
2020-10-07 01:14:08 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Checking if the path /mnt/virtual_hdd/plex/series/Fear the Walking Dead/Season 02 already exists
2020-10-07 01:14:09 DEBUG :: WEBSERVER-POSTPROCESS_0 :: No associated files for /mnt/virtual_hdd/downloads/deluge/complete/series/Fear.the.Walking.Dead.S02.1080p.AMZN.WEBRip.DDP5.1.x265-SiGMA[rartv]/Fear.the.Walking.Dead.S02E14.Wrath.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA.mkv were found during this pass
2020-10-07 01:14:09 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Moving file from /mnt/virtual_hdd/downloads/deluge/complete/series/Fear.the.Walking.Dead.S02.1080p.AMZN.WEBRip.DDP5.1.x265-SiGMA[rartv]/Fear.the.Walking.Dead.S02E14.Wrath.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA.mkv to /mnt/virtual_hdd/plex/series/Fear the Walking Dead/Season 02/Fear the Walking Dead - S02E14 - Wrath - 1080p WEB-DL h265 - SiGMA.mkv
2020-10-07 01:14:09 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Setter sets location to /mnt/virtual_hdd/plex/series/Fear the Walking Dead/Season 02/Fear the Walking Dead - S02E14 - Wrath - 1080p WEB-DL h265 - SiGMA.mkv
2020-10-07 01:14:10 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Checking subtitle candidates for Fear the Walking Dead S02E14 (Fear the Walking Dead - S02E14 - Wrath - 1080p WEB-DL h265 - SiGMA.mkv)
2020-10-07 01:14:12 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Could not search in addic7ed provider. Discarding for now
2020-10-07 01:14:12 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Could not search in legendastv provider. Discarding for now
2020-10-07 01:14:12 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955332876 is: 765 (min=213)
2020-10-07 01:14:12 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955333320 is: 765 (min=213)
2020-10-07 01:14:12 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955333319 is: 778 (min=213)
2020-10-07 01:14:13 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955332877 is: 766 (min=213)
2020-10-07 01:14:13 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955333321 is: 766 (min=213)
2020-10-07 01:14:13 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955333318 is: 777 (min=213)
2020-10-07 01:14:13 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955335286 is: 778 (min=213)
2020-10-07 01:14:13 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955335287 is: 777 (min=213)
2020-10-07 01:14:13 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955536818 is: 768 (min=213)
2020-10-07 01:14:13 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955334584 is: 773 (min=213)
2020-10-07 01:14:13 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955333243 is: 766 (min=213)
2020-10-07 01:14:13 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955333242 is: 776 (min=213)
2020-10-07 01:14:13 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [opensubtitles] Subtitle score for 1955333244 is: 766 (min=213)
2020-10-07 01:14:14 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for jztC is: 768 (min=213)
2020-10-07 01:14:14 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for jTtC is: 768 (min=213)
2020-10-07 01:14:15 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for ZTtC is: 767 (min=213)
2020-10-07 01:14:16 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for aTtC is: 767 (min=213)
2020-10-07 01:14:16 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for gO5B is: 767 (min=213)
2020-10-07 01:14:16 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for bMRB is: 778 (min=213)
2020-10-07 01:14:16 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for RcRB is: 773 (min=213)
2020-10-07 01:14:16 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for RMNB is: 772 (min=213)
2020-10-07 01:14:16 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for BsNB is: 766 (min=213)
2020-10-07 01:14:16 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for 7sJB is: 765 (min=213)
2020-10-07 01:14:16 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for 08JB is: 766 (min=213)
2020-10-07 01:14:16 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for tMJB is: 765 (min=213)
2020-10-07 01:14:16 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for s8JB is: 766 (min=213)
2020-10-07 01:14:16 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for hsRB is: 766 (min=213)
2020-10-07 01:14:17 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for gcRB is: 773 (min=213)
2020-10-07 01:14:17 DEBUG :: WEBSERVER-POSTPROCESS_0 :: [podnapisi] Subtitle score for fsRB is: 766 (min=213)
2020-10-07 01:14:21 DEBUG :: WEBSERVER-POSTPROCESS_0 :: history.logSubtitle opensubtitles, eng
2020-10-07 01:14:22 DEBUG :: WEBSERVER-POSTPROCESS_0 :: history.logSubtitle opensubtitles, dut
2020-10-07 01:14:22 DEBUG :: WEBSERVER-POSTPROCESS_0 :: 290853: Downloaded Dutch, English subtitles for Fear the Walking Dead S02E14
2020-10-07 01:14:22 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Parsed /mnt/virtual_hdd/plex/series/Fear the Walking Dead/Season 02/Fear the Walking Dead - S02E14 - Wrath - 1080p WEB-DL h265 - SiGMA into Fear the Walking Dead - S02E14 [ABD: False] [ANIME: False] [whichReg: ['standard', 'season_only']] Score: -2
2020-10-07 01:14:22 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Using cached parse result for: Fear.the.Walking.Dead.S02E14.Wrath.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA
2020-10-07 01:14:22 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Found codec for 'Fear the Walking Dead: Wrath'.
2020-10-07 01:14:22 DEBUG :: WEBSERVER-POSTPROCESS_0 :: formatting pattern: %SN - S%0SE%0E - %EN -> Fear the Walking Dead - S02E14 - Wrath
2020-10-07 01:14:22 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Notification for NMJ scan update not enabled, skipping this notification
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Parsed /mnt/virtual_hdd/plex/series/Fear the Walking Dead/Season 02/Fear the Walking Dead - S02E14 - Wrath - 1080p WEB-DL h265 - SiGMA into Fear the Walking Dead - S02E14 [ABD: False] [ANIME: False] [whichReg: ['standard', 'season_only']] Score: -2
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Using cached parse result for: Fear.the.Walking.Dead.S02E14.Wrath.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Found codec for 'Fear the Walking Dead: Wrath'.
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Fear the Walking Dead - 2x14 - Wrath - 1080p WEB-DL
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Notification for NMJ scan update not enabled, skipping this notification
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: PLEX: Updating hosts where TV section paths match the downloaded show: 2
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Parsed /mnt/virtual_hdd/plex/series/Fear the Walking Dead/Season 02/Fear the Walking Dead - S02E14 - Wrath - 1080p WEB-DL h265 - SiGMA into Fear the Walking Dead - S02E14 [ABD: False] [ANIME: False] [whichReg: ['standard', 'season_only']] Score: -2
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Using cached parse result for: Fear.the.Walking.Dead.S02E14.Wrath.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Found codec for 'Fear the Walking Dead: Wrath'.
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Fear the Walking Dead - 2x14 - Wrath - 1080p WEB-DL
2020-10-07 01:14:23 INFO :: WEBSERVER-POSTPROCESS_0 :: Processing succeeded for /mnt/virtual_hdd/downloads/deluge/complete/series/Fear.the.Walking.Dead.S02.1080p.AMZN.WEBRip.DDP5.1.x265-SiGMA[rartv]/Fear.the.Walking.Dead.S02E14.Wrath.1080p.AMZN.WEB-DL.DD5.1.H265-SiGMA.mkv
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Trying to find ['fear the walking dead s'] on theTVDB
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Could not find item on the indexer: (Indexer probably does not have this item) [expected string or bytes-like object]
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Traceback (most recent call last):
  File "/home/media/sickrage/sickchill/show/indexers/wrappers.py", line 21, in wrapper
    result = target(*args, **kwargs)
  File "/home/media/sickrage/sickchill/show/indexers/tvdb.py", line 107, in search
    if re.match(r'^t?t?\d{7,8}$', name) or re.match(r'^\d{6}$', name):
  File "/usr/lib64/python3.7/re.py", line 173, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Error when attempting to find show: Fear the Walking Dead S in SickChill. Error: list index out of range 
2020-10-07 01:14:23 DEBUG :: WEBSERVER-POSTPROCESS_0 :: Traceback (most recent call last):
  File "/home/media/sickrage/sickchill/oldbeard/helpers.py", line 984, in get_show
    settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
  File "/home/media/sickrage/sickchill/show/indexers/handler.py", line 114, in search_indexers_for_series_id
    result = self.indexers[i].get_series_by_name(n, indexerid, language)
  File "/home/media/sickrage/sickchill/show/indexers/tvdb.py", line 63, in get_series_by_name
    result = self._series(self.search(name, language)[0]['id'])
IndexError: list index out of range
```

**Comment by miigotu** [comment]
It's just debug info, for me. If you turn off debug it doesn't show in the logs.
