### ISSUE TITLE
Timing out while trying to open a show.

### ISSUE THREAD

**Issue by elit3ge** [SickChill/SickChill#6836]
Branch/Commit: master
OS: Windows 10
Browser: Chrome
What you did: Try to open a show.
What happened: The window sits there and spins and spins, settings and the other pages open. The only way to get it to work again is to restart SickChill. Also when adding a show ti doesn't add them, they sit in the status/ Show Queue.
What you expected: When you click on a show to open it.
Note: This has been happening for the last couple of weeks.
Logs:
```
AA RuntimeError: can't start new thread
AA _start_new_thread(self._bootstrap, ())
AA File "C:\Python38\lib\threading.py", line 852, in start
AA t.start()
AA File "C:\Python38\lib\concurrent\futures\thread.py", line 213, in _adjust_thread_count
AA self._adjust_thread_count()
AA File "C:\Python38\lib\concurrent\futures\thread.py", line 188, in submit
AA conc_future = getattr(self, executor).submit(fn, self, *args, **kwargs)
AA File "C:\Apps\SickRage-Master\lib3\tornado\concurrent.py", line 123, in wrapper
AA results = yield self.async_call(method)
AA File "C:\Apps\SickRage-Master\sickchill\views\index.py", line 161, in get
AA yielded = next(result)
AA File "C:\Apps\SickRage-Master\lib3\tornado\gen.py", line 209, in wrapper
AA result = await result
AA File "C:\Apps\SickRage-Master\lib3\tornado\web.py", line 1703, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='https', host='sickchill.**********.****', method='POST', uri='/errorlogs/viewlog/', version='HTTP/1.0', remote_ip='***.***.***.***')
2020-10-13 09:23:47 ERROR :: AUTO :: Uncaught exception POST /errorlogs/viewlog/ (***.***.***.***)
2020-10-13 09:22:43 DEBUG :: AUTO :: API :: future: cur_kwargs {'limit': '1000', 'paused': '1', 'type': 'missed|today|soon|later|snatched'}
2020-10-13 09:22:43 DEBUG :: AUTO :: API :: all kwargs: '{'limit': '1000', 'cmd': 'future', 'paused': '1', 'type': 'missed|today|soon|later|snatched'}'
2020-10-13 09:22:43 DEBUG :: AUTO :: API :: all args: '()'
2020-10-13 09:22:43 DEBUG :: AUTO :: API :: ***.***.***.***- gave correct API KEY. ACCESS GRANTED
2020-10-13 09:21:23 DEBUG :: WEBSERVER-CONFIG_0 :: git describe --abbrev=0 7b98df06ad3357a377d64bf31e11db8d4e372f8f : returned successful
2020-10-13 09:21:23 DEBUG :: WEBSERVER-CONFIG_0 :: Executing git describe --abbrev=0 7b98df06ad3357a377d64bf31e11db8d4e372f8f with your shell in C:\Apps\SickRage-Master\sickchill
2020-10-13 09:21:23 DEBUG :: WEBSERVER-CONFIG_0 :: cur_commit = 7b98df06ad3357a377d64bf31e11db8d4e372f8f, newest_commit = 7b98df06ad3357a377d64bf31e11db8d4e372f8f, num_commits_behind = 0, num_commits_ahead = 0
2020-10-13 09:21:23 DEBUG :: WEBSERVER-CONFIG_0 :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2020-10-13 09:21:23 DEBUG :: WEBSERVER-CONFIG_0 :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in C:\Apps\SickRage-Master\sickchill
2020-10-13 09:21:23 DEBUG :: WEBSERVER-CONFIG_0 :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2020-10-13 09:21:22 DEBUG :: WEBSERVER-CONFIG_0 :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in C:\Apps\SickRage-Master\sickchill
2020-10-13 09:21:22 DEBUG :: WEBSERVER-CONFIG_0 :: git branch --set-upstream-to origin/master : returned successful
2020-10-13 09:21:22 DEBUG :: WEBSERVER-CONFIG_0 :: Executing git branch --set-upstream-to origin/master with your shell in C:\Apps\SickRage-Master\sickchill
2020-10-13 09:21:22 DEBUG :: WEBSERVER-CONFIG_0 :: git fetch origin --prune : returned successful
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: Executing git fetch origin --prune with your shell in C:\Apps\SickRage-Master\sickchill
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: git config remote.origin.url https://github.com/SickChill/SickChill.git : returned successful
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: Executing git config remote.origin.url https://github.com/SickChill/SickChill.git with your shell in C:\Apps\SickRage-Master\sickchill
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: git rev-parse HEAD : returned successful
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: Executing git rev-parse HEAD with your shell in C:\Apps\SickRage-Master\sickchill
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: git symbolic-ref -q HEAD : returned successful
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: Executing git symbolic-ref -q HEAD with your shell in C:\Apps\SickRage-Master\sickchill
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: git symbolic-ref -q HEAD : returned successful
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: Executing git symbolic-ref -q HEAD with your shell in C:\Apps\SickRage-Master\sickchill
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: Using: git
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: git version : returned successful
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: Executing git version with your shell in C:\Apps\SickRage-Master\sickchill
2020-10-13 09:21:20 DEBUG :: WEBSERVER-CONFIG_0 :: Checking if we can use git commands: git version
2020-10-13 09:21:16 INFO :: DAILYSEARCHER :: No new released episodes found ...
2020-10-13 09:21:16 INFO :: DAILYSEARCHER :: Searching for new released episodes ...
2020-10-13 09:20:13 INFO :: FINDSUBTITLES :: Finished checking for missed subtitles
2020-10-13 09:20:13 DEBUG :: FINDSUBTITLES :: Subtitle search for Steven Universe S03E29 delayed for 12 days, 19 hours, 3 minutes
```

**Comment by sandokanfirst** [comment]
I have the same issue on linux on Synology, on DSM 6.2. From what I read elsewhere, I start to wonder if it has something to do with the introduction of python 3(.x) into sickchill?

**Comment by PaulW** [comment]
Same issue here too, running on a RPi4.  Logs seem to stop rolling/processing, and CPU utilisation seems to hang around 20%.  The only solution to resolve this is to, as mentioned, completely restart SIckChill.

I've tried clearing out the cache.db & cache folders, checking sickchill.db for issues, running a vacuum, ensuring that permissions for files, etc, are all as they should be yet it still just randomly 'hangs', and there appears to be no pattern to it either, it can happen 5 minutes in, or 5 hours in.

**Comment by sandokanfirst** [comment]
It's rather frustrating that high severity bugs like this one aren't even acknowledged after more than half a year. I'm a long time user of first SickBeard, then Sickrage and now... nothing as I can't get SickChill to work. That is, not on Linux while I can on Windows. The development team at the time used big words about (or rather: against) the developer who ran away with the project and its name and probably rightly so, but at least his response times is within a few weeks. I appreciate all the hard (and voluntary!) work put in by @miigotu and others - still there comes a moment when you should realise you don't have the time or the energy to maintain the application to a sufficient degree. I will never consider going back to the project led by the developer whose name begins with 'ech' and ends with 'on' - there have been too many dubious practices like using resources for bitcoin mining etc - but the reality is that many nzb indexers now recommend to keep clear of SickChill.

**Comment by miigotu** [comment]
What are you saying I don't have time? Do you even look at the commit log? Not to mention, that I am also maintaining an entire ecosystem of packages (such as synology that we just got merged into synocommunity).

This bug is due to how python was compiled, not SC. I can't compile python for you.

**Comment by miigotu** [comment]
Besides the fact that this is not "high severity". High severity requires destruction of data or leaking of sensitive information.

**Comment by sandokanfirst** [comment]
@miigotu First off, I'm not saying you don't have time. I suppose you spend and have spent a lot of time on this project. Sorry if I gave you offence - I really do appreciate the work you've put into this and I think you're doing a great job. 
As a user I notice that a support forum is lacking, and that github approaches this role most closely. If users encounter these kinds of issues and go through the trouble of reporting it, it is not very encouraging if there is no feedback.

You say it's python. I do wonder if there is any way around this?

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/discussions

**Comment by sandokanfirst** [comment]
Well, that doesn't make a lot of sense to me. If you build software I take it that you want people to use it. If there are issues and these are ignored, it will drive people away. The paid indexer I use recommends against SickChill and I guess this may have something to do with a (perceived) lack of support. I've been hanging around on irc twice for more than twelve hours and didn't get a single response to my questions.
By the way, when you all split up, there was a whole team - it now seems you're doing this all by yourself? I can understand if support isn't the thing that interests you most ;)

**Comment by miigotu** [comment]
Whoever this "paid nzb indexer" that advises against SC is, if they exist, has not reached out to anyone here. And that goes directly against the dozens of indexers that prefer SC lol. But you go ahead with your bad self. Talking shit and being rude doesn't get anyone to help you that's for sure. Implying we should have a whole support forum and pay for that and likely have staff to operate it and provide support when THERE IS NO BUDGET BECAUSE THIS IS FREE SOFTWARE. Since your indexer supposedly doesn't want you to use our software and you seem to have a problem with respect (or at least decency) and cannot see yourself out I'll help you with that block now. Clown.
