### ISSUE TITLE
Uncaught exception %s %r

### ISSUE THREAD

**Issue by MastaG** [SickChill/SickChill#6845]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master / 7b98df06ad3357a377d64bf31e11db8d4e372f8f
OS: Fedora 33 - Python 3.9.0
Browser: Firefox
What you did: I've upgraded SickChill and changed it to Python 3.9.0
What happened: It's working fine, but every now and then it will give me an error:
```
2020-10-15 09:00:12 Uncaught exception %s %r
```
What you expected: No error messages
Logs:
```


AA KeyError: 'Host'
AA return self._dict[_normalized_headers[name]]
AA File "/opt/sickchill/lib3/tornado/httputil.py", line 239, in __getitem__
AA if rh.request.headers['Host'][0] == '[':
AA File "/opt/sickchill/sickchill/views/common.py", line 48, in __init__
AA t = PageTemplate(rh=self, filename="login.mako")
AA File "/opt/sickchill/sickchill/views/authentication.py", line 14, in get
AA result = method(*self.path_args, **self.path_kwargs)
AA File "/opt/sickchill/lib3/tornado/web.py", line 1701, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='127.0.0.1', method='GET', uri='/login/?next=%2F', version='HTTP/1.0', remote_ip='83.X.X.X')
2020-10-15 09:00:12 ERROR :: WEBSERVER :: Uncaught exception GET /login/?next=%2F (83.X.X.X)
AA KeyError: 'Host'
AA return self._dict[_normalized_headers[name]]
AA File "/opt/sickchill/lib3/tornado/httputil.py", line 239, in __getitem__
AA if rh.request.headers['Host'][0] == '[':
AA File "/opt/sickchill/sickchill/views/common.py", line 48, in __init__
AA t = PageTemplate(rh=self, filename="login.mako")
AA File "/opt/sickchill/sickchill/views/authentication.py", line 14, in get
AA result = method(*self.path_args, **self.path_kwargs)
AA File "/opt/sickchill/lib3/tornado/web.py", line 1701, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='127.0.0.1', method='GET', uri='/login/?next=%2F', version='HTTP/1.0', remote_ip='83.X.X.X')
2020-10-14 02:53:04 ERROR :: WEBSERVER :: Uncaught exception GET /login/?next=%2F (83.X.X.X)
AA KeyError: 'Host'
AA return self._dict[_normalized_headers[name]]
AA File "/opt/sickchill/lib3/tornado/httputil.py", line 239, in __getitem__
AA if rh.request.headers['Host'][0] == '[':
AA File "/opt/sickchill/sickchill/views/common.py", line 48, in __init__
AA t = PageTemplate(rh=self, filename="login.mako")
AA File "/opt/sickchill/sickchill/views/authentication.py", line 14, in get
AA result = method(*self.path_args, **self.path_kwargs)
AA File "/opt/sickchill/lib3/tornado/web.py", line 1701, in _execute
AA Traceback (most recent call last):
AA HTTPServerRequest(protocol='http', host='127.0.0.1', method='GET', uri='/login/?next=%2F', version='HTTP/1.0', remote_ip='83.X.X.X')
2020-10-12 20:57:51 ERROR :: WEBSERVER :: Uncaught exception GET /login/?next=%2F (83.X.X.X)
```

I'm running SickChill behind a Nginx forwarder proxy, perhaps that has something to do with it?

**Comment by Pastagazok** [comment]
Hello, I have this error too, with Python 3.7.3.
And it's been a while from the last update of SC.
I don't know if it's normal or not, or if "Boss Migotu" is busy (with his baby maybe). :)
Have a nice day.
