### ISSUE TITLE
Error while updating after upgrading to python3 - OSError: [Errno 18] Cross-device link

### ISSUE THREAD

**Issue by jellobello** [SickChill/SickChill#6865]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master/99336df163c7e776c7931d864e84d1f0f83afe4d
OS: FreeBSD-11.3-RELEASE-p9-amd64-64bit-ELF
Browser: Chrome
What you did: Successfully updated to python3 version then attempted to update from within sickchill (to remove update available message)
What happened: Update was unsuccessful due to an error in os.renames
What you expected: For the update to work correctly

After some googling I determined the issue was that I am running sickchill within an iocage jail and have the config folder mounted outside the jail as below:

```
FSTAB ENTRY                                                                                            
/mnt/RAIDZPOOL/apps/sickchill    /mnt/RAIDZPOOL/iocage/jails/sickchill/root/config        nullfs  rw      0
```

This causes an error with os.renames as it is a different filesystem.

I managed to temporarily correct the error by editing line 141 in SickChill/sickchill/update_manager/source.py from:

            sr_update_dir = os.path.join(settings.DATA_DIR, 'sr-update')

to:

            sr_update_dir = os.path.join(settings.PROG_DIR, 'sr-update')

Thus keeping the update folder within the jail.

Once the change was made the update worked as expected.

Logs with error
```
2020-10-23 13:07:49 DEBUG :: WEBSERVER-HOME_0 :: cur_commit = 99336df163c7e776c7931d864e84d1f0f83afe4d, newest_commit = fd546a06e190fa2de993e9197891de2a79f31f70, num_commits_behind = 411
2020-10-23 13:07:49 INFO :: WEBSERVER-HOME_0 :: Creating update folder /config/sr-update before extracting
2020-10-23 13:07:49 INFO :: WEBSERVER-HOME_0 :: Downloading update from https://github.com/SickChill/SickChill/tarball/master
2020-10-23 13:07:57 INFO :: WEBSERVER-HOME_0 :: Extracting file /config/sr-update/sr-update.tar
2020-10-23 13:08:01 INFO :: WEBSERVER-HOME_0 :: Deleting file /config/sr-update/sr-update.tar
2020-10-23 13:08:01 INFO :: WEBSERVER-HOME_0 :: Moving files from /config/sr-update/SickChill-SickChill-fd546a0 to /usr/local/sickchill
2020-10-23 13:08:02 DEBUG :: WEBSERVER-HOME_0 :: Traceback: Traceback (most recent call last):
  File "/usr/local/sickchill/sickchill/update_manager/source.py", line 192, in update
    os.renames(old_path, new_path)
  File "/usr/local/lib/python3.7/os.py", line 270, in renames
    rename(old, new)
OSError: [Errno 18] Cross-device link: '/config/sr-update/SickChill-SickChill-fd546a0/.dockerignore' -> '/usr/local/sickchill/.dockerignore'
```

Logs after temp fix:

```
2020-10-23 13:29:30 DEBUG :: CHECKVERSION :: cur_commit = 99336df163c7e776c7931d864e84d1f0f83afe4d, newest_commit = fd546a06e190fa2de993e9197891de2a79f31f70, num_commits_behind = 411
2020-10-23 13:29:30 DEBUG :: CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2020-10-23 13:29:42 DEBUG :: WEBSERVER-CONFIG_0 :: cur_commit = 99336df163c7e776c7931d864e84d1f0f83afe4d, newest_commit = fd546a06e190fa2de993e9197891de2a79f31f70, num_commits_behind = 411
2020-10-23 13:29:51 DEBUG :: WEBSERVER-HOME_0 :: cur_commit = 99336df163c7e776c7931d864e84d1f0f83afe4d, newest_commit = fd546a06e190fa2de993e9197891de2a79f31f70, num_commits_behind = 411
2020-10-23 13:29:51 INFO :: WEBSERVER-HOME_0 :: Creating update folder /usr/local/sickchill/sickchill/sr-update before extracting
2020-10-23 13:29:51 INFO :: WEBSERVER-HOME_0 :: Downloading update from https://github.com/SickChill/SickChill/tarball/master
2020-10-23 13:29:58 INFO :: WEBSERVER-HOME_0 :: Extracting file /usr/local/sickchill/sickchill/sr-update/sr-update.tar
2020-10-23 13:30:03 INFO :: WEBSERVER-HOME_0 :: Deleting file /usr/local/sickchill/sickchill/sr-update/sr-update.tar
2020-10-23 13:30:03 INFO :: WEBSERVER-HOME_0 :: Moving files from /usr/local/sickchill/sickchill/sr-update/SickChill-SickChill-fd546a0 to /usr/local/sickchill
2020-10-23 13:30:06 DEBUG :: WEBSERVER-HOME_0 :: Notification for Boxcar2 not enabled, skipping this notification
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Aborting all threads
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the NOTIFICATIONS thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Saving all shows to the database
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Saving config file to disk
2020-10-23 13:30:06 INFO :: EVENT-QUEUE :: Shutting down Tornado
2020-10-23 13:30:16 INFO :: EVENT-QUEUE :: Restarting SickChill with ['/usr/local/bin/python3.7', '/usr/local/sickchill/SickChill.py', '--datadir', '/config', '-d', '--pidfile', '/var/run/sickchill/sickchill.pid', '--quiet', '--nolaunch']
```

**Comment by miigotu** [comment]
Use the official iocage jail. You shouldn't be using source updater, only the git updater.

Update to TrueNAS CORE (released the other day, freenas 12)
