### ISSUE TITLE
Unable to handle numbers in show name (particularly if show ends in a number)

### ISSUE THREAD

**Issue by DragonEmbers** [SickChill/SickChill#6874]
Branch/Commit: master / fd546a06e190fa2de993e9197891de2a79f31f70
OS: Debian 10
Browser: Firefox

Why/What/Where:

I've noticed repeatedly that sickchill has issues with the numbering of episodes, particularly if the episode is:
- numbered S00Exx (doesn't like the S00 - It assumes the series is NULL and when trying to do a [series A] < [series B] comparison it errors out
- In general, if a series has a number in the end of it it (eg. Magic Kaito 1412) it doesn't like the number and won't recognise the series
- If 2 shows are simular but one has a number at the end (eg. Stiens;Gate and Stiens;Gate 0) it won't recognise the 0 as part of the series name (even though it is in the exception list) and thus recognises the show as Steins;Gate and tries (fails) to overwrite existing episodes of the non-numbered show

Particularly in the last instance:
```
2020-10-26 21:40:41 WARNING :: WEBSERVER-POSTPROCESS_0 :: Processing failed for /mnt/z/_ingress/Steins Gate 0 - 24 (1080p - 24-10-2020).mkv:
2020-10-26 21:40:41 INFO :: WEBSERVER-POSTPROCESS_0 :: File exists and new file quality is not in a preferred quality list, marking it unsafe to replace
AA IndexError: list index out of range
AA result = self._series(self.search(name, language)[0]['id'])
AA File "/mnt/z/_apps/SickChill/sickchill/show/indexers/tvdb.py", line 63, in get_series_by_name
AA result = self.indexers[i].get_series_by_name(n, indexerid, language)
AA File "/mnt/z/_apps/SickChill/sickchill/show/indexers/handler.py", line 114, in search_indexers_for_series_id
AA settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "/mnt/z/_apps/SickChill/sickchill/oldbeard/helpers.py", line 984, in get_show
AA TypeError: expected string or bytes-like object
AA return _compile(pattern, flags).match(string)
AA File "/usr/lib/python3.7/re.py", line 173, in match
AA if re.match(r'^t?t?\d{7,8}$', name) or re.match(r'^\d{6}$', name):
AA File "/mnt/z/_apps/SickChill/sickchill/show/indexers/tvdb.py", line 107, in search
AA result = target(*args, **kwargs)
AA File "/mnt/z/_apps/SickChill/sickchill/show/indexers/wrappers.py", line 21, in wrapper
2020-10-26 21:40:41 INFO :: WEBSERVER-POSTPROCESS_0 :: Processing /mnt/z/_ingress/Steins;Gate 0/Steins Gate 0 - 24 (1080p - 24-10-2020).mkv (None)
```

**Comment by DragonEmbers** [comment]
Also, I should note that I have tried ingesting the files without the date in the name (eg "[MyRip] Steins Gate 0 - 24 [1080p]") in the common naming form

**Comment by DragonEmbers** [comment]
After quite a bit of further investigation, this seems to be an issue with the way the regex's are matching. Given the number of anime based regex's there are, the possibility to screw things up by adding another generic regex is potentially massive.

**Comment by Spartanaco** [comment]
Seeing a similar error in DEBUG for POSTPROCESSOR-AUTO 

```
2020-12-25 20:28:44 DEBUG :: POSTPROCESSOR-AUTO :: Skipping already processed file: [HorribleSubs] Boku no Hero Academia - 01 [1080p].mkv
2020-12-25 20:28:44 DEBUG :: POSTPROCESSOR-AUTO :: Trying to find ['boku no hero academia horriblesubs web'] on theTVDB
2020-12-25 20:28:44 DEBUG :: POSTPROCESSOR-AUTO :: Could not find item on the indexer: (Indexer probably does not have this item) [expected string or bytes-like object]
2020-12-25 20:28:44 DEBUG :: POSTPROCESSOR-AUTO :: Traceback (most recent call last):
  File "/media/sda/home/user/SickChill/sickchill/show/indexers/wrappers.py", line 21, in wrapper
    result = target(*args, **kwargs)
  File "/media/sda/home/user/SickChill/sickchill/show/indexers/tvdb.py", line 107, in search
    if re.match(r'^t?t?\d{7,8}$', name) or re.match(r'^\d{6}$', name):
  File "/media/sda/home/user/Python-3.8.7/Lib/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

2020-12-25 20:28:44 DEBUG :: POSTPROCESSOR-AUTO :: Error when attempting to find show: Boku No Hero Academia (HorribleSubs Web in SickChill. Error: list index out of range
2020-12-25 20:28:44 DEBUG :: POSTPROCESSOR-AUTO :: Traceback (most recent call last):
  File "/media/sda/home/user/SickChill/sickchill/oldbeard/helpers.py", line 984, in get_show
    settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
  File "/media/sda/home/user/SickChill/sickchill/show/indexers/handler.py", line 114, in search_indexers_for_series_id
    result = self.indexers[i].get_series_by_name(n, indexerid, language)
  File "/media/sda/home/user/SickChill/sickchill/show/indexers/tvdb.py", line 63, in get_series_by_name
    result = self._series(self.search(name, language)[0]['id'])
IndexError: list index out of range
```

Looks like the regex grouping is a bit off for Anime in tvdb.py but I'm not sure.

**Comment by xelgand** [comment]
Think I have the same issue here.

```
2021-02-28 14:04:58 WARNING :: POSTPROCESSOR-AUTO :: Processing Failed
2021-02-28 14:04:58 WARNING :: POSTPROCESSOR-AUTO :: Processing failed for /media/downloads/complete/Anime/post/[SubsPlease] Yuru Camp S2 - 03 (720p) [2E4D6C87].mkv:
2021-02-28 14:04:58 INFO :: POSTPROCESSOR-AUTO :: Not enough information to determine what episode this is. Quitting post-processing
AA IndexError: list index out of range
AA result = self._series(self.search(name, language)[0]['id'])
AA File "/usr/local/app/sickchill/sickchill/show/indexers/tvdb.py", line 63, in get_series_by_name
AA result = self.indexers[i].get_series_by_name(n, indexerid, language)
AA File "/usr/local/app/sickchill/sickchill/show/indexers/handler.py", line 114, in search_indexers_for_series_id
AA settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "/usr/local/app/sickchill/sickchill/oldbeard/helpers.py", line 989, in get_show
AA TypeError: expected string or bytes-like object
AA return _compile(pattern, flags).match(string)
AA File "/usr/local/lib/python3.7/re.py", line 175, in match
AA if re.match(r'^t?t?\d{7,8}$', name) or re.match(r'^\d{6}$', name):
AA File "/usr/local/app/sickchill/sickchill/show/indexers/tvdb.py", line 107, in search
AA result = target(*args, **kwargs)
AA File "/usr/local/app/sickchill/sickchill/show/indexers/wrappers.py", line 21, in wrapper
2021-02-28 14:04:58 INFO :: POSTPROCESSOR-AUTO :: Processing /media/downloads/complete/Anime/post/[SubsPlease] Yuru Camp S2 - 03 (720p) [2E4D6C87].mkv (None)
```

**Comment by miigotu** [comment]
It is expected to show an error trying to match on tvdb for anime. This isn't stopping the show from working as an anime with anidb as the indexer.
