### ISSUE TITLE
Issue with postprocessing

### ISSUE THREAD

**Issue by johnkristian** [SickChill/SickChill#6876]
Branch/Commit:  Master/fd546a06e190fa2de993e9197891de2a79f31f70
OS: Windows Server 2019
Browser: Chrome
What you did: Manual Postprocessing
What happened: Postprocessing completed and did nothing. Traceback in log attached. This happends when a serie with an unaccessible path is in database
What you expected: Postprocessing completed successfully
Logs:
```
2020-10-27 16:24:42 DEBUG :: POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2020-10-27 16:24:42 INFO :: POSTPROCESSOR :: Auto post processing task for \\x.x.x.x\Dump\Download\complete was added to the queue
2020-10-27 16:24:47 INFO :: POSTPROCESSOR-AUTO :: Beginning auto post processing task: \\x.x.x.x\Dump\Download\complete
2020-10-27 16:24:47 DEBUG :: POSTPROCESSOR-AUTO :: Processing in folder \\x.x.x.x\Dump\Download\complete
2020-10-27 16:24:47 INFO :: POSTPROCESSOR-AUTO :: Processing \\x.x.x.x\Dump\Download\complete
2020-10-27 16:24:47 DEBUG :: POSTPROCESSOR-AUTO :: Processing folder \\x.x.x.x\Dump\Download\complete
2020-10-27 16:25:19 DEBUG :: POSTPROCESSOR-AUTO :: Traceback (most recent call last):
  File "ntpath.py", line 647, in realpath
FileNotFoundError: [WinError 53] The network path was not found: '\\\\x.x.y.y\\02\\02.TV\\iGenius.How.Steve.Jobs.Changed.the.World.720p.HDTV.x264-DiVERGE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SickChill\SickChill\sickchill\oldbeard\processTV.py", line 170, in process_dir
    if not validate_dir(current_directory, release_name, failed, result):
  File "C:\SickChill\SickChill\sickchill\oldbeard\processTV.py", line 268, in validate_dir
    if process_path.lower().startswith(os.path.realpath(sqlShow["location"]).lower() + os.sep) or \
  File "ntpath.py", line 651, in realpath
  File "ntpath.py", line 601, in _getfinalpathname_nonstrict
FileNotFoundError: [WinError 53] The network path was not found: '\\\\x.x.y.y\\02\\02.TV\\iGenius.How.Steve.Jobs.Changed.the.World.720p.HDTV.x264-DiVERGE'

2020-10-27 16:25:19 INFO :: POSTPROCESSOR-AUTO :: Auto post processing task for \\x.x.x.x\Dump\Download\complete completed
```

**Comment by miigotu** [comment]
I don't know what you expect to happen? It tells you it can't access the location, it cannot magically fix an offline location or a location that is denying permissions.

**Comment by johnkristian** [comment]
Yeah ... but some kind of "error processing" here is bad. It should just carry on to the next, not drop dead.

**Comment by TATUMTOT** [comment]
@joshuahiggins  What Verion of Pythin do you have installed?

**Comment by TATUMTOT** [comment]
@miigotu @johnkristian Ok after testing. I had to install Python 3.6. 

I guess python 3.7 / 3.8/ 3.9 has this issue https://github.com/gcovr/gcovr/issues/365
@miigotu That link is just to somthing else on the internets but it went in to detail of what is wrong I think but it is over my head. 

My Drive Locations are RCLONE MOUNTS. Not networks pather per say but would sort of act as such and would not present a filesystem.

My Orginal error.
AA Please make sure that all required file system drivers are loaded and that the volume is not corrupted: 'M:\\'
AA OSError: [WinError 1005] The volume does not contain a recognized file system.
AA path = _getfinalpathname(path)
AA File "E:\Python39\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
AA path = _getfinalpathname_nonstrict(path)
AA File "E:\Python39\lib\ntpath.py", line 651, in realpath
AA if process_path.lower().startswith(os.path.realpath(sqlShow["location"]).lower() + os.sep) or \
AA File "E:\SickChill\sickchill\oldbeard\processTV.py", line 268, in validate_dir
AA if not validate_dir(current_directory, release_name, failed, result):
AA File "E:\SickChill\sickchill\oldbeard\processTV.py", line 170, in process_dir
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA FileNotFoundError: [WinError 2] The system cannot find the file specified: 'M:\\(SHOWNAME)'
AA path = _getfinalpathname(path)
AA File "E:\Python39\lib\ntpath.py", line 647, in realpath
