### ISSUE TITLE
RSS custom provider gives error

### ISSUE THREAD

**Issue by lobofoots** [SickChill/SickChill#6966]
SickChill Info:
Install: pip
Version: v2020.11.24-1
Database Version: 44.2
Python Version: 3.6.12 (default, Oct 3 2020, 10:02:01) [GCC FreeBSD Clang 10.0.0 (git@github.com:llvm/llvm-project.git llvmorg-10.0.0-
SSL Version: OpenSSL 1.0.2s-freebsd 28 May 2019
OS: FreeBSD-12.2-RELEASE-p2-amd64-64bit-ELF
Locale: en_US.UTF-8

Browser: Firefox Latest

What you did: I added a custom RSS provider, tried with https://subsplease.org/rss/?r=1080 and https://subsplease.org/rss/?t&r=1080

What happened: No needed episodes found
What you expected: To be able to process this RSS feed
Logs:
```
PASTE LOGS HERE
AA ValueError: dictionary update sequence element #0 has length 1; 2 is required
AA add_dict_to_cookiejar(self.provider.session.cookies, dict(x.rsplit('=', 1) for x in self.provider.cookies.split(';')))
AA File "/usr/local/lib/python3.6/site-packages/sickchill/oldbeard/providers/rsstorrent.py", line 179, in _get_rss_data
AA data = self._get_rss_data()
AA File "/usr/local/lib/python3.6/site-packages/sickchill/oldbeard/tvcache.py", line 66, in update_cache
2021-01-16 20:07:04 DEBUG :: SEARCHQUEUE-DAILY-SEARCH :: [RSS feed for SubsPlease releases (1080p)] :: Traceback (most recent call last):
2021-01-16 20:07:04 DEBUG :: SEARCHQUEUE-DAILY-SEARCH :: [RSS feed for SubsPlease releases (1080p)] :: Error while searching RSS feed for SubsPlease releases (1080p), skipping: ValueError('dictionary update sequence element #0 has length 1; 2 is required',)
2021-01-16 20:07:04 DEBUG :: SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from ShowName

**Comment by lobofoots** [comment]
Stran gely, it is working without error today, closing for now.
