### ISSUE TITLE
Fatal error executing query with db.action in database /opt/sickchill/cache.db: near "?": syntax error

### ISSUE THREAD

**Issue by hanskokx** [SickChill/SickChill#7054]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: commit 250e847904e8334dc112ce47dc6b95f3fecd6e40 (HEAD -> master)
OS: Ubuntu 20.10
Browser:
What you did: git pull; manually start sickchill
What happened: database upgrade script blew up
What you expected: no errors
Logs:
```
2021-03-23 21:34:52 INFO :: MAIN :: Backing up database before upgrade
2021-03-23 21:34:53 INFO :: MAIN :: Proceeding with upgrade
2021-03-23 21:34:53 INFO :: MAIN :: Adding column custom_name to tvshows
2021-03-23 21:34:54 INFO :: MAIN :: Updated to: 44.2
2021-03-23 21:34:55 ERROR :: MAIN :: Fatal error executing query with db.action in database /opt/sickchill/cache.db: near "?": syntax error
2021-03-23 21:34:55 INFO :: MAIN :: If this happened in cache.db, you can safely stop SickChill, and delete the cache.db file without losing any data
2021-03-23 21:34:55 INFO :: MAIN :: Here is the arguments that were passed to this function (This is what the developers need to know): {'self': <sickchill.oldbeard.db.DBConnection object at 0x7f734e4fe760>, 'query': 'INSERT INTO results SELECT provider, name , season, episodes, indexerid, url, time, quality,release_group, version, seeders, leechers, size, status, failed, added FROM ?', 'args': ['hd4free'], 'fetchall': False, 'fetchone': False, 'sql_results': [], 'attempt': 0, 'e': OperationalError('near "?": syntax error'), 'severity': 40}
Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 463, in <module>
    SickChill().start()
  File "/opt/sickchill/SickChill.py", line 187, in start
    sickchill.start.initialize(consoleLogging=self.console_logging)
  File "/opt/sickchill/sickchill/start.py", line 819, in initialize
    db.upgrade_database(cache_db_con, cache.InitialSchema)
  File "/opt/sickchill/sickchill/oldbeard/db.py", line 454, in upgrade_database
    _process_upgrade(connection, schema)
  File "/opt/sickchill/sickchill/oldbeard/db.py", line 492, in _process_upgrade
    _process_upgrade(connection, upgradeSubClass)
  File "/opt/sickchill/sickchill/oldbeard/db.py", line 482, in _process_upgrade
    instance.execute()
  File "/opt/sickchill/sickchill/oldbeard/databases/cache.py", line 58, in execute
    self.connection.action(
  File "/opt/sickchill/sickchill/oldbeard/db.py", line 264, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "/opt/sickchill/sickchill/oldbeard/db.py", line 120, in _execute
    sql_results = self.connection.cursor().execute(query, args)
sqlite3.OperationalError: near "?": syntax error
```

**Comment by miigotu** [comment]
Stop SC and delete cache.db. Do not git pull while SC is running and/or force stop SC next time.

**Comment by hanskokx** [comment]
Yeah, that's basically how I fixed it.
