### ISSUE TITLE
Not downloading subtitles

### ISSUE THREAD

**Issue by jackkiej** [SickChill/SickChill#7142]
So I have this issue for a few months now, I think it was since I upgraded to python 3, and I also think it is a subliminal issue.
I would like to have this solved, and I think not everyone has this issue so I would like to know how to fix it.
#6919 stated the same error, but nothing has been done with it.

Branch: master
Commit: 27701a96bf26a5ba2d5a5bc45ab41b661b8bf4bb
Version: v2021.04.10-1
Database Version: 44.2
Python: 3.7.5 (default, Oct 17 2019, 12:21:00) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
SSL: OpenSSL 1.1.1d FIPS 10 Sep 2019
OS: Linux-5.3.11-100.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
Browser: Google Chrome
What you did: Search for a subtitle (automatically and manually)
What happened: Error showed up, no subtitle was found and picked up
What you expected: To find and pick up a subtitle

Logs:
```
2021-05-19 01:42:12 DEBUG :: FINDSUBTITLES :: 134511: No subtitles downloaded for Blue Mountain State S01E01
2021-05-19 01:42:12 DEBUG :: FINDSUBTITLES :: Exception caught in subliminal.scan_video for Blue Mountain State S01E01
2021-05-19 01:42:12 DEBUG :: FINDSUBTITLES :: Exception: Insufficient data to process the guess
AA ValueError: Insufficient data to process the guess
AA raise ValueError('Insufficient data to process the guess')
AA File "/home/media/sickrage/lib3/subliminal/video.py", line 189, in fromguess
AA guess_ep = subliminal.Episode.fromguess(episode.release_name, guessit(episode.release_name))
AA File "/home/media/sickrage/sickchill/oldbeard/subtitles.py", line 553, in refine_video
AA refine_video(video, episode)
AA File "/home/media/sickrage/sickchill/oldbeard/subtitles.py", line 324, in get_video
2021-05-19 01:42:12 INFO :: FINDSUBTITLES :: Traceback (most recent call last):
2021-05-19 01:42:12 DEBUG :: FINDSUBTITLES :: Checking subtitle candidates for Blue Mountain State S01E01 (Blue Mountain State - S01E01 - It's Called Hazing, Look It Up - 1080p BluRay x264 - HD4U.mkv)
2021-05-19 01:42:12 INFO :: FINDSUBTITLES :: Searching for missing subtitles of Blue Mountain State S01E01
```

**Comment by miigotu** [comment]
Either you had something rename that video, or the provider you got it from is trash. That names does not follow scene standards, so guessit cannot get all the information from it. Sickchill (and all other forks), subliminal, guessit, only work with proper scene releases, with unchanged file names.

**Comment by miigotu** [comment]
If it was `Blue.Mountain.State.S01E01.1080p.BluRay.x264-HD4U.mkv` it would have processed and downloaded subtitles.

**Comment by jackkiej** [comment]
Yeah I use the renamer.
But the thing is, I’ve used this renaming pattern for years and subtitle search did work before.

**Comment by miigotu** [comment]
No, Sick Hill keeps the name it was before it renames it, and passes THAT to subliminal. The release was renamed before it was processed into SickChill. Either by your provider or your client or idk what. If it is the provider, use another provider that follows scene rules instead. If it is your client, or some script you run before SickChill gets the download, disable that renaming.

**Comment by jackkiej** [comment]
Well, I use NzbtoMedia, not sure what my settings are right now (will look when I’m back from home). But as I said, it worked earlier before with the same settings.

**Comment by jackkiej** [comment]
nzbToMedia gives me this:

```
2021-05-19 00:02:32 POSTPROCESS::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: Processing in folder /mnt/virtual_hdd/downloads/deluge/complete/series/Blue.Mountain.State.S01.1080p.BluRay.x264-HD4U[rartv]
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: Processing /mnt/virtual_hdd/downloads/deluge/complete/series/Blue.Mountain.State.S01.1080p.BluRay.x264-HD4U[rartv]
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: Processing folder /mnt/virtual_hdd/downloads/deluge/complete/series/Blue.Mountain.State.S01.1080p.BluRay.x264-HD4U[rartv]
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: Processing /mnt/virtual_hdd/downloads/deluge/complete/series/Blue.Mountain.State.S01.1080p.BluRay.x264-HD4U[rartv]/Blue.Mountain.State.S01E06.The.Drug.Olympics.1080p.BluRay.x264-HD4U.mkv (Blue.Mountain.State.S01.1080p.BluRay.x264-HD4U[rartv])
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: Retrieving episode object for 1x6
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: Snatch history had a quality in it, using that: 1080p BluRay
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: SC snatched this episode and it is not processed before
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: Is ep a priority download: True
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: There is no existing file so there's no worries about replacing it
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: This download is marked a priority download so I'm going to replace an existing file if I find one
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: Found release name Blue.Mountain.State.S01.1080p.BluRay.x264-HD4U[rartv]
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: Destination folder for this episode: /mnt/virtual_hdd/plex/series/Blue Mountain State/Season 01
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: No associated files for /mnt/virtual_hdd/downloads/deluge/complete/series/Blue.Mountain.State.S01.1080p.BluRay.x264-HD4U[rartv]/Blue.Mountain.State.S01E06.The.Drug.Olympics.1080p.BluRay.x264-HD4U.mkv were found during this pass
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: Moving file from /mnt/virtual_hdd/downloads/deluge/complete/series/Blue.Mountain.State.S01.1080p.BluRay.x264-HD4U[rartv]/Blue.Mountain.State.S01E06.The.Drug.Olympics.1080p.BluRay.x264-HD4U.mkv to /mnt/virtual_hdd/plex/series/Blue Mountain State/Season 01/Blue Mountain State - S01E06 - The Drug Olympics - 1080p BluRay x264 - HD4U.mkv
2021-05-19 00:03:10 POSTPROCESS::SICKBEARD: Processing succeeded for /mnt/virtual_hdd/downloads/deluge/complete/series/Blue.Mountain.State.S01.1080p.BluRay.x264-HD4U[rartv]/Blue.Mountain.State.S01E06.The.Drug.Olympics.1080p.BluRay.x264-HD4U.mkv
```

It uses the naming pattern I've set in SickChill: Season %0S/%SN - S%0SE%0E - %EN - %SQN - %RG

**Comment by jackkiej** [comment]
My bad, yes it is working. But not all the time, and I can't figure out why, I've tested it with a WEB-DL version from another show which works fine..

```
2021-05-19 12:10:23 DEBUG :: WEBSERVER-HOME_0 :: Notification for NMJ scan update not enabled, skipping this notification
2021-05-19 12:10:23 DEBUG :: WEBSERVER-HOME_0 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Walking Dead - S10E01 - Lines We Cross
2021-05-19 12:10:23 DEBUG :: WEBSERVER-HOME_0 :: Episode has no release group, replacing it with 'CasStudio'
2021-05-19 12:10:23 DEBUG :: WEBSERVER-HOME_0 :: Found codec for 'The Walking Dead: Lines We Cross'.
2021-05-19 12:10:23 DEBUG :: WEBSERVER-HOME_0 :: Parsed The.Walking.Dead.S10E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-CasStudio into The Walking Dead - S10E01 [GROUP: CasStudio] [ABD: False] [ANIME: False] [whichReg: ['standard']] Score: 5
2021-05-19 12:10:23 DEBUG :: WEBSERVER-HOME_0 :: Parsed /mnt/virtual_hdd/plex/series/The Walking Dead/Season 10/The Walking Dead - S10E01 - Lines We Cross - 1080p WEB-DL h264 - CasStudio into The Walking Dead - S10E01 [ABD: False] [ANIME: False] [whichReg: ['standard', 'season_only']] Score: -2
2021-05-19 12:10:23 DEBUG :: WEBSERVER-HOME_0 :: 153021: Downloaded English subtitles for The Walking Dead S10E01
2021-05-19 12:10:23 DEBUG :: WEBSERVER-HOME_0 :: history.logSubtitle podnapisi, eng
2021-05-19 12:10:22 DEBUG :: WEBSERVER-HOME_0 :: [tvsubtitles] Subtitle score for 309935 is: 773 (min=213)
2021-05-19 12:10:22 DEBUG :: WEBSERVER-HOME_0 :: [shooter] Subtitle score for https://www.shooter.cn/api/subapi.php?fetch=MTYyMTQxNzc4M3wzVGRERkVRV3AtVHEtMm9hY3VtOEVjLXhtckdNY0FDUjVuWXJOZGo1M0lRUUNNN3cxOEdXSWFQUUNYVk03MlhqVEZUb2ZQa1BTd3MwSkVKN0NraHRwdDQtX2xqS2lISVN4NmZwN2M4b2EtYld0TGY5NHFNaE9lVEpWX0ZsQVNZbWVwd3k4Q25kbWl2SGh0SmNDM25iQzExYzF5WWxMamNyZVFZYzlWb3NXOUctQlZBVTB3ZUJXMzJiTVdsVzZOZ0pLWmlzSkRiODhSUT181KwzFiCd9b-3uXX_M9kX81sFut8fk8-Z_W2kRiLH0Sc=&nonce=%B6%FDaj%16%3D%CD.%10%9A%9A%85a%F3.%07 is: 810 (min=213)
2021-05-19 12:10:22 DEBUG :: WEBSERVER-HOME_0 :: [shooter] Subtitle score for https://www.shooter.cn/api/subapi.php?fetch=MTYyMTQxNzc4M3x6SDRMaTBJekg3WjlQRzMzNEQ4d1M0R3A4T2ZERVk3Wi1QUUxPMUFtR0RvR0NWcVl6UHZLaUducUFYN09BakpuYk1vdXJ1Ri13b3ZmVDlQejdoME9udE1VaHh2OUxjLUdvaTRqLWh4STFuN3JzUnMtTkRVR3hrUkRmVFVRbTV6RVhnTWtTd0V0REJicnZvbDZjZkFwa3huSkQwRkhlRDM2bm1Tb0JYaENhcWdjeG1mci1GZER6UUJFSTBKVUFIVTNzcnBnQ1EzLWoyTT18-BEZoCpER1_FyXEiccNWf2ygcBGhD9vCUYOGQ9O_g1A=&nonce=%0F%DC%3B%D0f%AF%0E%BF%5B%40%CC%FD%9A%A6c%94 is: 810 (min=213)
2021-05-19 12:10:22 DEBUG :: WEBSERVER-HOME_0 :: [podnapisi] Subtitle score for ajNG is: 777 (min=213)
2021-05-19 12:10:22 DEBUG :: WEBSERVER-HOME_0 :: [podnapisi] Subtitle score for azNG is: 776 (min=213)
2021-05-19 12:10:22 DEBUG :: WEBSERVER-HOME_0 :: [podnapisi] Subtitle score for kzVG is: 809 (min=213)
2021-05-19 12:10:22 DEBUG :: WEBSERVER-HOME_0 :: [podnapisi] Subtitle score for pDVG is: 810 (min=213)
2021-05-19 12:10:21 DEBUG :: WEBSERVER-HOME_0 :: Could not search in thesubdb provider. Discarding for now
2021-05-19 12:10:21 DEBUG :: WEBSERVER-HOME_0 :: Could not search in legendastv provider. Discarding for now
2021-05-19 12:10:21 DEBUG :: WEBSERVER-HOME_0 :: Could not search in opensubtitles provider. Discarding for now
2021-05-19 12:10:21 DEBUG :: WEBSERVER-HOME_0 :: Could not search in addic7ed provider. Discarding for now
2021-05-19 12:10:18 DEBUG :: WEBSERVER-HOME_0 :: Checking subtitle candidates for The Walking Dead S10E01 (The Walking Dead - S10E01 - Lines We Cross - 1080p WEB-DL h264 - CasStudio.mkv)
2021-05-19 12:08:29 DEBUG :: WEBSERVER-HOME_0 :: 134511: No subtitles downloaded for Blue Mountain State S01E01
2021-05-19 12:08:29 DEBUG :: WEBSERVER-HOME_0 :: Exception caught in subliminal.scan_video for Blue Mountain State S01E01
2021-05-19 12:08:29 DEBUG :: WEBSERVER-HOME_0 :: Exception: Insufficient data to process the guess
AA ValueError: Insufficient data to process the guess
AA raise ValueError('Insufficient data to process the guess')
AA File "/home/media/sickrage/lib3/subliminal/video.py", line 189, in fromguess
AA guess_ep = subliminal.Episode.fromguess(episode.release_name, guessit(episode.release_name))
AA File "/home/media/sickrage/sickchill/oldbeard/subtitles.py", line 553, in refine_video
AA refine_video(video, episode)
AA File "/home/media/sickrage/sickchill/oldbeard/subtitles.py", line 324, in get_video
2021-05-19 12:08:29 INFO :: WEBSERVER-HOME_0 :: Traceback (most recent call last):
2021-05-19 12:08:29 DEBUG :: WEBSERVER-HOME_0 :: Checking subtitle candidates for Blue Mountain State S01E01 (Blue Mountain State - S01E01 - It's Called Hazing, Look It Up - 1080p BluRay x264 - HD4U.mkv)
```

**Comment by miigotu** [comment]
Maybe there is no subtitle available for that release in your desired language. We simply pass the release name to subliminal with desired language and provider settings.

**Comment by jackkiej** [comment]
Here I can find the subtitle in my language:
[https://www.opensubtitles.org/nl/subtitles/5274346/blue-mountain-state-it-s-called-hazing-look-it-up-nl](https://www.opensubtitles.org/nl/subtitles/5274346/blue-mountain-state-it-s-called-hazing-look-it-up-nl)
Besides, I have enabled subtitle download for english and dutch, when I active the "CC" button in show overview it should search for both languages.

If I search for Blue Mountain State S01E01 Bluray:

```
2021-05-19 16:38:04 DEBUG :: WEBSERVER-HOME_0 :: 134511: No subtitles downloaded for Blue Mountain State S01E01
2021-05-19 16:38:03 DEBUG :: WEBSERVER-HOME_0 :: Exception caught in subliminal.scan_video for Blue Mountain State S01E01
2021-05-19 16:38:03 DEBUG :: WEBSERVER-HOME_0 :: Exception: Insufficient data to process the guess
AA ValueError: Insufficient data to process the guess
AA raise ValueError('Insufficient data to process the guess')
AA File "/home/media/sickrage/lib3/subliminal/video.py", line 189, in fromguess
AA guess_ep = subliminal.Episode.fromguess(episode.release_name, guessit(episode.release_name))
AA File "/home/media/sickrage/sickchill/oldbeard/subtitles.py", line 553, in refine_video
AA refine_video(video, episode)
AA File "/home/media/sickrage/sickchill/oldbeard/subtitles.py", line 324, in get_video
2021-05-19 16:38:03 INFO :: WEBSERVER-HOME_0 :: Traceback (most recent call last):
2021-05-19 16:38:03 DEBUG :: WEBSERVER-HOME_0 :: Checking subtitle candidates for Blue Mountain State S01E01 (Blue Mountain State - S01E01 - It's Called Hazing, Look It Up - 1080p Bluray x264 - HD4U.mkv)
```
If I search for TWD S10E01 WEB-DL it works fine
```
2021-05-19 16:40:10 DEBUG :: WEBSERVER-HOME_0 :: Notification for NMJ scan update not enabled, skipping this notification
2021-05-19 16:40:10 DEBUG :: WEBSERVER-HOME_0 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Walking Dead - S10E01 - Lines We Cross
2021-05-19 16:40:10 DEBUG :: WEBSERVER-HOME_0 :: Found codec for 'The Walking Dead: Lines We Cross'.
2021-05-19 16:40:10 DEBUG :: WEBSERVER-HOME_0 :: Parsed The.Walking.Dead.S10E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-CasStudio into The Walking Dead - S10E01 [GROUP: CasStudio] [ABD: False] [ANIME: False] [whichReg: ['standard']] Score: 5
2021-05-19 16:40:10 DEBUG :: WEBSERVER-HOME_0 :: Parsed /mnt/virtual_hdd/plex/series/The Walking Dead/Season 10/The Walking Dead - S10E01 - Lines We Cross - 1080p WEB-DL h264 - CasStudio into The Walking Dead - S10E01 [ABD: False] [ANIME: False] [whichReg: ['standard', 'season_only']] Score: -2
2021-05-19 16:40:10 DEBUG :: WEBSERVER-HOME_0 :: 153021: Downloaded Dutch subtitles for The Walking Dead S10E01
2021-05-19 16:40:09 DEBUG :: WEBSERVER-HOME_0 :: history.logSubtitle opensubtitles, dut
2021-05-19 16:40:09 DEBUG :: WEBSERVER-HOME_0 :: [opensubtitles] Subtitle score for 1957183917 is: 775 (min=213)
2021-05-19 16:40:09 DEBUG :: WEBSERVER-HOME_0 :: [opensubtitles] Subtitle score for 1956490722 is: 777 (min=213)
2021-05-19 16:40:09 DEBUG :: WEBSERVER-HOME_0 :: [opensubtitles] Subtitle score for 1956487133 is: 810 (min=213)
2021-05-19 16:40:09 DEBUG :: WEBSERVER-HOME_0 :: Could not search in thesubdb provider. Discarding for now
2021-05-19 16:40:09 DEBUG :: WEBSERVER-HOME_0 :: Could not search in addic7ed provider. Discarding for now
2021-05-19 16:39:56 DEBUG :: WEBSERVER-HOME_0 :: Checking subtitle candidates for The Walking Dead S10E01 (The Walking Dead - S10E01 - Lines We Cross - 1080p WEB-DL h264 - CasStudio.mkv)
```

Maybe it has something to do with guessit or subliminal acting strange with the source? WEB-DL works perfectly, Bluray is acting strange, could also be because scenegroup is HD4U?

**Comment by jackkiej** [comment]
@miigotu Could you still take a look?

**Comment by miigotu** [comment]
Subliminal is not our code, we just pass the release name to it and of it doesn't have enough money information that's out of our hands.

**Comment by jackkiej** [comment]
> Subliminal is not our code, we just pass the release name to it and of it doesn't have enough money information that's out of our hands.

But that is just the issue, subliminal works fine with the same information.. If I do it manually it works, in SickRage it does not..

**Comment by jackkiej** [comment]
@miigotu please listen, I just can't figure it out and I really don't understand how this happens.
House S04E05 is from a Season pack, SickChill > Deluge > nzbToMedia > SickChill
The Good Doctor S04E16 is from Episode search, SickChill > Deluge > nzbToMedia > SickChill

They both are renamed the exact same way, and post-processing was exactly the same:
House - S04E05 - Mirror, Mirror - 1080p BluRay x264 - BRAVERY.mkv
The Good Doctor - S04E16 - Dr. Ted - 1080p WEB-DL h264 - STRONTiUM.mkv

The only 2 differences are that the House episode is from a Season Pack search, and that it is a BluRay version.

Logs while searching for subtitles:

House S04E05:
```
2021-08-31 15:19:51 DEBUG :: WEBSERVER-HOME_0 :: 73255: No subtitles downloaded for House S04E05
2021-08-31 15:19:51 DEBUG :: WEBSERVER-HOME_0 :: Exception caught in subliminal.scan_video for House S04E05
2021-08-31 15:19:51 DEBUG :: WEBSERVER-HOME_0 :: Exception: Insufficient data to process the guess
AA ValueError: Insufficient data to process the guess
AA raise ValueError('Insufficient data to process the guess')
AA File "/home/media/sickrage/.venv/lib/python3.7/site-packages/subliminal/video.py", line 189, in fromguess
AA guess_ep = subliminal.Episode.fromguess(episode.release_name, guessit(episode.release_name))
AA File "/home/media/sickrage/sickchill/oldbeard/subtitles.py", line 553, in refine_video
AA refine_video(video, episode)
AA File "/home/media/sickrage/sickchill/oldbeard/subtitles.py", line 324, in get_video
2021-08-31 15:19:51 INFO :: WEBSERVER-HOME_0 :: Traceback (most recent call last):
2021-08-31 15:19:50 DEBUG :: WEBSERVER-HOME_0 :: Checking subtitle candidates for House S04E05 (House - S04E05 - Mirror, Mirror - 1080p BluRay x264 - BRAVERY.mkv)
2021-08-31 15:19:44 DEBUG :: WEBSERVER-HOME_0 :: exceptions_cache: {-1: ['House', 'House M D', 'house']}
2021-08-31 15:19:44 DEBUG :: WEBSERVER-HOME_0 :: get_scene_exceptions: ['house', 'House M D', 'House']
```

The Good Doctor S04E16:
```
2021-08-31 15:46:36 DEBUG :: WEBSERVER-HOME_0 :: Notification for NMJ scan update not enabled, skipping this notification
2021-08-31 15:46:36 DEBUG :: WEBSERVER-HOME_0 :: formatting pattern: %SN - S%0SE%0E - %EN -> The Good Doctor - S04E16 - Dr. Ted
2021-08-31 15:46:36 DEBUG :: WEBSERVER-HOME_0 :: Found codec for 'The Good Doctor: Dr. Ted'.
2021-08-31 15:46:36 DEBUG :: WEBSERVER-HOME_0 :: Using cached parse result for: The.Good.Doctor.S04E16.1080p.WEB.H264-STRONTiUM
2021-08-31 15:46:36 DEBUG :: WEBSERVER-HOME_0 :: Parsed /mnt/virtual_hdd/plex/series/The Good Doctor/Season 04/The Good Doctor - S04E16 - Dr. Ted - 1080p WEB-DL h264 - STRONTiUM into The Good Doctor - S04E16 [ABD: False] [ANIME: False] [whichReg: ['standard', 'season_only']] Score: -2
2021-08-31 15:46:36 DEBUG :: WEBSERVER-HOME_0 :: 328634: Downloaded Dutch subtitles for The Good Doctor S04E16
2021-08-31 15:46:36 DEBUG :: WEBSERVER-HOME_0 :: history.logSubtitle opensubtitles, dut
2021-08-31 15:46:35 DEBUG :: WEBSERVER-HOME_0 :: [opensubtitles] Subtitle score for 1957236459 is: 792 (min=213)
2021-08-31 15:46:35 DEBUG :: WEBSERVER-HOME_0 :: [opensubtitles] Subtitle score for 1957231150 is: 768 (min=213)
2021-08-31 15:46:35 DEBUG :: WEBSERVER-HOME_0 :: [opensubtitles] Subtitle score for 1957230234 is: 775 (min=213)
2021-08-31 15:46:35 DEBUG :: WEBSERVER-HOME_0 :: [opensubtitles] Subtitle score for 1957236459 is: 810 (min=213)
2021-08-31 15:46:35 DEBUG :: WEBSERVER-HOME_0 :: Could not search in thesubdb provider. Discarding for now
2021-08-31 15:46:21 DEBUG :: WEBSERVER-HOME_0 :: Checking subtitle candidates for The Good Doctor S04E16 (The Good Doctor - S04E16 - Dr. Ted - 1080p WEB-DL h264 - STRONTiUM.mkv)
2021-08-31 15:46:00 DEBUG :: WEBSERVER-HOME_0 :: exceptions_cache: {-1: ['the good doctor']}
2021-08-31 15:46:00 DEBUG :: WEBSERVER-HOME_0 :: get_scene_exceptions: ['the good doctor']
```

**Comment by msurg** [comment]
> Subliminal is not our code, we just pass the release name to it and of it doesn't have enough money information that's out of our hands.

Could it be the reason how you pass the release name to subliminal? With subliminal command line all is working fine with Turkish subtitles.

eg

`subliminal --opensubtitles user password download -s -l tur "The Good Doctor - S04E16 - Dr. Ted - 1080p WEB-DL h264 - STRONTiUM.mkv"`

`subliminal --opensubtitles user password download -s -l tur "Blue Mountain State - S01E01 - It's Called Hazing, Look It Up - 1080p BluRay x264 - HD4U.mkv"`

`subliminal --opensubtitles user password download -s -l tur "1883-S01E02 -Behind Us, A Cliff-720p_WEB_DL-NTb.mkv"`


All these subtitles download fine with these subliminal commands. Please note quotation marks at the beginning and at the and of the file name.

**Comment by jackkiej** [comment]
> > Subliminal is not our code, we just pass the release name to it and of it doesn't have enough money information that's out of our hands.
> 
> Could it be the reason how you pass the release name to subliminal? With subliminal command line all is working fine with Turkish subtitles.
> 
> eg
> 
> `subliminal --opensubtitles user password download -s -l tur "The Good Doctor - S04E16 - Dr. Ted - 1080p WEB-DL h264 - STRONTiUM.mkv"`
> 
> `subliminal --opensubtitles user password download -s -l tur "Blue Mountain State - S01E01 - It's Called Hazing, Look It Up - 1080p BluRay x264 - HD4U.mkv"`
> 
> `subliminal --opensubtitles user password download -s -l tur "1883-S01E02 -Behind Us, A Cliff-720p_WEB_DL-NTb.mkv"`
> 
> All these subtitles download fine with these subliminal commands. Please note quotation marks at the beginning and at the and of the file name.

Problem lies in Season packs, try download a season pack instead of an episode alone.

**Comment by msurg** [comment]
I can't even download for individual episodes when I click on cc (search subtitles) in search column on show page. But can download with subliminal CLI

Here is the part of Sickchill log file

<pre>
2022-01-11 19:49:20 DEBUG :: WEBSERVER-HOME_0 :: Checking subtitle candidates for 1883 S01E02 (1883-S01E02-Behind Us, A Cliff-720p_WEB_DL-NTb.mkv)
2022-01-11 19:49:20 DEBUG :: WEBSERVER-HOME_0 :: Unable to set <class 'subliminal.video.Episode'>.episode from episode.episode attribute
2022-01-11 19:49:21 DEBUG :: WEBSERVER-HOME_0 :: No subtitles found for 1883 S01E02
2022-01-11 19:49:21 DEBUG :: WEBSERVER-HOME_0 :: 396390: No subtitles downloaded for 1883 S01E02
</pre>

**Comment by jackkiej** [comment]
I can confirm that with Season Packs, the problem lied in the renaming.
Just got a new season pack from House, without the renamer activated, and got no problems searching subtitles.

Why this happens with Season Packs and not with Episodes I don't know, but for now I will just stop using the renamer.

**Comment by miigotu** [comment]
> I can confirm that with Season Packs, the problem lied in the renaming.
> Just got a new season pack from House, without the renamer activated, and got no problems searching subtitles.
> 
> Why this happens with Season Packs and not with Episodes I don't know, but for now I will just stop using the renamer.

I wonder if we are putting the season pack release name as the release name for every file, and using that instead of the individual file names, or if we are using both. Check the show page and see what the release name for each file of the season is, that's what we send.

**Comment by jackkiej** [comment]
> > I can confirm that with Season Packs, the problem lied in the renaming.
> > Just got a new season pack from House, without the renamer activated, and got no problems searching subtitles.
> > Why this happens with Season Packs and not with Episodes I don't know, but for now I will just stop using the renamer.
> 
> I wonder if we are putting the season pack release name as the release name for every file, and using that instead of the individual file names, or if we are using both. Check the show page and see what the release name for each file of the season is, that's what we send.

This is what I have on the show page:

![Schermafbeelding 2022-05-03 192733](https://user-images.githubusercontent.com/1876996/166507104-a16d242b-dcf5-4312-8dd7-8d02d64e8ecc.png)

**Comment by miigotu** [comment]
> > I wonder if we are putting the season pack release name as the release name for every file, and using that instead of the individual file names, or if we are using both. Check the show page and see what the release name for each file of the season is, that's what we send.
> 
> This is what I have on the show page:
> 
> ![Schermafbeelding 2022-05-03 192733](https://user-images.githubusercontent.com/1876996/166507104-a16d242b-dcf5-4312-8dd7-8d02d64e8ecc.png)
> 
> Season 5 pack was with renamer, season 6 pack without renamer.

Put your mouse over the file name and it will show the release name in a pop-up

**Comment by jackkiej** [comment]
> 

You mean this?

![Schermafbeelding 2022-05-07 170435](https://user-images.githubusercontent.com/1876996/167260101-994e01f7-17fb-4234-a6a1-48382c2c3d57.png)

**Comment by miigotu** [comment]
Yes but over the location, to show the original file release name

**Comment by jackkiej** [comment]
> Yes but over the location, to show the original file release name

When I hover over file name nothing pops up, even changed language to english, but nothing pops up.
Only places where something pops up is at episode number (as shown here above) and "i" at episode name (summary of the episode).

**Comment by miigotu** [comment]
I guess that feature is not there anymore?

Try it this way:
`
sqlite3 ~/.config/sickchill/sickchill.db "select release_name, location from tv_episodes where showid = <tvdbid> and season = <season_number>;"
`

for example, for vikings:
`
sqlite3 /path/to/sickchill.db "select release_name, location from tv_episodes where showid = 260449 and season = 6;"
`

Paste the output from a season that does not work (has been renamed) and one that does (has not been renamed) on the same show.

**Comment by jackkiej** [comment]
> 
![Schermafbeelding 2022-05-10 235639](https://user-images.githubusercontent.com/1876996/167728753-6e7d9731-87d4-45e4-9628-b267337c9e64.png)
![Schermafbeelding 2022-05-10 235702](https://user-images.githubusercontent.com/1876996/167728757-b964cc29-d4a2-471b-aeab-16e6de74bf63.png)

**Comment by miigotu** [comment]
@jackkiej that confirms what I expected, we save the release name of the whole season pack instead of the name of the file. Im not sure off the top of my head how I can fix it but I will take a look.

**Comment by miigotu** [comment]
I need to do some more work to that branch, so it isnt ready yet. I'll let you know when you can test.
