### ISSUE TITLE
Exception in trakt sync when option 'remove watched and ended' is enabled

### ISSUE THREAD

**Issue by Pandabehr** [SickChill/SickChill#7163]
Branch/Commit: master / abe2dd7c6
OS: raspbian
Browser: chrome
What you did: enabled the option 'remove the show from sickchill if it's ended and completely watched'
What happened: a stacktrace in my log, no shows added or removed from sickchill
What you expected: shows added & removed from my sickchill
Logs:
```
AA ValueError: cannot switch from manual field specification to automatic field numbering
AA "Could not check trakt progress for {0} because the imdb id is missing from {} data, skipping".format(show.name, show.idxr.name)
AA File "/opt/sickchill/sickchill/oldbeard/traktChecker.py", line 356, in removeShowFromSickChill
AA self.removeShowFromSickChill()
AA File "/opt/sickchill/sickchill/oldbeard/traktChecker.py", line 225, in syncWatchlist
AA self.syncWatchlist()
AA File "/opt/sickchill/sickchill/oldbeard/traktChecker.py", line 59, in run
2021-06-06 10:24:28 DEBUG :: TRAKTCHECKER :: Traceback (most recent call last):
2021-06-06 10:24:24 DEBUG :: TRAKTCHECKER :: SHOW_SICKCHILL::REMOVE::START - Look for Shows to remove from SickChill
2021-06-06 10:24:24 DEBUG :: TRAKTCHECKER :: Sync SickChill with Trakt Watchlist
2021-06-06 10:24:24 DEBUG :: TRAKTCHECKER :: Starting new thread: TRAKTCHECKER
```

**Comment by miigotu** [comment]
Will merge to master asap
