### ISSUE TITLE
SickChill fails to start after update.

### ISSUE THREAD

**Issue by bjwest** [SickChill/SickChill#7179]
Branch/Commit: Unknown, updated 16 June@1513CST.  version.py states __version__ = "2021.5.10-1"
OS: Ubuntu Server 20.04
Browser: Firefox
What you did: Updated SickChill via message at top.
What happened: SickChill updated then failed to restart.
What you expected: SickChill starts normally.
Logs:  Relevant portion of log (last entry):
```
2021-06-16 15:13:28 INFO :: EVENT-QUEUE :: Aborting all threads
2021-06-16 15:13:28 INFO :: EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2021-06-16 15:13:29 INFO :: EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2021-06-16 15:13:30 INFO :: EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2021-06-16 15:13:30 INFO :: EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2021-06-16 15:13:30 INFO :: EVENT-QUEUE :: Waiting for the REFRESH thread to exit
2021-06-16 15:13:30 INFO :: EVENT-QUEUE :: Waiting for the SEARCHQUEUE-DAILY-SEARCH thread to exit
2021-06-16 15:13:30 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2021-06-16 15:13:30 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR-AUTO thread to exit
2021-06-16 15:13:30 INFO :: EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2021-06-16 15:13:30 INFO :: EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2021-06-16 15:13:30 INFO :: EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2021-06-16 15:13:30 INFO :: EVENT-QUEUE :: Waiting for the NOTIFICATIONS thread to exit
2021-06-16 15:13:30 INFO :: EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2021-06-16 15:13:30 INFO :: EVENT-QUEUE :: Saving all shows to the database
2021-06-16 15:13:38 INFO :: EVENT-QUEUE :: Saving config file to disk
2021-06-16 15:13:39 INFO :: EVENT-QUEUE :: Shutting down Tornado
2021-06-16 15:13:49 INFO :: EVENT-QUEUE :: Restarting SickChill with ['/usr/bin/python3', '/opt/SickChill/SickChill.py', '-q', '--daemon', '--nolaunch', '--datadir=/opt/SickChill']
```
Console output when started from systemd:
```
xxxxx@******:~$ systemctl start sickchill.service
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'sickchill.service'.
Authenticating as: xxxxx (xxxxx)
Password: 
==== AUTHENTICATION COMPLETE ===
Job for sickchill.service failed because the control process exited with error code.
See "systemctl status sickchill.service" and "journalctl -xe" for details.
xxxxx@******:~$ systemctl status sickchill.service
● sickchill.service - SickChill Daemon
     Loaded: loaded (/lib/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-06-16 16:39:04 CDT; 10s ago
    Process: 6772 ExecStart=/usr/bin/python3 /opt/SickChill/SickChill.py -q --daemon --nolaunch --datadir=/opt/SickChill (code=exited, status=1/FAILURE)

Jun 16 16:39:03 ****** python3[6772]:   File "/opt/SickChill/sickchill/oldbeard/show_name_helpers.py", line 10, in <module>
Jun 16 16:39:03 ****** python3[6772]:     from .name_parser.parser import InvalidNameException, InvalidShowException, NameParser
Jun 16 16:39:03 ****** python3[6772]:   File "/opt/SickChill/sickchill/oldbeard/name_parser/parser.py", line 23, in <module>
Jun 16 16:39:03 ****** python3[6772]:     class NameParser(object):
Jun 16 16:39:03 ****** python3[6772]:   File "/opt/SickChill/sickchill/oldbeard/name_parser/parser.py", line 28, in NameParser
Jun 16 16:39:03 ****** python3[6772]:     def __init__(self, filename: bool = True, showObj: TVShow = None, tryIndexers: bool = False, naming_pattern: bool = False>
Jun 16 16:39:03 ****** python3[6772]: NameError: name 'TVShow' is not defined
Jun 16 16:39:04 ****** systemd[1]: sickchill.service: Control process exited, code=exited, status=1/FAILURE
Jun 16 16:39:04 ****** systemd[1]: sickchill.service: Failed with result 'exit-code'.
Jun 16 16:39:04 ****** systemd[1]: Failed to start SickChill Daemon.
```
Console output when manually started:
```
xxxxx@******:~$ /usr/bin/python3 /opt/SickChill/SickChill.py -q --daemon --nolaunch --datadir=/opt/SickChill
/opt/SickChill/sickchill/locale
/opt/SickChill/sickchill/locale
Traceback (most recent call last):
  File "/opt/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/SickChill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/SickChill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/SickChill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/opt/SickChill/sickchill/tv.py", line 19, in <module>
    import sickchill.oldbeard.providers
  File "/opt/SickChill/sickchill/oldbeard/providers/__init__.py", line 6, in <module>
    from sickchill.oldbeard.providers import (
  File "/opt/SickChill/sickchill/oldbeard/providers/abnormal.py", line 8, in <module>
    from sickchill.oldbeard import tvcache
  File "/opt/SickChill/sickchill/oldbeard/tvcache.py", line 10, in <module>
    from . import db, show_name_helpers
  File "/opt/SickChill/sickchill/oldbeard/show_name_helpers.py", line 10, in <module>
    from .name_parser.parser import InvalidNameException, InvalidShowException, NameParser
  File "/opt/SickChill/sickchill/oldbeard/name_parser/parser.py", line 23, in <module>
    class NameParser(object):
  File "/opt/SickChill/sickchill/oldbeard/name_parser/parser.py", line 28, in NameParser
    def __init__(self, filename: bool = True, showObj: TVShow = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):
NameError: name 'TVShow' is not defined
```

**Comment by bink999999** [comment]
Broken for me as well. uninstalled/reinstalled. not working. total fail.

**Comment by kyuuk** [comment]
same as #7177

**Comment by bjwest** [comment]
The workaround in #7177 worked for me.  Sorry for the duplicate report, it took me a while to gather everything and I guess #7177 snuck in there while I was doing writing this one.
