### ISSUE TITLE
 SickChill NameError: name 'TVShow' is not defined

### ISSUE THREAD

**Issue by Dimas-sc** [SickChill/SickChill#7248]
**Setup**

Package Name: SickChill
Package Version: 20210329-1
NAS Model: DS214
NAS Architecture:
DSM version: 6.2.4-25556

Expected behavior: Chickchill doesn't start
Actual behavior: Chickchill doesn't start
Steps to reproduce: Try to start/run

Log:

Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
Traceback (most recent call last):
File "/volume1/@appstore/sickchill/share/SickChill/SickChill.py", line 14, in
import sickchill.start
File "/volume1/@appstore/sickchill/share/SickChill/sickchill/init.py", line 1, in
from .show.indexers import indexer, ShowIndexer
File "/volume1/@appstore/sickchill/share/SickChill/sickchill/show/indexers/init.py", line 1, in
from .handler import ShowIndexer
File "/volume1/@appstore/sickchill/share/SickChill/sickchill/show/indexers/handler.py", line 5, in
from sickchill.tv import Show, TVEpisode
File "/volume1/@appstore/sickchill/share/SickChill/sickchill/tv.py", line 19, in
import sickchill.oldbeard.providers
File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/providers/init.py", line 6, in
from sickchill.oldbeard.providers import (
File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/providers/abnormal.py", line 8, in
from sickchill.oldbeard import tvcache
File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/tvcache.py", line 10, in
from . import db, show_name_helpers
File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/show_name_helpers.py", line 10, in
from .name_parser.parser import InvalidNameException, InvalidShowException, NameParser
File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/name_parser/parser.py", line 23, in
class NameParser(object):
File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/name_parser/parser.py", line 28, in NameParser
def init(self, filename: bool = True, showObj: TVShow = None, tryIndexers: bool = False, naming_pattern: bool = False, parse_method: str = None):
NameError: name 'TVShow' is not defined

**Comment by miigotu** [comment]
This is an old error like 2 weeks or so ago that has been fixed.
Since the package is not using a git repository and uses a tarball, you will have to do some wonky work:

  1. Download https://github.com/SickChill/SickChill/archive/refs/heads/master.zip using download station
  2. Using file station, right click and "extract here". rename the folder from SickChill-master to SickChill

  3.  Command line:
```bash
# ssh in to the synology 
ssh username@synoip
# enter password, you will get some error about "Could not chdir to home directory", ignore the error

# save the original dir just in case, you can delete this SickChill_OLD dir once SC is running again (this is not where your data is)
sudo mv /var/packages/sickchill/target/share/SickChill /var/packages/sickchill/target/share/SickChill_OLD

# make sure this is the correct Download folder you extracted to
sudo mv /volume1/Downloads/SickChill-master /var/packages/sickchill/target/share/SickChill

# set permissions
sudo chown -R sc-sickchill:sickchill /var/packages/sickchill/target/share/SickChill
```

start the SC package up.
