### ISSUE TITLE
Unable to install Sickchill on Freenass

### ISSUE THREAD

**Issue by patarnoster** [SickChill/SickChill#7260]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: TrueNas
Browser: Chrome
What you did: Tried manual and via Freenas GUI
What happened: Error at the end 
What you expected: Installation successful 
Logs: Command line - running 

sudo pkg install py36-iocage
iocage fetch -r 12.1-RELEASE
iocage fetch -P sickchill -g https://github.com/ix-plugin-hub/iocage-plugin-index --branch 'master'
```
PASTE LOGS HERE
```
Trying user site-packages
Command result: ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
Traceback (most recent call last):
  File "/usr/local/app/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/usr/local/app/sickchill/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/usr/local/app/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/usr/local/app/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/usr/local/app/sickchill/sickchill/logger.py", line 12, in <module>
    from github import InputFileContent
ModuleNotFoundError: No module named 'github'

Trying user site-packages
Command result: ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
/usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill
Last 10 lines:
Cloning into '/usr/local/app/sickchill'...
 ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/usr/local/app/sickchill/requirements.txt'
 mkdir: /usr/local/etc/rc.d: File exists
 Traceback (most recent call last):
  File "/usr/local/app/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/usr/local/app/sickchill/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/usr/local/app/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/usr/local/app/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/usr/local/app/sickchill/sickchill/logger.py", line 12, in <module>
    from github import InputFileContent
ModuleNotFoundError: No module named 'github'
 /usr/local/etc/rc.d/sickchill: WARNING: failed to start sickchill
SickChill had a failure
Exception: SystemExit Message: 1
Partial plugin destroyed

**Comment by miigotu** [comment]
https://github.com/ix-plugin-hub/iocage-plugin-sickchill/pull/2
https://github.com/ix-plugin-hub/iocage-plugin-index/commit/e463a7085761f29a5f36ed648137524a8a669d9f
