### ISSUE TITLE
Trouble starting after update.

### ISSUE THREAD

**Issue by michaelosten** [SickChill/SickChill#7269]
root@nuc2:/opt/sickchill-new# /usr/bin/python3 /opt/sickchill-new/SickChill.py --nolaunch --datadir=/opt/sickchill
sickchill found: False
We always run from virtualenv when running from source
Because of the above errors, we will try creating a new virtualenvironment in /opt/sickchill-new/.venv
virtualenv found: False
virtualenv module not found, getting a portable one to use temporarily
Traceback (most recent call last):
  File "/opt/sickchill-new/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill-new/sickchill/__init__.py", line 3, in <module>
    poetry_install()
  File "/opt/sickchill-new/sickchill/init_helpers.py", line 221, in poetry_install
    make_virtualenv_and_rerun(pyproject_path.with_name(".venv"))
  File "/opt/sickchill-new/sickchill/init_helpers.py", line 162, in make_virtualenv_and_rerun
    tfd = download_to_temp_file("https://bootstrap.pypa.io/virtualenv.pyz", suffix=".pyz", prefix="virtualenv")
TypeError: download_to_temp_file() got an unexpected keyword argument 'suffix'

**Comment by zobe123** [comment]
same here

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/commit/3ea8b7975a17c73575b0dccd41dc99b0b46daf3c
