### ISSUE TITLE
Unable to start on OSX

### ISSUE THREAD

**Issue by identd113** [SickChill/SickChill#7273]
Branch/Commit: master branch as of 14:05 on 20210713
OS: OSX 10.15.7
Browser: N/A
What you did: tried to start SC by running this in terminal: `python3 ./SickChill.py`
What happened: stacktrace
What you expected: not a stacktrace
Logs:
```
❯ brew install virtualenv

Warning: virtualenv 20.4.7 is already installed and up-to-date.
To reinstall 20.4.7, run:
  brew reinstall virtualenv

sickchill found: False
We always run from virtualenv when running from source
Because of the above errors, we will try creating a new virtualenvironment in /Volumes/PlexDB/SickChill/.venv
virtualenv found: False
virtualenv module not found, getting a portable one to use temporarily
Traceback (most recent call last):
  File "/Volumes/PlexDB/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/Volumes/PlexDB/SickChill/sickchill/__init__.py", line 3, in <module>
    poetry_install()
  File "/Volumes/PlexDB/SickChill/sickchill/init_helpers.py", line 221, in poetry_install
    make_virtualenv_and_rerun(pyproject_path.with_name(".venv"))
  File "/Volumes/PlexDB/SickChill/sickchill/init_helpers.py", line 162, in make_virtualenv_and_rerun
    tfd = download_to_temp_file("https://bootstrap.pypa.io/virtualenv.pyz", suffix=".pyz", prefix="virtualenv")
TypeError: download_to_temp_file() got an unexpected keyword argument 'suffix'```

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/commit/3ea8b7975a17c73575b0dccd41dc99b0b46daf3c

**Comment by identd113** [comment]
I had to run it twice after the update, but it hammered through:

```
❯ git pull
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 19 (delta 7), reused 17 (delta 5), pack-reused 0
Unpacking objects: 100% (19/19), done.
From https://github.com/SickChill/SickChill
   1e89497f4..6f71297da  master     -> origin/master
   1e89497f4..6f71297da  develop    -> origin/develop
 * [new tag]             v2021.07.13-2 -> v2021.07.13-2
 * [new tag]             v2021.07.13-3 -> v2021.07.13-3
Updating 1e89497f4..6f71297da
Fast-forward
 SickChill.py              | 122 ++++--------------------------------
 pyproject.toml            |   2 +-
 sickchill/__init__.py     |   3 +-
 sickchill/init_helpers.py | 154 ++++++++++++++++++++++++++++++++++++++--------
 sickchill/version.py      |   2 +-
 5 files changed, 143 insertions(+), 140 deletions(-)


❯ python3 SickChill.py
Checking poetry
sickchill found: False
We always run from virtualenv when running from source
Because of the above errors, we will try creating a new virtualenvironment in /Volumes/PlexDB/SickChill/.venv
virtualenv found: False
virtualenv module not found, getting a portable one to use temporarily
Command result: Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/__main__.py", line 168, in <module>
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/__main__.py", line 164, in run
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/__main__.py", line 18, in run
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/run/__init__.py", line 32, in cli_run
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/run/session.py", line 46, in run
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/run/session.py", line 53, in _create
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/create/creator.py", line 171, in run
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 101, in create
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/create/via_global_ref/api.py", line 89, in create
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/create/via_global_ref/api.py", line 92, in install_patch
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/create/via_global_ref/builtin/cpython/cpython3.py", line 27, in env_patch_text
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/create/via_global_ref/api.py", line 103, in env_patch_text
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/app_data/base.py", line 58, in ensure_extracted
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/app_data/via_disk_folder.py", line 83, in extract
  File "/var/folders/ss/6rwp76pj2y1543v3pkf6nxy40000gn/T/virtualenvjia4wxjt.pyz/virtualenv/util/zipapp.py", line 22, in extract
    
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zipfile.py", line 1429, in getinfo
    raise KeyError(
KeyError: "There is no item named 'nv/create/via_global_ref/_virtualenv.py' in the archive"

Due to the above error, we cannot continue! Exiting


❯ python3 SickChill.py
Checking poetry
sickchill found: False
We always run from virtualenv when running from source
Restarting SickChill with ['/Volumes/PlexDB/SickChill/.venv/bin/python3.9', 'SickChill.py']
Checking poetry
sickchill found: False
pip found: False
Installing pip
Command result: Collecting pip
  Downloading pip-21.1.3-py3-none-any.whl (1.5 MB)
Collecting setuptools
  Downloading setuptools-57.1.0-py3-none-any.whl (818 kB)
Collecting wheel
  Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, pip
Successfully installed pip-21.1.3 setuptools-57.1.0 wheel-0.36.2

Pip installed
poetry found: True
sickchill found: False
2021-07-13 15:29:08 WARNING :: MAIN :: Unable to setup GitHub properly with your github token. Please check your credentials. Error: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
2021-07-13 15:29:08 DEBUG :: MAIN :: Parsed Show.Name.S02E03.HDTV.XviD-SICKCHILL into Show Name - S02E03 [GROUP: SICKCHILL] [ABD: False] [ANIME: False] [whichReg: ['anime_SxxExx']] Score: -2
```

This is resolved.
