### ISSUE TITLE
Errors after last update - Raspbian 

### ISSUE THREAD

**Issue by djtazie** [SickChill/SickChill#7274]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Raspbian
Browser: all
What you did: removed and reinstalled from git 
What happened: sickchill updated and stopped working 
What you expected: 
Logs:
```
root@Pi-Nas:/opt# sudo git clone https://github.com/SickChill/SickChill.git sickchill
Cloning into 'sickchill'...
remote: Enumerating objects: 121744, done.
remote: Counting objects: 100% (3352/3352), done.
remote: Compressing objects: 100% (2117/2117), done.
remote: Total 121744 (delta 1315), reused 3032 (delta 1112), pack-reused 118392
Receiving objects: 100% (121744/121744), 256.11 MiB | 4.06 MiB/s, done.
Resolving deltas: 100% (74843/74843), done.
Checking out files: 100% (2459/2459), done.
root@Pi-Nas:/opt# /opt/sickchill/SickChill.py --daemon --nolaunch --datadir=/opt/sickchill                                                                                                           




sickchill found: False
We always run from virtualenv when running from source
Because of the above errors, we will try creating a new virtualenvironment in /opt/sickchill/.v                                                                                                      env
virtualenv found: False
virtualenv module not found, getting a portable one to use temporarily
Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 3, in <module>
    poetry_install()
  File "/opt/sickchill/sickchill/init_helpers.py", line 221, in poetry_install
    make_virtualenv_and_rerun(pyproject_path.with_name(".venv"))
  File "/opt/sickchill/sickchill/init_helpers.py", line 162, in make_virtualenv_and_rerun
    tfd = download_to_temp_file("https://bootstrap.pypa.io/virtualenv.pyz", suffix=".pyz", pref                                                                                                      ix="virtualenv")
TypeError: download_to_temp_file() got an unexpected keyword argument 'suffix'

```

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/commit/3ea8b7975a17c73575b0dccd41dc99b0b46daf3c
