### ISSUE TITLE
Latest update error

### ISSUE THREAD

**Issue by zerosaber071** [SickChill/SickChill#7275]
OS: Ubuntu 20.04
Browser: Chrome
What you did: Updated to latest commit
What happened: Won't start up
Logs:
```
PASTE LOGS HERE
Checking poetry
We always run from virtualenv when running from source
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3.8', 'SickChill.py']
Checking poetry
Traceback (most recent call last):
  File "SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/opt/sickchill/sickchill/logger.py", line 12, in <module>
    from github import InputFileContent
  File "/opt/sickchill/.venv/lib/python3.8/site-packages/github/__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "/opt/sickchill/.venv/lib/python3.8/site-packages/github/MainClass.py", line 59, in <module>
    import github.Event
  File "/opt/sickchill/.venv/lib/python3.8/site-packages/github/Event.py", line 32, in <module>
    import github.NamedUser
  File "/opt/sickchill/.venv/lib/python3.8/site-packages/github/NamedUser.py", line 44, in <module>
    import github.Organization
  File "/opt/sickchill/.venv/lib/python3.8/site-packages/github/Organization.py", line 50, in <module>
    import github.Repository
  File "/opt/sickchill/.venv/lib/python3.8/site-packages/github/Repository.py", line 125, in <module>
    import github.PublicKey
  File "/opt/sickchill/.venv/lib/python3.8/site-packages/github/PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "/opt/sickchill/.venv/lib/python3.8/site-packages/nacl/public.py", line 17, in <module>
    import nacl.bindings
  File "/opt/sickchill/.venv/lib/python3.8/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_aead import (
  File "/opt/sickchill/.venv/lib/python3.8/site-packages/nacl/bindings/crypto_aead.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory

**Comment by miigotu** [comment]
is this a docker image?

**Comment by miigotu** [comment]
you installed some wheel from somwhere it seems. ubuntu doesnt use musl, that is for alpine linux.

**Comment by zerosaber071** [comment]
> is this a docker image?

I do not think so. I had a friend install sickshill for me way back/ I have some basic ubuntu skills

**Comment by miigotu** [comment]
I wonder if it might be my fault

**Comment by zerosaber071** [comment]
> I wonder if it might be my fault, let me make some changes.

I used a backup copy to push the update again and got the same error
