### ISSUE TITLE
latest commit broken

### ISSUE THREAD

**Issue by michaelosten** [SickChill/SickChill#7277]
root@nuc2:/opt/sickchill-07-13-2021# /usr/bin/python3 /opt/sickchill-07-13-2021/SickChill/SickChill.py --nolaunch --datadir=/opt/sickchill
Checking poetry
We always run from virtualenv when running from source
Restarting SickChill with ['/opt/sickchill-07-13-2021/SickChill/.venv/bin/python3.8', '/opt/sickchill-07-13-2021/SickChill/SickChill.py', '--nolaunch', '--datadir=/opt/sickchill']
Checking poetry
Traceback (most recent call last):
  File "/opt/sickchill-07-13-2021/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill-07-13-2021/SickChill/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill-07-13-2021/SickChill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill-07-13-2021/SickChill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/opt/sickchill-07-13-2021/SickChill/sickchill/logger.py", line 12, in <module>
    from github import InputFileContent
  File "/opt/sickchill-07-13-2021/SickChill/.venv/lib/python3.8/site-packages/github/__init__.py", line 56, in <module>
    from github.MainClass import Github, GithubIntegration
  File "/opt/sickchill-07-13-2021/SickChill/.venv/lib/python3.8/site-packages/github/MainClass.py", line 59, in <module>
    import github.Event
  File "/opt/sickchill-07-13-2021/SickChill/.venv/lib/python3.8/site-packages/github/Event.py", line 32, in <module>
    import github.NamedUser
  File "/opt/sickchill-07-13-2021/SickChill/.venv/lib/python3.8/site-packages/github/NamedUser.py", line 44, in <module>
    import github.Organization
  File "/opt/sickchill-07-13-2021/SickChill/.venv/lib/python3.8/site-packages/github/Organization.py", line 50, in <module>
    import github.Repository
  File "/opt/sickchill-07-13-2021/SickChill/.venv/lib/python3.8/site-packages/github/Repository.py", line 125, in <module>
    import github.PublicKey
  File "/opt/sickchill-07-13-2021/SickChill/.venv/lib/python3.8/site-packages/github/PublicKey.py", line 34, in <module>
    from nacl import encoding, public
  File "/opt/sickchill-07-13-2021/SickChill/.venv/lib/python3.8/site-packages/nacl/public.py", line 17, in <module>
    import nacl.bindings
  File "/opt/sickchill-07-13-2021/SickChill/.venv/lib/python3.8/site-packages/nacl/bindings/__init__.py", line 17, in <module>
    from nacl.bindings.crypto_aead import (
  File "/opt/sickchill-07-13-2021/SickChill/.venv/lib/python3.8/site-packages/nacl/bindings/crypto_aead.py", line 18, in <module>
    from nacl._sodium import ffi, lib
ImportError: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
root@nuc2:/opt/sickchill-07-13-2021# 

```

**Comment by miigotu** [comment]
You will need to follow the instructions in #7281
