### ISSUE TITLE
Failed update wont restart

### ISSUE THREAD

**Issue by optio50** [SickChill/SickChill#7278]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Release 2021.7.13-4
OS: Ubuntu 
Browser: Firefox
What you did: Update latest commit  via web interface
What happened: No restart
What you expected: updated and restart
Logs:
```
● sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Tue 2021-07-13 18:06:42 AKDT; 8s ago
    Process: 378090 ExecStart=/usr/bin/python3 /home/optio50/.sickchill/SickChill.py -q --daemon --nolaunch --datadir=/home/optio50/.sickchill (code=exited, status=0/SUCCESS)

Jul 13 18:06:03 Disco-Server systemd[1]: Starting SickChill Daemon...
Jul 13 18:06:03 Disco-Server systemd[1]: Started SickChill Daemon.
Jul 13 18:06:42 Disco-Server systemd[1]: sickchill.service: Succeeded.

2021-07-13 17:29:15 DEBUG :: WEBSERVER-HOME_0 :: Checking if we can use git commands: git version
2021-07-13 17:29:15 DEBUG :: WEBSERVER-HOME_0 :: Executing git version with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:15 DEBUG :: WEBSERVER-HOME_0 :: git version : returned successful
2021-07-13 17:29:15 DEBUG :: WEBSERVER-HOME_0 :: Using: git
2021-07-13 17:29:15 DEBUG :: WEBSERVER-HOME_0 :: Executing git symbolic-ref -q HEAD with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:15 DEBUG :: WEBSERVER-HOME_0 :: git symbolic-ref -q HEAD : returned successful
2021-07-13 17:29:15 DEBUG :: WEBSERVER-HOME_0 :: Executing git symbolic-ref -q HEAD with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:15 DEBUG :: WEBSERVER-HOME_0 :: git symbolic-ref -q HEAD : returned successful
2021-07-13 17:29:15 DEBUG :: WEBSERVER-HOME_0 :: Executing git rev-parse HEAD with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: git rev-parse HEAD : returned successful
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: Executing git config remote.origin.url https://github.com/SickChill/SickChill.git with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: git config remote.origin.url https://github.com/SickChill/SickChill.git : returned successful
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: Executing git fetch origin --prune with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: git fetch origin --prune : returned successful
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: Executing git branch --set-upstream-to origin/master with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: git branch --set-upstream-to origin/master : returned successful
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: cur_commit = 94f56b7e2c86655fc98d93e94be1a75e729d3969, newest_commit = 6479a960e33a48a67b1e95f41840c73c79b8b6c3, num_commits_behind = 107, num_commits_ahead = 0
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: Executing git config remote.origin.url https://github.com/SickChill/SickChill.git with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: git config remote.origin.url https://github.com/SickChill/SickChill.git : returned successful
2021-07-13 17:29:16 DEBUG :: WEBSERVER-HOME_0 :: Executing git reset --hard with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:17 DEBUG :: WEBSERVER-HOME_0 :: git reset --hard : returned successful
2021-07-13 17:29:17 DEBUG :: WEBSERVER-HOME_0 :: Executing git symbolic-ref -q HEAD with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:17 DEBUG :: WEBSERVER-HOME_0 :: git symbolic-ref -q HEAD : returned successful
2021-07-13 17:29:17 DEBUG :: WEBSERVER-HOME_0 :: Executing git pull -f origin master with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:19 DEBUG :: WEBSERVER-HOME_0 :: git pull -f origin master : returned successful
2021-07-13 17:29:19 DEBUG :: WEBSERVER-HOME_0 :: Executing git rev-parse HEAD with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:19 DEBUG :: WEBSERVER-HOME_0 :: git rev-parse HEAD : returned successful
2021-07-13 17:29:19 DEBUG :: WEBSERVER-HOME_0 :: Executing git clean -df lib with your shell in /home/optio50/.sickchill/sickchill
2021-07-13 17:29:19 DEBUG :: WEBSERVER-HOME_0 :: git clean -df lib : returned successful
2021-07-13 17:29:19 DEBUG :: WEBSERVER-HOME_0 :: Sending KODI notification to '192.168.20.4' - SickChill Updated To Commit#: 6479a960e33a48a67b1e95f41840c73c79b8b6c3
2021-07-13 17:29:19 DEBUG :: WEBSERVER-HOME_0 :: Notification for Boxcar2 not enabled, skipping this notification
2021-07-13 17:29:19 INFO :: EVENT-QUEUE :: Aborting all threads
2021-07-13 17:29:19 INFO :: EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Waiting for the SHOWQUEUE-REFRESH thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Waiting for the SEARCHQUEUE-BACKLOG-78904 thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR-AUTO thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Waiting for the NOTIFICATIONS thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Saving all shows to the database
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 73641: Saving to database: The King of Queens
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 73739: Saving to database: Lost
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 76119: Saving to database: NOVA
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 71470: Saving to database: Star Trek: The Next Generation
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 328686: Saving to database: SEAL Team
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 250440: Saving to database: Miss Marple
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 164981: Saving to database: Blue Bloods
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 71638: Saving to database: American Experience
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 82300: Saving to database: Storyville
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 80646: Saving to database: Frontline
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 350068: Saving to database: Magnum P.I.
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 258171: Saving to database: Continuum
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 82918: Saving to database: Diners, Drive-ins and Dives
2021-07-13 17:29:20 DEBUG :: EVENT-QUEUE :: 391288: Saving to database: Ice Airport Alaska
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Saving config file to disk
2021-07-13 17:29:20 INFO :: EVENT-QUEUE :: Shutting down Tornado
2021-07-13 17:29:30 INFO :: EVENT-QUEUE :: Restarting SickChill with ['/usr/bin/python3', '/home/optio50/.sickchill/SickChill.py', '-q', '--daemon', '--nolaunch', '--datadir=/home/optio50/.sickchill']


```

**Comment by LaughingLogic** [comment]
Seems to failing around here after adding the "-v" to command line.

> Traceback (most recent call last):
  File "C:\SickChill\SickChill\SickChill.py", line 14, in <module>
    import sickchill.start
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\SickChill\SickChill\sickchill\__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\SickChill\SickChill\sickchill\show\indexers\__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\SickChill\SickChill\sickchill\show\indexers\handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\SickChill\SickChill\sickchill\tv.py", line 14, in <module>
    import imdb
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'imdb'

**Comment by miigotu** [comment]
@LaughingLogic your issue is not the same. You need to reinstall with the newest version of the windows updater.

**Comment by miigotu** [comment]
@optio50 You need to git pull and do this https://github.com/SickChill/SickChill/discussions/7281 before starting it.

**Comment by LaughingLogic** [comment]
@miigotu thanks mate,  I just changed to Python 3.9.6 (was 3.8.x) and it started again.

**Comment by miigotu** [comment]
> @miigotu thanks mate, I just changed to Python 3.9.6 (was 3.8.x) and it started again.

That makes no difference lol, you maybe needed #7281 also.

**Comment by LaughingLogic** [comment]
> > @miigotu thanks mate, I just changed to Python 3.9.6 (was 3.8.x) and it started again.
> 
> That makes no difference lol, you maybe needed #7281 also.
lol.

I just uninstalled and reinstalled the latest Windows version. All good now.

**Comment by miigotu** [comment]
Oh lol ok, yeah the new installer v0.6.0 is the fix xD

**Comment by Smokey23** [comment]
@miigotu, if you have ran in to the issue of SickChill not starting after the update, can you follow the directions [here](https://github.com/SickChill/sickchill.github.io#before-you-open-an-issue) to update your local to master and be ok or does it require the installer to be ran?

I updated my local copy but the service would not run so I ran it from the command line and got it back up and running.

If I do have to reinstall, will I lose anything (obviously backup first) or will existing settings/db be preserved in the reinstall?

BTW, thanks for the quick fixes today!  I caught up on some of the things in the works as I was looking through issues and am impressed and very excited!!

**Comment by miigotu** [comment]
@Smokey23 what OS? On windows I would recommend the new installer, because virtualenv does not work on the python that was included in the installer. If it is an x86 windows, just stay where you are because there is no solution for that yet.

Everyone else, doing #7281 and git pulling should fix things, but if you are not sure how to go back then wait until others who do have given it a test.

**Comment by telsum** [comment]
Thank you, the new Windows installer worked great.
