### ISSUE TITLE
Unable to retrieve new version - Syno DSM

### ISSUE THREAD

**Issue by BKSteve** [SickChill/SickChill#7279]
Branch: develop
Commit: a0717b2a334bc945fc5ae3aa5fde45160ed1a153

attempted to update receive error and warning per log

```
2021-07-14 09:54:26 DEBUG :: WEBSERVER-HOME_0 :: cur_commit = a0717b2a334bc945fc5ae3aa5fde45160ed1a153, newest_commit = 8fd92124772bf5fd25dfe71ef886658ccc4e98cb, num_commits_behind = 12
2021-07-14 09:54:26 INFO :: WEBSERVER-HOME_0 :: Clearing out update folder /volume1/@appstore/sickchill/var/data/sc-update before extracting
2021-07-14 09:54:26 INFO :: WEBSERVER-HOME_0 :: Creating update folder /volume1/@appstore/sickchill/var/data/sc-update before extracting
2021-07-14 09:54:26 INFO :: WEBSERVER-HOME_0 :: Downloading update from https://github.com/SickChill/SickChill/tarball/develop
2021-07-14 09:54:26 ERROR :: WEBSERVER-HOME_0 :: Request failed: 'PosixPath' object has no attribute 'endswith' (<class 'str'>)
2021-07-14 09:54:26 DEBUG :: WEBSERVER-HOME_0 :: Traceback (most recent call last):
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/helpers.py", line 1331, in handle_requests_exception
    raise requests_exception
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/oldbeard/helpers.py", line 1303, in download_file
    if filename.endswith("nzb") and resp.headers.get("content-type") == "application/x-bittorrent":
AttributeError: 'PosixPath' object has no attribute 'endswith'

2021-07-14 09:54:26 WARNING :: WEBSERVER-HOME_0 :: Unable to retrieve new version from https://github.com/SickChill/SickChill/tarball/develop, can't update

```
Not sure if this is relevant 
[https://github.com/python-poetry/poetry/pull/2582](url)

**Comment by miigotu** [comment]
@BKSteve I fixed that error in 7dcca27570e32c94d0703a5869e2e66b7cc6eb84 (Will need to reinstall since you have no way to update)

**Comment by BKSteve** [comment]
OK, at least it's still running so I can make a fresh backup.
please close.

**Comment by BKSteve** [comment]
uninstall reinstall restore update
Fails to start 1ab5cd772328140c49813ca683de00f5bfa2997f
Can't find where it's going wrong there's no real data in the log.
It's says writing sickchill.pid but it's not created.

**Comment by BKSteve** [comment]
/volume1/@appstore/sickchill/var/sickchill.log

```
Wed Jul 14 14:14:30 WIB 2021
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data 
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
/volume1/@appstore/sickchill/share/SickChill/sickchill/locale
```

**Comment by miigotu** [comment]
What is the output of:
```bash
python3 -c "from pathlib import Path; print(Path('/volume1/@appstore/sickchill/var/sickchill.pid').resolve())"
```

Did you let it stay for a bit? It takes a bit between starting and logging after writing the pid
Otherwise I will have to try and start it up in awhile

**Comment by BKSteve** [comment]
I left it a long time between restarting and checking the log.
```
python3 -c "from pathlib import Path; print(Path('/volume1/@appstore/sickchill/var/sickchill.pid').resolve())"

/volume1/@appstore/sickchill/var/sickchill.pid
```

**Comment by BKSteve** [comment]
Adding here for others if looking:
the problem seems to be the #7234 problem. 
I did the chown and now up and running 9890d406bd9e84d945a6beddfbd80b9d30f26bd3 
`sudo chown -R sc-sickchill:sickchill /volume1/@appstore/sickchill/env`

Note that this 9890 version is back to using `/volume1/@appstore/sickchill/env/lib/python3.7/site-packages ` rather than the folder `/volume1/@appstore/sickchill/share/SickChill/.venv/lib/python3.7/site-packages` 

Now there is a new error when trying to update:
```
ERROR :: WEBSERVER-HOME_0 :: Error while trying to update: unlink() takes 1 positional argument but 2 were given
DEBUG :: WEBSERVER-HOME_0 :: Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/update_manager/source.py", line 171, in update
    tar_download_path.unlink(True)
TypeError: unlink() takes 1 positional argument but 2 were given
```

**Comment by miigotu** [comment]
@BKSteve that unlink is already fixed, will be in master within an hour
https://github.com/SickChill/SickChill/commit/eeded6729fdee99d0adbbd1b6a699fb9a403db18

**Comment by BKSteve** [comment]
Still had to `chown -R` /env to get Commit: eeded6729fdee99d0adbbd1b6a699fb9a403db18  to run.

Now a new update error:
```
2021-07-14 17:33:35 INFO :: WEBSERVER-HOME_0 :: Moving files from /volume1/@appstore/sickchill/var/data/sc-update/SickChill-SickChill-79972ea to /volume1/@appstore/sickchill/share/SickChill
2021-07-14 17:33:35 ERROR :: WEBSERVER-HOME_0 :: Error while trying to update: object of type 'PosixPath' has no len()
2021-07-14 17:33:35 DEBUG :: WEBSERVER-HOME_0 :: Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickchill/share/SickChill/sickchill/update_manager/source.py", line 187, in update
    dirname = dirname[len(content_dir) + 1 :]
TypeError: object of type 'PosixPath' has no len()

2021-07-14 17:34:42 DEBUG :: WEBSERVER-CONFIG_0 :: cur_commit = eeded6729fdee99d0adbbd1b6a699fb9a403db18, newest_commit = 79972ea8979a517dc24f72ee4a181574beff3afd, num_commits_behind = 1
```

**Comment by BKSteve** [comment]
Edited the one line and restarted, updated.

folder
`/volume1/@appstore/sickchill/env/lib/python3.7/site-packages`
still being used instead of expected `/volume1/@appstore/sickchill/share/SickChill/.venv`

**Comment by miigotu** [comment]
It is supposed to use the existing env, if it is writable.

**Comment by BKSteve** [comment]
SC did load files in the .venv folder when env was root when we were testing in #7234 but it now doesn't. 

Here's some details of the reinstall, and restart, followed by chown and run from package center.

/volume1/@appstore/sickchill/var/sickchill.log
```
Wed Jul 14 21:22:50 WIB 2021
Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data 
Writing PID: 13497 to /volume1/@appstore/sickchill/var/sickchill.pid
```
/volume1/@appstore/sickchill/share/SickChill/.venv/lib/python3.7/site-packages
```
FOLDERS
pip, pip-20.0.2.dist-info, pkg_resources, setuptools, setuptools-45.2.0.dist-info, wheel, wheel-0.34.2.dist-info
FILES
easy_install.py, pip-20.0.2.virtualenv, setuptools-45.2.0.virtualenv, wheel-0.34.2.virtualenv
```

/volume1/@appstore/sickchill/share/wheelhouse
```
FILES
appdirs-1.4.4-py2.py3-none-any.whl, attrdict-2.0.1-py2.py3-none-any.whl, babelfish-0.5.5-py3-none-any.whl, beautifulsoup4-4.9.3-py3-none-any.whl, bencode.py-4.0.0-py2.py3-none-any.whl, CacheControl-0.12.6-py2.py3-none-any.whl, certifi-2020.11.8-py2.py3-none-any.whl, chardet-3.0.4-py2.py3-none-any.whl, click-7.1.2-py2.py3-none-any.whl, cloudscraper-1.2.48-py3-none-any.whl, configobj-5.0.6-py3-none-any.whl, decorator-4.4.2-py2.py3-none-any.whl, deluge_client-1.9.0-py3-none-any.whl, Deprecated-1.2.10-py2.py3-none-any.whl, dogpile.cache-1.0.2-py3-none-any.whl, enzyme-0.4.1-py3-none-any.whl, feedparser-6.0.2-py3-none-any.whl, future-0.18.2-py3-none-any.whl, gntp-1.0.3-py3-none-any.whl, guessit-3.1.1-py3-none-any.whl, html5lib-1.1-py2.py3-none-any.whl, httplib2-0.18.1-py3-none-any.whl, idna-2.10-py2.py3-none-any.whl, ifaddr-0.1.7-py2.py3-none-any.whl, imagesize-1.2.0-py2.py3-none-any.whl, IMDbPY-2020.9.25-py3-none-any.whl, ipaddress-1.0.23-py2.py3-none-any.whl, Js2Py-0.70-py3-none-any.whl, jsonrpclib_pelix-0.4.2-py2.py3-none-any.whl, Mako-1.1.3-py2.py3-none-any.whl, markdown2-2.3.10-py2.py3-none-any.whl, MarkupSafe-1.1.1-py3-none-any.whl, msgpack-1.0.0-cp37-none-any.whl, new_rtorrent_python-1.0.1a0-py3-none-any.whl, oauthlib-3.1.0-py2.py3-none-any.whl, packaging-20.4-py2.py3-none-any.whl, pbr-5.5.1-py2.py3-none-any.whl, profilehooks-1.12.0-py2.py3-none-any.whl, putio.py-8.7.0-py3-none-any.whl, pyaes-1.6.1-py3-none-any.whl, pycparser-2.20-py2.py3-none-any.whl, PyGithub-1.53-py3-none-any.whl, pyjsparser-2.7.1-py3-none-any.whl, PyJWT-1.7.1-py2.py3-none-any.whl, pymediainfo-4.3-py2.py3-none-any.whl, PyNMA-1.0-py3-none-any.whl, pyOpenSSL-19.1.0-py2.py3-none-any.whl, pyparsing-2.4.7-py2.py3-none-any.whl, PySocks-1.7.1-py3-none-any.whl, pysrt-1.1.2-py3-none-any.whl, python_dateutil-2.8.1-py2.py3-none-any.whl, python_slugify-4.0.1-py2.py3-none-any.whl, python_twitter-3.5-py2.py3-none-any.whl, python3_fanart-2.0.0-py3-none-any.whl, pytz-2020.4-py3-none-any.whl, qbittorrent_api-2020.10.11-py3-none-any.whl, rarfile-4.0-py2.py3-none-any.whl, rebulk-2.0.1-py3-none-any.whl, requests_oauthlib-1.3.0-py2.py3-none-any.whl, requests_toolbelt-0.9.1-py2.py3-none-any.whl, requests-2.24.0-py2.py3-none-any.whl, Send2Trash-1.5.0-py3-none-any.whl, sgmllib3k-1.0.0-py3-none-any.whl, six-1.15.0-py2.py3-none-any.whl, soupsieve-2.0.1-py3-none-any.whl, SQLAlchemy-1.3.20-cp37-none-any.whl, stevedore-3.2.2-py3-none-any.whl, subliminal-2.1.0-py3-none-any.whl, text_unidecode-1.3-py2.py3-none-any.whl, timeago-1.0.14-py3-none-any.whl, tmdbsimple-2.6.6-py3-none-any.whl, tornado-6.1-cp37-none-any.whl, tus.py-1.3.4-py3-none-any.whl, tvdbsimple-1.0.6-py3-none-any.whl, twilio-6.47.0-py2.py3-none-any.whl, tzlocal-2.1-py2.py3-none-any.whl, Unidecode-1.1.1-py2.py3-none-any.whl, urllib3-1.26.0-py2.py3-none-any.whl, validators-0.18.1-py3-none-any.whl, webencodings-0.5.1-py2.py3-none-any.whl, win_inet_pton-1.1.0-py2.py3-none-any.whl, wrapt-1.12.1-py3-none-any.whl, xmltodict-0.10.1-py3-none-any.whl
```

/volume1/@appstore/sickchill/env/lib/python3.7/site-packages 
root:root
```
FOLDERS
__pycache__, appdirs-1.4.4.dist-info, attrdict, attrdict-2.0.1.dist-info, babelfish, babelfish-0.5.5.dist-info, beautifulsoup4-4.9.3.dist-info, bencode, bencode.py-4.0.0.dist-info, bencodepy, bs4, cachecontrol, CacheControl-0.12.6.dist-info, certifi, certifi-2020.11.8.dist-info, chardet, chardet-3.0.4.dist-info, click, click-7.1.2.dist-info, cloudscraper, cloudscraper-1.2.48.dist-info, configobj-5.0.6.dist-info, dateutil, decorator-4.4.2.dist-info, deluge_client, deluge_client-1.9.0.dist-info, deprecated, Deprecated-1.2.10.dist-info, dogpile, dogpile.cache-1.0.2.dist-info, enzyme, enzyme-0.4.1.dist-info, fanart, feedparser, feedparser-6.0.2.dist-info, future, future-0.18.2.dist-info, github, gntp, gntp-1.0.3.dist-info, guessit, guessit-3.1.1.dist-info, html5lib, html5lib-1.1.dist-info, httplib2, httplib2-0.18.1.dist-info, idna, idna-2.10.dist-info, ifaddr, ifaddr-0.1.7.dist-info, imagesize-1.2.0.dist-info, imdb, IMDbPY-2020.9.25.dist-info, ipaddress-1.0.23.dist-info, js2py, Js2Py-0.70.dist-info, jsonrpclib, jsonrpclib_pelix-0.4.2.dist-info, jwt, libfuturize, libpasteurize, mako, Mako-1.1.3.dist-info, markdown2-2.3.10.dist-info, markupsafe, MarkupSafe-1.1.1.dist-info, msgpack, msgpack-1.0.0.dist-info, new_rtorrent_python-1.0.1a0.dist-info, oauthlib, oauthlib-3.1.0.dist-info, OpenSSL, packaging, packaging-20.4.dist-info, past, pbr, pbr-5.5.1.dist-info, pip, pip-20.0.2.dist-info, pkg_resources, profilehooks-1.12.0.dist-info, putio.py-8.7.0.dist-info, pyaes, pyaes-1.6.1.dist-info, pycparser, pycparser-2.20.dist-info, PyGithub-1.53.dist-info, pyjsparser, pyjsparser-2.7.1.dist-info, PyJWT-1.7.1.dist-info, pymediainfo, pymediainfo-4.3.dist-info, pynma, PyNMA-1.0.dist-info, pyOpenSSL-19.1.0.dist-info, pyparsing-2.4.7.dist-info, PySocks-1.7.1.dist-info, pysrt, pysrt-1.1.2.dist-info, python_dateutil-2.8.1.dist-info, python_slugify-4.0.1.dist-info, python_twitter-3.5.dist-info, python3_fanart-2.0.0.dist-info, pytz, pytz-2020.4.dist-info, qbittorrent_api-2020.10.11.dist-info, qbittorrentapi, rarfile-4.0.dist-info, rebulk, rebulk-2.0.1.dist-info, requests, requests_oauthlib, requests_oauthlib-1.3.0.dist-info, requests_toolbelt, requests_toolbelt-0.9.1.dist-info, requests-2.24.0.dist-info, rtorrent, send2trash, Send2Trash-1.5.0.dist-info, setuptools, setuptools-45.2.0.dist-info, sgmllib3k-1.0.0.dist-info, six-1.15.0.dist-info, slugify, soupsieve, soupsieve-2.0.1.dist-info, sqlalchemy
SQLAlchemy-1.3.20.dist-info, stevedore, stevedore-3.2.2.dist-info, subliminal, subliminal-2.1.0.dist-info, text_unidecode, text_unidecode-1.3.dist-info, timeago, timeago-1.0.14.dist-info, tmdbsimple, tmdbsimple-2.6.6.dist-info, tornado, tornado-6.1.dist-info, tus.py-1.3.4.dist-info, tvdbsimple, tvdbsimple-1.0.6.dist-info, twilio, twilio-6.47.0.dist-info, twitter, tzlocal, tzlocal-2.1.dist-info, unidecode, Unidecode-1.1.1.dist-info, urllib3, urllib3-1.26.0.dist-info, usr, validators, validators-0.18.1.dist-info, webencodings, webencodings-0.5.1.dist-info, wheel, wheel-0.34.2.dist-info, win_inet_pton-1.1.0.dist-info, wrapt, wrapt-1.12.1.dist-info, xmltodict-0.10.1.dist-info
FILES
_version.py, appdirs.py, configobj.py, decorator.py, easy_install.py, imagesize.py, ipaddress.py, markdown2.py, pip-20.0.2.virtualenv, profilehooks.py, putiopy.py, pyparsing.py, rarfile.py, setuptools-45.2.0.virtualenv, sgmllib.py, six.py, socks.py, sockshandler.py, tus.py, validate.py, wheel-0.34.2.virtualenv, win_inet_pton.py, xmltodict.py
```

Did not start.
`sudo chown -R sc-sickchill:sickchill /volume1/@appstore/sickchill/env`

Restart and running.
/volume1/@appstore/sickchill/share/SickChill/.venv/lib/python3.7/site-packages
NO CHANGE

/volume1/@appstore/sickchill/share/wheelhouse
```
appdirs-1.4.4-py2.py3-none-any.whl, attrdict-2.0.1-py2.py3-none-any.whl, babelfish-0.5.5-py3-none-any.whl, beautifulsoup4-4.9.3-py3-none-any.whl, bencode.py-4.0.0-py2.py3-none-any.whl, CacheControl-0.12.6-py2.py3-none-any.whl, certifi-2020.11.8-py2.py3-none-any.whl, chardet-3.0.4-py2.py3-none-any.whl, click-7.1.2-py2.py3-none-any.whl, cloudscraper-1.2.48-py3-none-any.whl, configobj-5.0.6-py3-none-any.whl, decorator-4.4.2-py2.py3-none-any.whl, deluge_client-1.9.0-py3-none-any.whl, Deprecated-1.2.10-py2.py3-none-any.whl, dogpile.cache-1.0.2-py3-none-any.whl, enzyme-0.4.1-py3-none-any.whl, feedparser-6.0.2-py3-none-any.whl, future-0.18.2-py3-none-any.whl, gntp-1.0.3-py3-none-any.whl, guessit-3.1.1-py3-none-any.whl, html5lib-1.1-py2.py3-none-any.whl, httplib2-0.18.1-py3-none-any.whl, idna-2.10-py2.py3-none-any.whl, ifaddr-0.1.7-py2.py3-none-any.whl, imagesize-1.2.0-py2.py3-none-any.whl, IMDbPY-2020.9.25-py3-none-any.whl, ipaddress-1.0.23-py2.py3-none-any.whl, Js2Py-0.70-py3-none-any.whl, jsonrpclib_pelix-0.4.2-py2.py3-none-any.whl, Mako-1.1.3-py2.py3-none-any.whl, markdown2-2.3.10-py2.py3-none-any.whl, MarkupSafe-1.1.1-py3-none-any.whl, msgpack-1.0.0-cp37-none-any.whl, new_rtorrent_python-1.0.1a0-py3-none-any.whl, oauthlib-3.1.0-py2.py3-none-any.whl, packaging-20.4-py2.py3-none-any.whl, pbr-5.5.1-py2.py3-none-any.whl, profilehooks-1.12.0-py2.py3-none-any.whl, putio.py-8.7.0-py3-none-any.whl, pyaes-1.6.1-py3-none-any.whl, pycparser-2.20-py2.py3-none-any.whl, PyGithub-1.53-py3-none-any.whl, pyjsparser-2.7.1-py3-none-any.whl, PyJWT-1.7.1-py2.py3-none-any.whl, pymediainfo-4.3-py2.py3-none-any.whl, PyNMA-1.0-py3-none-any.whl, pyOpenSSL-19.1.0-py2.py3-none-any.whl, pyparsing-2.4.7-py2.py3-none-any.whl, PySocks-1.7.1-py3-none-any.whl, pysrt-1.1.2-py3-none-any.whl, python_dateutil-2.8.1-py2.py3-none-any.whl, python_slugify-4.0.1-py2.py3-none-any.whl, python_twitter-3.5-py2.py3-none-any.whl, python3_fanart-2.0.0-py3-none-any.whl, pytz-2020.4-py3-none-any.whl, qbittorrent_api-2020.10.11-py3-none-any.whl, rarfile-4.0-py2.py3-none-any.whl, rebulk-2.0.1-py3-none-any.whl, requests_oauthlib-1.3.0-py2.py3-none-any.whl, requests_toolbelt-0.9.1-py2.py3-none-any.whl, requests-2.24.0-py2.py3-none-any.whl, Send2Trash-1.5.0-py3-none-any.whl, sgmllib3k-1.0.0-py3-none-any.whl, six-1.15.0-py2.py3-none-any.whl, soupsieve-2.0.1-py3-none-any.whl, SQLAlchemy-1.3.20-cp37-none-any.whl, stevedore-3.2.2-py3-none-any.whl, subliminal-2.1.0-py3-none-any.whl, text_unidecode-1.3-py2.py3-none-any.whl, timeago-1.0.14-py3-none-any.whl, tmdbsimple-2.6.6-py3-none-any.whl, tornado-6.1-cp37-none-any.whl, tus.py-1.3.4-py3-none-any.whl, tvdbsimple-1.0.6-py3-none-any.whl, twilio-6.47.0-py2.py3-none-any.whl, tzlocal-2.1-py2.py3-none-any.whl, Unidecode-1.1.1-py2.py3-none-any.whl, urllib3-1.26.0-py2.py3-none-any.whl, validators-0.18.1-py3-none-any.whl, webencodings-0.5.1-py2.py3-none-any.whl, win_inet_pton-1.1.0-py2.py3-none-any.whl, wrapt-1.12.1-py3-none-any.whl, xmltodict-0.10.1-py3-none-any.whl
```


/volume1/@appstore/sickchill/env/lib/python3.7/site-packages 
sc-sickchill:sickchill
```
FOLDERS
__pycache__, _distutils_hack, appdirs-1.4.4.dist-info, attrdict, attrdict-2.0.1.dist-info, babelfish, babelfish-0.5.5.dist-info, beautifulsoup4-4.9.3.dist-info, beekeeper, beekeeper-0.9.2.dist-info, bencode, bencode.py-4.0.0.dist-info, bencodepy, bs4, cachecontrol, CacheControl-0.12.6.dist-info, cachy, cachy-0.3.0.dist-info, certifi, certifi-2021.5.30.dist-info, cffi, cffi.libs, cffi-1.14.6.dist-info, chardet, chardet-4.0.0.dist-info, charset_normalizer, charset_normalizer-2.0.1.dist-info, cleo, cleo-1.0.0a3.dist-info, click, click-8.0.1.dist-info, cloudscraper, cloudscraper-1.2.58.dist-info, configobj-5.0.6.dist-info, crashtest, crashtest-0.3.1.dist-info, cryptography, cryptography-3.4.7.dist-info, dateutil, decorator-5.0.9.dist-info, deluge_client, deluge_client-1.9.0.dist-info, deprecated, Deprecated-1.2.12.dist-info, distlib, distlib-0.3.2.dist-info, dogpile, dogpile.cache-1.1.3.dist-info, entrypoints-0.3.dist-info, enzyme, enzyme-0.4.1.dist-info, fanart, feedparser, feedparser-6.0.8.dist-info, future, future-0.18.2.dist-info, github, gntp, gntp-1.0.3.dist-info, greenlet, greenlet-1.1.0.dist-info, guessit, guessit-3.3.1.dist-info, html5lib, html5lib-1.1.dist-info, httplib2, httplib2-0.19.1.dist-info, idna, idna-3.2.dist-info, ifaddr, ifaddr-0.1.7.dist-info, imagesize-1.2.0.dist-info, imdb, IMDbPY-2021.4.18.dist-info, importlib_metadata, importlib_metadata-1.7.0.dist-info, ipaddress-1.0.23.dist-info, jeepney, jeepney-0.7.0.dist-info, js2py, Js2Py-0.71.dist-info, jsonrpclib, jsonrpclib_pelix-0.4.2.dist-info, jwt, keyring, keyring-23.0.1.dist-info, kodipydent, kodipydent-0.3.1.dist-info, libfuturize, libpasteurize, lockfile, lockfile-0.12.2.dist-info, lxml, lxml-4.6.3.dist-info, mako, Mako-1.1.4.dist-info, markdown2-2.4.0.dist-info, markupsafe, MarkupSafe-2.0.1.dist-info, Misc, msgpack, msgpack-1.0.2.dist-info, nacl, new_rtorrent_python-1.0.1a0.dist-info, oauthlib, oauthlib-3.1.1.dist-info, OpenSSL, packaging, packaging-20.9.dist-info, past, pbr, pbr-5.6.0.dist-info, pexpect, pexpect-4.8.0.dist-info, pip, pip-20.0.2.dist-info, pkg_resources, pkginfo, pkginfo-1.7.1.dist-info, poetry, poetry_core-1.1.0a5.dist-info, poetry-1.2.0a1.dist-info, profilehooks-1.12.0.dist-info, ptyprocess, ptyprocess-0.7.0.dist-info, putio.py-8.7.0.dist-info, pyaes, pyaes-1.6.1.dist-info, pycparser, pycparser-2.20.dist-info, PyGithub-1.55.dist-info, pyjsparser, pyjsparser-2.7.1.dist-info, PyJWT-2.1.0.dist-info, pylev, pylev-1.4.0.dist-info, pymediainfo, pymediainfo-5.1.0.dist-info, PyNaCl-1.4.0.dist-info, pynma, PyNMA-1.0.dist-info, pyOpenSSL-20.0.1.dist-info, pyparsing-2.4.7.dist-info, PySocks-1.7.1.dist-info, pysrt, pysrt-1.1.2.dist-info, python_dateutil-2.8.2.dist-info, python_slugify-5.0.2.dist-info, python_twitter-3.5.dist-info, python3_fanart-2.0.0.dist-info, pytz, pytz-2021.1.dist-info, qbittorrent_api-2021.5.22.dist-info, qbittorrentapi, rarfile-4.0.dist-info, rebulk, rebulk-3.0.1.dist-info, requests, requests_oauthlib, requests_oauthlib-1.3.0.dist-info, requests_toolbelt, requests_toolbelt-0.9.1.dist-info, requests-2.26.0.dist-info, rtorrent, secretstorage, SecretStorage-3.3.1.dist-info, send2trash, Send2Trash-1.7.1.dist-info, setuptools, setuptools-57.1.0.dist-info, sgmllib3k-1.0.0.dist-info, shellingham, shellingham-1.4.0.dist-info, six-1.16.0.dist-info, slugify, soupsieve, soupsieve-2.2.1.dist-info, sqlalchemy, SQLAlchemy-1.4.20.dist-info, stevedore, stevedore-3.3.0.dist-info, subliminal, subliminal-2.1.0.dist-info, temp_babelfish-0.5.6.dev0.dist-info, text_unidecode, text_unidecode-1.3.dist-info, timeago, timeago-1.0.15.dist-info, tmdbsimple, tmdbsimple-2.8.0.dist-info, tomlkit, tomlkit-0.7.2.dist-info, tornado, tornado-6.1.dist-info, tus.py-1.3.4.dist-info, tvdbsimple, tvdbsimple-1.0.6.dist-info, twilio, twilio-6.47.0.dist-info, twitter, tzlocal, tzlocal-2.1.dist-info, unidecode, Unidecode-1.2.0.dist-info, urllib3, urllib3-1.26.6.dist-info, usr, validators, validators-0.18.2.dist-info, virtualenv, virtualenv-20.4.4.dist-info, webencodings, webencodings-0.5.1.dist-info, wheel, wheel-0.34.2.dist-info, win_inet_pton-1.1.0.dist-info, wrapt, wrapt-1.12.1.dist-info, xmltodict-0.10.1.dist-info, zipp-3.5.0.dist-info, _cffi_backend.cpython-37m-x86_64-linux-gnu.so
FILES
_version.py, appdirs.py, configobj.py, decorator.py, distutils-precedence.pth, entrypoints.py, imagesize.py, ipaddress.py, markdown2.py, pip-20.0.2.virtualenv, profilehooks.py, putiopy.py, pyparsing.py, rarfile.py, sgmllib.py, six.py, socks.py, sockshandler.py, tus.py, validate.py, wheel-0.34.2.virtualenv, win_inet_pton.py, xmltodict.py, zipp.py
```

/volume1/@appstore/sickchill/var/data/Logs/sickchill.log
```
2021-07-14 21:18:15 INFO :: EVENT-QUEUE :: Restarting SickChill with ['/volume1/@appstore/sickchill/env/bin/python3', '/volume1/@appstore/sickchill/share/SickChill/SickChill.py', '--daemon', '--nolaunch', '--pidfile', '/volume1/@appstore/sickchill/var/sickchill.pid', '--config', '/volume1/@appstore/sickchill/var/data/config.ini', '--datadir', '/volume1/@appstore/sickchill/var/data']
2021-07-14 21:18:20 INFO :: MAIN :: Restore: restoring cache successful
2021-07-14 21:18:20 INFO :: MAIN :: Restore: Unable to remove the cache/mako directory: [Errno 2] No such file or directory: '/volume1/@appstore/sickchill/var/data/cache/mako'
2021-07-14 21:18:27 DEBUG :: CHECKVERSION :: cur_commit = a0717b2a334bc945fc5ae3aa5fde45160ed1a153, newest_commit = e1e91c3ec3c90479b556e7e78b48dc3bb81ead01, num_commits_behind = 31
2021-07-14 21:18:27 DEBUG :: CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2021-07-14 21:19:25 INFO :: EVENT-QUEUE :: Saving config file to disk
2021-07-14 21:19:25 INFO :: EVENT-QUEUE :: Shutting down Tornado
2021-07-14 21:19:35 INFO :: EVENT-QUEUE :: Restarting SickChill with ['/volume1/@appstore/sickchill/env/bin/python3', '/volume1/@appstore/sickchill/share/SickChill/SickChill.py', '--daemon', '--nolaunch', '--pidfile', '/volume1/@appstore/sickchill/var/sickchill.pid', '--config', '/volume1/@appstore/sickchill/var/data/config.ini', '--datadir', '/volume1/@appstore/sickchill/var/data']
2021-07-14 21:35:46 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
2021-07-14 21:35:46 DEBUG :: CHECKVERSION :: Starting new thread: CHECKVERSION
2021-07-14 21:35:46 INFO :: CHECKVERSION :: Checking for updates using SOURCE

Running
```

**Comment by miigotu** [comment]
You have to uninstall, and do #7281

**Comment by BKSteve** [comment]
after uninstalling I can't get `python -m pip cache dir | sudo xargs rm -rf` to do anything, always get this `/bin/python: No module named pip`
and there's no sickchill folder so no .venv to rm.

**Comment by BKSteve** [comment]
Tried multiple things, removed. Looked for cache. No luck.
reinstalled. cleaned .venv but never more than the few folders and files listed above.
Decided to take a rest and chown fresh install. Running.

**Comment by usk78dk** [comment]
@BKSteve Did you manage to get it running on Synology DSM again? Think I'm facing the same issues you had, but got a but lost in all the above. Also not an expert in all these Lynux (or whatever that is) commands ;-)

**Comment by usk78dk** [comment]
Got a bit lost in all this. I had what seemed to be the same issue as above. I took a backup, removed the DSM package and reinstalled it again. When running it said it was 800+ commits behind. Tried to update but then I couldn't start. The solution for me ended up being quite simple. I removed the package again, installed it again. Before updating a ran the command;
`sudo chown -R sc-sickchill:sickchill /volume1/@appstore/sickchill/env`
After that I clicked update in the UI and it updated fine.
This is mainly posted for others, but also there's the question if this is something that is to part of the install process for the DSM package in the future. I guess a lot of people won't notice this, so hope this somehow can be fixed in the package itself.

**Comment by usk78dk** [comment]
Got a bit lost in all this. I had what seemed to be the same issue as above. I took a backup, removed the DSM package and reinstalled it again. When running it said it was 800+ commits behind. Tried to update but then I couldn't start. Then I removed the package again, installed it again. Before updating a ran the command;
sudo chown -R sc-sickchill:sickchill /volume1/@appstore/sickchill/env
After that I clicked update in the UI and it updated fine.
I thiss something that is to part of the install process for the DSM package in the future. I guess a lot of people won't notice this, so hope this somehow can be fixed in the package itself.
Further if I restore my backup I couldn't start Sickchill up again. So is the only solution just to start all over again with setting it up?

**Comment by BKSteve** [comment]
#7316 for steps to get running, #7249 to see testing actions.

**Comment by usk78dk** [comment]
Thanks alot @BKSteve. Managed to get this to work in the end. Think the trick for me was the python cache thing (or whatever that command was ;-) )

So for other novices out there, here was what worked for me on my DS412+;

Took a backup in SC
Removed the SC package in DSMs package center
Ran the following commands logged in as root through SSH (don't know if both were needed);
'/var/packages/python3/target/bin/python3 -m pip cache dir | sudo xargs rm -rf'
'/var/packages/python38/target/bin/python3 -m pip cache dir | sudo xargs rm -rf'
Installed the SC package again through DSMs package center
Ran the following command
'sudo chown -R sc-sickchill:sickchill /volume1/@appstore/sickchill/env'
Restored my SC backup.

Now everything seems to be fine. SC takes a really long time to start up (already before restoring my SC backup), but as long as it runs, that's the most important for me.
