### ISSUE TITLE
Windows 10 - SickChill service would not start

### ISSUE THREAD

**Issue by tdfisxs** [SickChill/SickChill#7294]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: updated to the latest 
OS: windows 10
Browser: edge
What you did: SickChill service would not start
What happened:  Rebooted, manually ran GIT to pull the newest version, tried manually launching via command line.  Got the results below.
What you expected: service to start
Logs:
```
C:\SickChill\Data>"C:\SickChill\SickChill\SickChill.py" --nolaunch --port=8081 --datadir="C:\SickChill\Data"
Checking poetry
sickchill found: False
We always run from virtualenv when running from source
Because of the above errors, we will try creating a new virtualenvironment in C:\SickChill\SickChill\.venv
virtualenv found: False
virtualenv module not found, getting a portable one to use temporarily
Command result: Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Users\Stan\AppData\Local\Temp\virtualenvhr2q5wh4.pyz\__main__.py", line 168, in <module>
  File "C:\Users\Stan\AppData\Local\Temp\virtualenvhr2q5wh4.pyz\__main__.py", line 164, in run
  File "C:\Users\Stan\AppData\Local\Temp\virtualenvhr2q5wh4.pyz\virtualenv\__main__.py", line 18, in run
  File "C:\Users\Stan\AppData\Local\Temp\virtualenvhr2q5wh4.pyz\virtualenv\run\__init__.py", line 30, in cli_run
  File "C:\Users\Stan\AppData\Local\Temp\virtualenvhr2q5wh4.pyz\virtualenv\run\__init__.py", line 48, in session_via_cli
  File "C:\Users\Stan\AppData\Local\Temp\virtualenvhr2q5wh4.pyz\virtualenv\run\__init__.py", line 74, in build_parser
  File "C:\Users\Stan\AppData\Local\Temp\virtualenvhr2q5wh4.pyz\virtualenv\run\plugin\creators.py", line 15, in __init__
  File "C:\Users\Stan\AppData\Local\Temp\virtualenvhr2q5wh4.pyz\virtualenv\run\plugin\creators.py", line 25, in for_interpreter
  File "C:\Users\Stan\AppData\Local\Temp\virtualenvhr2q5wh4.pyz\virtualenv\create\via_global_ref\builtin\via_global_self_do.py", line 34, in can_create
  File "C:\Users\Stan\AppData\Local\Temp\virtualenvhr2q5wh4.pyz\virtualenv\create\via_global_ref\builtin\via_global_self_do.py", line 39, in _sources_can_be_applied
  File "C:\Users\Stan\AppData\Local\Temp\virtualenvhr2q5wh4.pyz\virtualenv\create\via_global_ref\builtin\cpython\cpython3.py", line 59, in sources
  File "C:\Users\Stan\AppData\Local\Temp\virtualenvhr2q5wh4.pyz\virtualenv\create\via_global_ref\builtin\cpython\cpython3.py", line 86, in include_dll_and_pyd
  File "pathlib.py", line 1118, in iterdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\SickChill\\Python3\\DLLs'

Due to the above error, we cannot continue! Exiting
```

**Comment by itsme9x** [comment]
Backup your sickbeard.db and config.ini.

Uninstall sickchill and all setting, reinstall sickchill and place the sickbeard.db and config.ini back in new installation folder.

This fixed it for me on windows.

**Comment by tdfisxs** [comment]
D:\Sabnzbd\Complete\Evil.S02E04.1080p.HEVC.x265-MeGusta
