### ISSUE TITLE
Fail to launch SC following update

### ISSUE THREAD

**Issue by kaparmar** [SickChill/SickChill#7295]
Branch/Commit: 
OS: MacOS 10.11.6
Browser: Chrome
What you did: Updated to latest version
What happened: Shut down, but didn't restart as it usually does when updating.
What you expected: It to start
Logs:
```
cd '/Applications/SickChill/' && '/usr/local/bin/pythonw' -d  '/Applications/SickChill/SickChill.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Applications/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/Applications/SickChill/sickchill/__init__.py", line 1, in <module>
    from sickchill.init_helpers import maybe_daemonize, poetry_install
  File "/Applications/SickChill/sickchill/init_helpers.py", line 20
    pid_file: Path = None
            ^
SyntaxError: invalid syntax
```
I believe this is the same or similar issue as [https://github.com/SickChill/SickChill/issues/6230](url). I have tried going through that solution but it am left with the same issue. There is no direct solution there for Mac and my computer language is limited.

I tried to use this solution :
Linux with Git

cd path/to/sickchill
systemctl stop sickrage
find . -name "*.pyc" -delete
find lib -empty -type d -delete
git pull
git clean -dfq lib
systemctl start sickrage

But got an error for the "find lib -empty -type d -delete" command that the file or command could not be found.

I proceeded to avoid figuring this out and just reinstalling completely to a new folder, but I get the same error message when trying to open SickChill.py

Thanks for the help!

**Comment by miigotu** [comment]
You need to run SC with python 3.6+. We have been python 3 only all year now.

**Comment by kaparmar** [comment]
Thanks for the reply, I have been opening it with Python Launcher 3.8.2

**Comment by miigotu** [comment]
That there is not a syntax error on 3.6+

**Comment by kretzu77** [comment]
I have Python 3.7.10-16 and I have the same issue after last update
My sickchill is on Synology DSM 6.2.4-25556

Any fix please?

**Comment by miigotu** [comment]
> I have Python 3.7.10-16 and I have the same issue after last update
> My sickchill is on Synology DSM 6.2.4-25556
> 
> Any fix please?
> ![python](https://user-images.githubusercontent.com/30404637/125855612-5d609f29-aa77-40ae-b6a8-e9ccccabced8.JPG)
> 

You cannot have the same syntax error on python 3.6+. It simply is not possible.

**Comment by BUZZ2K** [comment]
Same issue for me on debian. Sickchill doest restart after last update.
I was already with Python 3.7.3, tried to update to 3.9.6, but no luck... sickchill still down. (and now Deluge also ^^)

**Comment by miigotu** [comment]
> Same issue for me on debian. Sickchill doest restart after last update.
> I was already with Python 3.7.3, tried to update to 3.9.6, but no luck... sickchill still down. (and now Deluge also ^^)

Make sure your service is starting it with /usr/bin/python3.7 or whatever and not just /usr/bin/python, because it is likely the bare /python is pointing to python 2 or something lower than 3.6..

Just having a certain version of python installed does not change the command that is called to start a program.

**Comment by snakerman** [comment]
Sorry I made a mistake and Started a new issue with Debian did not see this earlier,

**Comment by BUZZ2K** [comment]
> > Same issue for me on debian. Sickchill doest restart after last update.
> > I was already with Python 3.7.3, tried to update to 3.9.6, but no luck... sickchill still down. (and now Deluge also ^^)
> 
> Make sure your service is starting it with /usr/bin/python3.7 or whatever and not just /usr/bin/python, because it is likely the bare /python is pointing to python 2 or something lower than 3.6..
> 
> Just having a certain version of python installed does not change the command that is called to start a program.

Thanks for the reply. It seems to be good : 
"ExecStart=/usr/bin/env python3 /opt/sickchill/SickChill.py --quiet --config /opt/sickchill/config.ini --datadir /opt/sickchill"

SickChill was working with Python 3.7 before sickchill update

**Comment by burtal** [comment]
Logs from synology 

![image](https://user-images.githubusercontent.com/65765790/126706915-d3d00a89-188a-424b-84e3-e05181ecb986.png)



<html><body>


2021-07-22 20:08:52 | stdout | Pip installed
-- | -- | --
2021-07-22 20:08:52 | stdout |  
2021-07-22 20:08:52 | stdout | Successfully installed pip-21.1.3
2021-07-22 20:08:52 | stdout | Successfully uninstalled pip-21.1.3
2021-07-22 20:08:52 | stdout | Uninstalling pip-21.1.3:
2021-07-22 20:08:52 | stdout | Found existing installation: pip 21.1.3
2021-07-22 20:08:52 | stdout | Attempting uninstall: pip
2021-07-22 20:08:52 | stdout | Installing collected packages: pip
2021-07-22 20:08:52 | stdout | Using cached pip-21.1.3-py3-none-any.whl (1.5 MB)
2021-07-22 20:08:52 | stdout | Command result: Collecting pip
2021-07-22 20:08:48 | stdout | Installing pip
2021-07-22 20:08:47 | stdout | Checking poetry
2021-07-22 20:08:47 | stdout | Restarting SickChill with ['/app/sickchill/.venv/bin/python3.7', 'SickChill.py', '-q', '--nolaunch', '--datadir=/data', '--port', '8081']
2021-07-22 20:08:47 | stdout | We always run from virtualenv when running from source
2021-07-22 20:08:46 | stdout | Checking poetry
2021-07-22 20:08:44 | stdout | Please check the permissions, and that it does not include global site packages
2021-07-22 20:08:44 | stdout | Unable to install to the existing virtual environment located at /app/sickchill/.venv
2021-07-22 20:08:44 | stdout |  
2021-07-22 20:08:44 | stdout | Command result: ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
2021-07-22 20:08:44 | stdout | Trying user site-packages
2021-07-22 20:08:44 | stdout |  
2021-07-22 20:08:44 | stdout | ERROR: Command errored out with exit status 1: /app/sickchill/.venv/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jvl30z65/cffi_4b2c8d34e4524b02833c280e0c271ff4/setup.py'"'"'; file='"'"'/tmp/pip-install-jvl30z65/cffi_4b2c8d34e4524b02833c280e0c271ff4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-_ahojrnu/install-record.txt --single-version-externally-managed --compile --install-headers /app/sickchill/.venv/include/site/python3.7/cffi Check the logs for full command output.
2021-07-22 20:08:44 | stdout | ----------------------------------------
2021-07-22 20:08:44 | stdout | error: command 'gcc' failed with exit status 1
2021-07-22 20:08:44 | stdout | unable to execute 'gcc': No such file or directory
2021-07-22 20:08:44 | stdout | gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/app/sickchill/.venv/include -I/usr/local/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.7/c/_cffi_backend.o
2021-07-22 20:08:44 | stdout | creating build/temp.linux-x86_64-3.7/c
2021-07-22 20:08:44 | stdout | creating build/temp.linux-x86_64-3.7
2021-07-22 20:08:44 | stdout | building '_cffi_backend' extension
2021-07-22 20:08:44 | stdout | running build_ext
2021-07-22 20:08:44 | stdout | copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/_embedding.h -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/verifier.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/recompiler.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/model.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/lock.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/error.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/cparser.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/commontypes.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/api.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/init.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | creating build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | creating build/lib.linux-x86_64-3.7
2021-07-22 20:08:44 | stdout | creating build
2021-07-22 20:08:44 | stdout | running build_py
2021-07-22 20:08:44 | stdout | running build
2021-07-22 20:08:44 | stdout | running install
2021-07-22 20:08:44 | stdout |  
2021-07-22 20:08:44 | stdout | a build done in a different context, you can ignore this warning.
2021-07-22 20:08:44 | stdout | Trying to continue anyway.  If you are trying to install CFFI from
2021-07-22 20:08:44 | stdout |  
2021-07-22 20:08:44 | stdout | the IRC channel #python on irc.libera.chat.)
2021-07-22 20:08:44 | stdout | Otherwise, see https://wiki.python.org/moin/CompLangPython or
2021-07-22 20:08:44 | stdout | -mno-fused-madd see http://stackoverflow.com/questions/22313407/
2021-07-22 20:08:44 | stdout | tries to compile C code.  (Hints: on OS/X 10.8, for errors about
2021-07-22 20:08:44 | stdout | to CFFI but generic to the setup.py of any Python package that
2021-07-22 20:08:44 | stdout | the error messages above.  Likely, the problem is not related
2021-07-22 20:08:44 | stdout | the compiler from Python's standard "distutils" module.  See
2021-07-22 20:08:44 | stdout | No working compiler found, or bogus compiler options passed to
2021-07-22 20:08:44 | stdout |  
2021-07-22 20:08:44 | stdout | unable to execute 'gcc': No such file or directory
2021-07-22 20:08:44 | stdout | unable to execute 'gcc': No such file or directory
2021-07-22 20:08:44 | stdout | Complete output (48 lines):
2021-07-22 20:08:44 | stdout | cwd: /tmp/pip-install-jvl30z65/cffi_4b2c8d34e4524b02833c280e0c271ff4/
2021-07-22 20:08:44 | stdout | command: /app/sickchill/.venv/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jvl30z65/cffi_4b2c8d34e4524b02833c280e0c271ff4/setup.py'"'"'; file='"'"'/tmp/pip-install-jvl30z65/cffi_4b2c8d34e4524b02833c280e0c271ff4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-_ahojrnu/install-record.txt --single-version-externally-managed --compile --install-headers /app/sickchill/.venv/include/site/python3.7/cffi
2021-07-22 20:08:44 | stdout | ERROR: Command errored out with exit status 1:
2021-07-22 20:08:44 | stdout | ERROR: Failed building wheel for cffi
2021-07-22 20:08:44 | stdout | ----------------------------------------
2021-07-22 20:08:44 | stdout | error: command 'gcc' failed with exit status 1
2021-07-22 20:08:44 | stdout | unable to execute 'gcc': No such file or directory
2021-07-22 20:08:44 | stdout | gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/app/sickchill/.venv/include -I/usr/local/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.7/c/_cffi_backend.o
2021-07-22 20:08:44 | stdout | creating build/temp.linux-x86_64-3.7/c
2021-07-22 20:08:44 | stdout | creating build/temp.linux-x86_64-3.7
2021-07-22 20:08:44 | stdout | building '_cffi_backend' extension
2021-07-22 20:08:44 | stdout | running build_ext
2021-07-22 20:08:44 | stdout | copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/_embedding.h -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/verifier.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/recompiler.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/model.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/lock.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/error.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/cparser.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/commontypes.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/api.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | copying cffi/init.py -> build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | creating build/lib.linux-x86_64-3.7/cffi
2021-07-22 20:08:44 | stdout | creating build/lib.linux-x86_64-3.7
2021-07-22 20:08:44 | stdout | creating build
2021-07-22 20:08:44 | stdout | running build_py
2021-07-22 20:08:44 | stdout | running build
2021-07-22 20:08:44 | stdout | running bdist_wheel
2021-07-22 20:08:44 | stdout |  
2021-07-22 20:08:44 | stdout | a build done in a different context, you can ignore this warning.
2021-07-22 20:08:44 | stdout | Trying to continue anyway.  If you are trying to install CFFI from


</body>
</html>
