### ISSUE TITLE
Sickchill Debian Buster

### ISSUE THREAD

**Issue by snakerman** [SickChill/SickChill#7344]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Debian Buster
Browser:  Safari
What you did:  Tried to start it after the autoupdate at 04:30 am
What happened: Failed to Start
What you expected:  To Start
Logs:
```
PASTE LOGS HERE
```2021-07-22 04:38:36 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR-AUTO thread to exit
2021-07-22 04:38:36 INFO :: EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2021-07-22 04:38:36 INFO :: EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2021-07-22 04:38:36 INFO :: EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2021-07-22 04:38:36 INFO :: EVENT-QUEUE :: Waiting for the NOTIFICATIONS thread to exit
2021-07-22 04:38:36 INFO :: EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2021-07-22 04:38:36 INFO :: EVENT-QUEUE :: Saving all shows to the database
2021-07-22 04:38:42 INFO :: EVENT-QUEUE :: Saving config file to disk
2021-07-22 04:38:42 INFO :: EVENT-QUEUE :: Shutting down Tornado
2021-07-22 04:38:52 INFO :: EVENT-QUEUE :: Restarting SickChill with ['/home/owner/.sickchill/.venv/bin/python3.7', '/home/owner/.sickchill/SickChill.py', '-q', '--daemon', '--nolaunch', '--datadir=/home/owner/.sickchill']

**Comment by snakerman** [comment]
sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2021-07-22 08:52:42 EDT; 1s ago
  Process: 4604 ExecStart=/usr/bin/python3 /home/owner/.sickchill/SickChill.py -q --daemon --nolaunch --datadir=/home/owner/.sickchill (code=exited, status=0/SUCCESS)

Jul 22 08:52:39 HpXXXX systemd[1]: Starting SickChill Daemon...
Jul 22 08:52:40 HpXXXX systemd[1]: Started SickChill Daemon.
Jul 22 08:52:42 HpXXXX systemd[1]: sickchill.service: Succeeded.


Debug active in settings give me no more info
Leaving my systemd status also

**Comment by crbenne** [comment]
I'm having the same problem -- on a Pi 4 Raspberry Pi OS/Buster, everything was working fine until I attempted to update to the latest version a couple of days ago.

If if attempt to start I get the following error:
```
pi@mediapi:~ $ /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill
Checking poetry
Current environment is not writable!
Source dir is not writable by this user either, we cannot continue: f/opt/sickchill
```

I haven't changed any permissions or configuration options -- I have one override for systemd unit so the service waits for an external drive to be mounted, here is systemd status:
```
● sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/sickchill.service.d
           └─override.conf
   Active: inactive (dead) since Thu 2021-07-22 15:36:57 EDT; 15min ago
  Process: 814 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, status=0/SUCCESS)

Jul 22 15:36:54 mediapi systemd[1]: Starting SickChill Daemon...
Jul 22 15:36:54 mediapi systemd[1]: Started SickChill Daemon.
Jul 22 15:36:57 mediapi systemd[1]: sickchill.service: Succeeded.
```

**Comment by LeePorte** [comment]
I'm seeing the following on ubuntu 20.04 

```
$ /usr/bin/python3 /opt/SickChill/SickChill.py --nolaunch --pidfile=/run/sickchill/sickchill.pid --datadir=/opt/SickChill --config=/opt/.SickChill/config.ini
Checking poetry
sickchill found: False
Current environment is not writable!
Restarting SickChill with ['/opt/SickChill/.venv/bin/python3.8', '/opt/SickChill/SickChill.py', '--nolaunch', '--pidfile=/run/sickchill/sickchill.pid', '--datadir=/opt/SickChill', '--config=/opt/.SickChill/config.ini']
Checking poetry
sickchill found: False
pip found: True
pip args: /opt/SickChill/.venv/bin/python3.8 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -qU --find-links=https://wheel-index.linuxserver.io/ubuntu/ setuptools poetry --pre
Command result: WARNING: Ignoring invalid distribution -yparsing (/opt/SickChill/.venv/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -yparsing (/opt/SickChill/.venv/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -yparsing (/opt/SickChill/.venv/lib/python3.8/site-packages)

poetry found: True

  ModuleNotFoundError

  No module named 'poetry_date_version_plugin'

  at <frozen importlib._bootstrap>:973 in _find_and_load_unlocked
Unable to install to the existing virtual environment located at /opt/SickChill/.venv
Please check the permissions, and that it does not include global site packages
$ 
```

**Comment by miigotu** [comment]
> I'm having the same problem -- on a Pi 4 Raspberry Pi OS/Buster, everything was working fine until I attempted to update to the latest version of SickChill a couple of days ago.
> 
> If if attempt to start interactively I get the following error:
> ```
> pi@mediapi:~ $ /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill
> Checking poetry
> Current environment is not writable!
> Source dir is not writable by this user either, we cannot continue: f/opt/sickchill
> ```
> 
> I haven't changed any permissions or configuration options -- I have one override for systemd unit so the service waits for an external drive to be mounted, here is systemd status:
> ```
> ● sickchill.service - SickChill Daemon
>    Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
>   Drop-In: /etc/systemd/system/sickchill.service.d
>            └─override.conf
>    Active: inactive (dead) since Thu 2021-07-22 15:36:57 EDT; 15min ago
>   Process: 814 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, status=0/SUCCESS)
> 
> Jul 22 15:36:54 mediapi systemd[1]: Starting SickChill Daemon...
> Jul 22 15:36:54 mediapi systemd[1]: Started SickChill Daemon.
> Jul 22 15:36:57 mediapi systemd[1]: sickchill.service: Succeeded.
> ```

chown -R the sickchill folder to the user:group it runs as.

**Comment by miigotu** [comment]
> I'm seeing the following on ubuntu 20.04 
> 
> ```
> $ /usr/bin/python3 /opt/SickChill/SickChill.py --nolaunch --pidfile=/run/sickchill/sickchill.pid --datadir=/opt/SickChill --config=/opt/.SickChill/config.ini
> Checking poetry
> sickchill found: False
> Current environment is not writable!
> Restarting SickChill with ['/opt/SickChill/.venv/bin/python3.8', '/opt/SickChill/SickChill.py', '--nolaunch', '--pidfile=/run/sickchill/sickchill.pid', '--datadir=/opt/SickChill', '--config=/opt/.SickChill/config.ini']
> Checking poetry
> sickchill found: False
> pip found: True
> pip args: /opt/SickChill/.venv/bin/python3.8 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -qU --find-links=https://wheel-index.linuxserver.io/ubuntu/ setuptools poetry --pre
> Command result: WARNING: Ignoring invalid distribution -yparsing (/opt/SickChill/.venv/lib/python3.8/site-packages)
> WARNING: Ignoring invalid distribution -yparsing (/opt/SickChill/.venv/lib/python3.8/site-packages)
> WARNING: Ignoring invalid distribution -yparsing (/opt/SickChill/.venv/lib/python3.8/site-packages)
> 
> poetry found: True
> 
>   ModuleNotFoundError
> 
>   No module named 'poetry_date_version_plugin'
> 
>   at <frozen importlib._bootstrap>:973 in _find_and_load_unlocked
> Unable to install to the existing virtual environment located at /opt/SickChill/.venv
> Please check the permissions, and that it does not include global site packages
> $ 
> $ python3 --version
> Python 3.8.10
> $ 
> ```

I'm going to be fixing that, for now you could `/opt/SickChill/.venv/bin/python3.8 -m pip install poetry_date_version_plugin`

**Comment by crbenne** [comment]
> > I'm having the same problem -- on a Pi 4 Raspberry Pi OS/Buster, everything was working fine until I attempted to update to the latest version of SickChill a couple of days ago.
> > If if attempt to start interactively I get the following error:
> > ```
> > pi@mediapi:~ $ /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill
> > Checking poetry
> > Current environment is not writable!
> > Source dir is not writable by this user either, we cannot continue: f/opt/sickchill
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I haven't changed any permissions or configuration options -- I have one override for systemd unit so the service waits for an external drive to be mounted, here is systemd status:
> > ```
> > ● sickchill.service - SickChill Daemon
> >    Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
> >   Drop-In: /etc/systemd/system/sickchill.service.d
> >            └─override.conf
> >    Active: inactive (dead) since Thu 2021-07-22 15:36:57 EDT; 15min ago
> >   Process: 814 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, status=0/SUCCESS)
> > 
> > Jul 22 15:36:54 mediapi systemd[1]: Starting SickChill Daemon...
> > Jul 22 15:36:54 mediapi systemd[1]: Started SickChill Daemon.
> > Jul 22 15:36:57 mediapi systemd[1]: sickchill.service: Succeeded.
> > ```
> 
> chown -R the sickchill folder to the user:group it runs as.

Ok so I checked /etc/systemd/system/sickchill.service, it's running as sickchill:sickchill -- so I did:
```
$ sudo chown -R sickchill:sickchill /opt/sickchill
```

But still not able to start the service (the directory was already set to that owner:group before and was working before the update)

**Comment by miigotu** [comment]
> > > I'm having the same problem -- on a Pi 4 Raspberry Pi OS/Buster, everything was working fine until I attempted to update to the latest version of SickChill a couple of days ago.
> > > If if attempt to start interactively I get the following error:
> > > ```
> > > pi@mediapi:~ $ /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill
> > > Checking poetry
> > > Current environment is not writable!
> > > Source dir is not writable by this user either, we cannot continue: f/opt/sickchill
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I haven't changed any permissions or configuration options -- I have one override for systemd unit so the service waits for an external drive to be mounted, here is systemd status:
> > > ```
> > > ● sickchill.service - SickChill Daemon
> > >    Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
> > >   Drop-In: /etc/systemd/system/sickchill.service.d
> > >            └─override.conf
> > >    Active: inactive (dead) since Thu 2021-07-22 15:36:57 EDT; 15min ago
> > >   Process: 814 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, status=0/SUCCESS)
> > > 
> > > Jul 22 15:36:54 mediapi systemd[1]: Starting SickChill Daemon...
> > > Jul 22 15:36:54 mediapi systemd[1]: Started SickChill Daemon.
> > > Jul 22 15:36:57 mediapi systemd[1]: sickchill.service: Succeeded.
> > > ```
> > 
> > chown -R the sickchill folder to the user:group it runs as.
> 
> Ok so I checked /etc/systemd/system/sickchill.service, it's running as sickchill:sickchill -- so I did:
> ```
> $ sudo chown -R sickchill:sickchill /opt/sickchill
> ```
> 
> But still not able to start the service (the directory was already set to that owner:group before and was working before the update)
> 
> update: Tried running as root to rule out a permission problem:
> ```
> $ sudo /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill
> Checking poetry
> We always run from virtualenv when running from source
> Because of the above errors, we will try creating a new virtualenvironment in /opt/sickchill/.venv
> virtualenv module not found, getting a portable one to use temporarily
> Command result: Traceback (most recent call last):
>   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/tmp/virtualenv5oofzvsv.pyz/__main__.py", line 168, in <module>
>   File "/tmp/virtualenv5oofzvsv.pyz/__main__.py", line 164, in run
>   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/__main__.py", line 18, in run
>   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/run/__init__.py", line 32, in cli_run
>   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/run/session.py", line 46, in run
>   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/run/session.py", line 53, in _create
>   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/creator.py", line 171, in run
>   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 79, in create
>   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 104, in ensure_directories
>   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/describe.py", line 29, in bin_dir
>   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/describe.py", line 33, in script_dir
>   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/discovery/py_info.py", line 125, in install_path
>   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/discovery/py_info.py", line 125, in <dictcomp>
> ValueError: too many values to unpack (expected 2)
> 
> Due to the above error, we cannot continue! Exiting
> ```
> 

The instant you run as root you break permissions. The instant you use for commands with root, you break permissions.

pip install virtualenv, or wait until the next release.

**Comment by mavack** [comment]
Having similar problems on centos 8
Wiped it, pulled fresh git over, copied sickchill.db over
started fresh fine

stopped it
restarted it and same failure again as 

```
service sickchill status
Redirecting to /bin/systemctl status sickchill.service
● sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Fri 2021-07-23 16:31:58 AEST; 3min 11s ago
  Process: 147824 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, status=0/SUCCESS)

Jul 23 16:31:57 web2.homenet.lan systemd[1]: Starting SickChill Daemon...
Jul 23 16:31:57 web2.homenet.lan systemd[1]: Started SickChill Daemon.
Jul 23 16:31:58 web2.homenet.lan systemd[1]: sickchill.service: Succeeded.


/usr/bin/python3 /opt/sickchill/SickChill.py -q --nolaunch --datadir=/opt/sickchill         
Checking poetry
sickchill found: False
We always run from virtualenv when running from source
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3.6', '/opt/sickchill/SickChill.py', '-q', '--nolaunch', '--datadir=/opt/sickchill']
Checking poetry
sickchill found: False
pip found: True
pip args: /opt/sickchill/.venv/bin/python3.6 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -qU setuptools poetry --pre
poetry found: True

  ModuleNotFoundError

  No module named 'poetry_date_version_plugin'

  at <frozen importlib._bootstrap>:953 in _find_and_load_unlocked
Unable to install to the existing virtual environment located at /opt/sickchill/.venv
Please check the permissions, and that it does not include global site packages
```

**Comment by crbenne** [comment]
> > > > I'm having the same problem -- on a Pi 4 Raspberry Pi OS/Buster, everything was working fine until I attempted to update to the latest version of SickChill a couple of days ago.
> > > > If if attempt to start interactively I get the following error:
> > > > ```
> > > > pi@mediapi:~ $ /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill
> > > > Checking poetry
> > > > Current environment is not writable!
> > > > Source dir is not writable by this user either, we cannot continue: f/opt/sickchill
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I haven't changed any permissions or configuration options -- I have one override for systemd unit so the service waits for an external drive to be mounted, here is systemd status:
> > > > ```
> > > > ● sickchill.service - SickChill Daemon
> > > >    Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
> > > >   Drop-In: /etc/systemd/system/sickchill.service.d
> > > >            └─override.conf
> > > >    Active: inactive (dead) since Thu 2021-07-22 15:36:57 EDT; 15min ago
> > > >   Process: 814 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, status=0/SUCCESS)
> > > > 
> > > > Jul 22 15:36:54 mediapi systemd[1]: Starting SickChill Daemon...
> > > > Jul 22 15:36:54 mediapi systemd[1]: Started SickChill Daemon.
> > > > Jul 22 15:36:57 mediapi systemd[1]: sickchill.service: Succeeded.
> > > > ```
> > > 
> > > 
> > > chown -R the sickchill folder to the user:group it runs as.
> > 
> > 
> > Ok so I checked /etc/systemd/system/sickchill.service, it's running as sickchill:sickchill -- so I did:
> > ```
> > $ sudo chown -R sickchill:sickchill /opt/sickchill
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But still not able to start the service (the directory was already set to that owner:group before and was working before the update)
> > update: Tried running as root to rule out a permission problem:
> > ```
> > $ sudo /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill
> > Checking poetry
> > We always run from virtualenv when running from source
> > Because of the above errors, we will try creating a new virtualenvironment in /opt/sickchill/.venv
> > virtualenv module not found, getting a portable one to use temporarily
> > Command result: Traceback (most recent call last):
> >   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
> >     "__main__", mod_spec)
> >   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
> >     exec(code, run_globals)
> >   File "/tmp/virtualenv5oofzvsv.pyz/__main__.py", line 168, in <module>
> >   File "/tmp/virtualenv5oofzvsv.pyz/__main__.py", line 164, in run
> >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/__main__.py", line 18, in run
> >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/run/__init__.py", line 32, in cli_run
> >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/run/session.py", line 46, in run
> >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/run/session.py", line 53, in _create
> >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/creator.py", line 171, in run
> >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 79, in create
> >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 104, in ensure_directories
> >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/describe.py", line 29, in bin_dir
> >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/describe.py", line 33, in script_dir
> >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/discovery/py_info.py", line 125, in install_path
> >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/discovery/py_info.py", line 125, in <dictcomp>
> > ValueError: too many values to unpack (expected 2)
> > 
> > Due to the above error, we cannot continue! Exiting
> > ```
> 
> The instant you run as root you break permissions. The instant you use for commands with root, you break permissions.
> 
> pip install virtualenv, or wait until the next release.

Installing virtualenv now allows the daemon to start via systemd, however the web interface is not accessible, getting a "refused to connect error" hmm

**Comment by miigotu** [comment]
> > > > > I'm having the same problem -- on a Pi 4 Raspberry Pi OS/Buster, everything was working fine until I attempted to update to the latest version of SickChill a couple of days ago.
> > > > > If if attempt to start interactively I get the following error:
> > > > > ```
> > > > > pi@mediapi:~ $ /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill
> > > > > Checking poetry
> > > > > Current environment is not writable!
> > > > > Source dir is not writable by this user either, we cannot continue: f/opt/sickchill
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > I haven't changed any permissions or configuration options -- I have one override for systemd unit so the service waits for an external drive to be mounted, here is systemd status:
> > > > > ```
> > > > > ● sickchill.service - SickChill Daemon
> > > > >    Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
> > > > >   Drop-In: /etc/systemd/system/sickchill.service.d
> > > > >            └─override.conf
> > > > >    Active: inactive (dead) since Thu 2021-07-22 15:36:57 EDT; 15min ago
> > > > >   Process: 814 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, status=0/SUCCESS)
> > > > > 
> > > > > Jul 22 15:36:54 mediapi systemd[1]: Starting SickChill Daemon...
> > > > > Jul 22 15:36:54 mediapi systemd[1]: Started SickChill Daemon.
> > > > > Jul 22 15:36:57 mediapi systemd[1]: sickchill.service: Succeeded.
> > > > > ```
> > > > 
> > > > 
> > > > chown -R the sickchill folder to the user:group it runs as.
> > > 
> > > 
> > > Ok so I checked /etc/systemd/system/sickchill.service, it's running as sickchill:sickchill -- so I did:
> > > ```
> > > $ sudo chown -R sickchill:sickchill /opt/sickchill
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > But still not able to start the service (the directory was already set to that owner:group before and was working before the update)
> > > update: Tried running as root to rule out a permission problem:
> > > ```
> > > $ sudo /usr/bin/python3 /opt/sickchill/SickChill.py --nolaunch --datadir=/opt/sickchill
> > > Checking poetry
> > > We always run from virtualenv when running from source
> > > Because of the above errors, we will try creating a new virtualenvironment in /opt/sickchill/.venv
> > > virtualenv module not found, getting a portable one to use temporarily
> > > Command result: Traceback (most recent call last):
> > >   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
> > >     "__main__", mod_spec)
> > >   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
> > >     exec(code, run_globals)
> > >   File "/tmp/virtualenv5oofzvsv.pyz/__main__.py", line 168, in <module>
> > >   File "/tmp/virtualenv5oofzvsv.pyz/__main__.py", line 164, in run
> > >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/__main__.py", line 18, in run
> > >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/run/__init__.py", line 32, in cli_run
> > >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/run/session.py", line 46, in run
> > >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/run/session.py", line 53, in _create
> > >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/creator.py", line 171, in run
> > >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 79, in create
> > >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/via_global_ref/builtin/via_global_self_do.py", line 104, in ensure_directories
> > >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/describe.py", line 29, in bin_dir
> > >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/create/describe.py", line 33, in script_dir
> > >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/discovery/py_info.py", line 125, in install_path
> > >   File "/tmp/virtualenv5oofzvsv.pyz/virtualenv/discovery/py_info.py", line 125, in <dictcomp>
> > > ValueError: too many values to unpack (expected 2)
> > > 
> > > Due to the above error, we cannot continue! Exiting
> > > ```
> > 
> > The instant you run as root you break permissions. The instant you use for commands with root, you break permissions.
> > 
> > pip install virtualenv, or wait until the next release.
> 
> Installing virtualenv now allows the daemon to start via systemd, ~however the web interface is not accessible, getting a "refused to connect" error hmm~ disregard, a reboot cleared that up, working now 👍 

Installing virtualenv is likely unnecessary after 2021.7.23

**Comment by papaxris** [comment]
For those interested.

Upgrade from:
Version: v2021.06.16-1

To:
Version: 2021.07.23

Worked without issue.  No errors.

Thank you @miigotu !

**Comment by LeePorte** [comment]
I've needed to keep virtualenv post 2021.7.23-1

**Comment by mavack** [comment]
yeah changes in 2021.07.23 have resolved it for me also

**Comment by miigotu** [comment]
> I've needed to keep virtualenv post 2021.7.23-1

Not if it is going to create a new virtual env, unless `python -m venv` doesn't work on your system? Virtualenv module is just for creating an environment.

**Comment by andefil** [comment]
Hi guys, 
please some help.
I'm on raspberry 3b+
I had the same problem. Now iìm able to start sickchill by command line but not as a service anymore.
I have all the permissions set for the user pi and the service too starts for the user pi, but checking the status it says that the service exited.
I updated to the 23july 
Does anyone solved this issue for the service
Thanks for any help

**Comment by snakerman** [comment]
Working for me on Debian buster now also, Does not die.  More testing today.

**Comment by snakerman** [comment]
One thing I noticed its not grabbing my nab from backlog or current having to add them manually!  Anyone else having this problem?

Debian Buster

**Comment by BUZZ2K** [comment]
Fresh install of debian 10 for me today. I have been able to reinstall deluge, nginx, etc and make them working, but impossible to get sickchill run after following this setup guide https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15 

Tried to change a bit the guide to run as root user, but nothing better... sickchill doesnt launch...

Thanks in advance for your help

**Comment by miigotu** [comment]
> Fresh install of debian 10 for me today. I have been able to reinstall deluge, nginx, etc and make them working, but impossible to get sickchill run after following this setup guide https://github.com/SickChill/SickChill/wiki/SickChill-installation-Ubuntu-15
> 
> Tried to change a bit the guide to run as root user, but nothing better... sickchill doesnt launch...
> 
> Thanks in advance for your help

Makes sense, that's an outdated guide that is for Ubuntu 15, not debian 10. Also, doing anything as root makes absolutely zero sense.

**Comment by BUZZ2K** [comment]
> Makes sense, that's an outdated guide that is for Ubuntu 15, not debian 10. Also, doing anything as root makes absolutely zero sense.

Referenced as "Debian/Ubuntu 15.x with systemd:" and did'nt find any other guide for debian so i guessed it was the good one. If any other guide would be more accurate, i would appreciate a link.

**Comment by miigotu** [comment]
```bash
sudo apt install python3.8
python3.8 -m venv ~/sickchill-env --with-pip

~/sickchill-env/bin/pip install sickchill
~/sickchill-env/bin/python ~/sickchill-env/bin/SickChill.py
```

**Comment by BUZZ2K** [comment]
> sudo apt install python3.8
Debian 10 doesnt find packet but i used to install manually python 3.8 aside.

> python3.8 -m venv ~/sickchill-env --with-pip
--with-pip is refused. seems to be only --without-pip available. I removed --with-pip and it worked

> ~/sickchill-env/bin/pip install sickchill
> ~/sickchill-env/bin/python ~/sickchill-env/bin/SickChill.py
I used to set /opt/sickchill-env... is it bad ?

All of this is now working. Thanks a lot @miigotu 

I see that the main folder is /root/sickchill, is it ok ?

how can i do to launch sickchill like that on restart ?

Thanks in advance guys, i hope this will help debian 10 users to solve this

**Comment by BUZZ2K** [comment]
Anyone knows how to launch this on startup ? : 

/opt/sickchill-env/bin/python /opt/sickchill-env/bin/SickChill.py

thanks in advance

**Comment by LeePorte** [comment]
What have you got in the systemd file?

Something along the line of this should work for you

```
### Configuration

[Unit]
Description=SickChill Daemon

[Service]
User=sickchill
Group=sickchill

Type=forking
PIDFile=/run/sickchill/sickchill.pid
EnvironmentFile=/opt/.SickChill/config.ini
ExecStart=/opt/sickchill-env/bin/python /opt/sickchill-env/bin/SickChill.py -q --daemon --nolaunch --pidfile=/run/sickchill/sickchill.pid --datadir= /opt/sickchill-env
ExecReload=/bin/sh -c "/bin/kill -s HUP $(/bin/cat /run/sickchill/sickchill.pid)"
ExecStop=/bin/sh -c "/bin/kill -s TERM $(/bin/cat /run/sickchill/sickchill.pid)"

[Install]
WantedBy=multi-user.target
```

**Comment by BUZZ2K** [comment]
Hi @LeePorte ,

Thanks for your reply. I have what you have replied, exept the lines "PIDFile", "ExecReload" and "ExecStop".

By the way, i do not have anything like /run/sickchill/sickchill.pid
Dont know where to find this PID file to modify like you replied.

**Comment by BUZZ2K** [comment]
[Unit]
Description=SickChill Daemon

[Service]
Typz=forking

User=sickchill
Group=sickchill
UMask=027

ExecStart=/opt/sickchill-env/bin/python /opt/sickchill-env/bin/SickChill.py -q --daemon

[Install]
WantedBy=multi-user.target

**Comment by BUZZ2K** [comment]
also tried with Type=simple to setup like deluge.. doest work

**Comment by LeePorte** [comment]
Is the systemd file enabled?

Do you see any errors after starting with `systemctl status sickchill` or `journalctl -xe`?

To create the temp dir for the pid file I have the folliwing in a file located at `/usr/lib/tmpfiles.d/sickchill.conf`

```
d /run/sickchill 0755 sickchill sickchill -
```

**Comment by BUZZ2K** [comment]
Hi everyone,

Thanks @LeePorte  for your help. Now, the systemd file seems to be considered by the system and on startup, sickchill is launched.

But : 

● sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
   Active: activating (start) since Mon 2021-08-02 07:39:58 UTC; 1min 1s ago
  Process: 500 ExecStart=/opt/sickchill-env/bin/python /opt/sickchill-env/bin/SickChill.py -q --daemon (code=exited, status=0/SUCCESS)
    Tasks: 16 (limit: 4915)
   Memory: 176.8M
   CGroup: /system.slice/sickchill.service
           └─546 /opt/sickchill-env/bin/python /opt/sickchill-env/bin/SickChill.py -q --daemon

Aug 02 07:39:58 vps-5e21893a systemd[1]: Starting SickChill Daemon...
Aug 02 07:39:58 vps-5e21893a systemd[1]: sickchill.service: Can't open PID file /run/sickchill/sickchill.pid (yet?) after start: No such file or directory

No PID file is created in /run/sickchill/

so sickchill is started but fail a few minutes later : 

● sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Mon 2021-08-02 07:41:38 UTC; 2min 51s ago
  Process: 500 ExecStart=/opt/sickchill-env/bin/python /opt/sickchill-env/bin/SickChill.py -q --daemon (code=exited, status=0/SUCCESS)

Aug 02 07:39:58 vps-5e21893a systemd[1]: Starting SickChill Daemon...
Aug 02 07:39:58 vps-5e21893a systemd[1]: sickchill.service: Can't open PID file /run/sickchill/sickchill.pid (yet?) after start: No such file or directory
Aug 02 07:41:27 vps-5e21893a systemd[1]: sickchill.service: Start operation timed out. Terminating.
Aug 02 07:41:38 vps-5e21893a systemd[1]: sickchill.service: Failed with result 'timeout'.
Aug 02 07:41:38 vps-5e21893a systemd[1]: Failed to start SickChill Daemon.
