### ISSUE TITLE
ModuleNotFoundError: No module named 'github'

### ISSUE THREAD

**Issue by MrHappy** [SickChill/SickChill#7389]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: latest
OS: Windows
Browser: irrelevant
What you did: updated to latest pull
What happened: installation broke
What you expected: flawlessly working
Logs:
```
Traceback (most recent call last):
  File "C:\SickChill\sickchill.py", line 14, in <module>
    import sickchill.start
  File "C:\SickChill\sickchill\__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "C:\SickChill\sickchill\show\indexers\__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "C:\SickChill\sickchill\show\indexers\handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "C:\SickChill\sickchill\logger.py", line 12, in <module>
    from github import InputFileContent
ModuleNotFoundError: No module named 'github'
```

**Comment by miigotu** [comment]
Uninstall without deleting data, use the newest installer. We don't use git on windows anymore.

**Comment by MrHappy** [comment]
Removed the entire folder and installed using the exe.
However the service keeps status 'paused'. Tried reinstalling and same result.
What am I missing?
