### ISSUE TITLE
Daily search not working

### ISSUE THREAD

**Issue by nitedevil** [SickChill/SickChill#7539]
Been having an issue where i have to do a manual search to download anything.. Daily searches do not run

Branch/Commit: pip/master
OS: Windows 10
Browser: Chrome
What you did: Start sickchill
What happened:  Exception generated in thread DAILYSEARCHER: [Errno 22] Invalid argument
What you expected:
Logs:
```
2021-10-01 22:32:02 INFO :: DAILYSEARCHER :: Searching for new released episodes ...
2021-10-01 22:32:02 ERROR :: DAILYSEARCHER :: Exception generated in thread DAILYSEARCHER: [Errno 22] Invalid argument
2021-10-01 22:32:02 DEBUG :: DAILYSEARCHER :: 'Traceback (most recent call last):
  File "C:\\SickChill\\Python3\\tools\\lib\\site-packages\\sickchill\\oldbeard\\scheduler.py", line 93, in run
    self.action.run(self.force)
  File "C:\\SickChill\\Python3\\tools\\lib\\site-packages\\sickchill\\oldbeard\\dailysearcher.py", line 62, in run
    air_time = network_timezones.parse_date_time(sqlEp["airdate"], show.airs, show.network).astimezone(network_timezones.sb_timezone)
  File "C:\\SickChill\\Python3\\tools\\lib\\site-packages\\dateutil\\tz\\_common.py", line 144, in fromutc
    return f(self, dt)
  File "C:\\SickChill\\Python3\\tools\\lib\\site-packages\\dateutil\\tz\\_common.py", line 258, in fromutc
    dt_wall = self._fromutc(dt)
  File "C:\\SickChill\\Python3\\tools\\lib\\site-packages\\dateutil\\tz\\_common.py", line 222, in _fromutc
    dtoff = dt.utcoffset()
  File "C:\\SickChill\\Python3\\tools\\lib\\site-packages\\dateutil\\tz\\tz.py", line 222, in utcoffset
    if self._isdst(dt):
  File "C:\\SickChill\\Python3\\tools\\lib\\site-packages\\dateutil\\tz\\tz.py", line 291, in _isdst
    dstval = self._naive_is_dst(dt)
  File "C:\\SickChill\\Python3\\tools\\lib\\site-packages\\dateutil\\tz\\tz.py", line 260, in _naive_is_dst
    return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument
'
```

**Comment by nitedevil** [comment]
Also now noticing the error in backlog overview

Traceback (most recent call last):
File C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\common.py:86, in render:
return self.template.render_unicode(*args, **context)
File C:\SickChill\Python3\tools\lib\site-packages\mako\template.py:478, in render_unicode:
return runtime._render(
File C:\SickChill\Python3\tools\lib\site-packages\mako\runtime.py:878, in _render:
_render_context(
File C:\SickChill\Python3\tools\lib\site-packages\mako\runtime.py:920, in _render_context:
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File C:\SickChill\Python3\tools\lib\site-packages\mako\runtime.py:947, in _exec_template:
callable_(context, *args, **kwargs)
File C:/SickChill/Python3/tools/lib/site-packages/sickchill/gui/slick/views/layouts/main.mako:325, in render_body:
File C:/SickChill/Python3/tools/lib/site-packages/sickchill/gui/slick/views/manage_backlogOverview.mako:106, in render_content: ${sbdatetime.sbdatetime.sbfdatetime(airDate)} File C:\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py:222, in utcoffset: if self._isdst(dt): File C:\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py:291, in _isdst: dstval = self._naive_is_dst(dt) File C:\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py:260, in _naive_is_dst: return time.localtime(timestamp + time.timezone).tm_isdst OSError: [Errno 22] Invalid argument
