### ISSUE TITLE
Can't access web interface ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by damagu** [SickChill/SickChill#7635]
Branch/Commit: 80528da322023b04102f2801d620fd1b8f8d09a7 (based on the log info)
OS: OSMC
Browser: Chrome 95.0.4638.69 
What you did: tried to view the web interface via chrome.
What happened:
```
This site can’t be reached 192.168.178.10 refused to connect.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

Logs:
```
2021-11-07 14:18:18 INFO :: POSTPROCESSOR-MANUAL :: Manual post processing task for /media/8TB_HD/files/downloads/tvshows completed
2021-11-07 14:18:25 INFO :: CHECKVERSION :: Config backup successful, updating...
2021-11-07 14:18:25 DEBUG :: CHECKVERSION :: Executing git symbolic-ref -q HEAD with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:25 DEBUG :: CHECKVERSION :: git symbolic-ref -q HEAD : returned successful
2021-11-07 14:18:25 DEBUG :: CHECKVERSION :: Executing git rev-parse HEAD with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:25 DEBUG :: CHECKVERSION :: git rev-parse HEAD : returned successful
2021-11-07 14:18:25 DEBUG :: CHECKVERSION :: Executing git config remote.origin.url https://github.com/SickChill/SickChill.git with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:25 DEBUG :: CHECKVERSION :: Executing git fetch origin --prune with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:31 DEBUG :: CHECKVERSION :: git fetch origin --prune : returned successful
2021-11-07 14:18:31 DEBUG :: CHECKVERSION :: Executing git branch --set-upstream-to origin/master with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:31 DEBUG :: CHECKVERSION :: Executing git branch -u origin/master with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:31 DEBUG :: CHECKVERSION :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:32 DEBUG :: CHECKVERSION :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2021-11-07 14:18:32 DEBUG :: CHECKVERSION :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:32 DEBUG :: CHECKVERSION :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2021-11-07 14:18:32 DEBUG :: CHECKVERSION :: cur_commit = 46455f17ef5e14a3b2581a522081cf1c33f4a0d8, newest_commit = 80528da322023b04102f2801d620fd1b8f8d09a7, num_commits_behind = 96, num_commits_ahead = 0
2021-11-07 14:18:32 DEBUG :: CHECKVERSION :: Executing git config remote.origin.url https://github.com/SickChill/SickChill.git with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:32 DEBUG :: CHECKVERSION :: Executing git reset --hard with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:32 DEBUG :: CHECKVERSION :: git reset --hard : returned successful
2021-11-07 14:18:32 DEBUG :: CHECKVERSION :: Executing git symbolic-ref -q HEAD with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:32 DEBUG :: CHECKVERSION :: git symbolic-ref -q HEAD : returned successful
2021-11-07 14:18:32 DEBUG :: CHECKVERSION :: Executing git pull -f origin master with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:39 DEBUG :: CHECKVERSION :: git pull -f origin master : returned successful
2021-11-07 14:18:39 DEBUG :: CHECKVERSION :: Executing git rev-parse HEAD with your shell in /opt/sickchill/sickchill
2021-11-07 14:18:39 DEBUG :: CHECKVERSION :: git rev-parse HEAD : returned successful
2021-11-07 14:18:42 DEBUG :: CHECKVERSION :: Sending KODI notification to '192.168.178.10' - SickChill Updated To Commit#: 80528da322023b04102f2801d620fd1b8f8d09a7
2021-11-07 14:18:42 DEBUG :: CHECKVERSION :: Notification for Boxcar2 not enabled, skipping this notification
2021-11-07 14:18:42 INFO :: CHECKVERSION :: Update was successful!                   
2021-11-07 14:18:42 DEBUG :: CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
2021-11-07 14:18:42 INFO :: EVENT-QUEUE :: Aborting all threads
2021-11-07 14:18:42 INFO :: EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2021-11-07 14:18:43 INFO :: EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2021-11-07 14:18:43 INFO :: EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2021-11-07 14:18:43 INFO :: EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2021-11-07 14:18:45 INFO :: EVENT-QUEUE :: Waiting for the SHOWQUEUE-REFRESH thread to exit
2021-11-07 14:18:45 INFO :: EVENT-QUEUE :: Waiting for the SEARCHQUEUE-BACKLOG-362250 thread to exit
2021-11-07 14:18:45 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2021-11-07 14:18:45 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR-MANUAL thread to exit
2021-11-07 14:18:45 INFO :: EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2021-11-07 14:18:45 INFO :: EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2021-11-07 14:18:45 INFO :: EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2021-11-07 14:18:45 INFO :: EVENT-QUEUE :: Waiting for the NOTIFICATIONS thread to exit
2021-11-07 14:18:45 INFO :: EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2021-11-07 14:18:45 INFO :: EVENT-QUEUE :: Saving all shows to the database
2021-11-07 14:18:46 INFO :: EVENT-QUEUE :: Saving config file to disk
2021-11-07 14:18:46 INFO :: EVENT-QUEUE :: Shutting down Tornado
2021-11-07 14:18:56 INFO :: EVENT-QUEUE :: Restarting SickChill with ['/opt/sickchill/.venv/bin/python3.7', '/opt/sickchill/SickChill.py', '-q', '--daemon', '--nolaunch', '--datadir=/opt/sickchill']
```

This is the end of the log file including the update that commenced at 2021-11-07 14:18:25. I can provide data from prior to this point but I think it's probably to do with the update. And there's nothing after the restart at 2021-11-07 14:18:56... nothing from today (2021-11-08). 

I am able to access the media centre via ssh and I can view the Chorus web interface for Kodi via http://192.168.178.10:8080/ so I don't see how it's a net connection/VPN/firewall issue.

I haven't made any manual changes to sickchill or the media centre recently (apart from adding media).

I checked to see if there's anyone else reporting a similar issue but the ones about refused connection that I found are from years ago. But... I did see this one from yesterday which I thought might be related:  https://github.com/SickChill/SickChill/issues/7629. And, in case it was related, I tried doing what the commenters said solved it for them.... I tried uninstalling and reinstalling poetry but that didn't appear to help. I also tried removing `/opt/sickchill/.venv` and then running `python SickChill.py` but all I get is this: 

```
Traceback (most recent call last):
  File "SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 1, in <module>
    from sickchill.init_helpers import maybe_daemonize, poetry_install
  File "/opt/sickchill/sickchill/init_helpers.py", line 21
    pid_file: Path = None
            ^
SyntaxError: invalid syntax
```

I don't know what this means. 

Please help.

**Comment by Khondokhan** [comment]
Exactly same issue with me.  Any update so far?

**Comment by bmccully** [comment]
same issue here, straight after updating.....

**Comment by BKSteve** [comment]
You read 7629 did you look at pyproject.toml line 40?
Can't say it's the answer for you but having `callable` in that string cause my dsm to not run SC. 
See #7630 for more too

**Comment by nydave69** [comment]
OK,  I got to this point  err_connection_refused after fixing the registry..

went for coffee (10+mins) tried it again and it now running..

**Comment by damagu** [comment]
> You read 7629 did you look at pyproject.toml line 40? Can't say it's the answer for you but having `callable` in that string cause my dsm to not run SC. See #7630 for more too

Yes. My pyproject.toml line 40 had this:

`SickChill = {reference = "SickChill.py", callable = "SickChill.py", type = "file", extras = ["cli"]}`

... which didn't seem to correspond with what I saw [here ](https://github.com/SickChill/SickChill/pull/7630/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L40-R40):
```
-  SickChill = {callable = "SickChill.py", type = "file", extras = ["cli"]}
+ SickChill = {reference = "SickChill.py", type = "file", extras = ["cli"]}
```
since it includes "refereence" and "callable". I don't know why my line is different from the one that's indicated to be removed or the one that's indicated to be added. I tried replacing my line 40 with the line indicated as to be added but I got the same errors.

**Comment by BKSteve** [comment]
Take a look at #7645 
It comments out both line 39 and 40, and should resolve issues which vary depending on what version of poetry is installed. (poetry 1.2.0a2 or 1.1.11) as 1.1.11 is more recent than the alpha with higher number.
```
-[tool.poetry.scripts]
-SickChill = {reference = "SickChill.py", callable = "SickChill.py", type = "file", extras = ["cli"]}
+# [tool.poetry.scripts]
+# SickChill = {reference = "SickChill.py", type = "file", extras = ["cli"]}
```

**Comment by damagu** [comment]
> Take a look at #7645

Ok. I did that and tried again and I still get the same error. Maybe I'm missing something else...?

**Comment by mediafreakch** [comment]
Same issue here, Sickchill Web Interface not accessible after a fresh install via Synology package center. I stopped Sickchill, commented out the said lines in `pyproject.toml` manually, then started again but Web interface is still inaccessible. 

Logs do not say much even with `debug = True` set in `config.ini`. (`debug = 1` will not start Sickchill)

> Starting sickchill command /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --daemon --nolaunch --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/data/config.ini --datadir /volume1/@appstore/sickchill/var/data 
Writing PID: 11212 to /volume1/@appstore/sickchill/var/sickchill.pid

**Comment by damagu** [comment]
Okay so I just tried: `python3 SickChill.py`... and I got little further along:

```
Checking poetry
Can write to /usr/local/lib/python3.7/dist-packages: False
Can write to /home/osmc/.local/lib/python3.7/site-packages: False
Current environment is not writable!
Source dir is not writable by this user either, we cannot continue: f/opt/sickchill
```
So... I then tried:

```
osmc@vero:/opt/sickchill$ sudo python3 SickChill.py 
Checking poetry
Can write to /root/.local/lib/python3.7/site-packages: False
Can write to /usr/local/lib/python3.7/dist-packages: True
We always run from virtualenv when running from source
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3.7', 'SickChill.py']
Checking poetry
Can write to /opt/sickchill/.venv/lib/python3.7/site-packages: True
Can write to /root/.local/lib/python3.7/site-packages: False
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3.7 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --extra-index-url=https://www.piwheels.org/simple setuptools poetry wheel
Command result: WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)

poetry installed: True
pip args: /opt/sickchill/.venv/bin/python3.7 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --extra-index-url=https://www.piwheels.org/simple appdirs==1.4.4 babelfish==0.6.0; python_version >= "3.6" and python_version < "4.0" backports.zoneinfo==0.2.1; python_version < "3.9" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") beautifulsoup4==4.10.0; python_full_version > "3.0.0" beekeeper-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" bencode.py==4.0.0 cachecontrol==0.12.9; python_version >= "3.6" certifi==2021.10.8; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" cffi==1.15.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" chardet==4.0.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") charset-normalizer==2.0.7; python_full_version >= "3.6.0" and python_version >= "3.6" click==8.0.3; python_version >= "3.6" cloudscraper==1.2.58 colorama==0.4.4; python_version >= "3.6" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.6" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==35.0.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" decorator==5.1.0; python_version >= "3.6" deluge-client==1.9.0 deprecated==1.2.13; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.4; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.8; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.2; python_version >= "3" and python_full_version < "3.0.0" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") or python_version >= "3" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") and python_full_version >= "3.5.0" guessit==3.4.0 html5lib==1.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.20.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") idna==3.3; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" ifaddr==0.1.7 imagesize==1.2.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2021.4.18 importlib-metadata==4.8.1; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6") importlib-resources==5.4.0; python_version < "3.7" and python_version >= "3.6" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.3.1 kodipydent-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" lxml==4.6.3; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.1.5; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") markdown2==2.4.1; python_version >= "3.5" and python_version < "4" markupsafe==2.0.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" msgpack==1.0.2; python_version >= "3.6" new-rtorrent-python==1.0.1a0 oauthlib==3.1.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==21.2; python_version >= "3.6" pbr==5.6.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.20; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.3.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >= "3.6" pynacl==1.4.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pynma==1.0 pyopenssl==21.0.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") pyparsing==2.4.7; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pysocks==1.7.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==5.0.2; python_version >= "3.6" python-twitter==3.5 python3-fanart==2.0.0 pytz-deprecation-shim==0.1.0.post0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" pytz==2021.3 qbittorrent-api==2021.8.23 rarfile==4.0 rebulk==3.1.0 requests-oauthlib==1.3.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests-toolbelt==0.9.1 requests==2.26.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") send2trash==1.8.0 sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" soupsieve==2.2.1; python_version >= "3.6" and python_full_version > "3.0.0" sqlalchemy==1.4.26; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.5.0; python_version >= "3.6" subliminal==2.1.0 text-unidecode==1.3; python_version >= "3.6" timeago==1.0.15 tmdbsimple==2.8.0 tornado==6.1; python_version >= "3.5" tus.py==1.3.4 tvdbsimple==1.0.6 typing-extensions==3.10.0.2; python_version < "3.8" and python_version >= "3.6" tzdata==2021.5; platform_system == "Windows" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") tzlocal==4.1; python_version >= "3.6" unidecode==1.3.2; python_version >= "3.5" urllib3==1.26.7; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version < "4" and python_version >= "3.6" validators==0.18.2; python_version >= "3.4" webencodings==0.5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.1.0 wrapt==1.13.3; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" xmltodict==0.12.0; python_full_version >= "3.6.2" and python_version < "4" zipp==3.6.0; python_version < "3.8" and python_version >= "3.6" 
Command result: WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -etuptools (/opt/sickchill/.venv/lib/python3.7/site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.11 requires importlib-metadata<2.0.0,>=1.6.0; python_version < "3.8", but you have importlib-metadata 4.8.1 which is incompatible.
poetry 1.1.11 requires packaging<21.0,>=20.4, but you have packaging 21.2 which is incompatible.
poetry-date-version-plugin 2021.7.16.post6 requires cleo<2.0.0,>=1.0.0a1, but you have cleo 0.8.1 which is incompatible.
poetry-date-version-plugin 2021.7.16.post6 requires poetry>=1.2.0a0, but you have poetry 1.1.11 which is incompatible.
poetry-core 1.0.7 requires importlib-metadata<2.0.0,>=1.7.0; python_version >= "2.7" and python_version < "2.8" or python_version >= "3.5" and python_version < "3.8", but you have importlib-metadata 4.8.1 which is incompatible.
```
... followed by a whole bunch of `DEBUG :: MAIN ::` stuff relating to different shows and then this:

```
2021-11-09 17:52:31 DEBUG :: CHECKVERSION :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2021-11-09 17:52:31 DEBUG :: CHECKVERSION :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /opt/sickchill/sickchill
2021-11-09 17:52:31 DEBUG :: CHECKVERSION :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2021-11-09 17:52:31 DEBUG :: CHECKVERSION :: cur_commit = 45567ca2301751b09a690672a640e28df60d931d, newest_commit = 45567ca2301751b09a690672a640e28df60d931d, num_commits_behind = 0, num_commits_ahead = 0
2021-11-09 17:52:31 DEBUG :: CHECKVERSION :: check_for_new_news: Checking GitHub for latest news.
```

And... then when I reloaded the GUI again and it was running.

This python version/depency stuff has caused issues for me before. It seems like there's something screwy going on with the different versions on my system and I don't know how to resolve it.

**Comment by miigotu** [comment]
> > You read 7629 did you look at pyproject.toml line 40? Can't say it's the answer for you but having `callable` in that string cause my dsm to not run SC. See #7630 for more too
> 
> Yes I did look at that file. But I wasn't sure what to do since my version of the file has this on line 40:
> 
> `SickChill = {reference = "SickChill.py", callable = "SickChill.py", type = "file", extras = ["cli"]}`
> 
> ... whereas the diff which is shown [here ](https://github.com/SickChill/SickChill/pull/7630/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L40-R40):
> 
> ```
> - SickChill = {callable = "SickChill.py", type = "file", extras = ["cli"]}
> + SickChill = {reference = "SickChill.py", type = "file", extras = ["cli"]}
> ```
> 
> ...shows a line which is different from mine because mine includes "reference" and "callable".
> 
> Despite that, I still tried replacing my line 40 with the line indicated as to be added but I got the same error when I did this:
> 
> ```
> osmc@vero:/opt/sickchill$ python SickChill.py 
> Traceback (most recent call last):
>  File "SickChill.py", line 14, in <module>
>    import sickchill.start
>  File "/opt/sickchill/sickchill/__init__.py", line 1, in <module>
>    from sickchill.init_helpers import maybe_daemonize, poetry_install
>  File "/opt/sickchill/sickchill/init_helpers.py", line 21
>    pid_file: Path = None
>            ^
> SyntaxError: invalid syntax
> ```

You have to start SC with python3, not python2
