### ISSUE TITLE
[APP SUBMITTED]: datetime.date(1876, 9, 18) is not JSON serializable

### ISSUE THREAD

**Issue by wetworkM** [SickChill/SickChill#7663]
### INFO
Python Version: **2.7.15 (default, Oct 13 2018, 13:29:10) [GCC 4.9.2]**
Operating System: **Linux-5.10.60-qnap-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f5717bf3aa72c85395dc38d3cadf16a43d1fbfda
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_1 :: [f5717bf] Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/webserve.py", line 2570, in searchIndexersForShowName
    return json.dumps({'results': final_results, 'langid': lang_id, 'success': len(final_results) > 0})
  File "/opt/SickChill/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/opt/SickChill/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/SickChill/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/opt/SickChill/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.date(1876, 9, 18) is not JSON serializable

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by wetworkM** [comment]
### INFO
Python Version: **2.7.15 (default, Oct 13 2018, 13:29:10) [GCC 4.9.2]**
Operating System: **Linux-5.10.60-qnap-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickChill/SickChill@f5717bf3aa72c85395dc38d3cadf16a43d1fbfda
No Log available with ERRORS:
### ERROR
```
ThreadPoolExecutor-0_0 :: [f5717bf] Failed doing webui callback: Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/webserve.py", line 288, in async_call
    result = function(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/QSickChill/SickChill/sickbeard/webserve.py", line 2570, in searchIndexersForShowName
    return json.dumps({'results': final_results, 'langid': lang_id, 'success': len(final_results) > 0})
  File "/opt/SickChill/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/opt/SickChill/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/SickChill/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/opt/SickChill/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.date(1876, 9, 18) is not JSON serializable

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
That old package is never going to work. Sickchill only works with python 3.6+
