### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'"

### ISSUE THREAD

**Issue by ouija** [SickChill/SickChill#7750]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: QNAP
Browser:
What you did:  Update Entware / Python3
What happened: SickChill broke due to Python 3.10 update and MutableMapping name change
What you expected: For it to work
Logs:
```
start daemon: failed!
= ExecuteAndLog()
output: "/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/sickchill/locale
/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/sickchill/locale
Traceback (most recent call last):
  File "/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/sickchill/__init__.py", line 1, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/sickchill/tv.py", line 33, in <module>
    from sickchill.oldbeard import db, helpers, network_timezones, notifiers, postProcessor, subtitles
  File "/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/sickchill/oldbeard/postProcessor.py", line 9, in <module>
    import sickchill.oldbeard.subtitles
  File "/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/sickchill/oldbeard/subtitles.py", line 8, in <module>
    import subliminal
  File "/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/lib3/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/lib3/subliminal/core.py", line 11, in <module>
    from babelfish import Language, LanguageReverseError
  File "/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/lib3/babelfish/__init__.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/share/CACHEDEV3_DATA/.qpkg/SickChill/SickChill/lib3/babelfish/converters/__init__.py", line 11, in <module>
    class CaseInsensitiveDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'"
result: [1]
```

There appears to be an issue using SickChill with Python 3.10.0 and [collections.MutableMapping being renamed to collections.abc.MutableMapping](https://stackoverflow.com/questions/69512672/getting-attributeerror-module-collections-has-no-attribute-mutablemapping-w)

[Updating babelfish](https://github.com/Diaoul/babelfish) will [resolve this issue](https://github.com/clinton-hall/nzbToMedia/issues/1866#issuecomment-985319891) with `collections.MutableMapping ` 

...although further inspect reveals that this is **indeed** updated in the lasted master repo [as of last month](https://github.com/SickChill/SickChill/blob/01020f3636d01535f60b83464d8127ea0efabfc7/poetry.lock#L44).

Apparently my local installation isn't pulling the latest changes for some odd reason...

**Comment by ouija** [comment]
**UPDATE:**   Figured out the cause, the QPKG _(QNAP Package)_ I am using is actually the cause of this issue, due to it reverting back to an older commit.

Consider this resolved, and apologies for the confusion!
