### ISSUE TITLE
Webserver uncaught exception

### ISSUE THREAD

**Issue by hshachor** [SickChill/SickChill#7838]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: 2021.11.10
OS: Raspbian GNU/Linux 11 (bullseye)
Browser: Firefox 96.0.3 (64-bit)
What you did: try to access sickchill web page
What happened: error 500
What you expected: see sickchill web page
Logs:
```
2022-02-01 21:37:40 ERROR :: WEBSERVER :: Uncaught exception GET / (192.168.0.106)
HTTPServerRequest(protocol='http', host='192.168.0.108:8081', method='GET', uri='/', version='HTTP/1.1', remote_ip='192.168.0.106')
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/pi/.local/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/pi/.local/lib/python3.9/site-packages/sickchill/views/index.py", line 164, in get
    results = yield self.async_call(method)
  File "/home/pi/.local/lib/python3.9/site-packages/tornado/concurrent.py", line 122, in wrapper
    conc_future = getattr(self, executor).submit(fn, self, *args, **kwargs)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 163, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

**Comment by BKSteve** [comment]
the final line `RuntimeError: cannot schedule new futures after interpreter shutdown` indicates there's a problem.
A search for this gives a number of issues including one with Python 3.9.
What did you change recently if anything?
Does a full device restart resolve it?

**Comment by hshachor** [comment]
Currently problem is solved on my side - 
I search the log to see when it started (few days ago) in order to see which changes to search in apt log. I found in log that cache.db is malformed. 
After deleting the cache, web server is running.

However, in the past, I knew about problems in cache.db from web-log, not from uncaught exception.
