### ISSUE TITLE
Can't access web interface ERR_CONNECTION_REFUSED ... again.

### ISSUE THREAD

**Issue by damagu** [SickChill/SickChill#7860]
After trying to restart sickchill today, I started getting the same message from the web interface as I got back in November when I raised issue [#7365](https://github.com/SickChill/SickChill/issues/7635).

I tried repeating some of the steps from the last time this occurred... I stopped sickchill and then tried updating it using:

```
osmc@vero:/opt/sickchill$ sudo git fetch origin
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 12 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (12/12), done.
From https://github.com/SickChill/SickChill
 * [new branch]          dependabot/npm_and_yarn/develop/eslint-8.9.0 -> origin/dependabot/npm_and_yarn/develop/eslint-8.9.0
 * [new branch]          dependabot/npm_and_yarn/develop/snyk-1.852.0 -> origin/dependabot/npm_and_yarn/develop/snyk-1.852.0
 * [new branch]          dependabot/pip/develop/pytest-7.0.1          -> origin/dependabot/pip/develop/pytest-7.0.1

osmc@vero:/opt/sickchill$ sudo git reset --hard origin/master
HEAD is now at 01020f363 Merge branch 'develop'

osmc@vero:/opt/sickchill$ sudo git pull
Already up to date.
Current branch master is up to date.

``` 

But when I restarted I was still getting the connection refused message.
I checked line 40 of the pyproject.toml file to make sure it didn't contain "callable". It appears to have changed since last time because it now contains this at line 40:

`SickChill = "SickChill:main"`

Then I tried removing /opt/sickchill/.venv and running `python3 SickChill.py` which gives me different output from last time:

```
osmc@vero:/opt/sickchill$ sudo python3 SickChill.py 
Checking poetry
Can write to /usr/local/lib/python3.7/dist-packages: True
Can write to /root/.local/lib/python3.7/site-packages: False
We always run from virtualenv when running from source
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3', 'SickChill.py']
Checking poetry
Can write to /opt/sickchill/.venv/lib/python3.7/site-packages: True
Can write to /root/.local/lib/python3.7/site-packages: False
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --extra-index-url=https://www.piwheels.org/simple setuptools poetry wheel
poetry installed: True
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/poetry/__main__.py", line 5, in <module>
    from .console import main
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/poetry/factory.py", line 18, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/poetry/repositories/pypi_repository.py", line 33, in <module>
    from ..inspection.info import PackageInfo
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/poetry/inspection/info.py", line 25, in <module>
    from poetry.utils.env import EnvCommandError
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/poetry/utils/env.py", line 23, in <module>
    import virtualenv
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/virtualenv/run/__init__.py", line 14, in <module>
    from .plugin.creators import CreatorSelector
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/virtualenv/run/plugin/creators.py", line 6, in <module>
    from virtualenv.create.via_global_ref.builtin.builtin_way import VirtualenvBuiltin
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/virtualenv/create/via_global_ref/builtin/builtin_way.py", line 7, in <module>
    from virtualenv.create.creator import Creator
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/virtualenv/create/creator.py", line 15, in <module>
    from virtualenv.discovery.cached_py_info import LogCmd
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/virtualenv/discovery/cached_py_info.py", line 23, in <module>
    _CACHE[Path(sys.executable)] = PythonInfo()
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/virtualenv/discovery/py_info.py", line 86, in __init__
    self.distutils_install = {u(k): u(v) for k, v in self._distutils_install().items()}
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/virtualenv/discovery/py_info.py", line 152, in _distutils_install
    d = dist.Distribution({"script_args": "--no-user-cfg"})  # conf files not parsed so they do not hijack paths
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/setuptools/dist.py", line 456, in __init__
    for ep in metadata.entry_points(group='distutils.setup_keywords'):
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 1003, in entry_points
    return SelectableGroups.load(eps).select(**params)
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 453, in load
    ordered = sorted(eps, key=by_group)
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 1001, in <genexpr>
    dist.entry_points for dist in unique(distributions())
  File "/opt/sickchill/.venv/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/_itertools.py", line 16, in unique_everseen
    k = key(element)
AttributeError: 'PathDistribution' object has no attribute '_normalized_name'
Unable to install to the existing virtual environment located at /opt/sickchill/.venv
Please check the permissions, and that it does not include global site packages
```
What permissions do I need to check? I haven't had to deal with permissions with sickchill before. Is it something to do with the fact that the .venv which was created is root:root while everything else in the directory is sickchill:sickchill. Should it also have the owner:group sickchill:sickchill?

Can I get some help trying to fix this?

**Comment by BKSteve** [comment]
I'd try as you suggested. Ownership could be the issue. 
Setuptools updated and was also kicking other errors but that's not what you were getting in the log. See #7757 where I was working on something to clear extra errors so it would load.
If you want to try that edit curl the raw file.

**Comment by damagu** [comment]
> I'd try as you suggested. Ownership could be the issue.

Ok. well I tried changing the owner of .venv to sickchill:sickchill and then I ran it again and got this:

```
osmc@vero:/opt/sickchill$ sudo python3 SickChill.py
Checking poetry
Can write to /usr/local/lib/python3.7/dist-packages: True
Can write to /root/.local/lib/python3.7/site-packages: False
We always run from virtualenv when running from source
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3', 'SickChill.py']
Checking poetry
Can write to /root/.local/lib/python3.7/site-packages: False
Can write to /opt/sickchill/.venv/lib/python3.7/site-packages: True
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --extra-index-url=https://www.piwheels.org/simple setuptools poetry wheel
Command result: WARNING: Ignoring invalid distribution -mportlib-metadata (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (/opt/sickchill/.venv/lib/python3.7/site-packages)

poetry installed: True
pip args: /opt/sickchill/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --extra-index-url=https://www.piwheels.org/simple appdirs==1.4.4 babelfish==0.6.0; python_version >= "3.6" and python_version < "4.0" backports.zoneinfo==0.2.1; python_version < "3.9" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") beautifulsoup4==4.10.0; python_full_version > "3.0.0" beekeeper-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" bencode.py==4.0.0 cachecontrol==0.12.10; python_version >= "3.6" certifi==2021.10.8; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" cffi==1.15.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" chardet==4.0.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") charset-normalizer==2.0.7; python_full_version >= "3.6.0" and python_version >= "3.6" click==8.0.3; python_version >= "3.6" cloudscraper==1.2.58 colorama==0.4.4; python_version >= "3.6" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.6" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==35.0.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" decorator==5.1.0; python_version >= "3.6" deluge-client==1.9.0 deprecated==1.2.13; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.4; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.8; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.2; python_version >= "3" and python_full_version < "3.0.0" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") or python_version >= "3" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") and python_full_version >= "3.5.0" guessit==3.4.2 html5lib==1.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.20.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") idna==3.3; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" ifaddr==0.1.7 imagesize==1.3.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2021.4.18 importlib-metadata==4.8.2; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6") importlib-resources==5.4.0; python_version >= "3.6" and python_version < "3.7" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.3.1 kodipydent-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" lxml==4.6.4; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.1.5; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") markdown2==2.4.1; python_version >= "3.5" and python_version < "4" markupsafe==2.0.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" msgpack==1.0.2; python_version >= "3.6" new-rtorrent-python==1.0.1a0 oauthlib==3.1.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==21.2; python_version >= "3.6" pbr==5.7.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.21; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.3.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >= "3.6" pynacl==1.4.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pynma==1.0 pyopenssl==21.0.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") pyparsing==2.4.7; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pysocks==1.7.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==5.0.2; python_version >= "3.6" python-twitter==3.5 python3-fanart==2.0.0 pytz-deprecation-shim==0.1.0.post0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" pytz==2021.3 qbittorrent-api==2021.8.23 rarfile==4.0 rebulk==3.1.0 requests-oauthlib==1.3.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests-toolbelt==0.9.1 requests==2.26.0; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") send2trash==1.8.0 sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" soupsieve==2.3; python_version >= "3.6" and python_full_version > "3.0.0" sqlalchemy==1.4.26; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.5.0; python_version >= "3.6" subliminal==2.1.0 text-unidecode==1.3; python_version >= "3.6" timeago==1.0.15 tmdbsimple==2.8.0 tornado==6.1; python_version >= "3.5" tus.py==1.3.4 tvdbsimple==1.0.6 typing-extensions==3.10.0.2; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6") tzdata==2021.5; platform_system == "Windows" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") tzlocal==4.1; python_version >= "3.6" unidecode==1.3.2; python_version >= "3.5" urllib3==1.26.7; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version < "4" and python_version >= "3.6" validators==0.18.2; python_version >= "3.4" webencodings==0.5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.1.0 wrapt==1.13.3; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" xmltodict==0.12.0; python_full_version >= "3.6.2" and python_version < "4" zipp==3.6.0; python_version < "3.8" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.6")
Command result: WARNING: Ignoring invalid distribution -mportlib-metadata (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -mportlib-metadata (/opt/sickchill/.venv/lib/python3.7/site-packages)
    WARNING: Ignoring invalid distribution -mportlib-metadata (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (/opt/sickchill/.venv/lib/python3.7/site-packages)
WARNING: Ignoring invalid distribution -mportlib-metadata (/opt/sickchill/.venv/lib/python3.7/site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.13 requires importlib-metadata<2.0.0,>=1.6.0; python_version < "3.8", but you have importlib-metadata 4.8.2 which is incompatible.
poetry 1.1.13 requires packaging<21.0,>=20.4, but you have packaging 21.2 which is incompatible.
poetry-core 1.0.7 requires importlib-metadata<2.0.0,>=1.7.0; python_version >= "2.7" and python_version < "2.8" or python_version >= "3.5" and python_version < "3.8", but you have importlib-metadata 4.8.2 which is incompatible.

2022-02-15 21:40:56 DEBUG :: MAIN :: ... [etc, etc] 
```

At which point, despite the warnings and the error, it appeared to be running. I checked the web interface and it was working.

I shut it down and tried to start the sickchill service and the web interface eventually loaded up again.

So... once again I've got it "fixed" (or at least working) without really understanding why it stopped working or how exactly I got it going again. 

> Setuptools updated and was also kicking other errors but that's not what you were getting in the log. See https://github.com/SickChill/SickChill/pull/7757 where I was working on something to clear extra errors by the poetry call so it would load.
> If you want to try that edit, then curl the raw file.

Umm... I don't really know. That's a bit above my current level of (in)expertise. And, now that it's working again I'm not sure I can be bothered trying it. 

I won't be surprised if I run into this problem again in a month or 3. Fingers crossed I'm wrong though. :)

**Comment by BKSteve** [comment]
Your log at the end also points out that the installed `importlib-metadata` is the latest `4.8.2`  but your `python` being `3.7` is lower than recommended for the version of `importlib-metadata`
But your working and it shouldn't be  problem.

You may wish to consider updating to Python 3.8 but if you do shutdown SC and remove the `.venv` folder then update Python and restart SC then it will create `/opt/sickchill/.venv/lib/python3.8/site-packages` and the `importlib-metadata` error should be gone.

**Comment by miigotu** [comment]
Could you check the output of `python3.7 -m poetry --version`?
