### ISSUE TITLE
[APP SUBMITTED]: 'list' object has no attribute 'id'

### ISSUE THREAD

**Issue by angeloschat** [SickChill/SickChill#7902]
### INFO
Python Version: **3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]**
Operating System: **Linux-4.4.249-1.el7.elrepo.x86_64-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@99336df163c7e776c7931d864e84d1f0f83afe4d
No Log available with ERRORS:
### ERROR
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sickchill/views/manage/add_shows.py", line 361, in favoriteShows
    favorite_shows = favorites.fetch_indexer_favorites()
  File "/usr/lib/python3.9/site-packages/sickchill/show/recommendations/favorites.py", line 20, in fetch_indexer_favorites
    if Show().find(settings.showList, series.id):
AttributeError: 'list' object has no attribute 'id'

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Maybe don't submit issues on a modified version that's 2 years old.
