### ISSUE TITLE
Sickchill not working after update 

### ISSUE THREAD

**Issue by vbigchris** [SickChill/SickChill#8031]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Ubuntu 20.04.4 LTS
Browser: 
What you did: Preformed ubuntu updates 
What happened: Sickchill stopped working 
What you expected:
Logs:

 sudo service sickchill status
● sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Fri 2022-07-22 14:24:11 UTC; 17min ago
    Process: 814 ExecStart=/usr/bin/python3.8 /opt/sickchill/SickChill.py -q --daemon --nolaunch --datadir=/opt/sickchill (code=exited, status=0/SUCCESS)
```
PASTE LOGS HERE

 /usr/bin/python3.9 /opt/sickchill/SickChill.py --datadir /opt/sickchill/
Checking poetry
Can write to /usr/local/lib/python3.9/dist-packages: False
Can write to /home/nzbuser/.local/lib/python3.9/site-packages: False
Current environment is not writable!
Restarting SickChill with ['/opt/sickchill/.venv/bin/python3.8', '/opt/sickchill/SickChill.py', '--datadir', '/opt/                                                                           sickchill/']
Checking poetry
Can write to /home/nzbuser/.local/lib/python3.8/site-packages: False
Can write to /opt/sickchill/.venv/lib/python3.8/site-packages: True
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3.8 -m pip install --no-input --disable-pip-version-check --no-python-vers                                                                           ion-warning --no-color -qU --find-links=https://wheel-index.linuxserver.io/ubuntu/ setuptools poetry wheel
poetry installed: True
Poetry installed packages checker started
Poetry installed packages checker completed
pip args: /opt/sickchill/.venv/bin/python3.8 -m pip install --no-input --disable-pip-version-check --no-python-vers                                                                           ion-warning --no-color -qU --find-links=https://wheel-index.linuxserver.io/ubuntu/ appdirs==1.4.4 babelfish==0.6.0;                                                                            python_version >= "3.6" and python_version < "4.0" backports.zoneinfo==0.2.1; python_version < "3.9" and python_ve                                                                           rsion >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and                                                                            python_version >= "3.6") beautifulsoup4==4.11.1; python_full_version >= "3.6.0" beekeeper-alt==2021.7.16; python_f                                                                           ull_version >= "3.6.2" and python_version < "4" bencode.py==4.0.0 cachecontrol==0.12.11; python_version >= "3.6" ce                                                                           rtifi==2022.6.15; python_version >= "3.7" and python_version < "4" cffi==1.15.1; python_version >= "3.6" chardet==5                                                                           .0.0; python_version >= "3.6" charset-normalizer==2.1.0; python_version >= "3.7" and python_version < "4" and pytho                                                                           n_full_version >= "3.6.0" cinemagoer==2022.2.11 click==8.1.3; python_version >= "3.7" colorama==0.4.5; python_versi                                                                           on >= "3.7" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and                                                                            python_version >= "3.7" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==37.0.4; python_version >=                                                                            "3.6" decorator==5.1.1; python_version >= "3.6" deluge-client==1.9.0 deprecated==1.2.13; python_version >= "3.6" a                                                                           nd python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.8                                                                           ; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.10; python_version >= "3.6" future==0.18.2; python_version                                                                            >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.2; python_ve                                                                           rsion >= "3" and python_full_version < "3.0.0" and (platform_machine == "aarch64" or platform_machine == "ppc64le"                                                                            or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine =                                                                           = "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_                                                                           full_version >= "3.6.0") or python_version >= "3" and (platform_machine == "aarch64" or platform_machine == "ppc64l                                                                           e" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machin                                                                           e == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or pyth                                                                           on_full_version >= "3.6.0") and python_full_version >= "3.5.0" guessit==3.4.3 html5lib==1.1; (python_version >= "2.                                                                           7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.20.4; (python_version >= "2.7                                                                           " and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") idna==3.3; python_version >= "3.7" and pyt                                                                           hon_version < "4" ifaddr==0.2.0 imagesize==1.4.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (p                                                                           ython_full_version >= "3.4.0") imdbpy==2022.7.9 importlib-metadata==4.12.0; python_version < "3.8" and python_versi                                                                           on >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_ful                                                                           l_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7") importlib-resources==5.8.0; python_ver                                                                           sion >= "3.7" and python_version < "3.9" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.3.2 kodipydent-alt==20                                                                           21.7.16; python_full_version >= "3.6.2" and python_version < "4" lxml==4.9.1; python_version >= "2.7" and python_fu                                                                           ll_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.2.1; python_version >= "3.7" markdown2==2.4.3; pytho                                                                           n_version >= "3.5" and python_version < "4" markupsafe==2.1.1; python_version >= "3.7" msgpack==1.0.4; python_versi                                                                           on >= "3.6" new-rtorrent-python==1.0.1a0 oauthlib==3.2.0; python_version >= "3.6" and python_full_version < "3.0.0"                                                                            or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==21.3; python_version >= "3.6" pbr==5.9.0;                                                                            python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.21; python_version >= "3.6"                                                                            and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pygithub==1.55; py                                                                           thon_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.4.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >=                                                                            "3.6" pynacl==1.5.0; python_version >= "3.6" pynma==1.0 pyopenssl==22.0.0; python_version >= "3.6" pyparsing==3.0.                                                                           9; python_full_version >= "3.6.8" and python_version >= "3.6" pysocks==1.7.1; (python_version >= "2.7" and python_f                                                                           ull_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.2; (python_version >=                                                                            "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==6.1.2; (python_version                                                                            >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") python-twitter==3.5 python3-fanart                                                                           ==2.0.0 pytz-deprecation-shim==0.1.0.post0; python_version >= "3.6" and python_full_version < "3.0.0" or python_ful                                                                           l_version >= "3.6.0" and python_version >= "3.6" pytz==2022.1 qbittorrent-api==2022.5.32 rarfile==4.0 rebulk==3.1.0                                                                            requests-oauthlib==1.3.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4                                                                           .0" requests==2.28.1; python_version >= "3.7" and python_version < "4" send2trash==1.8.0 sgmllib3k==1.0.0; python_v                                                                           ersion >= "3.6" six==1.16.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3                                                                           .5.0" soupsieve==2.3.2.post1; python_version >= "3.6" and python_full_version >= "3.6.0" sqlalchemy==1.4.39; (pytho                                                                           n_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.5.0; python_                                                                           version >= "3.6" subliminal==2.1.0 text-unidecode==1.3; python_version >= "2.7" and python_full_version < "3.0.0" o                                                                           r python_full_version >= "3.6.0" timeago==1.0.15 tmdbsimple==2.9.1 tornado==6.2; python_version >= "3.7" tus.py==1.                                                                           3.4 tvdbsimple==1.0.6 typing-extensions==4.3.0; python_version < "3.8" and python_version >= "3.7" and (python_vers                                                                           ion >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and pyt                                                                           hon_version < "3.8" and python_version >= "3.7") tzdata==2022.1; platform_system == "Windows" and python_version >=                                                                            "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_                                                                           version >= "3.6") tzlocal==4.2; python_version >= "3.6" unidecode==1.3.4; python_version >= "3.5" urllib3==1.26.10;                                                                            python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "4" or python_full_version >= "3.6.                                                                           0" and python_version < "4" and python_version >= "3.7" validators==0.20.0; python_version >= "3.4" webencodings==0                                                                           .5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.                                                                           1.0 wrapt==1.14.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and                                                                            python_version >= "3.6" xmltodict==0.13.0; python_full_version >= "3.6.2" and python_version < "4" and python_versi                                                                           on >= "3.4" zipp==3.8.1; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python                                                                           _full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and                                                                            python_version >= "3.7")
Command result: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.14 requires packaging<21.0,>=20.4, but you have packaging 21.3 which is incompatible.

Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/opt/sickchill/sickchill/tv.py", line 14, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'

```

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/discussions/8020
https://github.com/SickChill/SickChill/discussions/8027

This is fixed if you do a git pull or do one of the fixes in those discussions.
