### ISSUE TITLE
Latest image (11e506a54eb1) broke SickChill docker container

### ISSUE THREAD

**Issue by dfranken** [SickChill/SickChill#8033]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: ghcr.io/linuxserver/sickchill:latest image (11e506a54eb1) 
OS: Docker
Browser:
What you did: Watchtower informed me yesterday that there was a new image found for SickChill and updated it. After this, Sickchill won't start anymore
What happened: Watchtower updated to the latest image.
What you expected:
Logs:
```
PASTE LOGS HERE
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
**** The folders '/config/custom-cont-init.d' or '/config/custom-services.d'; or some of their contents have write permissions for others, which is a security risk. ****
**** Please review the permissions of these two folders and their contents to make sure they are owned by root, and can only be modified by root. ****
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
SickChill: https://www.patreon.com/SickChill
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1035
User gid:    100
-------------------------------------
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/30-config
Setting permissions
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] no custom files found exiting...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun sickchill (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
Checking poetry
sickchill installed: True
/usr/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.7) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/SickChill", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 345, in main
    SickChill().start()
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 90, in start
   File "/usr/lib/python3.9/site-packages/SickChill.py", line 90, in start
    settings.DATA_DIR = choose_data_dir(settings.PROG_DIR)
  File "/usr/lib/python3.9/site-packages/sickchill/helper/common.py", line 404, in choose_data_dir
    if location.joinpath(check).exists():
  File "/usr/lib/python3.9/pathlib.py", line 1424, in exists
    self.stat()
  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/sickchill/sickbeard.db'
Checking poetry
sickchill installed: True
/usr/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.7) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/SickChill", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 345, in main
    SickChill().start()
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 90, in start
    settings.DATA_DIR = choose_data_dir(settings.PROG_DIR)
  File "/usr/lib/python3.9/site-packages/sickchill/helper/common.py", line 404, in choose_data_dir
    if location.joinpath(check).exists():
  File "/usr/lib/python3.9/pathlib.py", line 1424, in exists
    self.stat()
  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/sickchill/sickbeard.db'
Checking poetry
sickchill installed: True
/usr/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.7) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/SickChill", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 345, in main
    SickChill().start()
	File "/usr/lib/python3.9/site-packages/SickChill.py", line 90, in start
    settings.DATA_DIR = choose_data_dir(settings.PROG_DIR)
  File "/usr/lib/python3.9/site-packages/sickchill/helper/common.py", line 404, in choose_data_dir
    if location.joinpath(check).exists():
  File "/usr/lib/python3.9/pathlib.py", line 1424, in exists
    self.stat()
  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/sickchill/sickbeard.db'
Checking poetry
sickchill installed: True
/usr/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.7) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/SickChill", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 345, in main
    SickChill().start()
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 90, in start
    settings.DATA_DIR = choose_data_dir(settings.PROG_DIR)
  File "/usr/lib/python3.9/site-packages/sickchill/helper/common.py", line 404, in choose_data_dir
    if location.joinpath(check).exists():
  File "/usr/lib/python3.9/pathlib.py", line 1424, in exists
  self.stat()
  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/sickchill/sickbeard.db'
Checking poetry
sickchill installed: True
/usr/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.7) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/SickChill", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 345, in main
    SickChill().start()
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 90, in start
    settings.DATA_DIR = choose_data_dir(settings.PROG_DIR)
  File "/usr/lib/python3.9/site-packages/sickchill/helper/common.py", line 404, in choose_data_dir
    if location.joinpath(check).exists():
  File "/usr/lib/python3.9/pathlib.py", line 1424, in exists
    self.stat()
  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/sickchill/sickbeard.db'
Checking poetry
sickchill installed: True
/usr/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.7) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/SickChill", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 345, in main
    SickChill().start()
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 90, in start
    settings.DATA_DIR = choose_data_dir(settings.PROG_DIR)
  File "/usr/lib/python3.9/site-packages/sickchill/helper/common.py", line 404, in choose_data_dir
    if location.joinpath(check).exists():
  File "/usr/lib/python3.9/pathlib.py", line 1424, in exists
    self.stat()
  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/sickchill/sickbeard.db'
Checking poetry
sickchill installed: True
/usr/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.7) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/SickChill", line 8, in <module>
    sys.exit(main())
	File "/usr/lib/python3.9/site-packages/SickChill.py", line 345, in main
    SickChill().start()
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 90, in start
    settings.DATA_DIR = choose_data_dir(settings.PROG_DIR)
  File "/usr/lib/python3.9/site-packages/sickchill/helper/common.py", line 404, in choose_data_dir
    if location.joinpath(check).exists():
  File "/usr/lib/python3.9/pathlib.py", line 1424, in exists
    self.stat()
  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/sickchill/sickbeard.db'
Checking poetry
sickchill installed: True
/usr/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.7) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/usr/bin/SickChill", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 345, in main
    SickChill().start()
  File "/usr/lib/python3.9/site-packages/SickChill.py", line 90, in start
    settings.DATA_DIR = choose_data_dir(settings.PROG_DIR)
  File "/usr/lib/python3.9/site-packages/sickchill/helper/common.py", line 404, in choose_data_dir
    if location.joinpath(check).exists():
  File "/usr/lib/python3.9/pathlib.py", line 1424, in exists
    self.stat()
  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/sickchill/sickbeard.db'
Checking poetry
sickchill installed: True
/usr/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.7) or chardet (5.0.0)/charset_normalizer (2.0.7) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "

**Comment by miigotu** [comment]
Sorry but we have our own docker container and we can't provide support for linuxserver containers.

**Comment by miigotu** [comment]
`PermissionError: [Errno 13] Permission denied: '/root/sickchill/sickbeard.db'`
