### ISSUE TITLE
Sickchill not working after update

### ISSUE THREAD

**Issue by promising1** [SickChill/SickChill#8037]
Branch/Commit: latest 
OS: Debian (raspberry pi)
Browser: Chrome
What you did: update
What happened: no longer starts and throws a Poetry GitHub package exception (see logs below) 
What you expected: to work

The application was working perfectly before the update.

Logs:
```
Get:1 http://archive.raspberrypi.org/debian bullseye InRelease [23.7 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages [13.2 MB]
Get:4 http://archive.raspberrypi.org/debian bullseye/main armhf Packages [295 kB]
Get:5 http://raspbian.raspberrypi.org/raspbian bullseye/non-free armhf Packages [106 kB]
Fetched 13.7 MB in 16s (839 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
81 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  base-files bash cups-pk-helper distro-info-data dpkg dpkg-dev ffmpeg firmware-atheros firmware-brcm80211 firmware-libertas firmware-misc-nonfree
  firmware-realtek gir1.2-gtk-3.0 gtk-update-icon-cache libavcodec58 libavdevice58 libavfilter7 libavformat58 libavresample4 libavutil56 libc-bin
  libc-dev-bin libc-devtools libc-l10n libc6 libc6-dbg libc6-dev libcamera-apps libcamera-tools libcamera0 libdpkg-perl libfreetype-dev libfreetype6
  libfreetype6-dev libfribidi0 libgnutls30 libgtk-3-0 libgtk-3-common libmutter-7-0 libnm0 libpostproc55 libpulse-mainloop-glib0 libpulse0 libpulsedsp
  libsdl2-2.0-0 libsmbclient libswresample3 libswscale5 libwbclient0 locales logrotate lxinput lxpanel lxpanel-data lxplug-bluetooth lxplug-cputemp
  lxplug-ejecter lxplug-magnifier lxplug-ptbatt lxplug-updater mutter mutter-common nano openssh-client openssh-server openssh-sftp-server pulseaudio
  pulseaudio-module-bluetooth pulseaudio-utils python-pip-whl python3-pip python3-twisted python3-twisted-bin raspberrypi-ui-mods rpi-chromium-mods
  rpi-eeprom samba-libs ssh tzdata usb.ids wireless-regdb
81 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 113 MB of archives.
After this operation, 308 kB of additional disk space will be used.
Get:1 http://archive.raspberrypi.org/debian bullseye/main armhf libc6-dbg armhf 2.31-13+rpt2+rpi1+deb11u3 [6,388 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf base-files armhf 11.1+rpi1+deb11u4 [70.3 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf bash armhf 5.1-2+deb11u1 [1,295 kB]
Get:4 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf dpkg armhf 1.20.11+rpi1 [2,460 kB]
Get:5 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libgnutls30 armhf 3.7.1-5+deb11u1 [1,263 kB]
Get:6 http://archive.raspberrypi.org/debian bullseye/main armhf libc-devtools armhf 2.31-13+rpt2+rpi1+deb11u3 [246 kB]
Get:7 http://archive.raspberrypi.org/debian bullseye/main armhf libc6-dev armhf 2.31-13+rpt2+rpi1+deb11u3 [1,815 kB]
Get:8 http://archive.raspberrypi.org/debian bullseye/main armhf libc-dev-bin armhf 2.31-13+rpt2+rpi1+deb11u3 [267 kB]
Get:9 http://archive.raspberrypi.org/debian bullseye/main armhf libc6 armhf 2.31-13+rpt2+rpi1+deb11u3 [2,295 kB]
Get:10 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libsmbclient armhf 2:4.13.13+dfsg-1~deb11u4 [162 kB]
Local time is now:      Sun Jul 24 16:39:43 PDT 2022.
Checking poetry
Can write to /opt/sickchill/.venv/lib/python3.9/site-packages: True
Can write to /home/pi/.local/lib/python3.9/site-packages: True
pip installed: True
pip args: /opt/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
poetry installed: True
Poetry installed packages checker started
Poetry installed packages checker completed
pip args: /opt/sickchill/.venv/bin/python3.9 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU The lock file does not exist. Locking. Updating dependencies Resolving dependencies...  Writing lock file appdirs==1.4.4 babelfish==0.6.0; python_version >= "3.6" and python_version < "4.0" backports.zoneinfo==0.2.1; python_version < "3.9" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") beautifulsoup4==4.11.1; python_full_version >= "3.6.0" beekeeper-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" bencode.py==4.0.0 cachecontrol==0.12.11; python_version >= "3.6" certifi==2022.6.15; python_version >= "3.7" and python_version < "4" cffi==1.15.1; python_version >= "3.6" chardet==5.0.0; python_version >= "3.6" charset-normalizer==2.1.0; python_version >= "3.7" and python_version < "4" and python_full_version >= "3.6.0" cinemagoer==2022.2.11 click==8.1.3; python_version >= "3.7" colorama==0.4.5; python_version >= "3.7" and python_full_version < "3.0.0" and platform_system == "Windows" or platform_system == "Windows" and python_version >= "3.7" and python_full_version >= "3.5.0" configobj==5.0.6 cryptography==37.0.4; python_version >= "3.6" decorator==5.1.1; python_version >= "3.6" deluge-client==1.9.0 deprecated==1.2.13; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" dogpile.cache==1.1.8; python_version >= "3.6" enzyme==0.4.1 feedparser==6.0.10; python_version >= "3.6" future==0.18.2; python_version >= "2.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" gntp==1.0.3 greenlet==1.1.2; python_version >= "3" and python_full_version < "3.0.0" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") or python_version >= "3" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0") and python_full_version >= "3.5.0" guessit==3.4.3 html5lib==1.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.5.0") httplib2==0.20.4; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") idna==3.3; python_version >= "3.7" and python_version < "4" ifaddr==0.2.0 imagesize==1.4.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") imdbpy==2022.7.9 importlib-metadata==4.12.0; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7") importlib-resources==5.9.0; python_version >= "3.7" and python_version < "3.9" ipaddress==1.0.23 js2py==0.71 jsonrpclib-pelix==0.4.3.2 kodipydent-alt==2021.7.16; python_full_version >= "3.6.2" and python_version < "4" lxml==4.9.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" mako==1.2.1; python_version >= "3.7" markdown2==2.4.3; python_version >= "3.5" and python_version < "4" markupsafe==2.1.1; python_version >= "3.7" msgpack==1.0.4; python_version >= "3.6" new-rtorrent-python==1.0.1a0 oauthlib==3.2.0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" packaging==21.3; python_version >= "3.6" pbr==5.9.0; python_version >= "3.6" profilehooks==1.12.0 putio.py==8.7.0 pyaes==1.6.1 pycparser==2.21; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6" pygithub==1.55; python_version >= "3.6" pyjsparser==2.7.1 pyjwt==2.4.0; python_version >= "3.6" pymediainfo==5.1.0; python_version >= "3.6" pynacl==1.5.0; python_version >= "3.6" pynma==1.0 pyopenssl==22.0.0; python_version >= "3.6" pyparsing==3.0.9; python_full_version >= "3.6.8" and python_version >= "3.6" pysocks==1.7.1; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.4.0") pysrt==1.1.2 python-dateutil==2.8.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.3.0") python-slugify==6.1.2; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") python-twitter==3.5 python3-fanart==2.0.0 pytz-deprecation-shim==0.1.0.post0; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6" pytz==2022.1 qbittorrent-api==2022.5.32 rarfile==4.0 rebulk==3.1.0 requests-oauthlib==1.3.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" requests==2.28.1; python_version >= "3.7" and python_version < "4" send2trash==1.8.0 sgmllib3k==1.0.0; python_version >= "3.6" six==1.16.0; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" soupsieve==2.3.2.post1; python_version >= "3.6" and python_full_version >= "3.6.0" sqlalchemy==1.4.39; (python_version >= "2.7" and python_full_version < "3.0.0") or (python_full_version >= "3.6.0") stevedore==3.5.0; python_version >= "3.6" subliminal==2.1.0 text-unidecode==1.3; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" timeago==1.0.15 tmdbsimple==2.9.1 tornado==6.2; python_version >= "3.7" tus.py==1.3.4 tvdbsimple==1.0.6 typing-extensions==4.3.0; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7") tzdata==2022.1; platform_system == "Windows" and python_version >= "3.6" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") tzlocal==4.2; python_version >= "3.6" unidecode==1.3.4; python_version >= "3.5" urllib3==1.26.10; python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "4" or python_full_version >= "3.6.0" and python_version < "4" and python_version >= "3.7" validators==0.20.0; python_version >= "3.4" webencodings==0.5.1; python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" win-inet-pton==1.1.0 wrapt==1.14.1; python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6" xmltodict==0.13.0; python_full_version >= "3.6.2" and python_version < "4" and python_version >= "3.4" zipp==3.8.1; python_version < "3.8" and python_version >= "3.7" and (python_version >= "3.7" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.6.0" and python_version < "3.8" and python_version >= "3.7")
Command result: ERROR: Invalid requirement: 'The lock file does not exist. Locking.'

Trying user site-packages
Command result: ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

Traceback (most recent call last):
  File "/opt/sickchill/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/sickchill/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 3, in <module>
    from sickchill import logger, settings
  File "/opt/sickchill/sickchill/logger.py", line 12, in <module>
    from github import InputFileContent
ModuleNotFoundError: No module named 'github'
```

**Comment by miigotu** [comment]
`sudo rm -rf /opt/SickChill/.venv && sudo systemctl restart sickchill `

**Comment by Insodus** [comment]
Why is this issue closed?  I have the same issue and the above listed fix about .venv does not work

Tried a git pull, removing .venv, all the usual, still no go and get the above error

**Comment by markasammut** [comment]
@miigotu  Same issue, not fixed by removing .venv

**Comment by promising1** [comment]
FYI, I had to completely delete the folder and pull the latest branch for it to work. As per @Insodus and @markasammut, the removal of the `.venv` was useless.

**Comment by paulvt** [comment]
This seems very related to this explanation: https://github.com/SickChill/SickChill/wiki/Poetry-and-the-history-of-dependencies-in-SickChill
If you check out and run it, nothing happens any more that fixes up the depends. It seems that it has to be done using by poetry manually from now on. None of the installation or upgrade guides seem to reflect this though (for Git installs).
I might be overlooking things though...

**Comment by miigotu** [comment]
Git installs should be reinstalled using a supported method, such as `pip install -U sickchill` or `git checkout.... && poetry install`

**Comment by paulvt** [comment]
Yes, that did the trick, thanks for the examples at the end of that page.
Please consider updating https://github.com/SickChill/SickChill/wiki/Installation-&-Configuration-Guides and dropping guides that no longer work (such as Debian's, that uses a Git install).

**Comment by miigotu** [comment]
> Yes, that did the trick, thanks for the examples at the end of that page. Please consider updating https://github.com/SickChill/SickChill/wiki/Installation-&-Configuration-Guides and dropping guides that no longer work (such as Debian's, that uses a Git install).

Yes, I agree. Please consider contributing edits and deletions to the wiki 😂
https://github.com/SickChill/SickChill.WikiTemp

The majority of the existing documentation needs updated, and there is like 15 years of documentation. It doesn't happen overnight.
