### ISSUE TITLE
Subtitle download fails always with 'TypeError: tuple indices must be integers or slices, not str'

### ISSUE THREAD

**Issue by crazyelectron-io** [SickChill/SickChill#8051]
Running Sickchill container (v2022.07.20) from linuxserver with 'latest' image tag.
Manually search for subtitles gives an error:
```
2022-08-02 21:31:12 DEBUG :: WEBSERVER-HOME_0 :: get_scene_exceptions: ['the flight attendant']
2022-08-02 21:31:12 DEBUG :: WEBSERVER-HOME_0 :: exceptions_cache: {-1: ['the flight attendant']}
2022-08-02 21:31:15 DEBUG :: WEBSERVER-HOME_0 :: Checking subtitle candidates for The Flight Attendant S02E08 (the.flight.attendant.s02e08.1080p.web.h264-cakes.mkv)
2022-08-02 21:31:16 DEBUG :: WEBSERVER-HOME_0 :: Could not search in thesubdb provider. Discarding for now
2022-08-02 21:31:16 INFO :: WEBSERVER-HOME_0 :: Error occurred when downloading subtitles for: /media/tv/The Flight Attendant/Season 02/the.flight.attendant.s02e08.1080p.web.h264-cakes.mkv
2022-08-02 21:31:16 ERROR :: WEBSERVER-HOME_0 :: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sickchill/oldbeard/subtitles.py", line 257, in download_subtitles
    f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']}%)"
TypeError: tuple indices must be integers or slices, not str

2022-08-02 21:31:16 DEBUG :: WEBSERVER-HOME_0 :: 366625: No subtitles downloaded for The Flight Attendant S02E08
```
The error occurs on the last `log.debug` line in `subtitles.py` section shown below:
```python
    try:
        subtitles_list = pool.list_subtitles(video, languages)

        for provider in providers:
            if provider in pool.discarded_providers:
                logger.debug("Could not search in {0} provider. Discarding for now".format(provider))

        if not subtitles_list:
            logger.debug(
                "No subtitles found for {0} {1}".format(
                    episode.show.name, episode_num(episode.season, episode.episode) or episode_num(episode.season, episode.episode, numbering="absolute")
                )
            )
            return existing_subtitles, None

        for subtitle in subtitles_list:
            scores = log_scores(subtitle, video, user_score=user_score)
            logger.debug(
=here=>         f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']}%)"
            )
```

**Comment by BKSteve** [comment]
Per the log `Could not search in thesubdb provider` indicates the provider gave no results. 
Is the provider `thesubdb` returning any results? 
I get `Error 522` when trying to connect to `http://www.thesubdb.com/`

**Comment by crazyelectron-io** [comment]
I removed `thesubdb` but the problem remains. Also when sticking to just `opensubtitles.org` I still get an error.

**Comment by BKSteve** [comment]
Just to confirm you version checksum is d3d9e0cd9ffe9343563ccbecd5a6c5a55878d0d5

**Comment by crazyelectron-io** [comment]
Not sure where to find the checksum, I am running the latest linuxserver.io docker image.

But, I mixed up some tests as I tried a few different SickBeard 'descendants' and the `opensubtitles` authentication error was from testing SickGear. Sorry for the confusion...

`opensubtitles.org` doesn't seem to work anymore:
```
2022-08-03 22:12:43 INFO :: WEBSERVER-HOME_0 :: Error occurred when downloading subtitles for: /media/tv/The Flight Attendant/Season 02/the.flight.attendant.s02e07.1080p.web.h264-cakes[eztv.re].mkv
2022-08-03 22:12:43 ERROR :: WEBSERVER-HOME_0 :: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sickchill/oldbeard/subtitles.py", line 257, in download_subtitles
    f"[{subtitle.provider_name}] Subtitle score for {subtitle.id} is: {scores['res']}/{scores['percent']}% (min={scores['min']}/{scores['min_percent']}%)"
TypeError: tuple indices must be integers or slices, not str

2022-08-03 22:12:43 DEBUG :: WEBSERVER-HOME_0 :: 366625: No subtitles downloaded for The Flight Attendant S02E07
```

**Comment by miigotu** [comment]
I think I did not build and send master to pypi (pip installs). It is fixed in master, but I have not fixed it in the latest version on pypi yet. This is why I was working on the maintenance scripts to avoid problems like that.

https://github.com/SickChill/SickChill/blob/master/sickchill/oldbeard/subtitles.py#L257

**Comment by crazyelectron-io** [comment]
Thanks.
After rebuilding the image with the updated file, the error is gone.
