### ISSUE TITLE
ModuleNotFoundError: No module named 'imdb'

### ISSUE THREAD

**Issue by alexsalex** [SickChill/SickChill#8059]
After upgrade to the latest version:

```
Command result: WARNING: Ignoring invalid distribution -br (/opt/SickChillServer/.venv/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -br (/opt/SickChillServer/.venv/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -br (/opt/SickChillServer/.venv/lib/python3.8/site-packages)
    WARNING: Ignoring invalid distribution -br (/opt/SickChillServer/.venv/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -br (/opt/SickChillServer/.venv/lib/python3.8/site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.14 requires packaging<21.0,>=20.4, but you have packaging 21.3 which is incompatible.
poetry-date-version-plugin 2021.7.16.post6 requires cleo<2.0.0,>=1.0.0a1, but you have cleo 0.8.1 which is incompatible.
poetry-date-version-plugin 2021.7.16.post6 requires poetry>=1.2.0a0, but you have poetry 1.1.14 which is incompatible.

Traceback (most recent call last):
  File "/opt/SickChillServer/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/opt/SickChillServer/sickchill/__init__.py", line 6, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/opt/SickChillServer/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/SickChillServer/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/opt/SickChillServer/sickchill/tv.py", line 14, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'
```

**Comment by alexsalex** [comment]
this worked for me to fix

/opt/SickChill/.venv/bin/python3.8 -m pip install --force-reinstall IMDbPY

**Comment by miigotu** [comment]
That is not a good solution. Just update SC or install it with pip.

Just delete the .venv folder, git pull, and restart SC.
