### ISSUE TITLE
[APP SUBMITTED]: __init__() missing 1 required positional argument: 'parsers'

### ISSUE THREAD

**Issue by Sandrus** [SickChill/SickChill#8065]
### INFO
Python Version: **3.9.13 (main, Jul 26 2022, 13:12:30) [GCC 10.3.1 20211027]**
Operating System: **Linux-5.15.46-Unraid-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@45567ca2301751b09a690672a640e28df60d931d
Link to Log: https://gist.github.com/19ad2feefb51f438f7fc3478fbf135d0
### ERROR
```
Exception while searching Jackett2. Error: __init__() missing 1 required positional argument: 'parsers'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Sandrus** [comment]
### INFO
Python Version: **3.9.13 (main, Jul 26 2022, 13:12:30) [GCC 10.3.1 20211027]**
Operating System: **Linux-5.15.46-Unraid-x86_64-with**
Locale: None
Branch: **pip**
Commit: SickChill/SickChill@45567ca2301751b09a690672a640e28df60d931d
Link to Log: https://gist.github.com/50500cdf00b805f55408c84b415b7af6
### ERROR
```
Exception while searching Jackett2. Error: __init__() missing 1 required positional argument: 'parsers'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by Sandrus** [comment]
Sickschill is on unRaid and up to date
Docker provided by lscr.io/linuxserver/sickchill

**Comment by thargan81** [comment]
Seeing the same after updating to the latest release earlier today:

`2022-08-14 22:14:05 INFO :: SEARCHQUEUE-MANUAL-253279 :: [NZBGeek] :: Performing episode search for The Exes
2022-08-14 22:14:05 DEBUG :: SEARCHQUEUE-MANUAL-253279 :: [NZBGeek] :: get_scene_exceptions: ['the exes']
2022-08-14 22:14:05 DEBUG :: SEARCHQUEUE-MANUAL-253279 :: [NZBGeek] :: exceptions_cache: {-1: ['the exes']}
2022-08-14 22:14:05 DEBUG :: SEARCHQUEUE-MANUAL-253279 :: [NZBGeek] :: get_scene_exceptions: ['the exes']
2022-08-14 22:14:05 DEBUG :: SEARCHQUEUE-MANUAL-253279 :: [NZBGeek] :: exceptions_cache: {-1: ['the exes']}
2022-08-14 22:14:05 DEBUG :: SEARCHQUEUE-MANUAL-253279 :: [NZBGeek] :: GET URL: https://api.nzbgeek.info/api?t=caps&apikey=REDACTED [Status: 200]
2022-08-14 22:14:05 ERROR :: SEARCHQUEUE-MANUAL-253279 :: [NZBGeek] :: Exception while searching NZBGeek. Error: __init__() missing 1 required positional argument: 'parsers'
2022-08-14 22:14:05 DEBUG :: SEARCHQUEUE-MANUAL-253279 :: [NZBGeek] :: Traceback (most recent call last):
  File "/home/barghest/Apps/SickChill/sickchill/oldbeard/search.py", line 459, in searchProviders
    searchResults = curProvider.find_search_results(show, episodes, search_mode, manualSearch, downCurQuality)
  File "/home/barghest/Apps/SickChill/sickchill/providers/GenericProvider.py", line 152, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/barghest/Apps/SickChill/sickchill/oldbeard/providers/newnewznab.py", line 268, in search
    self.get_newznab_categories(just_caps=True)
  File "/home/barghest/Apps/SickChill/sickchill/oldbeard/providers/newnewznab.py", line 150, in get_newznab_categories
    with BS4Parser(data, language="xml") as html:
TypeError: __init__() missing 1 required positional argument: 'parsers'

`

**Comment by thargan81** [comment]
NZBGeek looks to be working again after updating to commit 400f7a8ece5f511b92e08789efeef1fec125c759

**Comment by Sandrus** [comment]
Error is gone after update also, thank you
