### ISSUE TITLE
SickChill not responding correctly after latest update - 'sickchill.settings' has no attribute 'NO_LGMARGIN'

### ISSUE THREAD

**Issue by Smokey23** [SickChill/SickChill#8072]
Branch/Commit:  pip latest
OS:  Windows 10
Browser:  Chrome
What you did:  Noting.  App updated itself this morning
What happened:  After the update. page loads timeout and errors are thrown in logs.
What you expected:  For the update to work correctly
Logs:
```
2022-08-15 01:36:18 DEBUG :: CHECKVERSION :: Starting new thread: CHECKVERSION
2022-08-15 01:36:18 INFO :: CHECKVERSION :: New update found for SickChill, starting auto-updater ...
2022-08-15 01:36:19 INFO :: CHECKVERSION :: Request failed: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/SickChill/SickChill/v2022.08.15-None/sickchill/oldbeard/databases/main.py (HTTPError)
2022-08-15 01:36:19 DEBUG :: CHECKVERSION :: We can proceed with the update. New update has same DB version
2022-08-15 01:36:19 DEBUG :: CHECKVERSION :: We can proceed with the update. Post-Processor is not running
2022-08-15 01:36:19 DEBUG :: CHECKVERSION :: We can proceed with the update. Shows are not being updated
2022-08-15 01:36:19 DEBUG :: CHECKVERSION :: Proceeding with auto update
2022-08-15 01:36:19 INFO :: CHECKVERSION :: Config backup in progress...
2022-08-15 01:36:29 INFO :: CHECKVERSION :: Config backup successful, updating...
2022-08-15 01:36:38 ERROR :: WEBSERVER :: Uncaught exception POST /errorlogs/viewlog/ (192.168.0.1)
HTTPServerRequest(protocol='http', host='torrent', method='POST', uri='/errorlogs/viewlog/', version='HTTP/1.1', remote_ip='192.168.0.1')
Traceback (most recent call last):
  File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 185, in async_call
TypeError: viewlog() got an unexpected keyword argument 'min_level'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SickChill\Python3\tools\lib\site-packages\mako\lookup.py", line 344, in _check
    template_stat = os.stat(template.filename)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/SickChill/Python3/tools/lib/site-packages/sickchill/gui/slick/views/viewlogs.mako'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 161, in get
  File "C:\SickChill\Python3\tools\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\SickChill\Python3\tools\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\index.py", line 187, in async_call
  File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\logs.py", line 80, in viewlog
  File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\views\common.py", line 36, in __init__
  File "C:\SickChill\Python3\tools\lib\site-packages\mako\lookup.py", line 249, in get_template
    return self._check(uri, self._collection[uri])
  File "C:\SickChill\Python3\tools\lib\site-packages\mako\lookup.py", line 352, in _check
    raise exceptions.TemplateLookupException(
mako.exceptions.TemplateLookupException: Cant locate template for uri 'viewlogs.mako'
2022-08-15 01:36:43 INFO :: WEBSERVER-ERRORLOGS_0 :: A mako error occurred: module 'sickchill.settings' has no attribute 'NO_LGMARGIN'
```
After that, I get nothing in the logs.

**Comment by idontknowwhatzowrite** [comment]
"ssl_verify = 1" in config.ini solved the issue for me also

**Comment by miigotu** [comment]
This is fixed in master (verified it this time) but not in the 2022.08.29 release. I have limited releases to once a day for now, so I have to wait to push a release. I could do it now (it's a bit after midnight) but I want to make sure nothing else needs to go in today before I burn that release.
