### ISSUE TITLE
Scikchill won't start with error:  Cannot set verify_mode to CERT_NONE when check_hostname is enabled.

### ISSUE THREAD

**Issue by valheru** [SickChill/SickChill#8073]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Ubuntu 22.04
Browser: 
What you did: tried starting sickchill
What happened: didn't start
What you expected: actually starts
Logs:
```
As you can see in the logs it restarted by itself but never came back, when I tried starting via systemctl it just stopped again.
When starting without -q and --deamon I get this stacktrace, tried changing check_hostname=True to check_hsotname=False, same error:
[sickchill.log](https://github.com/SickChill/SickChill/files/9339752/sickchill.log)



Checking poetry
sickchill installed: True
Traceback (most recent call last):
  File "/home/websites/sickchill/SickChill.py", line 350, in <module>
    main()
  File "/home/websites/sickchill/SickChill.py", line 345, in main
    SickChill().start()
  File "/home/websites/sickchill/SickChill.py", line 151, in start
    sickchill.start.initialize(consoleLogging=self.console_logging)
  File "/home/websites/sickchill/sickchill/start.py", line 214, in initialize
    helpers.set_opener(settings.SSL_VERIFY)
  File "/home/websites/sickchill/sickchill/oldbeard/helpers.py", line 71, in set_opener
    https_handler = HTTPSHandler(context=make_context(verify), check_hostname=True)
  File "/home/websites/sickchill/sickchill/oldbeard/helpers.py", line 62, in make_context
    context.verify_mode = ssl.CERT_REQUIRED if verify else ssl.CERT_NONE
  File "/usr/lib/python3.10/ssl.py", line 737, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.

```

**Comment by modem** [comment]
I have the same issue after the last update.

**Comment by BKSteve** [comment]
#8068
