### ISSUE TITLE
calendar stopped working

### ISSUE THREAD

**Issue by herbi3** [SickChill/SickChill#8094]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: latest develop
OS:
Browser:
What you did: request webcal calendar link
What happened: nothing loaded
What you expected: ...
Logs:
```
tarfile.ReadError: file could not be opened successfully
raise ReadError("file could not be opened successfully") 
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\tarfile.py", line 1608, in open 
with TarFile.open(fileobj=zonefile_stream) as tf:
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\site-packages\dateutil\zoneinfo\__init__.py", line 33, in __init__ 
zif = ZoneInfoFile(getzoneinfofile_stream())
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\site-packages\dateutil\zoneinfo\__init__.py", line 102, in get_zonefile_instance 
tz = get_zonefile_instance().get(name) 
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py", line 1655, in nocache 
rv = self.nocache(name=name) AA File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py", line 1557, in __call__ 
utc = tz.gettz("GMT") 
File "C:\Users\admin\AppData\SickChillv2\SickChill\sickchill\views\calendar.py", line 61, in calendar 
self.write(self.calendar()) 
File "C:\Users\admin\AppData\SickChillv2\SickChill\sickchill\views\calendar.py", line 22, in calendar_auth 
return method(self, *args, **kwargs) 
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 3208, in wrapper 
self.calendar_auth() 
File "C:\Users\admin\AppData\SickChillv2\SickChill\sickchill\views\calendar.py", line 18, in get 
result = method(*self.path_args, **self.path_kwargs) 
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1711, in _execute 
Traceback (most recent call last): 
HTTPServerRequest(protocol='https', host='winterfell.tv', method='GET', uri='/sickchill/calendar', version='HTTP/1.0', remote_ip='2404:e80:84fb:3:0:1111:13:1046') 2022-08-20 13:55:12 ERROR :: WEBSERVER :: Uncaught exception GET /sickchill/calendar (2404:e80:84fb:3:0:1111:13:1046) 
tarfile.ReadError: file could not be opened successfully 
raise ReadError("file could not be opened successfully") 
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\tarfile.py", line 1608, in open 
with TarFile.open(fileobj=zonefile_stream) as tf: 
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\site-packages\dateutil\zoneinfo\__init__.py", line 33, in __init__ 
zif = ZoneInfoFile(getzoneinfofile_stream()) 
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\site-packages\dateutil\zoneinfo\__init__.py", line 102, in get_zonefile_instance 
tz = get_zonefile_instance().get(name) 
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py", line 1655, in nocache 
rv = self.nocache(name=name) 
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\site-packages\dateutil\tz\tz.py", line 1557, in __call__ 
utc = tz.gettz("GMT") 
File "C:\Users\admin\AppData\SickChillv2\SickChill\sickchill\views\calendar.py", line 61, in calendar 
self.write(self.calendar()) 
File "C:\Users\admin\AppData\SickChillv2\SickChill\sickchill\views\calendar.py", line 22, in calendar_auth 
return method(self, *args, **kwargs) 
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 3208, in wrapper 
self.calendar_auth() 
File "C:\Users\admin\AppData\SickChillv2\SickChill\sickchill\views\calendar.py", line 18, in get 
result = method(*self.path_args, **self.path_kwargs) 
File "C:\Users\admin\AppData\SickChill\Python3\tools\lib\site-packages\tornado\web.py", line 1711, in _execute 
Traceback (most recent call last): 
HTTPServerRequest(protocol='https', host='winterfell.tv', method='GET', uri='/sickchill/calendar', version='HTTP/1.0', remote_ip='2404:e80:84fb:3:0:1111:13:1046') 2022-08-20 13:55:12 ERROR :: WEBSERVER :: Uncaught exception GET /sickchill/calendar (2404:e80:84fb:3:0:1111:13:1046) 2022-08-20 13:55:12 INFO :: WEBSERVER :: Receiving iCal request from 2404:e80:84fb:3:0:1111:13:1046
```

**Comment by miigotu** [comment]
If you can, please test the develop branch.

**Comment by herbi3** [comment]
Fixed!
