### ISSUE TITLE
Won't start after recent update

### ISSUE THREAD

**Issue by cbude** [SickChill/SickChill#8100]
Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: cc9de09d40de432d8d86cd896ec424ab6af0d78d
OS:Ubuntu
Browser:Chrome
What you did: Update SC
What happened: It won't start
What you expected:
Logs:
```
Traceback (most recent call last):
  File "/opt/sickchill/sickchill/init_helpers.py", line 34, in create_module
    module = import_module(spec.name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/sickchill/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/opt/sickchill/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/opt/sickchill/sickchill/tv.py", line 20, in <module>
    import sickchill.oldbeard.providers
  File "/opt/sickchill/sickchill/oldbeard/providers/__init__.py", line 4, in <module>
    import sickchill.oldbeard.helpers
  File "/opt/sickchill/sickchill/oldbeard/helpers.py", line 32, in <module>
    from tornado._locale_data import LOCALE_NAMES
ModuleNotFoundError: No module named 'tornado'

```

**Comment by miigotu** [comment]
You'll need to switch to python3. 7+. Instead of switching to the lowest possible python version, I suggest getting as close to 3.10 as you can.
