### ISSUE TITLE
Missing module poetry_date_version_plugin (fixed myself) 

### ISSUE THREAD

**Issue by Wally73** [SickChill/SickChill#8126]
To help others hopefully

Branch/Commit: Master/b2b09e3720a5e1b4af3d88a165fa8f97d0a44593
OS: Windows 10 Pro
What you did: After automatic update to b2b09e3720a5e1b4af3d88a165fa8f97d0a44593 UI not working

After the auto update to b2b09e3720a5e1b4af3d88a165fa8f97d0a44593 web ui didn't work 
after manually trying to start in cmd bash window, it turns out that module poetry_date_version_plugin was missing 
done pip install --force-reinstall poetry_date_version_plugin in the current .venv 
and now SickChill webui works again

**Comment by miigotu** [comment]
Yeah beekeeper_alt and kodipydent_alt need an update to remove that requirement. I don't understand why poetry is requiring it but not installing it smh

**Comment by miigotu** [comment]
You broke that worse by using sudo. 
On Synology you have to run the command as sc-sickchill, but I don't know that command off the top of my head. @BKSteve might be able to direct you.

The command (without user) for syno is:
`/volume1/@appstore/sickchill/share/SickChill/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU poetry_date_version_plugin`

**Comment by tinyhands01** [comment]
> You broke that worse by using sudo.

So I uninstalled the package then attempted to reinstall.  Now I'm getting an error that port 8081 is either in use (it isn't) or reserved for system use (it never was before today).  How do I get around this?

Thanks

**Comment by BKSteve** [comment]
So, you probably have some items stuck with root and best to do a complete uninstall (you have a backup right).

useful information https://github.com/SickChill/SickChill/wiki/Synology

By what you are saying I'm assuming you are on DSM7 (if DSM6 then no `/volume1/@appdata` per below)
The _SynoComm package is linked in the build to Python3.8_ so unsure of the results using Python3.10 (not tested) 
Therefore I'd suggest you stay with 3.8 and stick with the default start string.

To completely remove SC from DSM there's quite a few folders, there's also other logs of package center install.

`/var/packages/sickchill/` is where package center puts things and further down /var there are logs of  installation.

To completely remove SC do an uninstall from the package center then:
complete uninstall from the package center not a partial (make sure your backup is safe)
```
sudo rm -rf /volume1/@appstore/sickchill
sudo rm -rf /volume1/@appdata/sickchill
sudo rm -rf /var/packages/sickchill/
```
As you did a `sudo` start of SC there may also be cache files in some folders `/volume1//homes/.cache` you can remove this too.
After the above there should be no SC floating around.
You should probably remove and reinstall `Python3.8` for safety, `sudo` can also affect changes in the python folder as they are still installed as `root` whereas SC is installed as `sc-sickchill` so the DSM will allow it to interact with your other folders.

**Comment by tinyhands01** [comment]
Performed the nuclear uninstall as @BKSteve described, including python3.8 (and 3.10, since I no longer need it).
Installed python3.8 from package, then sickchill from package.  Sickchill will not start from the package center.
Have not done anything else, including NOT attempting to start it from command line.

**Comment by BKSteve** [comment]
https://github.com/SickChill/SickChill/wiki/Synology

What DSM do you have?

If it was a totally fresh install from SynoCommunity, did it start first time?
If not, did you wait many minutes for first time load of all pypi.org packages? (about 10 minutes)

package install log is here `/var/log/packages/sickchill.log`
SC run logs are `/volume1/@appdata/sickchill/data/Logs` and `/volume1/@appdata/sickchill`

use the https://github.com/SickChill/SickChill/wiki/Synology#how-to-run-sc-form-ssh-terminal 
(fixed a typo there just a little while ago) so refresh the page.

**Comment by tinyhands01** [comment]
DSM7.
Totally fresh install from Package Center (community packages). I clicked the "run after install" box but it exits after 10 seconds.
There is nothing in /volume1/@appdata/sickchill/data/Logs
The only things in /volume1/@appdata/sickchill/sickchill.log is "Starting sickchill command ..." and "Writing PID ..."

```
bash-4.4$ /volume1/@appstore/sickchill/env/bin/python3 /volume1/@appstore/sickchill/share/SickChill/SickChill.py --config /volume1/@appdata/sickchill/data/config.ini --datadir /volume1/@appdata/sickchill/data
Checking poetry
Can write to /var/packages/sickchill/home/.local/lib/python3.8/site-packages: False
Can write to /volume1/@appstore/sickchill/env/lib/python3.8/site-packages: True
pip installed: True
Found wheelhouse dir at /volume1/@appstore/sickchill/share/wheelhouse
pip args: /volume1/@appstore/sickchill/env/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU -f/volume1/@appstore/sickchill/share/wheelhouse setuptools poetry wheel
poetry installed: True
Traceback (most recent call last):
  File "/var/packages/python38/target/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/var/packages/python38/target/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/packages/python38/target/lib/python3.8/site-packages/poetry/__main__.py", line 5, in <module>
    from .console import main
  File "/var/packages/python38/target/lib/python3.8/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/var/packages/python38/target/lib/python3.8/site-packages/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ImportError: cannot import name 'Application' from 'cleo' (/volume1/@appstore/sickchill/env/lib/python3.8/site-packages/cleo/__init__.py)
Restarting SickChill with ['/volume1/@appstore/sickchill/share/SickChill/.venv/bin/python3', '/volume1/@appstore/sickchill/share/SickChill/SickChill.py', '--config', '/volume1/@appdata/sickchill/data/config.ini', '--datadir', '/volume1/@appdata/sickchill/data']
Checking poetry
Can write to /volume1/@appstore/sickchill/share/SickChill/.venv/lib/python3.8/site-packages: True
Can write to /var/packages/sickchill/home/.local/lib/python3.8/site-packages: False
pip installed: True
Found wheelhouse dir at /volume1/@appstore/sickchill/share/wheelhouse
pip args: /volume1/@appstore/sickchill/share/SickChill/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU -f/volume1/@appstore/sickchill/share/wheelhouse setuptools poetry wheel
poetry installed: True
Found wheelhouse dir at /volume1/@appstore/sickchill/share/wheelhouse
pip args: /volume1/@appstore/sickchill/share/SickChill/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU -f/volume1/@appstore/sickchill/share/wheelhouse appdirs==1.4.4 ; python_full_version >= "3.6.2" and python_version < "4" babelfish==0.6.0 ; python_full_version >= "3.6.2" and python_version < "4.0" backports-zoneinfo==0.2.1 ; python_full_version >= "3.6.2" and python_version < "3.9" beautifulsoup4==4.10.0 ; python_full_version >= "3.6.2" and python_version < "4" beekeeper-alt==2021.7.16 ; python_full_version >= "3.6.2" and python_version < "4" bencode-py==4.0.0 ; python_full_version >= "3.6.2" and python_version < "4" cachecontrol==0.12.10 ; python_full_version >= "3.6.2" and python_version < "4" certifi==2021.10.8 ; python_full_version >= "3.6.2" and python_version < "4" cffi==1.15.0 ; python_full_version >= "3.6.2" and python_version < "4" chardet==4.0.0 ; python_full_version >= "3.6.2" and python_version < "4" charset-normalizer==2.0.7 ; python_full_version >= "3.6.2" and python_version < "4" click==8.0.3 ; python_full_version >= "3.6.2" and python_version < "4" cloudscraper==1.2.58 ; python_full_version >= "3.6.2" and python_version < "4" colorama==0.4.4 ; python_full_version >= "3.6.2" and python_version < "4" and platform_system == "Windows" configobj==5.0.6 ; python_full_version >= "3.6.2" and python_version < "4" cryptography==35.0.0 ; python_full_version >= "3.6.2" and python_version < "4" decorator==5.1.0 ; python_full_version >= "3.6.2" and python_version < "4" deluge-client==1.9.0 ; python_full_version >= "3.6.2" and python_version < "4" deprecated==1.2.13 ; python_full_version >= "3.6.2" and python_version < "4" dogpile-cache==1.1.4 ; python_full_version >= "3.6.2" and python_version < "4" enzyme==0.4.1 ; python_full_version >= "3.6.2" and python_version < "4" feedparser==6.0.8 ; python_full_version >= "3.6.2" and python_version < "4" future==0.18.2 ; python_full_version >= "3.6.2" and python_version < "4" gntp==1.0.3 ; python_full_version >= "3.6.2" and python_version < "4" greenlet==1.1.2 ; python_full_version >= "3.6.2" and (platform_machine == "aarch64" or platform_machine == "ppc64le" or platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "AMD64" or platform_machine == "win32" or platform_machine == "WIN32") and python_version < "4" guessit==3.4.2 ; python_full_version >= "3.6.2" and python_version < "4" html5lib==1.1 ; python_full_version >= "3.6.2" and python_version < "4" httplib2==0.20.2 ; python_full_version >= "3.6.2" and python_version < "4" idna==3.3 ; python_full_version >= "3.6.2" and python_version < "4" ifaddr==0.1.7 ; python_full_version >= "3.6.2" and python_version < "4" imagesize==1.3.0 ; python_full_version >= "3.6.2" and python_version < "4" imdbpy==2021.4.18 ; python_full_version >= "3.6.2" and python_version < "4" importlib-metadata==4.8.2 ; python_full_version >= "3.6.2" and python_version < "3.8" importlib-resources==5.4.0 ; python_full_version >= "3.6.2" and python_version < "3.9" ipaddress==1.0.23 ; python_full_version >= "3.6.2" and python_version < "4" js2py==0.71 ; python_full_version >= "3.6.2" and python_version < "4" jsonrpclib-pelix==0.4.3.1 ; python_full_version >= "3.6.2" and python_version < "4" kodipydent-alt==2021.7.16 ; python_full_version >= "3.6.2" and python_version < "4" lxml==4.6.4 ; python_full_version >= "3.6.2" and python_version < "4" mako==1.1.5 ; python_full_version >= "3.6.2" and python_version < "4" markdown2==2.4.1 ; python_full_version >= "3.6.2" and python_version < "4" markupsafe==2.0.1 ; python_full_version >= "3.6.2" and python_version < "4" msgpack==1.0.2 ; python_full_version >= "3.6.2" and python_version < "4" new-rtorrent-python==1.0.1a0 ; python_full_version >= "3.6.2" and python_version < "4" oauthlib==3.1.1 ; python_full_version >= "3.6.2" and python_version < "4" packaging==21.2 ; python_full_version >= "3.6.2" and python_version < "4" pbr==5.7.0 ; python_full_version >= "3.6.2" and python_version < "4" profilehooks==1.12.0 ; python_full_version >= "3.6.2" and python_version < "4" putio-py==8.7.0 ; python_full_version >= "3.6.2" and python_version < "4" pyaes==1.6.1 ; python_full_version >= "3.6.2" and python_version < "4" pycparser==2.21 ; python_full_version >= "3.6.2" and python_version < "4" pygithub==1.55 ; python_full_version >= "3.6.2" and python_version < "4" pyjsparser==2.7.1 ; python_full_version >= "3.6.2" and python_version < "4" pyjwt==2.3.0 ; python_full_version >= "3.6.2" and python_version < "4" pymediainfo==5.1.0 ; python_full_version >= "3.6.2" and python_version < "4" pynacl==1.4.0 ; python_full_version >= "3.6.2" and python_version < "4" pynma==1.0 ; python_full_version >= "3.6.2" and python_version < "4" pyopenssl==21.0.0 ; python_full_version >= "3.6.2" and python_version < "4" pyparsing==2.4.7 ; python_full_version >= "3.6.2" and python_version < "4" pysocks==1.7.1 ; python_full_version >= "3.6.2" and python_version < "4" pysrt==1.1.2 ; python_full_version >= "3.6.2" and python_version < "4" python-dateutil==2.8.2 ; python_full_version >= "3.6.2" and python_version < "4" python-slugify==5.0.2 ; python_full_version >= "3.6.2" and python_version < "4" python-twitter==3.5 ; python_full_version >= "3.6.2" and python_version < "4" python3-fanart==2.0.0 ; python_full_version >= "3.6.2" and python_version < "4" pytz-deprecation-shim==0.1.0.post0 ; python_full_version >= "3.6.2" and python_version < "4" pytz==2021.3 ; python_full_version >= "3.6.2" and python_version < "4" qbittorrent-api==2021.8.23 ; python_full_version >= "3.6.2" and python_version < "4" rarfile==4.0 ; python_full_version >= "3.6.2" and python_version < "4" rebulk==3.1.0 ; python_full_version >= "3.6.2" and python_version < "4" requests-oauthlib==1.3.0 ; python_full_version >= "3.6.2" and python_version < "4" requests-toolbelt==0.9.1 ; python_full_version >= "3.6.2" and python_version < "4" requests==2.26.0 ; python_full_version >= "3.6.2" and python_version < "4" send2trash==1.8.0 ; python_full_version >= "3.6.2" and python_version < "4" sgmllib3k==1.0.0 ; python_full_version >= "3.6.2" and python_version < "4" six==1.16.0 ; python_full_version >= "3.6.2" and python_version < "4" soupsieve==2.3 ; python_full_version >= "3.6.2" and python_version < "4" sqlalchemy==1.4.26 ; python_full_version >= "3.6.2" and python_version < "4" stevedore==3.5.0 ; python_full_version >= "3.6.2" and python_version < "4" subliminal==2.1.0 ; python_full_version >= "3.6.2" and python_version < "4" text-unidecode==1.3 ; python_full_version >= "3.6.2" and python_version < "4" timeago==1.0.15 ; python_full_version >= "3.6.2" and python_version < "4" tmdbsimple==2.8.0 ; python_full_version >= "3.6.2" and python_version < "4" tornado==6.1 ; python_full_version >= "3.6.2" and python_version < "4" tus-py==1.3.4 ; python_full_version >= "3.6.2" and python_version < "4" tvdbsimple==1.0.6 ; python_full_version >= "3.6.2" and python_version < "4" typing-extensions==3.10.0.2 ; python_full_version >= "3.6.2" and python_version < "3.8" tzdata==2021.5 ; python_full_version >= "3.6.2" and python_version < "4" tzlocal==4.1 ; python_full_version >= "3.6.2" and python_version < "4" unidecode==1.3.2 ; python_full_version >= "3.6.2" and python_version < "4" urllib3==1.26.7 ; python_full_version >= "3.6.2" and python_version < "4" validators==0.18.2 ; python_full_version >= "3.6.2" and python_version < "4" webencodings==0.5.1 ; python_full_version >= "3.6.2" and python_version < "4" win-inet-pton==1.1.0 ; python_full_version >= "3.6.2" and python_version < "4" wrapt==1.13.3 ; python_full_version >= "3.6.2" and python_version < "4" xmltodict==0.12.0 ; python_full_version >= "3.6.2" and python_version < "4" zipp==3.6.0 ; python_full_version >= "3.6.2" and python_version < "3.9"
2022-09-01 10:12:18 INFO :: MAIN :: Backing up database before upgrade
2022-09-01 10:12:18 INFO :: MAIN :: Proceeding with upgrade
2022-09-01 10:12:18 INFO :: MAIN :: Adding column rls_prefer_words to tvshows
2022-09-01 10:12:18 INFO :: MAIN :: Updated to: 44.4
2022-09-01 10:12:18 INFO :: MAIN :: Backing up database before upgrade
2022-09-01 10:12:18 INFO :: MAIN :: Proceeding with upgrade
2022-09-01 10:12:18 INFO :: MAIN :: Adding column custom_name to tvshows
2022-09-01 10:12:18 INFO :: MAIN :: Updated to: 44.5
2022-09-01 10:12:21 INFO :: MAIN :: Starting SickChill [master] using '/volume1/@appdata/sickchill/data/config.ini'
2022-09-01 10:12:21 INFO :: MAIN :: Generating New API key
2022-09-01 10:12:21 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
2022-09-01 10:12:21 INFO :: CHECKVERSION :: Checking for updates using SOURCE
2022-09-01 10:12:21 INFO :: MAIN :: Checking for scene exception updates from https://sickchill.github.io/scene_exceptions/scene_exceptions.json
2022-09-01 10:12:22 INFO :: MAIN :: Checking for XEM scene exception updates for theTVDB
2022-09-01 10:12:22 INFO :: MAIN :: Checking for scene exception updates for AniDB
```

And with that, the GUI is up (but complains about being 399 commits behind)
I then hit ^C which kills the process  and I see a bunch of "Waiting for ___ thread to exit" messages.
I went to Package Center to try to start SC and it runs for 10 seconds, then shuts down before the GUI starts.

**Comment by Mike-Benoit** [comment]
I'm getting this error on Ubuntu 22.04, "rm -rf .venv" is also not helping, and I confirmed all permissions are correct. 

```
/home/mikeb/sickrage/.venv/bin/python3 /home/mikeb/sickrage/SickChill.py --nolaunch --datadir=/home/mikeb/sickrage
2022-09-01 08:23:30 INFO :: MAIN :: Starting SickChill [master] using '/home/mikeb/sickrage/config.ini'
2022-09-01 08:23:30 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8082/
2022-09-01 08:23:50 INFO :: SEARCHQUEUE-MANUAL-311714 :: Beginning manual search for: [This Is Us - S06E01 - The Challenger]
Checking poetry
Can write to /home/mikeb/.local/lib/python3.10/site-packages: True
Can write to /home/mikeb/sickrage/.venv/lib/python3.10/site-packages: True
pip installed: True
pip args: /home/mikeb/sickrage/.venv/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU --find-links=https://wheel-index.linuxserver.io/ubuntu/ setuptools poetry wheel
poetry installed: True
Poetry installed packages checker started
Poetry installed packages checker completed
["No module named 'poetry_date_version_plugin'"]
Unable to install to the existing virtual environment located at /home/mikeb/sickrage/.venv
Please check the permissions, and that it does not include global site packages
```

All files owned by the proper user:
```
mikeb@mikeb-desktop:~/sickrage$ find . ! -user mikeb | wc
      0       0       0
```

**Comment by tinyhands01** [comment]
Within ```/var/log/packages/sickchill.log```  (actually log.1, which I had to unzip since it rolled over)  there are a number of lines which are suspect:
```
2022/09/01 09:19:44	ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
2022/09/01 09:19:44	poetry 1.1.13 requires cachy<0.4.0,>=0.3.0, which is not installed.
2022/09/01 09:19:44	poetry 1.1.13 requires cleo<0.9.0,>=0.8.1, which is not installed.
2022/09/01 09:19:44	poetry 1.1.13 requires clikit<0.7.0,>=0.6.2, which is not installed.
2022/09/01 09:19:44	poetry 1.1.13 requires crashtest<0.4.0,>=0.3.0; python_version >= "3.6" and python_version < "4.0", which is not installed.
2022/09/01 09:19:44	poetry 1.1.13 requires keyring>=21.2.0; python_version >= "3.6" and python_version < "4.0", which is not installed.
2022/09/01 09:19:44	poetry 1.1.13 requires pexpect<5.0.0,>=4.7.0, which is not installed.
2022/09/01 09:19:44	poetry 1.1.13 requires pkginfo<2.0,>=1.4, which is not installed.
2022/09/01 09:19:44	poetry 1.1.13 requires poetry-core<1.1.0,>=1.0.7, which is not installed.
2022/09/01 09:19:44	poetry 1.1.13 requires shellingham<2.0,>=1.1, which is not installed.
2022/09/01 09:19:44	poetry 1.1.13 requires tomlkit<1.0.0,>=0.7.0, which is not installed.
2022/09/01 09:19:44	poetry 1.1.13 requires virtualenv<21.0.0,>=20.0.26, which is not installed.
```
Although that is BEFORE it successfully started via command line above, so I'm not sure if it means anything.
Within the site-packages folder, I see cachy, crashtest, keyring, pexpect, pkginfo, shellingham, tomlkit, and virtualenv.
Cleo looks to be the wrong version (1.0.0a5) as does poetry-core (1.1.0). 
Clikit is missing altogether.

**Comment by BKSteve** [comment]
@tinyhands01  The issue happens with the Python3.8 code.

`File "/var/packages/python38/target/lib/python3.8/runpy.py"`

Then the issue is SC is creating `/volume1/@appstore/sickchill/share/SickChill/.venv/` which is a new virtual environment rather than the SC normal `/volume1/@appstore/sickchill/env/` location which is what it should be doing.

This is most likely due to the update of Python from 3.8.12 to 3.8.13.

**Comment by BKSteve** [comment]
@Mike-Benoit SickRage??

**Comment by tinyhands01** [comment]
Deleting the .venv folder caused Package Center to throw a "cannot start package" error.  Repair was unsuccessful.
I uninstalled without removing files, then reinstalled - Package would not stay running.
Copied the files from .venv to env - Package would not start.
Started from command line, updated, restored backup.
Strange thing is, it kept running even after I exited ssh session.
Logged back in, found & killed the manually-started PID.
Started from Package Center and it appears to keep running.

**Comment by luisfcorreia** [comment]
I also have this issue
Fedora Server 36, it happens no matter what user starts the process
`pip installed: True
pip args: /opt/sickchill/.venv/bin/python3.10 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU setuptools poetry wheel
poetry installed: True
Poetry installed packages checker started
Poetry installed packages checker completed
["No module named 'poetry_date_version_plugin'"]
Unable to install to the existing virtual environment located at /opt/sickchill/.venv
Please check the permissions, and that it does not include global site packages
`

**Comment by tinyhands01** [comment]
Although I initially had the same problem as OP, my problem diverged.  Perhaps a mod wants to split my posts (and replies) into a different issue?  I fear it is distracting from people not reading that OP actually posted the solution.

**Comment by luisfcorreia** [comment]
Problem is not fixed

**Comment by miigotu** [comment]
I wouldn't be too worried about solving the issue. It's most likely an update to poetry that caused plugins of depends to be required to export the requirements. However, I removed the code that does poetry_install in the tests branch. From here on, it will be on the package provider or the end user to install dependencies. "poetry install --no-root " or "pip install -U sickchill" will have to be called by the user whenever their install doesn't start.

We just need to improve logging and guides and lessen the impact of the change before we can merge it, so there isn't a shit storm when I do. Maybe you guys could switch to the tests branch (or get a package for your distribution that uses the tests branch) and help us improve it before it burns everyone?

**Comment by nydave69** [comment]
Sickchill runs fine until I start the GUI...   That crashes Sickchill every time.
I never get the GUI to show anything..
All since the last update.

Windows 10...

**Comment by Lifferman** [comment]
Hi,
Got the same issue, i couldn't launch from package center but it was working with command.
I did what tinyhands01 did and it got back from package center launcher

> Deleting the .venv folder caused Package Center to throw a "cannot start package" error. - Repair was unsuccessful. I uninstalled without removing files, then reinstalled - Package would not stay running. Copied the files from .venv to env - Package would not start. Started from command line, updated, restored backup. Strange thing is, it kept running even after I exited ssh session. Logged back in, found & killed the manually-started PID. Started from Package Center and it appears to keep running.

The last remaining issue for me is that sickchill crashes if I run episode search... That's what made me try to reinstall.
No logs when it happen even in debug... i think it's linked all together

**Comment by BKSteve** [comment]
Your Episode search uses which provider?
`master` nyaa was causing SC on DSM to crash.

**Comment by Lifferman** [comment]
yep, that was it!
I disabled nyaa and the search is starting fine.

**Comment by Lifferman** [comment]
Well, it seem i spoke too fast...
He does some research and doesn't do some
`2022-09-03 15:21:49 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/`
`2022-09-03 15:21:49 INFO :: MAIN :: Starting SickChill [master] using '/volume1/@appdata/sickchill/data/config.ini'`
`2022-09-03 15:00:24 INFO :: SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes`
`2022-09-03 15:00:24 INFO :: DAILYSEARCHER :: No new released episodes found ...`
`2022-09-03 15:00:24 INFO :: DAILYSEARCHER :: Searching for new released episodes ...`
`[...]`
`2022-09-03 14:50:56 INFO :: SEARCHQUEUE-BACKLOG-243011 :: [J_torlock] :: Performing épisode search for Clem`
`2022-09-03 14:50:49 INFO :: SEARCHQUEUE-BACKLOG-243011 :: Beginning backlog search for: [Clem]`
`2022-09-03 08:12:28 INFO :: SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes`

**Comment by Mike-Benoit** [comment]
@BKSteve

> @Mike-Benoit SickRage??

SickRage is just the name of the directory which I haven't bothered to change for a few years. 

mikeb@mikeb-desktop:~/sickrage$ git remote show origin
* remote origin
  Fetch URL: https://github.com/SickChill/SickChill.git
  Push  URL: https://github.com/SickChill/SickChill.git
  HEAD branch: master

 
> ["No module named 'poetry_date_version_plugin'"] see first post

Nothing in this issue has fixed the problem yet, including the commands in the first post.

**Comment by BKSteve** [comment]
switch to `develop`

**Comment by FaiqH** [comment]
same, SC stops running after start.
Nuked SC and clean install. Still issues with SC suddenly stopping 
installing via ssh and hangs on wheelhouse setuptools poetry wheel.

Usually I do this via GUI so very unsure how to procced.
logs show just start and stop.

**Comment by Lifferman** [comment]
24H i set to develop, SC hasn't crash for now
i think i'm gonna let it like that for now ^^
