### ISSUE TITLE
Sickchill won't start when ssl_verify = 0 (continuing #8119 since commenting was disabled)

### ISSUE THREAD

**Issue by knyllers** [SickChill/SickChill#8141]
I have done a pip3 install -U sickchill so should have latest code. But either the fix in #8119 doesn't work for me, or I'm on the wrong branch. config.ini says: cur_commit_branch = master so that should be correct, right?

henrik@knyllers-media:~$ python3.10 .local/lib/python3.10/site-packages/SickChill.py --datadir /home/henrik/sickchill
Checking poetry
sickchill installed: True
Traceback (most recent call last):
  File "/home/henrik/.local/lib/python3.10/site-packages/SickChill.py", line 350, in <module>
    main()
  File "/home/henrik/.local/lib/python3.10/site-packages/SickChill.py", line 345, in main
    SickChill().start()
  File "/home/henrik/.local/lib/python3.10/site-packages/SickChill.py", line 151, in start
    sickchill.start.initialize(consoleLogging=self.console_logging)
  File "/home/henrik/.local/lib/python3.10/site-packages/sickchill/start.py", line 212, in initialize
    helpers.set_opener(settings.SSL_VERIFY)
  File "/home/henrik/.local/lib/python3.10/site-packages/sickchill/oldbeard/helpers.py", line 71, in set_opener
    https_handler = HTTPSHandler(context=make_context(verify))
  File "/home/henrik/.local/lib/python3.10/site-packages/sickchill/oldbeard/helpers.py", line 63, in make_context
    context.verify_mode = (ssl.CERT_NONE, ssl.CERT_REQUIRED)[bool(verify)]
  File "/usr/lib/python3.10/ssl.py", line 737, in verify_mode
    super(SSLContext, SSLContext).verify_mode.__set__(self, value)
ValueError: Cannot set verify_mode to CERT_NONE when check_hostname is enabled.

**Comment by miigotu** [comment]
You are on a pip install, and there are a few commits from master that are not on the pypi released version yet.
