### ISSUE TITLE
Sickchill Completely Down - database error

### ISSUE THREAD

**Issue by MrNightRyder** [SickChill/SickChill#8144]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: latest build
OS: Server 2012
Browser: Any
What you did: I noticed my sickchill was not working so i uninstalled and reinstalled.  I reimported the database and configuration however it continues to fail.  Log errors are below
What happened:
What you expected:
Logs:

```

2022-09-06 03:46:41 INFO :: MAIN :: If this happened in cache.db, you can safely stop SickChill, and delete the cache.db file without losing any data
2022-09-06 03:46:41 INFO :: MAIN :: Here are the arguments that were passed to this function (This is what the developers need to know): {'self': <sickchill.oldbeard.db.DBConnection object at 0x00000040A9BFE220>, 'query': 'SELECT showid, season, episode, COUNT(showid) as count FROM tv_episodes GROUP BY showid, season, episode HAVING count > 1', 'args': None, 'fetchall': True, 'fetchone': False, 'sql_results': [], 'attempt': 0, 'e': DatabaseError('database disk image is malformed'), 'severity': 40}
2022-09-06 03:46:44 WARNING :: MAIN :: Unable to setup GitHub properly, You are currently being throttled by rate limiting for too many requests - Try adding an access token. Error: 403 {"message": "API rate limit exceeded for 45.21.155.220. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
2022-09-06 03:46:44 ERROR :: MAIN :: Fatal error executing query with db.action in database C:\SickChill\Data\sickchill.db: database disk image is malformed
2022-09-06 03:46:44 INFO :: MAIN :: Traceback (most recent call last):
  File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\db.py", line 265, in action
    sql_results = self._execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\db.py", line 119, in _execute
    sql_results = self.connection.cursor().execute(query)
sqlite3.DatabaseError: database disk image is malformed

2022-09-06 03:46:44 INFO :: MAIN :: If this happened in cache.db, you can safely stop SickChill, and delete the cache.db file without losing any data
2022-09-06 03:46:44 INFO :: MAIN :: Here are the arguments that were passed to this function (This is what the developers need to know): {'self': <sickchill.oldbeard.db.DBConnection object at 0x000000BE936E2130>, 'query': 'SELECT showid, season, episode, COUNT(showid) as count FROM tv_episodes GROUP BY showid, season, episode HAVING count > 1', 'args': None, 'fetchall': True, 'fetchone': False, 'sql_results': [], 'attempt': 0, 'e': DatabaseError('database disk image is malformed'), 'severity': 40}
```

**Comment by BKSteve** [comment]
With the logs use \``` on blank line above and then line below your logs.

Here's your error:
`sqlite3.DatabaseError: database disk image is malformed` and
`'e': DatabaseError('database disk image is malformed'`

It tells you what to try:
`If this happened in cache.db, you can safely stop SickChill, and delete the cache.db file without losing any data`
So make sure SC is shutdown and delete `cache.db` and try to restart.

If that doesn't solve your problem there's another db error which you'd need to restore from a backup.
You could either pull out the .db files from a backup zip or remove all and new install and restore your backup.

**Comment by miigotu** [comment]
We can't really protect against bitrot. Using this happens on single drive or raid 0 installs. Make sure the disk isn't full and try to restart the application.

**Comment by MrNightRyder** [comment]
Tried deleting cache.db and no dice same error.  I'm not sure where I can find the db backups (if they exist).... I did open the db up in SQLite and ran a PRAGMA integrity_check which claims theres a few rows missing from the sickchill.db (see screenshot)

https://i.imgur.com/eZbDSt9.png

As for the tvshow.nfo.... good question not sure if i have that or not would this be located in the folder where the items were downloaded or where would this be stored?

**Comment by BKSteve** [comment]
Dba are in the zip file of a normal SC backup. 

Nfo are in the show folder. If they don't exist and you need to rebuild then `add existing shows` will search for and ask you to choose the show as if adding new.

**Comment by MrNightRyder** [comment]
Is there a way I can import the tv shows from the past database using an export/import?  It looks like there is a tv_shows table as well as a tv_episodes table... I'm guessing the tv_shows stores the tv shows that were in the db and the tv_episodes likely stores past search history and what has or hasn't been downloaded?

**Comment by miigotu** [comment]
You can usually fix the database by exporting it to a sql backup file and then importing that onto a new db

https://docs.locusmap.eu/doku.php?id=manual:advanced:map_tools:corrupted_sqlite#general_solution

**Comment by miigotu** [comment]
I wonder if we could do that in code when it fails 🤔

**Comment by miigotu** [comment]
I guess this fixed it for you. Closing.
