### ISSUE TITLE
Update to 9.14 breaks SickChill

### ISSUE THREAD

**Issue by BCITMike** [SickChill/SickChill#8168]
I had a working SickChill yesterday and found the webGUI not responding. Logged into Debian 11 box and saw the port listening. Tried to start it from systemctl and it would die shortly after.

I started it from the command line and got this error:

```
# /usr/bin/python3 /usr/local/bin/SickChill.py --datadir=/home/rslsync/sickchill                       
Checking poetry
sickchill installed: True
sickchill installed: True
sickchill installed: True
2022-09-15 10:43:17 INFO :: MAIN :: Could not get IMDB info: 'imdbID'
2022-09-15 10:43:17 INFO :: MAIN :: 398216: Unable to find IMDb show info in the database
2022-09-15 10:43:17 INFO :: MAIN :: Starting SickChill [pip] using '/home/rslsync/sickchill/config.ini'
2022-09-15 10:43:17 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
2022-09-15 10:43:17 INFO :: CHECKVERSION :: New update found for SickChill, starting auto-updater ...
2022-09-15 10:43:18 WARNING :: CHECKVERSION :: We can't proceed with the update. Unable to check remote DB version. Error: KeyError('Request failed')
^C2022-09-15 10:44:43 INFO :: MAIN :: Signal 2 caught, saving and exiting...
2022-09-15 10:44:43 INFO :: EVENT-QUEUE :: Aborting all threads
2022-09-15 10:44:43 INFO :: EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Waiting for the NOTIFICATIONS thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Saving all shows to the database
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Saving config file to disk
2022-09-15 10:44:44 INFO :: EVENT-QUEUE :: Shutting down Tornado
```

So I thought that was saying my db was bad and found another issue where someone had a bad db and ran sqlite3 and it was good:
```
sqlite3 sickchill.db "PRAGMA integrity_check"
ok
```

so then I went and ran pip3 upgrade sickchill and it installed 9.14.

After that, when starting sickchill, it fails:
```
# /usr/bin/python3 /usr/local/bin/SickChill.py --datadir=/home/rslsync/sickchill
Traceback (most recent call last):
  File "/usr/local/bin/SickChill.py", line 38, in <module>
    from sickchill.update_manager import GitUpdateManager, SourceUpdateManager
ImportError: cannot import name 'GitUpdateManager' from 'sickchill.update_manager' (/usr/local/lib/python3.9/dist-packages/sickchill/update_manager/__init__.py)
```

If I use pip3 to reinstall 8.29, then it appears to try to upgrade and gets a 404:
```
# /usr/bin/python3 /usr/local/bin/SickChill.py --datadir=/home/rslsync/sickchill
sickchill installed: True
sickchill installed: True
2022-09-15 11:16:29 INFO :: MAIN :: Could not get IMDB info: 'imdbID'
2022-09-15 11:16:29 INFO :: MAIN :: 398216: Unable to find IMDb show info in the database
2022-09-15 11:16:29 INFO :: MAIN :: Starting SickChill [pip] using '/home/rslsync/sickchill/config.ini'
2022-09-15 11:16:29 INFO :: WEBSERVER :: Starting SickChill on http://0.0.0.0:8081/
2022-09-15 11:16:29 INFO :: CHECKVERSION :: New update found for SickChill, starting auto-updater ...
2022-09-15 11:16:29 INFO :: CHECKVERSION :: Request failed: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/SickChill/SickChill/v2022.09.14-None/sickchill/oldbeard/databases/main.py (HTTPError)
2022-09-15 11:16:29 INFO :: CHECKVERSION :: Config backup in progress...
2022-09-15 11:16:39 INFO :: CHECKVERSION :: Config backup successful, updating...
pip args: /usr/bin/python3 -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color -qU sickchill
Command result: WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

2022-09-15 11:16:41 INFO :: CHECKVERSION :: Update was successful!
2022-09-15 11:16:41 INFO :: EVENT-QUEUE :: Aborting all threads
2022-09-15 11:16:41 INFO :: EVENT-QUEUE :: Waiting for the DAILYSEARCHER thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Waiting for the BACKLOG thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Waiting for the SHOWUPDATER thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Waiting for the CHECKVERSION thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Waiting for the SHOWQUEUE thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Waiting for the SEARCHQUEUE thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Waiting for the POSTPROCESSOR thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Waiting for the TRAKTCHECKER thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Waiting for the FINDPROPERS thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Waiting for the FINDSUBTITLES thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Waiting for the NOTIFICATIONS thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Waiting for the EVENT-QUEUE thread to exit
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Saving all shows to the database
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Saving config file to disk
2022-09-15 11:16:42 INFO :: EVENT-QUEUE :: Shutting down Tornado
2022-09-15 11:16:52 INFO :: EVENT-QUEUE :: Restarting SickChill with ['/usr/bin/python3', '/usr/local/bin/SickChill.py', '--datadir=/home/rslsync/sickchill', '--nolaunch']
root@Chi:/home/rslsync/sickchill# Traceback (most recent call last):
  File "/usr/local/bin/SickChill.py", line 38, in <module>
    from sickchill.update_manager import GitUpdateManager, SourceUpdateManager
ImportError: cannot import name 'GitUpdateManager' from 'sickchill.update_manager' (/usr/local/lib/python3.9/dist-packages/sickchill/update_manager/__init__.py)
```

Instead of it trying https://raw.githubusercontent.com/SickChill/SickChill/v2022.09.14-None/sickchill/oldbeard/databases/main.py, it should be https://raw.githubusercontent.com/SickChill/SickChill/2022.9.14/sickchill/oldbeard/databases/main.py.

How do it get it to run the 8.29 version without auto updating and breaking, or how do I get it to run 9.14 properly?

Thanks

**Comment by BCITMike** [comment]
I disabled auto update in config.ini and can run 8.29 from the command line.

**Comment by BCITMike** [comment]
Ok, I see that there was a [commit to master and 9.14](https://github.com/SickChill/SickChill/commit/583063e18c3638a75f1bc85994610a63fdf3bbf1) branch to remove the git stuff and should be PipUpdateManager.

So I guess the files are not actually successfully upgrading to 9.14 properly?

**Comment by miigotu** [comment]
`/usr/local/bin/SickChill.py` is the incorrect script. That is leftover from a previous installation. 

Either 
`/usr/local/bin/SickChill` # no .py
Or
`/usr/local/lib/python3.9/dist-packages/SickChill.py`

**Comment by core-code** [comment]
same here, totally broken since 2 days
<img width="259" alt="Screenshot 2022-09-15 at 21 39 56" src="https://user-images.githubusercontent.com/1261954/190494169-ff2f9f49-b0cb-4cf4-862d-5f6ddf84b70c.png">

**Comment by pigsyn** [comment]
@BCITMike You are mixing a git install with a pip install as root.

@core-code create own issue for macOS, provide information on your current install (user, service)

**Comment by core-code** [comment]
i think my issue was related to macOS upgrading from Python 3.8 to Python 3.9 un unrelated to this issue. deleting `.venv`  did help. sorry for the noise.

**Comment by miigotu** [comment]
> i think my issue was related to macOS upgrading from Python 3.8 to Python 3.9 and unrelated to this issue. deleting `.venv` did help. sorry for the noise.

In the future, it is possible to fix a venv. Check the discussion I linked above about migration, there is a comment about fixing the venv.

**Comment by BCITMike** [comment]
> @BCITMike You are mixing a git install with a pip install as root.
> 
> @core-code create own issue for macOS, provide information on your current install (user, service)

How can I confirm that? I searched the server for a git repo, and only found it in python subdirs. AFAIR, I used pip for install. If anything, I probably misused venv or something. 

There was a time where I did have to do updates from the command line but then got to a point where it was self updating for the last year or so and the branch was "pip" in the GUI.

**Comment by miigotu** [comment]
> `/usr/local/bin/SickChill.py` is the incorrect script. That is leftover from a previous installation. 
> 
> Either 
> `/usr/local/bin/SickChill` # no .py
> Or
> `/usr/local/lib/python3.9/dist-packages/SickChill.py`
> 

@BCITMike I told you exactly what was wrong with your service script. It's calling the wrong script.

**Comment by BCITMike** [comment]
> `/usr/local/bin/SickChill.py` is the incorrect script. That is leftover from a previous installation.
> 
> Either `/usr/local/bin/SickChill` # no .py Or `/usr/local/lib/python3.9/dist-packages/SickChill.py`

Without .py didn't work. Using `/usr/local/lib/python3.9/dist-packages/SickChill.py` worked. Its back running 9.14.

Can you tell me if this is in any updated installation guide? I can't find any reference to using that.  https://github.com/SickChill/SickChill/wiki/Pip

**Comment by miigotu** [comment]
The wiki is entirely outdated. But how python packages are installed and provide scripts is the same as any python package. If you call the old SickChill.py from outside the environment it's not the correct script. We create a Sickchill in the bin for for that environment, or you can use the SickChill.py inside the site-paclage or dost-packages for (depending on how you pip installed)

**Comment by BCITMike** [comment]
> > `/usr/local/bin/SickChill.py` is the incorrect script. That is leftover from a previous installation.
> > Either
> > `/usr/local/bin/SickChill` # no .py
> > Or
> > `/usr/local/lib/python3.9/dist-packages/SickChill.py`
> 
> @BCITMike I told you exactly what was wrong with your service script. It's calling the wrong script.

I understood that part completely. I used to always have to update it from pip from command line and then it was self-updating for I want to say at least a year. It's broken a few times over the years and whatever edits might have been done to get it back working were done.  But up until yesterday, it was the longest it ran trouble free since the start a few years ago.

I'm trying to understand how to get back onto a proper installation that won't break again.

**Comment by BCITMike** [comment]
> The wiki is entirely outdated. But how python packages are installed and provide scripts is the same as any python package. If you call the old SickChill.py from outside the environment it's not the correct script. We create a Sickchill in the bin directory for for that environment, or you can use the SickChill.py inside the site-paclage or dost-packages for (depending on how you pip installed)
> 
> `sudo find / -name SickChill 2>/dev/null` should find it. This is everyday stuff on Linux.

An outdated Wiki serves no purpose if its not clearly marked as such. You couldn't even point me to a single updated installation guide to say "this is the one to be following in 2022". It probably would be more appropriate to remove all that mentioned for newbies (or at least indicate its entirely outdated) and just say, "run it yourself, this is everyday stuff on Linux." (I would argue this is python stuff, not Linux stuff).  How many issues are caused by improper/inconsistent installs?

Anyway, I got it working using the dist-packages path, I couldn't get it to keep running with any variant without the .py.  But it sounds like I shouldn't have to worry again until you move off of python 3.9.

The News with important changes and stuff hasn't been updated in a while and Changelog (shown in the webGUI) doesn't get updated on every release, either (it's running 9.14 and there is no entry for 8.29 or 9.14, but there is one for 7.20, which isn't a release on github). 

I'm getting the impression that to install via pip you must use venv and to use git, you have to run from master rather than releases? Does it run from master (latest commit), releases (dated 2.20) or from tags (dated 9.14?) Is there a blessed install/usage between pip and repo? I don't have a good memory, but I thought it was recommended to go pip way over repo way for updating reasons.

**Comment by miigotu** [comment]
It was warned for months that the documentation needs updated and that we did not have help to update them. Pip installs install and run __the same way__ for every pypi package that exists. It isn't a sickchill exclusive thing. Google it. There are thousands of guides online. 

Using a virtualenv:

```bash
python3 -m venv
source venv/bin/activate
pip install -U sickchill
venv/bin/SickChill
```
Point your service file to that script.

Or

```bash
pip install --user -U sickchill
/.local/bin/SickChill
```

It isn't difficult. Just follow the instructions I have you earlier and keep your smart comments to yourself, or fork it and do it yourself. Every damn time I start fixing shit and you people start acting that way I disappear. Keep at it.
