### ISSUE TITLE
[APP SUBMITTED]: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by josh-gaby** [SickChill/sickchill#8282]
### INFO
Python Version: **3.8.5 (default, Sep  7 2020, 23:51:24) [GCC 6.3.0 20170516]**
Operating System: **Linux-4.19.123-feral-x86_64-with-glibc2.17**
Locale: UTF-8
Version: **2022.10.13**
No Log available with ERRORS:
### ERROR
```
API :: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by josh-gaby** [comment]
Unsure why no log is available, debug logging is enabled. 

Here's the relevant content from the log:

2022-10-31 02:37:56 ERROR :: WEBSERVER :: API :: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
AA TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
AA cur_episode = int(row["episode"])
AA File "xxx/sickchill/views/api/webapi.py", line 2534, in run
AA cur_out_dict = to_call.run() # call function and get response
AA File "xxx/sickchill/views/api/webapi.py", line 175, in call_dispatcher
AA out_dict = _call_dispatcher(args, kwargs)
AA File "xxx/sickchill/views/api/webapi.py", line 106, in get
2022-10-31 02:37:56 INFO :: WEBSERVER :: Traceback (most recent call last):
2022-10-31 02:37:53 INFO :: SEARCHQUEUE-BACKLOG-79648 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?

**Comment by miigotu** [comment]
What was passed to the API?

**Comment by josh-gaby** [comment]
2022-10-31 20:37:58 ERROR :: WEBSERVER :: API :: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
AA TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
AA cur_episode = int(row["episode"])
AA File "xxx/sickchill/views/api/webapi.py", line 2534, in run
AA cur_out_dict = to_call.run() # call function and get response
AA File "xxx/sickchill/views/api/webapi.py", line 175, in call_dispatcher
AA out_dict = _call_dispatcher(args, kwargs)
AA File "xxx/sickchill/views/api/webapi.py", line 106, in get
2022-10-31 20:37:58 INFO :: WEBSERVER :: Traceback (most recent call last):
2022-10-31 20:37:58 DEBUG :: WEBSERVER :: API :: show.seasons: cur_kwargs {'tvdbid': '305074', 'season': '6'}
2022-10-31 20:37:58 DEBUG :: WEBSERVER :: API :: all kwargs: '{'cmd': 'show.seasons', 'tvdbid': '305074', 'season': '6'}'
2022-10-31 20:37:58 DEBUG :: WEBSERVER :: API :: all args: '()'
