### ISSUE TITLE
error 500 on python3.10 on Opensuse Tumbleweed.

### ISSUE THREAD

**Issue by mgaulton** [SickChill/sickchill#8331]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version:
OS: Opensuse Tumbleweed
Browser: Chrome
What you did: Tried to load web UI
What happened: error 500 
What you expected: Page should load as expected
Logs:
```
2023-01-02 16:43:22 ERROR :: WEBSERVER :: Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='192.168.2.5:8182', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/usr/lib64/python3.10/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/vpnuser/.local/lib/python3.10/site-packages/sickchill/views/index.py", line 161, in get
    results = yield self.async_call(method)
  File "/usr/lib64/python3.10/site-packages/tornado/concurrent.py", line 122, in wrapper
    conc_future = getattr(self, executor).submit(fn, self, *args, **kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
2023-01-02 16:43:22 ERROR :: WEBSERVER :: Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='192.168.2.5:8182', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/usr/lib64/python3.10/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/vpnuser/.local/lib/python3.10/site-packages/sickchill/views/index.py", line 161, in get
    results = yield self.async_call(method)
  File "/usr/lib64/python3.10/site-packages/tornado/concurrent.py", line 122, in wrapper
    conc_future = getattr(self, executor).submit(fn, self, *args, **kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

```

**Comment by miigotu** [comment]
This is using the official package from pypi, correct? If it was packaged from develop (or has an updated pypa/packaging package installed) it will fail to start.

**Comment by miigotu** [comment]
I just made a new release, try with that one.

**Comment by mgaulton** [comment]
Yes this was a straight  pip3 install -U sickchill

**Comment by mgaulton** [comment]
I force reinstalled 2023.1.2  and still show an issue.

```


2023-01-03 13:15:52 ERROR :: WEBSERVER :: Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8182', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/usr/lib64/python3.10/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/vpnuser/.local/lib/python3.10/site-packages/sickchill/views/index.py", line 161, in get
    results = yield self.async_call(method)
  File "/usr/lib64/python3.10/site-packages/tornado/concurrent.py", line 122, in wrapper
    conc_future = getattr(self, executor).submit(fn, self, *args, **kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 176, in submit
    self._adjust_thread_count()
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 199, in _adjust_thread_count
    t.start()
  File "/usr/lib64/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
2023-01-03 13:15:52 ERROR :: WEBSERVER :: Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8182', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/usr/lib64/python3.10/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/home/vpnuser/.local/lib/python3.10/site-packages/sickchill/views/index.py", line 161, in get
    results = yield self.async_call(method)
  File "/usr/lib64/python3.10/site-packages/tornado/concurrent.py", line 122, in wrapper
    conc_future = getattr(self, executor).submit(fn, self, *args, **kwargs)
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 176, in submit
    self._adjust_thread_count()
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 199, in _adjust_thread_count
    t.start()
  File "/usr/lib64/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

```

**Comment by mgaulton** [comment]
Seems its starting now after a 2nd force-reinstall.
I'll check out the UI and let you know if I hit any things.

**Comment by miigotu** [comment]
You need to increase the thread limit of the OS (and probably the limit for open files also) as this is OpenSUSE being overprotective, and not allowing your user to run many processes. 

You can check the existing limit with
```bash
sudo cat /proc/sys/kernel/threads-max
```

To set it permanently:
```bash
sudo nano /etc/sysctl.conf
```
Add or edit:
```ini
kernel.threads-max = "99999"
kernel.pid_max = "99999"

```

Reboot and check 
```bash
sudo ulimit -a
```

You might also have to set it in another place, see: https://stackoverflow.com/a/69264209

**Comment by miigotu** [comment]
The last time you probably got lucky that some other process wasn't running as many threads, which allowed SC to load it's 4 threads.

**Comment by mgaulton** [comment]
Hm I set it to 999999 and rebooted

server6:~ #  ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 63444
max locked memory           (kbytes, -l) 8192
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1048576
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 63444
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
server6:~ #

**Comment by miigotu** [comment]
Is that on the same user that runs sickchill? The sickchill system user maybe? Also see the other link I posted about defaults for new processes, OpenSUSE has another place you also have to edit.

**Comment by miigotu** [comment]
Try editing your service file and add `TasksMax=9999`

**Comment by miigotu** [comment]
I would also check something like the top command to see available memory and processing. This same error happens if you are out of memory or stack, or the CPU is pegged.

**Comment by miigotu** [comment]
I'm also curious where your python came from, maybe multithreading isn't enabled?

**Comment by miigotu** [comment]
Hmm, this is also possible with SickChill crashing in one thread and not another.

`cannot schedule new futures after interpreter shutdown`


Try running it from the shell, and check the log output there before this all happens. 

`/home/vpnuser/.local/lib/python3.10/bin/sickchill`

**Comment by mgaulton** [comment]
its always been the same user. I have a vpnuser, that runs inside a namespace, so only the vpn tunnel is available to it.
CPU peg is possible, but mem usage has been around 50% or less when i've checked it.
I'm using the system package for python. I'm using a bunch of other things like Mylar and Lazylibr.
I've done a system update and reboot. 
I also switched to doing a pipx run for sickchill, so its been stable the past couple days.

**Comment by mgaulton** [comment]
So I got the cannot schedule new futures after interpreter shutdown again, error 500.
CPU is high, memory is about 60% used, no swap
The DefaultTasksMax was 15% (the default uncommented value), bumping this to 30%

vpnuser@server6:~> ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 63444
max locked memory           (kbytes, -l) 8192
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1048576
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 63444
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
