### ISSUE TITLE
After adding Stargate SG-1, SickChill did not load the seasons/episodes

### ISSUE THREAD

**Issue by jdstone** [SickChill/sickchill#8335]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

**Version:** 2023.1.2
**OS:** Ubuntu 22.04.1 LTS (jammy)
Linux server 5.15.0-56-generic #62-Ubuntu SMP x86_64
**Browser:** Google Chrome Version 108.0.5359.125 (Official Build) (64-bit)
**What you did:** I added a new show, "Stargate SG-1". I also performed a Force Full Update on this show.
**What happened:** It never loaded any seasons or episodes. (see screenshot)
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/817664/211043907-6662118c-1f96-4942-9cc5-be1c7a0bae11.png">
**What you expected:** It should load/show the seasons and episodes.
**Logs:**
```
2023-01-06 07:36:01 DEBUG :: WEBSERVER-HOME_0 :: exceptions_cache: {-1: ['Stargate SG1', 'stargate sg 1']}
2023-01-06 07:36:01 DEBUG :: WEBSERVER-HOME_0 :: get_scene_exceptions: ['Stargate SG1', 'stargate sg 1']
2023-01-06 07:30:44 DEBUG :: WEBSERVER-HOME_0 :: exceptions_cache: {-1: ['Stargate SG1', 'stargate sg 1']}
2023-01-06 07:30:44 DEBUG :: WEBSERVER-HOME_0 :: get_scene_exceptions: ['Stargate SG1', 'stargate sg 1']
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: No new cache images needed, not retrieving new ones
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking if file fanart_path exists
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking if file banner_thumb_path exists
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking if file poster_thumb_path exists
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking if file banner_path exists
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking if file poster_path exists
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking if we need any cache images for show 72449
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking & filling cache for show Stargate SG-1
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Metadata provider KODI updating show indexer info metadata file for Stargate SG-1
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking if /mnt/storage/videos/tv/Stargate SG-1/tvshow.nfo exists: True
2023-01-06 07:24:03 INFO :: SHOWQUEUE-FORCE-UPDATE :: 72449: Updating NFOs for show with new indexer info
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: 72449: Writing NFOs for all episodes
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking if /mnt/storage/videos/tv/Stargate SG-1/tvshow.nfo exists: True
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: 72449: Writing NFOs for show
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking if /mnt/storage/videos/tv/Stargate SG-1/season-all-poster.jpg exists: True
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking if /mnt/storage/videos/tv/Stargate SG-1/season03-poster.jpg exists: True
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking if /mnt/storage/videos/tv/Stargate SG-1/banner.jpg exists: True
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Checking if /mnt/storage/videos/tv/Stargate SG-1/poster.jpg exists: True
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: 72449: Loading all episodes with a location from the database
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: 72449: Loading all episodes from the show directory /mnt/storage/videos/tv/Stargate SG-1
2023-01-06 07:24:03 INFO :: SHOWQUEUE-FORCE-UPDATE :: Performing refresh on Stargate SG-1
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Finished update of Stargate SG-1
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: 72449: Saving to database: Stargate SG-1
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: 72449: Saving to database: Stargate SG-1
AA TypeError: 'NoneType' object is not iterable
AA episodes.extend(self.page(i))
AA File "/home/jd/Applications/sickchill/lib/python3.10/site-packages/tvdbsimple/series.py", line 223, in all
AA result = self.series_episodes(show.indexerid, airedSeason=season, language=show.lang).all()
AA File "/home/jd/Applications/sickchill/lib/python3.10/site-packages/sickchill/show/indexers/tvdb.py", line 76, in episodes
AA result = target(*args, **kwargs)
AA File "/home/jd/Applications/sickchill/lib/python3.10/site-packages/sickchill/show/indexers/wrappers.py", line 25, in wrapper
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Traceback (most recent call last):
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Could not find item on the indexer: (Indexer probably does not have this item) ['NoneType' object is not iterable]
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: 72449: Loading all episodes from theTVDB...
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Loading all episodes from theTVDB
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Loading all episodes from the database
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: 72449: Saving to database: Stargate SG-1
2023-01-06 07:24:03 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: 72449: Obtained info from IMDb ->{'indexer_id': 72449, 'imdb_id': '0118480', 'title': 'Stargate SG-1', 'year': 1997, 'akas': 'Stargåte SG.1 (United States)|Stargate: SG-1 (United States)|Stargate Command (United States)|La porte des étoiles (Canada, French title)|Stargåte SG-1 (Israel, English title)', 'runtimes': '44', 'genres': 'Action|Adventure|Drama|Sci-Fi', 'countries': 'United States|Canada', 'country_codes': 'us|ca', 'certificates': 'Argentina:13|Australia:M::(some episodes)|Australia:PG::(some episodes)|Brazil:L|Brazil:Livre::(new rating)|Canada:14A::(DVD rating)|France:Tous publics|Germany:16|Iceland:16::(2 episodes)|India:U::(all episodes)|India:U::(video rating)|Italy:T|Mexico:PG::(DVD rating)|Netherlands:6|Philippines:13+::(self-applied)|Poland:15::(DVD rating)|Singapore:PG|Singapore:M18::(season 1)|Spain:12|United Kingdom:12::(some episodes)|United Kingdom:15::(some episodes)|United Kingdom:PG::(some episodes)|United States:TV-14|United States:TV-G|United States:TV-PG|United States:TV-MA::(Netflix rating)|United Arab Emirates:PG', 'rating': '8.4', 'votes': '94636', 'last_update': 738526}
2023-01-06 07:23:58 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: 72449: Loading show info from IMDb
2023-01-06 07:23:57 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: 72449: Loading show info from theTVDB
2023-01-06 07:23:57 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Retrieving show info from theTVDB
2023-01-06 07:23:57 DEBUG :: SHOWQUEUE-FORCE-UPDATE :: Beginning update of Stargate SG-1
2023-01-06 07:23:56 DEBUG :: WEBSERVER-HOME_0 :: exceptions_cache: {-1: ['Stargate SG1', 'stargate sg 1']}
2023-01-06 07:23:56 DEBUG :: WEBSERVER-HOME_0 :: get_scene_exceptions: ['Stargate SG1', 'stargate sg 1']
2023-01-06 07:23:48 DEBUG :: WEBSERVER-HOME_0 :: exceptions_cache: {-1: ['Stargate SG1', 'stargate sg 1']}
2023-01-06 07:23:48 DEBUG :: WEBSERVER-HOME_0 :: get_scene_exceptions: ['Stargate SG1', 'stargate sg 1']
```

**Comment by BKSteve** [comment]
Has it loaded yet? Are you adding as new show or existing `SG-1` has been around a long time.

If new then just try remove, clean any SG-1 folder, and add again.
If add existing move out all episodes to another folder, then remove, clean, add. Process the files back in using manual post processing if the show installs properly.

The `Could not find item on the indexer:` looks like tvdb issue. They might be being difficult with all those still using API v3

**Comment by miigotu** [comment]
Try adding by the tvdb id, 72449. You can put that in as the search string to add the show.

I'm thinking it is being added as 66562, which is a movie and obviously has no episodes to iterate over.

**Comment by jdstone** [comment]
@BKSteve Removing and re-adding it worked.  I don't know why I didn't think of that.

>Try adding by the tvdb id, 72449. You can put that in as the search string to add the show.
>
>I'm thinking it is being added as 66562, which is a movie and obviously has no episodes to iterate over.

@miigotu, this may have been the problem, though I can't confirm.  The TV show is now being added with tvdb id 72449.

Thank you all!
