### ISSUE TITLE
ModuleNotFoundError: No module named 'fanart'

### ISSUE THREAD

**Issue by SoftNotWork** [SickChill/sickchill#8336]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: GIT latest
OS: CentOS 7
Browser: Chrome
What you did: Updated to Git
What happened: It broke
What you expected:
Logs:
```
Traceback (most recent call last):
  File "/home/user/sickrage/./SickChill.py", line 14, in <module>
    import sickchill.start
  File "/home/user/sickrage/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/home/user/sickrage/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/home/user/sickrage/sickchill/show/indexers/handler.py", line 7, in <module>
    from .tvdb import TVDB
  File "/home/user/sickrage/sickchill/show/indexers/tvdb.py", line 10, in <module>
    import sickchill.start
  File "/home/user/sickrage/sickchill/start.py", line 22, in <module>
    from .oldbeard import (
  File "/home/user/sickrage/sickchill/oldbeard/image_cache.py", line 9, in <module>
    from sickchill.providers.metadata.generic import GenericMetadata
  File "/home/user/sickrage/sickchill/providers/metadata/__init__.py", line 3, in <module>
    from . import generic, helpers, kodi, mede8er, mediabrowser, ps3, tivo, wdtv
  File "/home/user/sickrage/sickchill/providers/metadata/generic.py", line 6, in <module>
    import fanart
ModuleNotFoundError: No module named 'fanart'
```

**Comment by SoftNotWork** [comment]
I actually fixed this with a: 

python3.9 -m pip install . inside the directory. The awkward install for CentoS7 seems to be the cause.

**Comment by kyuuk** [comment]
Source installs are not supported anymore, you need to install SickChill using pip.
https://github.com/SickChill/SickChill/wiki/Pip
