### ISSUE TITLE
Client Error posting to discord webhook only from PostProcessor, snatch is fine.

### ISSUE THREAD

**Issue by JustSomeGuyNZ** [SickChill/sickchill#8339]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: 2022.10.13
OS: Windows Server 2019
Browser: N/A
What you did/ happened/expected:
 At some point after NYE, web hook notifications from the post processor seem to have stopped working. I'm still getting notifications on snatch, but not when the post processor imports and attempts to notify on completion. Restarting the service doesn't seem to have changed anything, Debug logging shows a 400 client error.
What you expected:
Both snatch and download notifications to work.
Logs:
```
2023-01-10 20:14:33 INFO :: POSTPROCESSOR-AUTO :: Processing X:\Path\A TV Show\Season 02\A TV Show - S02E14 - Episode Name.1080p.AVC.EAC3.WEB-DL-METCON.mkv (None)
2023-01-10 20:14:33 DEBUG :: POSTPROCESSOR-AUTO :: Analyzing name A TV Show - S02E14 - Episode Name.1080p.AVC.EAC3.WEB-DL-METCON.mkv
2023-01-10 20:14:33 DEBUG :: POSTPROCESSOR-AUTO :: Trying a new way to verify if we can parse this file
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Parsed A TV Show - S02E14 - Episode Name.1080p.AVC.EAC3.WEB-DL-METCON into A TV Show - S02E14 [GROUP: METCON] [ABD: False] [ANIME: False] [whichReg: ['standard']] Score: 5
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Retrieving episode object for S02E14
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Snatch history had a quality in it, using that: 1080p WEB-DL
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Quality of the episode we're processing: 1080p WEB-DL
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: This was manually downloaded but it appears to be better quality than what we have so I'm marking it as priority
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Is ep a priority download: True
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: There is no existing file so there's no worries about replacing it
2023-01-10 20:14:34 INFO :: POSTPROCESSOR-AUTO :: This download is marked a priority download so I'm going to replace an existing file if I find one
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Trying to determine free space on the destination drive
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Setter sets location to 
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Found release name A TV Show - S02E14 - Episode Name.1080p.AVC.EAC3.WEB-DL-METCON
2023-01-10 20:14:34 INFO :: POSTPROCESSOR-AUTO :: Using release for release name.
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Parsed A TV Show - S02E14 - Episode Name.1080p.AVC.EAC3.WEB-DL-METCON into A TV Show - S02E14 [GROUP: METCON] [ABD: False] [ANIME: False] [whichReg: ['standard']] Score: 5
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Found codec for 'A TV Show: Episode Name'.
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Episode has no release group, replacing it with 'METCON'
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: formatting pattern: %SN - S%0SE%0E - %EN.%SQ.N.%RT-%RG -> A TV Show - S02E14 - Episode Name.1080p.WEB.DL.h264-METCON
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Parsed A TV Show - S02E14 - Episode Name.1080p.AVC.EAC3.WEB-DL-METCON into A TV Show - S02E14 [GROUP: METCON] [ABD: False] [ANIME: False] [whichReg: ['standard']] Score: 5
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Found codec for 'A TV Show: Episode Name'.
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: formatting pattern: Season %0S -> Season 02
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Destination folder for this episode: \\serverpath\media\TV\A TV Show\Season 02
2023-01-10 20:14:34 DEBUG :: POSTPROCESSOR-AUTO :: Checking if the path \\serverpath\media\TV\A TV Show\Season 02 already exists
2023-01-10 20:14:35 DEBUG :: POSTPROCESSOR-AUTO :: Found the following associated files for X:\Path\A TV Show\Season 02\A TV Show - S02E14 - Episode Name.1080p.AVC.EAC3.WEB-DL-METCON.mkv: ['X:\\Path\\A TV Show\\Season 02\\A TV Show - S02E14 - Episode Name.1080p.AVC.EAC3.WEB-DL-METCON.sfv']
2023-01-10 20:14:35 DEBUG :: POSTPROCESSOR-AUTO :: Allowing associated files for X:\Path\A TV Show\Season 02\A TV Show - S02E14 - Episode Name.1080p.AVC.EAC3.WEB-DL-METCON.mkv: ['X:\\Path\\A TV Show\\Season 02\\A TV Show - S02E14 - Episode Name.1080p.AVC.EAC3.WEB-DL-METCON.sfv']
2023-01-10 20:14:35 DEBUG :: POSTPROCESSOR-AUTO :: Moving file from X:\Path\A TV Show\Season 02\A TV Show - S02E14 - Episode Name.1080p.AVC.EAC3.WEB-DL-METCON.mkv to \\serverpath\media\TV\A TV Show\Season 02\A TV Show - S02E14 - Episode Name.1080p.AVC.EAC3.WEB-DL-METCON.mkv
2023-01-10 20:14:38 DEBUG :: NOTIFICATIONS-DISCORD :: Task for 600 started
2023-01-10 20:14:38 INFO :: NOTIFICATIONS-DISCORD :: Sending discord message: Finished Download: A TV Show - 2x13 - daisy - 720p WEB-DL
2023-01-10 20:14:38 INFO :: NOTIFICATIONS-DISCORD :: Sending discord message to url: https://discordapp.com/api/webhooks/blahblah
2023-01-10 20:14:38 DEBUG :: NOTIFICATIONS-DISCORD :: Traceback (most recent call last):
  File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifications_queue.py", line 111, in run
    self.last_result = self._send_discord()
  File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifications_queue.py", line 148, in _send_discord
    raise error
  File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\notifications_queue.py", line 142, in _send_discord
    r.raise_for_status()
  File "C:\SickChill\Python3\tools\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://discordapp.com/api/webhooks/blahblah

```

**Comment by JustSomeGuyNZ** [comment]
Sorry, correct version is 2023.1.2, not 2022.10.13

**Comment by Wally73** [comment]
2023-01-10 15:40:49 DEBUG :: NOTIFICATIONS-DISCORD :: Traceback (most recent call last):
  File "G:\SickChill\lib\site-packages\sickchill\oldbeard\notifications_queue.py", line 111, in run
    self.last_result = self._send_discord()
  File "G:\SickChill\lib\site-packages\sickchill\oldbeard\notifications_queue.py", line 148, in _send_discord
    raise error
  File "G:\SickChill\lib\site-packages\sickchill\oldbeard\notifications_queue.py", line 142, in _send_discord
    r.raise_for_status()
  File "G:\SickChill\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://discord.com/api/webhooks/editedoutstuff

**Comment by BKSteve** [comment]
https://discord.com/developers/docs/reference may allude to the reason. Default is deprecated.

**Comment by godofjesters** [comment]
i'm noticing the same problem

**Comment by JustSomeGuyNZ** [comment]
Mine is no longer posting for snatch now either, although it appeared to have been doing so when I originally posted.

**Comment by miigotu** [comment]
We need to add `traceback.format_exc()` on
https://github.com/SickChill/sickchill/blob/37535f7277855a583f38e7da4c683350de9528c3/sickchill/oldbeard/notifications_queue.py#L148
And on
https://github.com/SickChill/sickchill/blob/37535f7277855a583f38e7da4c683350de9528c3/sickchill/oldbeard/notifications_queue.py#L157

I think that might tell us more of you reproduce the error with those two lines added.

**Comment by miigotu** [comment]
Likely, rewriting the notifier to use  https://github.com/lovvskillz/python-discord-webhook would be the best way to go about it. If I can get some time soon I will maybe do that, it should be fairly quick.

I also saw this https://pypi.org/project/python-logging-discord-handler/ which might be cool to share error logs to us in the discord, where most support is going to be provided as soon as all the guides/forums and stuff is set up there. A lot going on in discord!

**Comment by miigotu** [comment]
> Likely, rewriting the notifier to use  https://github.com/lovvskillz/python-discord-webhook ( python >= 3.8) would be the best way to go about it. If I can get some time soon I will maybe do that, it should be fairly quick. There is also https://pypi.org/project/discordwebhook (python >= 3.6)
> And
> https://pypi.org/project/discord.py/ (python >= 3.8)
> 
> I also saw this https://pypi.org/project/python-logging-discord-handler/ which might be cool to share error logs to us in the discord, where most support is going to be provided as soon as all the guides/forums and stuff is set up there. A lot going on in discord! 
>  

Totally forgot about this, I have been super busy.

**Comment by BKSteve** [comment]
Testing `snatch` and `post processing` were both successful using current `develop` branch.

```
INFO :: SEARCHQUEUE-MANUAL-350665 :: Downloading The.Rookie.S05E17.1080p.HEVC.x265-MeGusta from TorrentDay
---
DEBUG :: NOTIFICATIONS-DISCORD :: Task for 600 started
INFO :: NOTIFICATIONS-DISCORD :: Sending discord message: Started Download: The Rookie - 5x17 - The Enemy Within - 1080p HDTV from TorrentDay
INFO :: NOTIFICATIONS-DISCORD :: Sending discord message to url: https://discord.com/api/webhooks/--WebHookCut--
DEBUG :: NOTIFICATIONS-DISCORD :: Task for 600 completed


INFO :: POSTPROCESSOR-AUTO :: Auto post processing task for /home/stephenr/TVShow completed
DEBUG :: NOTIFICATIONS-DISCORD :: Task for 600 started
INFO :: NOTIFICATIONS-DISCORD :: Sending discord message: Finished Download: House - 2x16 - Safe - Unknown
INFO :: NOTIFICATIONS-DISCORD :: Sending discord message to url: https://discord.com/api/webhooks/--WebHookCut--
DEBUG :: NOTIFICATIONS-DISCORD :: Task for 600 completed
```
![image](https://user-images.githubusercontent.com/10173496/228254256-1df91536-61bf-4172-9905-ac481c9e8911.png)

**Comment by BKSteve** [comment]
Let me know if ok to close.
