### ISSUE TITLE
NZB splitting of season packs does not work

### ISSUE THREAD

**Issue by Rubio9** [SickChill/sickchill#8365]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: 2023.1.2
OS: Linux / Synology DSM7
Browser: Any
What you did: Force backlog search for a show where there is a season pack with missing episodes.
What happened: Logs show it finds the season pack and decides it will use it, but never does. Debug logs show it errors.
What you expected: Season pack's nzb to be split so the wanted episodes out of it are downloaded.
Logs:
```
2023-02-17 13:39:51 DEBUG :: SEARCHQUEUE-BACKLOG-xxxxx :: [nzb.su] :: Episode already exists with quality SDTV but the found result quality 1080p WEB-DL is wanted more, getting found result for xxxxx S01E06
2023-02-17 13:39:51 DEBUG :: SEARCHQUEUE-BACKLOG-xxxxx :: [nzb.su] :: Breaking apart the NZB and adding the individual ones to our results
2023-02-17 13:39:52 DEBUG :: SEARCHQUEUE-BACKLOG-xxxxx :: [nzb.su] :: Using cached parse result for: xxxxx.S01.1080p.WEB-DL.DD+.2.0.x264-xpost
2023-02-17 13:39:52 DEBUG :: SEARCHQUEUE-BACKLOG-xxxxx :: [nzb.su] :: Split out xxxxx.S01E06.xxxxx.1080p.WEB-DL from xxxxx.S01.1080p.WEB-DL.DD+.2.0.x264-xpost
2023-02-17 13:39:52 DEBUG :: SEARCHQUEUE-BACKLOG-xxxxx :: [nzb.su] :: Parsed xxxxx.S01E06.xxxxx.1080p.WEB-DL into xxxxx - S01E06 [ABD: False] [ANIME: False] [whichReg: ['standard']] Score: 5
2023-02-17 13:39:52 DEBUG :: SEARCHQUEUE-BACKLOG-xxxxx :: [nzb.su] :: Any,Best = [ 720p HDTV, 1080p HDTV, 720p WEB-DL, 1080p WEB-DL, 720p BluRay, 1080p BluRay ] [ 1080p WEB-DL ] Found = [ 1080p WEB-DL ]
2023-02-17 13:39:52 DEBUG :: SEARCHQUEUE-BACKLOG-xxxxx :: [nzb.su] :: Episode already exists with quality SDTV but the found result quality 1080p WEB-DL is wanted more, getting found result for xxxxx S01E06
2023-02-17 13:39:52 DEBUG :: SEARCHQUEUE-BACKLOG-xxxxx :: [nzb.su] :: Traceback (most recent call last):
  File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/oldbeard/search_queue.py", line 213, in run
    searchResult = search.searchProviders(self.show, self.segment, False)
  File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/oldbeard/search.py", line 557, in searchProviders
    individualResults = nzbSplitter.split_result(bestSeasonResult)
  File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/oldbeard/nzbSplitter.py", line 185, in split_result
    cur_obj.extraInfo = [create_nzb_string(separate_nzbs[new_nzb], xmlns)]
  File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/oldbeard/nzbSplitter.py", line 83, in create_nzb_string
    root_element.append(strip_xmlns(cur_file, xmlns))
  File "/volume1/@appstore/sickchill/env/lib/python3.10/site-packages/sickchill/oldbeard/nzbSplitter.py", line 112, in strip_xmlns
    for cur_child in element.getchildren():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

**Comment by miigotu** [comment]
Thanks for fixing this. It isn't often someone makes a big report and then fixes the issue themselves anymore, it's a great quality and way to handle it!
