### ISSUE TITLE
Error on Searching for an episode, I believe SSL problem?

### ISSUE THREAD

**Issue by Blinkz** [SickChill/sickchill#8463]
## Notice:
The issue tracker, wiki,and discussions tab on GitHub is going to be archived/disabled in the near future for SickChill. All issues, discussions, support, guides, feature requests, and communication will be handled on [discord](https://discord.gg/FXre9qkHwE). Please consider raising your issue there instead. 

## Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: 2023.5.30
OS: Windows 10
Browser: Firefox
What you did: Search for episode
What happened: a long list of errors that doesn't seem to be handled by sickchill so not sure what the issue is...
What you expected: To at least have sickchill handle the error so can see what the issue is. I believe possibly SSL? I've tried deselecting verify SSL, along with a clean uninstall and reinstall of sickchill....
Logs:
```
023-06-05 10:05:08 INFO :: SEARCHQUEUE-MANUAL-290853 :: Unable to find a download for: [Fear the Walking Dead - S08E04 - King County]
2023-06-05 10:05:08 INFO :: SEARCHQUEUE-MANUAL-290853 :: [ThePirateBay] :: Performing season pack search for Fear the Walking Dead
AA requests.exceptions.SSLError: HTTPSConnectionPool(host='apibay.org', port=443): Max retries exceeded with url: /q.php?cat=208%2C205&q=Fear+the+Walking+Dead+S08E04 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))
AA raise SSLError(e, request=request)
AA File "C:\SickChill\Python3\tools\lib\site-packages\requests\adapters.py", line 563, in send
AA resp = super().send(request, **kw)
AA File "C:\Windows\system32\config\systemprofile\AppData\Roaming\Python\Python38\site-packages\cacheyou\adapter.py", line 72, in send
AA r = adapter.send(request, **kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\requests\sessions.py", line 701, in send
AA resp = self.send(prep, **send_kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\requests\sessions.py", line 587, in request
AA response = session.request(
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\helpers.py", line 1243, in getURL
AA raise requests_exception
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\helpers.py", line 1398, in handle_requests_exception
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='apibay.org', port=443): Max retries exceeded with url: /q.php?cat=208%2C205&q=Fear+the+Walking+Dead+S08E04 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))
AA raise MaxRetryError(_pool, url, error or ResponseError(cause))
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\util\retry.py", line 592, in increment
AA retries = retries.increment(
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
AA resp = conn.urlopen(
AA File "C:\SickChill\Python3\tools\lib\site-packages\requests\adapters.py", line 489, in send
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)
AA self._sslobj.do_handshake()
AA File "C:\SickChill\Python3\tools\lib\ssl.py", line 1309, in do_handshake
AA self.do_handshake()
AA File "C:\SickChill\Python3\tools\lib\ssl.py", line 1040, in _create
AA return self.sslsocket_class._create(
AA File "C:\SickChill\Python3\tools\lib\ssl.py", line 500, in wrap_socket
AA return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
AA ssl_sock = _ssl_wrap_socket_impl(
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
AA self.sock = ssl_wrap_socket(
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connection.py", line 414, in connect
AA conn.connect()
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
AA self._validate_conn(conn)
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
AA httplib_response = self._make_request(
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
AA requests.exceptions.SSLError: HTTPSConnectionPool(host='apibay.org', port=443): Max retries exceeded with url: /q.php?cat=208%2C205&q=fear+the+walking+dead+S08E04 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))
AA raise SSLError(e, request=request)
AA File "C:\SickChill\Python3\tools\lib\site-packages\requests\adapters.py", line 563, in send
AA resp = super().send(request, **kw)
AA File "C:\Windows\system32\config\systemprofile\AppData\Roaming\Python\Python38\site-packages\cacheyou\adapter.py", line 72, in send
AA r = adapter.send(request, **kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\requests\sessions.py", line 701, in send
AA resp = self.send(prep, **send_kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\requests\sessions.py", line 587, in request
AA response = session.request(
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\helpers.py", line 1243, in getURL
AA raise requests_exception
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\helpers.py", line 1398, in handle_requests_exception
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='apibay.org', port=443): Max retries exceeded with url: /q.php?cat=208%2C205&q=fear+the+walking+dead+S08E04 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))
AA raise MaxRetryError(_pool, url, error or ResponseError(cause))
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\util\retry.py", line 592, in increment
AA retries = retries.increment(
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
AA resp = conn.urlopen(
AA File "C:\SickChill\Python3\tools\lib\site-packages\requests\adapters.py", line 489, in send
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)
AA self._sslobj.do_handshake()
AA File "C:\SickChill\Python3\tools\lib\ssl.py", line 1309, in do_handshake
AA self.do_handshake()
AA File "C:\SickChill\Python3\tools\lib\ssl.py", line 1040, in _create
AA return self.sslsocket_class._create(
AA File "C:\SickChill\Python3\tools\lib\ssl.py", line 500, in wrap_socket
AA return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
AA ssl_sock = _ssl_wrap_socket_impl(
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
AA self.sock = ssl_wrap_socket(
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connection.py", line 414, in connect
AA conn.connect()
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
AA self._validate_conn(conn)
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
AA httplib_response = self._make_request(
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
AA requests.exceptions.SSLError: HTTPSConnectionPool(host='apibay.org', port=443): Max retries exceeded with url: /q.php?cat=208%2C205&q=tt3743822 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))
AA raise SSLError(e, request=request)
AA File "C:\SickChill\Python3\tools\lib\site-packages\requests\adapters.py", line 563, in send
AA resp = super().send(request, **kw)
AA File "C:\Windows\system32\config\systemprofile\AppData\Roaming\Python\Python38\site-packages\cacheyou\adapter.py", line 72, in send
AA r = adapter.send(request, **kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\requests\sessions.py", line 701, in send
AA resp = self.send(prep, **send_kwargs)
AA File "C:\SickChill\Python3\tools\lib\site-packages\requests\sessions.py", line 587, in request
AA response = session.request(
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\helpers.py", line 1243, in getURL
AA raise requests_exception
AA File "C:\SickChill\Python3\tools\lib\site-packages\sickchill\oldbeard\helpers.py", line 1398, in handle_requests_exception
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='apibay.org', port=443): Max retries exceeded with url: /q.php?cat=208%2C205&q=tt3743822 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))
AA raise MaxRetryError(_pool, url, error or ResponseError(cause))
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\util\retry.py", line 592, in increment
AA retries = retries.increment(
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
AA resp = conn.urlopen(
AA File "C:\SickChill\Python3\tools\lib\site-packages\requests\adapters.py", line 489, in send
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)
AA self._sslobj.do_handshake()
AA File "C:\SickChill\Python3\tools\lib\ssl.py", line 1309, in do_handshake
AA self.do_handshake()
AA File "C:\SickChill\Python3\tools\lib\ssl.py", line 1040, in _create
AA return self.sslsocket_class._create(
AA File "C:\SickChill\Python3\tools\lib\ssl.py", line 500, in wrap_socket
AA return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
AA ssl_sock = _ssl_wrap_socket_impl(
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
AA self.sock = ssl_wrap_socket(
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connection.py", line 414, in connect
AA conn.connect()
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
AA self._validate_conn(conn)
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
AA httplib_response = self._make_request(
AA File "C:\SickChill\Python3\tools\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
2023-06-05 10:05:07 INFO :: SEARCHQUEUE-MANUAL-290853 :: [ThePirateBay] :: Performing episode search for Fear the Walking Dead
2023-06-05 10:05:07 INFO :: SEARCHQUEUE-MANUAL-290853 :: [Rarbg] :: Performing season pack search for Fear the Walking Dead
2023-06-05 10:05:07 WARNING :: SEARCHQUEUE-MANUAL-290853 :: [Rarbg] :: Unable to connect to provider
2023-06-05 10:05:07 INFO :: SEARCHQUEUE-MANUAL-290853 :: [Rarbg] :: Request failed: 521 Server Error:  for url: http://torrentapi.org/pubapi_v2.php?get_token=get_token&format=json&app_id=sickchill (HTTPError)
2023-06-05 10:05:07 INFO :: SEARCHQUEUE-MANUAL-290853 :: [Rarbg] :: Performing episode search for Fear the Walking Dead
2023-06-05 10:05:07 WARNING :: SEARCHQUEUE-MANUAL-290853 :: [Rarbg] :: Unable to connect to provider
2023-06-05 10:05:07 INFO :: SEARCHQUEUE-MANUAL-290853 :: [Rarbg] :: Request failed: 521 Server Error:  for url: http://torrentapi.org/pubapi_v2.php?get_token=get_token&format=json&app_id=sickchill (HTTPError)
2023-06-05 10:05:07 INFO :: SEARCHQUEUE-MANUAL-290853 :: Beginning manual search for: [Fear the Walking Dead - S08E04 - King County]
```

**Comment by miigotu** [comment]
Rarbg is no longer in service. Also, please read the top of the issue here, we only use discord now
