### ISSUE TITLE
ModuleNotFoundError: No module named 'cachecontrol'

### ISSUE THREAD

**Issue by tobidoo** [SickChill/sickchill#8466]
## Notice:
The issue tracker, wiki,and discussions tab on GitHub is going to be archived/disabled in the near future for SickChill. All issues, discussions, support, guides, feature requests, and communication will be handled on [discord](https://discord.gg/FXre9qkHwE). Please consider raising your issue there instead. 

## Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: latest
OS: Unraid
Browser: Any
What you did: Tried to start sickchill
What happened: No gui.
What you expected: gui
Logs:
```

Traceback (most recent call last):
  File "/usr/bin/SickChill", line 5, in <module>
    from SickChill import main
  File "/config/.local/lib/python3.10/site-packages/SickChill.py", line 14, in <module>
    import sickchill.start
  File "/config/.local/lib/python3.10/site-packages/sickchill/__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "/config/.local/lib/python3.10/site-packages/sickchill/show/indexers/__init__.py", line 1, in <module>
    from .handler import ShowIndexer
  File "/config/.local/lib/python3.10/site-packages/sickchill/show/indexers/handler.py", line 5, in <module>
    from sickchill.tv import Show, TVEpisode
  File "/config/.local/lib/python3.10/site-packages/sickchill/tv.py", line 20, in <module>
    import sickchill.oldbeard.providers
  File "/config/.local/lib/python3.10/site-packages/sickchill/oldbeard/providers/__init__.py", line 4, in <module>
    import sickchill.oldbeard.helpers
  File "/config/.local/lib/python3.10/site-packages/sickchill/oldbeard/helpers.py", line 31, in <module>
    from cachecontrol import CacheControl
ModuleNotFoundError: No module named 'cachecontrol'

```
This just keeps repeating.
I've recently switched cache drive. 
No other problems except with sickchill.

**Comment by BKSteve** [comment]
https://discord.com/channels/502612977271439372/1116210715267702794/1116210715267702794
