### ISSUE TITLE
[APP SUBMITTED]: Valid User Account Required

### ISSUE THREAD

**Issue by avexel** [SickChill/sickchill#8609]
### INFO
Python Version: **3.11.6 (main, Oct  4 2023, 06:22:18) [GCC 12.2.1 20220924]**
Operating System: **Linux-5.19.17-Unraid-x86_64-with**
Locale: None
Version: **2023.6.27**
No Log available with ERRORS:
### ERROR
```
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/sickchill/views/manage/add_shows.py", line 364, in favoriteShows
    favorite_shows = favorites.fetch_indexer_favorites()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/sickchill/show/recommendations/favorites.py", line 17, in fetch_indexer_favorites
    indexer_favorites = sickchill.indexer.get_indexer_favorites()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/sickchill/show/indexers/handler.py", line 186, in get_indexer_favorites
    results.extend(indexer.get_favorites())
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/sickchill/show/indexers/tvdb.py", line 231, in get_favorites
    for tvdbid in user.favorites():
                  ^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/tvdbsimple/user.py", line 81, in favorites
    response = self._GET(path)
               ^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/tvdbsimple/base.py", line 149, in _GET
    return self._request('GET', path, params=params, cleanJson=cleanJson)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/tvdbsimple/base.py", line 126, in _request
    self._set_token_header(forceNewToken)
  File "/lsiopy/lib/python3.11/site-packages/tvdbsimple/base.py", line 91, in _set_token_header
    self._headers['Authorization'] = 'Bearer ' + self.get_token(forceNew)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/tvdbsimple/base.py", line 122, in get_token
    raise AuthenticationError(error)
tvdbsimple.base.AuthenticationError: Valid User Account Required

```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
Set a proper user token for tvdb in sickchill settings.
